import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 39000-39999 -/

equation 39000 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ y) ◇ x
equation 39001 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ y) ◇ y
equation 39002 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ y) ◇ z
equation 39003 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ z) ◇ x
equation 39004 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ z) ◇ y
equation 39005 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ z) ◇ z
equation 39006 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ z) ◇ w
equation 39007 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ x) ◇ x
equation 39008 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ x) ◇ y
equation 39009 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ x) ◇ z
equation 39010 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ x) ◇ w
equation 39011 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ y) ◇ x
equation 39012 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ y) ◇ y
equation 39013 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ y) ◇ z
equation 39014 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ y) ◇ w
equation 39015 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ z) ◇ x
equation 39016 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ z) ◇ y
equation 39017 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ z) ◇ z
equation 39018 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ z) ◇ w
equation 39019 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ w) ◇ x
equation 39020 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ w) ◇ y
equation 39021 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ w) ◇ z
equation 39022 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ w) ◇ w
equation 39023 := x = (((x ◇ y) ◇ (y ◇ z)) ◇ w) ◇ u
equation 39024 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ x) ◇ x
equation 39025 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ x) ◇ y
equation 39026 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ x) ◇ z
equation 39027 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ x) ◇ w
equation 39028 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ y) ◇ x
equation 39029 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ y) ◇ y
equation 39030 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ y) ◇ z
equation 39031 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ y) ◇ w
equation 39032 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ z) ◇ x
equation 39033 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ z) ◇ y
equation 39034 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ z) ◇ z
equation 39035 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ z) ◇ w
equation 39036 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ w) ◇ x
equation 39037 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ w) ◇ y
equation 39038 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ w) ◇ z
equation 39039 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ w) ◇ w
equation 39040 := x = (((x ◇ y) ◇ (z ◇ x)) ◇ w) ◇ u
equation 39041 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ x) ◇ x
equation 39042 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ x) ◇ y
equation 39043 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ x) ◇ z
equation 39044 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ x) ◇ w
equation 39045 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ y) ◇ x
equation 39046 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ y) ◇ y
equation 39047 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ y) ◇ z
equation 39048 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ y) ◇ w
equation 39049 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ z) ◇ x
equation 39050 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ z) ◇ y
equation 39051 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ z) ◇ z
equation 39052 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ z) ◇ w
equation 39053 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ w) ◇ x
equation 39054 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ w) ◇ y
equation 39055 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ w) ◇ z
equation 39056 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ w) ◇ w
equation 39057 := x = (((x ◇ y) ◇ (z ◇ y)) ◇ w) ◇ u
equation 39058 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ x) ◇ x
equation 39059 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ x) ◇ y
equation 39060 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ x) ◇ z
equation 39061 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ x) ◇ w
equation 39062 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ y) ◇ x
equation 39063 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ y) ◇ y
equation 39064 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ y) ◇ z
equation 39065 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ y) ◇ w
equation 39066 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ z) ◇ x
equation 39067 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ z) ◇ y
equation 39068 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ z) ◇ z
equation 39069 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ z) ◇ w
equation 39070 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ w) ◇ x
equation 39071 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ w) ◇ y
equation 39072 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ w) ◇ z
equation 39073 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ w) ◇ w
equation 39074 := x = (((x ◇ y) ◇ (z ◇ z)) ◇ w) ◇ u
equation 39075 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ x) ◇ x
equation 39076 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ x) ◇ y
equation 39077 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ x) ◇ z
equation 39078 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ x) ◇ w
equation 39079 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ x) ◇ u
equation 39080 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ y) ◇ x
equation 39081 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ y) ◇ y
equation 39082 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ y) ◇ z
equation 39083 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ y) ◇ w
equation 39084 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ y) ◇ u
equation 39085 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ z) ◇ x
equation 39086 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ z) ◇ y
equation 39087 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ z) ◇ z
equation 39088 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ z) ◇ w
equation 39089 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ z) ◇ u
equation 39090 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ w) ◇ x
equation 39091 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ w) ◇ y
equation 39092 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ w) ◇ z
equation 39093 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ w) ◇ w
equation 39094 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ w) ◇ u
equation 39095 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ x
equation 39096 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ y
equation 39097 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ z
equation 39098 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ w
equation 39099 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ u
equation 39100 := x = (((x ◇ y) ◇ (z ◇ w)) ◇ u) ◇ v
equation 39101 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ x) ◇ x
equation 39102 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ x) ◇ y
equation 39103 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ x) ◇ z
equation 39104 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ y) ◇ x
equation 39105 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ y) ◇ y
equation 39106 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ y) ◇ z
equation 39107 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ z) ◇ x
equation 39108 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ z) ◇ y
equation 39109 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ z) ◇ z
equation 39110 := x = (((y ◇ x) ◇ (x ◇ x)) ◇ z) ◇ w
equation 39111 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ x) ◇ x
equation 39112 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ x) ◇ y
equation 39113 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ x) ◇ z
equation 39114 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ y) ◇ x
equation 39115 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ y) ◇ y
equation 39116 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ y) ◇ z
equation 39117 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ z) ◇ x
equation 39118 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ z) ◇ y
equation 39119 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ z) ◇ z
equation 39120 := x = (((y ◇ x) ◇ (x ◇ y)) ◇ z) ◇ w
equation 39121 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ x) ◇ x
equation 39122 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ x) ◇ y
equation 39123 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ x) ◇ z
equation 39124 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ x) ◇ w
equation 39125 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ y) ◇ x
equation 39126 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ y) ◇ y
equation 39127 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ y) ◇ z
equation 39128 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ y) ◇ w
equation 39129 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ z) ◇ x
equation 39130 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ z) ◇ y
equation 39131 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ z) ◇ z
equation 39132 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ z) ◇ w
equation 39133 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ w) ◇ x
equation 39134 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ w) ◇ y
equation 39135 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ w) ◇ z
equation 39136 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ w) ◇ w
equation 39137 := x = (((y ◇ x) ◇ (x ◇ z)) ◇ w) ◇ u
equation 39138 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ x) ◇ x
equation 39139 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ x) ◇ y
equation 39140 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ x) ◇ z
equation 39141 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ y) ◇ x
equation 39142 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ y) ◇ y
equation 39143 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ y) ◇ z
equation 39144 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ z) ◇ x
equation 39145 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ z) ◇ y
equation 39146 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ z) ◇ z
equation 39147 := x = (((y ◇ x) ◇ (y ◇ x)) ◇ z) ◇ w
equation 39148 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ x) ◇ x
equation 39149 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ x) ◇ y
equation 39150 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ x) ◇ z
equation 39151 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ y) ◇ x
equation 39152 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ y) ◇ y
equation 39153 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ y) ◇ z
equation 39154 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ z) ◇ x
equation 39155 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ z) ◇ y
equation 39156 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ z) ◇ z
equation 39157 := x = (((y ◇ x) ◇ (y ◇ y)) ◇ z) ◇ w
equation 39158 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ x) ◇ x
equation 39159 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ x) ◇ y
equation 39160 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ x) ◇ z
equation 39161 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ x) ◇ w
equation 39162 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ y) ◇ x
equation 39163 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ y) ◇ y
equation 39164 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ y) ◇ z
equation 39165 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ y) ◇ w
equation 39166 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ z) ◇ x
equation 39167 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ z) ◇ y
equation 39168 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ z) ◇ z
equation 39169 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ z) ◇ w
equation 39170 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ w) ◇ x
equation 39171 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ w) ◇ y
equation 39172 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ w) ◇ z
equation 39173 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ w) ◇ w
equation 39174 := x = (((y ◇ x) ◇ (y ◇ z)) ◇ w) ◇ u
equation 39175 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ x) ◇ x
equation 39176 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ x) ◇ y
equation 39177 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ x) ◇ z
equation 39178 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ x) ◇ w
equation 39179 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ y) ◇ x
equation 39180 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ y) ◇ y
equation 39181 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ y) ◇ z
equation 39182 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ y) ◇ w
equation 39183 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ z) ◇ x
equation 39184 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ z) ◇ y
equation 39185 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ z) ◇ z
equation 39186 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ z) ◇ w
equation 39187 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ w) ◇ x
equation 39188 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ w) ◇ y
equation 39189 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ w) ◇ z
equation 39190 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ w) ◇ w
equation 39191 := x = (((y ◇ x) ◇ (z ◇ x)) ◇ w) ◇ u
equation 39192 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ x) ◇ x
equation 39193 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ x) ◇ y
equation 39194 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ x) ◇ z
equation 39195 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ x) ◇ w
equation 39196 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ y) ◇ x
equation 39197 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ y) ◇ y
equation 39198 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ y) ◇ z
equation 39199 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ y) ◇ w
equation 39200 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ z) ◇ x
equation 39201 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ z) ◇ y
equation 39202 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ z) ◇ z
equation 39203 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ z) ◇ w
equation 39204 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ w) ◇ x
equation 39205 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ w) ◇ y
equation 39206 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ w) ◇ z
equation 39207 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ w) ◇ w
equation 39208 := x = (((y ◇ x) ◇ (z ◇ y)) ◇ w) ◇ u
equation 39209 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ x) ◇ x
equation 39210 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ x) ◇ y
equation 39211 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ x) ◇ z
equation 39212 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ x) ◇ w
equation 39213 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ y) ◇ x
equation 39214 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ y) ◇ y
equation 39215 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ y) ◇ z
equation 39216 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ y) ◇ w
equation 39217 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ z) ◇ x
equation 39218 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ z) ◇ y
equation 39219 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ z) ◇ z
equation 39220 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ z) ◇ w
equation 39221 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ w) ◇ x
equation 39222 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ w) ◇ y
equation 39223 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ w) ◇ z
equation 39224 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ w) ◇ w
equation 39225 := x = (((y ◇ x) ◇ (z ◇ z)) ◇ w) ◇ u
equation 39226 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ x) ◇ x
equation 39227 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ x) ◇ y
equation 39228 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ x) ◇ z
equation 39229 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ x) ◇ w
equation 39230 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ x) ◇ u
equation 39231 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ y) ◇ x
equation 39232 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ y) ◇ y
equation 39233 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ y) ◇ z
equation 39234 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ y) ◇ w
equation 39235 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ y) ◇ u
equation 39236 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ z) ◇ x
equation 39237 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ z) ◇ y
equation 39238 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ z) ◇ z
equation 39239 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ z) ◇ w
equation 39240 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ z) ◇ u
equation 39241 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ w) ◇ x
equation 39242 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ w) ◇ y
equation 39243 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ w) ◇ z
equation 39244 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ w) ◇ w
equation 39245 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ w) ◇ u
equation 39246 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ x
equation 39247 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ y
equation 39248 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ z
equation 39249 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ w
equation 39250 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ u
equation 39251 := x = (((y ◇ x) ◇ (z ◇ w)) ◇ u) ◇ v
equation 39252 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ x) ◇ x
equation 39253 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ x) ◇ y
equation 39254 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ x) ◇ z
equation 39255 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ y) ◇ x
equation 39256 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ y) ◇ y
equation 39257 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ y) ◇ z
equation 39258 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ z) ◇ x
equation 39259 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ z) ◇ y
equation 39260 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ z) ◇ z
equation 39261 := x = (((y ◇ y) ◇ (x ◇ x)) ◇ z) ◇ w
equation 39262 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ x) ◇ x
equation 39263 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ x) ◇ y
equation 39264 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ x) ◇ z
equation 39265 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ y) ◇ x
equation 39266 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ y) ◇ y
equation 39267 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ y) ◇ z
equation 39268 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ z) ◇ x
equation 39269 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ z) ◇ y
equation 39270 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ z) ◇ z
equation 39271 := x = (((y ◇ y) ◇ (x ◇ y)) ◇ z) ◇ w
equation 39272 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ x) ◇ x
equation 39273 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ x) ◇ y
equation 39274 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ x) ◇ z
equation 39275 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ x) ◇ w
equation 39276 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ y) ◇ x
equation 39277 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ y) ◇ y
equation 39278 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ y) ◇ z
equation 39279 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ y) ◇ w
equation 39280 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ z) ◇ x
equation 39281 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ z) ◇ y
equation 39282 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ z) ◇ z
equation 39283 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ z) ◇ w
equation 39284 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ w) ◇ x
equation 39285 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ w) ◇ y
equation 39286 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ w) ◇ z
equation 39287 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ w) ◇ w
equation 39288 := x = (((y ◇ y) ◇ (x ◇ z)) ◇ w) ◇ u
equation 39289 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ x) ◇ x
equation 39290 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ x) ◇ y
equation 39291 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ x) ◇ z
equation 39292 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ y) ◇ x
equation 39293 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ y) ◇ y
equation 39294 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ y) ◇ z
equation 39295 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ z) ◇ x
equation 39296 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ z) ◇ y
equation 39297 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ z) ◇ z
equation 39298 := x = (((y ◇ y) ◇ (y ◇ x)) ◇ z) ◇ w
equation 39299 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ x) ◇ x
equation 39300 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ x) ◇ y
equation 39301 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ x) ◇ z
equation 39302 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ y) ◇ x
equation 39303 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ y) ◇ y
equation 39304 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ y) ◇ z
equation 39305 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ z) ◇ x
equation 39306 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ z) ◇ y
equation 39307 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ z) ◇ z
equation 39308 := x = (((y ◇ y) ◇ (y ◇ y)) ◇ z) ◇ w
equation 39309 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ x) ◇ x
equation 39310 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ x) ◇ y
equation 39311 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ x) ◇ z
equation 39312 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ x) ◇ w
equation 39313 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ y) ◇ x
equation 39314 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ y) ◇ y
equation 39315 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ y) ◇ z
equation 39316 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ y) ◇ w
equation 39317 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ z) ◇ x
equation 39318 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ z) ◇ y
equation 39319 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ z) ◇ z
equation 39320 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ z) ◇ w
equation 39321 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ w) ◇ x
equation 39322 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ w) ◇ y
equation 39323 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ w) ◇ z
equation 39324 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ w) ◇ w
equation 39325 := x = (((y ◇ y) ◇ (y ◇ z)) ◇ w) ◇ u
equation 39326 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ x) ◇ x
equation 39327 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ x) ◇ y
equation 39328 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ x) ◇ z
equation 39329 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ x) ◇ w
equation 39330 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ y) ◇ x
equation 39331 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ y) ◇ y
equation 39332 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ y) ◇ z
equation 39333 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ y) ◇ w
equation 39334 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ z) ◇ x
equation 39335 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ z) ◇ y
equation 39336 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ z) ◇ z
equation 39337 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ z) ◇ w
equation 39338 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ w) ◇ x
equation 39339 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ w) ◇ y
equation 39340 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ w) ◇ z
equation 39341 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ w) ◇ w
equation 39342 := x = (((y ◇ y) ◇ (z ◇ x)) ◇ w) ◇ u
equation 39343 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ x) ◇ x
equation 39344 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ x) ◇ y
equation 39345 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ x) ◇ z
equation 39346 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ x) ◇ w
equation 39347 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ y) ◇ x
equation 39348 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ y) ◇ y
equation 39349 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ y) ◇ z
equation 39350 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ y) ◇ w
equation 39351 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ z) ◇ x
equation 39352 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ z) ◇ y
equation 39353 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ z) ◇ z
equation 39354 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ z) ◇ w
equation 39355 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ w) ◇ x
equation 39356 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ w) ◇ y
equation 39357 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ w) ◇ z
equation 39358 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ w) ◇ w
equation 39359 := x = (((y ◇ y) ◇ (z ◇ y)) ◇ w) ◇ u
equation 39360 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ x) ◇ x
equation 39361 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ x) ◇ y
equation 39362 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ x) ◇ z
equation 39363 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ x) ◇ w
equation 39364 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ y) ◇ x
equation 39365 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ y) ◇ y
equation 39366 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ y) ◇ z
equation 39367 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ y) ◇ w
equation 39368 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ z) ◇ x
equation 39369 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ z) ◇ y
equation 39370 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ z) ◇ z
equation 39371 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ z) ◇ w
equation 39372 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ w) ◇ x
equation 39373 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ w) ◇ y
equation 39374 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ w) ◇ z
equation 39375 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ w) ◇ w
equation 39376 := x = (((y ◇ y) ◇ (z ◇ z)) ◇ w) ◇ u
equation 39377 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ x) ◇ x
equation 39378 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ x) ◇ y
equation 39379 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ x) ◇ z
equation 39380 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ x) ◇ w
equation 39381 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ x) ◇ u
equation 39382 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ y) ◇ x
equation 39383 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ y) ◇ y
equation 39384 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ y) ◇ z
equation 39385 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ y) ◇ w
equation 39386 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ y) ◇ u
equation 39387 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ z) ◇ x
equation 39388 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ z) ◇ y
equation 39389 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ z) ◇ z
equation 39390 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ z) ◇ w
equation 39391 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ z) ◇ u
equation 39392 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ w) ◇ x
equation 39393 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ w) ◇ y
equation 39394 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ w) ◇ z
equation 39395 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ w) ◇ w
equation 39396 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ w) ◇ u
equation 39397 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ x
equation 39398 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ y
equation 39399 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ z
equation 39400 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ w
equation 39401 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ u
equation 39402 := x = (((y ◇ y) ◇ (z ◇ w)) ◇ u) ◇ v
equation 39403 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ x) ◇ x
equation 39404 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ x) ◇ y
equation 39405 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ x) ◇ z
equation 39406 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ x) ◇ w
equation 39407 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ y) ◇ x
equation 39408 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ y) ◇ y
equation 39409 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ y) ◇ z
equation 39410 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ y) ◇ w
equation 39411 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ z) ◇ x
equation 39412 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ z) ◇ y
equation 39413 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ z) ◇ z
equation 39414 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ z) ◇ w
equation 39415 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ w) ◇ x
equation 39416 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ w) ◇ y
equation 39417 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ w) ◇ z
equation 39418 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ w) ◇ w
equation 39419 := x = (((y ◇ z) ◇ (x ◇ x)) ◇ w) ◇ u
equation 39420 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ x) ◇ x
equation 39421 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ x) ◇ y
equation 39422 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ x) ◇ z
equation 39423 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ x) ◇ w
equation 39424 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ y) ◇ x
equation 39425 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ y) ◇ y
equation 39426 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ y) ◇ z
equation 39427 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ y) ◇ w
equation 39428 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ z) ◇ x
equation 39429 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ z) ◇ y
equation 39430 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ z) ◇ z
equation 39431 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ z) ◇ w
equation 39432 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ w) ◇ x
equation 39433 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ w) ◇ y
equation 39434 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ w) ◇ z
equation 39435 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ w) ◇ w
equation 39436 := x = (((y ◇ z) ◇ (x ◇ y)) ◇ w) ◇ u
equation 39437 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ x) ◇ x
equation 39438 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ x) ◇ y
equation 39439 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ x) ◇ z
equation 39440 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ x) ◇ w
equation 39441 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ y) ◇ x
equation 39442 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ y) ◇ y
equation 39443 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ y) ◇ z
equation 39444 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ y) ◇ w
equation 39445 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ z) ◇ x
equation 39446 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ z) ◇ y
equation 39447 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ z) ◇ z
equation 39448 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ z) ◇ w
equation 39449 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ w) ◇ x
equation 39450 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ w) ◇ y
equation 39451 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ w) ◇ z
equation 39452 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ w) ◇ w
equation 39453 := x = (((y ◇ z) ◇ (x ◇ z)) ◇ w) ◇ u
equation 39454 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ x) ◇ x
equation 39455 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ x) ◇ y
equation 39456 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ x) ◇ z
equation 39457 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ x) ◇ w
equation 39458 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ x) ◇ u
equation 39459 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ y) ◇ x
equation 39460 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ y) ◇ y
equation 39461 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ y) ◇ z
equation 39462 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ y) ◇ w
equation 39463 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ y) ◇ u
equation 39464 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ z) ◇ x
equation 39465 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ z) ◇ y
equation 39466 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ z) ◇ z
equation 39467 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ z) ◇ w
equation 39468 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ z) ◇ u
equation 39469 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ w) ◇ x
equation 39470 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ w) ◇ y
equation 39471 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ w) ◇ z
equation 39472 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ w) ◇ w
equation 39473 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ w) ◇ u
equation 39474 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ x
equation 39475 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ y
equation 39476 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ z
equation 39477 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ w
equation 39478 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ u
equation 39479 := x = (((y ◇ z) ◇ (x ◇ w)) ◇ u) ◇ v
equation 39480 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ x) ◇ x
equation 39481 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ x) ◇ y
equation 39482 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ x) ◇ z
equation 39483 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ x) ◇ w
equation 39484 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ y) ◇ x
equation 39485 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ y) ◇ y
equation 39486 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ y) ◇ z
equation 39487 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ y) ◇ w
equation 39488 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ z) ◇ x
equation 39489 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ z) ◇ y
equation 39490 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ z) ◇ z
equation 39491 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ z) ◇ w
equation 39492 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ w) ◇ x
equation 39493 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ w) ◇ y
equation 39494 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ w) ◇ z
equation 39495 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ w) ◇ w
equation 39496 := x = (((y ◇ z) ◇ (y ◇ x)) ◇ w) ◇ u
equation 39497 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ x) ◇ x
equation 39498 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ x) ◇ y
equation 39499 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ x) ◇ z
equation 39500 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ x) ◇ w
equation 39501 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ y) ◇ x
equation 39502 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ y) ◇ y
equation 39503 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ y) ◇ z
equation 39504 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ y) ◇ w
equation 39505 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ z) ◇ x
equation 39506 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ z) ◇ y
equation 39507 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ z) ◇ z
equation 39508 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ z) ◇ w
equation 39509 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ w) ◇ x
equation 39510 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ w) ◇ y
equation 39511 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ w) ◇ z
equation 39512 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ w) ◇ w
equation 39513 := x = (((y ◇ z) ◇ (y ◇ y)) ◇ w) ◇ u
equation 39514 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ x) ◇ x
equation 39515 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ x) ◇ y
equation 39516 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ x) ◇ z
equation 39517 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ x) ◇ w
equation 39518 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ y) ◇ x
equation 39519 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ y) ◇ y
equation 39520 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ y) ◇ z
equation 39521 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ y) ◇ w
equation 39522 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ z) ◇ x
equation 39523 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ z) ◇ y
equation 39524 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ z) ◇ z
equation 39525 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ z) ◇ w
equation 39526 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ w) ◇ x
equation 39527 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ w) ◇ y
equation 39528 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ w) ◇ z
equation 39529 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ w) ◇ w
equation 39530 := x = (((y ◇ z) ◇ (y ◇ z)) ◇ w) ◇ u
equation 39531 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ x) ◇ x
equation 39532 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ x) ◇ y
equation 39533 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ x) ◇ z
equation 39534 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ x) ◇ w
equation 39535 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ x) ◇ u
equation 39536 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ y) ◇ x
equation 39537 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ y) ◇ y
equation 39538 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ y) ◇ z
equation 39539 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ y) ◇ w
equation 39540 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ y) ◇ u
equation 39541 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ z) ◇ x
equation 39542 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ z) ◇ y
equation 39543 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ z) ◇ z
equation 39544 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ z) ◇ w
equation 39545 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ z) ◇ u
equation 39546 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ w) ◇ x
equation 39547 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ w) ◇ y
equation 39548 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ w) ◇ z
equation 39549 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ w) ◇ w
equation 39550 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ w) ◇ u
equation 39551 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ x
equation 39552 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ y
equation 39553 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ z
equation 39554 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ w
equation 39555 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ u
equation 39556 := x = (((y ◇ z) ◇ (y ◇ w)) ◇ u) ◇ v
equation 39557 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ x) ◇ x
equation 39558 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ x) ◇ y
equation 39559 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ x) ◇ z
equation 39560 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ x) ◇ w
equation 39561 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ y) ◇ x
equation 39562 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ y) ◇ y
equation 39563 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ y) ◇ z
equation 39564 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ y) ◇ w
equation 39565 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ z) ◇ x
equation 39566 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ z) ◇ y
equation 39567 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ z) ◇ z
equation 39568 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ z) ◇ w
equation 39569 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ w) ◇ x
equation 39570 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ w) ◇ y
equation 39571 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ w) ◇ z
equation 39572 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ w) ◇ w
equation 39573 := x = (((y ◇ z) ◇ (z ◇ x)) ◇ w) ◇ u
equation 39574 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ x) ◇ x
equation 39575 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ x) ◇ y
equation 39576 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ x) ◇ z
equation 39577 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ x) ◇ w
equation 39578 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ y) ◇ x
equation 39579 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ y) ◇ y
equation 39580 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ y) ◇ z
equation 39581 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ y) ◇ w
equation 39582 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ z) ◇ x
equation 39583 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ z) ◇ y
equation 39584 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ z) ◇ z
equation 39585 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ z) ◇ w
equation 39586 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ w) ◇ x
equation 39587 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ w) ◇ y
equation 39588 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ w) ◇ z
equation 39589 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ w) ◇ w
equation 39590 := x = (((y ◇ z) ◇ (z ◇ y)) ◇ w) ◇ u
equation 39591 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ x) ◇ x
equation 39592 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ x) ◇ y
equation 39593 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ x) ◇ z
equation 39594 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ x) ◇ w
equation 39595 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ y) ◇ x
equation 39596 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ y) ◇ y
equation 39597 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ y) ◇ z
equation 39598 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ y) ◇ w
equation 39599 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ z) ◇ x
equation 39600 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ z) ◇ y
equation 39601 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ z) ◇ z
equation 39602 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ z) ◇ w
equation 39603 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ w) ◇ x
equation 39604 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ w) ◇ y
equation 39605 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ w) ◇ z
equation 39606 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ w) ◇ w
equation 39607 := x = (((y ◇ z) ◇ (z ◇ z)) ◇ w) ◇ u
equation 39608 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ x) ◇ x
equation 39609 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ x) ◇ y
equation 39610 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ x) ◇ z
equation 39611 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ x) ◇ w
equation 39612 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ x) ◇ u
equation 39613 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ y) ◇ x
equation 39614 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ y) ◇ y
equation 39615 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ y) ◇ z
equation 39616 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ y) ◇ w
equation 39617 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ y) ◇ u
equation 39618 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ z) ◇ x
equation 39619 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ z) ◇ y
equation 39620 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ z) ◇ z
equation 39621 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ z) ◇ w
equation 39622 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ z) ◇ u
equation 39623 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ w) ◇ x
equation 39624 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ w) ◇ y
equation 39625 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ w) ◇ z
equation 39626 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ w) ◇ w
equation 39627 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ w) ◇ u
equation 39628 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ x
equation 39629 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ y
equation 39630 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ z
equation 39631 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ w
equation 39632 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ u
equation 39633 := x = (((y ◇ z) ◇ (z ◇ w)) ◇ u) ◇ v
equation 39634 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ x) ◇ x
equation 39635 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ x) ◇ y
equation 39636 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ x) ◇ z
equation 39637 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ x) ◇ w
equation 39638 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ x) ◇ u
equation 39639 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ y) ◇ x
equation 39640 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ y) ◇ y
equation 39641 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ y) ◇ z
equation 39642 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ y) ◇ w
equation 39643 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ y) ◇ u
equation 39644 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ z) ◇ x
equation 39645 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ z) ◇ y
equation 39646 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ z) ◇ z
equation 39647 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ z) ◇ w
equation 39648 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ z) ◇ u
equation 39649 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ w) ◇ x
equation 39650 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ w) ◇ y
equation 39651 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ w) ◇ z
equation 39652 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ w) ◇ w
equation 39653 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ w) ◇ u
equation 39654 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ x
equation 39655 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ y
equation 39656 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ z
equation 39657 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ w
equation 39658 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ u
equation 39659 := x = (((y ◇ z) ◇ (w ◇ x)) ◇ u) ◇ v
equation 39660 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ x) ◇ x
equation 39661 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ x) ◇ y
equation 39662 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ x) ◇ z
equation 39663 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ x) ◇ w
equation 39664 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ x) ◇ u
equation 39665 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ y) ◇ x
equation 39666 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ y) ◇ y
equation 39667 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ y) ◇ z
equation 39668 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ y) ◇ w
equation 39669 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ y) ◇ u
equation 39670 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ z) ◇ x
equation 39671 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ z) ◇ y
equation 39672 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ z) ◇ z
equation 39673 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ z) ◇ w
equation 39674 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ z) ◇ u
equation 39675 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ w) ◇ x
equation 39676 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ w) ◇ y
equation 39677 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ w) ◇ z
equation 39678 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ w) ◇ w
equation 39679 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ w) ◇ u
equation 39680 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ x
equation 39681 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ y
equation 39682 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ z
equation 39683 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ w
equation 39684 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ u
equation 39685 := x = (((y ◇ z) ◇ (w ◇ y)) ◇ u) ◇ v
equation 39686 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ x) ◇ x
equation 39687 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ x) ◇ y
equation 39688 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ x) ◇ z
equation 39689 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ x) ◇ w
equation 39690 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ x) ◇ u
equation 39691 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ y) ◇ x
equation 39692 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ y) ◇ y
equation 39693 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ y) ◇ z
equation 39694 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ y) ◇ w
equation 39695 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ y) ◇ u
equation 39696 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ z) ◇ x
equation 39697 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ z) ◇ y
equation 39698 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ z) ◇ z
equation 39699 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ z) ◇ w
equation 39700 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ z) ◇ u
equation 39701 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ w) ◇ x
equation 39702 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ w) ◇ y
equation 39703 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ w) ◇ z
equation 39704 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ w) ◇ w
equation 39705 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ w) ◇ u
equation 39706 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ x
equation 39707 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ y
equation 39708 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ z
equation 39709 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ w
equation 39710 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ u
equation 39711 := x = (((y ◇ z) ◇ (w ◇ z)) ◇ u) ◇ v
equation 39712 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ x) ◇ x
equation 39713 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ x) ◇ y
equation 39714 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ x) ◇ z
equation 39715 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ x) ◇ w
equation 39716 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ x) ◇ u
equation 39717 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ y) ◇ x
equation 39718 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ y) ◇ y
equation 39719 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ y) ◇ z
equation 39720 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ y) ◇ w
equation 39721 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ y) ◇ u
equation 39722 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ z) ◇ x
equation 39723 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ z) ◇ y
equation 39724 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ z) ◇ z
equation 39725 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ z) ◇ w
equation 39726 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ z) ◇ u
equation 39727 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ w) ◇ x
equation 39728 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ w) ◇ y
equation 39729 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ w) ◇ z
equation 39730 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ w) ◇ w
equation 39731 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ w) ◇ u
equation 39732 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ x
equation 39733 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ y
equation 39734 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ z
equation 39735 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ w
equation 39736 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ u
equation 39737 := x = (((y ◇ z) ◇ (w ◇ w)) ◇ u) ◇ v
equation 39738 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ x
equation 39739 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ y
equation 39740 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ z
equation 39741 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ w
equation 39742 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ u
equation 39743 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ x) ◇ v
equation 39744 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ x
equation 39745 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ y
equation 39746 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ z
equation 39747 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ w
equation 39748 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ u
equation 39749 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ y) ◇ v
equation 39750 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ x
equation 39751 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ y
equation 39752 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ z
equation 39753 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ w
equation 39754 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ u
equation 39755 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ z) ◇ v
equation 39756 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ x
equation 39757 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ y
equation 39758 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ z
equation 39759 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ w
equation 39760 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ u
equation 39761 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ w) ◇ v
equation 39762 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ x
equation 39763 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ y
equation 39764 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ z
equation 39765 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ w
equation 39766 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ u
equation 39767 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ u) ◇ v
equation 39768 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ x
equation 39769 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ y
equation 39770 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ z
equation 39771 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ w
equation 39772 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ u
equation 39773 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ v
equation 39774 := x = (((y ◇ z) ◇ (w ◇ u)) ◇ v) ◇ r
equation 39775 := x = (((x ◇ (x ◇ x)) ◇ x) ◇ x) ◇ x
equation 39776 := x = (((x ◇ (x ◇ x)) ◇ x) ◇ x) ◇ y
equation 39777 := x = (((x ◇ (x ◇ x)) ◇ x) ◇ y) ◇ x
equation 39778 := x = (((x ◇ (x ◇ x)) ◇ x) ◇ y) ◇ y
equation 39779 := x = (((x ◇ (x ◇ x)) ◇ x) ◇ y) ◇ z
equation 39780 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ x) ◇ x
equation 39781 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ x) ◇ y
equation 39782 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ x) ◇ z
equation 39783 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ y) ◇ x
equation 39784 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ y) ◇ y
equation 39785 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ y) ◇ z
equation 39786 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ z) ◇ x
equation 39787 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ z) ◇ y
equation 39788 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ z) ◇ z
equation 39789 := x = (((x ◇ (x ◇ x)) ◇ y) ◇ z) ◇ w
equation 39790 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ x) ◇ x
equation 39791 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ x) ◇ y
equation 39792 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ x) ◇ z
equation 39793 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ y) ◇ x
equation 39794 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ y) ◇ y
equation 39795 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ y) ◇ z
equation 39796 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ z) ◇ x
equation 39797 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ z) ◇ y
equation 39798 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ z) ◇ z
equation 39799 := x = (((x ◇ (x ◇ y)) ◇ x) ◇ z) ◇ w
equation 39800 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ x) ◇ x
equation 39801 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ x) ◇ y
equation 39802 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ x) ◇ z
equation 39803 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ y) ◇ x
equation 39804 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ y) ◇ y
equation 39805 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ y) ◇ z
equation 39806 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ z) ◇ x
equation 39807 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ z) ◇ y
equation 39808 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ z) ◇ z
equation 39809 := x = (((x ◇ (x ◇ y)) ◇ y) ◇ z) ◇ w
equation 39810 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ x) ◇ x
equation 39811 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ x) ◇ y
equation 39812 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ x) ◇ z
equation 39813 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ x) ◇ w
equation 39814 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ y) ◇ x
equation 39815 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ y) ◇ y
equation 39816 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ y) ◇ z
equation 39817 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ y) ◇ w
equation 39818 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ z) ◇ x
equation 39819 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ z) ◇ y
equation 39820 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ z) ◇ z
equation 39821 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ z) ◇ w
equation 39822 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ w) ◇ x
equation 39823 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ w) ◇ y
equation 39824 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ w) ◇ z
equation 39825 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ w) ◇ w
equation 39826 := x = (((x ◇ (x ◇ y)) ◇ z) ◇ w) ◇ u
equation 39827 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ x) ◇ x
equation 39828 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ x) ◇ y
equation 39829 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ x) ◇ z
equation 39830 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ y) ◇ x
equation 39831 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ y) ◇ y
equation 39832 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ y) ◇ z
equation 39833 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ z) ◇ x
equation 39834 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ z) ◇ y
equation 39835 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ z) ◇ z
equation 39836 := x = (((x ◇ (y ◇ x)) ◇ x) ◇ z) ◇ w
equation 39837 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ x) ◇ x
equation 39838 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ x) ◇ y
equation 39839 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ x) ◇ z
equation 39840 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ y) ◇ x
equation 39841 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ y) ◇ y
equation 39842 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ y) ◇ z
equation 39843 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ z) ◇ x
equation 39844 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ z) ◇ y
equation 39845 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ z) ◇ z
equation 39846 := x = (((x ◇ (y ◇ x)) ◇ y) ◇ z) ◇ w
equation 39847 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ x) ◇ x
equation 39848 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ x) ◇ y
equation 39849 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ x) ◇ z
equation 39850 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ x) ◇ w
equation 39851 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ y) ◇ x
equation 39852 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ y) ◇ y
equation 39853 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ y) ◇ z
equation 39854 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ y) ◇ w
equation 39855 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ z) ◇ x
equation 39856 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ z) ◇ y
equation 39857 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ z) ◇ z
equation 39858 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ z) ◇ w
equation 39859 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ w) ◇ x
equation 39860 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ w) ◇ y
equation 39861 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ w) ◇ z
equation 39862 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ w) ◇ w
equation 39863 := x = (((x ◇ (y ◇ x)) ◇ z) ◇ w) ◇ u
equation 39864 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ x) ◇ x
equation 39865 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ x) ◇ y
equation 39866 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ x) ◇ z
equation 39867 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ y) ◇ x
equation 39868 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ y) ◇ y
equation 39869 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ y) ◇ z
equation 39870 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ z) ◇ x
equation 39871 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ z) ◇ y
equation 39872 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ z) ◇ z
equation 39873 := x = (((x ◇ (y ◇ y)) ◇ x) ◇ z) ◇ w
equation 39874 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ x) ◇ x
equation 39875 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ x) ◇ y
equation 39876 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ x) ◇ z
equation 39877 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ y) ◇ x
equation 39878 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ y) ◇ y
equation 39879 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ y) ◇ z
equation 39880 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ z) ◇ x
equation 39881 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ z) ◇ y
equation 39882 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ z) ◇ z
equation 39883 := x = (((x ◇ (y ◇ y)) ◇ y) ◇ z) ◇ w
equation 39884 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ x) ◇ x
equation 39885 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ x) ◇ y
equation 39886 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ x) ◇ z
equation 39887 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ x) ◇ w
equation 39888 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ y) ◇ x
equation 39889 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ y) ◇ y
equation 39890 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ y) ◇ z
equation 39891 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ y) ◇ w
equation 39892 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ z) ◇ x
equation 39893 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ z) ◇ y
equation 39894 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ z) ◇ z
equation 39895 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ z) ◇ w
equation 39896 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ w) ◇ x
equation 39897 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ w) ◇ y
equation 39898 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ w) ◇ z
equation 39899 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ w) ◇ w
equation 39900 := x = (((x ◇ (y ◇ y)) ◇ z) ◇ w) ◇ u
equation 39901 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ x) ◇ x
equation 39902 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ x) ◇ y
equation 39903 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ x) ◇ z
equation 39904 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ x) ◇ w
equation 39905 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ y) ◇ x
equation 39906 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ y) ◇ y
equation 39907 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ y) ◇ z
equation 39908 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ y) ◇ w
equation 39909 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ z) ◇ x
equation 39910 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ z) ◇ y
equation 39911 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ z) ◇ z
equation 39912 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ z) ◇ w
equation 39913 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ w) ◇ x
equation 39914 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ w) ◇ y
equation 39915 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ w) ◇ z
equation 39916 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ w) ◇ w
equation 39917 := x = (((x ◇ (y ◇ z)) ◇ x) ◇ w) ◇ u
equation 39918 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ x) ◇ x
equation 39919 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ x) ◇ y
equation 39920 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ x) ◇ z
equation 39921 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ x) ◇ w
equation 39922 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ y) ◇ x
equation 39923 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ y) ◇ y
equation 39924 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ y) ◇ z
equation 39925 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ y) ◇ w
equation 39926 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ z) ◇ x
equation 39927 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ z) ◇ y
equation 39928 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ z) ◇ z
equation 39929 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ z) ◇ w
equation 39930 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ w) ◇ x
equation 39931 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ w) ◇ y
equation 39932 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ w) ◇ z
equation 39933 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ w) ◇ w
equation 39934 := x = (((x ◇ (y ◇ z)) ◇ y) ◇ w) ◇ u
equation 39935 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ x) ◇ x
equation 39936 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ x) ◇ y
equation 39937 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ x) ◇ z
equation 39938 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ x) ◇ w
equation 39939 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ y) ◇ x
equation 39940 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ y) ◇ y
equation 39941 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ y) ◇ z
equation 39942 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ y) ◇ w
equation 39943 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ z) ◇ x
equation 39944 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ z) ◇ y
equation 39945 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ z) ◇ z
equation 39946 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ z) ◇ w
equation 39947 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ w) ◇ x
equation 39948 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ w) ◇ y
equation 39949 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ w) ◇ z
equation 39950 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ w) ◇ w
equation 39951 := x = (((x ◇ (y ◇ z)) ◇ z) ◇ w) ◇ u
equation 39952 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ x) ◇ x
equation 39953 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ x) ◇ y
equation 39954 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ x) ◇ z
equation 39955 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ x) ◇ w
equation 39956 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ x) ◇ u
equation 39957 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ y) ◇ x
equation 39958 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ y) ◇ y
equation 39959 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ y) ◇ z
equation 39960 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ y) ◇ w
equation 39961 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ y) ◇ u
equation 39962 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ z) ◇ x
equation 39963 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ z) ◇ y
equation 39964 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ z) ◇ z
equation 39965 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ z) ◇ w
equation 39966 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ z) ◇ u
equation 39967 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ w) ◇ x
equation 39968 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ w) ◇ y
equation 39969 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ w) ◇ z
equation 39970 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ w) ◇ w
equation 39971 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ w) ◇ u
equation 39972 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ x
equation 39973 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ y
equation 39974 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ z
equation 39975 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ w
equation 39976 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ u
equation 39977 := x = (((x ◇ (y ◇ z)) ◇ w) ◇ u) ◇ v
equation 39978 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ x) ◇ x
equation 39979 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ x) ◇ y
equation 39980 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ x) ◇ z
equation 39981 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ y) ◇ x
equation 39982 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ y) ◇ y
equation 39983 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ y) ◇ z
equation 39984 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ z) ◇ x
equation 39985 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ z) ◇ y
equation 39986 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ z) ◇ z
equation 39987 := x = (((y ◇ (x ◇ x)) ◇ x) ◇ z) ◇ w
equation 39988 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ x) ◇ x
equation 39989 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ x) ◇ y
equation 39990 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ x) ◇ z
equation 39991 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ y) ◇ x
equation 39992 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ y) ◇ y
equation 39993 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ y) ◇ z
equation 39994 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ z) ◇ x
equation 39995 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ z) ◇ y
equation 39996 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ z) ◇ z
equation 39997 := x = (((y ◇ (x ◇ x)) ◇ y) ◇ z) ◇ w
equation 39998 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ x) ◇ x
equation 39999 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ x) ◇ y
