import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 52000-52999 -/

equation 52000 := x ◇ y = ((z ◇ w) ◇ (w ◇ z)) ◇ x
equation 52001 := x ◇ y = ((z ◇ w) ◇ (w ◇ z)) ◇ y
equation 52002 := x ◇ y = ((z ◇ w) ◇ (w ◇ z)) ◇ z
equation 52003 := x ◇ y = ((z ◇ w) ◇ (w ◇ z)) ◇ w
equation 52004 := x ◇ y = ((z ◇ w) ◇ (w ◇ z)) ◇ u
equation 52005 := x ◇ y = ((z ◇ w) ◇ (w ◇ w)) ◇ x
equation 52006 := x ◇ y = ((z ◇ w) ◇ (w ◇ w)) ◇ y
equation 52007 := x ◇ y = ((z ◇ w) ◇ (w ◇ w)) ◇ z
equation 52008 := x ◇ y = ((z ◇ w) ◇ (w ◇ w)) ◇ w
equation 52009 := x ◇ y = ((z ◇ w) ◇ (w ◇ w)) ◇ u
equation 52010 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ x
equation 52011 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ y
equation 52012 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ z
equation 52013 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ w
equation 52014 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ u
equation 52015 := x ◇ y = ((z ◇ w) ◇ (w ◇ u)) ◇ v
equation 52016 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ x
equation 52017 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ y
equation 52018 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ z
equation 52019 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ w
equation 52020 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ u
equation 52021 := x ◇ y = ((z ◇ w) ◇ (u ◇ x)) ◇ v
equation 52022 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ x
equation 52023 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ y
equation 52024 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ z
equation 52025 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ w
equation 52026 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ u
equation 52027 := x ◇ y = ((z ◇ w) ◇ (u ◇ y)) ◇ v
equation 52028 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ x
equation 52029 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ y
equation 52030 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ z
equation 52031 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ w
equation 52032 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ u
equation 52033 := x ◇ y = ((z ◇ w) ◇ (u ◇ z)) ◇ v
equation 52034 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ x
equation 52035 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ y
equation 52036 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ z
equation 52037 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ w
equation 52038 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ u
equation 52039 := x ◇ y = ((z ◇ w) ◇ (u ◇ w)) ◇ v
equation 52040 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ x
equation 52041 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ y
equation 52042 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ z
equation 52043 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ w
equation 52044 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ u
equation 52045 := x ◇ y = ((z ◇ w) ◇ (u ◇ u)) ◇ v
equation 52046 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ x
equation 52047 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ y
equation 52048 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ z
equation 52049 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ w
equation 52050 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ u
equation 52051 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ v
equation 52052 := x ◇ y = ((z ◇ w) ◇ (u ◇ v)) ◇ r
equation 52053 := x ◇ x = ((x ◇ (x ◇ x)) ◇ x) ◇ x
equation 52054 := x ◇ x = ((x ◇ (x ◇ x)) ◇ x) ◇ y
equation 52055 := x ◇ x = ((x ◇ (x ◇ x)) ◇ y) ◇ x
equation 52056 := x ◇ x = ((x ◇ (x ◇ x)) ◇ y) ◇ y
equation 52057 := x ◇ x = ((x ◇ (x ◇ x)) ◇ y) ◇ z
equation 52058 := x ◇ x = ((x ◇ (x ◇ y)) ◇ x) ◇ x
equation 52059 := x ◇ x = ((x ◇ (x ◇ y)) ◇ x) ◇ y
equation 52060 := x ◇ x = ((x ◇ (x ◇ y)) ◇ x) ◇ z
equation 52061 := x ◇ x = ((x ◇ (x ◇ y)) ◇ y) ◇ x
equation 52062 := x ◇ x = ((x ◇ (x ◇ y)) ◇ y) ◇ y
equation 52063 := x ◇ x = ((x ◇ (x ◇ y)) ◇ y) ◇ z
equation 52064 := x ◇ x = ((x ◇ (x ◇ y)) ◇ z) ◇ x
equation 52065 := x ◇ x = ((x ◇ (x ◇ y)) ◇ z) ◇ y
equation 52066 := x ◇ x = ((x ◇ (x ◇ y)) ◇ z) ◇ z
equation 52067 := x ◇ x = ((x ◇ (x ◇ y)) ◇ z) ◇ w
equation 52068 := x ◇ x = ((x ◇ (y ◇ x)) ◇ x) ◇ x
equation 52069 := x ◇ x = ((x ◇ (y ◇ x)) ◇ x) ◇ y
equation 52070 := x ◇ x = ((x ◇ (y ◇ x)) ◇ x) ◇ z
equation 52071 := x ◇ x = ((x ◇ (y ◇ x)) ◇ y) ◇ x
equation 52072 := x ◇ x = ((x ◇ (y ◇ x)) ◇ y) ◇ y
equation 52073 := x ◇ x = ((x ◇ (y ◇ x)) ◇ y) ◇ z
equation 52074 := x ◇ x = ((x ◇ (y ◇ x)) ◇ z) ◇ x
equation 52075 := x ◇ x = ((x ◇ (y ◇ x)) ◇ z) ◇ y
equation 52076 := x ◇ x = ((x ◇ (y ◇ x)) ◇ z) ◇ z
equation 52077 := x ◇ x = ((x ◇ (y ◇ x)) ◇ z) ◇ w
equation 52078 := x ◇ x = ((x ◇ (y ◇ y)) ◇ x) ◇ x
equation 52079 := x ◇ x = ((x ◇ (y ◇ y)) ◇ x) ◇ y
equation 52080 := x ◇ x = ((x ◇ (y ◇ y)) ◇ x) ◇ z
equation 52081 := x ◇ x = ((x ◇ (y ◇ y)) ◇ y) ◇ x
equation 52082 := x ◇ x = ((x ◇ (y ◇ y)) ◇ y) ◇ y
equation 52083 := x ◇ x = ((x ◇ (y ◇ y)) ◇ y) ◇ z
equation 52084 := x ◇ x = ((x ◇ (y ◇ y)) ◇ z) ◇ x
equation 52085 := x ◇ x = ((x ◇ (y ◇ y)) ◇ z) ◇ y
equation 52086 := x ◇ x = ((x ◇ (y ◇ y)) ◇ z) ◇ z
equation 52087 := x ◇ x = ((x ◇ (y ◇ y)) ◇ z) ◇ w
equation 52088 := x ◇ x = ((x ◇ (y ◇ z)) ◇ x) ◇ x
equation 52089 := x ◇ x = ((x ◇ (y ◇ z)) ◇ x) ◇ y
equation 52090 := x ◇ x = ((x ◇ (y ◇ z)) ◇ x) ◇ z
equation 52091 := x ◇ x = ((x ◇ (y ◇ z)) ◇ x) ◇ w
equation 52092 := x ◇ x = ((x ◇ (y ◇ z)) ◇ y) ◇ x
equation 52093 := x ◇ x = ((x ◇ (y ◇ z)) ◇ y) ◇ y
equation 52094 := x ◇ x = ((x ◇ (y ◇ z)) ◇ y) ◇ z
equation 52095 := x ◇ x = ((x ◇ (y ◇ z)) ◇ y) ◇ w
equation 52096 := x ◇ x = ((x ◇ (y ◇ z)) ◇ z) ◇ x
equation 52097 := x ◇ x = ((x ◇ (y ◇ z)) ◇ z) ◇ y
equation 52098 := x ◇ x = ((x ◇ (y ◇ z)) ◇ z) ◇ z
equation 52099 := x ◇ x = ((x ◇ (y ◇ z)) ◇ z) ◇ w
equation 52100 := x ◇ x = ((x ◇ (y ◇ z)) ◇ w) ◇ x
equation 52101 := x ◇ x = ((x ◇ (y ◇ z)) ◇ w) ◇ y
equation 52102 := x ◇ x = ((x ◇ (y ◇ z)) ◇ w) ◇ z
equation 52103 := x ◇ x = ((x ◇ (y ◇ z)) ◇ w) ◇ w
equation 52104 := x ◇ x = ((x ◇ (y ◇ z)) ◇ w) ◇ u
equation 52105 := x ◇ x = ((y ◇ (x ◇ x)) ◇ x) ◇ x
equation 52106 := x ◇ x = ((y ◇ (x ◇ x)) ◇ x) ◇ y
equation 52107 := x ◇ x = ((y ◇ (x ◇ x)) ◇ x) ◇ z
equation 52108 := x ◇ x = ((y ◇ (x ◇ x)) ◇ y) ◇ x
equation 52109 := x ◇ x = ((y ◇ (x ◇ x)) ◇ y) ◇ y
equation 52110 := x ◇ x = ((y ◇ (x ◇ x)) ◇ y) ◇ z
equation 52111 := x ◇ x = ((y ◇ (x ◇ x)) ◇ z) ◇ x
equation 52112 := x ◇ x = ((y ◇ (x ◇ x)) ◇ z) ◇ y
equation 52113 := x ◇ x = ((y ◇ (x ◇ x)) ◇ z) ◇ z
equation 52114 := x ◇ x = ((y ◇ (x ◇ x)) ◇ z) ◇ w
equation 52115 := x ◇ x = ((y ◇ (x ◇ y)) ◇ x) ◇ x
equation 52116 := x ◇ x = ((y ◇ (x ◇ y)) ◇ x) ◇ y
equation 52117 := x ◇ x = ((y ◇ (x ◇ y)) ◇ x) ◇ z
equation 52118 := x ◇ x = ((y ◇ (x ◇ y)) ◇ y) ◇ x
equation 52119 := x ◇ x = ((y ◇ (x ◇ y)) ◇ y) ◇ y
equation 52120 := x ◇ x = ((y ◇ (x ◇ y)) ◇ y) ◇ z
equation 52121 := x ◇ x = ((y ◇ (x ◇ y)) ◇ z) ◇ x
equation 52122 := x ◇ x = ((y ◇ (x ◇ y)) ◇ z) ◇ y
equation 52123 := x ◇ x = ((y ◇ (x ◇ y)) ◇ z) ◇ z
equation 52124 := x ◇ x = ((y ◇ (x ◇ y)) ◇ z) ◇ w
equation 52125 := x ◇ x = ((y ◇ (x ◇ z)) ◇ x) ◇ x
equation 52126 := x ◇ x = ((y ◇ (x ◇ z)) ◇ x) ◇ y
equation 52127 := x ◇ x = ((y ◇ (x ◇ z)) ◇ x) ◇ z
equation 52128 := x ◇ x = ((y ◇ (x ◇ z)) ◇ x) ◇ w
equation 52129 := x ◇ x = ((y ◇ (x ◇ z)) ◇ y) ◇ x
equation 52130 := x ◇ x = ((y ◇ (x ◇ z)) ◇ y) ◇ y
equation 52131 := x ◇ x = ((y ◇ (x ◇ z)) ◇ y) ◇ z
equation 52132 := x ◇ x = ((y ◇ (x ◇ z)) ◇ y) ◇ w
equation 52133 := x ◇ x = ((y ◇ (x ◇ z)) ◇ z) ◇ x
equation 52134 := x ◇ x = ((y ◇ (x ◇ z)) ◇ z) ◇ y
equation 52135 := x ◇ x = ((y ◇ (x ◇ z)) ◇ z) ◇ z
equation 52136 := x ◇ x = ((y ◇ (x ◇ z)) ◇ z) ◇ w
equation 52137 := x ◇ x = ((y ◇ (x ◇ z)) ◇ w) ◇ x
equation 52138 := x ◇ x = ((y ◇ (x ◇ z)) ◇ w) ◇ y
equation 52139 := x ◇ x = ((y ◇ (x ◇ z)) ◇ w) ◇ z
equation 52140 := x ◇ x = ((y ◇ (x ◇ z)) ◇ w) ◇ w
equation 52141 := x ◇ x = ((y ◇ (x ◇ z)) ◇ w) ◇ u
equation 52142 := x ◇ x = ((y ◇ (y ◇ x)) ◇ x) ◇ x
equation 52143 := x ◇ x = ((y ◇ (y ◇ x)) ◇ x) ◇ y
equation 52144 := x ◇ x = ((y ◇ (y ◇ x)) ◇ x) ◇ z
equation 52145 := x ◇ x = ((y ◇ (y ◇ x)) ◇ y) ◇ x
equation 52146 := x ◇ x = ((y ◇ (y ◇ x)) ◇ y) ◇ y
equation 52147 := x ◇ x = ((y ◇ (y ◇ x)) ◇ y) ◇ z
equation 52148 := x ◇ x = ((y ◇ (y ◇ x)) ◇ z) ◇ x
equation 52149 := x ◇ x = ((y ◇ (y ◇ x)) ◇ z) ◇ y
equation 52150 := x ◇ x = ((y ◇ (y ◇ x)) ◇ z) ◇ z
equation 52151 := x ◇ x = ((y ◇ (y ◇ x)) ◇ z) ◇ w
equation 52152 := x ◇ x = ((y ◇ (y ◇ y)) ◇ x) ◇ x
equation 52153 := x ◇ x = ((y ◇ (y ◇ y)) ◇ x) ◇ y
equation 52154 := x ◇ x = ((y ◇ (y ◇ y)) ◇ x) ◇ z
equation 52155 := x ◇ x = ((y ◇ (y ◇ y)) ◇ y) ◇ x
equation 52156 := x ◇ x = ((y ◇ (y ◇ y)) ◇ y) ◇ y
equation 52157 := x ◇ x = ((y ◇ (y ◇ y)) ◇ y) ◇ z
equation 52158 := x ◇ x = ((y ◇ (y ◇ y)) ◇ z) ◇ x
equation 52159 := x ◇ x = ((y ◇ (y ◇ y)) ◇ z) ◇ y
equation 52160 := x ◇ x = ((y ◇ (y ◇ y)) ◇ z) ◇ z
equation 52161 := x ◇ x = ((y ◇ (y ◇ y)) ◇ z) ◇ w
equation 52162 := x ◇ x = ((y ◇ (y ◇ z)) ◇ x) ◇ x
equation 52163 := x ◇ x = ((y ◇ (y ◇ z)) ◇ x) ◇ y
equation 52164 := x ◇ x = ((y ◇ (y ◇ z)) ◇ x) ◇ z
equation 52165 := x ◇ x = ((y ◇ (y ◇ z)) ◇ x) ◇ w
equation 52166 := x ◇ x = ((y ◇ (y ◇ z)) ◇ y) ◇ x
equation 52167 := x ◇ x = ((y ◇ (y ◇ z)) ◇ y) ◇ y
equation 52168 := x ◇ x = ((y ◇ (y ◇ z)) ◇ y) ◇ z
equation 52169 := x ◇ x = ((y ◇ (y ◇ z)) ◇ y) ◇ w
equation 52170 := x ◇ x = ((y ◇ (y ◇ z)) ◇ z) ◇ x
equation 52171 := x ◇ x = ((y ◇ (y ◇ z)) ◇ z) ◇ y
equation 52172 := x ◇ x = ((y ◇ (y ◇ z)) ◇ z) ◇ z
equation 52173 := x ◇ x = ((y ◇ (y ◇ z)) ◇ z) ◇ w
equation 52174 := x ◇ x = ((y ◇ (y ◇ z)) ◇ w) ◇ x
equation 52175 := x ◇ x = ((y ◇ (y ◇ z)) ◇ w) ◇ y
equation 52176 := x ◇ x = ((y ◇ (y ◇ z)) ◇ w) ◇ z
equation 52177 := x ◇ x = ((y ◇ (y ◇ z)) ◇ w) ◇ w
equation 52178 := x ◇ x = ((y ◇ (y ◇ z)) ◇ w) ◇ u
equation 52179 := x ◇ x = ((y ◇ (z ◇ x)) ◇ x) ◇ x
equation 52180 := x ◇ x = ((y ◇ (z ◇ x)) ◇ x) ◇ y
equation 52181 := x ◇ x = ((y ◇ (z ◇ x)) ◇ x) ◇ z
equation 52182 := x ◇ x = ((y ◇ (z ◇ x)) ◇ x) ◇ w
equation 52183 := x ◇ x = ((y ◇ (z ◇ x)) ◇ y) ◇ x
equation 52184 := x ◇ x = ((y ◇ (z ◇ x)) ◇ y) ◇ y
equation 52185 := x ◇ x = ((y ◇ (z ◇ x)) ◇ y) ◇ z
equation 52186 := x ◇ x = ((y ◇ (z ◇ x)) ◇ y) ◇ w
equation 52187 := x ◇ x = ((y ◇ (z ◇ x)) ◇ z) ◇ x
equation 52188 := x ◇ x = ((y ◇ (z ◇ x)) ◇ z) ◇ y
equation 52189 := x ◇ x = ((y ◇ (z ◇ x)) ◇ z) ◇ z
equation 52190 := x ◇ x = ((y ◇ (z ◇ x)) ◇ z) ◇ w
equation 52191 := x ◇ x = ((y ◇ (z ◇ x)) ◇ w) ◇ x
equation 52192 := x ◇ x = ((y ◇ (z ◇ x)) ◇ w) ◇ y
equation 52193 := x ◇ x = ((y ◇ (z ◇ x)) ◇ w) ◇ z
equation 52194 := x ◇ x = ((y ◇ (z ◇ x)) ◇ w) ◇ w
equation 52195 := x ◇ x = ((y ◇ (z ◇ x)) ◇ w) ◇ u
equation 52196 := x ◇ x = ((y ◇ (z ◇ y)) ◇ x) ◇ x
equation 52197 := x ◇ x = ((y ◇ (z ◇ y)) ◇ x) ◇ y
equation 52198 := x ◇ x = ((y ◇ (z ◇ y)) ◇ x) ◇ z
equation 52199 := x ◇ x = ((y ◇ (z ◇ y)) ◇ x) ◇ w
equation 52200 := x ◇ x = ((y ◇ (z ◇ y)) ◇ y) ◇ x
equation 52201 := x ◇ x = ((y ◇ (z ◇ y)) ◇ y) ◇ y
equation 52202 := x ◇ x = ((y ◇ (z ◇ y)) ◇ y) ◇ z
equation 52203 := x ◇ x = ((y ◇ (z ◇ y)) ◇ y) ◇ w
equation 52204 := x ◇ x = ((y ◇ (z ◇ y)) ◇ z) ◇ x
equation 52205 := x ◇ x = ((y ◇ (z ◇ y)) ◇ z) ◇ y
equation 52206 := x ◇ x = ((y ◇ (z ◇ y)) ◇ z) ◇ z
equation 52207 := x ◇ x = ((y ◇ (z ◇ y)) ◇ z) ◇ w
equation 52208 := x ◇ x = ((y ◇ (z ◇ y)) ◇ w) ◇ x
equation 52209 := x ◇ x = ((y ◇ (z ◇ y)) ◇ w) ◇ y
equation 52210 := x ◇ x = ((y ◇ (z ◇ y)) ◇ w) ◇ z
equation 52211 := x ◇ x = ((y ◇ (z ◇ y)) ◇ w) ◇ w
equation 52212 := x ◇ x = ((y ◇ (z ◇ y)) ◇ w) ◇ u
equation 52213 := x ◇ x = ((y ◇ (z ◇ z)) ◇ x) ◇ x
equation 52214 := x ◇ x = ((y ◇ (z ◇ z)) ◇ x) ◇ y
equation 52215 := x ◇ x = ((y ◇ (z ◇ z)) ◇ x) ◇ z
equation 52216 := x ◇ x = ((y ◇ (z ◇ z)) ◇ x) ◇ w
equation 52217 := x ◇ x = ((y ◇ (z ◇ z)) ◇ y) ◇ x
equation 52218 := x ◇ x = ((y ◇ (z ◇ z)) ◇ y) ◇ y
equation 52219 := x ◇ x = ((y ◇ (z ◇ z)) ◇ y) ◇ z
equation 52220 := x ◇ x = ((y ◇ (z ◇ z)) ◇ y) ◇ w
equation 52221 := x ◇ x = ((y ◇ (z ◇ z)) ◇ z) ◇ x
equation 52222 := x ◇ x = ((y ◇ (z ◇ z)) ◇ z) ◇ y
equation 52223 := x ◇ x = ((y ◇ (z ◇ z)) ◇ z) ◇ z
equation 52224 := x ◇ x = ((y ◇ (z ◇ z)) ◇ z) ◇ w
equation 52225 := x ◇ x = ((y ◇ (z ◇ z)) ◇ w) ◇ x
equation 52226 := x ◇ x = ((y ◇ (z ◇ z)) ◇ w) ◇ y
equation 52227 := x ◇ x = ((y ◇ (z ◇ z)) ◇ w) ◇ z
equation 52228 := x ◇ x = ((y ◇ (z ◇ z)) ◇ w) ◇ w
equation 52229 := x ◇ x = ((y ◇ (z ◇ z)) ◇ w) ◇ u
equation 52230 := x ◇ x = ((y ◇ (z ◇ w)) ◇ x) ◇ x
equation 52231 := x ◇ x = ((y ◇ (z ◇ w)) ◇ x) ◇ y
equation 52232 := x ◇ x = ((y ◇ (z ◇ w)) ◇ x) ◇ z
equation 52233 := x ◇ x = ((y ◇ (z ◇ w)) ◇ x) ◇ w
equation 52234 := x ◇ x = ((y ◇ (z ◇ w)) ◇ x) ◇ u
equation 52235 := x ◇ x = ((y ◇ (z ◇ w)) ◇ y) ◇ x
equation 52236 := x ◇ x = ((y ◇ (z ◇ w)) ◇ y) ◇ y
equation 52237 := x ◇ x = ((y ◇ (z ◇ w)) ◇ y) ◇ z
equation 52238 := x ◇ x = ((y ◇ (z ◇ w)) ◇ y) ◇ w
equation 52239 := x ◇ x = ((y ◇ (z ◇ w)) ◇ y) ◇ u
equation 52240 := x ◇ x = ((y ◇ (z ◇ w)) ◇ z) ◇ x
equation 52241 := x ◇ x = ((y ◇ (z ◇ w)) ◇ z) ◇ y
equation 52242 := x ◇ x = ((y ◇ (z ◇ w)) ◇ z) ◇ z
equation 52243 := x ◇ x = ((y ◇ (z ◇ w)) ◇ z) ◇ w
equation 52244 := x ◇ x = ((y ◇ (z ◇ w)) ◇ z) ◇ u
equation 52245 := x ◇ x = ((y ◇ (z ◇ w)) ◇ w) ◇ x
equation 52246 := x ◇ x = ((y ◇ (z ◇ w)) ◇ w) ◇ y
equation 52247 := x ◇ x = ((y ◇ (z ◇ w)) ◇ w) ◇ z
equation 52248 := x ◇ x = ((y ◇ (z ◇ w)) ◇ w) ◇ w
equation 52249 := x ◇ x = ((y ◇ (z ◇ w)) ◇ w) ◇ u
equation 52250 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ x
equation 52251 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ y
equation 52252 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ z
equation 52253 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ w
equation 52254 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ u
equation 52255 := x ◇ x = ((y ◇ (z ◇ w)) ◇ u) ◇ v
equation 52256 := x ◇ y = ((x ◇ (x ◇ x)) ◇ x) ◇ x
equation 52257 := x ◇ y = ((x ◇ (x ◇ x)) ◇ x) ◇ y
equation 52258 := x ◇ y = ((x ◇ (x ◇ x)) ◇ x) ◇ z
equation 52259 := x ◇ y = ((x ◇ (x ◇ x)) ◇ y) ◇ x
equation 52260 := x ◇ y = ((x ◇ (x ◇ x)) ◇ y) ◇ y
equation 52261 := x ◇ y = ((x ◇ (x ◇ x)) ◇ y) ◇ z
equation 52262 := x ◇ y = ((x ◇ (x ◇ x)) ◇ z) ◇ x
equation 52263 := x ◇ y = ((x ◇ (x ◇ x)) ◇ z) ◇ y
equation 52264 := x ◇ y = ((x ◇ (x ◇ x)) ◇ z) ◇ z
equation 52265 := x ◇ y = ((x ◇ (x ◇ x)) ◇ z) ◇ w
equation 52266 := x ◇ y = ((x ◇ (x ◇ y)) ◇ x) ◇ x
equation 52267 := x ◇ y = ((x ◇ (x ◇ y)) ◇ x) ◇ y
equation 52268 := x ◇ y = ((x ◇ (x ◇ y)) ◇ x) ◇ z
equation 52269 := x ◇ y = ((x ◇ (x ◇ y)) ◇ y) ◇ x
equation 52270 := x ◇ y = ((x ◇ (x ◇ y)) ◇ y) ◇ y
equation 52271 := x ◇ y = ((x ◇ (x ◇ y)) ◇ y) ◇ z
equation 52272 := x ◇ y = ((x ◇ (x ◇ y)) ◇ z) ◇ x
equation 52273 := x ◇ y = ((x ◇ (x ◇ y)) ◇ z) ◇ y
equation 52274 := x ◇ y = ((x ◇ (x ◇ y)) ◇ z) ◇ z
equation 52275 := x ◇ y = ((x ◇ (x ◇ y)) ◇ z) ◇ w
equation 52276 := x ◇ y = ((x ◇ (x ◇ z)) ◇ x) ◇ x
equation 52277 := x ◇ y = ((x ◇ (x ◇ z)) ◇ x) ◇ y
equation 52278 := x ◇ y = ((x ◇ (x ◇ z)) ◇ x) ◇ z
equation 52279 := x ◇ y = ((x ◇ (x ◇ z)) ◇ x) ◇ w
equation 52280 := x ◇ y = ((x ◇ (x ◇ z)) ◇ y) ◇ x
equation 52281 := x ◇ y = ((x ◇ (x ◇ z)) ◇ y) ◇ y
equation 52282 := x ◇ y = ((x ◇ (x ◇ z)) ◇ y) ◇ z
equation 52283 := x ◇ y = ((x ◇ (x ◇ z)) ◇ y) ◇ w
equation 52284 := x ◇ y = ((x ◇ (x ◇ z)) ◇ z) ◇ x
equation 52285 := x ◇ y = ((x ◇ (x ◇ z)) ◇ z) ◇ y
equation 52286 := x ◇ y = ((x ◇ (x ◇ z)) ◇ z) ◇ z
equation 52287 := x ◇ y = ((x ◇ (x ◇ z)) ◇ z) ◇ w
equation 52288 := x ◇ y = ((x ◇ (x ◇ z)) ◇ w) ◇ x
equation 52289 := x ◇ y = ((x ◇ (x ◇ z)) ◇ w) ◇ y
equation 52290 := x ◇ y = ((x ◇ (x ◇ z)) ◇ w) ◇ z
equation 52291 := x ◇ y = ((x ◇ (x ◇ z)) ◇ w) ◇ w
equation 52292 := x ◇ y = ((x ◇ (x ◇ z)) ◇ w) ◇ u
equation 52293 := x ◇ y = ((x ◇ (y ◇ x)) ◇ x) ◇ x
equation 52294 := x ◇ y = ((x ◇ (y ◇ x)) ◇ x) ◇ y
equation 52295 := x ◇ y = ((x ◇ (y ◇ x)) ◇ x) ◇ z
equation 52296 := x ◇ y = ((x ◇ (y ◇ x)) ◇ y) ◇ x
equation 52297 := x ◇ y = ((x ◇ (y ◇ x)) ◇ y) ◇ y
equation 52298 := x ◇ y = ((x ◇ (y ◇ x)) ◇ y) ◇ z
equation 52299 := x ◇ y = ((x ◇ (y ◇ x)) ◇ z) ◇ x
equation 52300 := x ◇ y = ((x ◇ (y ◇ x)) ◇ z) ◇ y
equation 52301 := x ◇ y = ((x ◇ (y ◇ x)) ◇ z) ◇ z
equation 52302 := x ◇ y = ((x ◇ (y ◇ x)) ◇ z) ◇ w
equation 52303 := x ◇ y = ((x ◇ (y ◇ y)) ◇ x) ◇ x
equation 52304 := x ◇ y = ((x ◇ (y ◇ y)) ◇ x) ◇ y
equation 52305 := x ◇ y = ((x ◇ (y ◇ y)) ◇ x) ◇ z
equation 52306 := x ◇ y = ((x ◇ (y ◇ y)) ◇ y) ◇ x
equation 52307 := x ◇ y = ((x ◇ (y ◇ y)) ◇ y) ◇ y
equation 52308 := x ◇ y = ((x ◇ (y ◇ y)) ◇ y) ◇ z
equation 52309 := x ◇ y = ((x ◇ (y ◇ y)) ◇ z) ◇ x
equation 52310 := x ◇ y = ((x ◇ (y ◇ y)) ◇ z) ◇ y
equation 52311 := x ◇ y = ((x ◇ (y ◇ y)) ◇ z) ◇ z
equation 52312 := x ◇ y = ((x ◇ (y ◇ y)) ◇ z) ◇ w
equation 52313 := x ◇ y = ((x ◇ (y ◇ z)) ◇ x) ◇ x
equation 52314 := x ◇ y = ((x ◇ (y ◇ z)) ◇ x) ◇ y
equation 52315 := x ◇ y = ((x ◇ (y ◇ z)) ◇ x) ◇ z
equation 52316 := x ◇ y = ((x ◇ (y ◇ z)) ◇ x) ◇ w
equation 52317 := x ◇ y = ((x ◇ (y ◇ z)) ◇ y) ◇ x
equation 52318 := x ◇ y = ((x ◇ (y ◇ z)) ◇ y) ◇ y
equation 52319 := x ◇ y = ((x ◇ (y ◇ z)) ◇ y) ◇ z
equation 52320 := x ◇ y = ((x ◇ (y ◇ z)) ◇ y) ◇ w
equation 52321 := x ◇ y = ((x ◇ (y ◇ z)) ◇ z) ◇ x
equation 52322 := x ◇ y = ((x ◇ (y ◇ z)) ◇ z) ◇ y
equation 52323 := x ◇ y = ((x ◇ (y ◇ z)) ◇ z) ◇ z
equation 52324 := x ◇ y = ((x ◇ (y ◇ z)) ◇ z) ◇ w
equation 52325 := x ◇ y = ((x ◇ (y ◇ z)) ◇ w) ◇ x
equation 52326 := x ◇ y = ((x ◇ (y ◇ z)) ◇ w) ◇ y
equation 52327 := x ◇ y = ((x ◇ (y ◇ z)) ◇ w) ◇ z
equation 52328 := x ◇ y = ((x ◇ (y ◇ z)) ◇ w) ◇ w
equation 52329 := x ◇ y = ((x ◇ (y ◇ z)) ◇ w) ◇ u
equation 52330 := x ◇ y = ((x ◇ (z ◇ x)) ◇ x) ◇ x
equation 52331 := x ◇ y = ((x ◇ (z ◇ x)) ◇ x) ◇ y
equation 52332 := x ◇ y = ((x ◇ (z ◇ x)) ◇ x) ◇ z
equation 52333 := x ◇ y = ((x ◇ (z ◇ x)) ◇ x) ◇ w
equation 52334 := x ◇ y = ((x ◇ (z ◇ x)) ◇ y) ◇ x
equation 52335 := x ◇ y = ((x ◇ (z ◇ x)) ◇ y) ◇ y
equation 52336 := x ◇ y = ((x ◇ (z ◇ x)) ◇ y) ◇ z
equation 52337 := x ◇ y = ((x ◇ (z ◇ x)) ◇ y) ◇ w
equation 52338 := x ◇ y = ((x ◇ (z ◇ x)) ◇ z) ◇ x
equation 52339 := x ◇ y = ((x ◇ (z ◇ x)) ◇ z) ◇ y
equation 52340 := x ◇ y = ((x ◇ (z ◇ x)) ◇ z) ◇ z
equation 52341 := x ◇ y = ((x ◇ (z ◇ x)) ◇ z) ◇ w
equation 52342 := x ◇ y = ((x ◇ (z ◇ x)) ◇ w) ◇ x
equation 52343 := x ◇ y = ((x ◇ (z ◇ x)) ◇ w) ◇ y
equation 52344 := x ◇ y = ((x ◇ (z ◇ x)) ◇ w) ◇ z
equation 52345 := x ◇ y = ((x ◇ (z ◇ x)) ◇ w) ◇ w
equation 52346 := x ◇ y = ((x ◇ (z ◇ x)) ◇ w) ◇ u
equation 52347 := x ◇ y = ((x ◇ (z ◇ y)) ◇ x) ◇ x
equation 52348 := x ◇ y = ((x ◇ (z ◇ y)) ◇ x) ◇ y
equation 52349 := x ◇ y = ((x ◇ (z ◇ y)) ◇ x) ◇ z
equation 52350 := x ◇ y = ((x ◇ (z ◇ y)) ◇ x) ◇ w
equation 52351 := x ◇ y = ((x ◇ (z ◇ y)) ◇ y) ◇ x
equation 52352 := x ◇ y = ((x ◇ (z ◇ y)) ◇ y) ◇ y
equation 52353 := x ◇ y = ((x ◇ (z ◇ y)) ◇ y) ◇ z
equation 52354 := x ◇ y = ((x ◇ (z ◇ y)) ◇ y) ◇ w
equation 52355 := x ◇ y = ((x ◇ (z ◇ y)) ◇ z) ◇ x
equation 52356 := x ◇ y = ((x ◇ (z ◇ y)) ◇ z) ◇ y
equation 52357 := x ◇ y = ((x ◇ (z ◇ y)) ◇ z) ◇ z
equation 52358 := x ◇ y = ((x ◇ (z ◇ y)) ◇ z) ◇ w
equation 52359 := x ◇ y = ((x ◇ (z ◇ y)) ◇ w) ◇ x
equation 52360 := x ◇ y = ((x ◇ (z ◇ y)) ◇ w) ◇ y
equation 52361 := x ◇ y = ((x ◇ (z ◇ y)) ◇ w) ◇ z
equation 52362 := x ◇ y = ((x ◇ (z ◇ y)) ◇ w) ◇ w
equation 52363 := x ◇ y = ((x ◇ (z ◇ y)) ◇ w) ◇ u
equation 52364 := x ◇ y = ((x ◇ (z ◇ z)) ◇ x) ◇ x
equation 52365 := x ◇ y = ((x ◇ (z ◇ z)) ◇ x) ◇ y
equation 52366 := x ◇ y = ((x ◇ (z ◇ z)) ◇ x) ◇ z
equation 52367 := x ◇ y = ((x ◇ (z ◇ z)) ◇ x) ◇ w
equation 52368 := x ◇ y = ((x ◇ (z ◇ z)) ◇ y) ◇ x
equation 52369 := x ◇ y = ((x ◇ (z ◇ z)) ◇ y) ◇ y
equation 52370 := x ◇ y = ((x ◇ (z ◇ z)) ◇ y) ◇ z
equation 52371 := x ◇ y = ((x ◇ (z ◇ z)) ◇ y) ◇ w
equation 52372 := x ◇ y = ((x ◇ (z ◇ z)) ◇ z) ◇ x
equation 52373 := x ◇ y = ((x ◇ (z ◇ z)) ◇ z) ◇ y
equation 52374 := x ◇ y = ((x ◇ (z ◇ z)) ◇ z) ◇ z
equation 52375 := x ◇ y = ((x ◇ (z ◇ z)) ◇ z) ◇ w
equation 52376 := x ◇ y = ((x ◇ (z ◇ z)) ◇ w) ◇ x
equation 52377 := x ◇ y = ((x ◇ (z ◇ z)) ◇ w) ◇ y
equation 52378 := x ◇ y = ((x ◇ (z ◇ z)) ◇ w) ◇ z
equation 52379 := x ◇ y = ((x ◇ (z ◇ z)) ◇ w) ◇ w
equation 52380 := x ◇ y = ((x ◇ (z ◇ z)) ◇ w) ◇ u
equation 52381 := x ◇ y = ((x ◇ (z ◇ w)) ◇ x) ◇ x
equation 52382 := x ◇ y = ((x ◇ (z ◇ w)) ◇ x) ◇ y
equation 52383 := x ◇ y = ((x ◇ (z ◇ w)) ◇ x) ◇ z
equation 52384 := x ◇ y = ((x ◇ (z ◇ w)) ◇ x) ◇ w
equation 52385 := x ◇ y = ((x ◇ (z ◇ w)) ◇ x) ◇ u
equation 52386 := x ◇ y = ((x ◇ (z ◇ w)) ◇ y) ◇ x
equation 52387 := x ◇ y = ((x ◇ (z ◇ w)) ◇ y) ◇ y
equation 52388 := x ◇ y = ((x ◇ (z ◇ w)) ◇ y) ◇ z
equation 52389 := x ◇ y = ((x ◇ (z ◇ w)) ◇ y) ◇ w
equation 52390 := x ◇ y = ((x ◇ (z ◇ w)) ◇ y) ◇ u
equation 52391 := x ◇ y = ((x ◇ (z ◇ w)) ◇ z) ◇ x
equation 52392 := x ◇ y = ((x ◇ (z ◇ w)) ◇ z) ◇ y
equation 52393 := x ◇ y = ((x ◇ (z ◇ w)) ◇ z) ◇ z
equation 52394 := x ◇ y = ((x ◇ (z ◇ w)) ◇ z) ◇ w
equation 52395 := x ◇ y = ((x ◇ (z ◇ w)) ◇ z) ◇ u
equation 52396 := x ◇ y = ((x ◇ (z ◇ w)) ◇ w) ◇ x
equation 52397 := x ◇ y = ((x ◇ (z ◇ w)) ◇ w) ◇ y
equation 52398 := x ◇ y = ((x ◇ (z ◇ w)) ◇ w) ◇ z
equation 52399 := x ◇ y = ((x ◇ (z ◇ w)) ◇ w) ◇ w
equation 52400 := x ◇ y = ((x ◇ (z ◇ w)) ◇ w) ◇ u
equation 52401 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ x
equation 52402 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ y
equation 52403 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ z
equation 52404 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ w
equation 52405 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ u
equation 52406 := x ◇ y = ((x ◇ (z ◇ w)) ◇ u) ◇ v
equation 52407 := x ◇ y = ((y ◇ (x ◇ x)) ◇ x) ◇ x
equation 52408 := x ◇ y = ((y ◇ (x ◇ x)) ◇ x) ◇ y
equation 52409 := x ◇ y = ((y ◇ (x ◇ x)) ◇ x) ◇ z
equation 52410 := x ◇ y = ((y ◇ (x ◇ x)) ◇ y) ◇ x
equation 52411 := x ◇ y = ((y ◇ (x ◇ x)) ◇ y) ◇ y
equation 52412 := x ◇ y = ((y ◇ (x ◇ x)) ◇ y) ◇ z
equation 52413 := x ◇ y = ((y ◇ (x ◇ x)) ◇ z) ◇ x
equation 52414 := x ◇ y = ((y ◇ (x ◇ x)) ◇ z) ◇ y
equation 52415 := x ◇ y = ((y ◇ (x ◇ x)) ◇ z) ◇ z
equation 52416 := x ◇ y = ((y ◇ (x ◇ x)) ◇ z) ◇ w
equation 52417 := x ◇ y = ((y ◇ (x ◇ y)) ◇ x) ◇ x
equation 52418 := x ◇ y = ((y ◇ (x ◇ y)) ◇ x) ◇ y
equation 52419 := x ◇ y = ((y ◇ (x ◇ y)) ◇ x) ◇ z
equation 52420 := x ◇ y = ((y ◇ (x ◇ y)) ◇ y) ◇ x
equation 52421 := x ◇ y = ((y ◇ (x ◇ y)) ◇ y) ◇ y
equation 52422 := x ◇ y = ((y ◇ (x ◇ y)) ◇ y) ◇ z
equation 52423 := x ◇ y = ((y ◇ (x ◇ y)) ◇ z) ◇ x
equation 52424 := x ◇ y = ((y ◇ (x ◇ y)) ◇ z) ◇ y
equation 52425 := x ◇ y = ((y ◇ (x ◇ y)) ◇ z) ◇ z
equation 52426 := x ◇ y = ((y ◇ (x ◇ y)) ◇ z) ◇ w
equation 52427 := x ◇ y = ((y ◇ (x ◇ z)) ◇ x) ◇ x
equation 52428 := x ◇ y = ((y ◇ (x ◇ z)) ◇ x) ◇ y
equation 52429 := x ◇ y = ((y ◇ (x ◇ z)) ◇ x) ◇ z
equation 52430 := x ◇ y = ((y ◇ (x ◇ z)) ◇ x) ◇ w
equation 52431 := x ◇ y = ((y ◇ (x ◇ z)) ◇ y) ◇ x
equation 52432 := x ◇ y = ((y ◇ (x ◇ z)) ◇ y) ◇ y
equation 52433 := x ◇ y = ((y ◇ (x ◇ z)) ◇ y) ◇ z
equation 52434 := x ◇ y = ((y ◇ (x ◇ z)) ◇ y) ◇ w
equation 52435 := x ◇ y = ((y ◇ (x ◇ z)) ◇ z) ◇ x
equation 52436 := x ◇ y = ((y ◇ (x ◇ z)) ◇ z) ◇ y
equation 52437 := x ◇ y = ((y ◇ (x ◇ z)) ◇ z) ◇ z
equation 52438 := x ◇ y = ((y ◇ (x ◇ z)) ◇ z) ◇ w
equation 52439 := x ◇ y = ((y ◇ (x ◇ z)) ◇ w) ◇ x
equation 52440 := x ◇ y = ((y ◇ (x ◇ z)) ◇ w) ◇ y
equation 52441 := x ◇ y = ((y ◇ (x ◇ z)) ◇ w) ◇ z
equation 52442 := x ◇ y = ((y ◇ (x ◇ z)) ◇ w) ◇ w
equation 52443 := x ◇ y = ((y ◇ (x ◇ z)) ◇ w) ◇ u
equation 52444 := x ◇ y = ((y ◇ (y ◇ x)) ◇ x) ◇ x
equation 52445 := x ◇ y = ((y ◇ (y ◇ x)) ◇ x) ◇ y
equation 52446 := x ◇ y = ((y ◇ (y ◇ x)) ◇ x) ◇ z
equation 52447 := x ◇ y = ((y ◇ (y ◇ x)) ◇ y) ◇ x
equation 52448 := x ◇ y = ((y ◇ (y ◇ x)) ◇ y) ◇ y
equation 52449 := x ◇ y = ((y ◇ (y ◇ x)) ◇ y) ◇ z
equation 52450 := x ◇ y = ((y ◇ (y ◇ x)) ◇ z) ◇ x
equation 52451 := x ◇ y = ((y ◇ (y ◇ x)) ◇ z) ◇ y
equation 52452 := x ◇ y = ((y ◇ (y ◇ x)) ◇ z) ◇ z
equation 52453 := x ◇ y = ((y ◇ (y ◇ x)) ◇ z) ◇ w
equation 52454 := x ◇ y = ((y ◇ (y ◇ y)) ◇ x) ◇ x
equation 52455 := x ◇ y = ((y ◇ (y ◇ y)) ◇ x) ◇ y
equation 52456 := x ◇ y = ((y ◇ (y ◇ y)) ◇ x) ◇ z
equation 52457 := x ◇ y = ((y ◇ (y ◇ y)) ◇ y) ◇ x
equation 52458 := x ◇ y = ((y ◇ (y ◇ y)) ◇ y) ◇ y
equation 52459 := x ◇ y = ((y ◇ (y ◇ y)) ◇ y) ◇ z
equation 52460 := x ◇ y = ((y ◇ (y ◇ y)) ◇ z) ◇ x
equation 52461 := x ◇ y = ((y ◇ (y ◇ y)) ◇ z) ◇ y
equation 52462 := x ◇ y = ((y ◇ (y ◇ y)) ◇ z) ◇ z
equation 52463 := x ◇ y = ((y ◇ (y ◇ y)) ◇ z) ◇ w
equation 52464 := x ◇ y = ((y ◇ (y ◇ z)) ◇ x) ◇ x
equation 52465 := x ◇ y = ((y ◇ (y ◇ z)) ◇ x) ◇ y
equation 52466 := x ◇ y = ((y ◇ (y ◇ z)) ◇ x) ◇ z
equation 52467 := x ◇ y = ((y ◇ (y ◇ z)) ◇ x) ◇ w
equation 52468 := x ◇ y = ((y ◇ (y ◇ z)) ◇ y) ◇ x
equation 52469 := x ◇ y = ((y ◇ (y ◇ z)) ◇ y) ◇ y
equation 52470 := x ◇ y = ((y ◇ (y ◇ z)) ◇ y) ◇ z
equation 52471 := x ◇ y = ((y ◇ (y ◇ z)) ◇ y) ◇ w
equation 52472 := x ◇ y = ((y ◇ (y ◇ z)) ◇ z) ◇ x
equation 52473 := x ◇ y = ((y ◇ (y ◇ z)) ◇ z) ◇ y
equation 52474 := x ◇ y = ((y ◇ (y ◇ z)) ◇ z) ◇ z
equation 52475 := x ◇ y = ((y ◇ (y ◇ z)) ◇ z) ◇ w
equation 52476 := x ◇ y = ((y ◇ (y ◇ z)) ◇ w) ◇ x
equation 52477 := x ◇ y = ((y ◇ (y ◇ z)) ◇ w) ◇ y
equation 52478 := x ◇ y = ((y ◇ (y ◇ z)) ◇ w) ◇ z
equation 52479 := x ◇ y = ((y ◇ (y ◇ z)) ◇ w) ◇ w
equation 52480 := x ◇ y = ((y ◇ (y ◇ z)) ◇ w) ◇ u
equation 52481 := x ◇ y = ((y ◇ (z ◇ x)) ◇ x) ◇ x
equation 52482 := x ◇ y = ((y ◇ (z ◇ x)) ◇ x) ◇ y
equation 52483 := x ◇ y = ((y ◇ (z ◇ x)) ◇ x) ◇ z
equation 52484 := x ◇ y = ((y ◇ (z ◇ x)) ◇ x) ◇ w
equation 52485 := x ◇ y = ((y ◇ (z ◇ x)) ◇ y) ◇ x
equation 52486 := x ◇ y = ((y ◇ (z ◇ x)) ◇ y) ◇ y
equation 52487 := x ◇ y = ((y ◇ (z ◇ x)) ◇ y) ◇ z
equation 52488 := x ◇ y = ((y ◇ (z ◇ x)) ◇ y) ◇ w
equation 52489 := x ◇ y = ((y ◇ (z ◇ x)) ◇ z) ◇ x
equation 52490 := x ◇ y = ((y ◇ (z ◇ x)) ◇ z) ◇ y
equation 52491 := x ◇ y = ((y ◇ (z ◇ x)) ◇ z) ◇ z
equation 52492 := x ◇ y = ((y ◇ (z ◇ x)) ◇ z) ◇ w
equation 52493 := x ◇ y = ((y ◇ (z ◇ x)) ◇ w) ◇ x
equation 52494 := x ◇ y = ((y ◇ (z ◇ x)) ◇ w) ◇ y
equation 52495 := x ◇ y = ((y ◇ (z ◇ x)) ◇ w) ◇ z
equation 52496 := x ◇ y = ((y ◇ (z ◇ x)) ◇ w) ◇ w
equation 52497 := x ◇ y = ((y ◇ (z ◇ x)) ◇ w) ◇ u
equation 52498 := x ◇ y = ((y ◇ (z ◇ y)) ◇ x) ◇ x
equation 52499 := x ◇ y = ((y ◇ (z ◇ y)) ◇ x) ◇ y
equation 52500 := x ◇ y = ((y ◇ (z ◇ y)) ◇ x) ◇ z
equation 52501 := x ◇ y = ((y ◇ (z ◇ y)) ◇ x) ◇ w
equation 52502 := x ◇ y = ((y ◇ (z ◇ y)) ◇ y) ◇ x
equation 52503 := x ◇ y = ((y ◇ (z ◇ y)) ◇ y) ◇ y
equation 52504 := x ◇ y = ((y ◇ (z ◇ y)) ◇ y) ◇ z
equation 52505 := x ◇ y = ((y ◇ (z ◇ y)) ◇ y) ◇ w
equation 52506 := x ◇ y = ((y ◇ (z ◇ y)) ◇ z) ◇ x
equation 52507 := x ◇ y = ((y ◇ (z ◇ y)) ◇ z) ◇ y
equation 52508 := x ◇ y = ((y ◇ (z ◇ y)) ◇ z) ◇ z
equation 52509 := x ◇ y = ((y ◇ (z ◇ y)) ◇ z) ◇ w
equation 52510 := x ◇ y = ((y ◇ (z ◇ y)) ◇ w) ◇ x
equation 52511 := x ◇ y = ((y ◇ (z ◇ y)) ◇ w) ◇ y
equation 52512 := x ◇ y = ((y ◇ (z ◇ y)) ◇ w) ◇ z
equation 52513 := x ◇ y = ((y ◇ (z ◇ y)) ◇ w) ◇ w
equation 52514 := x ◇ y = ((y ◇ (z ◇ y)) ◇ w) ◇ u
equation 52515 := x ◇ y = ((y ◇ (z ◇ z)) ◇ x) ◇ x
equation 52516 := x ◇ y = ((y ◇ (z ◇ z)) ◇ x) ◇ y
equation 52517 := x ◇ y = ((y ◇ (z ◇ z)) ◇ x) ◇ z
equation 52518 := x ◇ y = ((y ◇ (z ◇ z)) ◇ x) ◇ w
equation 52519 := x ◇ y = ((y ◇ (z ◇ z)) ◇ y) ◇ x
equation 52520 := x ◇ y = ((y ◇ (z ◇ z)) ◇ y) ◇ y
equation 52521 := x ◇ y = ((y ◇ (z ◇ z)) ◇ y) ◇ z
equation 52522 := x ◇ y = ((y ◇ (z ◇ z)) ◇ y) ◇ w
equation 52523 := x ◇ y = ((y ◇ (z ◇ z)) ◇ z) ◇ x
equation 52524 := x ◇ y = ((y ◇ (z ◇ z)) ◇ z) ◇ y
equation 52525 := x ◇ y = ((y ◇ (z ◇ z)) ◇ z) ◇ z
equation 52526 := x ◇ y = ((y ◇ (z ◇ z)) ◇ z) ◇ w
equation 52527 := x ◇ y = ((y ◇ (z ◇ z)) ◇ w) ◇ x
equation 52528 := x ◇ y = ((y ◇ (z ◇ z)) ◇ w) ◇ y
equation 52529 := x ◇ y = ((y ◇ (z ◇ z)) ◇ w) ◇ z
equation 52530 := x ◇ y = ((y ◇ (z ◇ z)) ◇ w) ◇ w
equation 52531 := x ◇ y = ((y ◇ (z ◇ z)) ◇ w) ◇ u
equation 52532 := x ◇ y = ((y ◇ (z ◇ w)) ◇ x) ◇ x
equation 52533 := x ◇ y = ((y ◇ (z ◇ w)) ◇ x) ◇ y
equation 52534 := x ◇ y = ((y ◇ (z ◇ w)) ◇ x) ◇ z
equation 52535 := x ◇ y = ((y ◇ (z ◇ w)) ◇ x) ◇ w
equation 52536 := x ◇ y = ((y ◇ (z ◇ w)) ◇ x) ◇ u
equation 52537 := x ◇ y = ((y ◇ (z ◇ w)) ◇ y) ◇ x
equation 52538 := x ◇ y = ((y ◇ (z ◇ w)) ◇ y) ◇ y
equation 52539 := x ◇ y = ((y ◇ (z ◇ w)) ◇ y) ◇ z
equation 52540 := x ◇ y = ((y ◇ (z ◇ w)) ◇ y) ◇ w
equation 52541 := x ◇ y = ((y ◇ (z ◇ w)) ◇ y) ◇ u
equation 52542 := x ◇ y = ((y ◇ (z ◇ w)) ◇ z) ◇ x
equation 52543 := x ◇ y = ((y ◇ (z ◇ w)) ◇ z) ◇ y
equation 52544 := x ◇ y = ((y ◇ (z ◇ w)) ◇ z) ◇ z
equation 52545 := x ◇ y = ((y ◇ (z ◇ w)) ◇ z) ◇ w
equation 52546 := x ◇ y = ((y ◇ (z ◇ w)) ◇ z) ◇ u
equation 52547 := x ◇ y = ((y ◇ (z ◇ w)) ◇ w) ◇ x
equation 52548 := x ◇ y = ((y ◇ (z ◇ w)) ◇ w) ◇ y
equation 52549 := x ◇ y = ((y ◇ (z ◇ w)) ◇ w) ◇ z
equation 52550 := x ◇ y = ((y ◇ (z ◇ w)) ◇ w) ◇ w
equation 52551 := x ◇ y = ((y ◇ (z ◇ w)) ◇ w) ◇ u
equation 52552 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ x
equation 52553 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ y
equation 52554 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ z
equation 52555 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ w
equation 52556 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ u
equation 52557 := x ◇ y = ((y ◇ (z ◇ w)) ◇ u) ◇ v
equation 52558 := x ◇ y = ((z ◇ (x ◇ x)) ◇ x) ◇ x
equation 52559 := x ◇ y = ((z ◇ (x ◇ x)) ◇ x) ◇ y
equation 52560 := x ◇ y = ((z ◇ (x ◇ x)) ◇ x) ◇ z
equation 52561 := x ◇ y = ((z ◇ (x ◇ x)) ◇ x) ◇ w
equation 52562 := x ◇ y = ((z ◇ (x ◇ x)) ◇ y) ◇ x
equation 52563 := x ◇ y = ((z ◇ (x ◇ x)) ◇ y) ◇ y
equation 52564 := x ◇ y = ((z ◇ (x ◇ x)) ◇ y) ◇ z
equation 52565 := x ◇ y = ((z ◇ (x ◇ x)) ◇ y) ◇ w
equation 52566 := x ◇ y = ((z ◇ (x ◇ x)) ◇ z) ◇ x
equation 52567 := x ◇ y = ((z ◇ (x ◇ x)) ◇ z) ◇ y
equation 52568 := x ◇ y = ((z ◇ (x ◇ x)) ◇ z) ◇ z
equation 52569 := x ◇ y = ((z ◇ (x ◇ x)) ◇ z) ◇ w
equation 52570 := x ◇ y = ((z ◇ (x ◇ x)) ◇ w) ◇ x
equation 52571 := x ◇ y = ((z ◇ (x ◇ x)) ◇ w) ◇ y
equation 52572 := x ◇ y = ((z ◇ (x ◇ x)) ◇ w) ◇ z
equation 52573 := x ◇ y = ((z ◇ (x ◇ x)) ◇ w) ◇ w
equation 52574 := x ◇ y = ((z ◇ (x ◇ x)) ◇ w) ◇ u
equation 52575 := x ◇ y = ((z ◇ (x ◇ y)) ◇ x) ◇ x
equation 52576 := x ◇ y = ((z ◇ (x ◇ y)) ◇ x) ◇ y
equation 52577 := x ◇ y = ((z ◇ (x ◇ y)) ◇ x) ◇ z
equation 52578 := x ◇ y = ((z ◇ (x ◇ y)) ◇ x) ◇ w
equation 52579 := x ◇ y = ((z ◇ (x ◇ y)) ◇ y) ◇ x
equation 52580 := x ◇ y = ((z ◇ (x ◇ y)) ◇ y) ◇ y
equation 52581 := x ◇ y = ((z ◇ (x ◇ y)) ◇ y) ◇ z
equation 52582 := x ◇ y = ((z ◇ (x ◇ y)) ◇ y) ◇ w
equation 52583 := x ◇ y = ((z ◇ (x ◇ y)) ◇ z) ◇ x
equation 52584 := x ◇ y = ((z ◇ (x ◇ y)) ◇ z) ◇ y
equation 52585 := x ◇ y = ((z ◇ (x ◇ y)) ◇ z) ◇ z
equation 52586 := x ◇ y = ((z ◇ (x ◇ y)) ◇ z) ◇ w
equation 52587 := x ◇ y = ((z ◇ (x ◇ y)) ◇ w) ◇ x
equation 52588 := x ◇ y = ((z ◇ (x ◇ y)) ◇ w) ◇ y
equation 52589 := x ◇ y = ((z ◇ (x ◇ y)) ◇ w) ◇ z
equation 52590 := x ◇ y = ((z ◇ (x ◇ y)) ◇ w) ◇ w
equation 52591 := x ◇ y = ((z ◇ (x ◇ y)) ◇ w) ◇ u
equation 52592 := x ◇ y = ((z ◇ (x ◇ z)) ◇ x) ◇ x
equation 52593 := x ◇ y = ((z ◇ (x ◇ z)) ◇ x) ◇ y
equation 52594 := x ◇ y = ((z ◇ (x ◇ z)) ◇ x) ◇ z
equation 52595 := x ◇ y = ((z ◇ (x ◇ z)) ◇ x) ◇ w
equation 52596 := x ◇ y = ((z ◇ (x ◇ z)) ◇ y) ◇ x
equation 52597 := x ◇ y = ((z ◇ (x ◇ z)) ◇ y) ◇ y
equation 52598 := x ◇ y = ((z ◇ (x ◇ z)) ◇ y) ◇ z
equation 52599 := x ◇ y = ((z ◇ (x ◇ z)) ◇ y) ◇ w
equation 52600 := x ◇ y = ((z ◇ (x ◇ z)) ◇ z) ◇ x
equation 52601 := x ◇ y = ((z ◇ (x ◇ z)) ◇ z) ◇ y
equation 52602 := x ◇ y = ((z ◇ (x ◇ z)) ◇ z) ◇ z
equation 52603 := x ◇ y = ((z ◇ (x ◇ z)) ◇ z) ◇ w
equation 52604 := x ◇ y = ((z ◇ (x ◇ z)) ◇ w) ◇ x
equation 52605 := x ◇ y = ((z ◇ (x ◇ z)) ◇ w) ◇ y
equation 52606 := x ◇ y = ((z ◇ (x ◇ z)) ◇ w) ◇ z
equation 52607 := x ◇ y = ((z ◇ (x ◇ z)) ◇ w) ◇ w
equation 52608 := x ◇ y = ((z ◇ (x ◇ z)) ◇ w) ◇ u
equation 52609 := x ◇ y = ((z ◇ (x ◇ w)) ◇ x) ◇ x
equation 52610 := x ◇ y = ((z ◇ (x ◇ w)) ◇ x) ◇ y
equation 52611 := x ◇ y = ((z ◇ (x ◇ w)) ◇ x) ◇ z
equation 52612 := x ◇ y = ((z ◇ (x ◇ w)) ◇ x) ◇ w
equation 52613 := x ◇ y = ((z ◇ (x ◇ w)) ◇ x) ◇ u
equation 52614 := x ◇ y = ((z ◇ (x ◇ w)) ◇ y) ◇ x
equation 52615 := x ◇ y = ((z ◇ (x ◇ w)) ◇ y) ◇ y
equation 52616 := x ◇ y = ((z ◇ (x ◇ w)) ◇ y) ◇ z
equation 52617 := x ◇ y = ((z ◇ (x ◇ w)) ◇ y) ◇ w
equation 52618 := x ◇ y = ((z ◇ (x ◇ w)) ◇ y) ◇ u
equation 52619 := x ◇ y = ((z ◇ (x ◇ w)) ◇ z) ◇ x
equation 52620 := x ◇ y = ((z ◇ (x ◇ w)) ◇ z) ◇ y
equation 52621 := x ◇ y = ((z ◇ (x ◇ w)) ◇ z) ◇ z
equation 52622 := x ◇ y = ((z ◇ (x ◇ w)) ◇ z) ◇ w
equation 52623 := x ◇ y = ((z ◇ (x ◇ w)) ◇ z) ◇ u
equation 52624 := x ◇ y = ((z ◇ (x ◇ w)) ◇ w) ◇ x
equation 52625 := x ◇ y = ((z ◇ (x ◇ w)) ◇ w) ◇ y
equation 52626 := x ◇ y = ((z ◇ (x ◇ w)) ◇ w) ◇ z
equation 52627 := x ◇ y = ((z ◇ (x ◇ w)) ◇ w) ◇ w
equation 52628 := x ◇ y = ((z ◇ (x ◇ w)) ◇ w) ◇ u
equation 52629 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ x
equation 52630 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ y
equation 52631 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ z
equation 52632 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ w
equation 52633 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ u
equation 52634 := x ◇ y = ((z ◇ (x ◇ w)) ◇ u) ◇ v
equation 52635 := x ◇ y = ((z ◇ (y ◇ x)) ◇ x) ◇ x
equation 52636 := x ◇ y = ((z ◇ (y ◇ x)) ◇ x) ◇ y
equation 52637 := x ◇ y = ((z ◇ (y ◇ x)) ◇ x) ◇ z
equation 52638 := x ◇ y = ((z ◇ (y ◇ x)) ◇ x) ◇ w
equation 52639 := x ◇ y = ((z ◇ (y ◇ x)) ◇ y) ◇ x
equation 52640 := x ◇ y = ((z ◇ (y ◇ x)) ◇ y) ◇ y
equation 52641 := x ◇ y = ((z ◇ (y ◇ x)) ◇ y) ◇ z
equation 52642 := x ◇ y = ((z ◇ (y ◇ x)) ◇ y) ◇ w
equation 52643 := x ◇ y = ((z ◇ (y ◇ x)) ◇ z) ◇ x
equation 52644 := x ◇ y = ((z ◇ (y ◇ x)) ◇ z) ◇ y
equation 52645 := x ◇ y = ((z ◇ (y ◇ x)) ◇ z) ◇ z
equation 52646 := x ◇ y = ((z ◇ (y ◇ x)) ◇ z) ◇ w
equation 52647 := x ◇ y = ((z ◇ (y ◇ x)) ◇ w) ◇ x
equation 52648 := x ◇ y = ((z ◇ (y ◇ x)) ◇ w) ◇ y
equation 52649 := x ◇ y = ((z ◇ (y ◇ x)) ◇ w) ◇ z
equation 52650 := x ◇ y = ((z ◇ (y ◇ x)) ◇ w) ◇ w
equation 52651 := x ◇ y = ((z ◇ (y ◇ x)) ◇ w) ◇ u
equation 52652 := x ◇ y = ((z ◇ (y ◇ y)) ◇ x) ◇ x
equation 52653 := x ◇ y = ((z ◇ (y ◇ y)) ◇ x) ◇ y
equation 52654 := x ◇ y = ((z ◇ (y ◇ y)) ◇ x) ◇ z
equation 52655 := x ◇ y = ((z ◇ (y ◇ y)) ◇ x) ◇ w
equation 52656 := x ◇ y = ((z ◇ (y ◇ y)) ◇ y) ◇ x
equation 52657 := x ◇ y = ((z ◇ (y ◇ y)) ◇ y) ◇ y
equation 52658 := x ◇ y = ((z ◇ (y ◇ y)) ◇ y) ◇ z
equation 52659 := x ◇ y = ((z ◇ (y ◇ y)) ◇ y) ◇ w
equation 52660 := x ◇ y = ((z ◇ (y ◇ y)) ◇ z) ◇ x
equation 52661 := x ◇ y = ((z ◇ (y ◇ y)) ◇ z) ◇ y
equation 52662 := x ◇ y = ((z ◇ (y ◇ y)) ◇ z) ◇ z
equation 52663 := x ◇ y = ((z ◇ (y ◇ y)) ◇ z) ◇ w
equation 52664 := x ◇ y = ((z ◇ (y ◇ y)) ◇ w) ◇ x
equation 52665 := x ◇ y = ((z ◇ (y ◇ y)) ◇ w) ◇ y
equation 52666 := x ◇ y = ((z ◇ (y ◇ y)) ◇ w) ◇ z
equation 52667 := x ◇ y = ((z ◇ (y ◇ y)) ◇ w) ◇ w
equation 52668 := x ◇ y = ((z ◇ (y ◇ y)) ◇ w) ◇ u
equation 52669 := x ◇ y = ((z ◇ (y ◇ z)) ◇ x) ◇ x
equation 52670 := x ◇ y = ((z ◇ (y ◇ z)) ◇ x) ◇ y
equation 52671 := x ◇ y = ((z ◇ (y ◇ z)) ◇ x) ◇ z
equation 52672 := x ◇ y = ((z ◇ (y ◇ z)) ◇ x) ◇ w
equation 52673 := x ◇ y = ((z ◇ (y ◇ z)) ◇ y) ◇ x
equation 52674 := x ◇ y = ((z ◇ (y ◇ z)) ◇ y) ◇ y
equation 52675 := x ◇ y = ((z ◇ (y ◇ z)) ◇ y) ◇ z
equation 52676 := x ◇ y = ((z ◇ (y ◇ z)) ◇ y) ◇ w
equation 52677 := x ◇ y = ((z ◇ (y ◇ z)) ◇ z) ◇ x
equation 52678 := x ◇ y = ((z ◇ (y ◇ z)) ◇ z) ◇ y
equation 52679 := x ◇ y = ((z ◇ (y ◇ z)) ◇ z) ◇ z
equation 52680 := x ◇ y = ((z ◇ (y ◇ z)) ◇ z) ◇ w
equation 52681 := x ◇ y = ((z ◇ (y ◇ z)) ◇ w) ◇ x
equation 52682 := x ◇ y = ((z ◇ (y ◇ z)) ◇ w) ◇ y
equation 52683 := x ◇ y = ((z ◇ (y ◇ z)) ◇ w) ◇ z
equation 52684 := x ◇ y = ((z ◇ (y ◇ z)) ◇ w) ◇ w
equation 52685 := x ◇ y = ((z ◇ (y ◇ z)) ◇ w) ◇ u
equation 52686 := x ◇ y = ((z ◇ (y ◇ w)) ◇ x) ◇ x
equation 52687 := x ◇ y = ((z ◇ (y ◇ w)) ◇ x) ◇ y
equation 52688 := x ◇ y = ((z ◇ (y ◇ w)) ◇ x) ◇ z
equation 52689 := x ◇ y = ((z ◇ (y ◇ w)) ◇ x) ◇ w
equation 52690 := x ◇ y = ((z ◇ (y ◇ w)) ◇ x) ◇ u
equation 52691 := x ◇ y = ((z ◇ (y ◇ w)) ◇ y) ◇ x
equation 52692 := x ◇ y = ((z ◇ (y ◇ w)) ◇ y) ◇ y
equation 52693 := x ◇ y = ((z ◇ (y ◇ w)) ◇ y) ◇ z
equation 52694 := x ◇ y = ((z ◇ (y ◇ w)) ◇ y) ◇ w
equation 52695 := x ◇ y = ((z ◇ (y ◇ w)) ◇ y) ◇ u
equation 52696 := x ◇ y = ((z ◇ (y ◇ w)) ◇ z) ◇ x
equation 52697 := x ◇ y = ((z ◇ (y ◇ w)) ◇ z) ◇ y
equation 52698 := x ◇ y = ((z ◇ (y ◇ w)) ◇ z) ◇ z
equation 52699 := x ◇ y = ((z ◇ (y ◇ w)) ◇ z) ◇ w
equation 52700 := x ◇ y = ((z ◇ (y ◇ w)) ◇ z) ◇ u
equation 52701 := x ◇ y = ((z ◇ (y ◇ w)) ◇ w) ◇ x
equation 52702 := x ◇ y = ((z ◇ (y ◇ w)) ◇ w) ◇ y
equation 52703 := x ◇ y = ((z ◇ (y ◇ w)) ◇ w) ◇ z
equation 52704 := x ◇ y = ((z ◇ (y ◇ w)) ◇ w) ◇ w
equation 52705 := x ◇ y = ((z ◇ (y ◇ w)) ◇ w) ◇ u
equation 52706 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ x
equation 52707 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ y
equation 52708 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ z
equation 52709 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ w
equation 52710 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ u
equation 52711 := x ◇ y = ((z ◇ (y ◇ w)) ◇ u) ◇ v
equation 52712 := x ◇ y = ((z ◇ (z ◇ x)) ◇ x) ◇ x
equation 52713 := x ◇ y = ((z ◇ (z ◇ x)) ◇ x) ◇ y
equation 52714 := x ◇ y = ((z ◇ (z ◇ x)) ◇ x) ◇ z
equation 52715 := x ◇ y = ((z ◇ (z ◇ x)) ◇ x) ◇ w
equation 52716 := x ◇ y = ((z ◇ (z ◇ x)) ◇ y) ◇ x
equation 52717 := x ◇ y = ((z ◇ (z ◇ x)) ◇ y) ◇ y
equation 52718 := x ◇ y = ((z ◇ (z ◇ x)) ◇ y) ◇ z
equation 52719 := x ◇ y = ((z ◇ (z ◇ x)) ◇ y) ◇ w
equation 52720 := x ◇ y = ((z ◇ (z ◇ x)) ◇ z) ◇ x
equation 52721 := x ◇ y = ((z ◇ (z ◇ x)) ◇ z) ◇ y
equation 52722 := x ◇ y = ((z ◇ (z ◇ x)) ◇ z) ◇ z
equation 52723 := x ◇ y = ((z ◇ (z ◇ x)) ◇ z) ◇ w
equation 52724 := x ◇ y = ((z ◇ (z ◇ x)) ◇ w) ◇ x
equation 52725 := x ◇ y = ((z ◇ (z ◇ x)) ◇ w) ◇ y
equation 52726 := x ◇ y = ((z ◇ (z ◇ x)) ◇ w) ◇ z
equation 52727 := x ◇ y = ((z ◇ (z ◇ x)) ◇ w) ◇ w
equation 52728 := x ◇ y = ((z ◇ (z ◇ x)) ◇ w) ◇ u
equation 52729 := x ◇ y = ((z ◇ (z ◇ y)) ◇ x) ◇ x
equation 52730 := x ◇ y = ((z ◇ (z ◇ y)) ◇ x) ◇ y
equation 52731 := x ◇ y = ((z ◇ (z ◇ y)) ◇ x) ◇ z
equation 52732 := x ◇ y = ((z ◇ (z ◇ y)) ◇ x) ◇ w
equation 52733 := x ◇ y = ((z ◇ (z ◇ y)) ◇ y) ◇ x
equation 52734 := x ◇ y = ((z ◇ (z ◇ y)) ◇ y) ◇ y
equation 52735 := x ◇ y = ((z ◇ (z ◇ y)) ◇ y) ◇ z
equation 52736 := x ◇ y = ((z ◇ (z ◇ y)) ◇ y) ◇ w
equation 52737 := x ◇ y = ((z ◇ (z ◇ y)) ◇ z) ◇ x
equation 52738 := x ◇ y = ((z ◇ (z ◇ y)) ◇ z) ◇ y
equation 52739 := x ◇ y = ((z ◇ (z ◇ y)) ◇ z) ◇ z
equation 52740 := x ◇ y = ((z ◇ (z ◇ y)) ◇ z) ◇ w
equation 52741 := x ◇ y = ((z ◇ (z ◇ y)) ◇ w) ◇ x
equation 52742 := x ◇ y = ((z ◇ (z ◇ y)) ◇ w) ◇ y
equation 52743 := x ◇ y = ((z ◇ (z ◇ y)) ◇ w) ◇ z
equation 52744 := x ◇ y = ((z ◇ (z ◇ y)) ◇ w) ◇ w
equation 52745 := x ◇ y = ((z ◇ (z ◇ y)) ◇ w) ◇ u
equation 52746 := x ◇ y = ((z ◇ (z ◇ z)) ◇ x) ◇ x
equation 52747 := x ◇ y = ((z ◇ (z ◇ z)) ◇ x) ◇ y
equation 52748 := x ◇ y = ((z ◇ (z ◇ z)) ◇ x) ◇ z
equation 52749 := x ◇ y = ((z ◇ (z ◇ z)) ◇ x) ◇ w
equation 52750 := x ◇ y = ((z ◇ (z ◇ z)) ◇ y) ◇ x
equation 52751 := x ◇ y = ((z ◇ (z ◇ z)) ◇ y) ◇ y
equation 52752 := x ◇ y = ((z ◇ (z ◇ z)) ◇ y) ◇ z
equation 52753 := x ◇ y = ((z ◇ (z ◇ z)) ◇ y) ◇ w
equation 52754 := x ◇ y = ((z ◇ (z ◇ z)) ◇ z) ◇ x
equation 52755 := x ◇ y = ((z ◇ (z ◇ z)) ◇ z) ◇ y
equation 52756 := x ◇ y = ((z ◇ (z ◇ z)) ◇ z) ◇ z
equation 52757 := x ◇ y = ((z ◇ (z ◇ z)) ◇ z) ◇ w
equation 52758 := x ◇ y = ((z ◇ (z ◇ z)) ◇ w) ◇ x
equation 52759 := x ◇ y = ((z ◇ (z ◇ z)) ◇ w) ◇ y
equation 52760 := x ◇ y = ((z ◇ (z ◇ z)) ◇ w) ◇ z
equation 52761 := x ◇ y = ((z ◇ (z ◇ z)) ◇ w) ◇ w
equation 52762 := x ◇ y = ((z ◇ (z ◇ z)) ◇ w) ◇ u
equation 52763 := x ◇ y = ((z ◇ (z ◇ w)) ◇ x) ◇ x
equation 52764 := x ◇ y = ((z ◇ (z ◇ w)) ◇ x) ◇ y
equation 52765 := x ◇ y = ((z ◇ (z ◇ w)) ◇ x) ◇ z
equation 52766 := x ◇ y = ((z ◇ (z ◇ w)) ◇ x) ◇ w
equation 52767 := x ◇ y = ((z ◇ (z ◇ w)) ◇ x) ◇ u
equation 52768 := x ◇ y = ((z ◇ (z ◇ w)) ◇ y) ◇ x
equation 52769 := x ◇ y = ((z ◇ (z ◇ w)) ◇ y) ◇ y
equation 52770 := x ◇ y = ((z ◇ (z ◇ w)) ◇ y) ◇ z
equation 52771 := x ◇ y = ((z ◇ (z ◇ w)) ◇ y) ◇ w
equation 52772 := x ◇ y = ((z ◇ (z ◇ w)) ◇ y) ◇ u
equation 52773 := x ◇ y = ((z ◇ (z ◇ w)) ◇ z) ◇ x
equation 52774 := x ◇ y = ((z ◇ (z ◇ w)) ◇ z) ◇ y
equation 52775 := x ◇ y = ((z ◇ (z ◇ w)) ◇ z) ◇ z
equation 52776 := x ◇ y = ((z ◇ (z ◇ w)) ◇ z) ◇ w
equation 52777 := x ◇ y = ((z ◇ (z ◇ w)) ◇ z) ◇ u
equation 52778 := x ◇ y = ((z ◇ (z ◇ w)) ◇ w) ◇ x
equation 52779 := x ◇ y = ((z ◇ (z ◇ w)) ◇ w) ◇ y
equation 52780 := x ◇ y = ((z ◇ (z ◇ w)) ◇ w) ◇ z
equation 52781 := x ◇ y = ((z ◇ (z ◇ w)) ◇ w) ◇ w
equation 52782 := x ◇ y = ((z ◇ (z ◇ w)) ◇ w) ◇ u
equation 52783 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ x
equation 52784 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ y
equation 52785 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ z
equation 52786 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ w
equation 52787 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ u
equation 52788 := x ◇ y = ((z ◇ (z ◇ w)) ◇ u) ◇ v
equation 52789 := x ◇ y = ((z ◇ (w ◇ x)) ◇ x) ◇ x
equation 52790 := x ◇ y = ((z ◇ (w ◇ x)) ◇ x) ◇ y
equation 52791 := x ◇ y = ((z ◇ (w ◇ x)) ◇ x) ◇ z
equation 52792 := x ◇ y = ((z ◇ (w ◇ x)) ◇ x) ◇ w
equation 52793 := x ◇ y = ((z ◇ (w ◇ x)) ◇ x) ◇ u
equation 52794 := x ◇ y = ((z ◇ (w ◇ x)) ◇ y) ◇ x
equation 52795 := x ◇ y = ((z ◇ (w ◇ x)) ◇ y) ◇ y
equation 52796 := x ◇ y = ((z ◇ (w ◇ x)) ◇ y) ◇ z
equation 52797 := x ◇ y = ((z ◇ (w ◇ x)) ◇ y) ◇ w
equation 52798 := x ◇ y = ((z ◇ (w ◇ x)) ◇ y) ◇ u
equation 52799 := x ◇ y = ((z ◇ (w ◇ x)) ◇ z) ◇ x
equation 52800 := x ◇ y = ((z ◇ (w ◇ x)) ◇ z) ◇ y
equation 52801 := x ◇ y = ((z ◇ (w ◇ x)) ◇ z) ◇ z
equation 52802 := x ◇ y = ((z ◇ (w ◇ x)) ◇ z) ◇ w
equation 52803 := x ◇ y = ((z ◇ (w ◇ x)) ◇ z) ◇ u
equation 52804 := x ◇ y = ((z ◇ (w ◇ x)) ◇ w) ◇ x
equation 52805 := x ◇ y = ((z ◇ (w ◇ x)) ◇ w) ◇ y
equation 52806 := x ◇ y = ((z ◇ (w ◇ x)) ◇ w) ◇ z
equation 52807 := x ◇ y = ((z ◇ (w ◇ x)) ◇ w) ◇ w
equation 52808 := x ◇ y = ((z ◇ (w ◇ x)) ◇ w) ◇ u
equation 52809 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ x
equation 52810 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ y
equation 52811 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ z
equation 52812 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ w
equation 52813 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ u
equation 52814 := x ◇ y = ((z ◇ (w ◇ x)) ◇ u) ◇ v
equation 52815 := x ◇ y = ((z ◇ (w ◇ y)) ◇ x) ◇ x
equation 52816 := x ◇ y = ((z ◇ (w ◇ y)) ◇ x) ◇ y
equation 52817 := x ◇ y = ((z ◇ (w ◇ y)) ◇ x) ◇ z
equation 52818 := x ◇ y = ((z ◇ (w ◇ y)) ◇ x) ◇ w
equation 52819 := x ◇ y = ((z ◇ (w ◇ y)) ◇ x) ◇ u
equation 52820 := x ◇ y = ((z ◇ (w ◇ y)) ◇ y) ◇ x
equation 52821 := x ◇ y = ((z ◇ (w ◇ y)) ◇ y) ◇ y
equation 52822 := x ◇ y = ((z ◇ (w ◇ y)) ◇ y) ◇ z
equation 52823 := x ◇ y = ((z ◇ (w ◇ y)) ◇ y) ◇ w
equation 52824 := x ◇ y = ((z ◇ (w ◇ y)) ◇ y) ◇ u
equation 52825 := x ◇ y = ((z ◇ (w ◇ y)) ◇ z) ◇ x
equation 52826 := x ◇ y = ((z ◇ (w ◇ y)) ◇ z) ◇ y
equation 52827 := x ◇ y = ((z ◇ (w ◇ y)) ◇ z) ◇ z
equation 52828 := x ◇ y = ((z ◇ (w ◇ y)) ◇ z) ◇ w
equation 52829 := x ◇ y = ((z ◇ (w ◇ y)) ◇ z) ◇ u
equation 52830 := x ◇ y = ((z ◇ (w ◇ y)) ◇ w) ◇ x
equation 52831 := x ◇ y = ((z ◇ (w ◇ y)) ◇ w) ◇ y
equation 52832 := x ◇ y = ((z ◇ (w ◇ y)) ◇ w) ◇ z
equation 52833 := x ◇ y = ((z ◇ (w ◇ y)) ◇ w) ◇ w
equation 52834 := x ◇ y = ((z ◇ (w ◇ y)) ◇ w) ◇ u
equation 52835 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ x
equation 52836 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ y
equation 52837 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ z
equation 52838 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ w
equation 52839 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ u
equation 52840 := x ◇ y = ((z ◇ (w ◇ y)) ◇ u) ◇ v
equation 52841 := x ◇ y = ((z ◇ (w ◇ z)) ◇ x) ◇ x
equation 52842 := x ◇ y = ((z ◇ (w ◇ z)) ◇ x) ◇ y
equation 52843 := x ◇ y = ((z ◇ (w ◇ z)) ◇ x) ◇ z
equation 52844 := x ◇ y = ((z ◇ (w ◇ z)) ◇ x) ◇ w
equation 52845 := x ◇ y = ((z ◇ (w ◇ z)) ◇ x) ◇ u
equation 52846 := x ◇ y = ((z ◇ (w ◇ z)) ◇ y) ◇ x
equation 52847 := x ◇ y = ((z ◇ (w ◇ z)) ◇ y) ◇ y
equation 52848 := x ◇ y = ((z ◇ (w ◇ z)) ◇ y) ◇ z
equation 52849 := x ◇ y = ((z ◇ (w ◇ z)) ◇ y) ◇ w
equation 52850 := x ◇ y = ((z ◇ (w ◇ z)) ◇ y) ◇ u
equation 52851 := x ◇ y = ((z ◇ (w ◇ z)) ◇ z) ◇ x
equation 52852 := x ◇ y = ((z ◇ (w ◇ z)) ◇ z) ◇ y
equation 52853 := x ◇ y = ((z ◇ (w ◇ z)) ◇ z) ◇ z
equation 52854 := x ◇ y = ((z ◇ (w ◇ z)) ◇ z) ◇ w
equation 52855 := x ◇ y = ((z ◇ (w ◇ z)) ◇ z) ◇ u
equation 52856 := x ◇ y = ((z ◇ (w ◇ z)) ◇ w) ◇ x
equation 52857 := x ◇ y = ((z ◇ (w ◇ z)) ◇ w) ◇ y
equation 52858 := x ◇ y = ((z ◇ (w ◇ z)) ◇ w) ◇ z
equation 52859 := x ◇ y = ((z ◇ (w ◇ z)) ◇ w) ◇ w
equation 52860 := x ◇ y = ((z ◇ (w ◇ z)) ◇ w) ◇ u
equation 52861 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ x
equation 52862 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ y
equation 52863 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ z
equation 52864 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ w
equation 52865 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ u
equation 52866 := x ◇ y = ((z ◇ (w ◇ z)) ◇ u) ◇ v
equation 52867 := x ◇ y = ((z ◇ (w ◇ w)) ◇ x) ◇ x
equation 52868 := x ◇ y = ((z ◇ (w ◇ w)) ◇ x) ◇ y
equation 52869 := x ◇ y = ((z ◇ (w ◇ w)) ◇ x) ◇ z
equation 52870 := x ◇ y = ((z ◇ (w ◇ w)) ◇ x) ◇ w
equation 52871 := x ◇ y = ((z ◇ (w ◇ w)) ◇ x) ◇ u
equation 52872 := x ◇ y = ((z ◇ (w ◇ w)) ◇ y) ◇ x
equation 52873 := x ◇ y = ((z ◇ (w ◇ w)) ◇ y) ◇ y
equation 52874 := x ◇ y = ((z ◇ (w ◇ w)) ◇ y) ◇ z
equation 52875 := x ◇ y = ((z ◇ (w ◇ w)) ◇ y) ◇ w
equation 52876 := x ◇ y = ((z ◇ (w ◇ w)) ◇ y) ◇ u
equation 52877 := x ◇ y = ((z ◇ (w ◇ w)) ◇ z) ◇ x
equation 52878 := x ◇ y = ((z ◇ (w ◇ w)) ◇ z) ◇ y
equation 52879 := x ◇ y = ((z ◇ (w ◇ w)) ◇ z) ◇ z
equation 52880 := x ◇ y = ((z ◇ (w ◇ w)) ◇ z) ◇ w
equation 52881 := x ◇ y = ((z ◇ (w ◇ w)) ◇ z) ◇ u
equation 52882 := x ◇ y = ((z ◇ (w ◇ w)) ◇ w) ◇ x
equation 52883 := x ◇ y = ((z ◇ (w ◇ w)) ◇ w) ◇ y
equation 52884 := x ◇ y = ((z ◇ (w ◇ w)) ◇ w) ◇ z
equation 52885 := x ◇ y = ((z ◇ (w ◇ w)) ◇ w) ◇ w
equation 52886 := x ◇ y = ((z ◇ (w ◇ w)) ◇ w) ◇ u
equation 52887 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ x
equation 52888 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ y
equation 52889 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ z
equation 52890 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ w
equation 52891 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ u
equation 52892 := x ◇ y = ((z ◇ (w ◇ w)) ◇ u) ◇ v
equation 52893 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ x
equation 52894 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ y
equation 52895 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ z
equation 52896 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ w
equation 52897 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ u
equation 52898 := x ◇ y = ((z ◇ (w ◇ u)) ◇ x) ◇ v
equation 52899 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ x
equation 52900 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ y
equation 52901 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ z
equation 52902 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ w
equation 52903 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ u
equation 52904 := x ◇ y = ((z ◇ (w ◇ u)) ◇ y) ◇ v
equation 52905 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ x
equation 52906 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ y
equation 52907 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ z
equation 52908 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ w
equation 52909 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ u
equation 52910 := x ◇ y = ((z ◇ (w ◇ u)) ◇ z) ◇ v
equation 52911 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ x
equation 52912 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ y
equation 52913 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ z
equation 52914 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ w
equation 52915 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ u
equation 52916 := x ◇ y = ((z ◇ (w ◇ u)) ◇ w) ◇ v
equation 52917 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ x
equation 52918 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ y
equation 52919 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ z
equation 52920 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ w
equation 52921 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ u
equation 52922 := x ◇ y = ((z ◇ (w ◇ u)) ◇ u) ◇ v
equation 52923 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ x
equation 52924 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ y
equation 52925 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ z
equation 52926 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ w
equation 52927 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ u
equation 52928 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ v
equation 52929 := x ◇ y = ((z ◇ (w ◇ u)) ◇ v) ◇ r
equation 52930 := x ◇ x = (((x ◇ x) ◇ x) ◇ x) ◇ x
equation 52931 := x ◇ x = (((x ◇ x) ◇ x) ◇ x) ◇ y
equation 52932 := x ◇ x = (((x ◇ x) ◇ x) ◇ y) ◇ x
equation 52933 := x ◇ x = (((x ◇ x) ◇ x) ◇ y) ◇ y
equation 52934 := x ◇ x = (((x ◇ x) ◇ x) ◇ y) ◇ z
equation 52935 := x ◇ x = (((x ◇ x) ◇ y) ◇ x) ◇ x
equation 52936 := x ◇ x = (((x ◇ x) ◇ y) ◇ x) ◇ y
equation 52937 := x ◇ x = (((x ◇ x) ◇ y) ◇ x) ◇ z
equation 52938 := x ◇ x = (((x ◇ x) ◇ y) ◇ y) ◇ x
equation 52939 := x ◇ x = (((x ◇ x) ◇ y) ◇ y) ◇ y
equation 52940 := x ◇ x = (((x ◇ x) ◇ y) ◇ y) ◇ z
equation 52941 := x ◇ x = (((x ◇ x) ◇ y) ◇ z) ◇ x
equation 52942 := x ◇ x = (((x ◇ x) ◇ y) ◇ z) ◇ y
equation 52943 := x ◇ x = (((x ◇ x) ◇ y) ◇ z) ◇ z
equation 52944 := x ◇ x = (((x ◇ x) ◇ y) ◇ z) ◇ w
equation 52945 := x ◇ x = (((x ◇ y) ◇ x) ◇ x) ◇ x
equation 52946 := x ◇ x = (((x ◇ y) ◇ x) ◇ x) ◇ y
equation 52947 := x ◇ x = (((x ◇ y) ◇ x) ◇ x) ◇ z
equation 52948 := x ◇ x = (((x ◇ y) ◇ x) ◇ y) ◇ x
equation 52949 := x ◇ x = (((x ◇ y) ◇ x) ◇ y) ◇ y
equation 52950 := x ◇ x = (((x ◇ y) ◇ x) ◇ y) ◇ z
equation 52951 := x ◇ x = (((x ◇ y) ◇ x) ◇ z) ◇ x
equation 52952 := x ◇ x = (((x ◇ y) ◇ x) ◇ z) ◇ y
equation 52953 := x ◇ x = (((x ◇ y) ◇ x) ◇ z) ◇ z
equation 52954 := x ◇ x = (((x ◇ y) ◇ x) ◇ z) ◇ w
equation 52955 := x ◇ x = (((x ◇ y) ◇ y) ◇ x) ◇ x
equation 52956 := x ◇ x = (((x ◇ y) ◇ y) ◇ x) ◇ y
equation 52957 := x ◇ x = (((x ◇ y) ◇ y) ◇ x) ◇ z
equation 52958 := x ◇ x = (((x ◇ y) ◇ y) ◇ y) ◇ x
equation 52959 := x ◇ x = (((x ◇ y) ◇ y) ◇ y) ◇ y
equation 52960 := x ◇ x = (((x ◇ y) ◇ y) ◇ y) ◇ z
equation 52961 := x ◇ x = (((x ◇ y) ◇ y) ◇ z) ◇ x
equation 52962 := x ◇ x = (((x ◇ y) ◇ y) ◇ z) ◇ y
equation 52963 := x ◇ x = (((x ◇ y) ◇ y) ◇ z) ◇ z
equation 52964 := x ◇ x = (((x ◇ y) ◇ y) ◇ z) ◇ w
equation 52965 := x ◇ x = (((x ◇ y) ◇ z) ◇ x) ◇ x
equation 52966 := x ◇ x = (((x ◇ y) ◇ z) ◇ x) ◇ y
equation 52967 := x ◇ x = (((x ◇ y) ◇ z) ◇ x) ◇ z
equation 52968 := x ◇ x = (((x ◇ y) ◇ z) ◇ x) ◇ w
equation 52969 := x ◇ x = (((x ◇ y) ◇ z) ◇ y) ◇ x
equation 52970 := x ◇ x = (((x ◇ y) ◇ z) ◇ y) ◇ y
equation 52971 := x ◇ x = (((x ◇ y) ◇ z) ◇ y) ◇ z
equation 52972 := x ◇ x = (((x ◇ y) ◇ z) ◇ y) ◇ w
equation 52973 := x ◇ x = (((x ◇ y) ◇ z) ◇ z) ◇ x
equation 52974 := x ◇ x = (((x ◇ y) ◇ z) ◇ z) ◇ y
equation 52975 := x ◇ x = (((x ◇ y) ◇ z) ◇ z) ◇ z
equation 52976 := x ◇ x = (((x ◇ y) ◇ z) ◇ z) ◇ w
equation 52977 := x ◇ x = (((x ◇ y) ◇ z) ◇ w) ◇ x
equation 52978 := x ◇ x = (((x ◇ y) ◇ z) ◇ w) ◇ y
equation 52979 := x ◇ x = (((x ◇ y) ◇ z) ◇ w) ◇ z
equation 52980 := x ◇ x = (((x ◇ y) ◇ z) ◇ w) ◇ w
equation 52981 := x ◇ x = (((x ◇ y) ◇ z) ◇ w) ◇ u
equation 52982 := x ◇ x = (((y ◇ x) ◇ x) ◇ x) ◇ x
equation 52983 := x ◇ x = (((y ◇ x) ◇ x) ◇ x) ◇ y
equation 52984 := x ◇ x = (((y ◇ x) ◇ x) ◇ x) ◇ z
equation 52985 := x ◇ x = (((y ◇ x) ◇ x) ◇ y) ◇ x
equation 52986 := x ◇ x = (((y ◇ x) ◇ x) ◇ y) ◇ y
equation 52987 := x ◇ x = (((y ◇ x) ◇ x) ◇ y) ◇ z
equation 52988 := x ◇ x = (((y ◇ x) ◇ x) ◇ z) ◇ x
equation 52989 := x ◇ x = (((y ◇ x) ◇ x) ◇ z) ◇ y
equation 52990 := x ◇ x = (((y ◇ x) ◇ x) ◇ z) ◇ z
equation 52991 := x ◇ x = (((y ◇ x) ◇ x) ◇ z) ◇ w
equation 52992 := x ◇ x = (((y ◇ x) ◇ y) ◇ x) ◇ x
equation 52993 := x ◇ x = (((y ◇ x) ◇ y) ◇ x) ◇ y
equation 52994 := x ◇ x = (((y ◇ x) ◇ y) ◇ x) ◇ z
equation 52995 := x ◇ x = (((y ◇ x) ◇ y) ◇ y) ◇ x
equation 52996 := x ◇ x = (((y ◇ x) ◇ y) ◇ y) ◇ y
equation 52997 := x ◇ x = (((y ◇ x) ◇ y) ◇ y) ◇ z
equation 52998 := x ◇ x = (((y ◇ x) ◇ y) ◇ z) ◇ x
equation 52999 := x ◇ x = (((y ◇ x) ◇ y) ◇ z) ◇ y
