import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 40000-40999 -/

equation 40000 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ x) ◇ z
equation 40001 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ x) ◇ w
equation 40002 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ y) ◇ x
equation 40003 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ y) ◇ y
equation 40004 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ y) ◇ z
equation 40005 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ y) ◇ w
equation 40006 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ z) ◇ x
equation 40007 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ z) ◇ y
equation 40008 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ z) ◇ z
equation 40009 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ z) ◇ w
equation 40010 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ w) ◇ x
equation 40011 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ w) ◇ y
equation 40012 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ w) ◇ z
equation 40013 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ w) ◇ w
equation 40014 := x = (((y ◇ (x ◇ x)) ◇ z) ◇ w) ◇ u
equation 40015 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ x) ◇ x
equation 40016 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ x) ◇ y
equation 40017 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ x) ◇ z
equation 40018 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ y) ◇ x
equation 40019 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ y) ◇ y
equation 40020 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ y) ◇ z
equation 40021 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ z) ◇ x
equation 40022 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ z) ◇ y
equation 40023 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ z) ◇ z
equation 40024 := x = (((y ◇ (x ◇ y)) ◇ x) ◇ z) ◇ w
equation 40025 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ x) ◇ x
equation 40026 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ x) ◇ y
equation 40027 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ x) ◇ z
equation 40028 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ y) ◇ x
equation 40029 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ y) ◇ y
equation 40030 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ y) ◇ z
equation 40031 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ z) ◇ x
equation 40032 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ z) ◇ y
equation 40033 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ z) ◇ z
equation 40034 := x = (((y ◇ (x ◇ y)) ◇ y) ◇ z) ◇ w
equation 40035 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ x) ◇ x
equation 40036 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ x) ◇ y
equation 40037 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ x) ◇ z
equation 40038 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ x) ◇ w
equation 40039 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ y) ◇ x
equation 40040 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ y) ◇ y
equation 40041 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ y) ◇ z
equation 40042 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ y) ◇ w
equation 40043 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ z) ◇ x
equation 40044 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ z) ◇ y
equation 40045 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ z) ◇ z
equation 40046 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ z) ◇ w
equation 40047 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ w) ◇ x
equation 40048 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ w) ◇ y
equation 40049 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ w) ◇ z
equation 40050 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ w) ◇ w
equation 40051 := x = (((y ◇ (x ◇ y)) ◇ z) ◇ w) ◇ u
equation 40052 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ x) ◇ x
equation 40053 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ x) ◇ y
equation 40054 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ x) ◇ z
equation 40055 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ x) ◇ w
equation 40056 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ y) ◇ x
equation 40057 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ y) ◇ y
equation 40058 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ y) ◇ z
equation 40059 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ y) ◇ w
equation 40060 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ z) ◇ x
equation 40061 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ z) ◇ y
equation 40062 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ z) ◇ z
equation 40063 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ z) ◇ w
equation 40064 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ w) ◇ x
equation 40065 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ w) ◇ y
equation 40066 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ w) ◇ z
equation 40067 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ w) ◇ w
equation 40068 := x = (((y ◇ (x ◇ z)) ◇ x) ◇ w) ◇ u
equation 40069 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ x) ◇ x
equation 40070 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ x) ◇ y
equation 40071 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ x) ◇ z
equation 40072 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ x) ◇ w
equation 40073 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ y) ◇ x
equation 40074 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ y) ◇ y
equation 40075 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ y) ◇ z
equation 40076 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ y) ◇ w
equation 40077 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ z) ◇ x
equation 40078 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ z) ◇ y
equation 40079 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ z) ◇ z
equation 40080 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ z) ◇ w
equation 40081 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ w) ◇ x
equation 40082 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ w) ◇ y
equation 40083 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ w) ◇ z
equation 40084 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ w) ◇ w
equation 40085 := x = (((y ◇ (x ◇ z)) ◇ y) ◇ w) ◇ u
equation 40086 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ x) ◇ x
equation 40087 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ x) ◇ y
equation 40088 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ x) ◇ z
equation 40089 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ x) ◇ w
equation 40090 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ y) ◇ x
equation 40091 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ y) ◇ y
equation 40092 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ y) ◇ z
equation 40093 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ y) ◇ w
equation 40094 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ z) ◇ x
equation 40095 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ z) ◇ y
equation 40096 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ z) ◇ z
equation 40097 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ z) ◇ w
equation 40098 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ w) ◇ x
equation 40099 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ w) ◇ y
equation 40100 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ w) ◇ z
equation 40101 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ w) ◇ w
equation 40102 := x = (((y ◇ (x ◇ z)) ◇ z) ◇ w) ◇ u
equation 40103 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ x) ◇ x
equation 40104 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ x) ◇ y
equation 40105 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ x) ◇ z
equation 40106 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ x) ◇ w
equation 40107 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ x) ◇ u
equation 40108 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ y) ◇ x
equation 40109 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ y) ◇ y
equation 40110 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ y) ◇ z
equation 40111 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ y) ◇ w
equation 40112 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ y) ◇ u
equation 40113 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ z) ◇ x
equation 40114 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ z) ◇ y
equation 40115 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ z) ◇ z
equation 40116 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ z) ◇ w
equation 40117 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ z) ◇ u
equation 40118 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ w) ◇ x
equation 40119 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ w) ◇ y
equation 40120 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ w) ◇ z
equation 40121 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ w) ◇ w
equation 40122 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ w) ◇ u
equation 40123 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ x
equation 40124 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ y
equation 40125 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ z
equation 40126 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ w
equation 40127 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ u
equation 40128 := x = (((y ◇ (x ◇ z)) ◇ w) ◇ u) ◇ v
equation 40129 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ x) ◇ x
equation 40130 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ x) ◇ y
equation 40131 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ x) ◇ z
equation 40132 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ y) ◇ x
equation 40133 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ y) ◇ y
equation 40134 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ y) ◇ z
equation 40135 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ z) ◇ x
equation 40136 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ z) ◇ y
equation 40137 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ z) ◇ z
equation 40138 := x = (((y ◇ (y ◇ x)) ◇ x) ◇ z) ◇ w
equation 40139 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ x) ◇ x
equation 40140 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ x) ◇ y
equation 40141 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ x) ◇ z
equation 40142 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ y) ◇ x
equation 40143 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ y) ◇ y
equation 40144 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ y) ◇ z
equation 40145 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ z) ◇ x
equation 40146 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ z) ◇ y
equation 40147 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ z) ◇ z
equation 40148 := x = (((y ◇ (y ◇ x)) ◇ y) ◇ z) ◇ w
equation 40149 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ x) ◇ x
equation 40150 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ x) ◇ y
equation 40151 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ x) ◇ z
equation 40152 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ x) ◇ w
equation 40153 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ y) ◇ x
equation 40154 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ y) ◇ y
equation 40155 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ y) ◇ z
equation 40156 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ y) ◇ w
equation 40157 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ z) ◇ x
equation 40158 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ z) ◇ y
equation 40159 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ z) ◇ z
equation 40160 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ z) ◇ w
equation 40161 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ w) ◇ x
equation 40162 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ w) ◇ y
equation 40163 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ w) ◇ z
equation 40164 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ w) ◇ w
equation 40165 := x = (((y ◇ (y ◇ x)) ◇ z) ◇ w) ◇ u
equation 40166 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ x) ◇ x
equation 40167 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ x) ◇ y
equation 40168 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ x) ◇ z
equation 40169 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ y) ◇ x
equation 40170 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ y) ◇ y
equation 40171 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ y) ◇ z
equation 40172 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ z) ◇ x
equation 40173 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ z) ◇ y
equation 40174 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ z) ◇ z
equation 40175 := x = (((y ◇ (y ◇ y)) ◇ x) ◇ z) ◇ w
equation 40176 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ x) ◇ x
equation 40177 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ x) ◇ y
equation 40178 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ x) ◇ z
equation 40179 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ y) ◇ x
equation 40180 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ y) ◇ y
equation 40181 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ y) ◇ z
equation 40182 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ z) ◇ x
equation 40183 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ z) ◇ y
equation 40184 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ z) ◇ z
equation 40185 := x = (((y ◇ (y ◇ y)) ◇ y) ◇ z) ◇ w
equation 40186 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ x) ◇ x
equation 40187 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ x) ◇ y
equation 40188 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ x) ◇ z
equation 40189 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ x) ◇ w
equation 40190 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ y) ◇ x
equation 40191 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ y) ◇ y
equation 40192 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ y) ◇ z
equation 40193 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ y) ◇ w
equation 40194 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ z) ◇ x
equation 40195 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ z) ◇ y
equation 40196 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ z) ◇ z
equation 40197 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ z) ◇ w
equation 40198 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ w) ◇ x
equation 40199 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ w) ◇ y
equation 40200 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ w) ◇ z
equation 40201 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ w) ◇ w
equation 40202 := x = (((y ◇ (y ◇ y)) ◇ z) ◇ w) ◇ u
equation 40203 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ x) ◇ x
equation 40204 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ x) ◇ y
equation 40205 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ x) ◇ z
equation 40206 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ x) ◇ w
equation 40207 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ y) ◇ x
equation 40208 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ y) ◇ y
equation 40209 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ y) ◇ z
equation 40210 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ y) ◇ w
equation 40211 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ z) ◇ x
equation 40212 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ z) ◇ y
equation 40213 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ z) ◇ z
equation 40214 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ z) ◇ w
equation 40215 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ w) ◇ x
equation 40216 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ w) ◇ y
equation 40217 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ w) ◇ z
equation 40218 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ w) ◇ w
equation 40219 := x = (((y ◇ (y ◇ z)) ◇ x) ◇ w) ◇ u
equation 40220 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ x) ◇ x
equation 40221 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ x) ◇ y
equation 40222 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ x) ◇ z
equation 40223 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ x) ◇ w
equation 40224 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ y) ◇ x
equation 40225 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ y) ◇ y
equation 40226 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ y) ◇ z
equation 40227 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ y) ◇ w
equation 40228 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ z) ◇ x
equation 40229 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ z) ◇ y
equation 40230 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ z) ◇ z
equation 40231 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ z) ◇ w
equation 40232 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ w) ◇ x
equation 40233 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ w) ◇ y
equation 40234 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ w) ◇ z
equation 40235 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ w) ◇ w
equation 40236 := x = (((y ◇ (y ◇ z)) ◇ y) ◇ w) ◇ u
equation 40237 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ x) ◇ x
equation 40238 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ x) ◇ y
equation 40239 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ x) ◇ z
equation 40240 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ x) ◇ w
equation 40241 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ y) ◇ x
equation 40242 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ y) ◇ y
equation 40243 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ y) ◇ z
equation 40244 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ y) ◇ w
equation 40245 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ z) ◇ x
equation 40246 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ z) ◇ y
equation 40247 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ z) ◇ z
equation 40248 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ z) ◇ w
equation 40249 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ w) ◇ x
equation 40250 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ w) ◇ y
equation 40251 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ w) ◇ z
equation 40252 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ w) ◇ w
equation 40253 := x = (((y ◇ (y ◇ z)) ◇ z) ◇ w) ◇ u
equation 40254 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ x) ◇ x
equation 40255 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ x) ◇ y
equation 40256 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ x) ◇ z
equation 40257 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ x) ◇ w
equation 40258 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ x) ◇ u
equation 40259 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ y) ◇ x
equation 40260 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ y) ◇ y
equation 40261 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ y) ◇ z
equation 40262 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ y) ◇ w
equation 40263 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ y) ◇ u
equation 40264 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ z) ◇ x
equation 40265 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ z) ◇ y
equation 40266 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ z) ◇ z
equation 40267 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ z) ◇ w
equation 40268 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ z) ◇ u
equation 40269 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ w) ◇ x
equation 40270 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ w) ◇ y
equation 40271 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ w) ◇ z
equation 40272 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ w) ◇ w
equation 40273 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ w) ◇ u
equation 40274 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ x
equation 40275 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ y
equation 40276 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ z
equation 40277 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ w
equation 40278 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ u
equation 40279 := x = (((y ◇ (y ◇ z)) ◇ w) ◇ u) ◇ v
equation 40280 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ x) ◇ x
equation 40281 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ x) ◇ y
equation 40282 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ x) ◇ z
equation 40283 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ x) ◇ w
equation 40284 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ y) ◇ x
equation 40285 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ y) ◇ y
equation 40286 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ y) ◇ z
equation 40287 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ y) ◇ w
equation 40288 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ z) ◇ x
equation 40289 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ z) ◇ y
equation 40290 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ z) ◇ z
equation 40291 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ z) ◇ w
equation 40292 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ w) ◇ x
equation 40293 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ w) ◇ y
equation 40294 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ w) ◇ z
equation 40295 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ w) ◇ w
equation 40296 := x = (((y ◇ (z ◇ x)) ◇ x) ◇ w) ◇ u
equation 40297 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ x) ◇ x
equation 40298 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ x) ◇ y
equation 40299 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ x) ◇ z
equation 40300 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ x) ◇ w
equation 40301 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ y) ◇ x
equation 40302 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ y) ◇ y
equation 40303 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ y) ◇ z
equation 40304 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ y) ◇ w
equation 40305 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ z) ◇ x
equation 40306 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ z) ◇ y
equation 40307 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ z) ◇ z
equation 40308 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ z) ◇ w
equation 40309 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ w) ◇ x
equation 40310 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ w) ◇ y
equation 40311 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ w) ◇ z
equation 40312 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ w) ◇ w
equation 40313 := x = (((y ◇ (z ◇ x)) ◇ y) ◇ w) ◇ u
equation 40314 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ x) ◇ x
equation 40315 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ x) ◇ y
equation 40316 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ x) ◇ z
equation 40317 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ x) ◇ w
equation 40318 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ y) ◇ x
equation 40319 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ y) ◇ y
equation 40320 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ y) ◇ z
equation 40321 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ y) ◇ w
equation 40322 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ z) ◇ x
equation 40323 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ z) ◇ y
equation 40324 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ z) ◇ z
equation 40325 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ z) ◇ w
equation 40326 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ w) ◇ x
equation 40327 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ w) ◇ y
equation 40328 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ w) ◇ z
equation 40329 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ w) ◇ w
equation 40330 := x = (((y ◇ (z ◇ x)) ◇ z) ◇ w) ◇ u
equation 40331 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ x) ◇ x
equation 40332 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ x) ◇ y
equation 40333 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ x) ◇ z
equation 40334 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ x) ◇ w
equation 40335 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ x) ◇ u
equation 40336 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ y) ◇ x
equation 40337 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ y) ◇ y
equation 40338 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ y) ◇ z
equation 40339 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ y) ◇ w
equation 40340 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ y) ◇ u
equation 40341 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ z) ◇ x
equation 40342 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ z) ◇ y
equation 40343 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ z) ◇ z
equation 40344 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ z) ◇ w
equation 40345 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ z) ◇ u
equation 40346 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ w) ◇ x
equation 40347 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ w) ◇ y
equation 40348 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ w) ◇ z
equation 40349 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ w) ◇ w
equation 40350 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ w) ◇ u
equation 40351 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ x
equation 40352 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ y
equation 40353 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ z
equation 40354 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ w
equation 40355 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ u
equation 40356 := x = (((y ◇ (z ◇ x)) ◇ w) ◇ u) ◇ v
equation 40357 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ x) ◇ x
equation 40358 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ x) ◇ y
equation 40359 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ x) ◇ z
equation 40360 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ x) ◇ w
equation 40361 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ y) ◇ x
equation 40362 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ y) ◇ y
equation 40363 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ y) ◇ z
equation 40364 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ y) ◇ w
equation 40365 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ z) ◇ x
equation 40366 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ z) ◇ y
equation 40367 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ z) ◇ z
equation 40368 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ z) ◇ w
equation 40369 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ w) ◇ x
equation 40370 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ w) ◇ y
equation 40371 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ w) ◇ z
equation 40372 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ w) ◇ w
equation 40373 := x = (((y ◇ (z ◇ y)) ◇ x) ◇ w) ◇ u
equation 40374 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ x) ◇ x
equation 40375 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ x) ◇ y
equation 40376 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ x) ◇ z
equation 40377 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ x) ◇ w
equation 40378 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ y) ◇ x
equation 40379 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ y) ◇ y
equation 40380 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ y) ◇ z
equation 40381 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ y) ◇ w
equation 40382 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ z) ◇ x
equation 40383 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ z) ◇ y
equation 40384 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ z) ◇ z
equation 40385 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ z) ◇ w
equation 40386 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ w) ◇ x
equation 40387 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ w) ◇ y
equation 40388 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ w) ◇ z
equation 40389 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ w) ◇ w
equation 40390 := x = (((y ◇ (z ◇ y)) ◇ y) ◇ w) ◇ u
equation 40391 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ x) ◇ x
equation 40392 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ x) ◇ y
equation 40393 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ x) ◇ z
equation 40394 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ x) ◇ w
equation 40395 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ y) ◇ x
equation 40396 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ y) ◇ y
equation 40397 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ y) ◇ z
equation 40398 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ y) ◇ w
equation 40399 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ z) ◇ x
equation 40400 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ z) ◇ y
equation 40401 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ z) ◇ z
equation 40402 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ z) ◇ w
equation 40403 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ w) ◇ x
equation 40404 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ w) ◇ y
equation 40405 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ w) ◇ z
equation 40406 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ w) ◇ w
equation 40407 := x = (((y ◇ (z ◇ y)) ◇ z) ◇ w) ◇ u
equation 40408 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ x) ◇ x
equation 40409 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ x) ◇ y
equation 40410 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ x) ◇ z
equation 40411 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ x) ◇ w
equation 40412 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ x) ◇ u
equation 40413 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ y) ◇ x
equation 40414 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ y) ◇ y
equation 40415 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ y) ◇ z
equation 40416 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ y) ◇ w
equation 40417 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ y) ◇ u
equation 40418 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ z) ◇ x
equation 40419 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ z) ◇ y
equation 40420 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ z) ◇ z
equation 40421 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ z) ◇ w
equation 40422 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ z) ◇ u
equation 40423 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ w) ◇ x
equation 40424 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ w) ◇ y
equation 40425 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ w) ◇ z
equation 40426 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ w) ◇ w
equation 40427 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ w) ◇ u
equation 40428 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ x
equation 40429 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ y
equation 40430 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ z
equation 40431 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ w
equation 40432 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ u
equation 40433 := x = (((y ◇ (z ◇ y)) ◇ w) ◇ u) ◇ v
equation 40434 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ x) ◇ x
equation 40435 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ x) ◇ y
equation 40436 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ x) ◇ z
equation 40437 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ x) ◇ w
equation 40438 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ y) ◇ x
equation 40439 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ y) ◇ y
equation 40440 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ y) ◇ z
equation 40441 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ y) ◇ w
equation 40442 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ z) ◇ x
equation 40443 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ z) ◇ y
equation 40444 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ z) ◇ z
equation 40445 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ z) ◇ w
equation 40446 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ w) ◇ x
equation 40447 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ w) ◇ y
equation 40448 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ w) ◇ z
equation 40449 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ w) ◇ w
equation 40450 := x = (((y ◇ (z ◇ z)) ◇ x) ◇ w) ◇ u
equation 40451 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ x) ◇ x
equation 40452 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ x) ◇ y
equation 40453 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ x) ◇ z
equation 40454 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ x) ◇ w
equation 40455 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ y) ◇ x
equation 40456 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ y) ◇ y
equation 40457 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ y) ◇ z
equation 40458 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ y) ◇ w
equation 40459 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ z) ◇ x
equation 40460 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ z) ◇ y
equation 40461 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ z) ◇ z
equation 40462 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ z) ◇ w
equation 40463 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ w) ◇ x
equation 40464 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ w) ◇ y
equation 40465 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ w) ◇ z
equation 40466 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ w) ◇ w
equation 40467 := x = (((y ◇ (z ◇ z)) ◇ y) ◇ w) ◇ u
equation 40468 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ x) ◇ x
equation 40469 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ x) ◇ y
equation 40470 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ x) ◇ z
equation 40471 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ x) ◇ w
equation 40472 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ y) ◇ x
equation 40473 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ y) ◇ y
equation 40474 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ y) ◇ z
equation 40475 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ y) ◇ w
equation 40476 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ z) ◇ x
equation 40477 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ z) ◇ y
equation 40478 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ z) ◇ z
equation 40479 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ z) ◇ w
equation 40480 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ w) ◇ x
equation 40481 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ w) ◇ y
equation 40482 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ w) ◇ z
equation 40483 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ w) ◇ w
equation 40484 := x = (((y ◇ (z ◇ z)) ◇ z) ◇ w) ◇ u
equation 40485 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ x) ◇ x
equation 40486 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ x) ◇ y
equation 40487 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ x) ◇ z
equation 40488 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ x) ◇ w
equation 40489 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ x) ◇ u
equation 40490 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ y) ◇ x
equation 40491 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ y) ◇ y
equation 40492 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ y) ◇ z
equation 40493 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ y) ◇ w
equation 40494 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ y) ◇ u
equation 40495 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ z) ◇ x
equation 40496 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ z) ◇ y
equation 40497 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ z) ◇ z
equation 40498 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ z) ◇ w
equation 40499 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ z) ◇ u
equation 40500 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ w) ◇ x
equation 40501 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ w) ◇ y
equation 40502 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ w) ◇ z
equation 40503 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ w) ◇ w
equation 40504 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ w) ◇ u
equation 40505 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ x
equation 40506 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ y
equation 40507 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ z
equation 40508 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ w
equation 40509 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ u
equation 40510 := x = (((y ◇ (z ◇ z)) ◇ w) ◇ u) ◇ v
equation 40511 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ x) ◇ x
equation 40512 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ x) ◇ y
equation 40513 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ x) ◇ z
equation 40514 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ x) ◇ w
equation 40515 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ x) ◇ u
equation 40516 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ y) ◇ x
equation 40517 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ y) ◇ y
equation 40518 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ y) ◇ z
equation 40519 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ y) ◇ w
equation 40520 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ y) ◇ u
equation 40521 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ z) ◇ x
equation 40522 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ z) ◇ y
equation 40523 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ z) ◇ z
equation 40524 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ z) ◇ w
equation 40525 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ z) ◇ u
equation 40526 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ w) ◇ x
equation 40527 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ w) ◇ y
equation 40528 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ w) ◇ z
equation 40529 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ w) ◇ w
equation 40530 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ w) ◇ u
equation 40531 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ x
equation 40532 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ y
equation 40533 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ z
equation 40534 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ w
equation 40535 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ u
equation 40536 := x = (((y ◇ (z ◇ w)) ◇ x) ◇ u) ◇ v
equation 40537 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ x) ◇ x
equation 40538 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ x) ◇ y
equation 40539 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ x) ◇ z
equation 40540 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ x) ◇ w
equation 40541 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ x) ◇ u
equation 40542 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ y) ◇ x
equation 40543 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ y) ◇ y
equation 40544 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ y) ◇ z
equation 40545 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ y) ◇ w
equation 40546 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ y) ◇ u
equation 40547 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ z) ◇ x
equation 40548 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ z) ◇ y
equation 40549 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ z) ◇ z
equation 40550 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ z) ◇ w
equation 40551 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ z) ◇ u
equation 40552 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ w) ◇ x
equation 40553 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ w) ◇ y
equation 40554 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ w) ◇ z
equation 40555 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ w) ◇ w
equation 40556 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ w) ◇ u
equation 40557 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ x
equation 40558 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ y
equation 40559 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ z
equation 40560 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ w
equation 40561 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ u
equation 40562 := x = (((y ◇ (z ◇ w)) ◇ y) ◇ u) ◇ v
equation 40563 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ x) ◇ x
equation 40564 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ x) ◇ y
equation 40565 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ x) ◇ z
equation 40566 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ x) ◇ w
equation 40567 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ x) ◇ u
equation 40568 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ y) ◇ x
equation 40569 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ y) ◇ y
equation 40570 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ y) ◇ z
equation 40571 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ y) ◇ w
equation 40572 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ y) ◇ u
equation 40573 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ z) ◇ x
equation 40574 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ z) ◇ y
equation 40575 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ z) ◇ z
equation 40576 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ z) ◇ w
equation 40577 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ z) ◇ u
equation 40578 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ w) ◇ x
equation 40579 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ w) ◇ y
equation 40580 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ w) ◇ z
equation 40581 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ w) ◇ w
equation 40582 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ w) ◇ u
equation 40583 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ x
equation 40584 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ y
equation 40585 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ z
equation 40586 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ w
equation 40587 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ u
equation 40588 := x = (((y ◇ (z ◇ w)) ◇ z) ◇ u) ◇ v
equation 40589 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ x) ◇ x
equation 40590 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ x) ◇ y
equation 40591 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ x) ◇ z
equation 40592 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ x) ◇ w
equation 40593 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ x) ◇ u
equation 40594 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ y) ◇ x
equation 40595 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ y) ◇ y
equation 40596 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ y) ◇ z
equation 40597 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ y) ◇ w
equation 40598 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ y) ◇ u
equation 40599 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ z) ◇ x
equation 40600 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ z) ◇ y
equation 40601 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ z) ◇ z
equation 40602 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ z) ◇ w
equation 40603 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ z) ◇ u
equation 40604 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ w) ◇ x
equation 40605 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ w) ◇ y
equation 40606 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ w) ◇ z
equation 40607 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ w) ◇ w
equation 40608 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ w) ◇ u
equation 40609 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ x
equation 40610 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ y
equation 40611 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ z
equation 40612 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ w
equation 40613 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ u
equation 40614 := x = (((y ◇ (z ◇ w)) ◇ w) ◇ u) ◇ v
equation 40615 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ x
equation 40616 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ y
equation 40617 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ z
equation 40618 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ w
equation 40619 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ u
equation 40620 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ x) ◇ v
equation 40621 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ x
equation 40622 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ y
equation 40623 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ z
equation 40624 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ w
equation 40625 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ u
equation 40626 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ y) ◇ v
equation 40627 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ x
equation 40628 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ y
equation 40629 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ z
equation 40630 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ w
equation 40631 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ u
equation 40632 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ z) ◇ v
equation 40633 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ x
equation 40634 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ y
equation 40635 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ z
equation 40636 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ w
equation 40637 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ u
equation 40638 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ w) ◇ v
equation 40639 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ x
equation 40640 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ y
equation 40641 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ z
equation 40642 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ w
equation 40643 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ u
equation 40644 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ u) ◇ v
equation 40645 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ x
equation 40646 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ y
equation 40647 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ z
equation 40648 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ w
equation 40649 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ u
equation 40650 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ v
equation 40651 := x = (((y ◇ (z ◇ w)) ◇ u) ◇ v) ◇ r
equation 40652 := x = ((((x ◇ x) ◇ x) ◇ x) ◇ x) ◇ x
equation 40653 := x = ((((x ◇ x) ◇ x) ◇ x) ◇ x) ◇ y
equation 40654 := x = ((((x ◇ x) ◇ x) ◇ x) ◇ y) ◇ x
equation 40655 := x = ((((x ◇ x) ◇ x) ◇ x) ◇ y) ◇ y
equation 40656 := x = ((((x ◇ x) ◇ x) ◇ x) ◇ y) ◇ z
equation 40657 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ x) ◇ x
equation 40658 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ x) ◇ y
equation 40659 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ x) ◇ z
equation 40660 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ y) ◇ x
equation 40661 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ y) ◇ y
equation 40662 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ y) ◇ z
equation 40663 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ z) ◇ x
equation 40664 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ z) ◇ y
equation 40665 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ z) ◇ z
equation 40666 := x = ((((x ◇ x) ◇ x) ◇ y) ◇ z) ◇ w
equation 40667 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ x) ◇ x
equation 40668 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ x) ◇ y
equation 40669 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ x) ◇ z
equation 40670 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ y) ◇ x
equation 40671 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ y) ◇ y
equation 40672 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ y) ◇ z
equation 40673 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ z) ◇ x
equation 40674 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ z) ◇ y
equation 40675 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ z) ◇ z
equation 40676 := x = ((((x ◇ x) ◇ y) ◇ x) ◇ z) ◇ w
equation 40677 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ x) ◇ x
equation 40678 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ x) ◇ y
equation 40679 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ x) ◇ z
equation 40680 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ y) ◇ x
equation 40681 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ y) ◇ y
equation 40682 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ y) ◇ z
equation 40683 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ z) ◇ x
equation 40684 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ z) ◇ y
equation 40685 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ z) ◇ z
equation 40686 := x = ((((x ◇ x) ◇ y) ◇ y) ◇ z) ◇ w
equation 40687 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ x) ◇ x
equation 40688 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ x) ◇ y
equation 40689 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ x) ◇ z
equation 40690 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ x) ◇ w
equation 40691 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ y) ◇ x
equation 40692 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ y) ◇ y
equation 40693 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ y) ◇ z
equation 40694 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ y) ◇ w
equation 40695 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ z) ◇ x
equation 40696 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ z) ◇ y
equation 40697 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ z) ◇ z
equation 40698 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ z) ◇ w
equation 40699 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ w) ◇ x
equation 40700 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ w) ◇ y
equation 40701 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ w) ◇ z
equation 40702 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ w) ◇ w
equation 40703 := x = ((((x ◇ x) ◇ y) ◇ z) ◇ w) ◇ u
equation 40704 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ x) ◇ x
equation 40705 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ x) ◇ y
equation 40706 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ x) ◇ z
equation 40707 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ y) ◇ x
equation 40708 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ y) ◇ y
equation 40709 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ y) ◇ z
equation 40710 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ z) ◇ x
equation 40711 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ z) ◇ y
equation 40712 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ z) ◇ z
equation 40713 := x = ((((x ◇ y) ◇ x) ◇ x) ◇ z) ◇ w
equation 40714 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ x) ◇ x
equation 40715 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ x) ◇ y
equation 40716 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ x) ◇ z
equation 40717 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ y) ◇ x
equation 40718 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ y) ◇ y
equation 40719 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ y) ◇ z
equation 40720 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ z) ◇ x
equation 40721 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ z) ◇ y
equation 40722 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ z) ◇ z
equation 40723 := x = ((((x ◇ y) ◇ x) ◇ y) ◇ z) ◇ w
equation 40724 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ x) ◇ x
equation 40725 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ x) ◇ y
equation 40726 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ x) ◇ z
equation 40727 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ x) ◇ w
equation 40728 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ y) ◇ x
equation 40729 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ y) ◇ y
equation 40730 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ y) ◇ z
equation 40731 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ y) ◇ w
equation 40732 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ z) ◇ x
equation 40733 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ z) ◇ y
equation 40734 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ z) ◇ z
equation 40735 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ z) ◇ w
equation 40736 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ w) ◇ x
equation 40737 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ w) ◇ y
equation 40738 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ w) ◇ z
equation 40739 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ w) ◇ w
equation 40740 := x = ((((x ◇ y) ◇ x) ◇ z) ◇ w) ◇ u
equation 40741 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ x) ◇ x
equation 40742 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ x) ◇ y
equation 40743 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ x) ◇ z
equation 40744 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ y) ◇ x
equation 40745 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ y) ◇ y
equation 40746 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ y) ◇ z
equation 40747 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ z) ◇ x
equation 40748 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ z) ◇ y
equation 40749 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ z) ◇ z
equation 40750 := x = ((((x ◇ y) ◇ y) ◇ x) ◇ z) ◇ w
equation 40751 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ x) ◇ x
equation 40752 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ x) ◇ y
equation 40753 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ x) ◇ z
equation 40754 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ y) ◇ x
equation 40755 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ y) ◇ y
equation 40756 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ y) ◇ z
equation 40757 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ z) ◇ x
equation 40758 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ z) ◇ y
equation 40759 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ z) ◇ z
equation 40760 := x = ((((x ◇ y) ◇ y) ◇ y) ◇ z) ◇ w
equation 40761 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ x) ◇ x
equation 40762 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ x) ◇ y
equation 40763 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ x) ◇ z
equation 40764 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ x) ◇ w
equation 40765 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ y) ◇ x
equation 40766 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ y) ◇ y
equation 40767 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ y) ◇ z
equation 40768 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ y) ◇ w
equation 40769 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ z) ◇ x
equation 40770 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ z) ◇ y
equation 40771 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ z) ◇ z
equation 40772 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ z) ◇ w
equation 40773 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ w) ◇ x
equation 40774 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ w) ◇ y
equation 40775 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ w) ◇ z
equation 40776 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ w) ◇ w
equation 40777 := x = ((((x ◇ y) ◇ y) ◇ z) ◇ w) ◇ u
equation 40778 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ x) ◇ x
equation 40779 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ x) ◇ y
equation 40780 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ x) ◇ z
equation 40781 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ x) ◇ w
equation 40782 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ y) ◇ x
equation 40783 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ y) ◇ y
equation 40784 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ y) ◇ z
equation 40785 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ y) ◇ w
equation 40786 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ z) ◇ x
equation 40787 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ z) ◇ y
equation 40788 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ z) ◇ z
equation 40789 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ z) ◇ w
equation 40790 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ w) ◇ x
equation 40791 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ w) ◇ y
equation 40792 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ w) ◇ z
equation 40793 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ w) ◇ w
equation 40794 := x = ((((x ◇ y) ◇ z) ◇ x) ◇ w) ◇ u
equation 40795 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ x) ◇ x
equation 40796 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ x) ◇ y
equation 40797 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ x) ◇ z
equation 40798 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ x) ◇ w
equation 40799 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ y) ◇ x
equation 40800 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ y) ◇ y
equation 40801 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ y) ◇ z
equation 40802 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ y) ◇ w
equation 40803 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ z) ◇ x
equation 40804 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ z) ◇ y
equation 40805 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ z) ◇ z
equation 40806 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ z) ◇ w
equation 40807 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ w) ◇ x
equation 40808 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ w) ◇ y
equation 40809 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ w) ◇ z
equation 40810 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ w) ◇ w
equation 40811 := x = ((((x ◇ y) ◇ z) ◇ y) ◇ w) ◇ u
equation 40812 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ x) ◇ x
equation 40813 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ x) ◇ y
equation 40814 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ x) ◇ z
equation 40815 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ x) ◇ w
equation 40816 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ y) ◇ x
equation 40817 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ y) ◇ y
equation 40818 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ y) ◇ z
equation 40819 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ y) ◇ w
equation 40820 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ z) ◇ x
equation 40821 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ z) ◇ y
equation 40822 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ z) ◇ z
equation 40823 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ z) ◇ w
equation 40824 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ w) ◇ x
equation 40825 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ w) ◇ y
equation 40826 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ w) ◇ z
equation 40827 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ w) ◇ w
equation 40828 := x = ((((x ◇ y) ◇ z) ◇ z) ◇ w) ◇ u
equation 40829 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ x) ◇ x
equation 40830 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ x) ◇ y
equation 40831 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ x) ◇ z
equation 40832 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ x) ◇ w
equation 40833 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ x) ◇ u
equation 40834 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ y) ◇ x
equation 40835 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ y) ◇ y
equation 40836 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ y) ◇ z
equation 40837 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ y) ◇ w
equation 40838 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ y) ◇ u
equation 40839 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ z) ◇ x
equation 40840 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ z) ◇ y
equation 40841 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ z) ◇ z
equation 40842 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ z) ◇ w
equation 40843 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ z) ◇ u
equation 40844 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ w) ◇ x
equation 40845 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ w) ◇ y
equation 40846 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ w) ◇ z
equation 40847 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ w) ◇ w
equation 40848 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ w) ◇ u
equation 40849 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ x
equation 40850 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ y
equation 40851 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ z
equation 40852 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ w
equation 40853 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ u
equation 40854 := x = ((((x ◇ y) ◇ z) ◇ w) ◇ u) ◇ v
equation 40855 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ x) ◇ x
equation 40856 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ x) ◇ y
equation 40857 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ x) ◇ z
equation 40858 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ y) ◇ x
equation 40859 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ y) ◇ y
equation 40860 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ y) ◇ z
equation 40861 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ z) ◇ x
equation 40862 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ z) ◇ y
equation 40863 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ z) ◇ z
equation 40864 := x = ((((y ◇ x) ◇ x) ◇ x) ◇ z) ◇ w
equation 40865 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ x) ◇ x
equation 40866 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ x) ◇ y
equation 40867 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ x) ◇ z
equation 40868 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ y) ◇ x
equation 40869 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ y) ◇ y
equation 40870 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ y) ◇ z
equation 40871 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ z) ◇ x
equation 40872 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ z) ◇ y
equation 40873 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ z) ◇ z
equation 40874 := x = ((((y ◇ x) ◇ x) ◇ y) ◇ z) ◇ w
equation 40875 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ x) ◇ x
equation 40876 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ x) ◇ y
equation 40877 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ x) ◇ z
equation 40878 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ x) ◇ w
equation 40879 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ y) ◇ x
equation 40880 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ y) ◇ y
equation 40881 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ y) ◇ z
equation 40882 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ y) ◇ w
equation 40883 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ z) ◇ x
equation 40884 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ z) ◇ y
equation 40885 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ z) ◇ z
equation 40886 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ z) ◇ w
equation 40887 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ w) ◇ x
equation 40888 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ w) ◇ y
equation 40889 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ w) ◇ z
equation 40890 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ w) ◇ w
equation 40891 := x = ((((y ◇ x) ◇ x) ◇ z) ◇ w) ◇ u
equation 40892 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ x) ◇ x
equation 40893 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ x) ◇ y
equation 40894 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ x) ◇ z
equation 40895 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ y) ◇ x
equation 40896 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ y) ◇ y
equation 40897 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ y) ◇ z
equation 40898 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ z) ◇ x
equation 40899 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ z) ◇ y
equation 40900 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ z) ◇ z
equation 40901 := x = ((((y ◇ x) ◇ y) ◇ x) ◇ z) ◇ w
equation 40902 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ x) ◇ x
equation 40903 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ x) ◇ y
equation 40904 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ x) ◇ z
equation 40905 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ y) ◇ x
equation 40906 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ y) ◇ y
equation 40907 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ y) ◇ z
equation 40908 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ z) ◇ x
equation 40909 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ z) ◇ y
equation 40910 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ z) ◇ z
equation 40911 := x = ((((y ◇ x) ◇ y) ◇ y) ◇ z) ◇ w
equation 40912 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ x) ◇ x
equation 40913 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ x) ◇ y
equation 40914 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ x) ◇ z
equation 40915 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ x) ◇ w
equation 40916 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ y) ◇ x
equation 40917 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ y) ◇ y
equation 40918 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ y) ◇ z
equation 40919 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ y) ◇ w
equation 40920 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ z) ◇ x
equation 40921 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ z) ◇ y
equation 40922 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ z) ◇ z
equation 40923 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ z) ◇ w
equation 40924 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ w) ◇ x
equation 40925 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ w) ◇ y
equation 40926 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ w) ◇ z
equation 40927 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ w) ◇ w
equation 40928 := x = ((((y ◇ x) ◇ y) ◇ z) ◇ w) ◇ u
equation 40929 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ x) ◇ x
equation 40930 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ x) ◇ y
equation 40931 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ x) ◇ z
equation 40932 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ x) ◇ w
equation 40933 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ y) ◇ x
equation 40934 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ y) ◇ y
equation 40935 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ y) ◇ z
equation 40936 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ y) ◇ w
equation 40937 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ z) ◇ x
equation 40938 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ z) ◇ y
equation 40939 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ z) ◇ z
equation 40940 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ z) ◇ w
equation 40941 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ w) ◇ x
equation 40942 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ w) ◇ y
equation 40943 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ w) ◇ z
equation 40944 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ w) ◇ w
equation 40945 := x = ((((y ◇ x) ◇ z) ◇ x) ◇ w) ◇ u
equation 40946 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ x) ◇ x
equation 40947 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ x) ◇ y
equation 40948 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ x) ◇ z
equation 40949 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ x) ◇ w
equation 40950 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ y) ◇ x
equation 40951 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ y) ◇ y
equation 40952 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ y) ◇ z
equation 40953 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ y) ◇ w
equation 40954 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ z) ◇ x
equation 40955 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ z) ◇ y
equation 40956 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ z) ◇ z
equation 40957 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ z) ◇ w
equation 40958 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ w) ◇ x
equation 40959 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ w) ◇ y
equation 40960 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ w) ◇ z
equation 40961 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ w) ◇ w
equation 40962 := x = ((((y ◇ x) ◇ z) ◇ y) ◇ w) ◇ u
equation 40963 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ x) ◇ x
equation 40964 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ x) ◇ y
equation 40965 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ x) ◇ z
equation 40966 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ x) ◇ w
equation 40967 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ y) ◇ x
equation 40968 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ y) ◇ y
equation 40969 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ y) ◇ z
equation 40970 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ y) ◇ w
equation 40971 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ z) ◇ x
equation 40972 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ z) ◇ y
equation 40973 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ z) ◇ z
equation 40974 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ z) ◇ w
equation 40975 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ w) ◇ x
equation 40976 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ w) ◇ y
equation 40977 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ w) ◇ z
equation 40978 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ w) ◇ w
equation 40979 := x = ((((y ◇ x) ◇ z) ◇ z) ◇ w) ◇ u
equation 40980 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ x) ◇ x
equation 40981 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ x) ◇ y
equation 40982 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ x) ◇ z
equation 40983 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ x) ◇ w
equation 40984 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ x) ◇ u
equation 40985 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ y) ◇ x
equation 40986 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ y) ◇ y
equation 40987 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ y) ◇ z
equation 40988 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ y) ◇ w
equation 40989 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ y) ◇ u
equation 40990 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ z) ◇ x
equation 40991 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ z) ◇ y
equation 40992 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ z) ◇ z
equation 40993 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ z) ◇ w
equation 40994 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ z) ◇ u
equation 40995 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ w) ◇ x
equation 40996 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ w) ◇ y
equation 40997 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ w) ◇ z
equation 40998 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ w) ◇ w
equation 40999 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ w) ◇ u
