import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 35000-35999 -/

equation 35000 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ w
equation 35001 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ u
equation 35002 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ x
equation 35003 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ y
equation 35004 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ z
equation 35005 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ w
equation 35006 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ u
equation 35007 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ x
equation 35008 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ y
equation 35009 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ z
equation 35010 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ w
equation 35011 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ u
equation 35012 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ x
equation 35013 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ y
equation 35014 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ z
equation 35015 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ w
equation 35016 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ u
equation 35017 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ v
equation 35018 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ x)) ◇ x
equation 35019 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ x)) ◇ y
equation 35020 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ x)) ◇ z
equation 35021 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ x)) ◇ w
equation 35022 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ y)) ◇ x
equation 35023 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ y)) ◇ y
equation 35024 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ y)) ◇ z
equation 35025 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ y)) ◇ w
equation 35026 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ z)) ◇ x
equation 35027 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ z)) ◇ y
equation 35028 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ z)) ◇ z
equation 35029 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ z)) ◇ w
equation 35030 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ w)) ◇ x
equation 35031 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ w)) ◇ y
equation 35032 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ w)) ◇ z
equation 35033 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ w)) ◇ w
equation 35034 := x = ((y ◇ z) ◇ ((x ◇ x) ◇ w)) ◇ u
equation 35035 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ x)) ◇ x
equation 35036 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ x)) ◇ y
equation 35037 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ x)) ◇ z
equation 35038 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ x)) ◇ w
equation 35039 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ y)) ◇ x
equation 35040 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ y)) ◇ y
equation 35041 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ y)) ◇ z
equation 35042 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ y)) ◇ w
equation 35043 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ z)) ◇ x
equation 35044 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ z)) ◇ y
equation 35045 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ z)) ◇ z
equation 35046 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ z)) ◇ w
equation 35047 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ w)) ◇ x
equation 35048 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ w)) ◇ y
equation 35049 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ w)) ◇ z
equation 35050 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ w)) ◇ w
equation 35051 := x = ((y ◇ z) ◇ ((x ◇ y) ◇ w)) ◇ u
equation 35052 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ x)) ◇ x
equation 35053 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ x)) ◇ y
equation 35054 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ x)) ◇ z
equation 35055 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ x)) ◇ w
equation 35056 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ y)) ◇ x
equation 35057 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ y)) ◇ y
equation 35058 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ y)) ◇ z
equation 35059 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ y)) ◇ w
equation 35060 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ z)) ◇ x
equation 35061 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ z)) ◇ y
equation 35062 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ z)) ◇ z
equation 35063 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ z)) ◇ w
equation 35064 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ w)) ◇ x
equation 35065 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ w)) ◇ y
equation 35066 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ w)) ◇ z
equation 35067 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ w)) ◇ w
equation 35068 := x = ((y ◇ z) ◇ ((x ◇ z) ◇ w)) ◇ u
equation 35069 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ x)) ◇ x
equation 35070 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ x)) ◇ y
equation 35071 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ x)) ◇ z
equation 35072 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ x)) ◇ w
equation 35073 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ x)) ◇ u
equation 35074 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ y)) ◇ x
equation 35075 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ y)) ◇ y
equation 35076 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ y)) ◇ z
equation 35077 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ y)) ◇ w
equation 35078 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ y)) ◇ u
equation 35079 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ z)) ◇ x
equation 35080 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ z)) ◇ y
equation 35081 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ z)) ◇ z
equation 35082 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ z)) ◇ w
equation 35083 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ z)) ◇ u
equation 35084 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ w)) ◇ x
equation 35085 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ w)) ◇ y
equation 35086 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ w)) ◇ z
equation 35087 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ w)) ◇ w
equation 35088 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ w)) ◇ u
equation 35089 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ x
equation 35090 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ y
equation 35091 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ z
equation 35092 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ w
equation 35093 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ u
equation 35094 := x = ((y ◇ z) ◇ ((x ◇ w) ◇ u)) ◇ v
equation 35095 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ x)) ◇ x
equation 35096 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ x)) ◇ y
equation 35097 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ x)) ◇ z
equation 35098 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ x)) ◇ w
equation 35099 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ y)) ◇ x
equation 35100 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ y)) ◇ y
equation 35101 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ y)) ◇ z
equation 35102 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ y)) ◇ w
equation 35103 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ z)) ◇ x
equation 35104 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ z)) ◇ y
equation 35105 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ z)) ◇ z
equation 35106 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ z)) ◇ w
equation 35107 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ w)) ◇ x
equation 35108 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ w)) ◇ y
equation 35109 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ w)) ◇ z
equation 35110 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ w)) ◇ w
equation 35111 := x = ((y ◇ z) ◇ ((y ◇ x) ◇ w)) ◇ u
equation 35112 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ x)) ◇ x
equation 35113 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ x)) ◇ y
equation 35114 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ x)) ◇ z
equation 35115 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ x)) ◇ w
equation 35116 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ y)) ◇ x
equation 35117 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ y)) ◇ y
equation 35118 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ y)) ◇ z
equation 35119 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ y)) ◇ w
equation 35120 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ z)) ◇ x
equation 35121 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ z)) ◇ y
equation 35122 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ z)) ◇ z
equation 35123 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ z)) ◇ w
equation 35124 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ w)) ◇ x
equation 35125 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ w)) ◇ y
equation 35126 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ w)) ◇ z
equation 35127 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ w)) ◇ w
equation 35128 := x = ((y ◇ z) ◇ ((y ◇ y) ◇ w)) ◇ u
equation 35129 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ x)) ◇ x
equation 35130 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ x)) ◇ y
equation 35131 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ x)) ◇ z
equation 35132 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ x)) ◇ w
equation 35133 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ y)) ◇ x
equation 35134 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ y)) ◇ y
equation 35135 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ y)) ◇ z
equation 35136 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ y)) ◇ w
equation 35137 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ z)) ◇ x
equation 35138 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ z)) ◇ y
equation 35139 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ z)) ◇ z
equation 35140 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ z)) ◇ w
equation 35141 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ w)) ◇ x
equation 35142 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ w)) ◇ y
equation 35143 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ w)) ◇ z
equation 35144 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ w)) ◇ w
equation 35145 := x = ((y ◇ z) ◇ ((y ◇ z) ◇ w)) ◇ u
equation 35146 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ x)) ◇ x
equation 35147 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ x)) ◇ y
equation 35148 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ x)) ◇ z
equation 35149 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ x)) ◇ w
equation 35150 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ x)) ◇ u
equation 35151 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ y)) ◇ x
equation 35152 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ y)) ◇ y
equation 35153 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ y)) ◇ z
equation 35154 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ y)) ◇ w
equation 35155 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ y)) ◇ u
equation 35156 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ z)) ◇ x
equation 35157 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ z)) ◇ y
equation 35158 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ z)) ◇ z
equation 35159 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ z)) ◇ w
equation 35160 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ z)) ◇ u
equation 35161 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ w)) ◇ x
equation 35162 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ w)) ◇ y
equation 35163 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ w)) ◇ z
equation 35164 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ w)) ◇ w
equation 35165 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ w)) ◇ u
equation 35166 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ x
equation 35167 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ y
equation 35168 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ z
equation 35169 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ w
equation 35170 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ u
equation 35171 := x = ((y ◇ z) ◇ ((y ◇ w) ◇ u)) ◇ v
equation 35172 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ x)) ◇ x
equation 35173 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ x)) ◇ y
equation 35174 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ x)) ◇ z
equation 35175 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ x)) ◇ w
equation 35176 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ y)) ◇ x
equation 35177 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ y)) ◇ y
equation 35178 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ y)) ◇ z
equation 35179 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ y)) ◇ w
equation 35180 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ z)) ◇ x
equation 35181 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ z)) ◇ y
equation 35182 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ z)) ◇ z
equation 35183 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ z)) ◇ w
equation 35184 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ w)) ◇ x
equation 35185 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ w)) ◇ y
equation 35186 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ w)) ◇ z
equation 35187 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ w)) ◇ w
equation 35188 := x = ((y ◇ z) ◇ ((z ◇ x) ◇ w)) ◇ u
equation 35189 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ x)) ◇ x
equation 35190 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ x)) ◇ y
equation 35191 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ x)) ◇ z
equation 35192 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ x)) ◇ w
equation 35193 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ y)) ◇ x
equation 35194 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ y)) ◇ y
equation 35195 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ y)) ◇ z
equation 35196 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ y)) ◇ w
equation 35197 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ z)) ◇ x
equation 35198 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ z)) ◇ y
equation 35199 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ z)) ◇ z
equation 35200 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ z)) ◇ w
equation 35201 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ w)) ◇ x
equation 35202 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ w)) ◇ y
equation 35203 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ w)) ◇ z
equation 35204 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ w)) ◇ w
equation 35205 := x = ((y ◇ z) ◇ ((z ◇ y) ◇ w)) ◇ u
equation 35206 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ x)) ◇ x
equation 35207 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ x)) ◇ y
equation 35208 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ x)) ◇ z
equation 35209 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ x)) ◇ w
equation 35210 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ y)) ◇ x
equation 35211 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ y)) ◇ y
equation 35212 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ y)) ◇ z
equation 35213 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ y)) ◇ w
equation 35214 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ z)) ◇ x
equation 35215 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ z)) ◇ y
equation 35216 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ z)) ◇ z
equation 35217 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ z)) ◇ w
equation 35218 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ w)) ◇ x
equation 35219 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ w)) ◇ y
equation 35220 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ w)) ◇ z
equation 35221 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ w)) ◇ w
equation 35222 := x = ((y ◇ z) ◇ ((z ◇ z) ◇ w)) ◇ u
equation 35223 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ x)) ◇ x
equation 35224 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ x)) ◇ y
equation 35225 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ x)) ◇ z
equation 35226 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ x)) ◇ w
equation 35227 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ x)) ◇ u
equation 35228 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ y)) ◇ x
equation 35229 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ y)) ◇ y
equation 35230 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ y)) ◇ z
equation 35231 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ y)) ◇ w
equation 35232 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ y)) ◇ u
equation 35233 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ z)) ◇ x
equation 35234 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ z)) ◇ y
equation 35235 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ z)) ◇ z
equation 35236 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ z)) ◇ w
equation 35237 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ z)) ◇ u
equation 35238 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ w)) ◇ x
equation 35239 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ w)) ◇ y
equation 35240 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ w)) ◇ z
equation 35241 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ w)) ◇ w
equation 35242 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ w)) ◇ u
equation 35243 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ x
equation 35244 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ y
equation 35245 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ z
equation 35246 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ w
equation 35247 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ u
equation 35248 := x = ((y ◇ z) ◇ ((z ◇ w) ◇ u)) ◇ v
equation 35249 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ x)) ◇ x
equation 35250 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ x)) ◇ y
equation 35251 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ x)) ◇ z
equation 35252 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ x)) ◇ w
equation 35253 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ x)) ◇ u
equation 35254 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ y)) ◇ x
equation 35255 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ y)) ◇ y
equation 35256 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ y)) ◇ z
equation 35257 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ y)) ◇ w
equation 35258 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ y)) ◇ u
equation 35259 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ z)) ◇ x
equation 35260 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ z)) ◇ y
equation 35261 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ z)) ◇ z
equation 35262 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ z)) ◇ w
equation 35263 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ z)) ◇ u
equation 35264 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ w)) ◇ x
equation 35265 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ w)) ◇ y
equation 35266 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ w)) ◇ z
equation 35267 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ w)) ◇ w
equation 35268 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ w)) ◇ u
equation 35269 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ x
equation 35270 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ y
equation 35271 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ z
equation 35272 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ w
equation 35273 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ u
equation 35274 := x = ((y ◇ z) ◇ ((w ◇ x) ◇ u)) ◇ v
equation 35275 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ x)) ◇ x
equation 35276 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ x)) ◇ y
equation 35277 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ x)) ◇ z
equation 35278 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ x)) ◇ w
equation 35279 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ x)) ◇ u
equation 35280 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ y)) ◇ x
equation 35281 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ y)) ◇ y
equation 35282 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ y)) ◇ z
equation 35283 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ y)) ◇ w
equation 35284 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ y)) ◇ u
equation 35285 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ z)) ◇ x
equation 35286 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ z)) ◇ y
equation 35287 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ z)) ◇ z
equation 35288 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ z)) ◇ w
equation 35289 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ z)) ◇ u
equation 35290 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ w)) ◇ x
equation 35291 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ w)) ◇ y
equation 35292 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ w)) ◇ z
equation 35293 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ w)) ◇ w
equation 35294 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ w)) ◇ u
equation 35295 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ x
equation 35296 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ y
equation 35297 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ z
equation 35298 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ w
equation 35299 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ u
equation 35300 := x = ((y ◇ z) ◇ ((w ◇ y) ◇ u)) ◇ v
equation 35301 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ x)) ◇ x
equation 35302 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ x)) ◇ y
equation 35303 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ x)) ◇ z
equation 35304 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ x)) ◇ w
equation 35305 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ x)) ◇ u
equation 35306 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ y)) ◇ x
equation 35307 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ y)) ◇ y
equation 35308 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ y)) ◇ z
equation 35309 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ y)) ◇ w
equation 35310 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ y)) ◇ u
equation 35311 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ z)) ◇ x
equation 35312 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ z)) ◇ y
equation 35313 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ z)) ◇ z
equation 35314 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ z)) ◇ w
equation 35315 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ z)) ◇ u
equation 35316 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ w)) ◇ x
equation 35317 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ w)) ◇ y
equation 35318 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ w)) ◇ z
equation 35319 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ w)) ◇ w
equation 35320 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ w)) ◇ u
equation 35321 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ x
equation 35322 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ y
equation 35323 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ z
equation 35324 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ w
equation 35325 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ u
equation 35326 := x = ((y ◇ z) ◇ ((w ◇ z) ◇ u)) ◇ v
equation 35327 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ x)) ◇ x
equation 35328 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ x)) ◇ y
equation 35329 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ x)) ◇ z
equation 35330 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ x)) ◇ w
equation 35331 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ x)) ◇ u
equation 35332 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ y)) ◇ x
equation 35333 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ y)) ◇ y
equation 35334 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ y)) ◇ z
equation 35335 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ y)) ◇ w
equation 35336 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ y)) ◇ u
equation 35337 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ z)) ◇ x
equation 35338 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ z)) ◇ y
equation 35339 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ z)) ◇ z
equation 35340 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ z)) ◇ w
equation 35341 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ z)) ◇ u
equation 35342 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ w)) ◇ x
equation 35343 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ w)) ◇ y
equation 35344 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ w)) ◇ z
equation 35345 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ w)) ◇ w
equation 35346 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ w)) ◇ u
equation 35347 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ x
equation 35348 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ y
equation 35349 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ z
equation 35350 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ w
equation 35351 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ u
equation 35352 := x = ((y ◇ z) ◇ ((w ◇ w) ◇ u)) ◇ v
equation 35353 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ x
equation 35354 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ y
equation 35355 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ z
equation 35356 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ w
equation 35357 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ u
equation 35358 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ x)) ◇ v
equation 35359 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ x
equation 35360 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ y
equation 35361 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ z
equation 35362 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ w
equation 35363 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ u
equation 35364 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ y)) ◇ v
equation 35365 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ x
equation 35366 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ y
equation 35367 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ z
equation 35368 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ w
equation 35369 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ u
equation 35370 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ z)) ◇ v
equation 35371 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ x
equation 35372 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ y
equation 35373 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ z
equation 35374 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ w
equation 35375 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ u
equation 35376 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ w)) ◇ v
equation 35377 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ x
equation 35378 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ y
equation 35379 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ z
equation 35380 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ w
equation 35381 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ u
equation 35382 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ u)) ◇ v
equation 35383 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ x
equation 35384 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ y
equation 35385 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ z
equation 35386 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ w
equation 35387 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ u
equation 35388 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ v
equation 35389 := x = ((y ◇ z) ◇ ((w ◇ u) ◇ v)) ◇ r
equation 35390 := x = ((x ◇ (x ◇ x)) ◇ (x ◇ x)) ◇ x
equation 35391 := x = ((x ◇ (x ◇ x)) ◇ (x ◇ x)) ◇ y
equation 35392 := x = ((x ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ x
equation 35393 := x = ((x ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ y
equation 35394 := x = ((x ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ z
equation 35395 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ x
equation 35396 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ y
equation 35397 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ z
equation 35398 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ x
equation 35399 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ y
equation 35400 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ z
equation 35401 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ x
equation 35402 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ y
equation 35403 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ z
equation 35404 := x = ((x ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ w
equation 35405 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ x
equation 35406 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ y
equation 35407 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ z
equation 35408 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ x
equation 35409 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ y
equation 35410 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ z
equation 35411 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ x
equation 35412 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ y
equation 35413 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ z
equation 35414 := x = ((x ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ w
equation 35415 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ x
equation 35416 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ y
equation 35417 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ z
equation 35418 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ x
equation 35419 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ y
equation 35420 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ z
equation 35421 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ x
equation 35422 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ y
equation 35423 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ z
equation 35424 := x = ((x ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ w
equation 35425 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ x
equation 35426 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ y
equation 35427 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ z
equation 35428 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ w
equation 35429 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ x
equation 35430 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ y
equation 35431 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ z
equation 35432 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ w
equation 35433 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ x
equation 35434 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ y
equation 35435 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ z
equation 35436 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ w
equation 35437 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ x
equation 35438 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ y
equation 35439 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ z
equation 35440 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ w
equation 35441 := x = ((x ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ u
equation 35442 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ x
equation 35443 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ y
equation 35444 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ z
equation 35445 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ x
equation 35446 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ y
equation 35447 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ z
equation 35448 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ x
equation 35449 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ y
equation 35450 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ z
equation 35451 := x = ((x ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ w
equation 35452 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ x
equation 35453 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ y
equation 35454 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ z
equation 35455 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ x
equation 35456 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ y
equation 35457 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ z
equation 35458 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ x
equation 35459 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ y
equation 35460 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ z
equation 35461 := x = ((x ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ w
equation 35462 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ x
equation 35463 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ y
equation 35464 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ z
equation 35465 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ w
equation 35466 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ x
equation 35467 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ y
equation 35468 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ z
equation 35469 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ w
equation 35470 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ x
equation 35471 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ y
equation 35472 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ z
equation 35473 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ w
equation 35474 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ x
equation 35475 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ y
equation 35476 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ z
equation 35477 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ w
equation 35478 := x = ((x ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ u
equation 35479 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ x
equation 35480 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ y
equation 35481 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ z
equation 35482 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ x
equation 35483 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ y
equation 35484 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ z
equation 35485 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ x
equation 35486 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ y
equation 35487 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ z
equation 35488 := x = ((x ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ w
equation 35489 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ x
equation 35490 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ y
equation 35491 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ z
equation 35492 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ x
equation 35493 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ y
equation 35494 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ z
equation 35495 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ x
equation 35496 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ y
equation 35497 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ z
equation 35498 := x = ((x ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ w
equation 35499 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ x
equation 35500 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ y
equation 35501 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ z
equation 35502 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ w
equation 35503 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ x
equation 35504 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ y
equation 35505 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ z
equation 35506 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ w
equation 35507 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ x
equation 35508 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ y
equation 35509 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ z
equation 35510 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ w
equation 35511 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ x
equation 35512 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ y
equation 35513 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ z
equation 35514 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ w
equation 35515 := x = ((x ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ u
equation 35516 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ x
equation 35517 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ y
equation 35518 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ z
equation 35519 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ w
equation 35520 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ x
equation 35521 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ y
equation 35522 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ z
equation 35523 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ w
equation 35524 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ x
equation 35525 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ y
equation 35526 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ z
equation 35527 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ w
equation 35528 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ x
equation 35529 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ y
equation 35530 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ z
equation 35531 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ w
equation 35532 := x = ((x ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ u
equation 35533 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ x
equation 35534 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ y
equation 35535 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ z
equation 35536 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ w
equation 35537 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ x
equation 35538 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ y
equation 35539 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ z
equation 35540 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ w
equation 35541 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ x
equation 35542 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ y
equation 35543 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ z
equation 35544 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ w
equation 35545 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ x
equation 35546 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ y
equation 35547 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ z
equation 35548 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ w
equation 35549 := x = ((x ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ u
equation 35550 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ x
equation 35551 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ y
equation 35552 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ z
equation 35553 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ w
equation 35554 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ x
equation 35555 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ y
equation 35556 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ z
equation 35557 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ w
equation 35558 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ x
equation 35559 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ y
equation 35560 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ z
equation 35561 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ w
equation 35562 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ x
equation 35563 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ y
equation 35564 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ z
equation 35565 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ w
equation 35566 := x = ((x ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ u
equation 35567 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ x
equation 35568 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ y
equation 35569 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ z
equation 35570 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ w
equation 35571 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ u
equation 35572 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ x
equation 35573 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ y
equation 35574 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ z
equation 35575 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ w
equation 35576 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ u
equation 35577 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ x
equation 35578 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ y
equation 35579 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ z
equation 35580 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ w
equation 35581 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ u
equation 35582 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ x
equation 35583 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ y
equation 35584 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ z
equation 35585 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ w
equation 35586 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ u
equation 35587 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ x
equation 35588 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ y
equation 35589 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ z
equation 35590 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ w
equation 35591 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ u
equation 35592 := x = ((x ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ v
equation 35593 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ x)) ◇ x
equation 35594 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ x)) ◇ y
equation 35595 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ x)) ◇ z
equation 35596 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ x
equation 35597 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ y
equation 35598 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ y)) ◇ z
equation 35599 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ z)) ◇ x
equation 35600 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ z)) ◇ y
equation 35601 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ z)) ◇ z
equation 35602 := x = ((y ◇ (x ◇ x)) ◇ (x ◇ z)) ◇ w
equation 35603 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ x
equation 35604 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ y
equation 35605 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ x)) ◇ z
equation 35606 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ x
equation 35607 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ y
equation 35608 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ y)) ◇ z
equation 35609 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ x
equation 35610 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ y
equation 35611 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ z
equation 35612 := x = ((y ◇ (x ◇ x)) ◇ (y ◇ z)) ◇ w
equation 35613 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ x)) ◇ x
equation 35614 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ x)) ◇ y
equation 35615 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ x)) ◇ z
equation 35616 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ x)) ◇ w
equation 35617 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ y)) ◇ x
equation 35618 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ y)) ◇ y
equation 35619 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ y)) ◇ z
equation 35620 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ y)) ◇ w
equation 35621 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ z)) ◇ x
equation 35622 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ z)) ◇ y
equation 35623 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ z)) ◇ z
equation 35624 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ z)) ◇ w
equation 35625 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ w)) ◇ x
equation 35626 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ w)) ◇ y
equation 35627 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ w)) ◇ z
equation 35628 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ w)) ◇ w
equation 35629 := x = ((y ◇ (x ◇ x)) ◇ (z ◇ w)) ◇ u
equation 35630 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ x
equation 35631 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ y
equation 35632 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ x)) ◇ z
equation 35633 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ x
equation 35634 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ y
equation 35635 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ y)) ◇ z
equation 35636 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ x
equation 35637 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ y
equation 35638 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ z
equation 35639 := x = ((y ◇ (x ◇ y)) ◇ (x ◇ z)) ◇ w
equation 35640 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ x
equation 35641 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ y
equation 35642 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ x)) ◇ z
equation 35643 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ x
equation 35644 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ y
equation 35645 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ y)) ◇ z
equation 35646 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ x
equation 35647 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ y
equation 35648 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ z
equation 35649 := x = ((y ◇ (x ◇ y)) ◇ (y ◇ z)) ◇ w
equation 35650 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ x
equation 35651 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ y
equation 35652 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ z
equation 35653 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ x)) ◇ w
equation 35654 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ x
equation 35655 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ y
equation 35656 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ z
equation 35657 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ y)) ◇ w
equation 35658 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ x
equation 35659 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ y
equation 35660 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ z
equation 35661 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ z)) ◇ w
equation 35662 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ x
equation 35663 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ y
equation 35664 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ z
equation 35665 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ w
equation 35666 := x = ((y ◇ (x ◇ y)) ◇ (z ◇ w)) ◇ u
equation 35667 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ x)) ◇ x
equation 35668 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ x)) ◇ y
equation 35669 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ x)) ◇ z
equation 35670 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ x)) ◇ w
equation 35671 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ y)) ◇ x
equation 35672 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ y)) ◇ y
equation 35673 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ y)) ◇ z
equation 35674 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ y)) ◇ w
equation 35675 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ z)) ◇ x
equation 35676 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ z)) ◇ y
equation 35677 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ z)) ◇ z
equation 35678 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ z)) ◇ w
equation 35679 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ w)) ◇ x
equation 35680 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ w)) ◇ y
equation 35681 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ w)) ◇ z
equation 35682 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ w)) ◇ w
equation 35683 := x = ((y ◇ (x ◇ z)) ◇ (x ◇ w)) ◇ u
equation 35684 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ x)) ◇ x
equation 35685 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ x)) ◇ y
equation 35686 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ x)) ◇ z
equation 35687 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ x)) ◇ w
equation 35688 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ y)) ◇ x
equation 35689 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ y)) ◇ y
equation 35690 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ y)) ◇ z
equation 35691 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ y)) ◇ w
equation 35692 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ z)) ◇ x
equation 35693 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ z)) ◇ y
equation 35694 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ z)) ◇ z
equation 35695 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ z)) ◇ w
equation 35696 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ w)) ◇ x
equation 35697 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ w)) ◇ y
equation 35698 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ w)) ◇ z
equation 35699 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ w)) ◇ w
equation 35700 := x = ((y ◇ (x ◇ z)) ◇ (y ◇ w)) ◇ u
equation 35701 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ x)) ◇ x
equation 35702 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ x)) ◇ y
equation 35703 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ x)) ◇ z
equation 35704 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ x)) ◇ w
equation 35705 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ y)) ◇ x
equation 35706 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ y)) ◇ y
equation 35707 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ y)) ◇ z
equation 35708 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ y)) ◇ w
equation 35709 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ z)) ◇ x
equation 35710 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ z)) ◇ y
equation 35711 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ z)) ◇ z
equation 35712 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ z)) ◇ w
equation 35713 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ w)) ◇ x
equation 35714 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ w)) ◇ y
equation 35715 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ w)) ◇ z
equation 35716 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ w)) ◇ w
equation 35717 := x = ((y ◇ (x ◇ z)) ◇ (z ◇ w)) ◇ u
equation 35718 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ x)) ◇ x
equation 35719 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ x)) ◇ y
equation 35720 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ x)) ◇ z
equation 35721 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ x)) ◇ w
equation 35722 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ x)) ◇ u
equation 35723 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ y)) ◇ x
equation 35724 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ y)) ◇ y
equation 35725 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ y)) ◇ z
equation 35726 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ y)) ◇ w
equation 35727 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ y)) ◇ u
equation 35728 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ z)) ◇ x
equation 35729 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ z)) ◇ y
equation 35730 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ z)) ◇ z
equation 35731 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ z)) ◇ w
equation 35732 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ z)) ◇ u
equation 35733 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ w)) ◇ x
equation 35734 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ w)) ◇ y
equation 35735 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ w)) ◇ z
equation 35736 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ w)) ◇ w
equation 35737 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ w)) ◇ u
equation 35738 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ x
equation 35739 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ y
equation 35740 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ z
equation 35741 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ w
equation 35742 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ u
equation 35743 := x = ((y ◇ (x ◇ z)) ◇ (w ◇ u)) ◇ v
equation 35744 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ x
equation 35745 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ y
equation 35746 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ x)) ◇ z
equation 35747 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ x
equation 35748 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ y
equation 35749 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ y)) ◇ z
equation 35750 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ x
equation 35751 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ y
equation 35752 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ z
equation 35753 := x = ((y ◇ (y ◇ x)) ◇ (x ◇ z)) ◇ w
equation 35754 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ x
equation 35755 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ y
equation 35756 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ x)) ◇ z
equation 35757 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ x
equation 35758 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ y
equation 35759 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ y)) ◇ z
equation 35760 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ x
equation 35761 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ y
equation 35762 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ z
equation 35763 := x = ((y ◇ (y ◇ x)) ◇ (y ◇ z)) ◇ w
equation 35764 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ x
equation 35765 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ y
equation 35766 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ z
equation 35767 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ x)) ◇ w
equation 35768 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ x
equation 35769 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ y
equation 35770 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ z
equation 35771 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ y)) ◇ w
equation 35772 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ x
equation 35773 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ y
equation 35774 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ z
equation 35775 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ z)) ◇ w
equation 35776 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ x
equation 35777 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ y
equation 35778 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ z
equation 35779 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ w
equation 35780 := x = ((y ◇ (y ◇ x)) ◇ (z ◇ w)) ◇ u
equation 35781 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ x
equation 35782 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ y
equation 35783 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ x)) ◇ z
equation 35784 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ x
equation 35785 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ y
equation 35786 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ y)) ◇ z
equation 35787 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ x
equation 35788 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ y
equation 35789 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ z
equation 35790 := x = ((y ◇ (y ◇ y)) ◇ (x ◇ z)) ◇ w
equation 35791 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ x
equation 35792 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ y
equation 35793 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ x)) ◇ z
equation 35794 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ x
equation 35795 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ y
equation 35796 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ y)) ◇ z
equation 35797 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ x
equation 35798 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ y
equation 35799 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ z
equation 35800 := x = ((y ◇ (y ◇ y)) ◇ (y ◇ z)) ◇ w
equation 35801 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ x
equation 35802 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ y
equation 35803 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ z
equation 35804 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ x)) ◇ w
equation 35805 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ x
equation 35806 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ y
equation 35807 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ z
equation 35808 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ y)) ◇ w
equation 35809 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ x
equation 35810 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ y
equation 35811 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ z
equation 35812 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ z)) ◇ w
equation 35813 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ x
equation 35814 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ y
equation 35815 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ z
equation 35816 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ w
equation 35817 := x = ((y ◇ (y ◇ y)) ◇ (z ◇ w)) ◇ u
equation 35818 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ x
equation 35819 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ y
equation 35820 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ z
equation 35821 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ x)) ◇ w
equation 35822 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ x
equation 35823 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ y
equation 35824 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ z
equation 35825 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ y)) ◇ w
equation 35826 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ x
equation 35827 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ y
equation 35828 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ z
equation 35829 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ z)) ◇ w
equation 35830 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ x
equation 35831 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ y
equation 35832 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ z
equation 35833 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ w
equation 35834 := x = ((y ◇ (y ◇ z)) ◇ (x ◇ w)) ◇ u
equation 35835 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ x
equation 35836 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ y
equation 35837 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ z
equation 35838 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ x)) ◇ w
equation 35839 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ x
equation 35840 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ y
equation 35841 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ z
equation 35842 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ y)) ◇ w
equation 35843 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ x
equation 35844 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ y
equation 35845 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ z
equation 35846 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ z)) ◇ w
equation 35847 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ x
equation 35848 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ y
equation 35849 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ z
equation 35850 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ w
equation 35851 := x = ((y ◇ (y ◇ z)) ◇ (y ◇ w)) ◇ u
equation 35852 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ x
equation 35853 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ y
equation 35854 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ z
equation 35855 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ x)) ◇ w
equation 35856 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ x
equation 35857 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ y
equation 35858 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ z
equation 35859 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ y)) ◇ w
equation 35860 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ x
equation 35861 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ y
equation 35862 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ z
equation 35863 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ z)) ◇ w
equation 35864 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ x
equation 35865 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ y
equation 35866 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ z
equation 35867 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ w
equation 35868 := x = ((y ◇ (y ◇ z)) ◇ (z ◇ w)) ◇ u
equation 35869 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ x
equation 35870 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ y
equation 35871 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ z
equation 35872 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ w
equation 35873 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ x)) ◇ u
equation 35874 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ x
equation 35875 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ y
equation 35876 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ z
equation 35877 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ w
equation 35878 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ y)) ◇ u
equation 35879 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ x
equation 35880 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ y
equation 35881 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ z
equation 35882 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ w
equation 35883 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ z)) ◇ u
equation 35884 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ x
equation 35885 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ y
equation 35886 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ z
equation 35887 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ w
equation 35888 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ w)) ◇ u
equation 35889 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ x
equation 35890 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ y
equation 35891 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ z
equation 35892 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ w
equation 35893 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ u
equation 35894 := x = ((y ◇ (y ◇ z)) ◇ (w ◇ u)) ◇ v
equation 35895 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ x)) ◇ x
equation 35896 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ x)) ◇ y
equation 35897 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ x)) ◇ z
equation 35898 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ x)) ◇ w
equation 35899 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ y)) ◇ x
equation 35900 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ y)) ◇ y
equation 35901 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ y)) ◇ z
equation 35902 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ y)) ◇ w
equation 35903 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ z)) ◇ x
equation 35904 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ z)) ◇ y
equation 35905 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ z)) ◇ z
equation 35906 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ z)) ◇ w
equation 35907 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ w)) ◇ x
equation 35908 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ w)) ◇ y
equation 35909 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ w)) ◇ z
equation 35910 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ w)) ◇ w
equation 35911 := x = ((y ◇ (z ◇ x)) ◇ (x ◇ w)) ◇ u
equation 35912 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ x)) ◇ x
equation 35913 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ x)) ◇ y
equation 35914 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ x)) ◇ z
equation 35915 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ x)) ◇ w
equation 35916 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ y)) ◇ x
equation 35917 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ y)) ◇ y
equation 35918 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ y)) ◇ z
equation 35919 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ y)) ◇ w
equation 35920 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ z)) ◇ x
equation 35921 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ z)) ◇ y
equation 35922 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ z)) ◇ z
equation 35923 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ z)) ◇ w
equation 35924 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ w)) ◇ x
equation 35925 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ w)) ◇ y
equation 35926 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ w)) ◇ z
equation 35927 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ w)) ◇ w
equation 35928 := x = ((y ◇ (z ◇ x)) ◇ (y ◇ w)) ◇ u
equation 35929 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ x)) ◇ x
equation 35930 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ x)) ◇ y
equation 35931 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ x)) ◇ z
equation 35932 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ x)) ◇ w
equation 35933 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ y)) ◇ x
equation 35934 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ y)) ◇ y
equation 35935 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ y)) ◇ z
equation 35936 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ y)) ◇ w
equation 35937 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ z)) ◇ x
equation 35938 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ z)) ◇ y
equation 35939 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ z)) ◇ z
equation 35940 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ z)) ◇ w
equation 35941 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ w)) ◇ x
equation 35942 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ w)) ◇ y
equation 35943 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ w)) ◇ z
equation 35944 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ w)) ◇ w
equation 35945 := x = ((y ◇ (z ◇ x)) ◇ (z ◇ w)) ◇ u
equation 35946 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ x)) ◇ x
equation 35947 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ x)) ◇ y
equation 35948 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ x)) ◇ z
equation 35949 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ x)) ◇ w
equation 35950 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ x)) ◇ u
equation 35951 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ y)) ◇ x
equation 35952 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ y)) ◇ y
equation 35953 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ y)) ◇ z
equation 35954 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ y)) ◇ w
equation 35955 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ y)) ◇ u
equation 35956 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ z)) ◇ x
equation 35957 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ z)) ◇ y
equation 35958 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ z)) ◇ z
equation 35959 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ z)) ◇ w
equation 35960 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ z)) ◇ u
equation 35961 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ w)) ◇ x
equation 35962 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ w)) ◇ y
equation 35963 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ w)) ◇ z
equation 35964 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ w)) ◇ w
equation 35965 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ w)) ◇ u
equation 35966 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ x
equation 35967 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ y
equation 35968 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ z
equation 35969 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ w
equation 35970 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ u
equation 35971 := x = ((y ◇ (z ◇ x)) ◇ (w ◇ u)) ◇ v
equation 35972 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ x)) ◇ x
equation 35973 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ x)) ◇ y
equation 35974 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ x)) ◇ z
equation 35975 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ x)) ◇ w
equation 35976 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ y)) ◇ x
equation 35977 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ y)) ◇ y
equation 35978 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ y)) ◇ z
equation 35979 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ y)) ◇ w
equation 35980 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ z)) ◇ x
equation 35981 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ z)) ◇ y
equation 35982 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ z)) ◇ z
equation 35983 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ z)) ◇ w
equation 35984 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ w)) ◇ x
equation 35985 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ w)) ◇ y
equation 35986 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ w)) ◇ z
equation 35987 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ w)) ◇ w
equation 35988 := x = ((y ◇ (z ◇ y)) ◇ (x ◇ w)) ◇ u
equation 35989 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ x)) ◇ x
equation 35990 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ x)) ◇ y
equation 35991 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ x)) ◇ z
equation 35992 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ x)) ◇ w
equation 35993 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ y)) ◇ x
equation 35994 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ y)) ◇ y
equation 35995 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ y)) ◇ z
equation 35996 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ y)) ◇ w
equation 35997 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ z)) ◇ x
equation 35998 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ z)) ◇ y
equation 35999 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ z)) ◇ z
