import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 50000-50999 -/

equation 50000 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ z
equation 50001 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ w
equation 50002 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ u
equation 50003 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ v
equation 50004 := x ◇ y = (z ◇ (y ◇ (x ◇ x))) ◇ x
equation 50005 := x ◇ y = (z ◇ (y ◇ (x ◇ x))) ◇ y
equation 50006 := x ◇ y = (z ◇ (y ◇ (x ◇ x))) ◇ z
equation 50007 := x ◇ y = (z ◇ (y ◇ (x ◇ x))) ◇ w
equation 50008 := x ◇ y = (z ◇ (y ◇ (x ◇ y))) ◇ x
equation 50009 := x ◇ y = (z ◇ (y ◇ (x ◇ y))) ◇ y
equation 50010 := x ◇ y = (z ◇ (y ◇ (x ◇ y))) ◇ z
equation 50011 := x ◇ y = (z ◇ (y ◇ (x ◇ y))) ◇ w
equation 50012 := x ◇ y = (z ◇ (y ◇ (x ◇ z))) ◇ x
equation 50013 := x ◇ y = (z ◇ (y ◇ (x ◇ z))) ◇ y
equation 50014 := x ◇ y = (z ◇ (y ◇ (x ◇ z))) ◇ z
equation 50015 := x ◇ y = (z ◇ (y ◇ (x ◇ z))) ◇ w
equation 50016 := x ◇ y = (z ◇ (y ◇ (x ◇ w))) ◇ x
equation 50017 := x ◇ y = (z ◇ (y ◇ (x ◇ w))) ◇ y
equation 50018 := x ◇ y = (z ◇ (y ◇ (x ◇ w))) ◇ z
equation 50019 := x ◇ y = (z ◇ (y ◇ (x ◇ w))) ◇ w
equation 50020 := x ◇ y = (z ◇ (y ◇ (x ◇ w))) ◇ u
equation 50021 := x ◇ y = (z ◇ (y ◇ (y ◇ x))) ◇ x
equation 50022 := x ◇ y = (z ◇ (y ◇ (y ◇ x))) ◇ y
equation 50023 := x ◇ y = (z ◇ (y ◇ (y ◇ x))) ◇ z
equation 50024 := x ◇ y = (z ◇ (y ◇ (y ◇ x))) ◇ w
equation 50025 := x ◇ y = (z ◇ (y ◇ (y ◇ y))) ◇ x
equation 50026 := x ◇ y = (z ◇ (y ◇ (y ◇ y))) ◇ y
equation 50027 := x ◇ y = (z ◇ (y ◇ (y ◇ y))) ◇ z
equation 50028 := x ◇ y = (z ◇ (y ◇ (y ◇ y))) ◇ w
equation 50029 := x ◇ y = (z ◇ (y ◇ (y ◇ z))) ◇ x
equation 50030 := x ◇ y = (z ◇ (y ◇ (y ◇ z))) ◇ y
equation 50031 := x ◇ y = (z ◇ (y ◇ (y ◇ z))) ◇ z
equation 50032 := x ◇ y = (z ◇ (y ◇ (y ◇ z))) ◇ w
equation 50033 := x ◇ y = (z ◇ (y ◇ (y ◇ w))) ◇ x
equation 50034 := x ◇ y = (z ◇ (y ◇ (y ◇ w))) ◇ y
equation 50035 := x ◇ y = (z ◇ (y ◇ (y ◇ w))) ◇ z
equation 50036 := x ◇ y = (z ◇ (y ◇ (y ◇ w))) ◇ w
equation 50037 := x ◇ y = (z ◇ (y ◇ (y ◇ w))) ◇ u
equation 50038 := x ◇ y = (z ◇ (y ◇ (z ◇ x))) ◇ x
equation 50039 := x ◇ y = (z ◇ (y ◇ (z ◇ x))) ◇ y
equation 50040 := x ◇ y = (z ◇ (y ◇ (z ◇ x))) ◇ z
equation 50041 := x ◇ y = (z ◇ (y ◇ (z ◇ x))) ◇ w
equation 50042 := x ◇ y = (z ◇ (y ◇ (z ◇ y))) ◇ x
equation 50043 := x ◇ y = (z ◇ (y ◇ (z ◇ y))) ◇ y
equation 50044 := x ◇ y = (z ◇ (y ◇ (z ◇ y))) ◇ z
equation 50045 := x ◇ y = (z ◇ (y ◇ (z ◇ y))) ◇ w
equation 50046 := x ◇ y = (z ◇ (y ◇ (z ◇ z))) ◇ x
equation 50047 := x ◇ y = (z ◇ (y ◇ (z ◇ z))) ◇ y
equation 50048 := x ◇ y = (z ◇ (y ◇ (z ◇ z))) ◇ z
equation 50049 := x ◇ y = (z ◇ (y ◇ (z ◇ z))) ◇ w
equation 50050 := x ◇ y = (z ◇ (y ◇ (z ◇ w))) ◇ x
equation 50051 := x ◇ y = (z ◇ (y ◇ (z ◇ w))) ◇ y
equation 50052 := x ◇ y = (z ◇ (y ◇ (z ◇ w))) ◇ z
equation 50053 := x ◇ y = (z ◇ (y ◇ (z ◇ w))) ◇ w
equation 50054 := x ◇ y = (z ◇ (y ◇ (z ◇ w))) ◇ u
equation 50055 := x ◇ y = (z ◇ (y ◇ (w ◇ x))) ◇ x
equation 50056 := x ◇ y = (z ◇ (y ◇ (w ◇ x))) ◇ y
equation 50057 := x ◇ y = (z ◇ (y ◇ (w ◇ x))) ◇ z
equation 50058 := x ◇ y = (z ◇ (y ◇ (w ◇ x))) ◇ w
equation 50059 := x ◇ y = (z ◇ (y ◇ (w ◇ x))) ◇ u
equation 50060 := x ◇ y = (z ◇ (y ◇ (w ◇ y))) ◇ x
equation 50061 := x ◇ y = (z ◇ (y ◇ (w ◇ y))) ◇ y
equation 50062 := x ◇ y = (z ◇ (y ◇ (w ◇ y))) ◇ z
equation 50063 := x ◇ y = (z ◇ (y ◇ (w ◇ y))) ◇ w
equation 50064 := x ◇ y = (z ◇ (y ◇ (w ◇ y))) ◇ u
equation 50065 := x ◇ y = (z ◇ (y ◇ (w ◇ z))) ◇ x
equation 50066 := x ◇ y = (z ◇ (y ◇ (w ◇ z))) ◇ y
equation 50067 := x ◇ y = (z ◇ (y ◇ (w ◇ z))) ◇ z
equation 50068 := x ◇ y = (z ◇ (y ◇ (w ◇ z))) ◇ w
equation 50069 := x ◇ y = (z ◇ (y ◇ (w ◇ z))) ◇ u
equation 50070 := x ◇ y = (z ◇ (y ◇ (w ◇ w))) ◇ x
equation 50071 := x ◇ y = (z ◇ (y ◇ (w ◇ w))) ◇ y
equation 50072 := x ◇ y = (z ◇ (y ◇ (w ◇ w))) ◇ z
equation 50073 := x ◇ y = (z ◇ (y ◇ (w ◇ w))) ◇ w
equation 50074 := x ◇ y = (z ◇ (y ◇ (w ◇ w))) ◇ u
equation 50075 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ x
equation 50076 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ y
equation 50077 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ z
equation 50078 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ w
equation 50079 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ u
equation 50080 := x ◇ y = (z ◇ (y ◇ (w ◇ u))) ◇ v
equation 50081 := x ◇ y = (z ◇ (z ◇ (x ◇ x))) ◇ x
equation 50082 := x ◇ y = (z ◇ (z ◇ (x ◇ x))) ◇ y
equation 50083 := x ◇ y = (z ◇ (z ◇ (x ◇ x))) ◇ z
equation 50084 := x ◇ y = (z ◇ (z ◇ (x ◇ x))) ◇ w
equation 50085 := x ◇ y = (z ◇ (z ◇ (x ◇ y))) ◇ x
equation 50086 := x ◇ y = (z ◇ (z ◇ (x ◇ y))) ◇ y
equation 50087 := x ◇ y = (z ◇ (z ◇ (x ◇ y))) ◇ z
equation 50088 := x ◇ y = (z ◇ (z ◇ (x ◇ y))) ◇ w
equation 50089 := x ◇ y = (z ◇ (z ◇ (x ◇ z))) ◇ x
equation 50090 := x ◇ y = (z ◇ (z ◇ (x ◇ z))) ◇ y
equation 50091 := x ◇ y = (z ◇ (z ◇ (x ◇ z))) ◇ z
equation 50092 := x ◇ y = (z ◇ (z ◇ (x ◇ z))) ◇ w
equation 50093 := x ◇ y = (z ◇ (z ◇ (x ◇ w))) ◇ x
equation 50094 := x ◇ y = (z ◇ (z ◇ (x ◇ w))) ◇ y
equation 50095 := x ◇ y = (z ◇ (z ◇ (x ◇ w))) ◇ z
equation 50096 := x ◇ y = (z ◇ (z ◇ (x ◇ w))) ◇ w
equation 50097 := x ◇ y = (z ◇ (z ◇ (x ◇ w))) ◇ u
equation 50098 := x ◇ y = (z ◇ (z ◇ (y ◇ x))) ◇ x
equation 50099 := x ◇ y = (z ◇ (z ◇ (y ◇ x))) ◇ y
equation 50100 := x ◇ y = (z ◇ (z ◇ (y ◇ x))) ◇ z
equation 50101 := x ◇ y = (z ◇ (z ◇ (y ◇ x))) ◇ w
equation 50102 := x ◇ y = (z ◇ (z ◇ (y ◇ y))) ◇ x
equation 50103 := x ◇ y = (z ◇ (z ◇ (y ◇ y))) ◇ y
equation 50104 := x ◇ y = (z ◇ (z ◇ (y ◇ y))) ◇ z
equation 50105 := x ◇ y = (z ◇ (z ◇ (y ◇ y))) ◇ w
equation 50106 := x ◇ y = (z ◇ (z ◇ (y ◇ z))) ◇ x
equation 50107 := x ◇ y = (z ◇ (z ◇ (y ◇ z))) ◇ y
equation 50108 := x ◇ y = (z ◇ (z ◇ (y ◇ z))) ◇ z
equation 50109 := x ◇ y = (z ◇ (z ◇ (y ◇ z))) ◇ w
equation 50110 := x ◇ y = (z ◇ (z ◇ (y ◇ w))) ◇ x
equation 50111 := x ◇ y = (z ◇ (z ◇ (y ◇ w))) ◇ y
equation 50112 := x ◇ y = (z ◇ (z ◇ (y ◇ w))) ◇ z
equation 50113 := x ◇ y = (z ◇ (z ◇ (y ◇ w))) ◇ w
equation 50114 := x ◇ y = (z ◇ (z ◇ (y ◇ w))) ◇ u
equation 50115 := x ◇ y = (z ◇ (z ◇ (z ◇ x))) ◇ x
equation 50116 := x ◇ y = (z ◇ (z ◇ (z ◇ x))) ◇ y
equation 50117 := x ◇ y = (z ◇ (z ◇ (z ◇ x))) ◇ z
equation 50118 := x ◇ y = (z ◇ (z ◇ (z ◇ x))) ◇ w
equation 50119 := x ◇ y = (z ◇ (z ◇ (z ◇ y))) ◇ x
equation 50120 := x ◇ y = (z ◇ (z ◇ (z ◇ y))) ◇ y
equation 50121 := x ◇ y = (z ◇ (z ◇ (z ◇ y))) ◇ z
equation 50122 := x ◇ y = (z ◇ (z ◇ (z ◇ y))) ◇ w
equation 50123 := x ◇ y = (z ◇ (z ◇ (z ◇ z))) ◇ x
equation 50124 := x ◇ y = (z ◇ (z ◇ (z ◇ z))) ◇ y
equation 50125 := x ◇ y = (z ◇ (z ◇ (z ◇ z))) ◇ z
equation 50126 := x ◇ y = (z ◇ (z ◇ (z ◇ z))) ◇ w
equation 50127 := x ◇ y = (z ◇ (z ◇ (z ◇ w))) ◇ x
equation 50128 := x ◇ y = (z ◇ (z ◇ (z ◇ w))) ◇ y
equation 50129 := x ◇ y = (z ◇ (z ◇ (z ◇ w))) ◇ z
equation 50130 := x ◇ y = (z ◇ (z ◇ (z ◇ w))) ◇ w
equation 50131 := x ◇ y = (z ◇ (z ◇ (z ◇ w))) ◇ u
equation 50132 := x ◇ y = (z ◇ (z ◇ (w ◇ x))) ◇ x
equation 50133 := x ◇ y = (z ◇ (z ◇ (w ◇ x))) ◇ y
equation 50134 := x ◇ y = (z ◇ (z ◇ (w ◇ x))) ◇ z
equation 50135 := x ◇ y = (z ◇ (z ◇ (w ◇ x))) ◇ w
equation 50136 := x ◇ y = (z ◇ (z ◇ (w ◇ x))) ◇ u
equation 50137 := x ◇ y = (z ◇ (z ◇ (w ◇ y))) ◇ x
equation 50138 := x ◇ y = (z ◇ (z ◇ (w ◇ y))) ◇ y
equation 50139 := x ◇ y = (z ◇ (z ◇ (w ◇ y))) ◇ z
equation 50140 := x ◇ y = (z ◇ (z ◇ (w ◇ y))) ◇ w
equation 50141 := x ◇ y = (z ◇ (z ◇ (w ◇ y))) ◇ u
equation 50142 := x ◇ y = (z ◇ (z ◇ (w ◇ z))) ◇ x
equation 50143 := x ◇ y = (z ◇ (z ◇ (w ◇ z))) ◇ y
equation 50144 := x ◇ y = (z ◇ (z ◇ (w ◇ z))) ◇ z
equation 50145 := x ◇ y = (z ◇ (z ◇ (w ◇ z))) ◇ w
equation 50146 := x ◇ y = (z ◇ (z ◇ (w ◇ z))) ◇ u
equation 50147 := x ◇ y = (z ◇ (z ◇ (w ◇ w))) ◇ x
equation 50148 := x ◇ y = (z ◇ (z ◇ (w ◇ w))) ◇ y
equation 50149 := x ◇ y = (z ◇ (z ◇ (w ◇ w))) ◇ z
equation 50150 := x ◇ y = (z ◇ (z ◇ (w ◇ w))) ◇ w
equation 50151 := x ◇ y = (z ◇ (z ◇ (w ◇ w))) ◇ u
equation 50152 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ x
equation 50153 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ y
equation 50154 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ z
equation 50155 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ w
equation 50156 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ u
equation 50157 := x ◇ y = (z ◇ (z ◇ (w ◇ u))) ◇ v
equation 50158 := x ◇ y = (z ◇ (w ◇ (x ◇ x))) ◇ x
equation 50159 := x ◇ y = (z ◇ (w ◇ (x ◇ x))) ◇ y
equation 50160 := x ◇ y = (z ◇ (w ◇ (x ◇ x))) ◇ z
equation 50161 := x ◇ y = (z ◇ (w ◇ (x ◇ x))) ◇ w
equation 50162 := x ◇ y = (z ◇ (w ◇ (x ◇ x))) ◇ u
equation 50163 := x ◇ y = (z ◇ (w ◇ (x ◇ y))) ◇ x
equation 50164 := x ◇ y = (z ◇ (w ◇ (x ◇ y))) ◇ y
equation 50165 := x ◇ y = (z ◇ (w ◇ (x ◇ y))) ◇ z
equation 50166 := x ◇ y = (z ◇ (w ◇ (x ◇ y))) ◇ w
equation 50167 := x ◇ y = (z ◇ (w ◇ (x ◇ y))) ◇ u
equation 50168 := x ◇ y = (z ◇ (w ◇ (x ◇ z))) ◇ x
equation 50169 := x ◇ y = (z ◇ (w ◇ (x ◇ z))) ◇ y
equation 50170 := x ◇ y = (z ◇ (w ◇ (x ◇ z))) ◇ z
equation 50171 := x ◇ y = (z ◇ (w ◇ (x ◇ z))) ◇ w
equation 50172 := x ◇ y = (z ◇ (w ◇ (x ◇ z))) ◇ u
equation 50173 := x ◇ y = (z ◇ (w ◇ (x ◇ w))) ◇ x
equation 50174 := x ◇ y = (z ◇ (w ◇ (x ◇ w))) ◇ y
equation 50175 := x ◇ y = (z ◇ (w ◇ (x ◇ w))) ◇ z
equation 50176 := x ◇ y = (z ◇ (w ◇ (x ◇ w))) ◇ w
equation 50177 := x ◇ y = (z ◇ (w ◇ (x ◇ w))) ◇ u
equation 50178 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ x
equation 50179 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ y
equation 50180 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ z
equation 50181 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ w
equation 50182 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ u
equation 50183 := x ◇ y = (z ◇ (w ◇ (x ◇ u))) ◇ v
equation 50184 := x ◇ y = (z ◇ (w ◇ (y ◇ x))) ◇ x
equation 50185 := x ◇ y = (z ◇ (w ◇ (y ◇ x))) ◇ y
equation 50186 := x ◇ y = (z ◇ (w ◇ (y ◇ x))) ◇ z
equation 50187 := x ◇ y = (z ◇ (w ◇ (y ◇ x))) ◇ w
equation 50188 := x ◇ y = (z ◇ (w ◇ (y ◇ x))) ◇ u
equation 50189 := x ◇ y = (z ◇ (w ◇ (y ◇ y))) ◇ x
equation 50190 := x ◇ y = (z ◇ (w ◇ (y ◇ y))) ◇ y
equation 50191 := x ◇ y = (z ◇ (w ◇ (y ◇ y))) ◇ z
equation 50192 := x ◇ y = (z ◇ (w ◇ (y ◇ y))) ◇ w
equation 50193 := x ◇ y = (z ◇ (w ◇ (y ◇ y))) ◇ u
equation 50194 := x ◇ y = (z ◇ (w ◇ (y ◇ z))) ◇ x
equation 50195 := x ◇ y = (z ◇ (w ◇ (y ◇ z))) ◇ y
equation 50196 := x ◇ y = (z ◇ (w ◇ (y ◇ z))) ◇ z
equation 50197 := x ◇ y = (z ◇ (w ◇ (y ◇ z))) ◇ w
equation 50198 := x ◇ y = (z ◇ (w ◇ (y ◇ z))) ◇ u
equation 50199 := x ◇ y = (z ◇ (w ◇ (y ◇ w))) ◇ x
equation 50200 := x ◇ y = (z ◇ (w ◇ (y ◇ w))) ◇ y
equation 50201 := x ◇ y = (z ◇ (w ◇ (y ◇ w))) ◇ z
equation 50202 := x ◇ y = (z ◇ (w ◇ (y ◇ w))) ◇ w
equation 50203 := x ◇ y = (z ◇ (w ◇ (y ◇ w))) ◇ u
equation 50204 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ x
equation 50205 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ y
equation 50206 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ z
equation 50207 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ w
equation 50208 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ u
equation 50209 := x ◇ y = (z ◇ (w ◇ (y ◇ u))) ◇ v
equation 50210 := x ◇ y = (z ◇ (w ◇ (z ◇ x))) ◇ x
equation 50211 := x ◇ y = (z ◇ (w ◇ (z ◇ x))) ◇ y
equation 50212 := x ◇ y = (z ◇ (w ◇ (z ◇ x))) ◇ z
equation 50213 := x ◇ y = (z ◇ (w ◇ (z ◇ x))) ◇ w
equation 50214 := x ◇ y = (z ◇ (w ◇ (z ◇ x))) ◇ u
equation 50215 := x ◇ y = (z ◇ (w ◇ (z ◇ y))) ◇ x
equation 50216 := x ◇ y = (z ◇ (w ◇ (z ◇ y))) ◇ y
equation 50217 := x ◇ y = (z ◇ (w ◇ (z ◇ y))) ◇ z
equation 50218 := x ◇ y = (z ◇ (w ◇ (z ◇ y))) ◇ w
equation 50219 := x ◇ y = (z ◇ (w ◇ (z ◇ y))) ◇ u
equation 50220 := x ◇ y = (z ◇ (w ◇ (z ◇ z))) ◇ x
equation 50221 := x ◇ y = (z ◇ (w ◇ (z ◇ z))) ◇ y
equation 50222 := x ◇ y = (z ◇ (w ◇ (z ◇ z))) ◇ z
equation 50223 := x ◇ y = (z ◇ (w ◇ (z ◇ z))) ◇ w
equation 50224 := x ◇ y = (z ◇ (w ◇ (z ◇ z))) ◇ u
equation 50225 := x ◇ y = (z ◇ (w ◇ (z ◇ w))) ◇ x
equation 50226 := x ◇ y = (z ◇ (w ◇ (z ◇ w))) ◇ y
equation 50227 := x ◇ y = (z ◇ (w ◇ (z ◇ w))) ◇ z
equation 50228 := x ◇ y = (z ◇ (w ◇ (z ◇ w))) ◇ w
equation 50229 := x ◇ y = (z ◇ (w ◇ (z ◇ w))) ◇ u
equation 50230 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ x
equation 50231 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ y
equation 50232 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ z
equation 50233 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ w
equation 50234 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ u
equation 50235 := x ◇ y = (z ◇ (w ◇ (z ◇ u))) ◇ v
equation 50236 := x ◇ y = (z ◇ (w ◇ (w ◇ x))) ◇ x
equation 50237 := x ◇ y = (z ◇ (w ◇ (w ◇ x))) ◇ y
equation 50238 := x ◇ y = (z ◇ (w ◇ (w ◇ x))) ◇ z
equation 50239 := x ◇ y = (z ◇ (w ◇ (w ◇ x))) ◇ w
equation 50240 := x ◇ y = (z ◇ (w ◇ (w ◇ x))) ◇ u
equation 50241 := x ◇ y = (z ◇ (w ◇ (w ◇ y))) ◇ x
equation 50242 := x ◇ y = (z ◇ (w ◇ (w ◇ y))) ◇ y
equation 50243 := x ◇ y = (z ◇ (w ◇ (w ◇ y))) ◇ z
equation 50244 := x ◇ y = (z ◇ (w ◇ (w ◇ y))) ◇ w
equation 50245 := x ◇ y = (z ◇ (w ◇ (w ◇ y))) ◇ u
equation 50246 := x ◇ y = (z ◇ (w ◇ (w ◇ z))) ◇ x
equation 50247 := x ◇ y = (z ◇ (w ◇ (w ◇ z))) ◇ y
equation 50248 := x ◇ y = (z ◇ (w ◇ (w ◇ z))) ◇ z
equation 50249 := x ◇ y = (z ◇ (w ◇ (w ◇ z))) ◇ w
equation 50250 := x ◇ y = (z ◇ (w ◇ (w ◇ z))) ◇ u
equation 50251 := x ◇ y = (z ◇ (w ◇ (w ◇ w))) ◇ x
equation 50252 := x ◇ y = (z ◇ (w ◇ (w ◇ w))) ◇ y
equation 50253 := x ◇ y = (z ◇ (w ◇ (w ◇ w))) ◇ z
equation 50254 := x ◇ y = (z ◇ (w ◇ (w ◇ w))) ◇ w
equation 50255 := x ◇ y = (z ◇ (w ◇ (w ◇ w))) ◇ u
equation 50256 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ x
equation 50257 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ y
equation 50258 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ z
equation 50259 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ w
equation 50260 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ u
equation 50261 := x ◇ y = (z ◇ (w ◇ (w ◇ u))) ◇ v
equation 50262 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ x
equation 50263 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ y
equation 50264 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ z
equation 50265 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ w
equation 50266 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ u
equation 50267 := x ◇ y = (z ◇ (w ◇ (u ◇ x))) ◇ v
equation 50268 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ x
equation 50269 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ y
equation 50270 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ z
equation 50271 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ w
equation 50272 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ u
equation 50273 := x ◇ y = (z ◇ (w ◇ (u ◇ y))) ◇ v
equation 50274 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ x
equation 50275 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ y
equation 50276 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ z
equation 50277 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ w
equation 50278 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ u
equation 50279 := x ◇ y = (z ◇ (w ◇ (u ◇ z))) ◇ v
equation 50280 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ x
equation 50281 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ y
equation 50282 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ z
equation 50283 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ w
equation 50284 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ u
equation 50285 := x ◇ y = (z ◇ (w ◇ (u ◇ w))) ◇ v
equation 50286 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ x
equation 50287 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ y
equation 50288 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ z
equation 50289 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ w
equation 50290 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ u
equation 50291 := x ◇ y = (z ◇ (w ◇ (u ◇ u))) ◇ v
equation 50292 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ x
equation 50293 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ y
equation 50294 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ z
equation 50295 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ w
equation 50296 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ u
equation 50297 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ v
equation 50298 := x ◇ y = (z ◇ (w ◇ (u ◇ v))) ◇ r
equation 50299 := x ◇ x = (x ◇ ((x ◇ x) ◇ x)) ◇ x
equation 50300 := x ◇ x = (x ◇ ((x ◇ x) ◇ x)) ◇ y
equation 50301 := x ◇ x = (x ◇ ((x ◇ x) ◇ y)) ◇ x
equation 50302 := x ◇ x = (x ◇ ((x ◇ x) ◇ y)) ◇ y
equation 50303 := x ◇ x = (x ◇ ((x ◇ x) ◇ y)) ◇ z
equation 50304 := x ◇ x = (x ◇ ((x ◇ y) ◇ x)) ◇ x
equation 50305 := x ◇ x = (x ◇ ((x ◇ y) ◇ x)) ◇ y
equation 50306 := x ◇ x = (x ◇ ((x ◇ y) ◇ x)) ◇ z
equation 50307 := x ◇ x = (x ◇ ((x ◇ y) ◇ y)) ◇ x
equation 50308 := x ◇ x = (x ◇ ((x ◇ y) ◇ y)) ◇ y
equation 50309 := x ◇ x = (x ◇ ((x ◇ y) ◇ y)) ◇ z
equation 50310 := x ◇ x = (x ◇ ((x ◇ y) ◇ z)) ◇ x
equation 50311 := x ◇ x = (x ◇ ((x ◇ y) ◇ z)) ◇ y
equation 50312 := x ◇ x = (x ◇ ((x ◇ y) ◇ z)) ◇ z
equation 50313 := x ◇ x = (x ◇ ((x ◇ y) ◇ z)) ◇ w
equation 50314 := x ◇ x = (x ◇ ((y ◇ x) ◇ x)) ◇ x
equation 50315 := x ◇ x = (x ◇ ((y ◇ x) ◇ x)) ◇ y
equation 50316 := x ◇ x = (x ◇ ((y ◇ x) ◇ x)) ◇ z
equation 50317 := x ◇ x = (x ◇ ((y ◇ x) ◇ y)) ◇ x
equation 50318 := x ◇ x = (x ◇ ((y ◇ x) ◇ y)) ◇ y
equation 50319 := x ◇ x = (x ◇ ((y ◇ x) ◇ y)) ◇ z
equation 50320 := x ◇ x = (x ◇ ((y ◇ x) ◇ z)) ◇ x
equation 50321 := x ◇ x = (x ◇ ((y ◇ x) ◇ z)) ◇ y
equation 50322 := x ◇ x = (x ◇ ((y ◇ x) ◇ z)) ◇ z
equation 50323 := x ◇ x = (x ◇ ((y ◇ x) ◇ z)) ◇ w
equation 50324 := x ◇ x = (x ◇ ((y ◇ y) ◇ x)) ◇ x
equation 50325 := x ◇ x = (x ◇ ((y ◇ y) ◇ x)) ◇ y
equation 50326 := x ◇ x = (x ◇ ((y ◇ y) ◇ x)) ◇ z
equation 50327 := x ◇ x = (x ◇ ((y ◇ y) ◇ y)) ◇ x
equation 50328 := x ◇ x = (x ◇ ((y ◇ y) ◇ y)) ◇ y
equation 50329 := x ◇ x = (x ◇ ((y ◇ y) ◇ y)) ◇ z
equation 50330 := x ◇ x = (x ◇ ((y ◇ y) ◇ z)) ◇ x
equation 50331 := x ◇ x = (x ◇ ((y ◇ y) ◇ z)) ◇ y
equation 50332 := x ◇ x = (x ◇ ((y ◇ y) ◇ z)) ◇ z
equation 50333 := x ◇ x = (x ◇ ((y ◇ y) ◇ z)) ◇ w
equation 50334 := x ◇ x = (x ◇ ((y ◇ z) ◇ x)) ◇ x
equation 50335 := x ◇ x = (x ◇ ((y ◇ z) ◇ x)) ◇ y
equation 50336 := x ◇ x = (x ◇ ((y ◇ z) ◇ x)) ◇ z
equation 50337 := x ◇ x = (x ◇ ((y ◇ z) ◇ x)) ◇ w
equation 50338 := x ◇ x = (x ◇ ((y ◇ z) ◇ y)) ◇ x
equation 50339 := x ◇ x = (x ◇ ((y ◇ z) ◇ y)) ◇ y
equation 50340 := x ◇ x = (x ◇ ((y ◇ z) ◇ y)) ◇ z
equation 50341 := x ◇ x = (x ◇ ((y ◇ z) ◇ y)) ◇ w
equation 50342 := x ◇ x = (x ◇ ((y ◇ z) ◇ z)) ◇ x
equation 50343 := x ◇ x = (x ◇ ((y ◇ z) ◇ z)) ◇ y
equation 50344 := x ◇ x = (x ◇ ((y ◇ z) ◇ z)) ◇ z
equation 50345 := x ◇ x = (x ◇ ((y ◇ z) ◇ z)) ◇ w
equation 50346 := x ◇ x = (x ◇ ((y ◇ z) ◇ w)) ◇ x
equation 50347 := x ◇ x = (x ◇ ((y ◇ z) ◇ w)) ◇ y
equation 50348 := x ◇ x = (x ◇ ((y ◇ z) ◇ w)) ◇ z
equation 50349 := x ◇ x = (x ◇ ((y ◇ z) ◇ w)) ◇ w
equation 50350 := x ◇ x = (x ◇ ((y ◇ z) ◇ w)) ◇ u
equation 50351 := x ◇ x = (y ◇ ((x ◇ x) ◇ x)) ◇ x
equation 50352 := x ◇ x = (y ◇ ((x ◇ x) ◇ x)) ◇ y
equation 50353 := x ◇ x = (y ◇ ((x ◇ x) ◇ x)) ◇ z
equation 50354 := x ◇ x = (y ◇ ((x ◇ x) ◇ y)) ◇ x
equation 50355 := x ◇ x = (y ◇ ((x ◇ x) ◇ y)) ◇ y
equation 50356 := x ◇ x = (y ◇ ((x ◇ x) ◇ y)) ◇ z
equation 50357 := x ◇ x = (y ◇ ((x ◇ x) ◇ z)) ◇ x
equation 50358 := x ◇ x = (y ◇ ((x ◇ x) ◇ z)) ◇ y
equation 50359 := x ◇ x = (y ◇ ((x ◇ x) ◇ z)) ◇ z
equation 50360 := x ◇ x = (y ◇ ((x ◇ x) ◇ z)) ◇ w
equation 50361 := x ◇ x = (y ◇ ((x ◇ y) ◇ x)) ◇ x
equation 50362 := x ◇ x = (y ◇ ((x ◇ y) ◇ x)) ◇ y
equation 50363 := x ◇ x = (y ◇ ((x ◇ y) ◇ x)) ◇ z
equation 50364 := x ◇ x = (y ◇ ((x ◇ y) ◇ y)) ◇ x
equation 50365 := x ◇ x = (y ◇ ((x ◇ y) ◇ y)) ◇ y
equation 50366 := x ◇ x = (y ◇ ((x ◇ y) ◇ y)) ◇ z
equation 50367 := x ◇ x = (y ◇ ((x ◇ y) ◇ z)) ◇ x
equation 50368 := x ◇ x = (y ◇ ((x ◇ y) ◇ z)) ◇ y
equation 50369 := x ◇ x = (y ◇ ((x ◇ y) ◇ z)) ◇ z
equation 50370 := x ◇ x = (y ◇ ((x ◇ y) ◇ z)) ◇ w
equation 50371 := x ◇ x = (y ◇ ((x ◇ z) ◇ x)) ◇ x
equation 50372 := x ◇ x = (y ◇ ((x ◇ z) ◇ x)) ◇ y
equation 50373 := x ◇ x = (y ◇ ((x ◇ z) ◇ x)) ◇ z
equation 50374 := x ◇ x = (y ◇ ((x ◇ z) ◇ x)) ◇ w
equation 50375 := x ◇ x = (y ◇ ((x ◇ z) ◇ y)) ◇ x
equation 50376 := x ◇ x = (y ◇ ((x ◇ z) ◇ y)) ◇ y
equation 50377 := x ◇ x = (y ◇ ((x ◇ z) ◇ y)) ◇ z
equation 50378 := x ◇ x = (y ◇ ((x ◇ z) ◇ y)) ◇ w
equation 50379 := x ◇ x = (y ◇ ((x ◇ z) ◇ z)) ◇ x
equation 50380 := x ◇ x = (y ◇ ((x ◇ z) ◇ z)) ◇ y
equation 50381 := x ◇ x = (y ◇ ((x ◇ z) ◇ z)) ◇ z
equation 50382 := x ◇ x = (y ◇ ((x ◇ z) ◇ z)) ◇ w
equation 50383 := x ◇ x = (y ◇ ((x ◇ z) ◇ w)) ◇ x
equation 50384 := x ◇ x = (y ◇ ((x ◇ z) ◇ w)) ◇ y
equation 50385 := x ◇ x = (y ◇ ((x ◇ z) ◇ w)) ◇ z
equation 50386 := x ◇ x = (y ◇ ((x ◇ z) ◇ w)) ◇ w
equation 50387 := x ◇ x = (y ◇ ((x ◇ z) ◇ w)) ◇ u
equation 50388 := x ◇ x = (y ◇ ((y ◇ x) ◇ x)) ◇ x
equation 50389 := x ◇ x = (y ◇ ((y ◇ x) ◇ x)) ◇ y
equation 50390 := x ◇ x = (y ◇ ((y ◇ x) ◇ x)) ◇ z
equation 50391 := x ◇ x = (y ◇ ((y ◇ x) ◇ y)) ◇ x
equation 50392 := x ◇ x = (y ◇ ((y ◇ x) ◇ y)) ◇ y
equation 50393 := x ◇ x = (y ◇ ((y ◇ x) ◇ y)) ◇ z
equation 50394 := x ◇ x = (y ◇ ((y ◇ x) ◇ z)) ◇ x
equation 50395 := x ◇ x = (y ◇ ((y ◇ x) ◇ z)) ◇ y
equation 50396 := x ◇ x = (y ◇ ((y ◇ x) ◇ z)) ◇ z
equation 50397 := x ◇ x = (y ◇ ((y ◇ x) ◇ z)) ◇ w
equation 50398 := x ◇ x = (y ◇ ((y ◇ y) ◇ x)) ◇ x
equation 50399 := x ◇ x = (y ◇ ((y ◇ y) ◇ x)) ◇ y
equation 50400 := x ◇ x = (y ◇ ((y ◇ y) ◇ x)) ◇ z
equation 50401 := x ◇ x = (y ◇ ((y ◇ y) ◇ y)) ◇ x
equation 50402 := x ◇ x = (y ◇ ((y ◇ y) ◇ y)) ◇ y
equation 50403 := x ◇ x = (y ◇ ((y ◇ y) ◇ y)) ◇ z
equation 50404 := x ◇ x = (y ◇ ((y ◇ y) ◇ z)) ◇ x
equation 50405 := x ◇ x = (y ◇ ((y ◇ y) ◇ z)) ◇ y
equation 50406 := x ◇ x = (y ◇ ((y ◇ y) ◇ z)) ◇ z
equation 50407 := x ◇ x = (y ◇ ((y ◇ y) ◇ z)) ◇ w
equation 50408 := x ◇ x = (y ◇ ((y ◇ z) ◇ x)) ◇ x
equation 50409 := x ◇ x = (y ◇ ((y ◇ z) ◇ x)) ◇ y
equation 50410 := x ◇ x = (y ◇ ((y ◇ z) ◇ x)) ◇ z
equation 50411 := x ◇ x = (y ◇ ((y ◇ z) ◇ x)) ◇ w
equation 50412 := x ◇ x = (y ◇ ((y ◇ z) ◇ y)) ◇ x
equation 50413 := x ◇ x = (y ◇ ((y ◇ z) ◇ y)) ◇ y
equation 50414 := x ◇ x = (y ◇ ((y ◇ z) ◇ y)) ◇ z
equation 50415 := x ◇ x = (y ◇ ((y ◇ z) ◇ y)) ◇ w
equation 50416 := x ◇ x = (y ◇ ((y ◇ z) ◇ z)) ◇ x
equation 50417 := x ◇ x = (y ◇ ((y ◇ z) ◇ z)) ◇ y
equation 50418 := x ◇ x = (y ◇ ((y ◇ z) ◇ z)) ◇ z
equation 50419 := x ◇ x = (y ◇ ((y ◇ z) ◇ z)) ◇ w
equation 50420 := x ◇ x = (y ◇ ((y ◇ z) ◇ w)) ◇ x
equation 50421 := x ◇ x = (y ◇ ((y ◇ z) ◇ w)) ◇ y
equation 50422 := x ◇ x = (y ◇ ((y ◇ z) ◇ w)) ◇ z
equation 50423 := x ◇ x = (y ◇ ((y ◇ z) ◇ w)) ◇ w
equation 50424 := x ◇ x = (y ◇ ((y ◇ z) ◇ w)) ◇ u
equation 50425 := x ◇ x = (y ◇ ((z ◇ x) ◇ x)) ◇ x
equation 50426 := x ◇ x = (y ◇ ((z ◇ x) ◇ x)) ◇ y
equation 50427 := x ◇ x = (y ◇ ((z ◇ x) ◇ x)) ◇ z
equation 50428 := x ◇ x = (y ◇ ((z ◇ x) ◇ x)) ◇ w
equation 50429 := x ◇ x = (y ◇ ((z ◇ x) ◇ y)) ◇ x
equation 50430 := x ◇ x = (y ◇ ((z ◇ x) ◇ y)) ◇ y
equation 50431 := x ◇ x = (y ◇ ((z ◇ x) ◇ y)) ◇ z
equation 50432 := x ◇ x = (y ◇ ((z ◇ x) ◇ y)) ◇ w
equation 50433 := x ◇ x = (y ◇ ((z ◇ x) ◇ z)) ◇ x
equation 50434 := x ◇ x = (y ◇ ((z ◇ x) ◇ z)) ◇ y
equation 50435 := x ◇ x = (y ◇ ((z ◇ x) ◇ z)) ◇ z
equation 50436 := x ◇ x = (y ◇ ((z ◇ x) ◇ z)) ◇ w
equation 50437 := x ◇ x = (y ◇ ((z ◇ x) ◇ w)) ◇ x
equation 50438 := x ◇ x = (y ◇ ((z ◇ x) ◇ w)) ◇ y
equation 50439 := x ◇ x = (y ◇ ((z ◇ x) ◇ w)) ◇ z
equation 50440 := x ◇ x = (y ◇ ((z ◇ x) ◇ w)) ◇ w
equation 50441 := x ◇ x = (y ◇ ((z ◇ x) ◇ w)) ◇ u
equation 50442 := x ◇ x = (y ◇ ((z ◇ y) ◇ x)) ◇ x
equation 50443 := x ◇ x = (y ◇ ((z ◇ y) ◇ x)) ◇ y
equation 50444 := x ◇ x = (y ◇ ((z ◇ y) ◇ x)) ◇ z
equation 50445 := x ◇ x = (y ◇ ((z ◇ y) ◇ x)) ◇ w
equation 50446 := x ◇ x = (y ◇ ((z ◇ y) ◇ y)) ◇ x
equation 50447 := x ◇ x = (y ◇ ((z ◇ y) ◇ y)) ◇ y
equation 50448 := x ◇ x = (y ◇ ((z ◇ y) ◇ y)) ◇ z
equation 50449 := x ◇ x = (y ◇ ((z ◇ y) ◇ y)) ◇ w
equation 50450 := x ◇ x = (y ◇ ((z ◇ y) ◇ z)) ◇ x
equation 50451 := x ◇ x = (y ◇ ((z ◇ y) ◇ z)) ◇ y
equation 50452 := x ◇ x = (y ◇ ((z ◇ y) ◇ z)) ◇ z
equation 50453 := x ◇ x = (y ◇ ((z ◇ y) ◇ z)) ◇ w
equation 50454 := x ◇ x = (y ◇ ((z ◇ y) ◇ w)) ◇ x
equation 50455 := x ◇ x = (y ◇ ((z ◇ y) ◇ w)) ◇ y
equation 50456 := x ◇ x = (y ◇ ((z ◇ y) ◇ w)) ◇ z
equation 50457 := x ◇ x = (y ◇ ((z ◇ y) ◇ w)) ◇ w
equation 50458 := x ◇ x = (y ◇ ((z ◇ y) ◇ w)) ◇ u
equation 50459 := x ◇ x = (y ◇ ((z ◇ z) ◇ x)) ◇ x
equation 50460 := x ◇ x = (y ◇ ((z ◇ z) ◇ x)) ◇ y
equation 50461 := x ◇ x = (y ◇ ((z ◇ z) ◇ x)) ◇ z
equation 50462 := x ◇ x = (y ◇ ((z ◇ z) ◇ x)) ◇ w
equation 50463 := x ◇ x = (y ◇ ((z ◇ z) ◇ y)) ◇ x
equation 50464 := x ◇ x = (y ◇ ((z ◇ z) ◇ y)) ◇ y
equation 50465 := x ◇ x = (y ◇ ((z ◇ z) ◇ y)) ◇ z
equation 50466 := x ◇ x = (y ◇ ((z ◇ z) ◇ y)) ◇ w
equation 50467 := x ◇ x = (y ◇ ((z ◇ z) ◇ z)) ◇ x
equation 50468 := x ◇ x = (y ◇ ((z ◇ z) ◇ z)) ◇ y
equation 50469 := x ◇ x = (y ◇ ((z ◇ z) ◇ z)) ◇ z
equation 50470 := x ◇ x = (y ◇ ((z ◇ z) ◇ z)) ◇ w
equation 50471 := x ◇ x = (y ◇ ((z ◇ z) ◇ w)) ◇ x
equation 50472 := x ◇ x = (y ◇ ((z ◇ z) ◇ w)) ◇ y
equation 50473 := x ◇ x = (y ◇ ((z ◇ z) ◇ w)) ◇ z
equation 50474 := x ◇ x = (y ◇ ((z ◇ z) ◇ w)) ◇ w
equation 50475 := x ◇ x = (y ◇ ((z ◇ z) ◇ w)) ◇ u
equation 50476 := x ◇ x = (y ◇ ((z ◇ w) ◇ x)) ◇ x
equation 50477 := x ◇ x = (y ◇ ((z ◇ w) ◇ x)) ◇ y
equation 50478 := x ◇ x = (y ◇ ((z ◇ w) ◇ x)) ◇ z
equation 50479 := x ◇ x = (y ◇ ((z ◇ w) ◇ x)) ◇ w
equation 50480 := x ◇ x = (y ◇ ((z ◇ w) ◇ x)) ◇ u
equation 50481 := x ◇ x = (y ◇ ((z ◇ w) ◇ y)) ◇ x
equation 50482 := x ◇ x = (y ◇ ((z ◇ w) ◇ y)) ◇ y
equation 50483 := x ◇ x = (y ◇ ((z ◇ w) ◇ y)) ◇ z
equation 50484 := x ◇ x = (y ◇ ((z ◇ w) ◇ y)) ◇ w
equation 50485 := x ◇ x = (y ◇ ((z ◇ w) ◇ y)) ◇ u
equation 50486 := x ◇ x = (y ◇ ((z ◇ w) ◇ z)) ◇ x
equation 50487 := x ◇ x = (y ◇ ((z ◇ w) ◇ z)) ◇ y
equation 50488 := x ◇ x = (y ◇ ((z ◇ w) ◇ z)) ◇ z
equation 50489 := x ◇ x = (y ◇ ((z ◇ w) ◇ z)) ◇ w
equation 50490 := x ◇ x = (y ◇ ((z ◇ w) ◇ z)) ◇ u
equation 50491 := x ◇ x = (y ◇ ((z ◇ w) ◇ w)) ◇ x
equation 50492 := x ◇ x = (y ◇ ((z ◇ w) ◇ w)) ◇ y
equation 50493 := x ◇ x = (y ◇ ((z ◇ w) ◇ w)) ◇ z
equation 50494 := x ◇ x = (y ◇ ((z ◇ w) ◇ w)) ◇ w
equation 50495 := x ◇ x = (y ◇ ((z ◇ w) ◇ w)) ◇ u
equation 50496 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ x
equation 50497 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ y
equation 50498 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ z
equation 50499 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ w
equation 50500 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ u
equation 50501 := x ◇ x = (y ◇ ((z ◇ w) ◇ u)) ◇ v
equation 50502 := x ◇ y = (x ◇ ((x ◇ x) ◇ x)) ◇ x
equation 50503 := x ◇ y = (x ◇ ((x ◇ x) ◇ x)) ◇ y
equation 50504 := x ◇ y = (x ◇ ((x ◇ x) ◇ x)) ◇ z
equation 50505 := x ◇ y = (x ◇ ((x ◇ x) ◇ y)) ◇ x
equation 50506 := x ◇ y = (x ◇ ((x ◇ x) ◇ y)) ◇ y
equation 50507 := x ◇ y = (x ◇ ((x ◇ x) ◇ y)) ◇ z
equation 50508 := x ◇ y = (x ◇ ((x ◇ x) ◇ z)) ◇ x
equation 50509 := x ◇ y = (x ◇ ((x ◇ x) ◇ z)) ◇ y
equation 50510 := x ◇ y = (x ◇ ((x ◇ x) ◇ z)) ◇ z
equation 50511 := x ◇ y = (x ◇ ((x ◇ x) ◇ z)) ◇ w
equation 50512 := x ◇ y = (x ◇ ((x ◇ y) ◇ x)) ◇ x
equation 50513 := x ◇ y = (x ◇ ((x ◇ y) ◇ x)) ◇ y
equation 50514 := x ◇ y = (x ◇ ((x ◇ y) ◇ x)) ◇ z
equation 50515 := x ◇ y = (x ◇ ((x ◇ y) ◇ y)) ◇ x
equation 50516 := x ◇ y = (x ◇ ((x ◇ y) ◇ y)) ◇ y
equation 50517 := x ◇ y = (x ◇ ((x ◇ y) ◇ y)) ◇ z
equation 50518 := x ◇ y = (x ◇ ((x ◇ y) ◇ z)) ◇ x
equation 50519 := x ◇ y = (x ◇ ((x ◇ y) ◇ z)) ◇ y
equation 50520 := x ◇ y = (x ◇ ((x ◇ y) ◇ z)) ◇ z
equation 50521 := x ◇ y = (x ◇ ((x ◇ y) ◇ z)) ◇ w
equation 50522 := x ◇ y = (x ◇ ((x ◇ z) ◇ x)) ◇ x
equation 50523 := x ◇ y = (x ◇ ((x ◇ z) ◇ x)) ◇ y
equation 50524 := x ◇ y = (x ◇ ((x ◇ z) ◇ x)) ◇ z
equation 50525 := x ◇ y = (x ◇ ((x ◇ z) ◇ x)) ◇ w
equation 50526 := x ◇ y = (x ◇ ((x ◇ z) ◇ y)) ◇ x
equation 50527 := x ◇ y = (x ◇ ((x ◇ z) ◇ y)) ◇ y
equation 50528 := x ◇ y = (x ◇ ((x ◇ z) ◇ y)) ◇ z
equation 50529 := x ◇ y = (x ◇ ((x ◇ z) ◇ y)) ◇ w
equation 50530 := x ◇ y = (x ◇ ((x ◇ z) ◇ z)) ◇ x
equation 50531 := x ◇ y = (x ◇ ((x ◇ z) ◇ z)) ◇ y
equation 50532 := x ◇ y = (x ◇ ((x ◇ z) ◇ z)) ◇ z
equation 50533 := x ◇ y = (x ◇ ((x ◇ z) ◇ z)) ◇ w
equation 50534 := x ◇ y = (x ◇ ((x ◇ z) ◇ w)) ◇ x
equation 50535 := x ◇ y = (x ◇ ((x ◇ z) ◇ w)) ◇ y
equation 50536 := x ◇ y = (x ◇ ((x ◇ z) ◇ w)) ◇ z
equation 50537 := x ◇ y = (x ◇ ((x ◇ z) ◇ w)) ◇ w
equation 50538 := x ◇ y = (x ◇ ((x ◇ z) ◇ w)) ◇ u
equation 50539 := x ◇ y = (x ◇ ((y ◇ x) ◇ x)) ◇ x
equation 50540 := x ◇ y = (x ◇ ((y ◇ x) ◇ x)) ◇ y
equation 50541 := x ◇ y = (x ◇ ((y ◇ x) ◇ x)) ◇ z
equation 50542 := x ◇ y = (x ◇ ((y ◇ x) ◇ y)) ◇ x
equation 50543 := x ◇ y = (x ◇ ((y ◇ x) ◇ y)) ◇ y
equation 50544 := x ◇ y = (x ◇ ((y ◇ x) ◇ y)) ◇ z
equation 50545 := x ◇ y = (x ◇ ((y ◇ x) ◇ z)) ◇ x
equation 50546 := x ◇ y = (x ◇ ((y ◇ x) ◇ z)) ◇ y
equation 50547 := x ◇ y = (x ◇ ((y ◇ x) ◇ z)) ◇ z
equation 50548 := x ◇ y = (x ◇ ((y ◇ x) ◇ z)) ◇ w
equation 50549 := x ◇ y = (x ◇ ((y ◇ y) ◇ x)) ◇ x
equation 50550 := x ◇ y = (x ◇ ((y ◇ y) ◇ x)) ◇ y
equation 50551 := x ◇ y = (x ◇ ((y ◇ y) ◇ x)) ◇ z
equation 50552 := x ◇ y = (x ◇ ((y ◇ y) ◇ y)) ◇ x
equation 50553 := x ◇ y = (x ◇ ((y ◇ y) ◇ y)) ◇ y
equation 50554 := x ◇ y = (x ◇ ((y ◇ y) ◇ y)) ◇ z
equation 50555 := x ◇ y = (x ◇ ((y ◇ y) ◇ z)) ◇ x
equation 50556 := x ◇ y = (x ◇ ((y ◇ y) ◇ z)) ◇ y
equation 50557 := x ◇ y = (x ◇ ((y ◇ y) ◇ z)) ◇ z
equation 50558 := x ◇ y = (x ◇ ((y ◇ y) ◇ z)) ◇ w
equation 50559 := x ◇ y = (x ◇ ((y ◇ z) ◇ x)) ◇ x
equation 50560 := x ◇ y = (x ◇ ((y ◇ z) ◇ x)) ◇ y
equation 50561 := x ◇ y = (x ◇ ((y ◇ z) ◇ x)) ◇ z
equation 50562 := x ◇ y = (x ◇ ((y ◇ z) ◇ x)) ◇ w
equation 50563 := x ◇ y = (x ◇ ((y ◇ z) ◇ y)) ◇ x
equation 50564 := x ◇ y = (x ◇ ((y ◇ z) ◇ y)) ◇ y
equation 50565 := x ◇ y = (x ◇ ((y ◇ z) ◇ y)) ◇ z
equation 50566 := x ◇ y = (x ◇ ((y ◇ z) ◇ y)) ◇ w
equation 50567 := x ◇ y = (x ◇ ((y ◇ z) ◇ z)) ◇ x
equation 50568 := x ◇ y = (x ◇ ((y ◇ z) ◇ z)) ◇ y
equation 50569 := x ◇ y = (x ◇ ((y ◇ z) ◇ z)) ◇ z
equation 50570 := x ◇ y = (x ◇ ((y ◇ z) ◇ z)) ◇ w
equation 50571 := x ◇ y = (x ◇ ((y ◇ z) ◇ w)) ◇ x
equation 50572 := x ◇ y = (x ◇ ((y ◇ z) ◇ w)) ◇ y
equation 50573 := x ◇ y = (x ◇ ((y ◇ z) ◇ w)) ◇ z
equation 50574 := x ◇ y = (x ◇ ((y ◇ z) ◇ w)) ◇ w
equation 50575 := x ◇ y = (x ◇ ((y ◇ z) ◇ w)) ◇ u
equation 50576 := x ◇ y = (x ◇ ((z ◇ x) ◇ x)) ◇ x
equation 50577 := x ◇ y = (x ◇ ((z ◇ x) ◇ x)) ◇ y
equation 50578 := x ◇ y = (x ◇ ((z ◇ x) ◇ x)) ◇ z
equation 50579 := x ◇ y = (x ◇ ((z ◇ x) ◇ x)) ◇ w
equation 50580 := x ◇ y = (x ◇ ((z ◇ x) ◇ y)) ◇ x
equation 50581 := x ◇ y = (x ◇ ((z ◇ x) ◇ y)) ◇ y
equation 50582 := x ◇ y = (x ◇ ((z ◇ x) ◇ y)) ◇ z
equation 50583 := x ◇ y = (x ◇ ((z ◇ x) ◇ y)) ◇ w
equation 50584 := x ◇ y = (x ◇ ((z ◇ x) ◇ z)) ◇ x
equation 50585 := x ◇ y = (x ◇ ((z ◇ x) ◇ z)) ◇ y
equation 50586 := x ◇ y = (x ◇ ((z ◇ x) ◇ z)) ◇ z
equation 50587 := x ◇ y = (x ◇ ((z ◇ x) ◇ z)) ◇ w
equation 50588 := x ◇ y = (x ◇ ((z ◇ x) ◇ w)) ◇ x
equation 50589 := x ◇ y = (x ◇ ((z ◇ x) ◇ w)) ◇ y
equation 50590 := x ◇ y = (x ◇ ((z ◇ x) ◇ w)) ◇ z
equation 50591 := x ◇ y = (x ◇ ((z ◇ x) ◇ w)) ◇ w
equation 50592 := x ◇ y = (x ◇ ((z ◇ x) ◇ w)) ◇ u
equation 50593 := x ◇ y = (x ◇ ((z ◇ y) ◇ x)) ◇ x
equation 50594 := x ◇ y = (x ◇ ((z ◇ y) ◇ x)) ◇ y
equation 50595 := x ◇ y = (x ◇ ((z ◇ y) ◇ x)) ◇ z
equation 50596 := x ◇ y = (x ◇ ((z ◇ y) ◇ x)) ◇ w
equation 50597 := x ◇ y = (x ◇ ((z ◇ y) ◇ y)) ◇ x
equation 50598 := x ◇ y = (x ◇ ((z ◇ y) ◇ y)) ◇ y
equation 50599 := x ◇ y = (x ◇ ((z ◇ y) ◇ y)) ◇ z
equation 50600 := x ◇ y = (x ◇ ((z ◇ y) ◇ y)) ◇ w
equation 50601 := x ◇ y = (x ◇ ((z ◇ y) ◇ z)) ◇ x
equation 50602 := x ◇ y = (x ◇ ((z ◇ y) ◇ z)) ◇ y
equation 50603 := x ◇ y = (x ◇ ((z ◇ y) ◇ z)) ◇ z
equation 50604 := x ◇ y = (x ◇ ((z ◇ y) ◇ z)) ◇ w
equation 50605 := x ◇ y = (x ◇ ((z ◇ y) ◇ w)) ◇ x
equation 50606 := x ◇ y = (x ◇ ((z ◇ y) ◇ w)) ◇ y
equation 50607 := x ◇ y = (x ◇ ((z ◇ y) ◇ w)) ◇ z
equation 50608 := x ◇ y = (x ◇ ((z ◇ y) ◇ w)) ◇ w
equation 50609 := x ◇ y = (x ◇ ((z ◇ y) ◇ w)) ◇ u
equation 50610 := x ◇ y = (x ◇ ((z ◇ z) ◇ x)) ◇ x
equation 50611 := x ◇ y = (x ◇ ((z ◇ z) ◇ x)) ◇ y
equation 50612 := x ◇ y = (x ◇ ((z ◇ z) ◇ x)) ◇ z
equation 50613 := x ◇ y = (x ◇ ((z ◇ z) ◇ x)) ◇ w
equation 50614 := x ◇ y = (x ◇ ((z ◇ z) ◇ y)) ◇ x
equation 50615 := x ◇ y = (x ◇ ((z ◇ z) ◇ y)) ◇ y
equation 50616 := x ◇ y = (x ◇ ((z ◇ z) ◇ y)) ◇ z
equation 50617 := x ◇ y = (x ◇ ((z ◇ z) ◇ y)) ◇ w
equation 50618 := x ◇ y = (x ◇ ((z ◇ z) ◇ z)) ◇ x
equation 50619 := x ◇ y = (x ◇ ((z ◇ z) ◇ z)) ◇ y
equation 50620 := x ◇ y = (x ◇ ((z ◇ z) ◇ z)) ◇ z
equation 50621 := x ◇ y = (x ◇ ((z ◇ z) ◇ z)) ◇ w
equation 50622 := x ◇ y = (x ◇ ((z ◇ z) ◇ w)) ◇ x
equation 50623 := x ◇ y = (x ◇ ((z ◇ z) ◇ w)) ◇ y
equation 50624 := x ◇ y = (x ◇ ((z ◇ z) ◇ w)) ◇ z
equation 50625 := x ◇ y = (x ◇ ((z ◇ z) ◇ w)) ◇ w
equation 50626 := x ◇ y = (x ◇ ((z ◇ z) ◇ w)) ◇ u
equation 50627 := x ◇ y = (x ◇ ((z ◇ w) ◇ x)) ◇ x
equation 50628 := x ◇ y = (x ◇ ((z ◇ w) ◇ x)) ◇ y
equation 50629 := x ◇ y = (x ◇ ((z ◇ w) ◇ x)) ◇ z
equation 50630 := x ◇ y = (x ◇ ((z ◇ w) ◇ x)) ◇ w
equation 50631 := x ◇ y = (x ◇ ((z ◇ w) ◇ x)) ◇ u
equation 50632 := x ◇ y = (x ◇ ((z ◇ w) ◇ y)) ◇ x
equation 50633 := x ◇ y = (x ◇ ((z ◇ w) ◇ y)) ◇ y
equation 50634 := x ◇ y = (x ◇ ((z ◇ w) ◇ y)) ◇ z
equation 50635 := x ◇ y = (x ◇ ((z ◇ w) ◇ y)) ◇ w
equation 50636 := x ◇ y = (x ◇ ((z ◇ w) ◇ y)) ◇ u
equation 50637 := x ◇ y = (x ◇ ((z ◇ w) ◇ z)) ◇ x
equation 50638 := x ◇ y = (x ◇ ((z ◇ w) ◇ z)) ◇ y
equation 50639 := x ◇ y = (x ◇ ((z ◇ w) ◇ z)) ◇ z
equation 50640 := x ◇ y = (x ◇ ((z ◇ w) ◇ z)) ◇ w
equation 50641 := x ◇ y = (x ◇ ((z ◇ w) ◇ z)) ◇ u
equation 50642 := x ◇ y = (x ◇ ((z ◇ w) ◇ w)) ◇ x
equation 50643 := x ◇ y = (x ◇ ((z ◇ w) ◇ w)) ◇ y
equation 50644 := x ◇ y = (x ◇ ((z ◇ w) ◇ w)) ◇ z
equation 50645 := x ◇ y = (x ◇ ((z ◇ w) ◇ w)) ◇ w
equation 50646 := x ◇ y = (x ◇ ((z ◇ w) ◇ w)) ◇ u
equation 50647 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ x
equation 50648 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ y
equation 50649 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ z
equation 50650 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ w
equation 50651 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ u
equation 50652 := x ◇ y = (x ◇ ((z ◇ w) ◇ u)) ◇ v
equation 50653 := x ◇ y = (y ◇ ((x ◇ x) ◇ x)) ◇ x
equation 50654 := x ◇ y = (y ◇ ((x ◇ x) ◇ x)) ◇ y
equation 50655 := x ◇ y = (y ◇ ((x ◇ x) ◇ x)) ◇ z
equation 50656 := x ◇ y = (y ◇ ((x ◇ x) ◇ y)) ◇ x
equation 50657 := x ◇ y = (y ◇ ((x ◇ x) ◇ y)) ◇ y
equation 50658 := x ◇ y = (y ◇ ((x ◇ x) ◇ y)) ◇ z
equation 50659 := x ◇ y = (y ◇ ((x ◇ x) ◇ z)) ◇ x
equation 50660 := x ◇ y = (y ◇ ((x ◇ x) ◇ z)) ◇ y
equation 50661 := x ◇ y = (y ◇ ((x ◇ x) ◇ z)) ◇ z
equation 50662 := x ◇ y = (y ◇ ((x ◇ x) ◇ z)) ◇ w
equation 50663 := x ◇ y = (y ◇ ((x ◇ y) ◇ x)) ◇ x
equation 50664 := x ◇ y = (y ◇ ((x ◇ y) ◇ x)) ◇ y
equation 50665 := x ◇ y = (y ◇ ((x ◇ y) ◇ x)) ◇ z
equation 50666 := x ◇ y = (y ◇ ((x ◇ y) ◇ y)) ◇ x
equation 50667 := x ◇ y = (y ◇ ((x ◇ y) ◇ y)) ◇ y
equation 50668 := x ◇ y = (y ◇ ((x ◇ y) ◇ y)) ◇ z
equation 50669 := x ◇ y = (y ◇ ((x ◇ y) ◇ z)) ◇ x
equation 50670 := x ◇ y = (y ◇ ((x ◇ y) ◇ z)) ◇ y
equation 50671 := x ◇ y = (y ◇ ((x ◇ y) ◇ z)) ◇ z
equation 50672 := x ◇ y = (y ◇ ((x ◇ y) ◇ z)) ◇ w
equation 50673 := x ◇ y = (y ◇ ((x ◇ z) ◇ x)) ◇ x
equation 50674 := x ◇ y = (y ◇ ((x ◇ z) ◇ x)) ◇ y
equation 50675 := x ◇ y = (y ◇ ((x ◇ z) ◇ x)) ◇ z
equation 50676 := x ◇ y = (y ◇ ((x ◇ z) ◇ x)) ◇ w
equation 50677 := x ◇ y = (y ◇ ((x ◇ z) ◇ y)) ◇ x
equation 50678 := x ◇ y = (y ◇ ((x ◇ z) ◇ y)) ◇ y
equation 50679 := x ◇ y = (y ◇ ((x ◇ z) ◇ y)) ◇ z
equation 50680 := x ◇ y = (y ◇ ((x ◇ z) ◇ y)) ◇ w
equation 50681 := x ◇ y = (y ◇ ((x ◇ z) ◇ z)) ◇ x
equation 50682 := x ◇ y = (y ◇ ((x ◇ z) ◇ z)) ◇ y
equation 50683 := x ◇ y = (y ◇ ((x ◇ z) ◇ z)) ◇ z
equation 50684 := x ◇ y = (y ◇ ((x ◇ z) ◇ z)) ◇ w
equation 50685 := x ◇ y = (y ◇ ((x ◇ z) ◇ w)) ◇ x
equation 50686 := x ◇ y = (y ◇ ((x ◇ z) ◇ w)) ◇ y
equation 50687 := x ◇ y = (y ◇ ((x ◇ z) ◇ w)) ◇ z
equation 50688 := x ◇ y = (y ◇ ((x ◇ z) ◇ w)) ◇ w
equation 50689 := x ◇ y = (y ◇ ((x ◇ z) ◇ w)) ◇ u
equation 50690 := x ◇ y = (y ◇ ((y ◇ x) ◇ x)) ◇ x
equation 50691 := x ◇ y = (y ◇ ((y ◇ x) ◇ x)) ◇ y
equation 50692 := x ◇ y = (y ◇ ((y ◇ x) ◇ x)) ◇ z
equation 50693 := x ◇ y = (y ◇ ((y ◇ x) ◇ y)) ◇ x
equation 50694 := x ◇ y = (y ◇ ((y ◇ x) ◇ y)) ◇ y
equation 50695 := x ◇ y = (y ◇ ((y ◇ x) ◇ y)) ◇ z
equation 50696 := x ◇ y = (y ◇ ((y ◇ x) ◇ z)) ◇ x
equation 50697 := x ◇ y = (y ◇ ((y ◇ x) ◇ z)) ◇ y
equation 50698 := x ◇ y = (y ◇ ((y ◇ x) ◇ z)) ◇ z
equation 50699 := x ◇ y = (y ◇ ((y ◇ x) ◇ z)) ◇ w
equation 50700 := x ◇ y = (y ◇ ((y ◇ y) ◇ x)) ◇ x
equation 50701 := x ◇ y = (y ◇ ((y ◇ y) ◇ x)) ◇ y
equation 50702 := x ◇ y = (y ◇ ((y ◇ y) ◇ x)) ◇ z
equation 50703 := x ◇ y = (y ◇ ((y ◇ y) ◇ y)) ◇ x
equation 50704 := x ◇ y = (y ◇ ((y ◇ y) ◇ y)) ◇ y
equation 50705 := x ◇ y = (y ◇ ((y ◇ y) ◇ y)) ◇ z
equation 50706 := x ◇ y = (y ◇ ((y ◇ y) ◇ z)) ◇ x
equation 50707 := x ◇ y = (y ◇ ((y ◇ y) ◇ z)) ◇ y
equation 50708 := x ◇ y = (y ◇ ((y ◇ y) ◇ z)) ◇ z
equation 50709 := x ◇ y = (y ◇ ((y ◇ y) ◇ z)) ◇ w
equation 50710 := x ◇ y = (y ◇ ((y ◇ z) ◇ x)) ◇ x
equation 50711 := x ◇ y = (y ◇ ((y ◇ z) ◇ x)) ◇ y
equation 50712 := x ◇ y = (y ◇ ((y ◇ z) ◇ x)) ◇ z
equation 50713 := x ◇ y = (y ◇ ((y ◇ z) ◇ x)) ◇ w
equation 50714 := x ◇ y = (y ◇ ((y ◇ z) ◇ y)) ◇ x
equation 50715 := x ◇ y = (y ◇ ((y ◇ z) ◇ y)) ◇ y
equation 50716 := x ◇ y = (y ◇ ((y ◇ z) ◇ y)) ◇ z
equation 50717 := x ◇ y = (y ◇ ((y ◇ z) ◇ y)) ◇ w
equation 50718 := x ◇ y = (y ◇ ((y ◇ z) ◇ z)) ◇ x
equation 50719 := x ◇ y = (y ◇ ((y ◇ z) ◇ z)) ◇ y
equation 50720 := x ◇ y = (y ◇ ((y ◇ z) ◇ z)) ◇ z
equation 50721 := x ◇ y = (y ◇ ((y ◇ z) ◇ z)) ◇ w
equation 50722 := x ◇ y = (y ◇ ((y ◇ z) ◇ w)) ◇ x
equation 50723 := x ◇ y = (y ◇ ((y ◇ z) ◇ w)) ◇ y
equation 50724 := x ◇ y = (y ◇ ((y ◇ z) ◇ w)) ◇ z
equation 50725 := x ◇ y = (y ◇ ((y ◇ z) ◇ w)) ◇ w
equation 50726 := x ◇ y = (y ◇ ((y ◇ z) ◇ w)) ◇ u
equation 50727 := x ◇ y = (y ◇ ((z ◇ x) ◇ x)) ◇ x
equation 50728 := x ◇ y = (y ◇ ((z ◇ x) ◇ x)) ◇ y
equation 50729 := x ◇ y = (y ◇ ((z ◇ x) ◇ x)) ◇ z
equation 50730 := x ◇ y = (y ◇ ((z ◇ x) ◇ x)) ◇ w
equation 50731 := x ◇ y = (y ◇ ((z ◇ x) ◇ y)) ◇ x
equation 50732 := x ◇ y = (y ◇ ((z ◇ x) ◇ y)) ◇ y
equation 50733 := x ◇ y = (y ◇ ((z ◇ x) ◇ y)) ◇ z
equation 50734 := x ◇ y = (y ◇ ((z ◇ x) ◇ y)) ◇ w
equation 50735 := x ◇ y = (y ◇ ((z ◇ x) ◇ z)) ◇ x
equation 50736 := x ◇ y = (y ◇ ((z ◇ x) ◇ z)) ◇ y
equation 50737 := x ◇ y = (y ◇ ((z ◇ x) ◇ z)) ◇ z
equation 50738 := x ◇ y = (y ◇ ((z ◇ x) ◇ z)) ◇ w
equation 50739 := x ◇ y = (y ◇ ((z ◇ x) ◇ w)) ◇ x
equation 50740 := x ◇ y = (y ◇ ((z ◇ x) ◇ w)) ◇ y
equation 50741 := x ◇ y = (y ◇ ((z ◇ x) ◇ w)) ◇ z
equation 50742 := x ◇ y = (y ◇ ((z ◇ x) ◇ w)) ◇ w
equation 50743 := x ◇ y = (y ◇ ((z ◇ x) ◇ w)) ◇ u
equation 50744 := x ◇ y = (y ◇ ((z ◇ y) ◇ x)) ◇ x
equation 50745 := x ◇ y = (y ◇ ((z ◇ y) ◇ x)) ◇ y
equation 50746 := x ◇ y = (y ◇ ((z ◇ y) ◇ x)) ◇ z
equation 50747 := x ◇ y = (y ◇ ((z ◇ y) ◇ x)) ◇ w
equation 50748 := x ◇ y = (y ◇ ((z ◇ y) ◇ y)) ◇ x
equation 50749 := x ◇ y = (y ◇ ((z ◇ y) ◇ y)) ◇ y
equation 50750 := x ◇ y = (y ◇ ((z ◇ y) ◇ y)) ◇ z
equation 50751 := x ◇ y = (y ◇ ((z ◇ y) ◇ y)) ◇ w
equation 50752 := x ◇ y = (y ◇ ((z ◇ y) ◇ z)) ◇ x
equation 50753 := x ◇ y = (y ◇ ((z ◇ y) ◇ z)) ◇ y
equation 50754 := x ◇ y = (y ◇ ((z ◇ y) ◇ z)) ◇ z
equation 50755 := x ◇ y = (y ◇ ((z ◇ y) ◇ z)) ◇ w
equation 50756 := x ◇ y = (y ◇ ((z ◇ y) ◇ w)) ◇ x
equation 50757 := x ◇ y = (y ◇ ((z ◇ y) ◇ w)) ◇ y
equation 50758 := x ◇ y = (y ◇ ((z ◇ y) ◇ w)) ◇ z
equation 50759 := x ◇ y = (y ◇ ((z ◇ y) ◇ w)) ◇ w
equation 50760 := x ◇ y = (y ◇ ((z ◇ y) ◇ w)) ◇ u
equation 50761 := x ◇ y = (y ◇ ((z ◇ z) ◇ x)) ◇ x
equation 50762 := x ◇ y = (y ◇ ((z ◇ z) ◇ x)) ◇ y
equation 50763 := x ◇ y = (y ◇ ((z ◇ z) ◇ x)) ◇ z
equation 50764 := x ◇ y = (y ◇ ((z ◇ z) ◇ x)) ◇ w
equation 50765 := x ◇ y = (y ◇ ((z ◇ z) ◇ y)) ◇ x
equation 50766 := x ◇ y = (y ◇ ((z ◇ z) ◇ y)) ◇ y
equation 50767 := x ◇ y = (y ◇ ((z ◇ z) ◇ y)) ◇ z
equation 50768 := x ◇ y = (y ◇ ((z ◇ z) ◇ y)) ◇ w
equation 50769 := x ◇ y = (y ◇ ((z ◇ z) ◇ z)) ◇ x
equation 50770 := x ◇ y = (y ◇ ((z ◇ z) ◇ z)) ◇ y
equation 50771 := x ◇ y = (y ◇ ((z ◇ z) ◇ z)) ◇ z
equation 50772 := x ◇ y = (y ◇ ((z ◇ z) ◇ z)) ◇ w
equation 50773 := x ◇ y = (y ◇ ((z ◇ z) ◇ w)) ◇ x
equation 50774 := x ◇ y = (y ◇ ((z ◇ z) ◇ w)) ◇ y
equation 50775 := x ◇ y = (y ◇ ((z ◇ z) ◇ w)) ◇ z
equation 50776 := x ◇ y = (y ◇ ((z ◇ z) ◇ w)) ◇ w
equation 50777 := x ◇ y = (y ◇ ((z ◇ z) ◇ w)) ◇ u
equation 50778 := x ◇ y = (y ◇ ((z ◇ w) ◇ x)) ◇ x
equation 50779 := x ◇ y = (y ◇ ((z ◇ w) ◇ x)) ◇ y
equation 50780 := x ◇ y = (y ◇ ((z ◇ w) ◇ x)) ◇ z
equation 50781 := x ◇ y = (y ◇ ((z ◇ w) ◇ x)) ◇ w
equation 50782 := x ◇ y = (y ◇ ((z ◇ w) ◇ x)) ◇ u
equation 50783 := x ◇ y = (y ◇ ((z ◇ w) ◇ y)) ◇ x
equation 50784 := x ◇ y = (y ◇ ((z ◇ w) ◇ y)) ◇ y
equation 50785 := x ◇ y = (y ◇ ((z ◇ w) ◇ y)) ◇ z
equation 50786 := x ◇ y = (y ◇ ((z ◇ w) ◇ y)) ◇ w
equation 50787 := x ◇ y = (y ◇ ((z ◇ w) ◇ y)) ◇ u
equation 50788 := x ◇ y = (y ◇ ((z ◇ w) ◇ z)) ◇ x
equation 50789 := x ◇ y = (y ◇ ((z ◇ w) ◇ z)) ◇ y
equation 50790 := x ◇ y = (y ◇ ((z ◇ w) ◇ z)) ◇ z
equation 50791 := x ◇ y = (y ◇ ((z ◇ w) ◇ z)) ◇ w
equation 50792 := x ◇ y = (y ◇ ((z ◇ w) ◇ z)) ◇ u
equation 50793 := x ◇ y = (y ◇ ((z ◇ w) ◇ w)) ◇ x
equation 50794 := x ◇ y = (y ◇ ((z ◇ w) ◇ w)) ◇ y
equation 50795 := x ◇ y = (y ◇ ((z ◇ w) ◇ w)) ◇ z
equation 50796 := x ◇ y = (y ◇ ((z ◇ w) ◇ w)) ◇ w
equation 50797 := x ◇ y = (y ◇ ((z ◇ w) ◇ w)) ◇ u
equation 50798 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ x
equation 50799 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ y
equation 50800 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ z
equation 50801 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ w
equation 50802 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ u
equation 50803 := x ◇ y = (y ◇ ((z ◇ w) ◇ u)) ◇ v
equation 50804 := x ◇ y = (z ◇ ((x ◇ x) ◇ x)) ◇ x
equation 50805 := x ◇ y = (z ◇ ((x ◇ x) ◇ x)) ◇ y
equation 50806 := x ◇ y = (z ◇ ((x ◇ x) ◇ x)) ◇ z
equation 50807 := x ◇ y = (z ◇ ((x ◇ x) ◇ x)) ◇ w
equation 50808 := x ◇ y = (z ◇ ((x ◇ x) ◇ y)) ◇ x
equation 50809 := x ◇ y = (z ◇ ((x ◇ x) ◇ y)) ◇ y
equation 50810 := x ◇ y = (z ◇ ((x ◇ x) ◇ y)) ◇ z
equation 50811 := x ◇ y = (z ◇ ((x ◇ x) ◇ y)) ◇ w
equation 50812 := x ◇ y = (z ◇ ((x ◇ x) ◇ z)) ◇ x
equation 50813 := x ◇ y = (z ◇ ((x ◇ x) ◇ z)) ◇ y
equation 50814 := x ◇ y = (z ◇ ((x ◇ x) ◇ z)) ◇ z
equation 50815 := x ◇ y = (z ◇ ((x ◇ x) ◇ z)) ◇ w
equation 50816 := x ◇ y = (z ◇ ((x ◇ x) ◇ w)) ◇ x
equation 50817 := x ◇ y = (z ◇ ((x ◇ x) ◇ w)) ◇ y
equation 50818 := x ◇ y = (z ◇ ((x ◇ x) ◇ w)) ◇ z
equation 50819 := x ◇ y = (z ◇ ((x ◇ x) ◇ w)) ◇ w
equation 50820 := x ◇ y = (z ◇ ((x ◇ x) ◇ w)) ◇ u
equation 50821 := x ◇ y = (z ◇ ((x ◇ y) ◇ x)) ◇ x
equation 50822 := x ◇ y = (z ◇ ((x ◇ y) ◇ x)) ◇ y
equation 50823 := x ◇ y = (z ◇ ((x ◇ y) ◇ x)) ◇ z
equation 50824 := x ◇ y = (z ◇ ((x ◇ y) ◇ x)) ◇ w
equation 50825 := x ◇ y = (z ◇ ((x ◇ y) ◇ y)) ◇ x
equation 50826 := x ◇ y = (z ◇ ((x ◇ y) ◇ y)) ◇ y
equation 50827 := x ◇ y = (z ◇ ((x ◇ y) ◇ y)) ◇ z
equation 50828 := x ◇ y = (z ◇ ((x ◇ y) ◇ y)) ◇ w
equation 50829 := x ◇ y = (z ◇ ((x ◇ y) ◇ z)) ◇ x
equation 50830 := x ◇ y = (z ◇ ((x ◇ y) ◇ z)) ◇ y
equation 50831 := x ◇ y = (z ◇ ((x ◇ y) ◇ z)) ◇ z
equation 50832 := x ◇ y = (z ◇ ((x ◇ y) ◇ z)) ◇ w
equation 50833 := x ◇ y = (z ◇ ((x ◇ y) ◇ w)) ◇ x
equation 50834 := x ◇ y = (z ◇ ((x ◇ y) ◇ w)) ◇ y
equation 50835 := x ◇ y = (z ◇ ((x ◇ y) ◇ w)) ◇ z
equation 50836 := x ◇ y = (z ◇ ((x ◇ y) ◇ w)) ◇ w
equation 50837 := x ◇ y = (z ◇ ((x ◇ y) ◇ w)) ◇ u
equation 50838 := x ◇ y = (z ◇ ((x ◇ z) ◇ x)) ◇ x
equation 50839 := x ◇ y = (z ◇ ((x ◇ z) ◇ x)) ◇ y
equation 50840 := x ◇ y = (z ◇ ((x ◇ z) ◇ x)) ◇ z
equation 50841 := x ◇ y = (z ◇ ((x ◇ z) ◇ x)) ◇ w
equation 50842 := x ◇ y = (z ◇ ((x ◇ z) ◇ y)) ◇ x
equation 50843 := x ◇ y = (z ◇ ((x ◇ z) ◇ y)) ◇ y
equation 50844 := x ◇ y = (z ◇ ((x ◇ z) ◇ y)) ◇ z
equation 50845 := x ◇ y = (z ◇ ((x ◇ z) ◇ y)) ◇ w
equation 50846 := x ◇ y = (z ◇ ((x ◇ z) ◇ z)) ◇ x
equation 50847 := x ◇ y = (z ◇ ((x ◇ z) ◇ z)) ◇ y
equation 50848 := x ◇ y = (z ◇ ((x ◇ z) ◇ z)) ◇ z
equation 50849 := x ◇ y = (z ◇ ((x ◇ z) ◇ z)) ◇ w
equation 50850 := x ◇ y = (z ◇ ((x ◇ z) ◇ w)) ◇ x
equation 50851 := x ◇ y = (z ◇ ((x ◇ z) ◇ w)) ◇ y
equation 50852 := x ◇ y = (z ◇ ((x ◇ z) ◇ w)) ◇ z
equation 50853 := x ◇ y = (z ◇ ((x ◇ z) ◇ w)) ◇ w
equation 50854 := x ◇ y = (z ◇ ((x ◇ z) ◇ w)) ◇ u
equation 50855 := x ◇ y = (z ◇ ((x ◇ w) ◇ x)) ◇ x
equation 50856 := x ◇ y = (z ◇ ((x ◇ w) ◇ x)) ◇ y
equation 50857 := x ◇ y = (z ◇ ((x ◇ w) ◇ x)) ◇ z
equation 50858 := x ◇ y = (z ◇ ((x ◇ w) ◇ x)) ◇ w
equation 50859 := x ◇ y = (z ◇ ((x ◇ w) ◇ x)) ◇ u
equation 50860 := x ◇ y = (z ◇ ((x ◇ w) ◇ y)) ◇ x
equation 50861 := x ◇ y = (z ◇ ((x ◇ w) ◇ y)) ◇ y
equation 50862 := x ◇ y = (z ◇ ((x ◇ w) ◇ y)) ◇ z
equation 50863 := x ◇ y = (z ◇ ((x ◇ w) ◇ y)) ◇ w
equation 50864 := x ◇ y = (z ◇ ((x ◇ w) ◇ y)) ◇ u
equation 50865 := x ◇ y = (z ◇ ((x ◇ w) ◇ z)) ◇ x
equation 50866 := x ◇ y = (z ◇ ((x ◇ w) ◇ z)) ◇ y
equation 50867 := x ◇ y = (z ◇ ((x ◇ w) ◇ z)) ◇ z
equation 50868 := x ◇ y = (z ◇ ((x ◇ w) ◇ z)) ◇ w
equation 50869 := x ◇ y = (z ◇ ((x ◇ w) ◇ z)) ◇ u
equation 50870 := x ◇ y = (z ◇ ((x ◇ w) ◇ w)) ◇ x
equation 50871 := x ◇ y = (z ◇ ((x ◇ w) ◇ w)) ◇ y
equation 50872 := x ◇ y = (z ◇ ((x ◇ w) ◇ w)) ◇ z
equation 50873 := x ◇ y = (z ◇ ((x ◇ w) ◇ w)) ◇ w
equation 50874 := x ◇ y = (z ◇ ((x ◇ w) ◇ w)) ◇ u
equation 50875 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ x
equation 50876 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ y
equation 50877 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ z
equation 50878 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ w
equation 50879 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ u
equation 50880 := x ◇ y = (z ◇ ((x ◇ w) ◇ u)) ◇ v
equation 50881 := x ◇ y = (z ◇ ((y ◇ x) ◇ x)) ◇ x
equation 50882 := x ◇ y = (z ◇ ((y ◇ x) ◇ x)) ◇ y
equation 50883 := x ◇ y = (z ◇ ((y ◇ x) ◇ x)) ◇ z
equation 50884 := x ◇ y = (z ◇ ((y ◇ x) ◇ x)) ◇ w
equation 50885 := x ◇ y = (z ◇ ((y ◇ x) ◇ y)) ◇ x
equation 50886 := x ◇ y = (z ◇ ((y ◇ x) ◇ y)) ◇ y
equation 50887 := x ◇ y = (z ◇ ((y ◇ x) ◇ y)) ◇ z
equation 50888 := x ◇ y = (z ◇ ((y ◇ x) ◇ y)) ◇ w
equation 50889 := x ◇ y = (z ◇ ((y ◇ x) ◇ z)) ◇ x
equation 50890 := x ◇ y = (z ◇ ((y ◇ x) ◇ z)) ◇ y
equation 50891 := x ◇ y = (z ◇ ((y ◇ x) ◇ z)) ◇ z
equation 50892 := x ◇ y = (z ◇ ((y ◇ x) ◇ z)) ◇ w
equation 50893 := x ◇ y = (z ◇ ((y ◇ x) ◇ w)) ◇ x
equation 50894 := x ◇ y = (z ◇ ((y ◇ x) ◇ w)) ◇ y
equation 50895 := x ◇ y = (z ◇ ((y ◇ x) ◇ w)) ◇ z
equation 50896 := x ◇ y = (z ◇ ((y ◇ x) ◇ w)) ◇ w
equation 50897 := x ◇ y = (z ◇ ((y ◇ x) ◇ w)) ◇ u
equation 50898 := x ◇ y = (z ◇ ((y ◇ y) ◇ x)) ◇ x
equation 50899 := x ◇ y = (z ◇ ((y ◇ y) ◇ x)) ◇ y
equation 50900 := x ◇ y = (z ◇ ((y ◇ y) ◇ x)) ◇ z
equation 50901 := x ◇ y = (z ◇ ((y ◇ y) ◇ x)) ◇ w
equation 50902 := x ◇ y = (z ◇ ((y ◇ y) ◇ y)) ◇ x
equation 50903 := x ◇ y = (z ◇ ((y ◇ y) ◇ y)) ◇ y
equation 50904 := x ◇ y = (z ◇ ((y ◇ y) ◇ y)) ◇ z
equation 50905 := x ◇ y = (z ◇ ((y ◇ y) ◇ y)) ◇ w
equation 50906 := x ◇ y = (z ◇ ((y ◇ y) ◇ z)) ◇ x
equation 50907 := x ◇ y = (z ◇ ((y ◇ y) ◇ z)) ◇ y
equation 50908 := x ◇ y = (z ◇ ((y ◇ y) ◇ z)) ◇ z
equation 50909 := x ◇ y = (z ◇ ((y ◇ y) ◇ z)) ◇ w
equation 50910 := x ◇ y = (z ◇ ((y ◇ y) ◇ w)) ◇ x
equation 50911 := x ◇ y = (z ◇ ((y ◇ y) ◇ w)) ◇ y
equation 50912 := x ◇ y = (z ◇ ((y ◇ y) ◇ w)) ◇ z
equation 50913 := x ◇ y = (z ◇ ((y ◇ y) ◇ w)) ◇ w
equation 50914 := x ◇ y = (z ◇ ((y ◇ y) ◇ w)) ◇ u
equation 50915 := x ◇ y = (z ◇ ((y ◇ z) ◇ x)) ◇ x
equation 50916 := x ◇ y = (z ◇ ((y ◇ z) ◇ x)) ◇ y
equation 50917 := x ◇ y = (z ◇ ((y ◇ z) ◇ x)) ◇ z
equation 50918 := x ◇ y = (z ◇ ((y ◇ z) ◇ x)) ◇ w
equation 50919 := x ◇ y = (z ◇ ((y ◇ z) ◇ y)) ◇ x
equation 50920 := x ◇ y = (z ◇ ((y ◇ z) ◇ y)) ◇ y
equation 50921 := x ◇ y = (z ◇ ((y ◇ z) ◇ y)) ◇ z
equation 50922 := x ◇ y = (z ◇ ((y ◇ z) ◇ y)) ◇ w
equation 50923 := x ◇ y = (z ◇ ((y ◇ z) ◇ z)) ◇ x
equation 50924 := x ◇ y = (z ◇ ((y ◇ z) ◇ z)) ◇ y
equation 50925 := x ◇ y = (z ◇ ((y ◇ z) ◇ z)) ◇ z
equation 50926 := x ◇ y = (z ◇ ((y ◇ z) ◇ z)) ◇ w
equation 50927 := x ◇ y = (z ◇ ((y ◇ z) ◇ w)) ◇ x
equation 50928 := x ◇ y = (z ◇ ((y ◇ z) ◇ w)) ◇ y
equation 50929 := x ◇ y = (z ◇ ((y ◇ z) ◇ w)) ◇ z
equation 50930 := x ◇ y = (z ◇ ((y ◇ z) ◇ w)) ◇ w
equation 50931 := x ◇ y = (z ◇ ((y ◇ z) ◇ w)) ◇ u
equation 50932 := x ◇ y = (z ◇ ((y ◇ w) ◇ x)) ◇ x
equation 50933 := x ◇ y = (z ◇ ((y ◇ w) ◇ x)) ◇ y
equation 50934 := x ◇ y = (z ◇ ((y ◇ w) ◇ x)) ◇ z
equation 50935 := x ◇ y = (z ◇ ((y ◇ w) ◇ x)) ◇ w
equation 50936 := x ◇ y = (z ◇ ((y ◇ w) ◇ x)) ◇ u
equation 50937 := x ◇ y = (z ◇ ((y ◇ w) ◇ y)) ◇ x
equation 50938 := x ◇ y = (z ◇ ((y ◇ w) ◇ y)) ◇ y
equation 50939 := x ◇ y = (z ◇ ((y ◇ w) ◇ y)) ◇ z
equation 50940 := x ◇ y = (z ◇ ((y ◇ w) ◇ y)) ◇ w
equation 50941 := x ◇ y = (z ◇ ((y ◇ w) ◇ y)) ◇ u
equation 50942 := x ◇ y = (z ◇ ((y ◇ w) ◇ z)) ◇ x
equation 50943 := x ◇ y = (z ◇ ((y ◇ w) ◇ z)) ◇ y
equation 50944 := x ◇ y = (z ◇ ((y ◇ w) ◇ z)) ◇ z
equation 50945 := x ◇ y = (z ◇ ((y ◇ w) ◇ z)) ◇ w
equation 50946 := x ◇ y = (z ◇ ((y ◇ w) ◇ z)) ◇ u
equation 50947 := x ◇ y = (z ◇ ((y ◇ w) ◇ w)) ◇ x
equation 50948 := x ◇ y = (z ◇ ((y ◇ w) ◇ w)) ◇ y
equation 50949 := x ◇ y = (z ◇ ((y ◇ w) ◇ w)) ◇ z
equation 50950 := x ◇ y = (z ◇ ((y ◇ w) ◇ w)) ◇ w
equation 50951 := x ◇ y = (z ◇ ((y ◇ w) ◇ w)) ◇ u
equation 50952 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ x
equation 50953 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ y
equation 50954 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ z
equation 50955 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ w
equation 50956 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ u
equation 50957 := x ◇ y = (z ◇ ((y ◇ w) ◇ u)) ◇ v
equation 50958 := x ◇ y = (z ◇ ((z ◇ x) ◇ x)) ◇ x
equation 50959 := x ◇ y = (z ◇ ((z ◇ x) ◇ x)) ◇ y
equation 50960 := x ◇ y = (z ◇ ((z ◇ x) ◇ x)) ◇ z
equation 50961 := x ◇ y = (z ◇ ((z ◇ x) ◇ x)) ◇ w
equation 50962 := x ◇ y = (z ◇ ((z ◇ x) ◇ y)) ◇ x
equation 50963 := x ◇ y = (z ◇ ((z ◇ x) ◇ y)) ◇ y
equation 50964 := x ◇ y = (z ◇ ((z ◇ x) ◇ y)) ◇ z
equation 50965 := x ◇ y = (z ◇ ((z ◇ x) ◇ y)) ◇ w
equation 50966 := x ◇ y = (z ◇ ((z ◇ x) ◇ z)) ◇ x
equation 50967 := x ◇ y = (z ◇ ((z ◇ x) ◇ z)) ◇ y
equation 50968 := x ◇ y = (z ◇ ((z ◇ x) ◇ z)) ◇ z
equation 50969 := x ◇ y = (z ◇ ((z ◇ x) ◇ z)) ◇ w
equation 50970 := x ◇ y = (z ◇ ((z ◇ x) ◇ w)) ◇ x
equation 50971 := x ◇ y = (z ◇ ((z ◇ x) ◇ w)) ◇ y
equation 50972 := x ◇ y = (z ◇ ((z ◇ x) ◇ w)) ◇ z
equation 50973 := x ◇ y = (z ◇ ((z ◇ x) ◇ w)) ◇ w
equation 50974 := x ◇ y = (z ◇ ((z ◇ x) ◇ w)) ◇ u
equation 50975 := x ◇ y = (z ◇ ((z ◇ y) ◇ x)) ◇ x
equation 50976 := x ◇ y = (z ◇ ((z ◇ y) ◇ x)) ◇ y
equation 50977 := x ◇ y = (z ◇ ((z ◇ y) ◇ x)) ◇ z
equation 50978 := x ◇ y = (z ◇ ((z ◇ y) ◇ x)) ◇ w
equation 50979 := x ◇ y = (z ◇ ((z ◇ y) ◇ y)) ◇ x
equation 50980 := x ◇ y = (z ◇ ((z ◇ y) ◇ y)) ◇ y
equation 50981 := x ◇ y = (z ◇ ((z ◇ y) ◇ y)) ◇ z
equation 50982 := x ◇ y = (z ◇ ((z ◇ y) ◇ y)) ◇ w
equation 50983 := x ◇ y = (z ◇ ((z ◇ y) ◇ z)) ◇ x
equation 50984 := x ◇ y = (z ◇ ((z ◇ y) ◇ z)) ◇ y
equation 50985 := x ◇ y = (z ◇ ((z ◇ y) ◇ z)) ◇ z
equation 50986 := x ◇ y = (z ◇ ((z ◇ y) ◇ z)) ◇ w
equation 50987 := x ◇ y = (z ◇ ((z ◇ y) ◇ w)) ◇ x
equation 50988 := x ◇ y = (z ◇ ((z ◇ y) ◇ w)) ◇ y
equation 50989 := x ◇ y = (z ◇ ((z ◇ y) ◇ w)) ◇ z
equation 50990 := x ◇ y = (z ◇ ((z ◇ y) ◇ w)) ◇ w
equation 50991 := x ◇ y = (z ◇ ((z ◇ y) ◇ w)) ◇ u
equation 50992 := x ◇ y = (z ◇ ((z ◇ z) ◇ x)) ◇ x
equation 50993 := x ◇ y = (z ◇ ((z ◇ z) ◇ x)) ◇ y
equation 50994 := x ◇ y = (z ◇ ((z ◇ z) ◇ x)) ◇ z
equation 50995 := x ◇ y = (z ◇ ((z ◇ z) ◇ x)) ◇ w
equation 50996 := x ◇ y = (z ◇ ((z ◇ z) ◇ y)) ◇ x
equation 50997 := x ◇ y = (z ◇ ((z ◇ z) ◇ y)) ◇ y
equation 50998 := x ◇ y = (z ◇ ((z ◇ z) ◇ y)) ◇ z
equation 50999 := x ◇ y = (z ◇ ((z ◇ z) ◇ y)) ◇ w
