import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 36000-36999 -/

equation 36000 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ z)) ◇ w
equation 36001 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ w)) ◇ x
equation 36002 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ w)) ◇ y
equation 36003 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ w)) ◇ z
equation 36004 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ w)) ◇ w
equation 36005 := x = ((y ◇ (z ◇ y)) ◇ (y ◇ w)) ◇ u
equation 36006 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ x)) ◇ x
equation 36007 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ x)) ◇ y
equation 36008 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ x)) ◇ z
equation 36009 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ x)) ◇ w
equation 36010 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ y)) ◇ x
equation 36011 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ y)) ◇ y
equation 36012 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ y)) ◇ z
equation 36013 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ y)) ◇ w
equation 36014 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ z)) ◇ x
equation 36015 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ z)) ◇ y
equation 36016 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ z)) ◇ z
equation 36017 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ z)) ◇ w
equation 36018 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ w)) ◇ x
equation 36019 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ w)) ◇ y
equation 36020 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ w)) ◇ z
equation 36021 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ w)) ◇ w
equation 36022 := x = ((y ◇ (z ◇ y)) ◇ (z ◇ w)) ◇ u
equation 36023 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ x)) ◇ x
equation 36024 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ x)) ◇ y
equation 36025 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ x)) ◇ z
equation 36026 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ x)) ◇ w
equation 36027 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ x)) ◇ u
equation 36028 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ y)) ◇ x
equation 36029 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ y)) ◇ y
equation 36030 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ y)) ◇ z
equation 36031 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ y)) ◇ w
equation 36032 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ y)) ◇ u
equation 36033 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ z)) ◇ x
equation 36034 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ z)) ◇ y
equation 36035 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ z)) ◇ z
equation 36036 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ z)) ◇ w
equation 36037 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ z)) ◇ u
equation 36038 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ w)) ◇ x
equation 36039 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ w)) ◇ y
equation 36040 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ w)) ◇ z
equation 36041 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ w)) ◇ w
equation 36042 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ w)) ◇ u
equation 36043 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ x
equation 36044 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ y
equation 36045 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ z
equation 36046 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ w
equation 36047 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ u
equation 36048 := x = ((y ◇ (z ◇ y)) ◇ (w ◇ u)) ◇ v
equation 36049 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ x)) ◇ x
equation 36050 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ x)) ◇ y
equation 36051 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ x)) ◇ z
equation 36052 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ x)) ◇ w
equation 36053 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ y)) ◇ x
equation 36054 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ y)) ◇ y
equation 36055 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ y)) ◇ z
equation 36056 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ y)) ◇ w
equation 36057 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ z)) ◇ x
equation 36058 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ z)) ◇ y
equation 36059 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ z)) ◇ z
equation 36060 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ z)) ◇ w
equation 36061 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ w)) ◇ x
equation 36062 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ w)) ◇ y
equation 36063 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ w)) ◇ z
equation 36064 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ w)) ◇ w
equation 36065 := x = ((y ◇ (z ◇ z)) ◇ (x ◇ w)) ◇ u
equation 36066 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ x)) ◇ x
equation 36067 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ x)) ◇ y
equation 36068 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ x)) ◇ z
equation 36069 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ x)) ◇ w
equation 36070 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ y)) ◇ x
equation 36071 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ y)) ◇ y
equation 36072 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ y)) ◇ z
equation 36073 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ y)) ◇ w
equation 36074 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ z)) ◇ x
equation 36075 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ z)) ◇ y
equation 36076 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ z)) ◇ z
equation 36077 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ z)) ◇ w
equation 36078 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ w)) ◇ x
equation 36079 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ w)) ◇ y
equation 36080 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ w)) ◇ z
equation 36081 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ w)) ◇ w
equation 36082 := x = ((y ◇ (z ◇ z)) ◇ (y ◇ w)) ◇ u
equation 36083 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ x)) ◇ x
equation 36084 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ x)) ◇ y
equation 36085 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ x)) ◇ z
equation 36086 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ x)) ◇ w
equation 36087 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ y)) ◇ x
equation 36088 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ y)) ◇ y
equation 36089 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ y)) ◇ z
equation 36090 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ y)) ◇ w
equation 36091 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ z)) ◇ x
equation 36092 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ z)) ◇ y
equation 36093 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ z)) ◇ z
equation 36094 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ z)) ◇ w
equation 36095 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ w)) ◇ x
equation 36096 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ w)) ◇ y
equation 36097 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ w)) ◇ z
equation 36098 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ w)) ◇ w
equation 36099 := x = ((y ◇ (z ◇ z)) ◇ (z ◇ w)) ◇ u
equation 36100 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ x)) ◇ x
equation 36101 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ x)) ◇ y
equation 36102 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ x)) ◇ z
equation 36103 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ x)) ◇ w
equation 36104 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ x)) ◇ u
equation 36105 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ y)) ◇ x
equation 36106 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ y)) ◇ y
equation 36107 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ y)) ◇ z
equation 36108 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ y)) ◇ w
equation 36109 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ y)) ◇ u
equation 36110 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ z)) ◇ x
equation 36111 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ z)) ◇ y
equation 36112 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ z)) ◇ z
equation 36113 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ z)) ◇ w
equation 36114 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ z)) ◇ u
equation 36115 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ w)) ◇ x
equation 36116 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ w)) ◇ y
equation 36117 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ w)) ◇ z
equation 36118 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ w)) ◇ w
equation 36119 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ w)) ◇ u
equation 36120 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ x
equation 36121 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ y
equation 36122 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ z
equation 36123 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ w
equation 36124 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ u
equation 36125 := x = ((y ◇ (z ◇ z)) ◇ (w ◇ u)) ◇ v
equation 36126 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ x)) ◇ x
equation 36127 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ x)) ◇ y
equation 36128 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ x)) ◇ z
equation 36129 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ x)) ◇ w
equation 36130 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ x)) ◇ u
equation 36131 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ y)) ◇ x
equation 36132 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ y)) ◇ y
equation 36133 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ y)) ◇ z
equation 36134 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ y)) ◇ w
equation 36135 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ y)) ◇ u
equation 36136 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ z)) ◇ x
equation 36137 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ z)) ◇ y
equation 36138 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ z)) ◇ z
equation 36139 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ z)) ◇ w
equation 36140 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ z)) ◇ u
equation 36141 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ w)) ◇ x
equation 36142 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ w)) ◇ y
equation 36143 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ w)) ◇ z
equation 36144 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ w)) ◇ w
equation 36145 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ w)) ◇ u
equation 36146 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ x
equation 36147 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ y
equation 36148 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ z
equation 36149 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ w
equation 36150 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ u
equation 36151 := x = ((y ◇ (z ◇ w)) ◇ (x ◇ u)) ◇ v
equation 36152 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ x)) ◇ x
equation 36153 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ x)) ◇ y
equation 36154 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ x)) ◇ z
equation 36155 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ x)) ◇ w
equation 36156 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ x)) ◇ u
equation 36157 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ y)) ◇ x
equation 36158 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ y)) ◇ y
equation 36159 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ y)) ◇ z
equation 36160 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ y)) ◇ w
equation 36161 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ y)) ◇ u
equation 36162 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ z)) ◇ x
equation 36163 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ z)) ◇ y
equation 36164 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ z)) ◇ z
equation 36165 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ z)) ◇ w
equation 36166 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ z)) ◇ u
equation 36167 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ w)) ◇ x
equation 36168 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ w)) ◇ y
equation 36169 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ w)) ◇ z
equation 36170 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ w)) ◇ w
equation 36171 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ w)) ◇ u
equation 36172 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ x
equation 36173 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ y
equation 36174 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ z
equation 36175 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ w
equation 36176 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ u
equation 36177 := x = ((y ◇ (z ◇ w)) ◇ (y ◇ u)) ◇ v
equation 36178 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ x)) ◇ x
equation 36179 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ x)) ◇ y
equation 36180 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ x)) ◇ z
equation 36181 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ x)) ◇ w
equation 36182 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ x)) ◇ u
equation 36183 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ y)) ◇ x
equation 36184 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ y)) ◇ y
equation 36185 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ y)) ◇ z
equation 36186 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ y)) ◇ w
equation 36187 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ y)) ◇ u
equation 36188 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ z)) ◇ x
equation 36189 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ z)) ◇ y
equation 36190 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ z)) ◇ z
equation 36191 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ z)) ◇ w
equation 36192 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ z)) ◇ u
equation 36193 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ w)) ◇ x
equation 36194 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ w)) ◇ y
equation 36195 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ w)) ◇ z
equation 36196 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ w)) ◇ w
equation 36197 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ w)) ◇ u
equation 36198 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ x
equation 36199 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ y
equation 36200 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ z
equation 36201 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ w
equation 36202 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ u
equation 36203 := x = ((y ◇ (z ◇ w)) ◇ (z ◇ u)) ◇ v
equation 36204 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ x)) ◇ x
equation 36205 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ x)) ◇ y
equation 36206 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ x)) ◇ z
equation 36207 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ x)) ◇ w
equation 36208 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ x)) ◇ u
equation 36209 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ y)) ◇ x
equation 36210 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ y)) ◇ y
equation 36211 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ y)) ◇ z
equation 36212 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ y)) ◇ w
equation 36213 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ y)) ◇ u
equation 36214 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ z)) ◇ x
equation 36215 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ z)) ◇ y
equation 36216 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ z)) ◇ z
equation 36217 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ z)) ◇ w
equation 36218 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ z)) ◇ u
equation 36219 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ w)) ◇ x
equation 36220 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ w)) ◇ y
equation 36221 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ w)) ◇ z
equation 36222 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ w)) ◇ w
equation 36223 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ w)) ◇ u
equation 36224 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ x
equation 36225 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ y
equation 36226 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ z
equation 36227 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ w
equation 36228 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ u
equation 36229 := x = ((y ◇ (z ◇ w)) ◇ (w ◇ u)) ◇ v
equation 36230 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ x
equation 36231 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ y
equation 36232 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ z
equation 36233 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ w
equation 36234 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ u
equation 36235 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ x)) ◇ v
equation 36236 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ x
equation 36237 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ y
equation 36238 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ z
equation 36239 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ w
equation 36240 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ u
equation 36241 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ y)) ◇ v
equation 36242 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ x
equation 36243 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ y
equation 36244 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ z
equation 36245 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ w
equation 36246 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ u
equation 36247 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ z)) ◇ v
equation 36248 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ x
equation 36249 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ y
equation 36250 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ z
equation 36251 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ w
equation 36252 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ u
equation 36253 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ w)) ◇ v
equation 36254 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ x
equation 36255 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ y
equation 36256 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ z
equation 36257 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ w
equation 36258 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ u
equation 36259 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ u)) ◇ v
equation 36260 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ x
equation 36261 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ y
equation 36262 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ z
equation 36263 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ w
equation 36264 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ u
equation 36265 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ v
equation 36266 := x = ((y ◇ (z ◇ w)) ◇ (u ◇ v)) ◇ r
equation 36267 := x = (((x ◇ x) ◇ x) ◇ (x ◇ x)) ◇ x
equation 36268 := x = (((x ◇ x) ◇ x) ◇ (x ◇ x)) ◇ y
equation 36269 := x = (((x ◇ x) ◇ x) ◇ (x ◇ y)) ◇ x
equation 36270 := x = (((x ◇ x) ◇ x) ◇ (x ◇ y)) ◇ y
equation 36271 := x = (((x ◇ x) ◇ x) ◇ (x ◇ y)) ◇ z
equation 36272 := x = (((x ◇ x) ◇ x) ◇ (y ◇ x)) ◇ x
equation 36273 := x = (((x ◇ x) ◇ x) ◇ (y ◇ x)) ◇ y
equation 36274 := x = (((x ◇ x) ◇ x) ◇ (y ◇ x)) ◇ z
equation 36275 := x = (((x ◇ x) ◇ x) ◇ (y ◇ y)) ◇ x
equation 36276 := x = (((x ◇ x) ◇ x) ◇ (y ◇ y)) ◇ y
equation 36277 := x = (((x ◇ x) ◇ x) ◇ (y ◇ y)) ◇ z
equation 36278 := x = (((x ◇ x) ◇ x) ◇ (y ◇ z)) ◇ x
equation 36279 := x = (((x ◇ x) ◇ x) ◇ (y ◇ z)) ◇ y
equation 36280 := x = (((x ◇ x) ◇ x) ◇ (y ◇ z)) ◇ z
equation 36281 := x = (((x ◇ x) ◇ x) ◇ (y ◇ z)) ◇ w
equation 36282 := x = (((x ◇ x) ◇ y) ◇ (x ◇ x)) ◇ x
equation 36283 := x = (((x ◇ x) ◇ y) ◇ (x ◇ x)) ◇ y
equation 36284 := x = (((x ◇ x) ◇ y) ◇ (x ◇ x)) ◇ z
equation 36285 := x = (((x ◇ x) ◇ y) ◇ (x ◇ y)) ◇ x
equation 36286 := x = (((x ◇ x) ◇ y) ◇ (x ◇ y)) ◇ y
equation 36287 := x = (((x ◇ x) ◇ y) ◇ (x ◇ y)) ◇ z
equation 36288 := x = (((x ◇ x) ◇ y) ◇ (x ◇ z)) ◇ x
equation 36289 := x = (((x ◇ x) ◇ y) ◇ (x ◇ z)) ◇ y
equation 36290 := x = (((x ◇ x) ◇ y) ◇ (x ◇ z)) ◇ z
equation 36291 := x = (((x ◇ x) ◇ y) ◇ (x ◇ z)) ◇ w
equation 36292 := x = (((x ◇ x) ◇ y) ◇ (y ◇ x)) ◇ x
equation 36293 := x = (((x ◇ x) ◇ y) ◇ (y ◇ x)) ◇ y
equation 36294 := x = (((x ◇ x) ◇ y) ◇ (y ◇ x)) ◇ z
equation 36295 := x = (((x ◇ x) ◇ y) ◇ (y ◇ y)) ◇ x
equation 36296 := x = (((x ◇ x) ◇ y) ◇ (y ◇ y)) ◇ y
equation 36297 := x = (((x ◇ x) ◇ y) ◇ (y ◇ y)) ◇ z
equation 36298 := x = (((x ◇ x) ◇ y) ◇ (y ◇ z)) ◇ x
equation 36299 := x = (((x ◇ x) ◇ y) ◇ (y ◇ z)) ◇ y
equation 36300 := x = (((x ◇ x) ◇ y) ◇ (y ◇ z)) ◇ z
equation 36301 := x = (((x ◇ x) ◇ y) ◇ (y ◇ z)) ◇ w
equation 36302 := x = (((x ◇ x) ◇ y) ◇ (z ◇ x)) ◇ x
equation 36303 := x = (((x ◇ x) ◇ y) ◇ (z ◇ x)) ◇ y
equation 36304 := x = (((x ◇ x) ◇ y) ◇ (z ◇ x)) ◇ z
equation 36305 := x = (((x ◇ x) ◇ y) ◇ (z ◇ x)) ◇ w
equation 36306 := x = (((x ◇ x) ◇ y) ◇ (z ◇ y)) ◇ x
equation 36307 := x = (((x ◇ x) ◇ y) ◇ (z ◇ y)) ◇ y
equation 36308 := x = (((x ◇ x) ◇ y) ◇ (z ◇ y)) ◇ z
equation 36309 := x = (((x ◇ x) ◇ y) ◇ (z ◇ y)) ◇ w
equation 36310 := x = (((x ◇ x) ◇ y) ◇ (z ◇ z)) ◇ x
equation 36311 := x = (((x ◇ x) ◇ y) ◇ (z ◇ z)) ◇ y
equation 36312 := x = (((x ◇ x) ◇ y) ◇ (z ◇ z)) ◇ z
equation 36313 := x = (((x ◇ x) ◇ y) ◇ (z ◇ z)) ◇ w
equation 36314 := x = (((x ◇ x) ◇ y) ◇ (z ◇ w)) ◇ x
equation 36315 := x = (((x ◇ x) ◇ y) ◇ (z ◇ w)) ◇ y
equation 36316 := x = (((x ◇ x) ◇ y) ◇ (z ◇ w)) ◇ z
equation 36317 := x = (((x ◇ x) ◇ y) ◇ (z ◇ w)) ◇ w
equation 36318 := x = (((x ◇ x) ◇ y) ◇ (z ◇ w)) ◇ u
equation 36319 := x = (((x ◇ y) ◇ x) ◇ (x ◇ x)) ◇ x
equation 36320 := x = (((x ◇ y) ◇ x) ◇ (x ◇ x)) ◇ y
equation 36321 := x = (((x ◇ y) ◇ x) ◇ (x ◇ x)) ◇ z
equation 36322 := x = (((x ◇ y) ◇ x) ◇ (x ◇ y)) ◇ x
equation 36323 := x = (((x ◇ y) ◇ x) ◇ (x ◇ y)) ◇ y
equation 36324 := x = (((x ◇ y) ◇ x) ◇ (x ◇ y)) ◇ z
equation 36325 := x = (((x ◇ y) ◇ x) ◇ (x ◇ z)) ◇ x
equation 36326 := x = (((x ◇ y) ◇ x) ◇ (x ◇ z)) ◇ y
equation 36327 := x = (((x ◇ y) ◇ x) ◇ (x ◇ z)) ◇ z
equation 36328 := x = (((x ◇ y) ◇ x) ◇ (x ◇ z)) ◇ w
equation 36329 := x = (((x ◇ y) ◇ x) ◇ (y ◇ x)) ◇ x
equation 36330 := x = (((x ◇ y) ◇ x) ◇ (y ◇ x)) ◇ y
equation 36331 := x = (((x ◇ y) ◇ x) ◇ (y ◇ x)) ◇ z
equation 36332 := x = (((x ◇ y) ◇ x) ◇ (y ◇ y)) ◇ x
equation 36333 := x = (((x ◇ y) ◇ x) ◇ (y ◇ y)) ◇ y
equation 36334 := x = (((x ◇ y) ◇ x) ◇ (y ◇ y)) ◇ z
equation 36335 := x = (((x ◇ y) ◇ x) ◇ (y ◇ z)) ◇ x
equation 36336 := x = (((x ◇ y) ◇ x) ◇ (y ◇ z)) ◇ y
equation 36337 := x = (((x ◇ y) ◇ x) ◇ (y ◇ z)) ◇ z
equation 36338 := x = (((x ◇ y) ◇ x) ◇ (y ◇ z)) ◇ w
equation 36339 := x = (((x ◇ y) ◇ x) ◇ (z ◇ x)) ◇ x
equation 36340 := x = (((x ◇ y) ◇ x) ◇ (z ◇ x)) ◇ y
equation 36341 := x = (((x ◇ y) ◇ x) ◇ (z ◇ x)) ◇ z
equation 36342 := x = (((x ◇ y) ◇ x) ◇ (z ◇ x)) ◇ w
equation 36343 := x = (((x ◇ y) ◇ x) ◇ (z ◇ y)) ◇ x
equation 36344 := x = (((x ◇ y) ◇ x) ◇ (z ◇ y)) ◇ y
equation 36345 := x = (((x ◇ y) ◇ x) ◇ (z ◇ y)) ◇ z
equation 36346 := x = (((x ◇ y) ◇ x) ◇ (z ◇ y)) ◇ w
equation 36347 := x = (((x ◇ y) ◇ x) ◇ (z ◇ z)) ◇ x
equation 36348 := x = (((x ◇ y) ◇ x) ◇ (z ◇ z)) ◇ y
equation 36349 := x = (((x ◇ y) ◇ x) ◇ (z ◇ z)) ◇ z
equation 36350 := x = (((x ◇ y) ◇ x) ◇ (z ◇ z)) ◇ w
equation 36351 := x = (((x ◇ y) ◇ x) ◇ (z ◇ w)) ◇ x
equation 36352 := x = (((x ◇ y) ◇ x) ◇ (z ◇ w)) ◇ y
equation 36353 := x = (((x ◇ y) ◇ x) ◇ (z ◇ w)) ◇ z
equation 36354 := x = (((x ◇ y) ◇ x) ◇ (z ◇ w)) ◇ w
equation 36355 := x = (((x ◇ y) ◇ x) ◇ (z ◇ w)) ◇ u
equation 36356 := x = (((x ◇ y) ◇ y) ◇ (x ◇ x)) ◇ x
equation 36357 := x = (((x ◇ y) ◇ y) ◇ (x ◇ x)) ◇ y
equation 36358 := x = (((x ◇ y) ◇ y) ◇ (x ◇ x)) ◇ z
equation 36359 := x = (((x ◇ y) ◇ y) ◇ (x ◇ y)) ◇ x
equation 36360 := x = (((x ◇ y) ◇ y) ◇ (x ◇ y)) ◇ y
equation 36361 := x = (((x ◇ y) ◇ y) ◇ (x ◇ y)) ◇ z
equation 36362 := x = (((x ◇ y) ◇ y) ◇ (x ◇ z)) ◇ x
equation 36363 := x = (((x ◇ y) ◇ y) ◇ (x ◇ z)) ◇ y
equation 36364 := x = (((x ◇ y) ◇ y) ◇ (x ◇ z)) ◇ z
equation 36365 := x = (((x ◇ y) ◇ y) ◇ (x ◇ z)) ◇ w
equation 36366 := x = (((x ◇ y) ◇ y) ◇ (y ◇ x)) ◇ x
equation 36367 := x = (((x ◇ y) ◇ y) ◇ (y ◇ x)) ◇ y
equation 36368 := x = (((x ◇ y) ◇ y) ◇ (y ◇ x)) ◇ z
equation 36369 := x = (((x ◇ y) ◇ y) ◇ (y ◇ y)) ◇ x
equation 36370 := x = (((x ◇ y) ◇ y) ◇ (y ◇ y)) ◇ y
equation 36371 := x = (((x ◇ y) ◇ y) ◇ (y ◇ y)) ◇ z
equation 36372 := x = (((x ◇ y) ◇ y) ◇ (y ◇ z)) ◇ x
equation 36373 := x = (((x ◇ y) ◇ y) ◇ (y ◇ z)) ◇ y
equation 36374 := x = (((x ◇ y) ◇ y) ◇ (y ◇ z)) ◇ z
equation 36375 := x = (((x ◇ y) ◇ y) ◇ (y ◇ z)) ◇ w
equation 36376 := x = (((x ◇ y) ◇ y) ◇ (z ◇ x)) ◇ x
equation 36377 := x = (((x ◇ y) ◇ y) ◇ (z ◇ x)) ◇ y
equation 36378 := x = (((x ◇ y) ◇ y) ◇ (z ◇ x)) ◇ z
equation 36379 := x = (((x ◇ y) ◇ y) ◇ (z ◇ x)) ◇ w
equation 36380 := x = (((x ◇ y) ◇ y) ◇ (z ◇ y)) ◇ x
equation 36381 := x = (((x ◇ y) ◇ y) ◇ (z ◇ y)) ◇ y
equation 36382 := x = (((x ◇ y) ◇ y) ◇ (z ◇ y)) ◇ z
equation 36383 := x = (((x ◇ y) ◇ y) ◇ (z ◇ y)) ◇ w
equation 36384 := x = (((x ◇ y) ◇ y) ◇ (z ◇ z)) ◇ x
equation 36385 := x = (((x ◇ y) ◇ y) ◇ (z ◇ z)) ◇ y
equation 36386 := x = (((x ◇ y) ◇ y) ◇ (z ◇ z)) ◇ z
equation 36387 := x = (((x ◇ y) ◇ y) ◇ (z ◇ z)) ◇ w
equation 36388 := x = (((x ◇ y) ◇ y) ◇ (z ◇ w)) ◇ x
equation 36389 := x = (((x ◇ y) ◇ y) ◇ (z ◇ w)) ◇ y
equation 36390 := x = (((x ◇ y) ◇ y) ◇ (z ◇ w)) ◇ z
equation 36391 := x = (((x ◇ y) ◇ y) ◇ (z ◇ w)) ◇ w
equation 36392 := x = (((x ◇ y) ◇ y) ◇ (z ◇ w)) ◇ u
equation 36393 := x = (((x ◇ y) ◇ z) ◇ (x ◇ x)) ◇ x
equation 36394 := x = (((x ◇ y) ◇ z) ◇ (x ◇ x)) ◇ y
equation 36395 := x = (((x ◇ y) ◇ z) ◇ (x ◇ x)) ◇ z
equation 36396 := x = (((x ◇ y) ◇ z) ◇ (x ◇ x)) ◇ w
equation 36397 := x = (((x ◇ y) ◇ z) ◇ (x ◇ y)) ◇ x
equation 36398 := x = (((x ◇ y) ◇ z) ◇ (x ◇ y)) ◇ y
equation 36399 := x = (((x ◇ y) ◇ z) ◇ (x ◇ y)) ◇ z
equation 36400 := x = (((x ◇ y) ◇ z) ◇ (x ◇ y)) ◇ w
equation 36401 := x = (((x ◇ y) ◇ z) ◇ (x ◇ z)) ◇ x
equation 36402 := x = (((x ◇ y) ◇ z) ◇ (x ◇ z)) ◇ y
equation 36403 := x = (((x ◇ y) ◇ z) ◇ (x ◇ z)) ◇ z
equation 36404 := x = (((x ◇ y) ◇ z) ◇ (x ◇ z)) ◇ w
equation 36405 := x = (((x ◇ y) ◇ z) ◇ (x ◇ w)) ◇ x
equation 36406 := x = (((x ◇ y) ◇ z) ◇ (x ◇ w)) ◇ y
equation 36407 := x = (((x ◇ y) ◇ z) ◇ (x ◇ w)) ◇ z
equation 36408 := x = (((x ◇ y) ◇ z) ◇ (x ◇ w)) ◇ w
equation 36409 := x = (((x ◇ y) ◇ z) ◇ (x ◇ w)) ◇ u
equation 36410 := x = (((x ◇ y) ◇ z) ◇ (y ◇ x)) ◇ x
equation 36411 := x = (((x ◇ y) ◇ z) ◇ (y ◇ x)) ◇ y
equation 36412 := x = (((x ◇ y) ◇ z) ◇ (y ◇ x)) ◇ z
equation 36413 := x = (((x ◇ y) ◇ z) ◇ (y ◇ x)) ◇ w
equation 36414 := x = (((x ◇ y) ◇ z) ◇ (y ◇ y)) ◇ x
equation 36415 := x = (((x ◇ y) ◇ z) ◇ (y ◇ y)) ◇ y
equation 36416 := x = (((x ◇ y) ◇ z) ◇ (y ◇ y)) ◇ z
equation 36417 := x = (((x ◇ y) ◇ z) ◇ (y ◇ y)) ◇ w
equation 36418 := x = (((x ◇ y) ◇ z) ◇ (y ◇ z)) ◇ x
equation 36419 := x = (((x ◇ y) ◇ z) ◇ (y ◇ z)) ◇ y
equation 36420 := x = (((x ◇ y) ◇ z) ◇ (y ◇ z)) ◇ z
equation 36421 := x = (((x ◇ y) ◇ z) ◇ (y ◇ z)) ◇ w
equation 36422 := x = (((x ◇ y) ◇ z) ◇ (y ◇ w)) ◇ x
equation 36423 := x = (((x ◇ y) ◇ z) ◇ (y ◇ w)) ◇ y
equation 36424 := x = (((x ◇ y) ◇ z) ◇ (y ◇ w)) ◇ z
equation 36425 := x = (((x ◇ y) ◇ z) ◇ (y ◇ w)) ◇ w
equation 36426 := x = (((x ◇ y) ◇ z) ◇ (y ◇ w)) ◇ u
equation 36427 := x = (((x ◇ y) ◇ z) ◇ (z ◇ x)) ◇ x
equation 36428 := x = (((x ◇ y) ◇ z) ◇ (z ◇ x)) ◇ y
equation 36429 := x = (((x ◇ y) ◇ z) ◇ (z ◇ x)) ◇ z
equation 36430 := x = (((x ◇ y) ◇ z) ◇ (z ◇ x)) ◇ w
equation 36431 := x = (((x ◇ y) ◇ z) ◇ (z ◇ y)) ◇ x
equation 36432 := x = (((x ◇ y) ◇ z) ◇ (z ◇ y)) ◇ y
equation 36433 := x = (((x ◇ y) ◇ z) ◇ (z ◇ y)) ◇ z
equation 36434 := x = (((x ◇ y) ◇ z) ◇ (z ◇ y)) ◇ w
equation 36435 := x = (((x ◇ y) ◇ z) ◇ (z ◇ z)) ◇ x
equation 36436 := x = (((x ◇ y) ◇ z) ◇ (z ◇ z)) ◇ y
equation 36437 := x = (((x ◇ y) ◇ z) ◇ (z ◇ z)) ◇ z
equation 36438 := x = (((x ◇ y) ◇ z) ◇ (z ◇ z)) ◇ w
equation 36439 := x = (((x ◇ y) ◇ z) ◇ (z ◇ w)) ◇ x
equation 36440 := x = (((x ◇ y) ◇ z) ◇ (z ◇ w)) ◇ y
equation 36441 := x = (((x ◇ y) ◇ z) ◇ (z ◇ w)) ◇ z
equation 36442 := x = (((x ◇ y) ◇ z) ◇ (z ◇ w)) ◇ w
equation 36443 := x = (((x ◇ y) ◇ z) ◇ (z ◇ w)) ◇ u
equation 36444 := x = (((x ◇ y) ◇ z) ◇ (w ◇ x)) ◇ x
equation 36445 := x = (((x ◇ y) ◇ z) ◇ (w ◇ x)) ◇ y
equation 36446 := x = (((x ◇ y) ◇ z) ◇ (w ◇ x)) ◇ z
equation 36447 := x = (((x ◇ y) ◇ z) ◇ (w ◇ x)) ◇ w
equation 36448 := x = (((x ◇ y) ◇ z) ◇ (w ◇ x)) ◇ u
equation 36449 := x = (((x ◇ y) ◇ z) ◇ (w ◇ y)) ◇ x
equation 36450 := x = (((x ◇ y) ◇ z) ◇ (w ◇ y)) ◇ y
equation 36451 := x = (((x ◇ y) ◇ z) ◇ (w ◇ y)) ◇ z
equation 36452 := x = (((x ◇ y) ◇ z) ◇ (w ◇ y)) ◇ w
equation 36453 := x = (((x ◇ y) ◇ z) ◇ (w ◇ y)) ◇ u
equation 36454 := x = (((x ◇ y) ◇ z) ◇ (w ◇ z)) ◇ x
equation 36455 := x = (((x ◇ y) ◇ z) ◇ (w ◇ z)) ◇ y
equation 36456 := x = (((x ◇ y) ◇ z) ◇ (w ◇ z)) ◇ z
equation 36457 := x = (((x ◇ y) ◇ z) ◇ (w ◇ z)) ◇ w
equation 36458 := x = (((x ◇ y) ◇ z) ◇ (w ◇ z)) ◇ u
equation 36459 := x = (((x ◇ y) ◇ z) ◇ (w ◇ w)) ◇ x
equation 36460 := x = (((x ◇ y) ◇ z) ◇ (w ◇ w)) ◇ y
equation 36461 := x = (((x ◇ y) ◇ z) ◇ (w ◇ w)) ◇ z
equation 36462 := x = (((x ◇ y) ◇ z) ◇ (w ◇ w)) ◇ w
equation 36463 := x = (((x ◇ y) ◇ z) ◇ (w ◇ w)) ◇ u
equation 36464 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ x
equation 36465 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ y
equation 36466 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ z
equation 36467 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ w
equation 36468 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ u
equation 36469 := x = (((x ◇ y) ◇ z) ◇ (w ◇ u)) ◇ v
equation 36470 := x = (((y ◇ x) ◇ x) ◇ (x ◇ x)) ◇ x
equation 36471 := x = (((y ◇ x) ◇ x) ◇ (x ◇ x)) ◇ y
equation 36472 := x = (((y ◇ x) ◇ x) ◇ (x ◇ x)) ◇ z
equation 36473 := x = (((y ◇ x) ◇ x) ◇ (x ◇ y)) ◇ x
equation 36474 := x = (((y ◇ x) ◇ x) ◇ (x ◇ y)) ◇ y
equation 36475 := x = (((y ◇ x) ◇ x) ◇ (x ◇ y)) ◇ z
equation 36476 := x = (((y ◇ x) ◇ x) ◇ (x ◇ z)) ◇ x
equation 36477 := x = (((y ◇ x) ◇ x) ◇ (x ◇ z)) ◇ y
equation 36478 := x = (((y ◇ x) ◇ x) ◇ (x ◇ z)) ◇ z
equation 36479 := x = (((y ◇ x) ◇ x) ◇ (x ◇ z)) ◇ w
equation 36480 := x = (((y ◇ x) ◇ x) ◇ (y ◇ x)) ◇ x
equation 36481 := x = (((y ◇ x) ◇ x) ◇ (y ◇ x)) ◇ y
equation 36482 := x = (((y ◇ x) ◇ x) ◇ (y ◇ x)) ◇ z
equation 36483 := x = (((y ◇ x) ◇ x) ◇ (y ◇ y)) ◇ x
equation 36484 := x = (((y ◇ x) ◇ x) ◇ (y ◇ y)) ◇ y
equation 36485 := x = (((y ◇ x) ◇ x) ◇ (y ◇ y)) ◇ z
equation 36486 := x = (((y ◇ x) ◇ x) ◇ (y ◇ z)) ◇ x
equation 36487 := x = (((y ◇ x) ◇ x) ◇ (y ◇ z)) ◇ y
equation 36488 := x = (((y ◇ x) ◇ x) ◇ (y ◇ z)) ◇ z
equation 36489 := x = (((y ◇ x) ◇ x) ◇ (y ◇ z)) ◇ w
equation 36490 := x = (((y ◇ x) ◇ x) ◇ (z ◇ x)) ◇ x
equation 36491 := x = (((y ◇ x) ◇ x) ◇ (z ◇ x)) ◇ y
equation 36492 := x = (((y ◇ x) ◇ x) ◇ (z ◇ x)) ◇ z
equation 36493 := x = (((y ◇ x) ◇ x) ◇ (z ◇ x)) ◇ w
equation 36494 := x = (((y ◇ x) ◇ x) ◇ (z ◇ y)) ◇ x
equation 36495 := x = (((y ◇ x) ◇ x) ◇ (z ◇ y)) ◇ y
equation 36496 := x = (((y ◇ x) ◇ x) ◇ (z ◇ y)) ◇ z
equation 36497 := x = (((y ◇ x) ◇ x) ◇ (z ◇ y)) ◇ w
equation 36498 := x = (((y ◇ x) ◇ x) ◇ (z ◇ z)) ◇ x
equation 36499 := x = (((y ◇ x) ◇ x) ◇ (z ◇ z)) ◇ y
equation 36500 := x = (((y ◇ x) ◇ x) ◇ (z ◇ z)) ◇ z
equation 36501 := x = (((y ◇ x) ◇ x) ◇ (z ◇ z)) ◇ w
equation 36502 := x = (((y ◇ x) ◇ x) ◇ (z ◇ w)) ◇ x
equation 36503 := x = (((y ◇ x) ◇ x) ◇ (z ◇ w)) ◇ y
equation 36504 := x = (((y ◇ x) ◇ x) ◇ (z ◇ w)) ◇ z
equation 36505 := x = (((y ◇ x) ◇ x) ◇ (z ◇ w)) ◇ w
equation 36506 := x = (((y ◇ x) ◇ x) ◇ (z ◇ w)) ◇ u
equation 36507 := x = (((y ◇ x) ◇ y) ◇ (x ◇ x)) ◇ x
equation 36508 := x = (((y ◇ x) ◇ y) ◇ (x ◇ x)) ◇ y
equation 36509 := x = (((y ◇ x) ◇ y) ◇ (x ◇ x)) ◇ z
equation 36510 := x = (((y ◇ x) ◇ y) ◇ (x ◇ y)) ◇ x
equation 36511 := x = (((y ◇ x) ◇ y) ◇ (x ◇ y)) ◇ y
equation 36512 := x = (((y ◇ x) ◇ y) ◇ (x ◇ y)) ◇ z
equation 36513 := x = (((y ◇ x) ◇ y) ◇ (x ◇ z)) ◇ x
equation 36514 := x = (((y ◇ x) ◇ y) ◇ (x ◇ z)) ◇ y
equation 36515 := x = (((y ◇ x) ◇ y) ◇ (x ◇ z)) ◇ z
equation 36516 := x = (((y ◇ x) ◇ y) ◇ (x ◇ z)) ◇ w
equation 36517 := x = (((y ◇ x) ◇ y) ◇ (y ◇ x)) ◇ x
equation 36518 := x = (((y ◇ x) ◇ y) ◇ (y ◇ x)) ◇ y
equation 36519 := x = (((y ◇ x) ◇ y) ◇ (y ◇ x)) ◇ z
equation 36520 := x = (((y ◇ x) ◇ y) ◇ (y ◇ y)) ◇ x
equation 36521 := x = (((y ◇ x) ◇ y) ◇ (y ◇ y)) ◇ y
equation 36522 := x = (((y ◇ x) ◇ y) ◇ (y ◇ y)) ◇ z
equation 36523 := x = (((y ◇ x) ◇ y) ◇ (y ◇ z)) ◇ x
equation 36524 := x = (((y ◇ x) ◇ y) ◇ (y ◇ z)) ◇ y
equation 36525 := x = (((y ◇ x) ◇ y) ◇ (y ◇ z)) ◇ z
equation 36526 := x = (((y ◇ x) ◇ y) ◇ (y ◇ z)) ◇ w
equation 36527 := x = (((y ◇ x) ◇ y) ◇ (z ◇ x)) ◇ x
equation 36528 := x = (((y ◇ x) ◇ y) ◇ (z ◇ x)) ◇ y
equation 36529 := x = (((y ◇ x) ◇ y) ◇ (z ◇ x)) ◇ z
equation 36530 := x = (((y ◇ x) ◇ y) ◇ (z ◇ x)) ◇ w
equation 36531 := x = (((y ◇ x) ◇ y) ◇ (z ◇ y)) ◇ x
equation 36532 := x = (((y ◇ x) ◇ y) ◇ (z ◇ y)) ◇ y
equation 36533 := x = (((y ◇ x) ◇ y) ◇ (z ◇ y)) ◇ z
equation 36534 := x = (((y ◇ x) ◇ y) ◇ (z ◇ y)) ◇ w
equation 36535 := x = (((y ◇ x) ◇ y) ◇ (z ◇ z)) ◇ x
equation 36536 := x = (((y ◇ x) ◇ y) ◇ (z ◇ z)) ◇ y
equation 36537 := x = (((y ◇ x) ◇ y) ◇ (z ◇ z)) ◇ z
equation 36538 := x = (((y ◇ x) ◇ y) ◇ (z ◇ z)) ◇ w
equation 36539 := x = (((y ◇ x) ◇ y) ◇ (z ◇ w)) ◇ x
equation 36540 := x = (((y ◇ x) ◇ y) ◇ (z ◇ w)) ◇ y
equation 36541 := x = (((y ◇ x) ◇ y) ◇ (z ◇ w)) ◇ z
equation 36542 := x = (((y ◇ x) ◇ y) ◇ (z ◇ w)) ◇ w
equation 36543 := x = (((y ◇ x) ◇ y) ◇ (z ◇ w)) ◇ u
equation 36544 := x = (((y ◇ x) ◇ z) ◇ (x ◇ x)) ◇ x
equation 36545 := x = (((y ◇ x) ◇ z) ◇ (x ◇ x)) ◇ y
equation 36546 := x = (((y ◇ x) ◇ z) ◇ (x ◇ x)) ◇ z
equation 36547 := x = (((y ◇ x) ◇ z) ◇ (x ◇ x)) ◇ w
equation 36548 := x = (((y ◇ x) ◇ z) ◇ (x ◇ y)) ◇ x
equation 36549 := x = (((y ◇ x) ◇ z) ◇ (x ◇ y)) ◇ y
equation 36550 := x = (((y ◇ x) ◇ z) ◇ (x ◇ y)) ◇ z
equation 36551 := x = (((y ◇ x) ◇ z) ◇ (x ◇ y)) ◇ w
equation 36552 := x = (((y ◇ x) ◇ z) ◇ (x ◇ z)) ◇ x
equation 36553 := x = (((y ◇ x) ◇ z) ◇ (x ◇ z)) ◇ y
equation 36554 := x = (((y ◇ x) ◇ z) ◇ (x ◇ z)) ◇ z
equation 36555 := x = (((y ◇ x) ◇ z) ◇ (x ◇ z)) ◇ w
equation 36556 := x = (((y ◇ x) ◇ z) ◇ (x ◇ w)) ◇ x
equation 36557 := x = (((y ◇ x) ◇ z) ◇ (x ◇ w)) ◇ y
equation 36558 := x = (((y ◇ x) ◇ z) ◇ (x ◇ w)) ◇ z
equation 36559 := x = (((y ◇ x) ◇ z) ◇ (x ◇ w)) ◇ w
equation 36560 := x = (((y ◇ x) ◇ z) ◇ (x ◇ w)) ◇ u
equation 36561 := x = (((y ◇ x) ◇ z) ◇ (y ◇ x)) ◇ x
equation 36562 := x = (((y ◇ x) ◇ z) ◇ (y ◇ x)) ◇ y
equation 36563 := x = (((y ◇ x) ◇ z) ◇ (y ◇ x)) ◇ z
equation 36564 := x = (((y ◇ x) ◇ z) ◇ (y ◇ x)) ◇ w
equation 36565 := x = (((y ◇ x) ◇ z) ◇ (y ◇ y)) ◇ x
equation 36566 := x = (((y ◇ x) ◇ z) ◇ (y ◇ y)) ◇ y
equation 36567 := x = (((y ◇ x) ◇ z) ◇ (y ◇ y)) ◇ z
equation 36568 := x = (((y ◇ x) ◇ z) ◇ (y ◇ y)) ◇ w
equation 36569 := x = (((y ◇ x) ◇ z) ◇ (y ◇ z)) ◇ x
equation 36570 := x = (((y ◇ x) ◇ z) ◇ (y ◇ z)) ◇ y
equation 36571 := x = (((y ◇ x) ◇ z) ◇ (y ◇ z)) ◇ z
equation 36572 := x = (((y ◇ x) ◇ z) ◇ (y ◇ z)) ◇ w
equation 36573 := x = (((y ◇ x) ◇ z) ◇ (y ◇ w)) ◇ x
equation 36574 := x = (((y ◇ x) ◇ z) ◇ (y ◇ w)) ◇ y
equation 36575 := x = (((y ◇ x) ◇ z) ◇ (y ◇ w)) ◇ z
equation 36576 := x = (((y ◇ x) ◇ z) ◇ (y ◇ w)) ◇ w
equation 36577 := x = (((y ◇ x) ◇ z) ◇ (y ◇ w)) ◇ u
equation 36578 := x = (((y ◇ x) ◇ z) ◇ (z ◇ x)) ◇ x
equation 36579 := x = (((y ◇ x) ◇ z) ◇ (z ◇ x)) ◇ y
equation 36580 := x = (((y ◇ x) ◇ z) ◇ (z ◇ x)) ◇ z
equation 36581 := x = (((y ◇ x) ◇ z) ◇ (z ◇ x)) ◇ w
equation 36582 := x = (((y ◇ x) ◇ z) ◇ (z ◇ y)) ◇ x
equation 36583 := x = (((y ◇ x) ◇ z) ◇ (z ◇ y)) ◇ y
equation 36584 := x = (((y ◇ x) ◇ z) ◇ (z ◇ y)) ◇ z
equation 36585 := x = (((y ◇ x) ◇ z) ◇ (z ◇ y)) ◇ w
equation 36586 := x = (((y ◇ x) ◇ z) ◇ (z ◇ z)) ◇ x
equation 36587 := x = (((y ◇ x) ◇ z) ◇ (z ◇ z)) ◇ y
equation 36588 := x = (((y ◇ x) ◇ z) ◇ (z ◇ z)) ◇ z
equation 36589 := x = (((y ◇ x) ◇ z) ◇ (z ◇ z)) ◇ w
equation 36590 := x = (((y ◇ x) ◇ z) ◇ (z ◇ w)) ◇ x
equation 36591 := x = (((y ◇ x) ◇ z) ◇ (z ◇ w)) ◇ y
equation 36592 := x = (((y ◇ x) ◇ z) ◇ (z ◇ w)) ◇ z
equation 36593 := x = (((y ◇ x) ◇ z) ◇ (z ◇ w)) ◇ w
equation 36594 := x = (((y ◇ x) ◇ z) ◇ (z ◇ w)) ◇ u
equation 36595 := x = (((y ◇ x) ◇ z) ◇ (w ◇ x)) ◇ x
equation 36596 := x = (((y ◇ x) ◇ z) ◇ (w ◇ x)) ◇ y
equation 36597 := x = (((y ◇ x) ◇ z) ◇ (w ◇ x)) ◇ z
equation 36598 := x = (((y ◇ x) ◇ z) ◇ (w ◇ x)) ◇ w
equation 36599 := x = (((y ◇ x) ◇ z) ◇ (w ◇ x)) ◇ u
equation 36600 := x = (((y ◇ x) ◇ z) ◇ (w ◇ y)) ◇ x
equation 36601 := x = (((y ◇ x) ◇ z) ◇ (w ◇ y)) ◇ y
equation 36602 := x = (((y ◇ x) ◇ z) ◇ (w ◇ y)) ◇ z
equation 36603 := x = (((y ◇ x) ◇ z) ◇ (w ◇ y)) ◇ w
equation 36604 := x = (((y ◇ x) ◇ z) ◇ (w ◇ y)) ◇ u
equation 36605 := x = (((y ◇ x) ◇ z) ◇ (w ◇ z)) ◇ x
equation 36606 := x = (((y ◇ x) ◇ z) ◇ (w ◇ z)) ◇ y
equation 36607 := x = (((y ◇ x) ◇ z) ◇ (w ◇ z)) ◇ z
equation 36608 := x = (((y ◇ x) ◇ z) ◇ (w ◇ z)) ◇ w
equation 36609 := x = (((y ◇ x) ◇ z) ◇ (w ◇ z)) ◇ u
equation 36610 := x = (((y ◇ x) ◇ z) ◇ (w ◇ w)) ◇ x
equation 36611 := x = (((y ◇ x) ◇ z) ◇ (w ◇ w)) ◇ y
equation 36612 := x = (((y ◇ x) ◇ z) ◇ (w ◇ w)) ◇ z
equation 36613 := x = (((y ◇ x) ◇ z) ◇ (w ◇ w)) ◇ w
equation 36614 := x = (((y ◇ x) ◇ z) ◇ (w ◇ w)) ◇ u
equation 36615 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ x
equation 36616 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ y
equation 36617 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ z
equation 36618 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ w
equation 36619 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ u
equation 36620 := x = (((y ◇ x) ◇ z) ◇ (w ◇ u)) ◇ v
equation 36621 := x = (((y ◇ y) ◇ x) ◇ (x ◇ x)) ◇ x
equation 36622 := x = (((y ◇ y) ◇ x) ◇ (x ◇ x)) ◇ y
equation 36623 := x = (((y ◇ y) ◇ x) ◇ (x ◇ x)) ◇ z
equation 36624 := x = (((y ◇ y) ◇ x) ◇ (x ◇ y)) ◇ x
equation 36625 := x = (((y ◇ y) ◇ x) ◇ (x ◇ y)) ◇ y
equation 36626 := x = (((y ◇ y) ◇ x) ◇ (x ◇ y)) ◇ z
equation 36627 := x = (((y ◇ y) ◇ x) ◇ (x ◇ z)) ◇ x
equation 36628 := x = (((y ◇ y) ◇ x) ◇ (x ◇ z)) ◇ y
equation 36629 := x = (((y ◇ y) ◇ x) ◇ (x ◇ z)) ◇ z
equation 36630 := x = (((y ◇ y) ◇ x) ◇ (x ◇ z)) ◇ w
equation 36631 := x = (((y ◇ y) ◇ x) ◇ (y ◇ x)) ◇ x
equation 36632 := x = (((y ◇ y) ◇ x) ◇ (y ◇ x)) ◇ y
equation 36633 := x = (((y ◇ y) ◇ x) ◇ (y ◇ x)) ◇ z
equation 36634 := x = (((y ◇ y) ◇ x) ◇ (y ◇ y)) ◇ x
equation 36635 := x = (((y ◇ y) ◇ x) ◇ (y ◇ y)) ◇ y
equation 36636 := x = (((y ◇ y) ◇ x) ◇ (y ◇ y)) ◇ z
equation 36637 := x = (((y ◇ y) ◇ x) ◇ (y ◇ z)) ◇ x
equation 36638 := x = (((y ◇ y) ◇ x) ◇ (y ◇ z)) ◇ y
equation 36639 := x = (((y ◇ y) ◇ x) ◇ (y ◇ z)) ◇ z
equation 36640 := x = (((y ◇ y) ◇ x) ◇ (y ◇ z)) ◇ w
equation 36641 := x = (((y ◇ y) ◇ x) ◇ (z ◇ x)) ◇ x
equation 36642 := x = (((y ◇ y) ◇ x) ◇ (z ◇ x)) ◇ y
equation 36643 := x = (((y ◇ y) ◇ x) ◇ (z ◇ x)) ◇ z
equation 36644 := x = (((y ◇ y) ◇ x) ◇ (z ◇ x)) ◇ w
equation 36645 := x = (((y ◇ y) ◇ x) ◇ (z ◇ y)) ◇ x
equation 36646 := x = (((y ◇ y) ◇ x) ◇ (z ◇ y)) ◇ y
equation 36647 := x = (((y ◇ y) ◇ x) ◇ (z ◇ y)) ◇ z
equation 36648 := x = (((y ◇ y) ◇ x) ◇ (z ◇ y)) ◇ w
equation 36649 := x = (((y ◇ y) ◇ x) ◇ (z ◇ z)) ◇ x
equation 36650 := x = (((y ◇ y) ◇ x) ◇ (z ◇ z)) ◇ y
equation 36651 := x = (((y ◇ y) ◇ x) ◇ (z ◇ z)) ◇ z
equation 36652 := x = (((y ◇ y) ◇ x) ◇ (z ◇ z)) ◇ w
equation 36653 := x = (((y ◇ y) ◇ x) ◇ (z ◇ w)) ◇ x
equation 36654 := x = (((y ◇ y) ◇ x) ◇ (z ◇ w)) ◇ y
equation 36655 := x = (((y ◇ y) ◇ x) ◇ (z ◇ w)) ◇ z
equation 36656 := x = (((y ◇ y) ◇ x) ◇ (z ◇ w)) ◇ w
equation 36657 := x = (((y ◇ y) ◇ x) ◇ (z ◇ w)) ◇ u
equation 36658 := x = (((y ◇ y) ◇ y) ◇ (x ◇ x)) ◇ x
equation 36659 := x = (((y ◇ y) ◇ y) ◇ (x ◇ x)) ◇ y
equation 36660 := x = (((y ◇ y) ◇ y) ◇ (x ◇ x)) ◇ z
equation 36661 := x = (((y ◇ y) ◇ y) ◇ (x ◇ y)) ◇ x
equation 36662 := x = (((y ◇ y) ◇ y) ◇ (x ◇ y)) ◇ y
equation 36663 := x = (((y ◇ y) ◇ y) ◇ (x ◇ y)) ◇ z
equation 36664 := x = (((y ◇ y) ◇ y) ◇ (x ◇ z)) ◇ x
equation 36665 := x = (((y ◇ y) ◇ y) ◇ (x ◇ z)) ◇ y
equation 36666 := x = (((y ◇ y) ◇ y) ◇ (x ◇ z)) ◇ z
equation 36667 := x = (((y ◇ y) ◇ y) ◇ (x ◇ z)) ◇ w
equation 36668 := x = (((y ◇ y) ◇ y) ◇ (y ◇ x)) ◇ x
equation 36669 := x = (((y ◇ y) ◇ y) ◇ (y ◇ x)) ◇ y
equation 36670 := x = (((y ◇ y) ◇ y) ◇ (y ◇ x)) ◇ z
equation 36671 := x = (((y ◇ y) ◇ y) ◇ (y ◇ y)) ◇ x
equation 36672 := x = (((y ◇ y) ◇ y) ◇ (y ◇ y)) ◇ y
equation 36673 := x = (((y ◇ y) ◇ y) ◇ (y ◇ y)) ◇ z
equation 36674 := x = (((y ◇ y) ◇ y) ◇ (y ◇ z)) ◇ x
equation 36675 := x = (((y ◇ y) ◇ y) ◇ (y ◇ z)) ◇ y
equation 36676 := x = (((y ◇ y) ◇ y) ◇ (y ◇ z)) ◇ z
equation 36677 := x = (((y ◇ y) ◇ y) ◇ (y ◇ z)) ◇ w
equation 36678 := x = (((y ◇ y) ◇ y) ◇ (z ◇ x)) ◇ x
equation 36679 := x = (((y ◇ y) ◇ y) ◇ (z ◇ x)) ◇ y
equation 36680 := x = (((y ◇ y) ◇ y) ◇ (z ◇ x)) ◇ z
equation 36681 := x = (((y ◇ y) ◇ y) ◇ (z ◇ x)) ◇ w
equation 36682 := x = (((y ◇ y) ◇ y) ◇ (z ◇ y)) ◇ x
equation 36683 := x = (((y ◇ y) ◇ y) ◇ (z ◇ y)) ◇ y
equation 36684 := x = (((y ◇ y) ◇ y) ◇ (z ◇ y)) ◇ z
equation 36685 := x = (((y ◇ y) ◇ y) ◇ (z ◇ y)) ◇ w
equation 36686 := x = (((y ◇ y) ◇ y) ◇ (z ◇ z)) ◇ x
equation 36687 := x = (((y ◇ y) ◇ y) ◇ (z ◇ z)) ◇ y
equation 36688 := x = (((y ◇ y) ◇ y) ◇ (z ◇ z)) ◇ z
equation 36689 := x = (((y ◇ y) ◇ y) ◇ (z ◇ z)) ◇ w
equation 36690 := x = (((y ◇ y) ◇ y) ◇ (z ◇ w)) ◇ x
equation 36691 := x = (((y ◇ y) ◇ y) ◇ (z ◇ w)) ◇ y
equation 36692 := x = (((y ◇ y) ◇ y) ◇ (z ◇ w)) ◇ z
equation 36693 := x = (((y ◇ y) ◇ y) ◇ (z ◇ w)) ◇ w
equation 36694 := x = (((y ◇ y) ◇ y) ◇ (z ◇ w)) ◇ u
equation 36695 := x = (((y ◇ y) ◇ z) ◇ (x ◇ x)) ◇ x
equation 36696 := x = (((y ◇ y) ◇ z) ◇ (x ◇ x)) ◇ y
equation 36697 := x = (((y ◇ y) ◇ z) ◇ (x ◇ x)) ◇ z
equation 36698 := x = (((y ◇ y) ◇ z) ◇ (x ◇ x)) ◇ w
equation 36699 := x = (((y ◇ y) ◇ z) ◇ (x ◇ y)) ◇ x
equation 36700 := x = (((y ◇ y) ◇ z) ◇ (x ◇ y)) ◇ y
equation 36701 := x = (((y ◇ y) ◇ z) ◇ (x ◇ y)) ◇ z
equation 36702 := x = (((y ◇ y) ◇ z) ◇ (x ◇ y)) ◇ w
equation 36703 := x = (((y ◇ y) ◇ z) ◇ (x ◇ z)) ◇ x
equation 36704 := x = (((y ◇ y) ◇ z) ◇ (x ◇ z)) ◇ y
equation 36705 := x = (((y ◇ y) ◇ z) ◇ (x ◇ z)) ◇ z
equation 36706 := x = (((y ◇ y) ◇ z) ◇ (x ◇ z)) ◇ w
equation 36707 := x = (((y ◇ y) ◇ z) ◇ (x ◇ w)) ◇ x
equation 36708 := x = (((y ◇ y) ◇ z) ◇ (x ◇ w)) ◇ y
equation 36709 := x = (((y ◇ y) ◇ z) ◇ (x ◇ w)) ◇ z
equation 36710 := x = (((y ◇ y) ◇ z) ◇ (x ◇ w)) ◇ w
equation 36711 := x = (((y ◇ y) ◇ z) ◇ (x ◇ w)) ◇ u
equation 36712 := x = (((y ◇ y) ◇ z) ◇ (y ◇ x)) ◇ x
equation 36713 := x = (((y ◇ y) ◇ z) ◇ (y ◇ x)) ◇ y
equation 36714 := x = (((y ◇ y) ◇ z) ◇ (y ◇ x)) ◇ z
equation 36715 := x = (((y ◇ y) ◇ z) ◇ (y ◇ x)) ◇ w
equation 36716 := x = (((y ◇ y) ◇ z) ◇ (y ◇ y)) ◇ x
equation 36717 := x = (((y ◇ y) ◇ z) ◇ (y ◇ y)) ◇ y
equation 36718 := x = (((y ◇ y) ◇ z) ◇ (y ◇ y)) ◇ z
equation 36719 := x = (((y ◇ y) ◇ z) ◇ (y ◇ y)) ◇ w
equation 36720 := x = (((y ◇ y) ◇ z) ◇ (y ◇ z)) ◇ x
equation 36721 := x = (((y ◇ y) ◇ z) ◇ (y ◇ z)) ◇ y
equation 36722 := x = (((y ◇ y) ◇ z) ◇ (y ◇ z)) ◇ z
equation 36723 := x = (((y ◇ y) ◇ z) ◇ (y ◇ z)) ◇ w
equation 36724 := x = (((y ◇ y) ◇ z) ◇ (y ◇ w)) ◇ x
equation 36725 := x = (((y ◇ y) ◇ z) ◇ (y ◇ w)) ◇ y
equation 36726 := x = (((y ◇ y) ◇ z) ◇ (y ◇ w)) ◇ z
equation 36727 := x = (((y ◇ y) ◇ z) ◇ (y ◇ w)) ◇ w
equation 36728 := x = (((y ◇ y) ◇ z) ◇ (y ◇ w)) ◇ u
equation 36729 := x = (((y ◇ y) ◇ z) ◇ (z ◇ x)) ◇ x
equation 36730 := x = (((y ◇ y) ◇ z) ◇ (z ◇ x)) ◇ y
equation 36731 := x = (((y ◇ y) ◇ z) ◇ (z ◇ x)) ◇ z
equation 36732 := x = (((y ◇ y) ◇ z) ◇ (z ◇ x)) ◇ w
equation 36733 := x = (((y ◇ y) ◇ z) ◇ (z ◇ y)) ◇ x
equation 36734 := x = (((y ◇ y) ◇ z) ◇ (z ◇ y)) ◇ y
equation 36735 := x = (((y ◇ y) ◇ z) ◇ (z ◇ y)) ◇ z
equation 36736 := x = (((y ◇ y) ◇ z) ◇ (z ◇ y)) ◇ w
equation 36737 := x = (((y ◇ y) ◇ z) ◇ (z ◇ z)) ◇ x
equation 36738 := x = (((y ◇ y) ◇ z) ◇ (z ◇ z)) ◇ y
equation 36739 := x = (((y ◇ y) ◇ z) ◇ (z ◇ z)) ◇ z
equation 36740 := x = (((y ◇ y) ◇ z) ◇ (z ◇ z)) ◇ w
equation 36741 := x = (((y ◇ y) ◇ z) ◇ (z ◇ w)) ◇ x
equation 36742 := x = (((y ◇ y) ◇ z) ◇ (z ◇ w)) ◇ y
equation 36743 := x = (((y ◇ y) ◇ z) ◇ (z ◇ w)) ◇ z
equation 36744 := x = (((y ◇ y) ◇ z) ◇ (z ◇ w)) ◇ w
equation 36745 := x = (((y ◇ y) ◇ z) ◇ (z ◇ w)) ◇ u
equation 36746 := x = (((y ◇ y) ◇ z) ◇ (w ◇ x)) ◇ x
equation 36747 := x = (((y ◇ y) ◇ z) ◇ (w ◇ x)) ◇ y
equation 36748 := x = (((y ◇ y) ◇ z) ◇ (w ◇ x)) ◇ z
equation 36749 := x = (((y ◇ y) ◇ z) ◇ (w ◇ x)) ◇ w
equation 36750 := x = (((y ◇ y) ◇ z) ◇ (w ◇ x)) ◇ u
equation 36751 := x = (((y ◇ y) ◇ z) ◇ (w ◇ y)) ◇ x
equation 36752 := x = (((y ◇ y) ◇ z) ◇ (w ◇ y)) ◇ y
equation 36753 := x = (((y ◇ y) ◇ z) ◇ (w ◇ y)) ◇ z
equation 36754 := x = (((y ◇ y) ◇ z) ◇ (w ◇ y)) ◇ w
equation 36755 := x = (((y ◇ y) ◇ z) ◇ (w ◇ y)) ◇ u
equation 36756 := x = (((y ◇ y) ◇ z) ◇ (w ◇ z)) ◇ x
equation 36757 := x = (((y ◇ y) ◇ z) ◇ (w ◇ z)) ◇ y
equation 36758 := x = (((y ◇ y) ◇ z) ◇ (w ◇ z)) ◇ z
equation 36759 := x = (((y ◇ y) ◇ z) ◇ (w ◇ z)) ◇ w
equation 36760 := x = (((y ◇ y) ◇ z) ◇ (w ◇ z)) ◇ u
equation 36761 := x = (((y ◇ y) ◇ z) ◇ (w ◇ w)) ◇ x
equation 36762 := x = (((y ◇ y) ◇ z) ◇ (w ◇ w)) ◇ y
equation 36763 := x = (((y ◇ y) ◇ z) ◇ (w ◇ w)) ◇ z
equation 36764 := x = (((y ◇ y) ◇ z) ◇ (w ◇ w)) ◇ w
equation 36765 := x = (((y ◇ y) ◇ z) ◇ (w ◇ w)) ◇ u
equation 36766 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ x
equation 36767 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ y
equation 36768 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ z
equation 36769 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ w
equation 36770 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ u
equation 36771 := x = (((y ◇ y) ◇ z) ◇ (w ◇ u)) ◇ v
equation 36772 := x = (((y ◇ z) ◇ x) ◇ (x ◇ x)) ◇ x
equation 36773 := x = (((y ◇ z) ◇ x) ◇ (x ◇ x)) ◇ y
equation 36774 := x = (((y ◇ z) ◇ x) ◇ (x ◇ x)) ◇ z
equation 36775 := x = (((y ◇ z) ◇ x) ◇ (x ◇ x)) ◇ w
equation 36776 := x = (((y ◇ z) ◇ x) ◇ (x ◇ y)) ◇ x
equation 36777 := x = (((y ◇ z) ◇ x) ◇ (x ◇ y)) ◇ y
equation 36778 := x = (((y ◇ z) ◇ x) ◇ (x ◇ y)) ◇ z
equation 36779 := x = (((y ◇ z) ◇ x) ◇ (x ◇ y)) ◇ w
equation 36780 := x = (((y ◇ z) ◇ x) ◇ (x ◇ z)) ◇ x
equation 36781 := x = (((y ◇ z) ◇ x) ◇ (x ◇ z)) ◇ y
equation 36782 := x = (((y ◇ z) ◇ x) ◇ (x ◇ z)) ◇ z
equation 36783 := x = (((y ◇ z) ◇ x) ◇ (x ◇ z)) ◇ w
equation 36784 := x = (((y ◇ z) ◇ x) ◇ (x ◇ w)) ◇ x
equation 36785 := x = (((y ◇ z) ◇ x) ◇ (x ◇ w)) ◇ y
equation 36786 := x = (((y ◇ z) ◇ x) ◇ (x ◇ w)) ◇ z
equation 36787 := x = (((y ◇ z) ◇ x) ◇ (x ◇ w)) ◇ w
equation 36788 := x = (((y ◇ z) ◇ x) ◇ (x ◇ w)) ◇ u
equation 36789 := x = (((y ◇ z) ◇ x) ◇ (y ◇ x)) ◇ x
equation 36790 := x = (((y ◇ z) ◇ x) ◇ (y ◇ x)) ◇ y
equation 36791 := x = (((y ◇ z) ◇ x) ◇ (y ◇ x)) ◇ z
equation 36792 := x = (((y ◇ z) ◇ x) ◇ (y ◇ x)) ◇ w
equation 36793 := x = (((y ◇ z) ◇ x) ◇ (y ◇ y)) ◇ x
equation 36794 := x = (((y ◇ z) ◇ x) ◇ (y ◇ y)) ◇ y
equation 36795 := x = (((y ◇ z) ◇ x) ◇ (y ◇ y)) ◇ z
equation 36796 := x = (((y ◇ z) ◇ x) ◇ (y ◇ y)) ◇ w
equation 36797 := x = (((y ◇ z) ◇ x) ◇ (y ◇ z)) ◇ x
equation 36798 := x = (((y ◇ z) ◇ x) ◇ (y ◇ z)) ◇ y
equation 36799 := x = (((y ◇ z) ◇ x) ◇ (y ◇ z)) ◇ z
equation 36800 := x = (((y ◇ z) ◇ x) ◇ (y ◇ z)) ◇ w
equation 36801 := x = (((y ◇ z) ◇ x) ◇ (y ◇ w)) ◇ x
equation 36802 := x = (((y ◇ z) ◇ x) ◇ (y ◇ w)) ◇ y
equation 36803 := x = (((y ◇ z) ◇ x) ◇ (y ◇ w)) ◇ z
equation 36804 := x = (((y ◇ z) ◇ x) ◇ (y ◇ w)) ◇ w
equation 36805 := x = (((y ◇ z) ◇ x) ◇ (y ◇ w)) ◇ u
equation 36806 := x = (((y ◇ z) ◇ x) ◇ (z ◇ x)) ◇ x
equation 36807 := x = (((y ◇ z) ◇ x) ◇ (z ◇ x)) ◇ y
equation 36808 := x = (((y ◇ z) ◇ x) ◇ (z ◇ x)) ◇ z
equation 36809 := x = (((y ◇ z) ◇ x) ◇ (z ◇ x)) ◇ w
equation 36810 := x = (((y ◇ z) ◇ x) ◇ (z ◇ y)) ◇ x
equation 36811 := x = (((y ◇ z) ◇ x) ◇ (z ◇ y)) ◇ y
equation 36812 := x = (((y ◇ z) ◇ x) ◇ (z ◇ y)) ◇ z
equation 36813 := x = (((y ◇ z) ◇ x) ◇ (z ◇ y)) ◇ w
equation 36814 := x = (((y ◇ z) ◇ x) ◇ (z ◇ z)) ◇ x
equation 36815 := x = (((y ◇ z) ◇ x) ◇ (z ◇ z)) ◇ y
equation 36816 := x = (((y ◇ z) ◇ x) ◇ (z ◇ z)) ◇ z
equation 36817 := x = (((y ◇ z) ◇ x) ◇ (z ◇ z)) ◇ w
equation 36818 := x = (((y ◇ z) ◇ x) ◇ (z ◇ w)) ◇ x
equation 36819 := x = (((y ◇ z) ◇ x) ◇ (z ◇ w)) ◇ y
equation 36820 := x = (((y ◇ z) ◇ x) ◇ (z ◇ w)) ◇ z
equation 36821 := x = (((y ◇ z) ◇ x) ◇ (z ◇ w)) ◇ w
equation 36822 := x = (((y ◇ z) ◇ x) ◇ (z ◇ w)) ◇ u
equation 36823 := x = (((y ◇ z) ◇ x) ◇ (w ◇ x)) ◇ x
equation 36824 := x = (((y ◇ z) ◇ x) ◇ (w ◇ x)) ◇ y
equation 36825 := x = (((y ◇ z) ◇ x) ◇ (w ◇ x)) ◇ z
equation 36826 := x = (((y ◇ z) ◇ x) ◇ (w ◇ x)) ◇ w
equation 36827 := x = (((y ◇ z) ◇ x) ◇ (w ◇ x)) ◇ u
equation 36828 := x = (((y ◇ z) ◇ x) ◇ (w ◇ y)) ◇ x
equation 36829 := x = (((y ◇ z) ◇ x) ◇ (w ◇ y)) ◇ y
equation 36830 := x = (((y ◇ z) ◇ x) ◇ (w ◇ y)) ◇ z
equation 36831 := x = (((y ◇ z) ◇ x) ◇ (w ◇ y)) ◇ w
equation 36832 := x = (((y ◇ z) ◇ x) ◇ (w ◇ y)) ◇ u
equation 36833 := x = (((y ◇ z) ◇ x) ◇ (w ◇ z)) ◇ x
equation 36834 := x = (((y ◇ z) ◇ x) ◇ (w ◇ z)) ◇ y
equation 36835 := x = (((y ◇ z) ◇ x) ◇ (w ◇ z)) ◇ z
equation 36836 := x = (((y ◇ z) ◇ x) ◇ (w ◇ z)) ◇ w
equation 36837 := x = (((y ◇ z) ◇ x) ◇ (w ◇ z)) ◇ u
equation 36838 := x = (((y ◇ z) ◇ x) ◇ (w ◇ w)) ◇ x
equation 36839 := x = (((y ◇ z) ◇ x) ◇ (w ◇ w)) ◇ y
equation 36840 := x = (((y ◇ z) ◇ x) ◇ (w ◇ w)) ◇ z
equation 36841 := x = (((y ◇ z) ◇ x) ◇ (w ◇ w)) ◇ w
equation 36842 := x = (((y ◇ z) ◇ x) ◇ (w ◇ w)) ◇ u
equation 36843 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ x
equation 36844 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ y
equation 36845 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ z
equation 36846 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ w
equation 36847 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ u
equation 36848 := x = (((y ◇ z) ◇ x) ◇ (w ◇ u)) ◇ v
equation 36849 := x = (((y ◇ z) ◇ y) ◇ (x ◇ x)) ◇ x
equation 36850 := x = (((y ◇ z) ◇ y) ◇ (x ◇ x)) ◇ y
equation 36851 := x = (((y ◇ z) ◇ y) ◇ (x ◇ x)) ◇ z
equation 36852 := x = (((y ◇ z) ◇ y) ◇ (x ◇ x)) ◇ w
equation 36853 := x = (((y ◇ z) ◇ y) ◇ (x ◇ y)) ◇ x
equation 36854 := x = (((y ◇ z) ◇ y) ◇ (x ◇ y)) ◇ y
equation 36855 := x = (((y ◇ z) ◇ y) ◇ (x ◇ y)) ◇ z
equation 36856 := x = (((y ◇ z) ◇ y) ◇ (x ◇ y)) ◇ w
equation 36857 := x = (((y ◇ z) ◇ y) ◇ (x ◇ z)) ◇ x
equation 36858 := x = (((y ◇ z) ◇ y) ◇ (x ◇ z)) ◇ y
equation 36859 := x = (((y ◇ z) ◇ y) ◇ (x ◇ z)) ◇ z
equation 36860 := x = (((y ◇ z) ◇ y) ◇ (x ◇ z)) ◇ w
equation 36861 := x = (((y ◇ z) ◇ y) ◇ (x ◇ w)) ◇ x
equation 36862 := x = (((y ◇ z) ◇ y) ◇ (x ◇ w)) ◇ y
equation 36863 := x = (((y ◇ z) ◇ y) ◇ (x ◇ w)) ◇ z
equation 36864 := x = (((y ◇ z) ◇ y) ◇ (x ◇ w)) ◇ w
equation 36865 := x = (((y ◇ z) ◇ y) ◇ (x ◇ w)) ◇ u
equation 36866 := x = (((y ◇ z) ◇ y) ◇ (y ◇ x)) ◇ x
equation 36867 := x = (((y ◇ z) ◇ y) ◇ (y ◇ x)) ◇ y
equation 36868 := x = (((y ◇ z) ◇ y) ◇ (y ◇ x)) ◇ z
equation 36869 := x = (((y ◇ z) ◇ y) ◇ (y ◇ x)) ◇ w
equation 36870 := x = (((y ◇ z) ◇ y) ◇ (y ◇ y)) ◇ x
equation 36871 := x = (((y ◇ z) ◇ y) ◇ (y ◇ y)) ◇ y
equation 36872 := x = (((y ◇ z) ◇ y) ◇ (y ◇ y)) ◇ z
equation 36873 := x = (((y ◇ z) ◇ y) ◇ (y ◇ y)) ◇ w
equation 36874 := x = (((y ◇ z) ◇ y) ◇ (y ◇ z)) ◇ x
equation 36875 := x = (((y ◇ z) ◇ y) ◇ (y ◇ z)) ◇ y
equation 36876 := x = (((y ◇ z) ◇ y) ◇ (y ◇ z)) ◇ z
equation 36877 := x = (((y ◇ z) ◇ y) ◇ (y ◇ z)) ◇ w
equation 36878 := x = (((y ◇ z) ◇ y) ◇ (y ◇ w)) ◇ x
equation 36879 := x = (((y ◇ z) ◇ y) ◇ (y ◇ w)) ◇ y
equation 36880 := x = (((y ◇ z) ◇ y) ◇ (y ◇ w)) ◇ z
equation 36881 := x = (((y ◇ z) ◇ y) ◇ (y ◇ w)) ◇ w
equation 36882 := x = (((y ◇ z) ◇ y) ◇ (y ◇ w)) ◇ u
equation 36883 := x = (((y ◇ z) ◇ y) ◇ (z ◇ x)) ◇ x
equation 36884 := x = (((y ◇ z) ◇ y) ◇ (z ◇ x)) ◇ y
equation 36885 := x = (((y ◇ z) ◇ y) ◇ (z ◇ x)) ◇ z
equation 36886 := x = (((y ◇ z) ◇ y) ◇ (z ◇ x)) ◇ w
equation 36887 := x = (((y ◇ z) ◇ y) ◇ (z ◇ y)) ◇ x
equation 36888 := x = (((y ◇ z) ◇ y) ◇ (z ◇ y)) ◇ y
equation 36889 := x = (((y ◇ z) ◇ y) ◇ (z ◇ y)) ◇ z
equation 36890 := x = (((y ◇ z) ◇ y) ◇ (z ◇ y)) ◇ w
equation 36891 := x = (((y ◇ z) ◇ y) ◇ (z ◇ z)) ◇ x
equation 36892 := x = (((y ◇ z) ◇ y) ◇ (z ◇ z)) ◇ y
equation 36893 := x = (((y ◇ z) ◇ y) ◇ (z ◇ z)) ◇ z
equation 36894 := x = (((y ◇ z) ◇ y) ◇ (z ◇ z)) ◇ w
equation 36895 := x = (((y ◇ z) ◇ y) ◇ (z ◇ w)) ◇ x
equation 36896 := x = (((y ◇ z) ◇ y) ◇ (z ◇ w)) ◇ y
equation 36897 := x = (((y ◇ z) ◇ y) ◇ (z ◇ w)) ◇ z
equation 36898 := x = (((y ◇ z) ◇ y) ◇ (z ◇ w)) ◇ w
equation 36899 := x = (((y ◇ z) ◇ y) ◇ (z ◇ w)) ◇ u
equation 36900 := x = (((y ◇ z) ◇ y) ◇ (w ◇ x)) ◇ x
equation 36901 := x = (((y ◇ z) ◇ y) ◇ (w ◇ x)) ◇ y
equation 36902 := x = (((y ◇ z) ◇ y) ◇ (w ◇ x)) ◇ z
equation 36903 := x = (((y ◇ z) ◇ y) ◇ (w ◇ x)) ◇ w
equation 36904 := x = (((y ◇ z) ◇ y) ◇ (w ◇ x)) ◇ u
equation 36905 := x = (((y ◇ z) ◇ y) ◇ (w ◇ y)) ◇ x
equation 36906 := x = (((y ◇ z) ◇ y) ◇ (w ◇ y)) ◇ y
equation 36907 := x = (((y ◇ z) ◇ y) ◇ (w ◇ y)) ◇ z
equation 36908 := x = (((y ◇ z) ◇ y) ◇ (w ◇ y)) ◇ w
equation 36909 := x = (((y ◇ z) ◇ y) ◇ (w ◇ y)) ◇ u
equation 36910 := x = (((y ◇ z) ◇ y) ◇ (w ◇ z)) ◇ x
equation 36911 := x = (((y ◇ z) ◇ y) ◇ (w ◇ z)) ◇ y
equation 36912 := x = (((y ◇ z) ◇ y) ◇ (w ◇ z)) ◇ z
equation 36913 := x = (((y ◇ z) ◇ y) ◇ (w ◇ z)) ◇ w
equation 36914 := x = (((y ◇ z) ◇ y) ◇ (w ◇ z)) ◇ u
equation 36915 := x = (((y ◇ z) ◇ y) ◇ (w ◇ w)) ◇ x
equation 36916 := x = (((y ◇ z) ◇ y) ◇ (w ◇ w)) ◇ y
equation 36917 := x = (((y ◇ z) ◇ y) ◇ (w ◇ w)) ◇ z
equation 36918 := x = (((y ◇ z) ◇ y) ◇ (w ◇ w)) ◇ w
equation 36919 := x = (((y ◇ z) ◇ y) ◇ (w ◇ w)) ◇ u
equation 36920 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ x
equation 36921 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ y
equation 36922 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ z
equation 36923 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ w
equation 36924 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ u
equation 36925 := x = (((y ◇ z) ◇ y) ◇ (w ◇ u)) ◇ v
equation 36926 := x = (((y ◇ z) ◇ z) ◇ (x ◇ x)) ◇ x
equation 36927 := x = (((y ◇ z) ◇ z) ◇ (x ◇ x)) ◇ y
equation 36928 := x = (((y ◇ z) ◇ z) ◇ (x ◇ x)) ◇ z
equation 36929 := x = (((y ◇ z) ◇ z) ◇ (x ◇ x)) ◇ w
equation 36930 := x = (((y ◇ z) ◇ z) ◇ (x ◇ y)) ◇ x
equation 36931 := x = (((y ◇ z) ◇ z) ◇ (x ◇ y)) ◇ y
equation 36932 := x = (((y ◇ z) ◇ z) ◇ (x ◇ y)) ◇ z
equation 36933 := x = (((y ◇ z) ◇ z) ◇ (x ◇ y)) ◇ w
equation 36934 := x = (((y ◇ z) ◇ z) ◇ (x ◇ z)) ◇ x
equation 36935 := x = (((y ◇ z) ◇ z) ◇ (x ◇ z)) ◇ y
equation 36936 := x = (((y ◇ z) ◇ z) ◇ (x ◇ z)) ◇ z
equation 36937 := x = (((y ◇ z) ◇ z) ◇ (x ◇ z)) ◇ w
equation 36938 := x = (((y ◇ z) ◇ z) ◇ (x ◇ w)) ◇ x
equation 36939 := x = (((y ◇ z) ◇ z) ◇ (x ◇ w)) ◇ y
equation 36940 := x = (((y ◇ z) ◇ z) ◇ (x ◇ w)) ◇ z
equation 36941 := x = (((y ◇ z) ◇ z) ◇ (x ◇ w)) ◇ w
equation 36942 := x = (((y ◇ z) ◇ z) ◇ (x ◇ w)) ◇ u
equation 36943 := x = (((y ◇ z) ◇ z) ◇ (y ◇ x)) ◇ x
equation 36944 := x = (((y ◇ z) ◇ z) ◇ (y ◇ x)) ◇ y
equation 36945 := x = (((y ◇ z) ◇ z) ◇ (y ◇ x)) ◇ z
equation 36946 := x = (((y ◇ z) ◇ z) ◇ (y ◇ x)) ◇ w
equation 36947 := x = (((y ◇ z) ◇ z) ◇ (y ◇ y)) ◇ x
equation 36948 := x = (((y ◇ z) ◇ z) ◇ (y ◇ y)) ◇ y
equation 36949 := x = (((y ◇ z) ◇ z) ◇ (y ◇ y)) ◇ z
equation 36950 := x = (((y ◇ z) ◇ z) ◇ (y ◇ y)) ◇ w
equation 36951 := x = (((y ◇ z) ◇ z) ◇ (y ◇ z)) ◇ x
equation 36952 := x = (((y ◇ z) ◇ z) ◇ (y ◇ z)) ◇ y
equation 36953 := x = (((y ◇ z) ◇ z) ◇ (y ◇ z)) ◇ z
equation 36954 := x = (((y ◇ z) ◇ z) ◇ (y ◇ z)) ◇ w
equation 36955 := x = (((y ◇ z) ◇ z) ◇ (y ◇ w)) ◇ x
equation 36956 := x = (((y ◇ z) ◇ z) ◇ (y ◇ w)) ◇ y
equation 36957 := x = (((y ◇ z) ◇ z) ◇ (y ◇ w)) ◇ z
equation 36958 := x = (((y ◇ z) ◇ z) ◇ (y ◇ w)) ◇ w
equation 36959 := x = (((y ◇ z) ◇ z) ◇ (y ◇ w)) ◇ u
equation 36960 := x = (((y ◇ z) ◇ z) ◇ (z ◇ x)) ◇ x
equation 36961 := x = (((y ◇ z) ◇ z) ◇ (z ◇ x)) ◇ y
equation 36962 := x = (((y ◇ z) ◇ z) ◇ (z ◇ x)) ◇ z
equation 36963 := x = (((y ◇ z) ◇ z) ◇ (z ◇ x)) ◇ w
equation 36964 := x = (((y ◇ z) ◇ z) ◇ (z ◇ y)) ◇ x
equation 36965 := x = (((y ◇ z) ◇ z) ◇ (z ◇ y)) ◇ y
equation 36966 := x = (((y ◇ z) ◇ z) ◇ (z ◇ y)) ◇ z
equation 36967 := x = (((y ◇ z) ◇ z) ◇ (z ◇ y)) ◇ w
equation 36968 := x = (((y ◇ z) ◇ z) ◇ (z ◇ z)) ◇ x
equation 36969 := x = (((y ◇ z) ◇ z) ◇ (z ◇ z)) ◇ y
equation 36970 := x = (((y ◇ z) ◇ z) ◇ (z ◇ z)) ◇ z
equation 36971 := x = (((y ◇ z) ◇ z) ◇ (z ◇ z)) ◇ w
equation 36972 := x = (((y ◇ z) ◇ z) ◇ (z ◇ w)) ◇ x
equation 36973 := x = (((y ◇ z) ◇ z) ◇ (z ◇ w)) ◇ y
equation 36974 := x = (((y ◇ z) ◇ z) ◇ (z ◇ w)) ◇ z
equation 36975 := x = (((y ◇ z) ◇ z) ◇ (z ◇ w)) ◇ w
equation 36976 := x = (((y ◇ z) ◇ z) ◇ (z ◇ w)) ◇ u
equation 36977 := x = (((y ◇ z) ◇ z) ◇ (w ◇ x)) ◇ x
equation 36978 := x = (((y ◇ z) ◇ z) ◇ (w ◇ x)) ◇ y
equation 36979 := x = (((y ◇ z) ◇ z) ◇ (w ◇ x)) ◇ z
equation 36980 := x = (((y ◇ z) ◇ z) ◇ (w ◇ x)) ◇ w
equation 36981 := x = (((y ◇ z) ◇ z) ◇ (w ◇ x)) ◇ u
equation 36982 := x = (((y ◇ z) ◇ z) ◇ (w ◇ y)) ◇ x
equation 36983 := x = (((y ◇ z) ◇ z) ◇ (w ◇ y)) ◇ y
equation 36984 := x = (((y ◇ z) ◇ z) ◇ (w ◇ y)) ◇ z
equation 36985 := x = (((y ◇ z) ◇ z) ◇ (w ◇ y)) ◇ w
equation 36986 := x = (((y ◇ z) ◇ z) ◇ (w ◇ y)) ◇ u
equation 36987 := x = (((y ◇ z) ◇ z) ◇ (w ◇ z)) ◇ x
equation 36988 := x = (((y ◇ z) ◇ z) ◇ (w ◇ z)) ◇ y
equation 36989 := x = (((y ◇ z) ◇ z) ◇ (w ◇ z)) ◇ z
equation 36990 := x = (((y ◇ z) ◇ z) ◇ (w ◇ z)) ◇ w
equation 36991 := x = (((y ◇ z) ◇ z) ◇ (w ◇ z)) ◇ u
equation 36992 := x = (((y ◇ z) ◇ z) ◇ (w ◇ w)) ◇ x
equation 36993 := x = (((y ◇ z) ◇ z) ◇ (w ◇ w)) ◇ y
equation 36994 := x = (((y ◇ z) ◇ z) ◇ (w ◇ w)) ◇ z
equation 36995 := x = (((y ◇ z) ◇ z) ◇ (w ◇ w)) ◇ w
equation 36996 := x = (((y ◇ z) ◇ z) ◇ (w ◇ w)) ◇ u
equation 36997 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ x
equation 36998 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ y
equation 36999 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ z
