import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 38000-38999 -/

equation 38000 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ u
equation 38001 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ v
equation 38002 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ x
equation 38003 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ y
equation 38004 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ z
equation 38005 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ w
equation 38006 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ u
equation 38007 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ w) ◇ v
equation 38008 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ x
equation 38009 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ y
equation 38010 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ z
equation 38011 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ w
equation 38012 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ u
equation 38013 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ u) ◇ v
equation 38014 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ x
equation 38015 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ y
equation 38016 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ z
equation 38017 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ w
equation 38018 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ u
equation 38019 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ v
equation 38020 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ v) ◇ r
equation 38021 := x = ((x ◇ ((x ◇ x) ◇ x)) ◇ x) ◇ x
equation 38022 := x = ((x ◇ ((x ◇ x) ◇ x)) ◇ x) ◇ y
equation 38023 := x = ((x ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ x
equation 38024 := x = ((x ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ y
equation 38025 := x = ((x ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ z
equation 38026 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ x
equation 38027 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ y
equation 38028 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ z
equation 38029 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ x
equation 38030 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ y
equation 38031 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ z
equation 38032 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ x
equation 38033 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ y
equation 38034 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ z
equation 38035 := x = ((x ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ w
equation 38036 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ x
equation 38037 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ y
equation 38038 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ z
equation 38039 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ x
equation 38040 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ y
equation 38041 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ z
equation 38042 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ x
equation 38043 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ y
equation 38044 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ z
equation 38045 := x = ((x ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ w
equation 38046 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ x
equation 38047 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ y
equation 38048 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ z
equation 38049 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ x
equation 38050 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ y
equation 38051 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ z
equation 38052 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ x
equation 38053 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ y
equation 38054 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ z
equation 38055 := x = ((x ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ w
equation 38056 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ x
equation 38057 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ y
equation 38058 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ z
equation 38059 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ w
equation 38060 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ x
equation 38061 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ y
equation 38062 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ z
equation 38063 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ w
equation 38064 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ x
equation 38065 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ y
equation 38066 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ z
equation 38067 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ w
equation 38068 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ x
equation 38069 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ y
equation 38070 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ z
equation 38071 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ w
equation 38072 := x = ((x ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ u
equation 38073 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ x
equation 38074 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ y
equation 38075 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ z
equation 38076 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ x
equation 38077 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ y
equation 38078 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ z
equation 38079 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ x
equation 38080 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ y
equation 38081 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ z
equation 38082 := x = ((x ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ w
equation 38083 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ x
equation 38084 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ y
equation 38085 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ z
equation 38086 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ x
equation 38087 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ y
equation 38088 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ z
equation 38089 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ x
equation 38090 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ y
equation 38091 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ z
equation 38092 := x = ((x ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ w
equation 38093 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ x
equation 38094 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ y
equation 38095 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ z
equation 38096 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ w
equation 38097 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ x
equation 38098 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ y
equation 38099 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ z
equation 38100 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ w
equation 38101 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ x
equation 38102 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ y
equation 38103 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ z
equation 38104 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ w
equation 38105 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ x
equation 38106 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ y
equation 38107 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ z
equation 38108 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ w
equation 38109 := x = ((x ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ u
equation 38110 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ x
equation 38111 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ y
equation 38112 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ z
equation 38113 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ x
equation 38114 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ y
equation 38115 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ z
equation 38116 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ x
equation 38117 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ y
equation 38118 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ z
equation 38119 := x = ((x ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ w
equation 38120 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ x
equation 38121 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ y
equation 38122 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ z
equation 38123 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ x
equation 38124 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ y
equation 38125 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ z
equation 38126 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ x
equation 38127 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ y
equation 38128 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ z
equation 38129 := x = ((x ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ w
equation 38130 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ x
equation 38131 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ y
equation 38132 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ z
equation 38133 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ w
equation 38134 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ x
equation 38135 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ y
equation 38136 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ z
equation 38137 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ w
equation 38138 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ x
equation 38139 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ y
equation 38140 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ z
equation 38141 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ w
equation 38142 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ x
equation 38143 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ y
equation 38144 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ z
equation 38145 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ w
equation 38146 := x = ((x ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ u
equation 38147 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ x
equation 38148 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ y
equation 38149 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ z
equation 38150 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ w
equation 38151 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ x
equation 38152 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ y
equation 38153 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ z
equation 38154 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ w
equation 38155 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ x
equation 38156 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ y
equation 38157 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ z
equation 38158 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ w
equation 38159 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ x
equation 38160 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ y
equation 38161 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ z
equation 38162 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ w
equation 38163 := x = ((x ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ u
equation 38164 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ x
equation 38165 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ y
equation 38166 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ z
equation 38167 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ w
equation 38168 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ x
equation 38169 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ y
equation 38170 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ z
equation 38171 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ w
equation 38172 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ x
equation 38173 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ y
equation 38174 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ z
equation 38175 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ w
equation 38176 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ x
equation 38177 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ y
equation 38178 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ z
equation 38179 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ w
equation 38180 := x = ((x ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ u
equation 38181 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ x
equation 38182 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ y
equation 38183 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ z
equation 38184 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ w
equation 38185 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ x
equation 38186 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ y
equation 38187 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ z
equation 38188 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ w
equation 38189 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ x
equation 38190 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ y
equation 38191 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ z
equation 38192 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ w
equation 38193 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ x
equation 38194 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ y
equation 38195 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ z
equation 38196 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ w
equation 38197 := x = ((x ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ u
equation 38198 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ x
equation 38199 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ y
equation 38200 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ z
equation 38201 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ w
equation 38202 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ u
equation 38203 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ x
equation 38204 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ y
equation 38205 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ z
equation 38206 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ w
equation 38207 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ u
equation 38208 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ x
equation 38209 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ y
equation 38210 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ z
equation 38211 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ w
equation 38212 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ u
equation 38213 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ x
equation 38214 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ y
equation 38215 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ z
equation 38216 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ w
equation 38217 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ u
equation 38218 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ x
equation 38219 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ y
equation 38220 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ z
equation 38221 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ w
equation 38222 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ u
equation 38223 := x = ((x ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ v
equation 38224 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ x) ◇ x
equation 38225 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ x) ◇ y
equation 38226 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ x) ◇ z
equation 38227 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ x
equation 38228 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ y
equation 38229 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ y) ◇ z
equation 38230 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ z) ◇ x
equation 38231 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ z) ◇ y
equation 38232 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ z) ◇ z
equation 38233 := x = ((y ◇ ((x ◇ x) ◇ x)) ◇ z) ◇ w
equation 38234 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ x
equation 38235 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ y
equation 38236 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ x) ◇ z
equation 38237 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ x
equation 38238 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ y
equation 38239 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ y) ◇ z
equation 38240 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ x
equation 38241 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ y
equation 38242 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ z
equation 38243 := x = ((y ◇ ((x ◇ x) ◇ y)) ◇ z) ◇ w
equation 38244 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ x) ◇ x
equation 38245 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ x) ◇ y
equation 38246 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ x) ◇ z
equation 38247 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ x) ◇ w
equation 38248 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ y) ◇ x
equation 38249 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ y) ◇ y
equation 38250 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ y) ◇ z
equation 38251 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ y) ◇ w
equation 38252 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ z) ◇ x
equation 38253 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ z) ◇ y
equation 38254 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ z) ◇ z
equation 38255 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ z) ◇ w
equation 38256 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ w) ◇ x
equation 38257 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ w) ◇ y
equation 38258 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ w) ◇ z
equation 38259 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ w) ◇ w
equation 38260 := x = ((y ◇ ((x ◇ x) ◇ z)) ◇ w) ◇ u
equation 38261 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ x
equation 38262 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ y
equation 38263 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ x) ◇ z
equation 38264 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ x
equation 38265 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ y
equation 38266 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ y) ◇ z
equation 38267 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ x
equation 38268 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ y
equation 38269 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ z
equation 38270 := x = ((y ◇ ((x ◇ y) ◇ x)) ◇ z) ◇ w
equation 38271 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ x
equation 38272 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ y
equation 38273 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ x) ◇ z
equation 38274 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ x
equation 38275 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ y
equation 38276 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ y) ◇ z
equation 38277 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ x
equation 38278 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ y
equation 38279 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ z
equation 38280 := x = ((y ◇ ((x ◇ y) ◇ y)) ◇ z) ◇ w
equation 38281 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ x
equation 38282 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ y
equation 38283 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ z
equation 38284 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ x) ◇ w
equation 38285 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ x
equation 38286 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ y
equation 38287 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ z
equation 38288 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ y) ◇ w
equation 38289 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ x
equation 38290 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ y
equation 38291 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ z
equation 38292 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ z) ◇ w
equation 38293 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ x
equation 38294 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ y
equation 38295 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ z
equation 38296 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ w
equation 38297 := x = ((y ◇ ((x ◇ y) ◇ z)) ◇ w) ◇ u
equation 38298 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ x) ◇ x
equation 38299 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ x) ◇ y
equation 38300 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ x) ◇ z
equation 38301 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ x) ◇ w
equation 38302 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ y) ◇ x
equation 38303 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ y) ◇ y
equation 38304 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ y) ◇ z
equation 38305 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ y) ◇ w
equation 38306 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ z) ◇ x
equation 38307 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ z) ◇ y
equation 38308 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ z) ◇ z
equation 38309 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ z) ◇ w
equation 38310 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ w) ◇ x
equation 38311 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ w) ◇ y
equation 38312 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ w) ◇ z
equation 38313 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ w) ◇ w
equation 38314 := x = ((y ◇ ((x ◇ z) ◇ x)) ◇ w) ◇ u
equation 38315 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ x) ◇ x
equation 38316 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ x) ◇ y
equation 38317 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ x) ◇ z
equation 38318 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ x) ◇ w
equation 38319 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ y) ◇ x
equation 38320 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ y) ◇ y
equation 38321 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ y) ◇ z
equation 38322 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ y) ◇ w
equation 38323 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ z) ◇ x
equation 38324 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ z) ◇ y
equation 38325 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ z) ◇ z
equation 38326 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ z) ◇ w
equation 38327 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ w) ◇ x
equation 38328 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ w) ◇ y
equation 38329 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ w) ◇ z
equation 38330 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ w) ◇ w
equation 38331 := x = ((y ◇ ((x ◇ z) ◇ y)) ◇ w) ◇ u
equation 38332 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ x) ◇ x
equation 38333 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ x) ◇ y
equation 38334 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ x) ◇ z
equation 38335 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ x) ◇ w
equation 38336 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ y) ◇ x
equation 38337 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ y) ◇ y
equation 38338 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ y) ◇ z
equation 38339 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ y) ◇ w
equation 38340 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ z) ◇ x
equation 38341 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ z) ◇ y
equation 38342 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ z) ◇ z
equation 38343 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ z) ◇ w
equation 38344 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ w) ◇ x
equation 38345 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ w) ◇ y
equation 38346 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ w) ◇ z
equation 38347 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ w) ◇ w
equation 38348 := x = ((y ◇ ((x ◇ z) ◇ z)) ◇ w) ◇ u
equation 38349 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ x) ◇ x
equation 38350 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ x) ◇ y
equation 38351 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ x) ◇ z
equation 38352 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ x) ◇ w
equation 38353 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ x) ◇ u
equation 38354 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ y) ◇ x
equation 38355 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ y) ◇ y
equation 38356 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ y) ◇ z
equation 38357 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ y) ◇ w
equation 38358 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ y) ◇ u
equation 38359 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ z) ◇ x
equation 38360 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ z) ◇ y
equation 38361 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ z) ◇ z
equation 38362 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ z) ◇ w
equation 38363 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ z) ◇ u
equation 38364 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ w) ◇ x
equation 38365 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ w) ◇ y
equation 38366 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ w) ◇ z
equation 38367 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ w) ◇ w
equation 38368 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ w) ◇ u
equation 38369 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ x
equation 38370 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ y
equation 38371 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ z
equation 38372 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ w
equation 38373 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ u
equation 38374 := x = ((y ◇ ((x ◇ z) ◇ w)) ◇ u) ◇ v
equation 38375 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ x
equation 38376 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ y
equation 38377 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ x) ◇ z
equation 38378 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ x
equation 38379 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ y
equation 38380 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ y) ◇ z
equation 38381 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ x
equation 38382 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ y
equation 38383 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ z
equation 38384 := x = ((y ◇ ((y ◇ x) ◇ x)) ◇ z) ◇ w
equation 38385 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ x
equation 38386 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ y
equation 38387 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ x) ◇ z
equation 38388 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ x
equation 38389 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ y
equation 38390 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ y) ◇ z
equation 38391 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ x
equation 38392 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ y
equation 38393 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ z
equation 38394 := x = ((y ◇ ((y ◇ x) ◇ y)) ◇ z) ◇ w
equation 38395 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ x
equation 38396 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ y
equation 38397 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ z
equation 38398 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ x) ◇ w
equation 38399 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ x
equation 38400 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ y
equation 38401 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ z
equation 38402 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ y) ◇ w
equation 38403 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ x
equation 38404 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ y
equation 38405 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ z
equation 38406 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ z) ◇ w
equation 38407 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ x
equation 38408 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ y
equation 38409 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ z
equation 38410 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ w
equation 38411 := x = ((y ◇ ((y ◇ x) ◇ z)) ◇ w) ◇ u
equation 38412 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ x
equation 38413 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ y
equation 38414 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ x) ◇ z
equation 38415 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ x
equation 38416 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ y
equation 38417 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ y) ◇ z
equation 38418 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ x
equation 38419 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ y
equation 38420 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ z
equation 38421 := x = ((y ◇ ((y ◇ y) ◇ x)) ◇ z) ◇ w
equation 38422 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ x
equation 38423 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ y
equation 38424 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ x) ◇ z
equation 38425 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ x
equation 38426 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ y
equation 38427 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ y) ◇ z
equation 38428 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ x
equation 38429 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ y
equation 38430 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ z
equation 38431 := x = ((y ◇ ((y ◇ y) ◇ y)) ◇ z) ◇ w
equation 38432 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ x
equation 38433 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ y
equation 38434 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ z
equation 38435 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ x) ◇ w
equation 38436 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ x
equation 38437 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ y
equation 38438 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ z
equation 38439 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ y) ◇ w
equation 38440 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ x
equation 38441 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ y
equation 38442 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ z
equation 38443 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ z) ◇ w
equation 38444 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ x
equation 38445 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ y
equation 38446 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ z
equation 38447 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ w
equation 38448 := x = ((y ◇ ((y ◇ y) ◇ z)) ◇ w) ◇ u
equation 38449 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ x
equation 38450 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ y
equation 38451 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ z
equation 38452 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ x) ◇ w
equation 38453 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ x
equation 38454 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ y
equation 38455 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ z
equation 38456 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ y) ◇ w
equation 38457 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ x
equation 38458 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ y
equation 38459 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ z
equation 38460 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ z) ◇ w
equation 38461 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ x
equation 38462 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ y
equation 38463 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ z
equation 38464 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ w
equation 38465 := x = ((y ◇ ((y ◇ z) ◇ x)) ◇ w) ◇ u
equation 38466 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ x
equation 38467 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ y
equation 38468 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ z
equation 38469 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ x) ◇ w
equation 38470 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ x
equation 38471 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ y
equation 38472 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ z
equation 38473 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ y) ◇ w
equation 38474 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ x
equation 38475 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ y
equation 38476 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ z
equation 38477 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ z) ◇ w
equation 38478 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ x
equation 38479 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ y
equation 38480 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ z
equation 38481 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ w
equation 38482 := x = ((y ◇ ((y ◇ z) ◇ y)) ◇ w) ◇ u
equation 38483 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ x
equation 38484 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ y
equation 38485 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ z
equation 38486 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ x) ◇ w
equation 38487 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ x
equation 38488 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ y
equation 38489 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ z
equation 38490 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ y) ◇ w
equation 38491 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ x
equation 38492 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ y
equation 38493 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ z
equation 38494 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ z) ◇ w
equation 38495 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ x
equation 38496 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ y
equation 38497 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ z
equation 38498 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ w
equation 38499 := x = ((y ◇ ((y ◇ z) ◇ z)) ◇ w) ◇ u
equation 38500 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ x
equation 38501 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ y
equation 38502 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ z
equation 38503 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ w
equation 38504 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ x) ◇ u
equation 38505 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ x
equation 38506 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ y
equation 38507 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ z
equation 38508 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ w
equation 38509 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ y) ◇ u
equation 38510 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ x
equation 38511 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ y
equation 38512 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ z
equation 38513 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ w
equation 38514 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ z) ◇ u
equation 38515 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ x
equation 38516 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ y
equation 38517 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ z
equation 38518 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ w
equation 38519 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ w) ◇ u
equation 38520 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ x
equation 38521 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ y
equation 38522 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ z
equation 38523 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ w
equation 38524 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ u
equation 38525 := x = ((y ◇ ((y ◇ z) ◇ w)) ◇ u) ◇ v
equation 38526 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ x) ◇ x
equation 38527 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ x) ◇ y
equation 38528 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ x) ◇ z
equation 38529 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ x) ◇ w
equation 38530 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ y) ◇ x
equation 38531 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ y) ◇ y
equation 38532 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ y) ◇ z
equation 38533 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ y) ◇ w
equation 38534 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ z) ◇ x
equation 38535 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ z) ◇ y
equation 38536 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ z) ◇ z
equation 38537 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ z) ◇ w
equation 38538 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ w) ◇ x
equation 38539 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ w) ◇ y
equation 38540 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ w) ◇ z
equation 38541 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ w) ◇ w
equation 38542 := x = ((y ◇ ((z ◇ x) ◇ x)) ◇ w) ◇ u
equation 38543 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ x) ◇ x
equation 38544 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ x) ◇ y
equation 38545 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ x) ◇ z
equation 38546 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ x) ◇ w
equation 38547 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ y) ◇ x
equation 38548 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ y) ◇ y
equation 38549 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ y) ◇ z
equation 38550 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ y) ◇ w
equation 38551 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ z) ◇ x
equation 38552 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ z) ◇ y
equation 38553 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ z) ◇ z
equation 38554 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ z) ◇ w
equation 38555 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ w) ◇ x
equation 38556 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ w) ◇ y
equation 38557 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ w) ◇ z
equation 38558 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ w) ◇ w
equation 38559 := x = ((y ◇ ((z ◇ x) ◇ y)) ◇ w) ◇ u
equation 38560 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ x) ◇ x
equation 38561 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ x) ◇ y
equation 38562 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ x) ◇ z
equation 38563 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ x) ◇ w
equation 38564 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ y) ◇ x
equation 38565 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ y) ◇ y
equation 38566 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ y) ◇ z
equation 38567 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ y) ◇ w
equation 38568 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ z) ◇ x
equation 38569 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ z) ◇ y
equation 38570 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ z) ◇ z
equation 38571 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ z) ◇ w
equation 38572 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ w) ◇ x
equation 38573 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ w) ◇ y
equation 38574 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ w) ◇ z
equation 38575 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ w) ◇ w
equation 38576 := x = ((y ◇ ((z ◇ x) ◇ z)) ◇ w) ◇ u
equation 38577 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ x) ◇ x
equation 38578 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ x) ◇ y
equation 38579 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ x) ◇ z
equation 38580 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ x) ◇ w
equation 38581 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ x) ◇ u
equation 38582 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ y) ◇ x
equation 38583 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ y) ◇ y
equation 38584 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ y) ◇ z
equation 38585 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ y) ◇ w
equation 38586 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ y) ◇ u
equation 38587 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ z) ◇ x
equation 38588 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ z) ◇ y
equation 38589 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ z) ◇ z
equation 38590 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ z) ◇ w
equation 38591 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ z) ◇ u
equation 38592 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ w) ◇ x
equation 38593 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ w) ◇ y
equation 38594 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ w) ◇ z
equation 38595 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ w) ◇ w
equation 38596 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ w) ◇ u
equation 38597 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ x
equation 38598 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ y
equation 38599 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ z
equation 38600 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ w
equation 38601 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ u
equation 38602 := x = ((y ◇ ((z ◇ x) ◇ w)) ◇ u) ◇ v
equation 38603 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ x) ◇ x
equation 38604 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ x) ◇ y
equation 38605 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ x) ◇ z
equation 38606 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ x) ◇ w
equation 38607 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ y) ◇ x
equation 38608 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ y) ◇ y
equation 38609 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ y) ◇ z
equation 38610 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ y) ◇ w
equation 38611 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ z) ◇ x
equation 38612 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ z) ◇ y
equation 38613 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ z) ◇ z
equation 38614 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ z) ◇ w
equation 38615 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ w) ◇ x
equation 38616 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ w) ◇ y
equation 38617 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ w) ◇ z
equation 38618 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ w) ◇ w
equation 38619 := x = ((y ◇ ((z ◇ y) ◇ x)) ◇ w) ◇ u
equation 38620 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ x) ◇ x
equation 38621 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ x) ◇ y
equation 38622 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ x) ◇ z
equation 38623 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ x) ◇ w
equation 38624 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ y) ◇ x
equation 38625 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ y) ◇ y
equation 38626 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ y) ◇ z
equation 38627 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ y) ◇ w
equation 38628 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ z) ◇ x
equation 38629 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ z) ◇ y
equation 38630 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ z) ◇ z
equation 38631 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ z) ◇ w
equation 38632 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ w) ◇ x
equation 38633 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ w) ◇ y
equation 38634 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ w) ◇ z
equation 38635 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ w) ◇ w
equation 38636 := x = ((y ◇ ((z ◇ y) ◇ y)) ◇ w) ◇ u
equation 38637 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ x) ◇ x
equation 38638 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ x) ◇ y
equation 38639 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ x) ◇ z
equation 38640 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ x) ◇ w
equation 38641 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ y) ◇ x
equation 38642 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ y) ◇ y
equation 38643 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ y) ◇ z
equation 38644 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ y) ◇ w
equation 38645 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ z) ◇ x
equation 38646 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ z) ◇ y
equation 38647 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ z) ◇ z
equation 38648 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ z) ◇ w
equation 38649 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ w) ◇ x
equation 38650 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ w) ◇ y
equation 38651 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ w) ◇ z
equation 38652 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ w) ◇ w
equation 38653 := x = ((y ◇ ((z ◇ y) ◇ z)) ◇ w) ◇ u
equation 38654 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ x) ◇ x
equation 38655 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ x) ◇ y
equation 38656 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ x) ◇ z
equation 38657 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ x) ◇ w
equation 38658 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ x) ◇ u
equation 38659 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ y) ◇ x
equation 38660 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ y) ◇ y
equation 38661 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ y) ◇ z
equation 38662 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ y) ◇ w
equation 38663 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ y) ◇ u
equation 38664 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ z) ◇ x
equation 38665 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ z) ◇ y
equation 38666 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ z) ◇ z
equation 38667 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ z) ◇ w
equation 38668 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ z) ◇ u
equation 38669 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ w) ◇ x
equation 38670 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ w) ◇ y
equation 38671 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ w) ◇ z
equation 38672 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ w) ◇ w
equation 38673 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ w) ◇ u
equation 38674 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ x
equation 38675 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ y
equation 38676 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ z
equation 38677 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ w
equation 38678 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ u
equation 38679 := x = ((y ◇ ((z ◇ y) ◇ w)) ◇ u) ◇ v
equation 38680 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ x) ◇ x
equation 38681 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ x) ◇ y
equation 38682 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ x) ◇ z
equation 38683 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ x) ◇ w
equation 38684 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ y) ◇ x
equation 38685 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ y) ◇ y
equation 38686 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ y) ◇ z
equation 38687 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ y) ◇ w
equation 38688 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ z) ◇ x
equation 38689 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ z) ◇ y
equation 38690 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ z) ◇ z
equation 38691 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ z) ◇ w
equation 38692 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ w) ◇ x
equation 38693 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ w) ◇ y
equation 38694 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ w) ◇ z
equation 38695 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ w) ◇ w
equation 38696 := x = ((y ◇ ((z ◇ z) ◇ x)) ◇ w) ◇ u
equation 38697 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ x) ◇ x
equation 38698 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ x) ◇ y
equation 38699 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ x) ◇ z
equation 38700 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ x) ◇ w
equation 38701 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ y) ◇ x
equation 38702 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ y) ◇ y
equation 38703 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ y) ◇ z
equation 38704 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ y) ◇ w
equation 38705 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ z) ◇ x
equation 38706 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ z) ◇ y
equation 38707 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ z) ◇ z
equation 38708 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ z) ◇ w
equation 38709 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ w) ◇ x
equation 38710 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ w) ◇ y
equation 38711 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ w) ◇ z
equation 38712 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ w) ◇ w
equation 38713 := x = ((y ◇ ((z ◇ z) ◇ y)) ◇ w) ◇ u
equation 38714 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ x) ◇ x
equation 38715 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ x) ◇ y
equation 38716 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ x) ◇ z
equation 38717 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ x) ◇ w
equation 38718 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ y) ◇ x
equation 38719 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ y) ◇ y
equation 38720 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ y) ◇ z
equation 38721 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ y) ◇ w
equation 38722 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ z) ◇ x
equation 38723 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ z) ◇ y
equation 38724 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ z) ◇ z
equation 38725 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ z) ◇ w
equation 38726 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ w) ◇ x
equation 38727 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ w) ◇ y
equation 38728 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ w) ◇ z
equation 38729 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ w) ◇ w
equation 38730 := x = ((y ◇ ((z ◇ z) ◇ z)) ◇ w) ◇ u
equation 38731 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ x) ◇ x
equation 38732 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ x) ◇ y
equation 38733 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ x) ◇ z
equation 38734 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ x) ◇ w
equation 38735 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ x) ◇ u
equation 38736 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ y) ◇ x
equation 38737 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ y) ◇ y
equation 38738 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ y) ◇ z
equation 38739 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ y) ◇ w
equation 38740 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ y) ◇ u
equation 38741 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ z) ◇ x
equation 38742 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ z) ◇ y
equation 38743 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ z) ◇ z
equation 38744 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ z) ◇ w
equation 38745 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ z) ◇ u
equation 38746 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ w) ◇ x
equation 38747 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ w) ◇ y
equation 38748 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ w) ◇ z
equation 38749 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ w) ◇ w
equation 38750 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ w) ◇ u
equation 38751 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ x
equation 38752 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ y
equation 38753 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ z
equation 38754 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ w
equation 38755 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ u
equation 38756 := x = ((y ◇ ((z ◇ z) ◇ w)) ◇ u) ◇ v
equation 38757 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ x) ◇ x
equation 38758 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ x) ◇ y
equation 38759 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ x) ◇ z
equation 38760 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ x) ◇ w
equation 38761 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ x) ◇ u
equation 38762 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ y) ◇ x
equation 38763 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ y) ◇ y
equation 38764 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ y) ◇ z
equation 38765 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ y) ◇ w
equation 38766 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ y) ◇ u
equation 38767 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ z) ◇ x
equation 38768 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ z) ◇ y
equation 38769 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ z) ◇ z
equation 38770 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ z) ◇ w
equation 38771 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ z) ◇ u
equation 38772 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ w) ◇ x
equation 38773 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ w) ◇ y
equation 38774 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ w) ◇ z
equation 38775 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ w) ◇ w
equation 38776 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ w) ◇ u
equation 38777 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ x
equation 38778 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ y
equation 38779 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ z
equation 38780 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ w
equation 38781 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ u
equation 38782 := x = ((y ◇ ((z ◇ w) ◇ x)) ◇ u) ◇ v
equation 38783 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ x) ◇ x
equation 38784 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ x) ◇ y
equation 38785 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ x) ◇ z
equation 38786 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ x) ◇ w
equation 38787 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ x) ◇ u
equation 38788 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ y) ◇ x
equation 38789 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ y) ◇ y
equation 38790 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ y) ◇ z
equation 38791 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ y) ◇ w
equation 38792 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ y) ◇ u
equation 38793 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ z) ◇ x
equation 38794 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ z) ◇ y
equation 38795 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ z) ◇ z
equation 38796 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ z) ◇ w
equation 38797 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ z) ◇ u
equation 38798 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ w) ◇ x
equation 38799 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ w) ◇ y
equation 38800 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ w) ◇ z
equation 38801 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ w) ◇ w
equation 38802 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ w) ◇ u
equation 38803 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ x
equation 38804 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ y
equation 38805 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ z
equation 38806 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ w
equation 38807 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ u
equation 38808 := x = ((y ◇ ((z ◇ w) ◇ y)) ◇ u) ◇ v
equation 38809 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ x) ◇ x
equation 38810 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ x) ◇ y
equation 38811 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ x) ◇ z
equation 38812 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ x) ◇ w
equation 38813 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ x) ◇ u
equation 38814 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ y) ◇ x
equation 38815 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ y) ◇ y
equation 38816 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ y) ◇ z
equation 38817 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ y) ◇ w
equation 38818 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ y) ◇ u
equation 38819 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ z) ◇ x
equation 38820 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ z) ◇ y
equation 38821 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ z) ◇ z
equation 38822 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ z) ◇ w
equation 38823 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ z) ◇ u
equation 38824 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ w) ◇ x
equation 38825 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ w) ◇ y
equation 38826 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ w) ◇ z
equation 38827 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ w) ◇ w
equation 38828 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ w) ◇ u
equation 38829 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ x
equation 38830 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ y
equation 38831 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ z
equation 38832 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ w
equation 38833 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ u
equation 38834 := x = ((y ◇ ((z ◇ w) ◇ z)) ◇ u) ◇ v
equation 38835 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ x) ◇ x
equation 38836 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ x) ◇ y
equation 38837 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ x) ◇ z
equation 38838 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ x) ◇ w
equation 38839 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ x) ◇ u
equation 38840 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ y) ◇ x
equation 38841 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ y) ◇ y
equation 38842 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ y) ◇ z
equation 38843 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ y) ◇ w
equation 38844 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ y) ◇ u
equation 38845 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ z) ◇ x
equation 38846 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ z) ◇ y
equation 38847 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ z) ◇ z
equation 38848 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ z) ◇ w
equation 38849 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ z) ◇ u
equation 38850 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ w) ◇ x
equation 38851 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ w) ◇ y
equation 38852 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ w) ◇ z
equation 38853 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ w) ◇ w
equation 38854 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ w) ◇ u
equation 38855 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ x
equation 38856 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ y
equation 38857 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ z
equation 38858 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ w
equation 38859 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ u
equation 38860 := x = ((y ◇ ((z ◇ w) ◇ w)) ◇ u) ◇ v
equation 38861 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ x
equation 38862 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ y
equation 38863 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ z
equation 38864 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ w
equation 38865 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ u
equation 38866 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ x) ◇ v
equation 38867 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ x
equation 38868 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ y
equation 38869 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ z
equation 38870 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ w
equation 38871 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ u
equation 38872 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ y) ◇ v
equation 38873 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ x
equation 38874 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ y
equation 38875 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ z
equation 38876 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ w
equation 38877 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ u
equation 38878 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ z) ◇ v
equation 38879 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ x
equation 38880 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ y
equation 38881 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ z
equation 38882 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ w
equation 38883 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ u
equation 38884 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ w) ◇ v
equation 38885 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ x
equation 38886 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ y
equation 38887 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ z
equation 38888 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ w
equation 38889 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ u
equation 38890 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ u) ◇ v
equation 38891 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ x
equation 38892 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ y
equation 38893 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ z
equation 38894 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ w
equation 38895 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ u
equation 38896 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ v
equation 38897 := x = ((y ◇ ((z ◇ w) ◇ u)) ◇ v) ◇ r
equation 38898 := x = (((x ◇ x) ◇ (x ◇ x)) ◇ x) ◇ x
equation 38899 := x = (((x ◇ x) ◇ (x ◇ x)) ◇ x) ◇ y
equation 38900 := x = (((x ◇ x) ◇ (x ◇ x)) ◇ y) ◇ x
equation 38901 := x = (((x ◇ x) ◇ (x ◇ x)) ◇ y) ◇ y
equation 38902 := x = (((x ◇ x) ◇ (x ◇ x)) ◇ y) ◇ z
equation 38903 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ x) ◇ x
equation 38904 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ x) ◇ y
equation 38905 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ x) ◇ z
equation 38906 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ y) ◇ x
equation 38907 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ y) ◇ y
equation 38908 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ y) ◇ z
equation 38909 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ z) ◇ x
equation 38910 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ z) ◇ y
equation 38911 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ z) ◇ z
equation 38912 := x = (((x ◇ x) ◇ (x ◇ y)) ◇ z) ◇ w
equation 38913 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ x) ◇ x
equation 38914 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ x) ◇ y
equation 38915 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ x) ◇ z
equation 38916 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ y) ◇ x
equation 38917 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ y) ◇ y
equation 38918 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ y) ◇ z
equation 38919 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ z) ◇ x
equation 38920 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ z) ◇ y
equation 38921 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ z) ◇ z
equation 38922 := x = (((x ◇ x) ◇ (y ◇ x)) ◇ z) ◇ w
equation 38923 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ x) ◇ x
equation 38924 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ x) ◇ y
equation 38925 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ x) ◇ z
equation 38926 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ y) ◇ x
equation 38927 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ y) ◇ y
equation 38928 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ y) ◇ z
equation 38929 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ z) ◇ x
equation 38930 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ z) ◇ y
equation 38931 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ z) ◇ z
equation 38932 := x = (((x ◇ x) ◇ (y ◇ y)) ◇ z) ◇ w
equation 38933 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ x) ◇ x
equation 38934 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ x) ◇ y
equation 38935 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ x) ◇ z
equation 38936 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ x) ◇ w
equation 38937 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ y) ◇ x
equation 38938 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ y) ◇ y
equation 38939 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ y) ◇ z
equation 38940 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ y) ◇ w
equation 38941 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ z) ◇ x
equation 38942 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ z) ◇ y
equation 38943 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ z) ◇ z
equation 38944 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ z) ◇ w
equation 38945 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ w) ◇ x
equation 38946 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ w) ◇ y
equation 38947 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ w) ◇ z
equation 38948 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ w) ◇ w
equation 38949 := x = (((x ◇ x) ◇ (y ◇ z)) ◇ w) ◇ u
equation 38950 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ x) ◇ x
equation 38951 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ x) ◇ y
equation 38952 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ x) ◇ z
equation 38953 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ y) ◇ x
equation 38954 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ y) ◇ y
equation 38955 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ y) ◇ z
equation 38956 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ z) ◇ x
equation 38957 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ z) ◇ y
equation 38958 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ z) ◇ z
equation 38959 := x = (((x ◇ y) ◇ (x ◇ x)) ◇ z) ◇ w
equation 38960 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ x) ◇ x
equation 38961 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ x) ◇ y
equation 38962 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ x) ◇ z
equation 38963 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ y) ◇ x
equation 38964 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ y) ◇ y
equation 38965 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ y) ◇ z
equation 38966 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ z) ◇ x
equation 38967 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ z) ◇ y
equation 38968 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ z) ◇ z
equation 38969 := x = (((x ◇ y) ◇ (x ◇ y)) ◇ z) ◇ w
equation 38970 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ x) ◇ x
equation 38971 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ x) ◇ y
equation 38972 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ x) ◇ z
equation 38973 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ x) ◇ w
equation 38974 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ y) ◇ x
equation 38975 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ y) ◇ y
equation 38976 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ y) ◇ z
equation 38977 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ y) ◇ w
equation 38978 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ z) ◇ x
equation 38979 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ z) ◇ y
equation 38980 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ z) ◇ z
equation 38981 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ z) ◇ w
equation 38982 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ w) ◇ x
equation 38983 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ w) ◇ y
equation 38984 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ w) ◇ z
equation 38985 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ w) ◇ w
equation 38986 := x = (((x ◇ y) ◇ (x ◇ z)) ◇ w) ◇ u
equation 38987 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ x) ◇ x
equation 38988 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ x) ◇ y
equation 38989 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ x) ◇ z
equation 38990 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ y) ◇ x
equation 38991 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ y) ◇ y
equation 38992 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ y) ◇ z
equation 38993 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ z) ◇ x
equation 38994 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ z) ◇ y
equation 38995 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ z) ◇ z
equation 38996 := x = (((x ◇ y) ◇ (y ◇ x)) ◇ z) ◇ w
equation 38997 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ x) ◇ x
equation 38998 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ x) ◇ y
equation 38999 := x = (((x ◇ y) ◇ (y ◇ y)) ◇ x) ◇ z
