import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 51000-51999 -/

equation 51000 := x ◇ y = (z ◇ ((z ◇ z) ◇ z)) ◇ x
equation 51001 := x ◇ y = (z ◇ ((z ◇ z) ◇ z)) ◇ y
equation 51002 := x ◇ y = (z ◇ ((z ◇ z) ◇ z)) ◇ z
equation 51003 := x ◇ y = (z ◇ ((z ◇ z) ◇ z)) ◇ w
equation 51004 := x ◇ y = (z ◇ ((z ◇ z) ◇ w)) ◇ x
equation 51005 := x ◇ y = (z ◇ ((z ◇ z) ◇ w)) ◇ y
equation 51006 := x ◇ y = (z ◇ ((z ◇ z) ◇ w)) ◇ z
equation 51007 := x ◇ y = (z ◇ ((z ◇ z) ◇ w)) ◇ w
equation 51008 := x ◇ y = (z ◇ ((z ◇ z) ◇ w)) ◇ u
equation 51009 := x ◇ y = (z ◇ ((z ◇ w) ◇ x)) ◇ x
equation 51010 := x ◇ y = (z ◇ ((z ◇ w) ◇ x)) ◇ y
equation 51011 := x ◇ y = (z ◇ ((z ◇ w) ◇ x)) ◇ z
equation 51012 := x ◇ y = (z ◇ ((z ◇ w) ◇ x)) ◇ w
equation 51013 := x ◇ y = (z ◇ ((z ◇ w) ◇ x)) ◇ u
equation 51014 := x ◇ y = (z ◇ ((z ◇ w) ◇ y)) ◇ x
equation 51015 := x ◇ y = (z ◇ ((z ◇ w) ◇ y)) ◇ y
equation 51016 := x ◇ y = (z ◇ ((z ◇ w) ◇ y)) ◇ z
equation 51017 := x ◇ y = (z ◇ ((z ◇ w) ◇ y)) ◇ w
equation 51018 := x ◇ y = (z ◇ ((z ◇ w) ◇ y)) ◇ u
equation 51019 := x ◇ y = (z ◇ ((z ◇ w) ◇ z)) ◇ x
equation 51020 := x ◇ y = (z ◇ ((z ◇ w) ◇ z)) ◇ y
equation 51021 := x ◇ y = (z ◇ ((z ◇ w) ◇ z)) ◇ z
equation 51022 := x ◇ y = (z ◇ ((z ◇ w) ◇ z)) ◇ w
equation 51023 := x ◇ y = (z ◇ ((z ◇ w) ◇ z)) ◇ u
equation 51024 := x ◇ y = (z ◇ ((z ◇ w) ◇ w)) ◇ x
equation 51025 := x ◇ y = (z ◇ ((z ◇ w) ◇ w)) ◇ y
equation 51026 := x ◇ y = (z ◇ ((z ◇ w) ◇ w)) ◇ z
equation 51027 := x ◇ y = (z ◇ ((z ◇ w) ◇ w)) ◇ w
equation 51028 := x ◇ y = (z ◇ ((z ◇ w) ◇ w)) ◇ u
equation 51029 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ x
equation 51030 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ y
equation 51031 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ z
equation 51032 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ w
equation 51033 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ u
equation 51034 := x ◇ y = (z ◇ ((z ◇ w) ◇ u)) ◇ v
equation 51035 := x ◇ y = (z ◇ ((w ◇ x) ◇ x)) ◇ x
equation 51036 := x ◇ y = (z ◇ ((w ◇ x) ◇ x)) ◇ y
equation 51037 := x ◇ y = (z ◇ ((w ◇ x) ◇ x)) ◇ z
equation 51038 := x ◇ y = (z ◇ ((w ◇ x) ◇ x)) ◇ w
equation 51039 := x ◇ y = (z ◇ ((w ◇ x) ◇ x)) ◇ u
equation 51040 := x ◇ y = (z ◇ ((w ◇ x) ◇ y)) ◇ x
equation 51041 := x ◇ y = (z ◇ ((w ◇ x) ◇ y)) ◇ y
equation 51042 := x ◇ y = (z ◇ ((w ◇ x) ◇ y)) ◇ z
equation 51043 := x ◇ y = (z ◇ ((w ◇ x) ◇ y)) ◇ w
equation 51044 := x ◇ y = (z ◇ ((w ◇ x) ◇ y)) ◇ u
equation 51045 := x ◇ y = (z ◇ ((w ◇ x) ◇ z)) ◇ x
equation 51046 := x ◇ y = (z ◇ ((w ◇ x) ◇ z)) ◇ y
equation 51047 := x ◇ y = (z ◇ ((w ◇ x) ◇ z)) ◇ z
equation 51048 := x ◇ y = (z ◇ ((w ◇ x) ◇ z)) ◇ w
equation 51049 := x ◇ y = (z ◇ ((w ◇ x) ◇ z)) ◇ u
equation 51050 := x ◇ y = (z ◇ ((w ◇ x) ◇ w)) ◇ x
equation 51051 := x ◇ y = (z ◇ ((w ◇ x) ◇ w)) ◇ y
equation 51052 := x ◇ y = (z ◇ ((w ◇ x) ◇ w)) ◇ z
equation 51053 := x ◇ y = (z ◇ ((w ◇ x) ◇ w)) ◇ w
equation 51054 := x ◇ y = (z ◇ ((w ◇ x) ◇ w)) ◇ u
equation 51055 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ x
equation 51056 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ y
equation 51057 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ z
equation 51058 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ w
equation 51059 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ u
equation 51060 := x ◇ y = (z ◇ ((w ◇ x) ◇ u)) ◇ v
equation 51061 := x ◇ y = (z ◇ ((w ◇ y) ◇ x)) ◇ x
equation 51062 := x ◇ y = (z ◇ ((w ◇ y) ◇ x)) ◇ y
equation 51063 := x ◇ y = (z ◇ ((w ◇ y) ◇ x)) ◇ z
equation 51064 := x ◇ y = (z ◇ ((w ◇ y) ◇ x)) ◇ w
equation 51065 := x ◇ y = (z ◇ ((w ◇ y) ◇ x)) ◇ u
equation 51066 := x ◇ y = (z ◇ ((w ◇ y) ◇ y)) ◇ x
equation 51067 := x ◇ y = (z ◇ ((w ◇ y) ◇ y)) ◇ y
equation 51068 := x ◇ y = (z ◇ ((w ◇ y) ◇ y)) ◇ z
equation 51069 := x ◇ y = (z ◇ ((w ◇ y) ◇ y)) ◇ w
equation 51070 := x ◇ y = (z ◇ ((w ◇ y) ◇ y)) ◇ u
equation 51071 := x ◇ y = (z ◇ ((w ◇ y) ◇ z)) ◇ x
equation 51072 := x ◇ y = (z ◇ ((w ◇ y) ◇ z)) ◇ y
equation 51073 := x ◇ y = (z ◇ ((w ◇ y) ◇ z)) ◇ z
equation 51074 := x ◇ y = (z ◇ ((w ◇ y) ◇ z)) ◇ w
equation 51075 := x ◇ y = (z ◇ ((w ◇ y) ◇ z)) ◇ u
equation 51076 := x ◇ y = (z ◇ ((w ◇ y) ◇ w)) ◇ x
equation 51077 := x ◇ y = (z ◇ ((w ◇ y) ◇ w)) ◇ y
equation 51078 := x ◇ y = (z ◇ ((w ◇ y) ◇ w)) ◇ z
equation 51079 := x ◇ y = (z ◇ ((w ◇ y) ◇ w)) ◇ w
equation 51080 := x ◇ y = (z ◇ ((w ◇ y) ◇ w)) ◇ u
equation 51081 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ x
equation 51082 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ y
equation 51083 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ z
equation 51084 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ w
equation 51085 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ u
equation 51086 := x ◇ y = (z ◇ ((w ◇ y) ◇ u)) ◇ v
equation 51087 := x ◇ y = (z ◇ ((w ◇ z) ◇ x)) ◇ x
equation 51088 := x ◇ y = (z ◇ ((w ◇ z) ◇ x)) ◇ y
equation 51089 := x ◇ y = (z ◇ ((w ◇ z) ◇ x)) ◇ z
equation 51090 := x ◇ y = (z ◇ ((w ◇ z) ◇ x)) ◇ w
equation 51091 := x ◇ y = (z ◇ ((w ◇ z) ◇ x)) ◇ u
equation 51092 := x ◇ y = (z ◇ ((w ◇ z) ◇ y)) ◇ x
equation 51093 := x ◇ y = (z ◇ ((w ◇ z) ◇ y)) ◇ y
equation 51094 := x ◇ y = (z ◇ ((w ◇ z) ◇ y)) ◇ z
equation 51095 := x ◇ y = (z ◇ ((w ◇ z) ◇ y)) ◇ w
equation 51096 := x ◇ y = (z ◇ ((w ◇ z) ◇ y)) ◇ u
equation 51097 := x ◇ y = (z ◇ ((w ◇ z) ◇ z)) ◇ x
equation 51098 := x ◇ y = (z ◇ ((w ◇ z) ◇ z)) ◇ y
equation 51099 := x ◇ y = (z ◇ ((w ◇ z) ◇ z)) ◇ z
equation 51100 := x ◇ y = (z ◇ ((w ◇ z) ◇ z)) ◇ w
equation 51101 := x ◇ y = (z ◇ ((w ◇ z) ◇ z)) ◇ u
equation 51102 := x ◇ y = (z ◇ ((w ◇ z) ◇ w)) ◇ x
equation 51103 := x ◇ y = (z ◇ ((w ◇ z) ◇ w)) ◇ y
equation 51104 := x ◇ y = (z ◇ ((w ◇ z) ◇ w)) ◇ z
equation 51105 := x ◇ y = (z ◇ ((w ◇ z) ◇ w)) ◇ w
equation 51106 := x ◇ y = (z ◇ ((w ◇ z) ◇ w)) ◇ u
equation 51107 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ x
equation 51108 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ y
equation 51109 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ z
equation 51110 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ w
equation 51111 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ u
equation 51112 := x ◇ y = (z ◇ ((w ◇ z) ◇ u)) ◇ v
equation 51113 := x ◇ y = (z ◇ ((w ◇ w) ◇ x)) ◇ x
equation 51114 := x ◇ y = (z ◇ ((w ◇ w) ◇ x)) ◇ y
equation 51115 := x ◇ y = (z ◇ ((w ◇ w) ◇ x)) ◇ z
equation 51116 := x ◇ y = (z ◇ ((w ◇ w) ◇ x)) ◇ w
equation 51117 := x ◇ y = (z ◇ ((w ◇ w) ◇ x)) ◇ u
equation 51118 := x ◇ y = (z ◇ ((w ◇ w) ◇ y)) ◇ x
equation 51119 := x ◇ y = (z ◇ ((w ◇ w) ◇ y)) ◇ y
equation 51120 := x ◇ y = (z ◇ ((w ◇ w) ◇ y)) ◇ z
equation 51121 := x ◇ y = (z ◇ ((w ◇ w) ◇ y)) ◇ w
equation 51122 := x ◇ y = (z ◇ ((w ◇ w) ◇ y)) ◇ u
equation 51123 := x ◇ y = (z ◇ ((w ◇ w) ◇ z)) ◇ x
equation 51124 := x ◇ y = (z ◇ ((w ◇ w) ◇ z)) ◇ y
equation 51125 := x ◇ y = (z ◇ ((w ◇ w) ◇ z)) ◇ z
equation 51126 := x ◇ y = (z ◇ ((w ◇ w) ◇ z)) ◇ w
equation 51127 := x ◇ y = (z ◇ ((w ◇ w) ◇ z)) ◇ u
equation 51128 := x ◇ y = (z ◇ ((w ◇ w) ◇ w)) ◇ x
equation 51129 := x ◇ y = (z ◇ ((w ◇ w) ◇ w)) ◇ y
equation 51130 := x ◇ y = (z ◇ ((w ◇ w) ◇ w)) ◇ z
equation 51131 := x ◇ y = (z ◇ ((w ◇ w) ◇ w)) ◇ w
equation 51132 := x ◇ y = (z ◇ ((w ◇ w) ◇ w)) ◇ u
equation 51133 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ x
equation 51134 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ y
equation 51135 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ z
equation 51136 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ w
equation 51137 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ u
equation 51138 := x ◇ y = (z ◇ ((w ◇ w) ◇ u)) ◇ v
equation 51139 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ x
equation 51140 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ y
equation 51141 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ z
equation 51142 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ w
equation 51143 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ u
equation 51144 := x ◇ y = (z ◇ ((w ◇ u) ◇ x)) ◇ v
equation 51145 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ x
equation 51146 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ y
equation 51147 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ z
equation 51148 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ w
equation 51149 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ u
equation 51150 := x ◇ y = (z ◇ ((w ◇ u) ◇ y)) ◇ v
equation 51151 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ x
equation 51152 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ y
equation 51153 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ z
equation 51154 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ w
equation 51155 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ u
equation 51156 := x ◇ y = (z ◇ ((w ◇ u) ◇ z)) ◇ v
equation 51157 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ x
equation 51158 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ y
equation 51159 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ z
equation 51160 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ w
equation 51161 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ u
equation 51162 := x ◇ y = (z ◇ ((w ◇ u) ◇ w)) ◇ v
equation 51163 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ x
equation 51164 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ y
equation 51165 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ z
equation 51166 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ w
equation 51167 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ u
equation 51168 := x ◇ y = (z ◇ ((w ◇ u) ◇ u)) ◇ v
equation 51169 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ x
equation 51170 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ y
equation 51171 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ z
equation 51172 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ w
equation 51173 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ u
equation 51174 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ v
equation 51175 := x ◇ y = (z ◇ ((w ◇ u) ◇ v)) ◇ r
equation 51176 := x ◇ x = ((x ◇ x) ◇ (x ◇ x)) ◇ x
equation 51177 := x ◇ x = ((x ◇ x) ◇ (x ◇ x)) ◇ y
equation 51178 := x ◇ x = ((x ◇ x) ◇ (x ◇ y)) ◇ x
equation 51179 := x ◇ x = ((x ◇ x) ◇ (x ◇ y)) ◇ y
equation 51180 := x ◇ x = ((x ◇ x) ◇ (x ◇ y)) ◇ z
equation 51181 := x ◇ x = ((x ◇ x) ◇ (y ◇ x)) ◇ x
equation 51182 := x ◇ x = ((x ◇ x) ◇ (y ◇ x)) ◇ y
equation 51183 := x ◇ x = ((x ◇ x) ◇ (y ◇ x)) ◇ z
equation 51184 := x ◇ x = ((x ◇ x) ◇ (y ◇ y)) ◇ x
equation 51185 := x ◇ x = ((x ◇ x) ◇ (y ◇ y)) ◇ y
equation 51186 := x ◇ x = ((x ◇ x) ◇ (y ◇ y)) ◇ z
equation 51187 := x ◇ x = ((x ◇ x) ◇ (y ◇ z)) ◇ x
equation 51188 := x ◇ x = ((x ◇ x) ◇ (y ◇ z)) ◇ y
equation 51189 := x ◇ x = ((x ◇ x) ◇ (y ◇ z)) ◇ z
equation 51190 := x ◇ x = ((x ◇ x) ◇ (y ◇ z)) ◇ w
equation 51191 := x ◇ x = ((x ◇ y) ◇ (x ◇ x)) ◇ x
equation 51192 := x ◇ x = ((x ◇ y) ◇ (x ◇ x)) ◇ y
equation 51193 := x ◇ x = ((x ◇ y) ◇ (x ◇ x)) ◇ z
equation 51194 := x ◇ x = ((x ◇ y) ◇ (x ◇ y)) ◇ x
equation 51195 := x ◇ x = ((x ◇ y) ◇ (x ◇ y)) ◇ y
equation 51196 := x ◇ x = ((x ◇ y) ◇ (x ◇ y)) ◇ z
equation 51197 := x ◇ x = ((x ◇ y) ◇ (x ◇ z)) ◇ x
equation 51198 := x ◇ x = ((x ◇ y) ◇ (x ◇ z)) ◇ y
equation 51199 := x ◇ x = ((x ◇ y) ◇ (x ◇ z)) ◇ z
equation 51200 := x ◇ x = ((x ◇ y) ◇ (x ◇ z)) ◇ w
equation 51201 := x ◇ x = ((x ◇ y) ◇ (y ◇ x)) ◇ x
equation 51202 := x ◇ x = ((x ◇ y) ◇ (y ◇ x)) ◇ y
equation 51203 := x ◇ x = ((x ◇ y) ◇ (y ◇ x)) ◇ z
equation 51204 := x ◇ x = ((x ◇ y) ◇ (y ◇ y)) ◇ x
equation 51205 := x ◇ x = ((x ◇ y) ◇ (y ◇ y)) ◇ y
equation 51206 := x ◇ x = ((x ◇ y) ◇ (y ◇ y)) ◇ z
equation 51207 := x ◇ x = ((x ◇ y) ◇ (y ◇ z)) ◇ x
equation 51208 := x ◇ x = ((x ◇ y) ◇ (y ◇ z)) ◇ y
equation 51209 := x ◇ x = ((x ◇ y) ◇ (y ◇ z)) ◇ z
equation 51210 := x ◇ x = ((x ◇ y) ◇ (y ◇ z)) ◇ w
equation 51211 := x ◇ x = ((x ◇ y) ◇ (z ◇ x)) ◇ x
equation 51212 := x ◇ x = ((x ◇ y) ◇ (z ◇ x)) ◇ y
equation 51213 := x ◇ x = ((x ◇ y) ◇ (z ◇ x)) ◇ z
equation 51214 := x ◇ x = ((x ◇ y) ◇ (z ◇ x)) ◇ w
equation 51215 := x ◇ x = ((x ◇ y) ◇ (z ◇ y)) ◇ x
equation 51216 := x ◇ x = ((x ◇ y) ◇ (z ◇ y)) ◇ y
equation 51217 := x ◇ x = ((x ◇ y) ◇ (z ◇ y)) ◇ z
equation 51218 := x ◇ x = ((x ◇ y) ◇ (z ◇ y)) ◇ w
equation 51219 := x ◇ x = ((x ◇ y) ◇ (z ◇ z)) ◇ x
equation 51220 := x ◇ x = ((x ◇ y) ◇ (z ◇ z)) ◇ y
equation 51221 := x ◇ x = ((x ◇ y) ◇ (z ◇ z)) ◇ z
equation 51222 := x ◇ x = ((x ◇ y) ◇ (z ◇ z)) ◇ w
equation 51223 := x ◇ x = ((x ◇ y) ◇ (z ◇ w)) ◇ x
equation 51224 := x ◇ x = ((x ◇ y) ◇ (z ◇ w)) ◇ y
equation 51225 := x ◇ x = ((x ◇ y) ◇ (z ◇ w)) ◇ z
equation 51226 := x ◇ x = ((x ◇ y) ◇ (z ◇ w)) ◇ w
equation 51227 := x ◇ x = ((x ◇ y) ◇ (z ◇ w)) ◇ u
equation 51228 := x ◇ x = ((y ◇ x) ◇ (x ◇ x)) ◇ x
equation 51229 := x ◇ x = ((y ◇ x) ◇ (x ◇ x)) ◇ y
equation 51230 := x ◇ x = ((y ◇ x) ◇ (x ◇ x)) ◇ z
equation 51231 := x ◇ x = ((y ◇ x) ◇ (x ◇ y)) ◇ x
equation 51232 := x ◇ x = ((y ◇ x) ◇ (x ◇ y)) ◇ y
equation 51233 := x ◇ x = ((y ◇ x) ◇ (x ◇ y)) ◇ z
equation 51234 := x ◇ x = ((y ◇ x) ◇ (x ◇ z)) ◇ x
equation 51235 := x ◇ x = ((y ◇ x) ◇ (x ◇ z)) ◇ y
equation 51236 := x ◇ x = ((y ◇ x) ◇ (x ◇ z)) ◇ z
equation 51237 := x ◇ x = ((y ◇ x) ◇ (x ◇ z)) ◇ w
equation 51238 := x ◇ x = ((y ◇ x) ◇ (y ◇ x)) ◇ x
equation 51239 := x ◇ x = ((y ◇ x) ◇ (y ◇ x)) ◇ y
equation 51240 := x ◇ x = ((y ◇ x) ◇ (y ◇ x)) ◇ z
equation 51241 := x ◇ x = ((y ◇ x) ◇ (y ◇ y)) ◇ x
equation 51242 := x ◇ x = ((y ◇ x) ◇ (y ◇ y)) ◇ y
equation 51243 := x ◇ x = ((y ◇ x) ◇ (y ◇ y)) ◇ z
equation 51244 := x ◇ x = ((y ◇ x) ◇ (y ◇ z)) ◇ x
equation 51245 := x ◇ x = ((y ◇ x) ◇ (y ◇ z)) ◇ y
equation 51246 := x ◇ x = ((y ◇ x) ◇ (y ◇ z)) ◇ z
equation 51247 := x ◇ x = ((y ◇ x) ◇ (y ◇ z)) ◇ w
equation 51248 := x ◇ x = ((y ◇ x) ◇ (z ◇ x)) ◇ x
equation 51249 := x ◇ x = ((y ◇ x) ◇ (z ◇ x)) ◇ y
equation 51250 := x ◇ x = ((y ◇ x) ◇ (z ◇ x)) ◇ z
equation 51251 := x ◇ x = ((y ◇ x) ◇ (z ◇ x)) ◇ w
equation 51252 := x ◇ x = ((y ◇ x) ◇ (z ◇ y)) ◇ x
equation 51253 := x ◇ x = ((y ◇ x) ◇ (z ◇ y)) ◇ y
equation 51254 := x ◇ x = ((y ◇ x) ◇ (z ◇ y)) ◇ z
equation 51255 := x ◇ x = ((y ◇ x) ◇ (z ◇ y)) ◇ w
equation 51256 := x ◇ x = ((y ◇ x) ◇ (z ◇ z)) ◇ x
equation 51257 := x ◇ x = ((y ◇ x) ◇ (z ◇ z)) ◇ y
equation 51258 := x ◇ x = ((y ◇ x) ◇ (z ◇ z)) ◇ z
equation 51259 := x ◇ x = ((y ◇ x) ◇ (z ◇ z)) ◇ w
equation 51260 := x ◇ x = ((y ◇ x) ◇ (z ◇ w)) ◇ x
equation 51261 := x ◇ x = ((y ◇ x) ◇ (z ◇ w)) ◇ y
equation 51262 := x ◇ x = ((y ◇ x) ◇ (z ◇ w)) ◇ z
equation 51263 := x ◇ x = ((y ◇ x) ◇ (z ◇ w)) ◇ w
equation 51264 := x ◇ x = ((y ◇ x) ◇ (z ◇ w)) ◇ u
equation 51265 := x ◇ x = ((y ◇ y) ◇ (x ◇ x)) ◇ x
equation 51266 := x ◇ x = ((y ◇ y) ◇ (x ◇ x)) ◇ y
equation 51267 := x ◇ x = ((y ◇ y) ◇ (x ◇ x)) ◇ z
equation 51268 := x ◇ x = ((y ◇ y) ◇ (x ◇ y)) ◇ x
equation 51269 := x ◇ x = ((y ◇ y) ◇ (x ◇ y)) ◇ y
equation 51270 := x ◇ x = ((y ◇ y) ◇ (x ◇ y)) ◇ z
equation 51271 := x ◇ x = ((y ◇ y) ◇ (x ◇ z)) ◇ x
equation 51272 := x ◇ x = ((y ◇ y) ◇ (x ◇ z)) ◇ y
equation 51273 := x ◇ x = ((y ◇ y) ◇ (x ◇ z)) ◇ z
equation 51274 := x ◇ x = ((y ◇ y) ◇ (x ◇ z)) ◇ w
equation 51275 := x ◇ x = ((y ◇ y) ◇ (y ◇ x)) ◇ x
equation 51276 := x ◇ x = ((y ◇ y) ◇ (y ◇ x)) ◇ y
equation 51277 := x ◇ x = ((y ◇ y) ◇ (y ◇ x)) ◇ z
equation 51278 := x ◇ x = ((y ◇ y) ◇ (y ◇ y)) ◇ x
equation 51279 := x ◇ x = ((y ◇ y) ◇ (y ◇ y)) ◇ y
equation 51280 := x ◇ x = ((y ◇ y) ◇ (y ◇ y)) ◇ z
equation 51281 := x ◇ x = ((y ◇ y) ◇ (y ◇ z)) ◇ x
equation 51282 := x ◇ x = ((y ◇ y) ◇ (y ◇ z)) ◇ y
equation 51283 := x ◇ x = ((y ◇ y) ◇ (y ◇ z)) ◇ z
equation 51284 := x ◇ x = ((y ◇ y) ◇ (y ◇ z)) ◇ w
equation 51285 := x ◇ x = ((y ◇ y) ◇ (z ◇ x)) ◇ x
equation 51286 := x ◇ x = ((y ◇ y) ◇ (z ◇ x)) ◇ y
equation 51287 := x ◇ x = ((y ◇ y) ◇ (z ◇ x)) ◇ z
equation 51288 := x ◇ x = ((y ◇ y) ◇ (z ◇ x)) ◇ w
equation 51289 := x ◇ x = ((y ◇ y) ◇ (z ◇ y)) ◇ x
equation 51290 := x ◇ x = ((y ◇ y) ◇ (z ◇ y)) ◇ y
equation 51291 := x ◇ x = ((y ◇ y) ◇ (z ◇ y)) ◇ z
equation 51292 := x ◇ x = ((y ◇ y) ◇ (z ◇ y)) ◇ w
equation 51293 := x ◇ x = ((y ◇ y) ◇ (z ◇ z)) ◇ x
equation 51294 := x ◇ x = ((y ◇ y) ◇ (z ◇ z)) ◇ y
equation 51295 := x ◇ x = ((y ◇ y) ◇ (z ◇ z)) ◇ z
equation 51296 := x ◇ x = ((y ◇ y) ◇ (z ◇ z)) ◇ w
equation 51297 := x ◇ x = ((y ◇ y) ◇ (z ◇ w)) ◇ x
equation 51298 := x ◇ x = ((y ◇ y) ◇ (z ◇ w)) ◇ y
equation 51299 := x ◇ x = ((y ◇ y) ◇ (z ◇ w)) ◇ z
equation 51300 := x ◇ x = ((y ◇ y) ◇ (z ◇ w)) ◇ w
equation 51301 := x ◇ x = ((y ◇ y) ◇ (z ◇ w)) ◇ u
equation 51302 := x ◇ x = ((y ◇ z) ◇ (x ◇ x)) ◇ x
equation 51303 := x ◇ x = ((y ◇ z) ◇ (x ◇ x)) ◇ y
equation 51304 := x ◇ x = ((y ◇ z) ◇ (x ◇ x)) ◇ z
equation 51305 := x ◇ x = ((y ◇ z) ◇ (x ◇ x)) ◇ w
equation 51306 := x ◇ x = ((y ◇ z) ◇ (x ◇ y)) ◇ x
equation 51307 := x ◇ x = ((y ◇ z) ◇ (x ◇ y)) ◇ y
equation 51308 := x ◇ x = ((y ◇ z) ◇ (x ◇ y)) ◇ z
equation 51309 := x ◇ x = ((y ◇ z) ◇ (x ◇ y)) ◇ w
equation 51310 := x ◇ x = ((y ◇ z) ◇ (x ◇ z)) ◇ x
equation 51311 := x ◇ x = ((y ◇ z) ◇ (x ◇ z)) ◇ y
equation 51312 := x ◇ x = ((y ◇ z) ◇ (x ◇ z)) ◇ z
equation 51313 := x ◇ x = ((y ◇ z) ◇ (x ◇ z)) ◇ w
equation 51314 := x ◇ x = ((y ◇ z) ◇ (x ◇ w)) ◇ x
equation 51315 := x ◇ x = ((y ◇ z) ◇ (x ◇ w)) ◇ y
equation 51316 := x ◇ x = ((y ◇ z) ◇ (x ◇ w)) ◇ z
equation 51317 := x ◇ x = ((y ◇ z) ◇ (x ◇ w)) ◇ w
equation 51318 := x ◇ x = ((y ◇ z) ◇ (x ◇ w)) ◇ u
equation 51319 := x ◇ x = ((y ◇ z) ◇ (y ◇ x)) ◇ x
equation 51320 := x ◇ x = ((y ◇ z) ◇ (y ◇ x)) ◇ y
equation 51321 := x ◇ x = ((y ◇ z) ◇ (y ◇ x)) ◇ z
equation 51322 := x ◇ x = ((y ◇ z) ◇ (y ◇ x)) ◇ w
equation 51323 := x ◇ x = ((y ◇ z) ◇ (y ◇ y)) ◇ x
equation 51324 := x ◇ x = ((y ◇ z) ◇ (y ◇ y)) ◇ y
equation 51325 := x ◇ x = ((y ◇ z) ◇ (y ◇ y)) ◇ z
equation 51326 := x ◇ x = ((y ◇ z) ◇ (y ◇ y)) ◇ w
equation 51327 := x ◇ x = ((y ◇ z) ◇ (y ◇ z)) ◇ x
equation 51328 := x ◇ x = ((y ◇ z) ◇ (y ◇ z)) ◇ y
equation 51329 := x ◇ x = ((y ◇ z) ◇ (y ◇ z)) ◇ z
equation 51330 := x ◇ x = ((y ◇ z) ◇ (y ◇ z)) ◇ w
equation 51331 := x ◇ x = ((y ◇ z) ◇ (y ◇ w)) ◇ x
equation 51332 := x ◇ x = ((y ◇ z) ◇ (y ◇ w)) ◇ y
equation 51333 := x ◇ x = ((y ◇ z) ◇ (y ◇ w)) ◇ z
equation 51334 := x ◇ x = ((y ◇ z) ◇ (y ◇ w)) ◇ w
equation 51335 := x ◇ x = ((y ◇ z) ◇ (y ◇ w)) ◇ u
equation 51336 := x ◇ x = ((y ◇ z) ◇ (z ◇ x)) ◇ x
equation 51337 := x ◇ x = ((y ◇ z) ◇ (z ◇ x)) ◇ y
equation 51338 := x ◇ x = ((y ◇ z) ◇ (z ◇ x)) ◇ z
equation 51339 := x ◇ x = ((y ◇ z) ◇ (z ◇ x)) ◇ w
equation 51340 := x ◇ x = ((y ◇ z) ◇ (z ◇ y)) ◇ x
equation 51341 := x ◇ x = ((y ◇ z) ◇ (z ◇ y)) ◇ y
equation 51342 := x ◇ x = ((y ◇ z) ◇ (z ◇ y)) ◇ z
equation 51343 := x ◇ x = ((y ◇ z) ◇ (z ◇ y)) ◇ w
equation 51344 := x ◇ x = ((y ◇ z) ◇ (z ◇ z)) ◇ x
equation 51345 := x ◇ x = ((y ◇ z) ◇ (z ◇ z)) ◇ y
equation 51346 := x ◇ x = ((y ◇ z) ◇ (z ◇ z)) ◇ z
equation 51347 := x ◇ x = ((y ◇ z) ◇ (z ◇ z)) ◇ w
equation 51348 := x ◇ x = ((y ◇ z) ◇ (z ◇ w)) ◇ x
equation 51349 := x ◇ x = ((y ◇ z) ◇ (z ◇ w)) ◇ y
equation 51350 := x ◇ x = ((y ◇ z) ◇ (z ◇ w)) ◇ z
equation 51351 := x ◇ x = ((y ◇ z) ◇ (z ◇ w)) ◇ w
equation 51352 := x ◇ x = ((y ◇ z) ◇ (z ◇ w)) ◇ u
equation 51353 := x ◇ x = ((y ◇ z) ◇ (w ◇ x)) ◇ x
equation 51354 := x ◇ x = ((y ◇ z) ◇ (w ◇ x)) ◇ y
equation 51355 := x ◇ x = ((y ◇ z) ◇ (w ◇ x)) ◇ z
equation 51356 := x ◇ x = ((y ◇ z) ◇ (w ◇ x)) ◇ w
equation 51357 := x ◇ x = ((y ◇ z) ◇ (w ◇ x)) ◇ u
equation 51358 := x ◇ x = ((y ◇ z) ◇ (w ◇ y)) ◇ x
equation 51359 := x ◇ x = ((y ◇ z) ◇ (w ◇ y)) ◇ y
equation 51360 := x ◇ x = ((y ◇ z) ◇ (w ◇ y)) ◇ z
equation 51361 := x ◇ x = ((y ◇ z) ◇ (w ◇ y)) ◇ w
equation 51362 := x ◇ x = ((y ◇ z) ◇ (w ◇ y)) ◇ u
equation 51363 := x ◇ x = ((y ◇ z) ◇ (w ◇ z)) ◇ x
equation 51364 := x ◇ x = ((y ◇ z) ◇ (w ◇ z)) ◇ y
equation 51365 := x ◇ x = ((y ◇ z) ◇ (w ◇ z)) ◇ z
equation 51366 := x ◇ x = ((y ◇ z) ◇ (w ◇ z)) ◇ w
equation 51367 := x ◇ x = ((y ◇ z) ◇ (w ◇ z)) ◇ u
equation 51368 := x ◇ x = ((y ◇ z) ◇ (w ◇ w)) ◇ x
equation 51369 := x ◇ x = ((y ◇ z) ◇ (w ◇ w)) ◇ y
equation 51370 := x ◇ x = ((y ◇ z) ◇ (w ◇ w)) ◇ z
equation 51371 := x ◇ x = ((y ◇ z) ◇ (w ◇ w)) ◇ w
equation 51372 := x ◇ x = ((y ◇ z) ◇ (w ◇ w)) ◇ u
equation 51373 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ x
equation 51374 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ y
equation 51375 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ z
equation 51376 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ w
equation 51377 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ u
equation 51378 := x ◇ x = ((y ◇ z) ◇ (w ◇ u)) ◇ v
equation 51379 := x ◇ y = ((x ◇ x) ◇ (x ◇ x)) ◇ x
equation 51380 := x ◇ y = ((x ◇ x) ◇ (x ◇ x)) ◇ y
equation 51381 := x ◇ y = ((x ◇ x) ◇ (x ◇ x)) ◇ z
equation 51382 := x ◇ y = ((x ◇ x) ◇ (x ◇ y)) ◇ x
equation 51383 := x ◇ y = ((x ◇ x) ◇ (x ◇ y)) ◇ y
equation 51384 := x ◇ y = ((x ◇ x) ◇ (x ◇ y)) ◇ z
equation 51385 := x ◇ y = ((x ◇ x) ◇ (x ◇ z)) ◇ x
equation 51386 := x ◇ y = ((x ◇ x) ◇ (x ◇ z)) ◇ y
equation 51387 := x ◇ y = ((x ◇ x) ◇ (x ◇ z)) ◇ z
equation 51388 := x ◇ y = ((x ◇ x) ◇ (x ◇ z)) ◇ w
equation 51389 := x ◇ y = ((x ◇ x) ◇ (y ◇ x)) ◇ x
equation 51390 := x ◇ y = ((x ◇ x) ◇ (y ◇ x)) ◇ y
equation 51391 := x ◇ y = ((x ◇ x) ◇ (y ◇ x)) ◇ z
equation 51392 := x ◇ y = ((x ◇ x) ◇ (y ◇ y)) ◇ x
equation 51393 := x ◇ y = ((x ◇ x) ◇ (y ◇ y)) ◇ y
equation 51394 := x ◇ y = ((x ◇ x) ◇ (y ◇ y)) ◇ z
equation 51395 := x ◇ y = ((x ◇ x) ◇ (y ◇ z)) ◇ x
equation 51396 := x ◇ y = ((x ◇ x) ◇ (y ◇ z)) ◇ y
equation 51397 := x ◇ y = ((x ◇ x) ◇ (y ◇ z)) ◇ z
equation 51398 := x ◇ y = ((x ◇ x) ◇ (y ◇ z)) ◇ w
equation 51399 := x ◇ y = ((x ◇ x) ◇ (z ◇ x)) ◇ x
equation 51400 := x ◇ y = ((x ◇ x) ◇ (z ◇ x)) ◇ y
equation 51401 := x ◇ y = ((x ◇ x) ◇ (z ◇ x)) ◇ z
equation 51402 := x ◇ y = ((x ◇ x) ◇ (z ◇ x)) ◇ w
equation 51403 := x ◇ y = ((x ◇ x) ◇ (z ◇ y)) ◇ x
equation 51404 := x ◇ y = ((x ◇ x) ◇ (z ◇ y)) ◇ y
equation 51405 := x ◇ y = ((x ◇ x) ◇ (z ◇ y)) ◇ z
equation 51406 := x ◇ y = ((x ◇ x) ◇ (z ◇ y)) ◇ w
equation 51407 := x ◇ y = ((x ◇ x) ◇ (z ◇ z)) ◇ x
equation 51408 := x ◇ y = ((x ◇ x) ◇ (z ◇ z)) ◇ y
equation 51409 := x ◇ y = ((x ◇ x) ◇ (z ◇ z)) ◇ z
equation 51410 := x ◇ y = ((x ◇ x) ◇ (z ◇ z)) ◇ w
equation 51411 := x ◇ y = ((x ◇ x) ◇ (z ◇ w)) ◇ x
equation 51412 := x ◇ y = ((x ◇ x) ◇ (z ◇ w)) ◇ y
equation 51413 := x ◇ y = ((x ◇ x) ◇ (z ◇ w)) ◇ z
equation 51414 := x ◇ y = ((x ◇ x) ◇ (z ◇ w)) ◇ w
equation 51415 := x ◇ y = ((x ◇ x) ◇ (z ◇ w)) ◇ u
equation 51416 := x ◇ y = ((x ◇ y) ◇ (x ◇ x)) ◇ x
equation 51417 := x ◇ y = ((x ◇ y) ◇ (x ◇ x)) ◇ y
equation 51418 := x ◇ y = ((x ◇ y) ◇ (x ◇ x)) ◇ z
equation 51419 := x ◇ y = ((x ◇ y) ◇ (x ◇ y)) ◇ x
equation 51420 := x ◇ y = ((x ◇ y) ◇ (x ◇ y)) ◇ y
equation 51421 := x ◇ y = ((x ◇ y) ◇ (x ◇ y)) ◇ z
equation 51422 := x ◇ y = ((x ◇ y) ◇ (x ◇ z)) ◇ x
equation 51423 := x ◇ y = ((x ◇ y) ◇ (x ◇ z)) ◇ y
equation 51424 := x ◇ y = ((x ◇ y) ◇ (x ◇ z)) ◇ z
equation 51425 := x ◇ y = ((x ◇ y) ◇ (x ◇ z)) ◇ w
equation 51426 := x ◇ y = ((x ◇ y) ◇ (y ◇ x)) ◇ x
equation 51427 := x ◇ y = ((x ◇ y) ◇ (y ◇ x)) ◇ y
equation 51428 := x ◇ y = ((x ◇ y) ◇ (y ◇ x)) ◇ z
equation 51429 := x ◇ y = ((x ◇ y) ◇ (y ◇ y)) ◇ x
equation 51430 := x ◇ y = ((x ◇ y) ◇ (y ◇ y)) ◇ y
equation 51431 := x ◇ y = ((x ◇ y) ◇ (y ◇ y)) ◇ z
equation 51432 := x ◇ y = ((x ◇ y) ◇ (y ◇ z)) ◇ x
equation 51433 := x ◇ y = ((x ◇ y) ◇ (y ◇ z)) ◇ y
equation 51434 := x ◇ y = ((x ◇ y) ◇ (y ◇ z)) ◇ z
equation 51435 := x ◇ y = ((x ◇ y) ◇ (y ◇ z)) ◇ w
equation 51436 := x ◇ y = ((x ◇ y) ◇ (z ◇ x)) ◇ x
equation 51437 := x ◇ y = ((x ◇ y) ◇ (z ◇ x)) ◇ y
equation 51438 := x ◇ y = ((x ◇ y) ◇ (z ◇ x)) ◇ z
equation 51439 := x ◇ y = ((x ◇ y) ◇ (z ◇ x)) ◇ w
equation 51440 := x ◇ y = ((x ◇ y) ◇ (z ◇ y)) ◇ x
equation 51441 := x ◇ y = ((x ◇ y) ◇ (z ◇ y)) ◇ y
equation 51442 := x ◇ y = ((x ◇ y) ◇ (z ◇ y)) ◇ z
equation 51443 := x ◇ y = ((x ◇ y) ◇ (z ◇ y)) ◇ w
equation 51444 := x ◇ y = ((x ◇ y) ◇ (z ◇ z)) ◇ x
equation 51445 := x ◇ y = ((x ◇ y) ◇ (z ◇ z)) ◇ y
equation 51446 := x ◇ y = ((x ◇ y) ◇ (z ◇ z)) ◇ z
equation 51447 := x ◇ y = ((x ◇ y) ◇ (z ◇ z)) ◇ w
equation 51448 := x ◇ y = ((x ◇ y) ◇ (z ◇ w)) ◇ x
equation 51449 := x ◇ y = ((x ◇ y) ◇ (z ◇ w)) ◇ y
equation 51450 := x ◇ y = ((x ◇ y) ◇ (z ◇ w)) ◇ z
equation 51451 := x ◇ y = ((x ◇ y) ◇ (z ◇ w)) ◇ w
equation 51452 := x ◇ y = ((x ◇ y) ◇ (z ◇ w)) ◇ u
equation 51453 := x ◇ y = ((x ◇ z) ◇ (x ◇ x)) ◇ x
equation 51454 := x ◇ y = ((x ◇ z) ◇ (x ◇ x)) ◇ y
equation 51455 := x ◇ y = ((x ◇ z) ◇ (x ◇ x)) ◇ z
equation 51456 := x ◇ y = ((x ◇ z) ◇ (x ◇ x)) ◇ w
equation 51457 := x ◇ y = ((x ◇ z) ◇ (x ◇ y)) ◇ x
equation 51458 := x ◇ y = ((x ◇ z) ◇ (x ◇ y)) ◇ y
equation 51459 := x ◇ y = ((x ◇ z) ◇ (x ◇ y)) ◇ z
equation 51460 := x ◇ y = ((x ◇ z) ◇ (x ◇ y)) ◇ w
equation 51461 := x ◇ y = ((x ◇ z) ◇ (x ◇ z)) ◇ x
equation 51462 := x ◇ y = ((x ◇ z) ◇ (x ◇ z)) ◇ y
equation 51463 := x ◇ y = ((x ◇ z) ◇ (x ◇ z)) ◇ z
equation 51464 := x ◇ y = ((x ◇ z) ◇ (x ◇ z)) ◇ w
equation 51465 := x ◇ y = ((x ◇ z) ◇ (x ◇ w)) ◇ x
equation 51466 := x ◇ y = ((x ◇ z) ◇ (x ◇ w)) ◇ y
equation 51467 := x ◇ y = ((x ◇ z) ◇ (x ◇ w)) ◇ z
equation 51468 := x ◇ y = ((x ◇ z) ◇ (x ◇ w)) ◇ w
equation 51469 := x ◇ y = ((x ◇ z) ◇ (x ◇ w)) ◇ u
equation 51470 := x ◇ y = ((x ◇ z) ◇ (y ◇ x)) ◇ x
equation 51471 := x ◇ y = ((x ◇ z) ◇ (y ◇ x)) ◇ y
equation 51472 := x ◇ y = ((x ◇ z) ◇ (y ◇ x)) ◇ z
equation 51473 := x ◇ y = ((x ◇ z) ◇ (y ◇ x)) ◇ w
equation 51474 := x ◇ y = ((x ◇ z) ◇ (y ◇ y)) ◇ x
equation 51475 := x ◇ y = ((x ◇ z) ◇ (y ◇ y)) ◇ y
equation 51476 := x ◇ y = ((x ◇ z) ◇ (y ◇ y)) ◇ z
equation 51477 := x ◇ y = ((x ◇ z) ◇ (y ◇ y)) ◇ w
equation 51478 := x ◇ y = ((x ◇ z) ◇ (y ◇ z)) ◇ x
equation 51479 := x ◇ y = ((x ◇ z) ◇ (y ◇ z)) ◇ y
equation 51480 := x ◇ y = ((x ◇ z) ◇ (y ◇ z)) ◇ z
equation 51481 := x ◇ y = ((x ◇ z) ◇ (y ◇ z)) ◇ w
equation 51482 := x ◇ y = ((x ◇ z) ◇ (y ◇ w)) ◇ x
equation 51483 := x ◇ y = ((x ◇ z) ◇ (y ◇ w)) ◇ y
equation 51484 := x ◇ y = ((x ◇ z) ◇ (y ◇ w)) ◇ z
equation 51485 := x ◇ y = ((x ◇ z) ◇ (y ◇ w)) ◇ w
equation 51486 := x ◇ y = ((x ◇ z) ◇ (y ◇ w)) ◇ u
equation 51487 := x ◇ y = ((x ◇ z) ◇ (z ◇ x)) ◇ x
equation 51488 := x ◇ y = ((x ◇ z) ◇ (z ◇ x)) ◇ y
equation 51489 := x ◇ y = ((x ◇ z) ◇ (z ◇ x)) ◇ z
equation 51490 := x ◇ y = ((x ◇ z) ◇ (z ◇ x)) ◇ w
equation 51491 := x ◇ y = ((x ◇ z) ◇ (z ◇ y)) ◇ x
equation 51492 := x ◇ y = ((x ◇ z) ◇ (z ◇ y)) ◇ y
equation 51493 := x ◇ y = ((x ◇ z) ◇ (z ◇ y)) ◇ z
equation 51494 := x ◇ y = ((x ◇ z) ◇ (z ◇ y)) ◇ w
equation 51495 := x ◇ y = ((x ◇ z) ◇ (z ◇ z)) ◇ x
equation 51496 := x ◇ y = ((x ◇ z) ◇ (z ◇ z)) ◇ y
equation 51497 := x ◇ y = ((x ◇ z) ◇ (z ◇ z)) ◇ z
equation 51498 := x ◇ y = ((x ◇ z) ◇ (z ◇ z)) ◇ w
equation 51499 := x ◇ y = ((x ◇ z) ◇ (z ◇ w)) ◇ x
equation 51500 := x ◇ y = ((x ◇ z) ◇ (z ◇ w)) ◇ y
equation 51501 := x ◇ y = ((x ◇ z) ◇ (z ◇ w)) ◇ z
equation 51502 := x ◇ y = ((x ◇ z) ◇ (z ◇ w)) ◇ w
equation 51503 := x ◇ y = ((x ◇ z) ◇ (z ◇ w)) ◇ u
equation 51504 := x ◇ y = ((x ◇ z) ◇ (w ◇ x)) ◇ x
equation 51505 := x ◇ y = ((x ◇ z) ◇ (w ◇ x)) ◇ y
equation 51506 := x ◇ y = ((x ◇ z) ◇ (w ◇ x)) ◇ z
equation 51507 := x ◇ y = ((x ◇ z) ◇ (w ◇ x)) ◇ w
equation 51508 := x ◇ y = ((x ◇ z) ◇ (w ◇ x)) ◇ u
equation 51509 := x ◇ y = ((x ◇ z) ◇ (w ◇ y)) ◇ x
equation 51510 := x ◇ y = ((x ◇ z) ◇ (w ◇ y)) ◇ y
equation 51511 := x ◇ y = ((x ◇ z) ◇ (w ◇ y)) ◇ z
equation 51512 := x ◇ y = ((x ◇ z) ◇ (w ◇ y)) ◇ w
equation 51513 := x ◇ y = ((x ◇ z) ◇ (w ◇ y)) ◇ u
equation 51514 := x ◇ y = ((x ◇ z) ◇ (w ◇ z)) ◇ x
equation 51515 := x ◇ y = ((x ◇ z) ◇ (w ◇ z)) ◇ y
equation 51516 := x ◇ y = ((x ◇ z) ◇ (w ◇ z)) ◇ z
equation 51517 := x ◇ y = ((x ◇ z) ◇ (w ◇ z)) ◇ w
equation 51518 := x ◇ y = ((x ◇ z) ◇ (w ◇ z)) ◇ u
equation 51519 := x ◇ y = ((x ◇ z) ◇ (w ◇ w)) ◇ x
equation 51520 := x ◇ y = ((x ◇ z) ◇ (w ◇ w)) ◇ y
equation 51521 := x ◇ y = ((x ◇ z) ◇ (w ◇ w)) ◇ z
equation 51522 := x ◇ y = ((x ◇ z) ◇ (w ◇ w)) ◇ w
equation 51523 := x ◇ y = ((x ◇ z) ◇ (w ◇ w)) ◇ u
equation 51524 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ x
equation 51525 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ y
equation 51526 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ z
equation 51527 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ w
equation 51528 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ u
equation 51529 := x ◇ y = ((x ◇ z) ◇ (w ◇ u)) ◇ v
equation 51530 := x ◇ y = ((y ◇ x) ◇ (x ◇ x)) ◇ x
equation 51531 := x ◇ y = ((y ◇ x) ◇ (x ◇ x)) ◇ y
equation 51532 := x ◇ y = ((y ◇ x) ◇ (x ◇ x)) ◇ z
equation 51533 := x ◇ y = ((y ◇ x) ◇ (x ◇ y)) ◇ x
equation 51534 := x ◇ y = ((y ◇ x) ◇ (x ◇ y)) ◇ y
equation 51535 := x ◇ y = ((y ◇ x) ◇ (x ◇ y)) ◇ z
equation 51536 := x ◇ y = ((y ◇ x) ◇ (x ◇ z)) ◇ x
equation 51537 := x ◇ y = ((y ◇ x) ◇ (x ◇ z)) ◇ y
equation 51538 := x ◇ y = ((y ◇ x) ◇ (x ◇ z)) ◇ z
equation 51539 := x ◇ y = ((y ◇ x) ◇ (x ◇ z)) ◇ w
equation 51540 := x ◇ y = ((y ◇ x) ◇ (y ◇ x)) ◇ x
equation 51541 := x ◇ y = ((y ◇ x) ◇ (y ◇ x)) ◇ y
equation 51542 := x ◇ y = ((y ◇ x) ◇ (y ◇ x)) ◇ z
equation 51543 := x ◇ y = ((y ◇ x) ◇ (y ◇ y)) ◇ x
equation 51544 := x ◇ y = ((y ◇ x) ◇ (y ◇ y)) ◇ y
equation 51545 := x ◇ y = ((y ◇ x) ◇ (y ◇ y)) ◇ z
equation 51546 := x ◇ y = ((y ◇ x) ◇ (y ◇ z)) ◇ x
equation 51547 := x ◇ y = ((y ◇ x) ◇ (y ◇ z)) ◇ y
equation 51548 := x ◇ y = ((y ◇ x) ◇ (y ◇ z)) ◇ z
equation 51549 := x ◇ y = ((y ◇ x) ◇ (y ◇ z)) ◇ w
equation 51550 := x ◇ y = ((y ◇ x) ◇ (z ◇ x)) ◇ x
equation 51551 := x ◇ y = ((y ◇ x) ◇ (z ◇ x)) ◇ y
equation 51552 := x ◇ y = ((y ◇ x) ◇ (z ◇ x)) ◇ z
equation 51553 := x ◇ y = ((y ◇ x) ◇ (z ◇ x)) ◇ w
equation 51554 := x ◇ y = ((y ◇ x) ◇ (z ◇ y)) ◇ x
equation 51555 := x ◇ y = ((y ◇ x) ◇ (z ◇ y)) ◇ y
equation 51556 := x ◇ y = ((y ◇ x) ◇ (z ◇ y)) ◇ z
equation 51557 := x ◇ y = ((y ◇ x) ◇ (z ◇ y)) ◇ w
equation 51558 := x ◇ y = ((y ◇ x) ◇ (z ◇ z)) ◇ x
equation 51559 := x ◇ y = ((y ◇ x) ◇ (z ◇ z)) ◇ y
equation 51560 := x ◇ y = ((y ◇ x) ◇ (z ◇ z)) ◇ z
equation 51561 := x ◇ y = ((y ◇ x) ◇ (z ◇ z)) ◇ w
equation 51562 := x ◇ y = ((y ◇ x) ◇ (z ◇ w)) ◇ x
equation 51563 := x ◇ y = ((y ◇ x) ◇ (z ◇ w)) ◇ y
equation 51564 := x ◇ y = ((y ◇ x) ◇ (z ◇ w)) ◇ z
equation 51565 := x ◇ y = ((y ◇ x) ◇ (z ◇ w)) ◇ w
equation 51566 := x ◇ y = ((y ◇ x) ◇ (z ◇ w)) ◇ u
equation 51567 := x ◇ y = ((y ◇ y) ◇ (x ◇ x)) ◇ x
equation 51568 := x ◇ y = ((y ◇ y) ◇ (x ◇ x)) ◇ y
equation 51569 := x ◇ y = ((y ◇ y) ◇ (x ◇ x)) ◇ z
equation 51570 := x ◇ y = ((y ◇ y) ◇ (x ◇ y)) ◇ x
equation 51571 := x ◇ y = ((y ◇ y) ◇ (x ◇ y)) ◇ y
equation 51572 := x ◇ y = ((y ◇ y) ◇ (x ◇ y)) ◇ z
equation 51573 := x ◇ y = ((y ◇ y) ◇ (x ◇ z)) ◇ x
equation 51574 := x ◇ y = ((y ◇ y) ◇ (x ◇ z)) ◇ y
equation 51575 := x ◇ y = ((y ◇ y) ◇ (x ◇ z)) ◇ z
equation 51576 := x ◇ y = ((y ◇ y) ◇ (x ◇ z)) ◇ w
equation 51577 := x ◇ y = ((y ◇ y) ◇ (y ◇ x)) ◇ x
equation 51578 := x ◇ y = ((y ◇ y) ◇ (y ◇ x)) ◇ y
equation 51579 := x ◇ y = ((y ◇ y) ◇ (y ◇ x)) ◇ z
equation 51580 := x ◇ y = ((y ◇ y) ◇ (y ◇ y)) ◇ x
equation 51581 := x ◇ y = ((y ◇ y) ◇ (y ◇ y)) ◇ y
equation 51582 := x ◇ y = ((y ◇ y) ◇ (y ◇ y)) ◇ z
equation 51583 := x ◇ y = ((y ◇ y) ◇ (y ◇ z)) ◇ x
equation 51584 := x ◇ y = ((y ◇ y) ◇ (y ◇ z)) ◇ y
equation 51585 := x ◇ y = ((y ◇ y) ◇ (y ◇ z)) ◇ z
equation 51586 := x ◇ y = ((y ◇ y) ◇ (y ◇ z)) ◇ w
equation 51587 := x ◇ y = ((y ◇ y) ◇ (z ◇ x)) ◇ x
equation 51588 := x ◇ y = ((y ◇ y) ◇ (z ◇ x)) ◇ y
equation 51589 := x ◇ y = ((y ◇ y) ◇ (z ◇ x)) ◇ z
equation 51590 := x ◇ y = ((y ◇ y) ◇ (z ◇ x)) ◇ w
equation 51591 := x ◇ y = ((y ◇ y) ◇ (z ◇ y)) ◇ x
equation 51592 := x ◇ y = ((y ◇ y) ◇ (z ◇ y)) ◇ y
equation 51593 := x ◇ y = ((y ◇ y) ◇ (z ◇ y)) ◇ z
equation 51594 := x ◇ y = ((y ◇ y) ◇ (z ◇ y)) ◇ w
equation 51595 := x ◇ y = ((y ◇ y) ◇ (z ◇ z)) ◇ x
equation 51596 := x ◇ y = ((y ◇ y) ◇ (z ◇ z)) ◇ y
equation 51597 := x ◇ y = ((y ◇ y) ◇ (z ◇ z)) ◇ z
equation 51598 := x ◇ y = ((y ◇ y) ◇ (z ◇ z)) ◇ w
equation 51599 := x ◇ y = ((y ◇ y) ◇ (z ◇ w)) ◇ x
equation 51600 := x ◇ y = ((y ◇ y) ◇ (z ◇ w)) ◇ y
equation 51601 := x ◇ y = ((y ◇ y) ◇ (z ◇ w)) ◇ z
equation 51602 := x ◇ y = ((y ◇ y) ◇ (z ◇ w)) ◇ w
equation 51603 := x ◇ y = ((y ◇ y) ◇ (z ◇ w)) ◇ u
equation 51604 := x ◇ y = ((y ◇ z) ◇ (x ◇ x)) ◇ x
equation 51605 := x ◇ y = ((y ◇ z) ◇ (x ◇ x)) ◇ y
equation 51606 := x ◇ y = ((y ◇ z) ◇ (x ◇ x)) ◇ z
equation 51607 := x ◇ y = ((y ◇ z) ◇ (x ◇ x)) ◇ w
equation 51608 := x ◇ y = ((y ◇ z) ◇ (x ◇ y)) ◇ x
equation 51609 := x ◇ y = ((y ◇ z) ◇ (x ◇ y)) ◇ y
equation 51610 := x ◇ y = ((y ◇ z) ◇ (x ◇ y)) ◇ z
equation 51611 := x ◇ y = ((y ◇ z) ◇ (x ◇ y)) ◇ w
equation 51612 := x ◇ y = ((y ◇ z) ◇ (x ◇ z)) ◇ x
equation 51613 := x ◇ y = ((y ◇ z) ◇ (x ◇ z)) ◇ y
equation 51614 := x ◇ y = ((y ◇ z) ◇ (x ◇ z)) ◇ z
equation 51615 := x ◇ y = ((y ◇ z) ◇ (x ◇ z)) ◇ w
equation 51616 := x ◇ y = ((y ◇ z) ◇ (x ◇ w)) ◇ x
equation 51617 := x ◇ y = ((y ◇ z) ◇ (x ◇ w)) ◇ y
equation 51618 := x ◇ y = ((y ◇ z) ◇ (x ◇ w)) ◇ z
equation 51619 := x ◇ y = ((y ◇ z) ◇ (x ◇ w)) ◇ w
equation 51620 := x ◇ y = ((y ◇ z) ◇ (x ◇ w)) ◇ u
equation 51621 := x ◇ y = ((y ◇ z) ◇ (y ◇ x)) ◇ x
equation 51622 := x ◇ y = ((y ◇ z) ◇ (y ◇ x)) ◇ y
equation 51623 := x ◇ y = ((y ◇ z) ◇ (y ◇ x)) ◇ z
equation 51624 := x ◇ y = ((y ◇ z) ◇ (y ◇ x)) ◇ w
equation 51625 := x ◇ y = ((y ◇ z) ◇ (y ◇ y)) ◇ x
equation 51626 := x ◇ y = ((y ◇ z) ◇ (y ◇ y)) ◇ y
equation 51627 := x ◇ y = ((y ◇ z) ◇ (y ◇ y)) ◇ z
equation 51628 := x ◇ y = ((y ◇ z) ◇ (y ◇ y)) ◇ w
equation 51629 := x ◇ y = ((y ◇ z) ◇ (y ◇ z)) ◇ x
equation 51630 := x ◇ y = ((y ◇ z) ◇ (y ◇ z)) ◇ y
equation 51631 := x ◇ y = ((y ◇ z) ◇ (y ◇ z)) ◇ z
equation 51632 := x ◇ y = ((y ◇ z) ◇ (y ◇ z)) ◇ w
equation 51633 := x ◇ y = ((y ◇ z) ◇ (y ◇ w)) ◇ x
equation 51634 := x ◇ y = ((y ◇ z) ◇ (y ◇ w)) ◇ y
equation 51635 := x ◇ y = ((y ◇ z) ◇ (y ◇ w)) ◇ z
equation 51636 := x ◇ y = ((y ◇ z) ◇ (y ◇ w)) ◇ w
equation 51637 := x ◇ y = ((y ◇ z) ◇ (y ◇ w)) ◇ u
equation 51638 := x ◇ y = ((y ◇ z) ◇ (z ◇ x)) ◇ x
equation 51639 := x ◇ y = ((y ◇ z) ◇ (z ◇ x)) ◇ y
equation 51640 := x ◇ y = ((y ◇ z) ◇ (z ◇ x)) ◇ z
equation 51641 := x ◇ y = ((y ◇ z) ◇ (z ◇ x)) ◇ w
equation 51642 := x ◇ y = ((y ◇ z) ◇ (z ◇ y)) ◇ x
equation 51643 := x ◇ y = ((y ◇ z) ◇ (z ◇ y)) ◇ y
equation 51644 := x ◇ y = ((y ◇ z) ◇ (z ◇ y)) ◇ z
equation 51645 := x ◇ y = ((y ◇ z) ◇ (z ◇ y)) ◇ w
equation 51646 := x ◇ y = ((y ◇ z) ◇ (z ◇ z)) ◇ x
equation 51647 := x ◇ y = ((y ◇ z) ◇ (z ◇ z)) ◇ y
equation 51648 := x ◇ y = ((y ◇ z) ◇ (z ◇ z)) ◇ z
equation 51649 := x ◇ y = ((y ◇ z) ◇ (z ◇ z)) ◇ w
equation 51650 := x ◇ y = ((y ◇ z) ◇ (z ◇ w)) ◇ x
equation 51651 := x ◇ y = ((y ◇ z) ◇ (z ◇ w)) ◇ y
equation 51652 := x ◇ y = ((y ◇ z) ◇ (z ◇ w)) ◇ z
equation 51653 := x ◇ y = ((y ◇ z) ◇ (z ◇ w)) ◇ w
equation 51654 := x ◇ y = ((y ◇ z) ◇ (z ◇ w)) ◇ u
equation 51655 := x ◇ y = ((y ◇ z) ◇ (w ◇ x)) ◇ x
equation 51656 := x ◇ y = ((y ◇ z) ◇ (w ◇ x)) ◇ y
equation 51657 := x ◇ y = ((y ◇ z) ◇ (w ◇ x)) ◇ z
equation 51658 := x ◇ y = ((y ◇ z) ◇ (w ◇ x)) ◇ w
equation 51659 := x ◇ y = ((y ◇ z) ◇ (w ◇ x)) ◇ u
equation 51660 := x ◇ y = ((y ◇ z) ◇ (w ◇ y)) ◇ x
equation 51661 := x ◇ y = ((y ◇ z) ◇ (w ◇ y)) ◇ y
equation 51662 := x ◇ y = ((y ◇ z) ◇ (w ◇ y)) ◇ z
equation 51663 := x ◇ y = ((y ◇ z) ◇ (w ◇ y)) ◇ w
equation 51664 := x ◇ y = ((y ◇ z) ◇ (w ◇ y)) ◇ u
equation 51665 := x ◇ y = ((y ◇ z) ◇ (w ◇ z)) ◇ x
equation 51666 := x ◇ y = ((y ◇ z) ◇ (w ◇ z)) ◇ y
equation 51667 := x ◇ y = ((y ◇ z) ◇ (w ◇ z)) ◇ z
equation 51668 := x ◇ y = ((y ◇ z) ◇ (w ◇ z)) ◇ w
equation 51669 := x ◇ y = ((y ◇ z) ◇ (w ◇ z)) ◇ u
equation 51670 := x ◇ y = ((y ◇ z) ◇ (w ◇ w)) ◇ x
equation 51671 := x ◇ y = ((y ◇ z) ◇ (w ◇ w)) ◇ y
equation 51672 := x ◇ y = ((y ◇ z) ◇ (w ◇ w)) ◇ z
equation 51673 := x ◇ y = ((y ◇ z) ◇ (w ◇ w)) ◇ w
equation 51674 := x ◇ y = ((y ◇ z) ◇ (w ◇ w)) ◇ u
equation 51675 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ x
equation 51676 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ y
equation 51677 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ z
equation 51678 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ w
equation 51679 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ u
equation 51680 := x ◇ y = ((y ◇ z) ◇ (w ◇ u)) ◇ v
equation 51681 := x ◇ y = ((z ◇ x) ◇ (x ◇ x)) ◇ x
equation 51682 := x ◇ y = ((z ◇ x) ◇ (x ◇ x)) ◇ y
equation 51683 := x ◇ y = ((z ◇ x) ◇ (x ◇ x)) ◇ z
equation 51684 := x ◇ y = ((z ◇ x) ◇ (x ◇ x)) ◇ w
equation 51685 := x ◇ y = ((z ◇ x) ◇ (x ◇ y)) ◇ x
equation 51686 := x ◇ y = ((z ◇ x) ◇ (x ◇ y)) ◇ y
equation 51687 := x ◇ y = ((z ◇ x) ◇ (x ◇ y)) ◇ z
equation 51688 := x ◇ y = ((z ◇ x) ◇ (x ◇ y)) ◇ w
equation 51689 := x ◇ y = ((z ◇ x) ◇ (x ◇ z)) ◇ x
equation 51690 := x ◇ y = ((z ◇ x) ◇ (x ◇ z)) ◇ y
equation 51691 := x ◇ y = ((z ◇ x) ◇ (x ◇ z)) ◇ z
equation 51692 := x ◇ y = ((z ◇ x) ◇ (x ◇ z)) ◇ w
equation 51693 := x ◇ y = ((z ◇ x) ◇ (x ◇ w)) ◇ x
equation 51694 := x ◇ y = ((z ◇ x) ◇ (x ◇ w)) ◇ y
equation 51695 := x ◇ y = ((z ◇ x) ◇ (x ◇ w)) ◇ z
equation 51696 := x ◇ y = ((z ◇ x) ◇ (x ◇ w)) ◇ w
equation 51697 := x ◇ y = ((z ◇ x) ◇ (x ◇ w)) ◇ u
equation 51698 := x ◇ y = ((z ◇ x) ◇ (y ◇ x)) ◇ x
equation 51699 := x ◇ y = ((z ◇ x) ◇ (y ◇ x)) ◇ y
equation 51700 := x ◇ y = ((z ◇ x) ◇ (y ◇ x)) ◇ z
equation 51701 := x ◇ y = ((z ◇ x) ◇ (y ◇ x)) ◇ w
equation 51702 := x ◇ y = ((z ◇ x) ◇ (y ◇ y)) ◇ x
equation 51703 := x ◇ y = ((z ◇ x) ◇ (y ◇ y)) ◇ y
equation 51704 := x ◇ y = ((z ◇ x) ◇ (y ◇ y)) ◇ z
equation 51705 := x ◇ y = ((z ◇ x) ◇ (y ◇ y)) ◇ w
equation 51706 := x ◇ y = ((z ◇ x) ◇ (y ◇ z)) ◇ x
equation 51707 := x ◇ y = ((z ◇ x) ◇ (y ◇ z)) ◇ y
equation 51708 := x ◇ y = ((z ◇ x) ◇ (y ◇ z)) ◇ z
equation 51709 := x ◇ y = ((z ◇ x) ◇ (y ◇ z)) ◇ w
equation 51710 := x ◇ y = ((z ◇ x) ◇ (y ◇ w)) ◇ x
equation 51711 := x ◇ y = ((z ◇ x) ◇ (y ◇ w)) ◇ y
equation 51712 := x ◇ y = ((z ◇ x) ◇ (y ◇ w)) ◇ z
equation 51713 := x ◇ y = ((z ◇ x) ◇ (y ◇ w)) ◇ w
equation 51714 := x ◇ y = ((z ◇ x) ◇ (y ◇ w)) ◇ u
equation 51715 := x ◇ y = ((z ◇ x) ◇ (z ◇ x)) ◇ x
equation 51716 := x ◇ y = ((z ◇ x) ◇ (z ◇ x)) ◇ y
equation 51717 := x ◇ y = ((z ◇ x) ◇ (z ◇ x)) ◇ z
equation 51718 := x ◇ y = ((z ◇ x) ◇ (z ◇ x)) ◇ w
equation 51719 := x ◇ y = ((z ◇ x) ◇ (z ◇ y)) ◇ x
equation 51720 := x ◇ y = ((z ◇ x) ◇ (z ◇ y)) ◇ y
equation 51721 := x ◇ y = ((z ◇ x) ◇ (z ◇ y)) ◇ z
equation 51722 := x ◇ y = ((z ◇ x) ◇ (z ◇ y)) ◇ w
equation 51723 := x ◇ y = ((z ◇ x) ◇ (z ◇ z)) ◇ x
equation 51724 := x ◇ y = ((z ◇ x) ◇ (z ◇ z)) ◇ y
equation 51725 := x ◇ y = ((z ◇ x) ◇ (z ◇ z)) ◇ z
equation 51726 := x ◇ y = ((z ◇ x) ◇ (z ◇ z)) ◇ w
equation 51727 := x ◇ y = ((z ◇ x) ◇ (z ◇ w)) ◇ x
equation 51728 := x ◇ y = ((z ◇ x) ◇ (z ◇ w)) ◇ y
equation 51729 := x ◇ y = ((z ◇ x) ◇ (z ◇ w)) ◇ z
equation 51730 := x ◇ y = ((z ◇ x) ◇ (z ◇ w)) ◇ w
equation 51731 := x ◇ y = ((z ◇ x) ◇ (z ◇ w)) ◇ u
equation 51732 := x ◇ y = ((z ◇ x) ◇ (w ◇ x)) ◇ x
equation 51733 := x ◇ y = ((z ◇ x) ◇ (w ◇ x)) ◇ y
equation 51734 := x ◇ y = ((z ◇ x) ◇ (w ◇ x)) ◇ z
equation 51735 := x ◇ y = ((z ◇ x) ◇ (w ◇ x)) ◇ w
equation 51736 := x ◇ y = ((z ◇ x) ◇ (w ◇ x)) ◇ u
equation 51737 := x ◇ y = ((z ◇ x) ◇ (w ◇ y)) ◇ x
equation 51738 := x ◇ y = ((z ◇ x) ◇ (w ◇ y)) ◇ y
equation 51739 := x ◇ y = ((z ◇ x) ◇ (w ◇ y)) ◇ z
equation 51740 := x ◇ y = ((z ◇ x) ◇ (w ◇ y)) ◇ w
equation 51741 := x ◇ y = ((z ◇ x) ◇ (w ◇ y)) ◇ u
equation 51742 := x ◇ y = ((z ◇ x) ◇ (w ◇ z)) ◇ x
equation 51743 := x ◇ y = ((z ◇ x) ◇ (w ◇ z)) ◇ y
equation 51744 := x ◇ y = ((z ◇ x) ◇ (w ◇ z)) ◇ z
equation 51745 := x ◇ y = ((z ◇ x) ◇ (w ◇ z)) ◇ w
equation 51746 := x ◇ y = ((z ◇ x) ◇ (w ◇ z)) ◇ u
equation 51747 := x ◇ y = ((z ◇ x) ◇ (w ◇ w)) ◇ x
equation 51748 := x ◇ y = ((z ◇ x) ◇ (w ◇ w)) ◇ y
equation 51749 := x ◇ y = ((z ◇ x) ◇ (w ◇ w)) ◇ z
equation 51750 := x ◇ y = ((z ◇ x) ◇ (w ◇ w)) ◇ w
equation 51751 := x ◇ y = ((z ◇ x) ◇ (w ◇ w)) ◇ u
equation 51752 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ x
equation 51753 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ y
equation 51754 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ z
equation 51755 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ w
equation 51756 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ u
equation 51757 := x ◇ y = ((z ◇ x) ◇ (w ◇ u)) ◇ v
equation 51758 := x ◇ y = ((z ◇ y) ◇ (x ◇ x)) ◇ x
equation 51759 := x ◇ y = ((z ◇ y) ◇ (x ◇ x)) ◇ y
equation 51760 := x ◇ y = ((z ◇ y) ◇ (x ◇ x)) ◇ z
equation 51761 := x ◇ y = ((z ◇ y) ◇ (x ◇ x)) ◇ w
equation 51762 := x ◇ y = ((z ◇ y) ◇ (x ◇ y)) ◇ x
equation 51763 := x ◇ y = ((z ◇ y) ◇ (x ◇ y)) ◇ y
equation 51764 := x ◇ y = ((z ◇ y) ◇ (x ◇ y)) ◇ z
equation 51765 := x ◇ y = ((z ◇ y) ◇ (x ◇ y)) ◇ w
equation 51766 := x ◇ y = ((z ◇ y) ◇ (x ◇ z)) ◇ x
equation 51767 := x ◇ y = ((z ◇ y) ◇ (x ◇ z)) ◇ y
equation 51768 := x ◇ y = ((z ◇ y) ◇ (x ◇ z)) ◇ z
equation 51769 := x ◇ y = ((z ◇ y) ◇ (x ◇ z)) ◇ w
equation 51770 := x ◇ y = ((z ◇ y) ◇ (x ◇ w)) ◇ x
equation 51771 := x ◇ y = ((z ◇ y) ◇ (x ◇ w)) ◇ y
equation 51772 := x ◇ y = ((z ◇ y) ◇ (x ◇ w)) ◇ z
equation 51773 := x ◇ y = ((z ◇ y) ◇ (x ◇ w)) ◇ w
equation 51774 := x ◇ y = ((z ◇ y) ◇ (x ◇ w)) ◇ u
equation 51775 := x ◇ y = ((z ◇ y) ◇ (y ◇ x)) ◇ x
equation 51776 := x ◇ y = ((z ◇ y) ◇ (y ◇ x)) ◇ y
equation 51777 := x ◇ y = ((z ◇ y) ◇ (y ◇ x)) ◇ z
equation 51778 := x ◇ y = ((z ◇ y) ◇ (y ◇ x)) ◇ w
equation 51779 := x ◇ y = ((z ◇ y) ◇ (y ◇ y)) ◇ x
equation 51780 := x ◇ y = ((z ◇ y) ◇ (y ◇ y)) ◇ y
equation 51781 := x ◇ y = ((z ◇ y) ◇ (y ◇ y)) ◇ z
equation 51782 := x ◇ y = ((z ◇ y) ◇ (y ◇ y)) ◇ w
equation 51783 := x ◇ y = ((z ◇ y) ◇ (y ◇ z)) ◇ x
equation 51784 := x ◇ y = ((z ◇ y) ◇ (y ◇ z)) ◇ y
equation 51785 := x ◇ y = ((z ◇ y) ◇ (y ◇ z)) ◇ z
equation 51786 := x ◇ y = ((z ◇ y) ◇ (y ◇ z)) ◇ w
equation 51787 := x ◇ y = ((z ◇ y) ◇ (y ◇ w)) ◇ x
equation 51788 := x ◇ y = ((z ◇ y) ◇ (y ◇ w)) ◇ y
equation 51789 := x ◇ y = ((z ◇ y) ◇ (y ◇ w)) ◇ z
equation 51790 := x ◇ y = ((z ◇ y) ◇ (y ◇ w)) ◇ w
equation 51791 := x ◇ y = ((z ◇ y) ◇ (y ◇ w)) ◇ u
equation 51792 := x ◇ y = ((z ◇ y) ◇ (z ◇ x)) ◇ x
equation 51793 := x ◇ y = ((z ◇ y) ◇ (z ◇ x)) ◇ y
equation 51794 := x ◇ y = ((z ◇ y) ◇ (z ◇ x)) ◇ z
equation 51795 := x ◇ y = ((z ◇ y) ◇ (z ◇ x)) ◇ w
equation 51796 := x ◇ y = ((z ◇ y) ◇ (z ◇ y)) ◇ x
equation 51797 := x ◇ y = ((z ◇ y) ◇ (z ◇ y)) ◇ y
equation 51798 := x ◇ y = ((z ◇ y) ◇ (z ◇ y)) ◇ z
equation 51799 := x ◇ y = ((z ◇ y) ◇ (z ◇ y)) ◇ w
equation 51800 := x ◇ y = ((z ◇ y) ◇ (z ◇ z)) ◇ x
equation 51801 := x ◇ y = ((z ◇ y) ◇ (z ◇ z)) ◇ y
equation 51802 := x ◇ y = ((z ◇ y) ◇ (z ◇ z)) ◇ z
equation 51803 := x ◇ y = ((z ◇ y) ◇ (z ◇ z)) ◇ w
equation 51804 := x ◇ y = ((z ◇ y) ◇ (z ◇ w)) ◇ x
equation 51805 := x ◇ y = ((z ◇ y) ◇ (z ◇ w)) ◇ y
equation 51806 := x ◇ y = ((z ◇ y) ◇ (z ◇ w)) ◇ z
equation 51807 := x ◇ y = ((z ◇ y) ◇ (z ◇ w)) ◇ w
equation 51808 := x ◇ y = ((z ◇ y) ◇ (z ◇ w)) ◇ u
equation 51809 := x ◇ y = ((z ◇ y) ◇ (w ◇ x)) ◇ x
equation 51810 := x ◇ y = ((z ◇ y) ◇ (w ◇ x)) ◇ y
equation 51811 := x ◇ y = ((z ◇ y) ◇ (w ◇ x)) ◇ z
equation 51812 := x ◇ y = ((z ◇ y) ◇ (w ◇ x)) ◇ w
equation 51813 := x ◇ y = ((z ◇ y) ◇ (w ◇ x)) ◇ u
equation 51814 := x ◇ y = ((z ◇ y) ◇ (w ◇ y)) ◇ x
equation 51815 := x ◇ y = ((z ◇ y) ◇ (w ◇ y)) ◇ y
equation 51816 := x ◇ y = ((z ◇ y) ◇ (w ◇ y)) ◇ z
equation 51817 := x ◇ y = ((z ◇ y) ◇ (w ◇ y)) ◇ w
equation 51818 := x ◇ y = ((z ◇ y) ◇ (w ◇ y)) ◇ u
equation 51819 := x ◇ y = ((z ◇ y) ◇ (w ◇ z)) ◇ x
equation 51820 := x ◇ y = ((z ◇ y) ◇ (w ◇ z)) ◇ y
equation 51821 := x ◇ y = ((z ◇ y) ◇ (w ◇ z)) ◇ z
equation 51822 := x ◇ y = ((z ◇ y) ◇ (w ◇ z)) ◇ w
equation 51823 := x ◇ y = ((z ◇ y) ◇ (w ◇ z)) ◇ u
equation 51824 := x ◇ y = ((z ◇ y) ◇ (w ◇ w)) ◇ x
equation 51825 := x ◇ y = ((z ◇ y) ◇ (w ◇ w)) ◇ y
equation 51826 := x ◇ y = ((z ◇ y) ◇ (w ◇ w)) ◇ z
equation 51827 := x ◇ y = ((z ◇ y) ◇ (w ◇ w)) ◇ w
equation 51828 := x ◇ y = ((z ◇ y) ◇ (w ◇ w)) ◇ u
equation 51829 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ x
equation 51830 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ y
equation 51831 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ z
equation 51832 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ w
equation 51833 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ u
equation 51834 := x ◇ y = ((z ◇ y) ◇ (w ◇ u)) ◇ v
equation 51835 := x ◇ y = ((z ◇ z) ◇ (x ◇ x)) ◇ x
equation 51836 := x ◇ y = ((z ◇ z) ◇ (x ◇ x)) ◇ y
equation 51837 := x ◇ y = ((z ◇ z) ◇ (x ◇ x)) ◇ z
equation 51838 := x ◇ y = ((z ◇ z) ◇ (x ◇ x)) ◇ w
equation 51839 := x ◇ y = ((z ◇ z) ◇ (x ◇ y)) ◇ x
equation 51840 := x ◇ y = ((z ◇ z) ◇ (x ◇ y)) ◇ y
equation 51841 := x ◇ y = ((z ◇ z) ◇ (x ◇ y)) ◇ z
equation 51842 := x ◇ y = ((z ◇ z) ◇ (x ◇ y)) ◇ w
equation 51843 := x ◇ y = ((z ◇ z) ◇ (x ◇ z)) ◇ x
equation 51844 := x ◇ y = ((z ◇ z) ◇ (x ◇ z)) ◇ y
equation 51845 := x ◇ y = ((z ◇ z) ◇ (x ◇ z)) ◇ z
equation 51846 := x ◇ y = ((z ◇ z) ◇ (x ◇ z)) ◇ w
equation 51847 := x ◇ y = ((z ◇ z) ◇ (x ◇ w)) ◇ x
equation 51848 := x ◇ y = ((z ◇ z) ◇ (x ◇ w)) ◇ y
equation 51849 := x ◇ y = ((z ◇ z) ◇ (x ◇ w)) ◇ z
equation 51850 := x ◇ y = ((z ◇ z) ◇ (x ◇ w)) ◇ w
equation 51851 := x ◇ y = ((z ◇ z) ◇ (x ◇ w)) ◇ u
equation 51852 := x ◇ y = ((z ◇ z) ◇ (y ◇ x)) ◇ x
equation 51853 := x ◇ y = ((z ◇ z) ◇ (y ◇ x)) ◇ y
equation 51854 := x ◇ y = ((z ◇ z) ◇ (y ◇ x)) ◇ z
equation 51855 := x ◇ y = ((z ◇ z) ◇ (y ◇ x)) ◇ w
equation 51856 := x ◇ y = ((z ◇ z) ◇ (y ◇ y)) ◇ x
equation 51857 := x ◇ y = ((z ◇ z) ◇ (y ◇ y)) ◇ y
equation 51858 := x ◇ y = ((z ◇ z) ◇ (y ◇ y)) ◇ z
equation 51859 := x ◇ y = ((z ◇ z) ◇ (y ◇ y)) ◇ w
equation 51860 := x ◇ y = ((z ◇ z) ◇ (y ◇ z)) ◇ x
equation 51861 := x ◇ y = ((z ◇ z) ◇ (y ◇ z)) ◇ y
equation 51862 := x ◇ y = ((z ◇ z) ◇ (y ◇ z)) ◇ z
equation 51863 := x ◇ y = ((z ◇ z) ◇ (y ◇ z)) ◇ w
equation 51864 := x ◇ y = ((z ◇ z) ◇ (y ◇ w)) ◇ x
equation 51865 := x ◇ y = ((z ◇ z) ◇ (y ◇ w)) ◇ y
equation 51866 := x ◇ y = ((z ◇ z) ◇ (y ◇ w)) ◇ z
equation 51867 := x ◇ y = ((z ◇ z) ◇ (y ◇ w)) ◇ w
equation 51868 := x ◇ y = ((z ◇ z) ◇ (y ◇ w)) ◇ u
equation 51869 := x ◇ y = ((z ◇ z) ◇ (z ◇ x)) ◇ x
equation 51870 := x ◇ y = ((z ◇ z) ◇ (z ◇ x)) ◇ y
equation 51871 := x ◇ y = ((z ◇ z) ◇ (z ◇ x)) ◇ z
equation 51872 := x ◇ y = ((z ◇ z) ◇ (z ◇ x)) ◇ w
equation 51873 := x ◇ y = ((z ◇ z) ◇ (z ◇ y)) ◇ x
equation 51874 := x ◇ y = ((z ◇ z) ◇ (z ◇ y)) ◇ y
equation 51875 := x ◇ y = ((z ◇ z) ◇ (z ◇ y)) ◇ z
equation 51876 := x ◇ y = ((z ◇ z) ◇ (z ◇ y)) ◇ w
equation 51877 := x ◇ y = ((z ◇ z) ◇ (z ◇ z)) ◇ x
equation 51878 := x ◇ y = ((z ◇ z) ◇ (z ◇ z)) ◇ y
equation 51879 := x ◇ y = ((z ◇ z) ◇ (z ◇ z)) ◇ z
equation 51880 := x ◇ y = ((z ◇ z) ◇ (z ◇ z)) ◇ w
equation 51881 := x ◇ y = ((z ◇ z) ◇ (z ◇ w)) ◇ x
equation 51882 := x ◇ y = ((z ◇ z) ◇ (z ◇ w)) ◇ y
equation 51883 := x ◇ y = ((z ◇ z) ◇ (z ◇ w)) ◇ z
equation 51884 := x ◇ y = ((z ◇ z) ◇ (z ◇ w)) ◇ w
equation 51885 := x ◇ y = ((z ◇ z) ◇ (z ◇ w)) ◇ u
equation 51886 := x ◇ y = ((z ◇ z) ◇ (w ◇ x)) ◇ x
equation 51887 := x ◇ y = ((z ◇ z) ◇ (w ◇ x)) ◇ y
equation 51888 := x ◇ y = ((z ◇ z) ◇ (w ◇ x)) ◇ z
equation 51889 := x ◇ y = ((z ◇ z) ◇ (w ◇ x)) ◇ w
equation 51890 := x ◇ y = ((z ◇ z) ◇ (w ◇ x)) ◇ u
equation 51891 := x ◇ y = ((z ◇ z) ◇ (w ◇ y)) ◇ x
equation 51892 := x ◇ y = ((z ◇ z) ◇ (w ◇ y)) ◇ y
equation 51893 := x ◇ y = ((z ◇ z) ◇ (w ◇ y)) ◇ z
equation 51894 := x ◇ y = ((z ◇ z) ◇ (w ◇ y)) ◇ w
equation 51895 := x ◇ y = ((z ◇ z) ◇ (w ◇ y)) ◇ u
equation 51896 := x ◇ y = ((z ◇ z) ◇ (w ◇ z)) ◇ x
equation 51897 := x ◇ y = ((z ◇ z) ◇ (w ◇ z)) ◇ y
equation 51898 := x ◇ y = ((z ◇ z) ◇ (w ◇ z)) ◇ z
equation 51899 := x ◇ y = ((z ◇ z) ◇ (w ◇ z)) ◇ w
equation 51900 := x ◇ y = ((z ◇ z) ◇ (w ◇ z)) ◇ u
equation 51901 := x ◇ y = ((z ◇ z) ◇ (w ◇ w)) ◇ x
equation 51902 := x ◇ y = ((z ◇ z) ◇ (w ◇ w)) ◇ y
equation 51903 := x ◇ y = ((z ◇ z) ◇ (w ◇ w)) ◇ z
equation 51904 := x ◇ y = ((z ◇ z) ◇ (w ◇ w)) ◇ w
equation 51905 := x ◇ y = ((z ◇ z) ◇ (w ◇ w)) ◇ u
equation 51906 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ x
equation 51907 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ y
equation 51908 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ z
equation 51909 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ w
equation 51910 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ u
equation 51911 := x ◇ y = ((z ◇ z) ◇ (w ◇ u)) ◇ v
equation 51912 := x ◇ y = ((z ◇ w) ◇ (x ◇ x)) ◇ x
equation 51913 := x ◇ y = ((z ◇ w) ◇ (x ◇ x)) ◇ y
equation 51914 := x ◇ y = ((z ◇ w) ◇ (x ◇ x)) ◇ z
equation 51915 := x ◇ y = ((z ◇ w) ◇ (x ◇ x)) ◇ w
equation 51916 := x ◇ y = ((z ◇ w) ◇ (x ◇ x)) ◇ u
equation 51917 := x ◇ y = ((z ◇ w) ◇ (x ◇ y)) ◇ x
equation 51918 := x ◇ y = ((z ◇ w) ◇ (x ◇ y)) ◇ y
equation 51919 := x ◇ y = ((z ◇ w) ◇ (x ◇ y)) ◇ z
equation 51920 := x ◇ y = ((z ◇ w) ◇ (x ◇ y)) ◇ w
equation 51921 := x ◇ y = ((z ◇ w) ◇ (x ◇ y)) ◇ u
equation 51922 := x ◇ y = ((z ◇ w) ◇ (x ◇ z)) ◇ x
equation 51923 := x ◇ y = ((z ◇ w) ◇ (x ◇ z)) ◇ y
equation 51924 := x ◇ y = ((z ◇ w) ◇ (x ◇ z)) ◇ z
equation 51925 := x ◇ y = ((z ◇ w) ◇ (x ◇ z)) ◇ w
equation 51926 := x ◇ y = ((z ◇ w) ◇ (x ◇ z)) ◇ u
equation 51927 := x ◇ y = ((z ◇ w) ◇ (x ◇ w)) ◇ x
equation 51928 := x ◇ y = ((z ◇ w) ◇ (x ◇ w)) ◇ y
equation 51929 := x ◇ y = ((z ◇ w) ◇ (x ◇ w)) ◇ z
equation 51930 := x ◇ y = ((z ◇ w) ◇ (x ◇ w)) ◇ w
equation 51931 := x ◇ y = ((z ◇ w) ◇ (x ◇ w)) ◇ u
equation 51932 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ x
equation 51933 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ y
equation 51934 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ z
equation 51935 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ w
equation 51936 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ u
equation 51937 := x ◇ y = ((z ◇ w) ◇ (x ◇ u)) ◇ v
equation 51938 := x ◇ y = ((z ◇ w) ◇ (y ◇ x)) ◇ x
equation 51939 := x ◇ y = ((z ◇ w) ◇ (y ◇ x)) ◇ y
equation 51940 := x ◇ y = ((z ◇ w) ◇ (y ◇ x)) ◇ z
equation 51941 := x ◇ y = ((z ◇ w) ◇ (y ◇ x)) ◇ w
equation 51942 := x ◇ y = ((z ◇ w) ◇ (y ◇ x)) ◇ u
equation 51943 := x ◇ y = ((z ◇ w) ◇ (y ◇ y)) ◇ x
equation 51944 := x ◇ y = ((z ◇ w) ◇ (y ◇ y)) ◇ y
equation 51945 := x ◇ y = ((z ◇ w) ◇ (y ◇ y)) ◇ z
equation 51946 := x ◇ y = ((z ◇ w) ◇ (y ◇ y)) ◇ w
equation 51947 := x ◇ y = ((z ◇ w) ◇ (y ◇ y)) ◇ u
equation 51948 := x ◇ y = ((z ◇ w) ◇ (y ◇ z)) ◇ x
equation 51949 := x ◇ y = ((z ◇ w) ◇ (y ◇ z)) ◇ y
equation 51950 := x ◇ y = ((z ◇ w) ◇ (y ◇ z)) ◇ z
equation 51951 := x ◇ y = ((z ◇ w) ◇ (y ◇ z)) ◇ w
equation 51952 := x ◇ y = ((z ◇ w) ◇ (y ◇ z)) ◇ u
equation 51953 := x ◇ y = ((z ◇ w) ◇ (y ◇ w)) ◇ x
equation 51954 := x ◇ y = ((z ◇ w) ◇ (y ◇ w)) ◇ y
equation 51955 := x ◇ y = ((z ◇ w) ◇ (y ◇ w)) ◇ z
equation 51956 := x ◇ y = ((z ◇ w) ◇ (y ◇ w)) ◇ w
equation 51957 := x ◇ y = ((z ◇ w) ◇ (y ◇ w)) ◇ u
equation 51958 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ x
equation 51959 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ y
equation 51960 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ z
equation 51961 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ w
equation 51962 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ u
equation 51963 := x ◇ y = ((z ◇ w) ◇ (y ◇ u)) ◇ v
equation 51964 := x ◇ y = ((z ◇ w) ◇ (z ◇ x)) ◇ x
equation 51965 := x ◇ y = ((z ◇ w) ◇ (z ◇ x)) ◇ y
equation 51966 := x ◇ y = ((z ◇ w) ◇ (z ◇ x)) ◇ z
equation 51967 := x ◇ y = ((z ◇ w) ◇ (z ◇ x)) ◇ w
equation 51968 := x ◇ y = ((z ◇ w) ◇ (z ◇ x)) ◇ u
equation 51969 := x ◇ y = ((z ◇ w) ◇ (z ◇ y)) ◇ x
equation 51970 := x ◇ y = ((z ◇ w) ◇ (z ◇ y)) ◇ y
equation 51971 := x ◇ y = ((z ◇ w) ◇ (z ◇ y)) ◇ z
equation 51972 := x ◇ y = ((z ◇ w) ◇ (z ◇ y)) ◇ w
equation 51973 := x ◇ y = ((z ◇ w) ◇ (z ◇ y)) ◇ u
equation 51974 := x ◇ y = ((z ◇ w) ◇ (z ◇ z)) ◇ x
equation 51975 := x ◇ y = ((z ◇ w) ◇ (z ◇ z)) ◇ y
equation 51976 := x ◇ y = ((z ◇ w) ◇ (z ◇ z)) ◇ z
equation 51977 := x ◇ y = ((z ◇ w) ◇ (z ◇ z)) ◇ w
equation 51978 := x ◇ y = ((z ◇ w) ◇ (z ◇ z)) ◇ u
equation 51979 := x ◇ y = ((z ◇ w) ◇ (z ◇ w)) ◇ x
equation 51980 := x ◇ y = ((z ◇ w) ◇ (z ◇ w)) ◇ y
equation 51981 := x ◇ y = ((z ◇ w) ◇ (z ◇ w)) ◇ z
equation 51982 := x ◇ y = ((z ◇ w) ◇ (z ◇ w)) ◇ w
equation 51983 := x ◇ y = ((z ◇ w) ◇ (z ◇ w)) ◇ u
equation 51984 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ x
equation 51985 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ y
equation 51986 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ z
equation 51987 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ w
equation 51988 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ u
equation 51989 := x ◇ y = ((z ◇ w) ◇ (z ◇ u)) ◇ v
equation 51990 := x ◇ y = ((z ◇ w) ◇ (w ◇ x)) ◇ x
equation 51991 := x ◇ y = ((z ◇ w) ◇ (w ◇ x)) ◇ y
equation 51992 := x ◇ y = ((z ◇ w) ◇ (w ◇ x)) ◇ z
equation 51993 := x ◇ y = ((z ◇ w) ◇ (w ◇ x)) ◇ w
equation 51994 := x ◇ y = ((z ◇ w) ◇ (w ◇ x)) ◇ u
equation 51995 := x ◇ y = ((z ◇ w) ◇ (w ◇ y)) ◇ x
equation 51996 := x ◇ y = ((z ◇ w) ◇ (w ◇ y)) ◇ y
equation 51997 := x ◇ y = ((z ◇ w) ◇ (w ◇ y)) ◇ z
equation 51998 := x ◇ y = ((z ◇ w) ◇ (w ◇ y)) ◇ w
equation 51999 := x ◇ y = ((z ◇ w) ◇ (w ◇ y)) ◇ u
