import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 53000-53999 -/

equation 53000 := x ◇ x = (((y ◇ x) ◇ y) ◇ z) ◇ z
equation 53001 := x ◇ x = (((y ◇ x) ◇ y) ◇ z) ◇ w
equation 53002 := x ◇ x = (((y ◇ x) ◇ z) ◇ x) ◇ x
equation 53003 := x ◇ x = (((y ◇ x) ◇ z) ◇ x) ◇ y
equation 53004 := x ◇ x = (((y ◇ x) ◇ z) ◇ x) ◇ z
equation 53005 := x ◇ x = (((y ◇ x) ◇ z) ◇ x) ◇ w
equation 53006 := x ◇ x = (((y ◇ x) ◇ z) ◇ y) ◇ x
equation 53007 := x ◇ x = (((y ◇ x) ◇ z) ◇ y) ◇ y
equation 53008 := x ◇ x = (((y ◇ x) ◇ z) ◇ y) ◇ z
equation 53009 := x ◇ x = (((y ◇ x) ◇ z) ◇ y) ◇ w
equation 53010 := x ◇ x = (((y ◇ x) ◇ z) ◇ z) ◇ x
equation 53011 := x ◇ x = (((y ◇ x) ◇ z) ◇ z) ◇ y
equation 53012 := x ◇ x = (((y ◇ x) ◇ z) ◇ z) ◇ z
equation 53013 := x ◇ x = (((y ◇ x) ◇ z) ◇ z) ◇ w
equation 53014 := x ◇ x = (((y ◇ x) ◇ z) ◇ w) ◇ x
equation 53015 := x ◇ x = (((y ◇ x) ◇ z) ◇ w) ◇ y
equation 53016 := x ◇ x = (((y ◇ x) ◇ z) ◇ w) ◇ z
equation 53017 := x ◇ x = (((y ◇ x) ◇ z) ◇ w) ◇ w
equation 53018 := x ◇ x = (((y ◇ x) ◇ z) ◇ w) ◇ u
equation 53019 := x ◇ x = (((y ◇ y) ◇ x) ◇ x) ◇ x
equation 53020 := x ◇ x = (((y ◇ y) ◇ x) ◇ x) ◇ y
equation 53021 := x ◇ x = (((y ◇ y) ◇ x) ◇ x) ◇ z
equation 53022 := x ◇ x = (((y ◇ y) ◇ x) ◇ y) ◇ x
equation 53023 := x ◇ x = (((y ◇ y) ◇ x) ◇ y) ◇ y
equation 53024 := x ◇ x = (((y ◇ y) ◇ x) ◇ y) ◇ z
equation 53025 := x ◇ x = (((y ◇ y) ◇ x) ◇ z) ◇ x
equation 53026 := x ◇ x = (((y ◇ y) ◇ x) ◇ z) ◇ y
equation 53027 := x ◇ x = (((y ◇ y) ◇ x) ◇ z) ◇ z
equation 53028 := x ◇ x = (((y ◇ y) ◇ x) ◇ z) ◇ w
equation 53029 := x ◇ x = (((y ◇ y) ◇ y) ◇ x) ◇ x
equation 53030 := x ◇ x = (((y ◇ y) ◇ y) ◇ x) ◇ y
equation 53031 := x ◇ x = (((y ◇ y) ◇ y) ◇ x) ◇ z
equation 53032 := x ◇ x = (((y ◇ y) ◇ y) ◇ y) ◇ x
equation 53033 := x ◇ x = (((y ◇ y) ◇ y) ◇ y) ◇ y
equation 53034 := x ◇ x = (((y ◇ y) ◇ y) ◇ y) ◇ z
equation 53035 := x ◇ x = (((y ◇ y) ◇ y) ◇ z) ◇ x
equation 53036 := x ◇ x = (((y ◇ y) ◇ y) ◇ z) ◇ y
equation 53037 := x ◇ x = (((y ◇ y) ◇ y) ◇ z) ◇ z
equation 53038 := x ◇ x = (((y ◇ y) ◇ y) ◇ z) ◇ w
equation 53039 := x ◇ x = (((y ◇ y) ◇ z) ◇ x) ◇ x
equation 53040 := x ◇ x = (((y ◇ y) ◇ z) ◇ x) ◇ y
equation 53041 := x ◇ x = (((y ◇ y) ◇ z) ◇ x) ◇ z
equation 53042 := x ◇ x = (((y ◇ y) ◇ z) ◇ x) ◇ w
equation 53043 := x ◇ x = (((y ◇ y) ◇ z) ◇ y) ◇ x
equation 53044 := x ◇ x = (((y ◇ y) ◇ z) ◇ y) ◇ y
equation 53045 := x ◇ x = (((y ◇ y) ◇ z) ◇ y) ◇ z
equation 53046 := x ◇ x = (((y ◇ y) ◇ z) ◇ y) ◇ w
equation 53047 := x ◇ x = (((y ◇ y) ◇ z) ◇ z) ◇ x
equation 53048 := x ◇ x = (((y ◇ y) ◇ z) ◇ z) ◇ y
equation 53049 := x ◇ x = (((y ◇ y) ◇ z) ◇ z) ◇ z
equation 53050 := x ◇ x = (((y ◇ y) ◇ z) ◇ z) ◇ w
equation 53051 := x ◇ x = (((y ◇ y) ◇ z) ◇ w) ◇ x
equation 53052 := x ◇ x = (((y ◇ y) ◇ z) ◇ w) ◇ y
equation 53053 := x ◇ x = (((y ◇ y) ◇ z) ◇ w) ◇ z
equation 53054 := x ◇ x = (((y ◇ y) ◇ z) ◇ w) ◇ w
equation 53055 := x ◇ x = (((y ◇ y) ◇ z) ◇ w) ◇ u
equation 53056 := x ◇ x = (((y ◇ z) ◇ x) ◇ x) ◇ x
equation 53057 := x ◇ x = (((y ◇ z) ◇ x) ◇ x) ◇ y
equation 53058 := x ◇ x = (((y ◇ z) ◇ x) ◇ x) ◇ z
equation 53059 := x ◇ x = (((y ◇ z) ◇ x) ◇ x) ◇ w
equation 53060 := x ◇ x = (((y ◇ z) ◇ x) ◇ y) ◇ x
equation 53061 := x ◇ x = (((y ◇ z) ◇ x) ◇ y) ◇ y
equation 53062 := x ◇ x = (((y ◇ z) ◇ x) ◇ y) ◇ z
equation 53063 := x ◇ x = (((y ◇ z) ◇ x) ◇ y) ◇ w
equation 53064 := x ◇ x = (((y ◇ z) ◇ x) ◇ z) ◇ x
equation 53065 := x ◇ x = (((y ◇ z) ◇ x) ◇ z) ◇ y
equation 53066 := x ◇ x = (((y ◇ z) ◇ x) ◇ z) ◇ z
equation 53067 := x ◇ x = (((y ◇ z) ◇ x) ◇ z) ◇ w
equation 53068 := x ◇ x = (((y ◇ z) ◇ x) ◇ w) ◇ x
equation 53069 := x ◇ x = (((y ◇ z) ◇ x) ◇ w) ◇ y
equation 53070 := x ◇ x = (((y ◇ z) ◇ x) ◇ w) ◇ z
equation 53071 := x ◇ x = (((y ◇ z) ◇ x) ◇ w) ◇ w
equation 53072 := x ◇ x = (((y ◇ z) ◇ x) ◇ w) ◇ u
equation 53073 := x ◇ x = (((y ◇ z) ◇ y) ◇ x) ◇ x
equation 53074 := x ◇ x = (((y ◇ z) ◇ y) ◇ x) ◇ y
equation 53075 := x ◇ x = (((y ◇ z) ◇ y) ◇ x) ◇ z
equation 53076 := x ◇ x = (((y ◇ z) ◇ y) ◇ x) ◇ w
equation 53077 := x ◇ x = (((y ◇ z) ◇ y) ◇ y) ◇ x
equation 53078 := x ◇ x = (((y ◇ z) ◇ y) ◇ y) ◇ y
equation 53079 := x ◇ x = (((y ◇ z) ◇ y) ◇ y) ◇ z
equation 53080 := x ◇ x = (((y ◇ z) ◇ y) ◇ y) ◇ w
equation 53081 := x ◇ x = (((y ◇ z) ◇ y) ◇ z) ◇ x
equation 53082 := x ◇ x = (((y ◇ z) ◇ y) ◇ z) ◇ y
equation 53083 := x ◇ x = (((y ◇ z) ◇ y) ◇ z) ◇ z
equation 53084 := x ◇ x = (((y ◇ z) ◇ y) ◇ z) ◇ w
equation 53085 := x ◇ x = (((y ◇ z) ◇ y) ◇ w) ◇ x
equation 53086 := x ◇ x = (((y ◇ z) ◇ y) ◇ w) ◇ y
equation 53087 := x ◇ x = (((y ◇ z) ◇ y) ◇ w) ◇ z
equation 53088 := x ◇ x = (((y ◇ z) ◇ y) ◇ w) ◇ w
equation 53089 := x ◇ x = (((y ◇ z) ◇ y) ◇ w) ◇ u
equation 53090 := x ◇ x = (((y ◇ z) ◇ z) ◇ x) ◇ x
equation 53091 := x ◇ x = (((y ◇ z) ◇ z) ◇ x) ◇ y
equation 53092 := x ◇ x = (((y ◇ z) ◇ z) ◇ x) ◇ z
equation 53093 := x ◇ x = (((y ◇ z) ◇ z) ◇ x) ◇ w
equation 53094 := x ◇ x = (((y ◇ z) ◇ z) ◇ y) ◇ x
equation 53095 := x ◇ x = (((y ◇ z) ◇ z) ◇ y) ◇ y
equation 53096 := x ◇ x = (((y ◇ z) ◇ z) ◇ y) ◇ z
equation 53097 := x ◇ x = (((y ◇ z) ◇ z) ◇ y) ◇ w
equation 53098 := x ◇ x = (((y ◇ z) ◇ z) ◇ z) ◇ x
equation 53099 := x ◇ x = (((y ◇ z) ◇ z) ◇ z) ◇ y
equation 53100 := x ◇ x = (((y ◇ z) ◇ z) ◇ z) ◇ z
equation 53101 := x ◇ x = (((y ◇ z) ◇ z) ◇ z) ◇ w
equation 53102 := x ◇ x = (((y ◇ z) ◇ z) ◇ w) ◇ x
equation 53103 := x ◇ x = (((y ◇ z) ◇ z) ◇ w) ◇ y
equation 53104 := x ◇ x = (((y ◇ z) ◇ z) ◇ w) ◇ z
equation 53105 := x ◇ x = (((y ◇ z) ◇ z) ◇ w) ◇ w
equation 53106 := x ◇ x = (((y ◇ z) ◇ z) ◇ w) ◇ u
equation 53107 := x ◇ x = (((y ◇ z) ◇ w) ◇ x) ◇ x
equation 53108 := x ◇ x = (((y ◇ z) ◇ w) ◇ x) ◇ y
equation 53109 := x ◇ x = (((y ◇ z) ◇ w) ◇ x) ◇ z
equation 53110 := x ◇ x = (((y ◇ z) ◇ w) ◇ x) ◇ w
equation 53111 := x ◇ x = (((y ◇ z) ◇ w) ◇ x) ◇ u
equation 53112 := x ◇ x = (((y ◇ z) ◇ w) ◇ y) ◇ x
equation 53113 := x ◇ x = (((y ◇ z) ◇ w) ◇ y) ◇ y
equation 53114 := x ◇ x = (((y ◇ z) ◇ w) ◇ y) ◇ z
equation 53115 := x ◇ x = (((y ◇ z) ◇ w) ◇ y) ◇ w
equation 53116 := x ◇ x = (((y ◇ z) ◇ w) ◇ y) ◇ u
equation 53117 := x ◇ x = (((y ◇ z) ◇ w) ◇ z) ◇ x
equation 53118 := x ◇ x = (((y ◇ z) ◇ w) ◇ z) ◇ y
equation 53119 := x ◇ x = (((y ◇ z) ◇ w) ◇ z) ◇ z
equation 53120 := x ◇ x = (((y ◇ z) ◇ w) ◇ z) ◇ w
equation 53121 := x ◇ x = (((y ◇ z) ◇ w) ◇ z) ◇ u
equation 53122 := x ◇ x = (((y ◇ z) ◇ w) ◇ w) ◇ x
equation 53123 := x ◇ x = (((y ◇ z) ◇ w) ◇ w) ◇ y
equation 53124 := x ◇ x = (((y ◇ z) ◇ w) ◇ w) ◇ z
equation 53125 := x ◇ x = (((y ◇ z) ◇ w) ◇ w) ◇ w
equation 53126 := x ◇ x = (((y ◇ z) ◇ w) ◇ w) ◇ u
equation 53127 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ x
equation 53128 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ y
equation 53129 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ z
equation 53130 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ w
equation 53131 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ u
equation 53132 := x ◇ x = (((y ◇ z) ◇ w) ◇ u) ◇ v
equation 53133 := x ◇ y = (((x ◇ x) ◇ x) ◇ x) ◇ x
equation 53134 := x ◇ y = (((x ◇ x) ◇ x) ◇ x) ◇ y
equation 53135 := x ◇ y = (((x ◇ x) ◇ x) ◇ x) ◇ z
equation 53136 := x ◇ y = (((x ◇ x) ◇ x) ◇ y) ◇ x
equation 53137 := x ◇ y = (((x ◇ x) ◇ x) ◇ y) ◇ y
equation 53138 := x ◇ y = (((x ◇ x) ◇ x) ◇ y) ◇ z
equation 53139 := x ◇ y = (((x ◇ x) ◇ x) ◇ z) ◇ x
equation 53140 := x ◇ y = (((x ◇ x) ◇ x) ◇ z) ◇ y
equation 53141 := x ◇ y = (((x ◇ x) ◇ x) ◇ z) ◇ z
equation 53142 := x ◇ y = (((x ◇ x) ◇ x) ◇ z) ◇ w
equation 53143 := x ◇ y = (((x ◇ x) ◇ y) ◇ x) ◇ x
equation 53144 := x ◇ y = (((x ◇ x) ◇ y) ◇ x) ◇ y
equation 53145 := x ◇ y = (((x ◇ x) ◇ y) ◇ x) ◇ z
equation 53146 := x ◇ y = (((x ◇ x) ◇ y) ◇ y) ◇ x
equation 53147 := x ◇ y = (((x ◇ x) ◇ y) ◇ y) ◇ y
equation 53148 := x ◇ y = (((x ◇ x) ◇ y) ◇ y) ◇ z
equation 53149 := x ◇ y = (((x ◇ x) ◇ y) ◇ z) ◇ x
equation 53150 := x ◇ y = (((x ◇ x) ◇ y) ◇ z) ◇ y
equation 53151 := x ◇ y = (((x ◇ x) ◇ y) ◇ z) ◇ z
equation 53152 := x ◇ y = (((x ◇ x) ◇ y) ◇ z) ◇ w
equation 53153 := x ◇ y = (((x ◇ x) ◇ z) ◇ x) ◇ x
equation 53154 := x ◇ y = (((x ◇ x) ◇ z) ◇ x) ◇ y
equation 53155 := x ◇ y = (((x ◇ x) ◇ z) ◇ x) ◇ z
equation 53156 := x ◇ y = (((x ◇ x) ◇ z) ◇ x) ◇ w
equation 53157 := x ◇ y = (((x ◇ x) ◇ z) ◇ y) ◇ x
equation 53158 := x ◇ y = (((x ◇ x) ◇ z) ◇ y) ◇ y
equation 53159 := x ◇ y = (((x ◇ x) ◇ z) ◇ y) ◇ z
equation 53160 := x ◇ y = (((x ◇ x) ◇ z) ◇ y) ◇ w
equation 53161 := x ◇ y = (((x ◇ x) ◇ z) ◇ z) ◇ x
equation 53162 := x ◇ y = (((x ◇ x) ◇ z) ◇ z) ◇ y
equation 53163 := x ◇ y = (((x ◇ x) ◇ z) ◇ z) ◇ z
equation 53164 := x ◇ y = (((x ◇ x) ◇ z) ◇ z) ◇ w
equation 53165 := x ◇ y = (((x ◇ x) ◇ z) ◇ w) ◇ x
equation 53166 := x ◇ y = (((x ◇ x) ◇ z) ◇ w) ◇ y
equation 53167 := x ◇ y = (((x ◇ x) ◇ z) ◇ w) ◇ z
equation 53168 := x ◇ y = (((x ◇ x) ◇ z) ◇ w) ◇ w
equation 53169 := x ◇ y = (((x ◇ x) ◇ z) ◇ w) ◇ u
equation 53170 := x ◇ y = (((x ◇ y) ◇ x) ◇ x) ◇ x
equation 53171 := x ◇ y = (((x ◇ y) ◇ x) ◇ x) ◇ y
equation 53172 := x ◇ y = (((x ◇ y) ◇ x) ◇ x) ◇ z
equation 53173 := x ◇ y = (((x ◇ y) ◇ x) ◇ y) ◇ x
equation 53174 := x ◇ y = (((x ◇ y) ◇ x) ◇ y) ◇ y
equation 53175 := x ◇ y = (((x ◇ y) ◇ x) ◇ y) ◇ z
equation 53176 := x ◇ y = (((x ◇ y) ◇ x) ◇ z) ◇ x
equation 53177 := x ◇ y = (((x ◇ y) ◇ x) ◇ z) ◇ y
equation 53178 := x ◇ y = (((x ◇ y) ◇ x) ◇ z) ◇ z
equation 53179 := x ◇ y = (((x ◇ y) ◇ x) ◇ z) ◇ w
equation 53180 := x ◇ y = (((x ◇ y) ◇ y) ◇ x) ◇ x
equation 53181 := x ◇ y = (((x ◇ y) ◇ y) ◇ x) ◇ y
equation 53182 := x ◇ y = (((x ◇ y) ◇ y) ◇ x) ◇ z
equation 53183 := x ◇ y = (((x ◇ y) ◇ y) ◇ y) ◇ x
equation 53184 := x ◇ y = (((x ◇ y) ◇ y) ◇ y) ◇ y
equation 53185 := x ◇ y = (((x ◇ y) ◇ y) ◇ y) ◇ z
equation 53186 := x ◇ y = (((x ◇ y) ◇ y) ◇ z) ◇ x
equation 53187 := x ◇ y = (((x ◇ y) ◇ y) ◇ z) ◇ y
equation 53188 := x ◇ y = (((x ◇ y) ◇ y) ◇ z) ◇ z
equation 53189 := x ◇ y = (((x ◇ y) ◇ y) ◇ z) ◇ w
equation 53190 := x ◇ y = (((x ◇ y) ◇ z) ◇ x) ◇ x
equation 53191 := x ◇ y = (((x ◇ y) ◇ z) ◇ x) ◇ y
equation 53192 := x ◇ y = (((x ◇ y) ◇ z) ◇ x) ◇ z
equation 53193 := x ◇ y = (((x ◇ y) ◇ z) ◇ x) ◇ w
equation 53194 := x ◇ y = (((x ◇ y) ◇ z) ◇ y) ◇ x
equation 53195 := x ◇ y = (((x ◇ y) ◇ z) ◇ y) ◇ y
equation 53196 := x ◇ y = (((x ◇ y) ◇ z) ◇ y) ◇ z
equation 53197 := x ◇ y = (((x ◇ y) ◇ z) ◇ y) ◇ w
equation 53198 := x ◇ y = (((x ◇ y) ◇ z) ◇ z) ◇ x
equation 53199 := x ◇ y = (((x ◇ y) ◇ z) ◇ z) ◇ y
equation 53200 := x ◇ y = (((x ◇ y) ◇ z) ◇ z) ◇ z
equation 53201 := x ◇ y = (((x ◇ y) ◇ z) ◇ z) ◇ w
equation 53202 := x ◇ y = (((x ◇ y) ◇ z) ◇ w) ◇ x
equation 53203 := x ◇ y = (((x ◇ y) ◇ z) ◇ w) ◇ y
equation 53204 := x ◇ y = (((x ◇ y) ◇ z) ◇ w) ◇ z
equation 53205 := x ◇ y = (((x ◇ y) ◇ z) ◇ w) ◇ w
equation 53206 := x ◇ y = (((x ◇ y) ◇ z) ◇ w) ◇ u
equation 53207 := x ◇ y = (((x ◇ z) ◇ x) ◇ x) ◇ x
equation 53208 := x ◇ y = (((x ◇ z) ◇ x) ◇ x) ◇ y
equation 53209 := x ◇ y = (((x ◇ z) ◇ x) ◇ x) ◇ z
equation 53210 := x ◇ y = (((x ◇ z) ◇ x) ◇ x) ◇ w
equation 53211 := x ◇ y = (((x ◇ z) ◇ x) ◇ y) ◇ x
equation 53212 := x ◇ y = (((x ◇ z) ◇ x) ◇ y) ◇ y
equation 53213 := x ◇ y = (((x ◇ z) ◇ x) ◇ y) ◇ z
equation 53214 := x ◇ y = (((x ◇ z) ◇ x) ◇ y) ◇ w
equation 53215 := x ◇ y = (((x ◇ z) ◇ x) ◇ z) ◇ x
equation 53216 := x ◇ y = (((x ◇ z) ◇ x) ◇ z) ◇ y
equation 53217 := x ◇ y = (((x ◇ z) ◇ x) ◇ z) ◇ z
equation 53218 := x ◇ y = (((x ◇ z) ◇ x) ◇ z) ◇ w
equation 53219 := x ◇ y = (((x ◇ z) ◇ x) ◇ w) ◇ x
equation 53220 := x ◇ y = (((x ◇ z) ◇ x) ◇ w) ◇ y
equation 53221 := x ◇ y = (((x ◇ z) ◇ x) ◇ w) ◇ z
equation 53222 := x ◇ y = (((x ◇ z) ◇ x) ◇ w) ◇ w
equation 53223 := x ◇ y = (((x ◇ z) ◇ x) ◇ w) ◇ u
equation 53224 := x ◇ y = (((x ◇ z) ◇ y) ◇ x) ◇ x
equation 53225 := x ◇ y = (((x ◇ z) ◇ y) ◇ x) ◇ y
equation 53226 := x ◇ y = (((x ◇ z) ◇ y) ◇ x) ◇ z
equation 53227 := x ◇ y = (((x ◇ z) ◇ y) ◇ x) ◇ w
equation 53228 := x ◇ y = (((x ◇ z) ◇ y) ◇ y) ◇ x
equation 53229 := x ◇ y = (((x ◇ z) ◇ y) ◇ y) ◇ y
equation 53230 := x ◇ y = (((x ◇ z) ◇ y) ◇ y) ◇ z
equation 53231 := x ◇ y = (((x ◇ z) ◇ y) ◇ y) ◇ w
equation 53232 := x ◇ y = (((x ◇ z) ◇ y) ◇ z) ◇ x
equation 53233 := x ◇ y = (((x ◇ z) ◇ y) ◇ z) ◇ y
equation 53234 := x ◇ y = (((x ◇ z) ◇ y) ◇ z) ◇ z
equation 53235 := x ◇ y = (((x ◇ z) ◇ y) ◇ z) ◇ w
equation 53236 := x ◇ y = (((x ◇ z) ◇ y) ◇ w) ◇ x
equation 53237 := x ◇ y = (((x ◇ z) ◇ y) ◇ w) ◇ y
equation 53238 := x ◇ y = (((x ◇ z) ◇ y) ◇ w) ◇ z
equation 53239 := x ◇ y = (((x ◇ z) ◇ y) ◇ w) ◇ w
equation 53240 := x ◇ y = (((x ◇ z) ◇ y) ◇ w) ◇ u
equation 53241 := x ◇ y = (((x ◇ z) ◇ z) ◇ x) ◇ x
equation 53242 := x ◇ y = (((x ◇ z) ◇ z) ◇ x) ◇ y
equation 53243 := x ◇ y = (((x ◇ z) ◇ z) ◇ x) ◇ z
equation 53244 := x ◇ y = (((x ◇ z) ◇ z) ◇ x) ◇ w
equation 53245 := x ◇ y = (((x ◇ z) ◇ z) ◇ y) ◇ x
equation 53246 := x ◇ y = (((x ◇ z) ◇ z) ◇ y) ◇ y
equation 53247 := x ◇ y = (((x ◇ z) ◇ z) ◇ y) ◇ z
equation 53248 := x ◇ y = (((x ◇ z) ◇ z) ◇ y) ◇ w
equation 53249 := x ◇ y = (((x ◇ z) ◇ z) ◇ z) ◇ x
equation 53250 := x ◇ y = (((x ◇ z) ◇ z) ◇ z) ◇ y
equation 53251 := x ◇ y = (((x ◇ z) ◇ z) ◇ z) ◇ z
equation 53252 := x ◇ y = (((x ◇ z) ◇ z) ◇ z) ◇ w
equation 53253 := x ◇ y = (((x ◇ z) ◇ z) ◇ w) ◇ x
equation 53254 := x ◇ y = (((x ◇ z) ◇ z) ◇ w) ◇ y
equation 53255 := x ◇ y = (((x ◇ z) ◇ z) ◇ w) ◇ z
equation 53256 := x ◇ y = (((x ◇ z) ◇ z) ◇ w) ◇ w
equation 53257 := x ◇ y = (((x ◇ z) ◇ z) ◇ w) ◇ u
equation 53258 := x ◇ y = (((x ◇ z) ◇ w) ◇ x) ◇ x
equation 53259 := x ◇ y = (((x ◇ z) ◇ w) ◇ x) ◇ y
equation 53260 := x ◇ y = (((x ◇ z) ◇ w) ◇ x) ◇ z
equation 53261 := x ◇ y = (((x ◇ z) ◇ w) ◇ x) ◇ w
equation 53262 := x ◇ y = (((x ◇ z) ◇ w) ◇ x) ◇ u
equation 53263 := x ◇ y = (((x ◇ z) ◇ w) ◇ y) ◇ x
equation 53264 := x ◇ y = (((x ◇ z) ◇ w) ◇ y) ◇ y
equation 53265 := x ◇ y = (((x ◇ z) ◇ w) ◇ y) ◇ z
equation 53266 := x ◇ y = (((x ◇ z) ◇ w) ◇ y) ◇ w
equation 53267 := x ◇ y = (((x ◇ z) ◇ w) ◇ y) ◇ u
equation 53268 := x ◇ y = (((x ◇ z) ◇ w) ◇ z) ◇ x
equation 53269 := x ◇ y = (((x ◇ z) ◇ w) ◇ z) ◇ y
equation 53270 := x ◇ y = (((x ◇ z) ◇ w) ◇ z) ◇ z
equation 53271 := x ◇ y = (((x ◇ z) ◇ w) ◇ z) ◇ w
equation 53272 := x ◇ y = (((x ◇ z) ◇ w) ◇ z) ◇ u
equation 53273 := x ◇ y = (((x ◇ z) ◇ w) ◇ w) ◇ x
equation 53274 := x ◇ y = (((x ◇ z) ◇ w) ◇ w) ◇ y
equation 53275 := x ◇ y = (((x ◇ z) ◇ w) ◇ w) ◇ z
equation 53276 := x ◇ y = (((x ◇ z) ◇ w) ◇ w) ◇ w
equation 53277 := x ◇ y = (((x ◇ z) ◇ w) ◇ w) ◇ u
equation 53278 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ x
equation 53279 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ y
equation 53280 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ z
equation 53281 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ w
equation 53282 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ u
equation 53283 := x ◇ y = (((x ◇ z) ◇ w) ◇ u) ◇ v
equation 53284 := x ◇ y = (((y ◇ x) ◇ x) ◇ x) ◇ x
equation 53285 := x ◇ y = (((y ◇ x) ◇ x) ◇ x) ◇ y
equation 53286 := x ◇ y = (((y ◇ x) ◇ x) ◇ x) ◇ z
equation 53287 := x ◇ y = (((y ◇ x) ◇ x) ◇ y) ◇ x
equation 53288 := x ◇ y = (((y ◇ x) ◇ x) ◇ y) ◇ y
equation 53289 := x ◇ y = (((y ◇ x) ◇ x) ◇ y) ◇ z
equation 53290 := x ◇ y = (((y ◇ x) ◇ x) ◇ z) ◇ x
equation 53291 := x ◇ y = (((y ◇ x) ◇ x) ◇ z) ◇ y
equation 53292 := x ◇ y = (((y ◇ x) ◇ x) ◇ z) ◇ z
equation 53293 := x ◇ y = (((y ◇ x) ◇ x) ◇ z) ◇ w
equation 53294 := x ◇ y = (((y ◇ x) ◇ y) ◇ x) ◇ x
equation 53295 := x ◇ y = (((y ◇ x) ◇ y) ◇ x) ◇ y
equation 53296 := x ◇ y = (((y ◇ x) ◇ y) ◇ x) ◇ z
equation 53297 := x ◇ y = (((y ◇ x) ◇ y) ◇ y) ◇ x
equation 53298 := x ◇ y = (((y ◇ x) ◇ y) ◇ y) ◇ y
equation 53299 := x ◇ y = (((y ◇ x) ◇ y) ◇ y) ◇ z
equation 53300 := x ◇ y = (((y ◇ x) ◇ y) ◇ z) ◇ x
equation 53301 := x ◇ y = (((y ◇ x) ◇ y) ◇ z) ◇ y
equation 53302 := x ◇ y = (((y ◇ x) ◇ y) ◇ z) ◇ z
equation 53303 := x ◇ y = (((y ◇ x) ◇ y) ◇ z) ◇ w
equation 53304 := x ◇ y = (((y ◇ x) ◇ z) ◇ x) ◇ x
equation 53305 := x ◇ y = (((y ◇ x) ◇ z) ◇ x) ◇ y
equation 53306 := x ◇ y = (((y ◇ x) ◇ z) ◇ x) ◇ z
equation 53307 := x ◇ y = (((y ◇ x) ◇ z) ◇ x) ◇ w
equation 53308 := x ◇ y = (((y ◇ x) ◇ z) ◇ y) ◇ x
equation 53309 := x ◇ y = (((y ◇ x) ◇ z) ◇ y) ◇ y
equation 53310 := x ◇ y = (((y ◇ x) ◇ z) ◇ y) ◇ z
equation 53311 := x ◇ y = (((y ◇ x) ◇ z) ◇ y) ◇ w
equation 53312 := x ◇ y = (((y ◇ x) ◇ z) ◇ z) ◇ x
equation 53313 := x ◇ y = (((y ◇ x) ◇ z) ◇ z) ◇ y
equation 53314 := x ◇ y = (((y ◇ x) ◇ z) ◇ z) ◇ z
equation 53315 := x ◇ y = (((y ◇ x) ◇ z) ◇ z) ◇ w
equation 53316 := x ◇ y = (((y ◇ x) ◇ z) ◇ w) ◇ x
equation 53317 := x ◇ y = (((y ◇ x) ◇ z) ◇ w) ◇ y
equation 53318 := x ◇ y = (((y ◇ x) ◇ z) ◇ w) ◇ z
equation 53319 := x ◇ y = (((y ◇ x) ◇ z) ◇ w) ◇ w
equation 53320 := x ◇ y = (((y ◇ x) ◇ z) ◇ w) ◇ u
equation 53321 := x ◇ y = (((y ◇ y) ◇ x) ◇ x) ◇ x
equation 53322 := x ◇ y = (((y ◇ y) ◇ x) ◇ x) ◇ y
equation 53323 := x ◇ y = (((y ◇ y) ◇ x) ◇ x) ◇ z
equation 53324 := x ◇ y = (((y ◇ y) ◇ x) ◇ y) ◇ x
equation 53325 := x ◇ y = (((y ◇ y) ◇ x) ◇ y) ◇ y
equation 53326 := x ◇ y = (((y ◇ y) ◇ x) ◇ y) ◇ z
equation 53327 := x ◇ y = (((y ◇ y) ◇ x) ◇ z) ◇ x
equation 53328 := x ◇ y = (((y ◇ y) ◇ x) ◇ z) ◇ y
equation 53329 := x ◇ y = (((y ◇ y) ◇ x) ◇ z) ◇ z
equation 53330 := x ◇ y = (((y ◇ y) ◇ x) ◇ z) ◇ w
equation 53331 := x ◇ y = (((y ◇ y) ◇ y) ◇ x) ◇ x
equation 53332 := x ◇ y = (((y ◇ y) ◇ y) ◇ x) ◇ y
equation 53333 := x ◇ y = (((y ◇ y) ◇ y) ◇ x) ◇ z
equation 53334 := x ◇ y = (((y ◇ y) ◇ y) ◇ y) ◇ x
equation 53335 := x ◇ y = (((y ◇ y) ◇ y) ◇ y) ◇ y
equation 53336 := x ◇ y = (((y ◇ y) ◇ y) ◇ y) ◇ z
equation 53337 := x ◇ y = (((y ◇ y) ◇ y) ◇ z) ◇ x
equation 53338 := x ◇ y = (((y ◇ y) ◇ y) ◇ z) ◇ y
equation 53339 := x ◇ y = (((y ◇ y) ◇ y) ◇ z) ◇ z
equation 53340 := x ◇ y = (((y ◇ y) ◇ y) ◇ z) ◇ w
equation 53341 := x ◇ y = (((y ◇ y) ◇ z) ◇ x) ◇ x
equation 53342 := x ◇ y = (((y ◇ y) ◇ z) ◇ x) ◇ y
equation 53343 := x ◇ y = (((y ◇ y) ◇ z) ◇ x) ◇ z
equation 53344 := x ◇ y = (((y ◇ y) ◇ z) ◇ x) ◇ w
equation 53345 := x ◇ y = (((y ◇ y) ◇ z) ◇ y) ◇ x
equation 53346 := x ◇ y = (((y ◇ y) ◇ z) ◇ y) ◇ y
equation 53347 := x ◇ y = (((y ◇ y) ◇ z) ◇ y) ◇ z
equation 53348 := x ◇ y = (((y ◇ y) ◇ z) ◇ y) ◇ w
equation 53349 := x ◇ y = (((y ◇ y) ◇ z) ◇ z) ◇ x
equation 53350 := x ◇ y = (((y ◇ y) ◇ z) ◇ z) ◇ y
equation 53351 := x ◇ y = (((y ◇ y) ◇ z) ◇ z) ◇ z
equation 53352 := x ◇ y = (((y ◇ y) ◇ z) ◇ z) ◇ w
equation 53353 := x ◇ y = (((y ◇ y) ◇ z) ◇ w) ◇ x
equation 53354 := x ◇ y = (((y ◇ y) ◇ z) ◇ w) ◇ y
equation 53355 := x ◇ y = (((y ◇ y) ◇ z) ◇ w) ◇ z
equation 53356 := x ◇ y = (((y ◇ y) ◇ z) ◇ w) ◇ w
equation 53357 := x ◇ y = (((y ◇ y) ◇ z) ◇ w) ◇ u
equation 53358 := x ◇ y = (((y ◇ z) ◇ x) ◇ x) ◇ x
equation 53359 := x ◇ y = (((y ◇ z) ◇ x) ◇ x) ◇ y
equation 53360 := x ◇ y = (((y ◇ z) ◇ x) ◇ x) ◇ z
equation 53361 := x ◇ y = (((y ◇ z) ◇ x) ◇ x) ◇ w
equation 53362 := x ◇ y = (((y ◇ z) ◇ x) ◇ y) ◇ x
equation 53363 := x ◇ y = (((y ◇ z) ◇ x) ◇ y) ◇ y
equation 53364 := x ◇ y = (((y ◇ z) ◇ x) ◇ y) ◇ z
equation 53365 := x ◇ y = (((y ◇ z) ◇ x) ◇ y) ◇ w
equation 53366 := x ◇ y = (((y ◇ z) ◇ x) ◇ z) ◇ x
equation 53367 := x ◇ y = (((y ◇ z) ◇ x) ◇ z) ◇ y
equation 53368 := x ◇ y = (((y ◇ z) ◇ x) ◇ z) ◇ z
equation 53369 := x ◇ y = (((y ◇ z) ◇ x) ◇ z) ◇ w
equation 53370 := x ◇ y = (((y ◇ z) ◇ x) ◇ w) ◇ x
equation 53371 := x ◇ y = (((y ◇ z) ◇ x) ◇ w) ◇ y
equation 53372 := x ◇ y = (((y ◇ z) ◇ x) ◇ w) ◇ z
equation 53373 := x ◇ y = (((y ◇ z) ◇ x) ◇ w) ◇ w
equation 53374 := x ◇ y = (((y ◇ z) ◇ x) ◇ w) ◇ u
equation 53375 := x ◇ y = (((y ◇ z) ◇ y) ◇ x) ◇ x
equation 53376 := x ◇ y = (((y ◇ z) ◇ y) ◇ x) ◇ y
equation 53377 := x ◇ y = (((y ◇ z) ◇ y) ◇ x) ◇ z
equation 53378 := x ◇ y = (((y ◇ z) ◇ y) ◇ x) ◇ w
equation 53379 := x ◇ y = (((y ◇ z) ◇ y) ◇ y) ◇ x
equation 53380 := x ◇ y = (((y ◇ z) ◇ y) ◇ y) ◇ y
equation 53381 := x ◇ y = (((y ◇ z) ◇ y) ◇ y) ◇ z
equation 53382 := x ◇ y = (((y ◇ z) ◇ y) ◇ y) ◇ w
equation 53383 := x ◇ y = (((y ◇ z) ◇ y) ◇ z) ◇ x
equation 53384 := x ◇ y = (((y ◇ z) ◇ y) ◇ z) ◇ y
equation 53385 := x ◇ y = (((y ◇ z) ◇ y) ◇ z) ◇ z
equation 53386 := x ◇ y = (((y ◇ z) ◇ y) ◇ z) ◇ w
equation 53387 := x ◇ y = (((y ◇ z) ◇ y) ◇ w) ◇ x
equation 53388 := x ◇ y = (((y ◇ z) ◇ y) ◇ w) ◇ y
equation 53389 := x ◇ y = (((y ◇ z) ◇ y) ◇ w) ◇ z
equation 53390 := x ◇ y = (((y ◇ z) ◇ y) ◇ w) ◇ w
equation 53391 := x ◇ y = (((y ◇ z) ◇ y) ◇ w) ◇ u
equation 53392 := x ◇ y = (((y ◇ z) ◇ z) ◇ x) ◇ x
equation 53393 := x ◇ y = (((y ◇ z) ◇ z) ◇ x) ◇ y
equation 53394 := x ◇ y = (((y ◇ z) ◇ z) ◇ x) ◇ z
equation 53395 := x ◇ y = (((y ◇ z) ◇ z) ◇ x) ◇ w
equation 53396 := x ◇ y = (((y ◇ z) ◇ z) ◇ y) ◇ x
equation 53397 := x ◇ y = (((y ◇ z) ◇ z) ◇ y) ◇ y
equation 53398 := x ◇ y = (((y ◇ z) ◇ z) ◇ y) ◇ z
equation 53399 := x ◇ y = (((y ◇ z) ◇ z) ◇ y) ◇ w
equation 53400 := x ◇ y = (((y ◇ z) ◇ z) ◇ z) ◇ x
equation 53401 := x ◇ y = (((y ◇ z) ◇ z) ◇ z) ◇ y
equation 53402 := x ◇ y = (((y ◇ z) ◇ z) ◇ z) ◇ z
equation 53403 := x ◇ y = (((y ◇ z) ◇ z) ◇ z) ◇ w
equation 53404 := x ◇ y = (((y ◇ z) ◇ z) ◇ w) ◇ x
equation 53405 := x ◇ y = (((y ◇ z) ◇ z) ◇ w) ◇ y
equation 53406 := x ◇ y = (((y ◇ z) ◇ z) ◇ w) ◇ z
equation 53407 := x ◇ y = (((y ◇ z) ◇ z) ◇ w) ◇ w
equation 53408 := x ◇ y = (((y ◇ z) ◇ z) ◇ w) ◇ u
equation 53409 := x ◇ y = (((y ◇ z) ◇ w) ◇ x) ◇ x
equation 53410 := x ◇ y = (((y ◇ z) ◇ w) ◇ x) ◇ y
equation 53411 := x ◇ y = (((y ◇ z) ◇ w) ◇ x) ◇ z
equation 53412 := x ◇ y = (((y ◇ z) ◇ w) ◇ x) ◇ w
equation 53413 := x ◇ y = (((y ◇ z) ◇ w) ◇ x) ◇ u
equation 53414 := x ◇ y = (((y ◇ z) ◇ w) ◇ y) ◇ x
equation 53415 := x ◇ y = (((y ◇ z) ◇ w) ◇ y) ◇ y
equation 53416 := x ◇ y = (((y ◇ z) ◇ w) ◇ y) ◇ z
equation 53417 := x ◇ y = (((y ◇ z) ◇ w) ◇ y) ◇ w
equation 53418 := x ◇ y = (((y ◇ z) ◇ w) ◇ y) ◇ u
equation 53419 := x ◇ y = (((y ◇ z) ◇ w) ◇ z) ◇ x
equation 53420 := x ◇ y = (((y ◇ z) ◇ w) ◇ z) ◇ y
equation 53421 := x ◇ y = (((y ◇ z) ◇ w) ◇ z) ◇ z
equation 53422 := x ◇ y = (((y ◇ z) ◇ w) ◇ z) ◇ w
equation 53423 := x ◇ y = (((y ◇ z) ◇ w) ◇ z) ◇ u
equation 53424 := x ◇ y = (((y ◇ z) ◇ w) ◇ w) ◇ x
equation 53425 := x ◇ y = (((y ◇ z) ◇ w) ◇ w) ◇ y
equation 53426 := x ◇ y = (((y ◇ z) ◇ w) ◇ w) ◇ z
equation 53427 := x ◇ y = (((y ◇ z) ◇ w) ◇ w) ◇ w
equation 53428 := x ◇ y = (((y ◇ z) ◇ w) ◇ w) ◇ u
equation 53429 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ x
equation 53430 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ y
equation 53431 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ z
equation 53432 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ w
equation 53433 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ u
equation 53434 := x ◇ y = (((y ◇ z) ◇ w) ◇ u) ◇ v
equation 53435 := x ◇ y = (((z ◇ x) ◇ x) ◇ x) ◇ x
equation 53436 := x ◇ y = (((z ◇ x) ◇ x) ◇ x) ◇ y
equation 53437 := x ◇ y = (((z ◇ x) ◇ x) ◇ x) ◇ z
equation 53438 := x ◇ y = (((z ◇ x) ◇ x) ◇ x) ◇ w
equation 53439 := x ◇ y = (((z ◇ x) ◇ x) ◇ y) ◇ x
equation 53440 := x ◇ y = (((z ◇ x) ◇ x) ◇ y) ◇ y
equation 53441 := x ◇ y = (((z ◇ x) ◇ x) ◇ y) ◇ z
equation 53442 := x ◇ y = (((z ◇ x) ◇ x) ◇ y) ◇ w
equation 53443 := x ◇ y = (((z ◇ x) ◇ x) ◇ z) ◇ x
equation 53444 := x ◇ y = (((z ◇ x) ◇ x) ◇ z) ◇ y
equation 53445 := x ◇ y = (((z ◇ x) ◇ x) ◇ z) ◇ z
equation 53446 := x ◇ y = (((z ◇ x) ◇ x) ◇ z) ◇ w
equation 53447 := x ◇ y = (((z ◇ x) ◇ x) ◇ w) ◇ x
equation 53448 := x ◇ y = (((z ◇ x) ◇ x) ◇ w) ◇ y
equation 53449 := x ◇ y = (((z ◇ x) ◇ x) ◇ w) ◇ z
equation 53450 := x ◇ y = (((z ◇ x) ◇ x) ◇ w) ◇ w
equation 53451 := x ◇ y = (((z ◇ x) ◇ x) ◇ w) ◇ u
equation 53452 := x ◇ y = (((z ◇ x) ◇ y) ◇ x) ◇ x
equation 53453 := x ◇ y = (((z ◇ x) ◇ y) ◇ x) ◇ y
equation 53454 := x ◇ y = (((z ◇ x) ◇ y) ◇ x) ◇ z
equation 53455 := x ◇ y = (((z ◇ x) ◇ y) ◇ x) ◇ w
equation 53456 := x ◇ y = (((z ◇ x) ◇ y) ◇ y) ◇ x
equation 53457 := x ◇ y = (((z ◇ x) ◇ y) ◇ y) ◇ y
equation 53458 := x ◇ y = (((z ◇ x) ◇ y) ◇ y) ◇ z
equation 53459 := x ◇ y = (((z ◇ x) ◇ y) ◇ y) ◇ w
equation 53460 := x ◇ y = (((z ◇ x) ◇ y) ◇ z) ◇ x
equation 53461 := x ◇ y = (((z ◇ x) ◇ y) ◇ z) ◇ y
equation 53462 := x ◇ y = (((z ◇ x) ◇ y) ◇ z) ◇ z
equation 53463 := x ◇ y = (((z ◇ x) ◇ y) ◇ z) ◇ w
equation 53464 := x ◇ y = (((z ◇ x) ◇ y) ◇ w) ◇ x
equation 53465 := x ◇ y = (((z ◇ x) ◇ y) ◇ w) ◇ y
equation 53466 := x ◇ y = (((z ◇ x) ◇ y) ◇ w) ◇ z
equation 53467 := x ◇ y = (((z ◇ x) ◇ y) ◇ w) ◇ w
equation 53468 := x ◇ y = (((z ◇ x) ◇ y) ◇ w) ◇ u
equation 53469 := x ◇ y = (((z ◇ x) ◇ z) ◇ x) ◇ x
equation 53470 := x ◇ y = (((z ◇ x) ◇ z) ◇ x) ◇ y
equation 53471 := x ◇ y = (((z ◇ x) ◇ z) ◇ x) ◇ z
equation 53472 := x ◇ y = (((z ◇ x) ◇ z) ◇ x) ◇ w
equation 53473 := x ◇ y = (((z ◇ x) ◇ z) ◇ y) ◇ x
equation 53474 := x ◇ y = (((z ◇ x) ◇ z) ◇ y) ◇ y
equation 53475 := x ◇ y = (((z ◇ x) ◇ z) ◇ y) ◇ z
equation 53476 := x ◇ y = (((z ◇ x) ◇ z) ◇ y) ◇ w
equation 53477 := x ◇ y = (((z ◇ x) ◇ z) ◇ z) ◇ x
equation 53478 := x ◇ y = (((z ◇ x) ◇ z) ◇ z) ◇ y
equation 53479 := x ◇ y = (((z ◇ x) ◇ z) ◇ z) ◇ z
equation 53480 := x ◇ y = (((z ◇ x) ◇ z) ◇ z) ◇ w
equation 53481 := x ◇ y = (((z ◇ x) ◇ z) ◇ w) ◇ x
equation 53482 := x ◇ y = (((z ◇ x) ◇ z) ◇ w) ◇ y
equation 53483 := x ◇ y = (((z ◇ x) ◇ z) ◇ w) ◇ z
equation 53484 := x ◇ y = (((z ◇ x) ◇ z) ◇ w) ◇ w
equation 53485 := x ◇ y = (((z ◇ x) ◇ z) ◇ w) ◇ u
equation 53486 := x ◇ y = (((z ◇ x) ◇ w) ◇ x) ◇ x
equation 53487 := x ◇ y = (((z ◇ x) ◇ w) ◇ x) ◇ y
equation 53488 := x ◇ y = (((z ◇ x) ◇ w) ◇ x) ◇ z
equation 53489 := x ◇ y = (((z ◇ x) ◇ w) ◇ x) ◇ w
equation 53490 := x ◇ y = (((z ◇ x) ◇ w) ◇ x) ◇ u
equation 53491 := x ◇ y = (((z ◇ x) ◇ w) ◇ y) ◇ x
equation 53492 := x ◇ y = (((z ◇ x) ◇ w) ◇ y) ◇ y
equation 53493 := x ◇ y = (((z ◇ x) ◇ w) ◇ y) ◇ z
equation 53494 := x ◇ y = (((z ◇ x) ◇ w) ◇ y) ◇ w
equation 53495 := x ◇ y = (((z ◇ x) ◇ w) ◇ y) ◇ u
equation 53496 := x ◇ y = (((z ◇ x) ◇ w) ◇ z) ◇ x
equation 53497 := x ◇ y = (((z ◇ x) ◇ w) ◇ z) ◇ y
equation 53498 := x ◇ y = (((z ◇ x) ◇ w) ◇ z) ◇ z
equation 53499 := x ◇ y = (((z ◇ x) ◇ w) ◇ z) ◇ w
equation 53500 := x ◇ y = (((z ◇ x) ◇ w) ◇ z) ◇ u
equation 53501 := x ◇ y = (((z ◇ x) ◇ w) ◇ w) ◇ x
equation 53502 := x ◇ y = (((z ◇ x) ◇ w) ◇ w) ◇ y
equation 53503 := x ◇ y = (((z ◇ x) ◇ w) ◇ w) ◇ z
equation 53504 := x ◇ y = (((z ◇ x) ◇ w) ◇ w) ◇ w
equation 53505 := x ◇ y = (((z ◇ x) ◇ w) ◇ w) ◇ u
equation 53506 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ x
equation 53507 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ y
equation 53508 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ z
equation 53509 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ w
equation 53510 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ u
equation 53511 := x ◇ y = (((z ◇ x) ◇ w) ◇ u) ◇ v
equation 53512 := x ◇ y = (((z ◇ y) ◇ x) ◇ x) ◇ x
equation 53513 := x ◇ y = (((z ◇ y) ◇ x) ◇ x) ◇ y
equation 53514 := x ◇ y = (((z ◇ y) ◇ x) ◇ x) ◇ z
equation 53515 := x ◇ y = (((z ◇ y) ◇ x) ◇ x) ◇ w
equation 53516 := x ◇ y = (((z ◇ y) ◇ x) ◇ y) ◇ x
equation 53517 := x ◇ y = (((z ◇ y) ◇ x) ◇ y) ◇ y
equation 53518 := x ◇ y = (((z ◇ y) ◇ x) ◇ y) ◇ z
equation 53519 := x ◇ y = (((z ◇ y) ◇ x) ◇ y) ◇ w
equation 53520 := x ◇ y = (((z ◇ y) ◇ x) ◇ z) ◇ x
equation 53521 := x ◇ y = (((z ◇ y) ◇ x) ◇ z) ◇ y
equation 53522 := x ◇ y = (((z ◇ y) ◇ x) ◇ z) ◇ z
equation 53523 := x ◇ y = (((z ◇ y) ◇ x) ◇ z) ◇ w
equation 53524 := x ◇ y = (((z ◇ y) ◇ x) ◇ w) ◇ x
equation 53525 := x ◇ y = (((z ◇ y) ◇ x) ◇ w) ◇ y
equation 53526 := x ◇ y = (((z ◇ y) ◇ x) ◇ w) ◇ z
equation 53527 := x ◇ y = (((z ◇ y) ◇ x) ◇ w) ◇ w
equation 53528 := x ◇ y = (((z ◇ y) ◇ x) ◇ w) ◇ u
equation 53529 := x ◇ y = (((z ◇ y) ◇ y) ◇ x) ◇ x
equation 53530 := x ◇ y = (((z ◇ y) ◇ y) ◇ x) ◇ y
equation 53531 := x ◇ y = (((z ◇ y) ◇ y) ◇ x) ◇ z
equation 53532 := x ◇ y = (((z ◇ y) ◇ y) ◇ x) ◇ w
equation 53533 := x ◇ y = (((z ◇ y) ◇ y) ◇ y) ◇ x
equation 53534 := x ◇ y = (((z ◇ y) ◇ y) ◇ y) ◇ y
equation 53535 := x ◇ y = (((z ◇ y) ◇ y) ◇ y) ◇ z
equation 53536 := x ◇ y = (((z ◇ y) ◇ y) ◇ y) ◇ w
equation 53537 := x ◇ y = (((z ◇ y) ◇ y) ◇ z) ◇ x
equation 53538 := x ◇ y = (((z ◇ y) ◇ y) ◇ z) ◇ y
equation 53539 := x ◇ y = (((z ◇ y) ◇ y) ◇ z) ◇ z
equation 53540 := x ◇ y = (((z ◇ y) ◇ y) ◇ z) ◇ w
equation 53541 := x ◇ y = (((z ◇ y) ◇ y) ◇ w) ◇ x
equation 53542 := x ◇ y = (((z ◇ y) ◇ y) ◇ w) ◇ y
equation 53543 := x ◇ y = (((z ◇ y) ◇ y) ◇ w) ◇ z
equation 53544 := x ◇ y = (((z ◇ y) ◇ y) ◇ w) ◇ w
equation 53545 := x ◇ y = (((z ◇ y) ◇ y) ◇ w) ◇ u
equation 53546 := x ◇ y = (((z ◇ y) ◇ z) ◇ x) ◇ x
equation 53547 := x ◇ y = (((z ◇ y) ◇ z) ◇ x) ◇ y
equation 53548 := x ◇ y = (((z ◇ y) ◇ z) ◇ x) ◇ z
equation 53549 := x ◇ y = (((z ◇ y) ◇ z) ◇ x) ◇ w
equation 53550 := x ◇ y = (((z ◇ y) ◇ z) ◇ y) ◇ x
equation 53551 := x ◇ y = (((z ◇ y) ◇ z) ◇ y) ◇ y
equation 53552 := x ◇ y = (((z ◇ y) ◇ z) ◇ y) ◇ z
equation 53553 := x ◇ y = (((z ◇ y) ◇ z) ◇ y) ◇ w
equation 53554 := x ◇ y = (((z ◇ y) ◇ z) ◇ z) ◇ x
equation 53555 := x ◇ y = (((z ◇ y) ◇ z) ◇ z) ◇ y
equation 53556 := x ◇ y = (((z ◇ y) ◇ z) ◇ z) ◇ z
equation 53557 := x ◇ y = (((z ◇ y) ◇ z) ◇ z) ◇ w
equation 53558 := x ◇ y = (((z ◇ y) ◇ z) ◇ w) ◇ x
equation 53559 := x ◇ y = (((z ◇ y) ◇ z) ◇ w) ◇ y
equation 53560 := x ◇ y = (((z ◇ y) ◇ z) ◇ w) ◇ z
equation 53561 := x ◇ y = (((z ◇ y) ◇ z) ◇ w) ◇ w
equation 53562 := x ◇ y = (((z ◇ y) ◇ z) ◇ w) ◇ u
equation 53563 := x ◇ y = (((z ◇ y) ◇ w) ◇ x) ◇ x
equation 53564 := x ◇ y = (((z ◇ y) ◇ w) ◇ x) ◇ y
equation 53565 := x ◇ y = (((z ◇ y) ◇ w) ◇ x) ◇ z
equation 53566 := x ◇ y = (((z ◇ y) ◇ w) ◇ x) ◇ w
equation 53567 := x ◇ y = (((z ◇ y) ◇ w) ◇ x) ◇ u
equation 53568 := x ◇ y = (((z ◇ y) ◇ w) ◇ y) ◇ x
equation 53569 := x ◇ y = (((z ◇ y) ◇ w) ◇ y) ◇ y
equation 53570 := x ◇ y = (((z ◇ y) ◇ w) ◇ y) ◇ z
equation 53571 := x ◇ y = (((z ◇ y) ◇ w) ◇ y) ◇ w
equation 53572 := x ◇ y = (((z ◇ y) ◇ w) ◇ y) ◇ u
equation 53573 := x ◇ y = (((z ◇ y) ◇ w) ◇ z) ◇ x
equation 53574 := x ◇ y = (((z ◇ y) ◇ w) ◇ z) ◇ y
equation 53575 := x ◇ y = (((z ◇ y) ◇ w) ◇ z) ◇ z
equation 53576 := x ◇ y = (((z ◇ y) ◇ w) ◇ z) ◇ w
equation 53577 := x ◇ y = (((z ◇ y) ◇ w) ◇ z) ◇ u
equation 53578 := x ◇ y = (((z ◇ y) ◇ w) ◇ w) ◇ x
equation 53579 := x ◇ y = (((z ◇ y) ◇ w) ◇ w) ◇ y
equation 53580 := x ◇ y = (((z ◇ y) ◇ w) ◇ w) ◇ z
equation 53581 := x ◇ y = (((z ◇ y) ◇ w) ◇ w) ◇ w
equation 53582 := x ◇ y = (((z ◇ y) ◇ w) ◇ w) ◇ u
equation 53583 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ x
equation 53584 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ y
equation 53585 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ z
equation 53586 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ w
equation 53587 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ u
equation 53588 := x ◇ y = (((z ◇ y) ◇ w) ◇ u) ◇ v
equation 53589 := x ◇ y = (((z ◇ z) ◇ x) ◇ x) ◇ x
equation 53590 := x ◇ y = (((z ◇ z) ◇ x) ◇ x) ◇ y
equation 53591 := x ◇ y = (((z ◇ z) ◇ x) ◇ x) ◇ z
equation 53592 := x ◇ y = (((z ◇ z) ◇ x) ◇ x) ◇ w
equation 53593 := x ◇ y = (((z ◇ z) ◇ x) ◇ y) ◇ x
equation 53594 := x ◇ y = (((z ◇ z) ◇ x) ◇ y) ◇ y
equation 53595 := x ◇ y = (((z ◇ z) ◇ x) ◇ y) ◇ z
equation 53596 := x ◇ y = (((z ◇ z) ◇ x) ◇ y) ◇ w
equation 53597 := x ◇ y = (((z ◇ z) ◇ x) ◇ z) ◇ x
equation 53598 := x ◇ y = (((z ◇ z) ◇ x) ◇ z) ◇ y
equation 53599 := x ◇ y = (((z ◇ z) ◇ x) ◇ z) ◇ z
equation 53600 := x ◇ y = (((z ◇ z) ◇ x) ◇ z) ◇ w
equation 53601 := x ◇ y = (((z ◇ z) ◇ x) ◇ w) ◇ x
equation 53602 := x ◇ y = (((z ◇ z) ◇ x) ◇ w) ◇ y
equation 53603 := x ◇ y = (((z ◇ z) ◇ x) ◇ w) ◇ z
equation 53604 := x ◇ y = (((z ◇ z) ◇ x) ◇ w) ◇ w
equation 53605 := x ◇ y = (((z ◇ z) ◇ x) ◇ w) ◇ u
equation 53606 := x ◇ y = (((z ◇ z) ◇ y) ◇ x) ◇ x
equation 53607 := x ◇ y = (((z ◇ z) ◇ y) ◇ x) ◇ y
equation 53608 := x ◇ y = (((z ◇ z) ◇ y) ◇ x) ◇ z
equation 53609 := x ◇ y = (((z ◇ z) ◇ y) ◇ x) ◇ w
equation 53610 := x ◇ y = (((z ◇ z) ◇ y) ◇ y) ◇ x
equation 53611 := x ◇ y = (((z ◇ z) ◇ y) ◇ y) ◇ y
equation 53612 := x ◇ y = (((z ◇ z) ◇ y) ◇ y) ◇ z
equation 53613 := x ◇ y = (((z ◇ z) ◇ y) ◇ y) ◇ w
equation 53614 := x ◇ y = (((z ◇ z) ◇ y) ◇ z) ◇ x
equation 53615 := x ◇ y = (((z ◇ z) ◇ y) ◇ z) ◇ y
equation 53616 := x ◇ y = (((z ◇ z) ◇ y) ◇ z) ◇ z
equation 53617 := x ◇ y = (((z ◇ z) ◇ y) ◇ z) ◇ w
equation 53618 := x ◇ y = (((z ◇ z) ◇ y) ◇ w) ◇ x
equation 53619 := x ◇ y = (((z ◇ z) ◇ y) ◇ w) ◇ y
equation 53620 := x ◇ y = (((z ◇ z) ◇ y) ◇ w) ◇ z
equation 53621 := x ◇ y = (((z ◇ z) ◇ y) ◇ w) ◇ w
equation 53622 := x ◇ y = (((z ◇ z) ◇ y) ◇ w) ◇ u
equation 53623 := x ◇ y = (((z ◇ z) ◇ z) ◇ x) ◇ x
equation 53624 := x ◇ y = (((z ◇ z) ◇ z) ◇ x) ◇ y
equation 53625 := x ◇ y = (((z ◇ z) ◇ z) ◇ x) ◇ z
equation 53626 := x ◇ y = (((z ◇ z) ◇ z) ◇ x) ◇ w
equation 53627 := x ◇ y = (((z ◇ z) ◇ z) ◇ y) ◇ x
equation 53628 := x ◇ y = (((z ◇ z) ◇ z) ◇ y) ◇ y
equation 53629 := x ◇ y = (((z ◇ z) ◇ z) ◇ y) ◇ z
equation 53630 := x ◇ y = (((z ◇ z) ◇ z) ◇ y) ◇ w
equation 53631 := x ◇ y = (((z ◇ z) ◇ z) ◇ z) ◇ x
equation 53632 := x ◇ y = (((z ◇ z) ◇ z) ◇ z) ◇ y
equation 53633 := x ◇ y = (((z ◇ z) ◇ z) ◇ z) ◇ z
equation 53634 := x ◇ y = (((z ◇ z) ◇ z) ◇ z) ◇ w
equation 53635 := x ◇ y = (((z ◇ z) ◇ z) ◇ w) ◇ x
equation 53636 := x ◇ y = (((z ◇ z) ◇ z) ◇ w) ◇ y
equation 53637 := x ◇ y = (((z ◇ z) ◇ z) ◇ w) ◇ z
equation 53638 := x ◇ y = (((z ◇ z) ◇ z) ◇ w) ◇ w
equation 53639 := x ◇ y = (((z ◇ z) ◇ z) ◇ w) ◇ u
equation 53640 := x ◇ y = (((z ◇ z) ◇ w) ◇ x) ◇ x
equation 53641 := x ◇ y = (((z ◇ z) ◇ w) ◇ x) ◇ y
equation 53642 := x ◇ y = (((z ◇ z) ◇ w) ◇ x) ◇ z
equation 53643 := x ◇ y = (((z ◇ z) ◇ w) ◇ x) ◇ w
equation 53644 := x ◇ y = (((z ◇ z) ◇ w) ◇ x) ◇ u
equation 53645 := x ◇ y = (((z ◇ z) ◇ w) ◇ y) ◇ x
equation 53646 := x ◇ y = (((z ◇ z) ◇ w) ◇ y) ◇ y
equation 53647 := x ◇ y = (((z ◇ z) ◇ w) ◇ y) ◇ z
equation 53648 := x ◇ y = (((z ◇ z) ◇ w) ◇ y) ◇ w
equation 53649 := x ◇ y = (((z ◇ z) ◇ w) ◇ y) ◇ u
equation 53650 := x ◇ y = (((z ◇ z) ◇ w) ◇ z) ◇ x
equation 53651 := x ◇ y = (((z ◇ z) ◇ w) ◇ z) ◇ y
equation 53652 := x ◇ y = (((z ◇ z) ◇ w) ◇ z) ◇ z
equation 53653 := x ◇ y = (((z ◇ z) ◇ w) ◇ z) ◇ w
equation 53654 := x ◇ y = (((z ◇ z) ◇ w) ◇ z) ◇ u
equation 53655 := x ◇ y = (((z ◇ z) ◇ w) ◇ w) ◇ x
equation 53656 := x ◇ y = (((z ◇ z) ◇ w) ◇ w) ◇ y
equation 53657 := x ◇ y = (((z ◇ z) ◇ w) ◇ w) ◇ z
equation 53658 := x ◇ y = (((z ◇ z) ◇ w) ◇ w) ◇ w
equation 53659 := x ◇ y = (((z ◇ z) ◇ w) ◇ w) ◇ u
equation 53660 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ x
equation 53661 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ y
equation 53662 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ z
equation 53663 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ w
equation 53664 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ u
equation 53665 := x ◇ y = (((z ◇ z) ◇ w) ◇ u) ◇ v
equation 53666 := x ◇ y = (((z ◇ w) ◇ x) ◇ x) ◇ x
equation 53667 := x ◇ y = (((z ◇ w) ◇ x) ◇ x) ◇ y
equation 53668 := x ◇ y = (((z ◇ w) ◇ x) ◇ x) ◇ z
equation 53669 := x ◇ y = (((z ◇ w) ◇ x) ◇ x) ◇ w
equation 53670 := x ◇ y = (((z ◇ w) ◇ x) ◇ x) ◇ u
equation 53671 := x ◇ y = (((z ◇ w) ◇ x) ◇ y) ◇ x
equation 53672 := x ◇ y = (((z ◇ w) ◇ x) ◇ y) ◇ y
equation 53673 := x ◇ y = (((z ◇ w) ◇ x) ◇ y) ◇ z
equation 53674 := x ◇ y = (((z ◇ w) ◇ x) ◇ y) ◇ w
equation 53675 := x ◇ y = (((z ◇ w) ◇ x) ◇ y) ◇ u
equation 53676 := x ◇ y = (((z ◇ w) ◇ x) ◇ z) ◇ x
equation 53677 := x ◇ y = (((z ◇ w) ◇ x) ◇ z) ◇ y
equation 53678 := x ◇ y = (((z ◇ w) ◇ x) ◇ z) ◇ z
equation 53679 := x ◇ y = (((z ◇ w) ◇ x) ◇ z) ◇ w
equation 53680 := x ◇ y = (((z ◇ w) ◇ x) ◇ z) ◇ u
equation 53681 := x ◇ y = (((z ◇ w) ◇ x) ◇ w) ◇ x
equation 53682 := x ◇ y = (((z ◇ w) ◇ x) ◇ w) ◇ y
equation 53683 := x ◇ y = (((z ◇ w) ◇ x) ◇ w) ◇ z
equation 53684 := x ◇ y = (((z ◇ w) ◇ x) ◇ w) ◇ w
equation 53685 := x ◇ y = (((z ◇ w) ◇ x) ◇ w) ◇ u
equation 53686 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ x
equation 53687 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ y
equation 53688 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ z
equation 53689 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ w
equation 53690 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ u
equation 53691 := x ◇ y = (((z ◇ w) ◇ x) ◇ u) ◇ v
equation 53692 := x ◇ y = (((z ◇ w) ◇ y) ◇ x) ◇ x
equation 53693 := x ◇ y = (((z ◇ w) ◇ y) ◇ x) ◇ y
equation 53694 := x ◇ y = (((z ◇ w) ◇ y) ◇ x) ◇ z
equation 53695 := x ◇ y = (((z ◇ w) ◇ y) ◇ x) ◇ w
equation 53696 := x ◇ y = (((z ◇ w) ◇ y) ◇ x) ◇ u
equation 53697 := x ◇ y = (((z ◇ w) ◇ y) ◇ y) ◇ x
equation 53698 := x ◇ y = (((z ◇ w) ◇ y) ◇ y) ◇ y
equation 53699 := x ◇ y = (((z ◇ w) ◇ y) ◇ y) ◇ z
equation 53700 := x ◇ y = (((z ◇ w) ◇ y) ◇ y) ◇ w
equation 53701 := x ◇ y = (((z ◇ w) ◇ y) ◇ y) ◇ u
equation 53702 := x ◇ y = (((z ◇ w) ◇ y) ◇ z) ◇ x
equation 53703 := x ◇ y = (((z ◇ w) ◇ y) ◇ z) ◇ y
equation 53704 := x ◇ y = (((z ◇ w) ◇ y) ◇ z) ◇ z
equation 53705 := x ◇ y = (((z ◇ w) ◇ y) ◇ z) ◇ w
equation 53706 := x ◇ y = (((z ◇ w) ◇ y) ◇ z) ◇ u
equation 53707 := x ◇ y = (((z ◇ w) ◇ y) ◇ w) ◇ x
equation 53708 := x ◇ y = (((z ◇ w) ◇ y) ◇ w) ◇ y
equation 53709 := x ◇ y = (((z ◇ w) ◇ y) ◇ w) ◇ z
equation 53710 := x ◇ y = (((z ◇ w) ◇ y) ◇ w) ◇ w
equation 53711 := x ◇ y = (((z ◇ w) ◇ y) ◇ w) ◇ u
equation 53712 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ x
equation 53713 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ y
equation 53714 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ z
equation 53715 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ w
equation 53716 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ u
equation 53717 := x ◇ y = (((z ◇ w) ◇ y) ◇ u) ◇ v
equation 53718 := x ◇ y = (((z ◇ w) ◇ z) ◇ x) ◇ x
equation 53719 := x ◇ y = (((z ◇ w) ◇ z) ◇ x) ◇ y
equation 53720 := x ◇ y = (((z ◇ w) ◇ z) ◇ x) ◇ z
equation 53721 := x ◇ y = (((z ◇ w) ◇ z) ◇ x) ◇ w
equation 53722 := x ◇ y = (((z ◇ w) ◇ z) ◇ x) ◇ u
equation 53723 := x ◇ y = (((z ◇ w) ◇ z) ◇ y) ◇ x
equation 53724 := x ◇ y = (((z ◇ w) ◇ z) ◇ y) ◇ y
equation 53725 := x ◇ y = (((z ◇ w) ◇ z) ◇ y) ◇ z
equation 53726 := x ◇ y = (((z ◇ w) ◇ z) ◇ y) ◇ w
equation 53727 := x ◇ y = (((z ◇ w) ◇ z) ◇ y) ◇ u
equation 53728 := x ◇ y = (((z ◇ w) ◇ z) ◇ z) ◇ x
equation 53729 := x ◇ y = (((z ◇ w) ◇ z) ◇ z) ◇ y
equation 53730 := x ◇ y = (((z ◇ w) ◇ z) ◇ z) ◇ z
equation 53731 := x ◇ y = (((z ◇ w) ◇ z) ◇ z) ◇ w
equation 53732 := x ◇ y = (((z ◇ w) ◇ z) ◇ z) ◇ u
equation 53733 := x ◇ y = (((z ◇ w) ◇ z) ◇ w) ◇ x
equation 53734 := x ◇ y = (((z ◇ w) ◇ z) ◇ w) ◇ y
equation 53735 := x ◇ y = (((z ◇ w) ◇ z) ◇ w) ◇ z
equation 53736 := x ◇ y = (((z ◇ w) ◇ z) ◇ w) ◇ w
equation 53737 := x ◇ y = (((z ◇ w) ◇ z) ◇ w) ◇ u
equation 53738 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ x
equation 53739 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ y
equation 53740 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ z
equation 53741 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ w
equation 53742 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ u
equation 53743 := x ◇ y = (((z ◇ w) ◇ z) ◇ u) ◇ v
equation 53744 := x ◇ y = (((z ◇ w) ◇ w) ◇ x) ◇ x
equation 53745 := x ◇ y = (((z ◇ w) ◇ w) ◇ x) ◇ y
equation 53746 := x ◇ y = (((z ◇ w) ◇ w) ◇ x) ◇ z
equation 53747 := x ◇ y = (((z ◇ w) ◇ w) ◇ x) ◇ w
equation 53748 := x ◇ y = (((z ◇ w) ◇ w) ◇ x) ◇ u
equation 53749 := x ◇ y = (((z ◇ w) ◇ w) ◇ y) ◇ x
equation 53750 := x ◇ y = (((z ◇ w) ◇ w) ◇ y) ◇ y
equation 53751 := x ◇ y = (((z ◇ w) ◇ w) ◇ y) ◇ z
equation 53752 := x ◇ y = (((z ◇ w) ◇ w) ◇ y) ◇ w
equation 53753 := x ◇ y = (((z ◇ w) ◇ w) ◇ y) ◇ u
equation 53754 := x ◇ y = (((z ◇ w) ◇ w) ◇ z) ◇ x
equation 53755 := x ◇ y = (((z ◇ w) ◇ w) ◇ z) ◇ y
equation 53756 := x ◇ y = (((z ◇ w) ◇ w) ◇ z) ◇ z
equation 53757 := x ◇ y = (((z ◇ w) ◇ w) ◇ z) ◇ w
equation 53758 := x ◇ y = (((z ◇ w) ◇ w) ◇ z) ◇ u
equation 53759 := x ◇ y = (((z ◇ w) ◇ w) ◇ w) ◇ x
equation 53760 := x ◇ y = (((z ◇ w) ◇ w) ◇ w) ◇ y
equation 53761 := x ◇ y = (((z ◇ w) ◇ w) ◇ w) ◇ z
equation 53762 := x ◇ y = (((z ◇ w) ◇ w) ◇ w) ◇ w
equation 53763 := x ◇ y = (((z ◇ w) ◇ w) ◇ w) ◇ u
equation 53764 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ x
equation 53765 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ y
equation 53766 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ z
equation 53767 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ w
equation 53768 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ u
equation 53769 := x ◇ y = (((z ◇ w) ◇ w) ◇ u) ◇ v
equation 53770 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ x
equation 53771 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ y
equation 53772 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ z
equation 53773 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ w
equation 53774 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ u
equation 53775 := x ◇ y = (((z ◇ w) ◇ u) ◇ x) ◇ v
equation 53776 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ x
equation 53777 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ y
equation 53778 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ z
equation 53779 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ w
equation 53780 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ u
equation 53781 := x ◇ y = (((z ◇ w) ◇ u) ◇ y) ◇ v
equation 53782 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ x
equation 53783 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ y
equation 53784 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ z
equation 53785 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ w
equation 53786 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ u
equation 53787 := x ◇ y = (((z ◇ w) ◇ u) ◇ z) ◇ v
equation 53788 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ x
equation 53789 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ y
equation 53790 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ z
equation 53791 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ w
equation 53792 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ u
equation 53793 := x ◇ y = (((z ◇ w) ◇ u) ◇ w) ◇ v
equation 53794 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ x
equation 53795 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ y
equation 53796 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ z
equation 53797 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ w
equation 53798 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ u
equation 53799 := x ◇ y = (((z ◇ w) ◇ u) ◇ u) ◇ v
equation 53800 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ x
equation 53801 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ y
equation 53802 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ z
equation 53803 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ w
equation 53804 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ u
equation 53805 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ v
equation 53806 := x ◇ y = (((z ◇ w) ◇ u) ◇ v) ◇ r
equation 53807 := x ◇ (x ◇ x) = x ◇ (x ◇ (x ◇ x))
equation 53808 := x ◇ (x ◇ x) = x ◇ (x ◇ (x ◇ y))
equation 53809 := x ◇ (x ◇ x) = x ◇ (x ◇ (y ◇ x))
equation 53810 := x ◇ (x ◇ x) = x ◇ (x ◇ (y ◇ y))
equation 53811 := x ◇ (x ◇ x) = x ◇ (x ◇ (y ◇ z))
equation 53812 := x ◇ (x ◇ x) = x ◇ (y ◇ (x ◇ x))
equation 53813 := x ◇ (x ◇ x) = x ◇ (y ◇ (x ◇ y))
equation 53814 := x ◇ (x ◇ x) = x ◇ (y ◇ (x ◇ z))
equation 53815 := x ◇ (x ◇ x) = x ◇ (y ◇ (y ◇ x))
equation 53816 := x ◇ (x ◇ x) = x ◇ (y ◇ (y ◇ y))
equation 53817 := x ◇ (x ◇ x) = x ◇ (y ◇ (y ◇ z))
equation 53818 := x ◇ (x ◇ x) = x ◇ (y ◇ (z ◇ x))
equation 53819 := x ◇ (x ◇ x) = x ◇ (y ◇ (z ◇ y))
equation 53820 := x ◇ (x ◇ x) = x ◇ (y ◇ (z ◇ z))
equation 53821 := x ◇ (x ◇ x) = x ◇ (y ◇ (z ◇ w))
equation 53822 := x ◇ (x ◇ x) = y ◇ (x ◇ (x ◇ x))
equation 53823 := x ◇ (x ◇ x) = y ◇ (x ◇ (x ◇ y))
equation 53824 := x ◇ (x ◇ x) = y ◇ (x ◇ (x ◇ z))
equation 53825 := x ◇ (x ◇ x) = y ◇ (x ◇ (y ◇ x))
equation 53826 := x ◇ (x ◇ x) = y ◇ (x ◇ (y ◇ y))
equation 53827 := x ◇ (x ◇ x) = y ◇ (x ◇ (y ◇ z))
equation 53828 := x ◇ (x ◇ x) = y ◇ (x ◇ (z ◇ x))
equation 53829 := x ◇ (x ◇ x) = y ◇ (x ◇ (z ◇ y))
equation 53830 := x ◇ (x ◇ x) = y ◇ (x ◇ (z ◇ z))
equation 53831 := x ◇ (x ◇ x) = y ◇ (x ◇ (z ◇ w))
equation 53832 := x ◇ (x ◇ x) = y ◇ (y ◇ (x ◇ x))
equation 53833 := x ◇ (x ◇ x) = y ◇ (y ◇ (x ◇ y))
equation 53834 := x ◇ (x ◇ x) = y ◇ (y ◇ (x ◇ z))
equation 53835 := x ◇ (x ◇ x) = y ◇ (y ◇ (y ◇ x))
equation 53836 := x ◇ (x ◇ x) = y ◇ (y ◇ (y ◇ y))
equation 53837 := x ◇ (x ◇ x) = y ◇ (y ◇ (y ◇ z))
equation 53838 := x ◇ (x ◇ x) = y ◇ (y ◇ (z ◇ x))
equation 53839 := x ◇ (x ◇ x) = y ◇ (y ◇ (z ◇ y))
equation 53840 := x ◇ (x ◇ x) = y ◇ (y ◇ (z ◇ z))
equation 53841 := x ◇ (x ◇ x) = y ◇ (y ◇ (z ◇ w))
equation 53842 := x ◇ (x ◇ x) = y ◇ (z ◇ (x ◇ x))
equation 53843 := x ◇ (x ◇ x) = y ◇ (z ◇ (x ◇ y))
equation 53844 := x ◇ (x ◇ x) = y ◇ (z ◇ (x ◇ z))
equation 53845 := x ◇ (x ◇ x) = y ◇ (z ◇ (x ◇ w))
equation 53846 := x ◇ (x ◇ x) = y ◇ (z ◇ (y ◇ x))
equation 53847 := x ◇ (x ◇ x) = y ◇ (z ◇ (y ◇ y))
equation 53848 := x ◇ (x ◇ x) = y ◇ (z ◇ (y ◇ z))
equation 53849 := x ◇ (x ◇ x) = y ◇ (z ◇ (y ◇ w))
equation 53850 := x ◇ (x ◇ x) = y ◇ (z ◇ (z ◇ x))
equation 53851 := x ◇ (x ◇ x) = y ◇ (z ◇ (z ◇ y))
equation 53852 := x ◇ (x ◇ x) = y ◇ (z ◇ (z ◇ z))
equation 53853 := x ◇ (x ◇ x) = y ◇ (z ◇ (z ◇ w))
equation 53854 := x ◇ (x ◇ x) = y ◇ (z ◇ (w ◇ x))
equation 53855 := x ◇ (x ◇ x) = y ◇ (z ◇ (w ◇ y))
equation 53856 := x ◇ (x ◇ x) = y ◇ (z ◇ (w ◇ z))
equation 53857 := x ◇ (x ◇ x) = y ◇ (z ◇ (w ◇ w))
equation 53858 := x ◇ (x ◇ x) = y ◇ (z ◇ (w ◇ u))
equation 53859 := x ◇ (x ◇ y) = x ◇ (x ◇ (x ◇ x))
equation 53860 := x ◇ (x ◇ y) = x ◇ (x ◇ (x ◇ y))
equation 53861 := x ◇ (x ◇ y) = x ◇ (x ◇ (x ◇ z))
equation 53862 := x ◇ (x ◇ y) = x ◇ (x ◇ (y ◇ x))
equation 53863 := x ◇ (x ◇ y) = x ◇ (x ◇ (y ◇ y))
equation 53864 := x ◇ (x ◇ y) = x ◇ (x ◇ (y ◇ z))
equation 53865 := x ◇ (x ◇ y) = x ◇ (x ◇ (z ◇ x))
equation 53866 := x ◇ (x ◇ y) = x ◇ (x ◇ (z ◇ y))
equation 53867 := x ◇ (x ◇ y) = x ◇ (x ◇ (z ◇ z))
equation 53868 := x ◇ (x ◇ y) = x ◇ (x ◇ (z ◇ w))
equation 53869 := x ◇ (x ◇ y) = x ◇ (y ◇ (x ◇ x))
equation 53870 := x ◇ (x ◇ y) = x ◇ (y ◇ (x ◇ y))
equation 53871 := x ◇ (x ◇ y) = x ◇ (y ◇ (x ◇ z))
equation 53872 := x ◇ (x ◇ y) = x ◇ (y ◇ (y ◇ x))
equation 53873 := x ◇ (x ◇ y) = x ◇ (y ◇ (y ◇ y))
equation 53874 := x ◇ (x ◇ y) = x ◇ (y ◇ (y ◇ z))
equation 53875 := x ◇ (x ◇ y) = x ◇ (y ◇ (z ◇ x))
equation 53876 := x ◇ (x ◇ y) = x ◇ (y ◇ (z ◇ y))
equation 53877 := x ◇ (x ◇ y) = x ◇ (y ◇ (z ◇ z))
equation 53878 := x ◇ (x ◇ y) = x ◇ (y ◇ (z ◇ w))
equation 53879 := x ◇ (x ◇ y) = x ◇ (z ◇ (x ◇ x))
equation 53880 := x ◇ (x ◇ y) = x ◇ (z ◇ (x ◇ y))
equation 53881 := x ◇ (x ◇ y) = x ◇ (z ◇ (x ◇ z))
equation 53882 := x ◇ (x ◇ y) = x ◇ (z ◇ (x ◇ w))
equation 53883 := x ◇ (x ◇ y) = x ◇ (z ◇ (y ◇ x))
equation 53884 := x ◇ (x ◇ y) = x ◇ (z ◇ (y ◇ y))
equation 53885 := x ◇ (x ◇ y) = x ◇ (z ◇ (y ◇ z))
equation 53886 := x ◇ (x ◇ y) = x ◇ (z ◇ (y ◇ w))
equation 53887 := x ◇ (x ◇ y) = x ◇ (z ◇ (z ◇ x))
equation 53888 := x ◇ (x ◇ y) = x ◇ (z ◇ (z ◇ y))
equation 53889 := x ◇ (x ◇ y) = x ◇ (z ◇ (z ◇ z))
equation 53890 := x ◇ (x ◇ y) = x ◇ (z ◇ (z ◇ w))
equation 53891 := x ◇ (x ◇ y) = x ◇ (z ◇ (w ◇ x))
equation 53892 := x ◇ (x ◇ y) = x ◇ (z ◇ (w ◇ y))
equation 53893 := x ◇ (x ◇ y) = x ◇ (z ◇ (w ◇ z))
equation 53894 := x ◇ (x ◇ y) = x ◇ (z ◇ (w ◇ w))
equation 53895 := x ◇ (x ◇ y) = x ◇ (z ◇ (w ◇ u))
equation 53896 := x ◇ (x ◇ y) = y ◇ (x ◇ (x ◇ x))
equation 53897 := x ◇ (x ◇ y) = y ◇ (x ◇ (x ◇ y))
equation 53898 := x ◇ (x ◇ y) = y ◇ (x ◇ (x ◇ z))
equation 53899 := x ◇ (x ◇ y) = y ◇ (x ◇ (y ◇ x))
equation 53900 := x ◇ (x ◇ y) = y ◇ (x ◇ (y ◇ y))
equation 53901 := x ◇ (x ◇ y) = y ◇ (x ◇ (y ◇ z))
equation 53902 := x ◇ (x ◇ y) = y ◇ (x ◇ (z ◇ x))
equation 53903 := x ◇ (x ◇ y) = y ◇ (x ◇ (z ◇ y))
equation 53904 := x ◇ (x ◇ y) = y ◇ (x ◇ (z ◇ z))
equation 53905 := x ◇ (x ◇ y) = y ◇ (x ◇ (z ◇ w))
equation 53906 := x ◇ (x ◇ y) = y ◇ (y ◇ (x ◇ x))
equation 53907 := x ◇ (x ◇ y) = y ◇ (y ◇ (x ◇ y))
equation 53908 := x ◇ (x ◇ y) = y ◇ (y ◇ (x ◇ z))
equation 53909 := x ◇ (x ◇ y) = y ◇ (y ◇ (y ◇ x))
equation 53910 := x ◇ (x ◇ y) = y ◇ (y ◇ (y ◇ y))
equation 53911 := x ◇ (x ◇ y) = y ◇ (y ◇ (y ◇ z))
equation 53912 := x ◇ (x ◇ y) = y ◇ (y ◇ (z ◇ x))
equation 53913 := x ◇ (x ◇ y) = y ◇ (y ◇ (z ◇ y))
equation 53914 := x ◇ (x ◇ y) = y ◇ (y ◇ (z ◇ z))
equation 53915 := x ◇ (x ◇ y) = y ◇ (y ◇ (z ◇ w))
equation 53916 := x ◇ (x ◇ y) = y ◇ (z ◇ (x ◇ x))
equation 53917 := x ◇ (x ◇ y) = y ◇ (z ◇ (x ◇ y))
equation 53918 := x ◇ (x ◇ y) = y ◇ (z ◇ (x ◇ z))
equation 53919 := x ◇ (x ◇ y) = y ◇ (z ◇ (x ◇ w))
equation 53920 := x ◇ (x ◇ y) = y ◇ (z ◇ (y ◇ x))
equation 53921 := x ◇ (x ◇ y) = y ◇ (z ◇ (y ◇ y))
equation 53922 := x ◇ (x ◇ y) = y ◇ (z ◇ (y ◇ z))
equation 53923 := x ◇ (x ◇ y) = y ◇ (z ◇ (y ◇ w))
equation 53924 := x ◇ (x ◇ y) = y ◇ (z ◇ (z ◇ x))
equation 53925 := x ◇ (x ◇ y) = y ◇ (z ◇ (z ◇ y))
equation 53926 := x ◇ (x ◇ y) = y ◇ (z ◇ (z ◇ z))
equation 53927 := x ◇ (x ◇ y) = y ◇ (z ◇ (z ◇ w))
equation 53928 := x ◇ (x ◇ y) = y ◇ (z ◇ (w ◇ x))
equation 53929 := x ◇ (x ◇ y) = y ◇ (z ◇ (w ◇ y))
equation 53930 := x ◇ (x ◇ y) = y ◇ (z ◇ (w ◇ z))
equation 53931 := x ◇ (x ◇ y) = y ◇ (z ◇ (w ◇ w))
equation 53932 := x ◇ (x ◇ y) = y ◇ (z ◇ (w ◇ u))
equation 53933 := x ◇ (x ◇ y) = z ◇ (x ◇ (x ◇ x))
equation 53934 := x ◇ (x ◇ y) = z ◇ (x ◇ (x ◇ y))
equation 53935 := x ◇ (x ◇ y) = z ◇ (x ◇ (x ◇ z))
equation 53936 := x ◇ (x ◇ y) = z ◇ (x ◇ (x ◇ w))
equation 53937 := x ◇ (x ◇ y) = z ◇ (x ◇ (y ◇ x))
equation 53938 := x ◇ (x ◇ y) = z ◇ (x ◇ (y ◇ y))
equation 53939 := x ◇ (x ◇ y) = z ◇ (x ◇ (y ◇ z))
equation 53940 := x ◇ (x ◇ y) = z ◇ (x ◇ (y ◇ w))
equation 53941 := x ◇ (x ◇ y) = z ◇ (x ◇ (z ◇ x))
equation 53942 := x ◇ (x ◇ y) = z ◇ (x ◇ (z ◇ y))
equation 53943 := x ◇ (x ◇ y) = z ◇ (x ◇ (z ◇ z))
equation 53944 := x ◇ (x ◇ y) = z ◇ (x ◇ (z ◇ w))
equation 53945 := x ◇ (x ◇ y) = z ◇ (x ◇ (w ◇ x))
equation 53946 := x ◇ (x ◇ y) = z ◇ (x ◇ (w ◇ y))
equation 53947 := x ◇ (x ◇ y) = z ◇ (x ◇ (w ◇ z))
equation 53948 := x ◇ (x ◇ y) = z ◇ (x ◇ (w ◇ w))
equation 53949 := x ◇ (x ◇ y) = z ◇ (x ◇ (w ◇ u))
equation 53950 := x ◇ (x ◇ y) = z ◇ (y ◇ (x ◇ x))
equation 53951 := x ◇ (x ◇ y) = z ◇ (y ◇ (x ◇ y))
equation 53952 := x ◇ (x ◇ y) = z ◇ (y ◇ (x ◇ z))
equation 53953 := x ◇ (x ◇ y) = z ◇ (y ◇ (x ◇ w))
equation 53954 := x ◇ (x ◇ y) = z ◇ (y ◇ (y ◇ x))
equation 53955 := x ◇ (x ◇ y) = z ◇ (y ◇ (y ◇ y))
equation 53956 := x ◇ (x ◇ y) = z ◇ (y ◇ (y ◇ z))
equation 53957 := x ◇ (x ◇ y) = z ◇ (y ◇ (y ◇ w))
equation 53958 := x ◇ (x ◇ y) = z ◇ (y ◇ (z ◇ x))
equation 53959 := x ◇ (x ◇ y) = z ◇ (y ◇ (z ◇ y))
equation 53960 := x ◇ (x ◇ y) = z ◇ (y ◇ (z ◇ z))
equation 53961 := x ◇ (x ◇ y) = z ◇ (y ◇ (z ◇ w))
equation 53962 := x ◇ (x ◇ y) = z ◇ (y ◇ (w ◇ x))
equation 53963 := x ◇ (x ◇ y) = z ◇ (y ◇ (w ◇ y))
equation 53964 := x ◇ (x ◇ y) = z ◇ (y ◇ (w ◇ z))
equation 53965 := x ◇ (x ◇ y) = z ◇ (y ◇ (w ◇ w))
equation 53966 := x ◇ (x ◇ y) = z ◇ (y ◇ (w ◇ u))
equation 53967 := x ◇ (x ◇ y) = z ◇ (z ◇ (x ◇ x))
equation 53968 := x ◇ (x ◇ y) = z ◇ (z ◇ (x ◇ y))
equation 53969 := x ◇ (x ◇ y) = z ◇ (z ◇ (x ◇ z))
equation 53970 := x ◇ (x ◇ y) = z ◇ (z ◇ (x ◇ w))
equation 53971 := x ◇ (x ◇ y) = z ◇ (z ◇ (y ◇ x))
equation 53972 := x ◇ (x ◇ y) = z ◇ (z ◇ (y ◇ y))
equation 53973 := x ◇ (x ◇ y) = z ◇ (z ◇ (y ◇ z))
equation 53974 := x ◇ (x ◇ y) = z ◇ (z ◇ (y ◇ w))
equation 53975 := x ◇ (x ◇ y) = z ◇ (z ◇ (z ◇ x))
equation 53976 := x ◇ (x ◇ y) = z ◇ (z ◇ (z ◇ y))
equation 53977 := x ◇ (x ◇ y) = z ◇ (z ◇ (z ◇ z))
equation 53978 := x ◇ (x ◇ y) = z ◇ (z ◇ (z ◇ w))
equation 53979 := x ◇ (x ◇ y) = z ◇ (z ◇ (w ◇ x))
equation 53980 := x ◇ (x ◇ y) = z ◇ (z ◇ (w ◇ y))
equation 53981 := x ◇ (x ◇ y) = z ◇ (z ◇ (w ◇ z))
equation 53982 := x ◇ (x ◇ y) = z ◇ (z ◇ (w ◇ w))
equation 53983 := x ◇ (x ◇ y) = z ◇ (z ◇ (w ◇ u))
equation 53984 := x ◇ (x ◇ y) = z ◇ (w ◇ (x ◇ x))
equation 53985 := x ◇ (x ◇ y) = z ◇ (w ◇ (x ◇ y))
equation 53986 := x ◇ (x ◇ y) = z ◇ (w ◇ (x ◇ z))
equation 53987 := x ◇ (x ◇ y) = z ◇ (w ◇ (x ◇ w))
equation 53988 := x ◇ (x ◇ y) = z ◇ (w ◇ (x ◇ u))
equation 53989 := x ◇ (x ◇ y) = z ◇ (w ◇ (y ◇ x))
equation 53990 := x ◇ (x ◇ y) = z ◇ (w ◇ (y ◇ y))
equation 53991 := x ◇ (x ◇ y) = z ◇ (w ◇ (y ◇ z))
equation 53992 := x ◇ (x ◇ y) = z ◇ (w ◇ (y ◇ w))
equation 53993 := x ◇ (x ◇ y) = z ◇ (w ◇ (y ◇ u))
equation 53994 := x ◇ (x ◇ y) = z ◇ (w ◇ (z ◇ x))
equation 53995 := x ◇ (x ◇ y) = z ◇ (w ◇ (z ◇ y))
equation 53996 := x ◇ (x ◇ y) = z ◇ (w ◇ (z ◇ z))
equation 53997 := x ◇ (x ◇ y) = z ◇ (w ◇ (z ◇ w))
equation 53998 := x ◇ (x ◇ y) = z ◇ (w ◇ (z ◇ u))
equation 53999 := x ◇ (x ◇ y) = z ◇ (w ◇ (w ◇ x))
