import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 62000-62576 -/

equation 62000 := (x ◇ y) ◇ x = ((z ◇ y) ◇ y) ◇ z
equation 62001 := (x ◇ y) ◇ x = ((z ◇ y) ◇ y) ◇ w
equation 62002 := (x ◇ y) ◇ x = ((z ◇ y) ◇ z) ◇ x
equation 62003 := (x ◇ y) ◇ x = ((z ◇ y) ◇ z) ◇ y
equation 62004 := (x ◇ y) ◇ x = ((z ◇ y) ◇ z) ◇ z
equation 62005 := (x ◇ y) ◇ x = ((z ◇ y) ◇ z) ◇ w
equation 62006 := (x ◇ y) ◇ x = ((z ◇ y) ◇ w) ◇ x
equation 62007 := (x ◇ y) ◇ x = ((z ◇ y) ◇ w) ◇ y
equation 62008 := (x ◇ y) ◇ x = ((z ◇ y) ◇ w) ◇ z
equation 62009 := (x ◇ y) ◇ x = ((z ◇ y) ◇ w) ◇ w
equation 62010 := (x ◇ y) ◇ x = ((z ◇ y) ◇ w) ◇ u
equation 62011 := (x ◇ y) ◇ x = ((z ◇ z) ◇ x) ◇ x
equation 62012 := (x ◇ y) ◇ x = ((z ◇ z) ◇ x) ◇ y
equation 62013 := (x ◇ y) ◇ x = ((z ◇ z) ◇ x) ◇ z
equation 62014 := (x ◇ y) ◇ x = ((z ◇ z) ◇ x) ◇ w
equation 62015 := (x ◇ y) ◇ x = ((z ◇ z) ◇ y) ◇ x
equation 62016 := (x ◇ y) ◇ x = ((z ◇ z) ◇ y) ◇ y
equation 62017 := (x ◇ y) ◇ x = ((z ◇ z) ◇ y) ◇ z
equation 62018 := (x ◇ y) ◇ x = ((z ◇ z) ◇ y) ◇ w
equation 62019 := (x ◇ y) ◇ x = ((z ◇ z) ◇ z) ◇ x
equation 62020 := (x ◇ y) ◇ x = ((z ◇ z) ◇ z) ◇ y
equation 62021 := (x ◇ y) ◇ x = ((z ◇ z) ◇ z) ◇ z
equation 62022 := (x ◇ y) ◇ x = ((z ◇ z) ◇ z) ◇ w
equation 62023 := (x ◇ y) ◇ x = ((z ◇ z) ◇ w) ◇ x
equation 62024 := (x ◇ y) ◇ x = ((z ◇ z) ◇ w) ◇ y
equation 62025 := (x ◇ y) ◇ x = ((z ◇ z) ◇ w) ◇ z
equation 62026 := (x ◇ y) ◇ x = ((z ◇ z) ◇ w) ◇ w
equation 62027 := (x ◇ y) ◇ x = ((z ◇ z) ◇ w) ◇ u
equation 62028 := (x ◇ y) ◇ x = ((z ◇ w) ◇ x) ◇ x
equation 62029 := (x ◇ y) ◇ x = ((z ◇ w) ◇ x) ◇ y
equation 62030 := (x ◇ y) ◇ x = ((z ◇ w) ◇ x) ◇ z
equation 62031 := (x ◇ y) ◇ x = ((z ◇ w) ◇ x) ◇ w
equation 62032 := (x ◇ y) ◇ x = ((z ◇ w) ◇ x) ◇ u
equation 62033 := (x ◇ y) ◇ x = ((z ◇ w) ◇ y) ◇ x
equation 62034 := (x ◇ y) ◇ x = ((z ◇ w) ◇ y) ◇ y
equation 62035 := (x ◇ y) ◇ x = ((z ◇ w) ◇ y) ◇ z
equation 62036 := (x ◇ y) ◇ x = ((z ◇ w) ◇ y) ◇ w
equation 62037 := (x ◇ y) ◇ x = ((z ◇ w) ◇ y) ◇ u
equation 62038 := (x ◇ y) ◇ x = ((z ◇ w) ◇ z) ◇ x
equation 62039 := (x ◇ y) ◇ x = ((z ◇ w) ◇ z) ◇ y
equation 62040 := (x ◇ y) ◇ x = ((z ◇ w) ◇ z) ◇ z
equation 62041 := (x ◇ y) ◇ x = ((z ◇ w) ◇ z) ◇ w
equation 62042 := (x ◇ y) ◇ x = ((z ◇ w) ◇ z) ◇ u
equation 62043 := (x ◇ y) ◇ x = ((z ◇ w) ◇ w) ◇ x
equation 62044 := (x ◇ y) ◇ x = ((z ◇ w) ◇ w) ◇ y
equation 62045 := (x ◇ y) ◇ x = ((z ◇ w) ◇ w) ◇ z
equation 62046 := (x ◇ y) ◇ x = ((z ◇ w) ◇ w) ◇ w
equation 62047 := (x ◇ y) ◇ x = ((z ◇ w) ◇ w) ◇ u
equation 62048 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ x
equation 62049 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ y
equation 62050 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ z
equation 62051 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ w
equation 62052 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ u
equation 62053 := (x ◇ y) ◇ x = ((z ◇ w) ◇ u) ◇ v
equation 62054 := (x ◇ y) ◇ y = ((x ◇ x) ◇ x) ◇ x
equation 62055 := (x ◇ y) ◇ y = ((x ◇ x) ◇ x) ◇ y
equation 62056 := (x ◇ y) ◇ y = ((x ◇ x) ◇ x) ◇ z
equation 62057 := (x ◇ y) ◇ y = ((x ◇ x) ◇ y) ◇ x
equation 62058 := (x ◇ y) ◇ y = ((x ◇ x) ◇ y) ◇ y
equation 62059 := (x ◇ y) ◇ y = ((x ◇ x) ◇ y) ◇ z
equation 62060 := (x ◇ y) ◇ y = ((x ◇ x) ◇ z) ◇ x
equation 62061 := (x ◇ y) ◇ y = ((x ◇ x) ◇ z) ◇ y
equation 62062 := (x ◇ y) ◇ y = ((x ◇ x) ◇ z) ◇ z
equation 62063 := (x ◇ y) ◇ y = ((x ◇ x) ◇ z) ◇ w
equation 62064 := (x ◇ y) ◇ y = ((x ◇ y) ◇ x) ◇ x
equation 62065 := (x ◇ y) ◇ y = ((x ◇ y) ◇ x) ◇ y
equation 62066 := (x ◇ y) ◇ y = ((x ◇ y) ◇ x) ◇ z
equation 62067 := (x ◇ y) ◇ y = ((x ◇ y) ◇ y) ◇ x
equation 62068 := (x ◇ y) ◇ y = ((x ◇ y) ◇ y) ◇ y
equation 62069 := (x ◇ y) ◇ y = ((x ◇ y) ◇ y) ◇ z
equation 62070 := (x ◇ y) ◇ y = ((x ◇ y) ◇ z) ◇ x
equation 62071 := (x ◇ y) ◇ y = ((x ◇ y) ◇ z) ◇ y
equation 62072 := (x ◇ y) ◇ y = ((x ◇ y) ◇ z) ◇ z
equation 62073 := (x ◇ y) ◇ y = ((x ◇ y) ◇ z) ◇ w
equation 62074 := (x ◇ y) ◇ y = ((x ◇ z) ◇ x) ◇ x
equation 62075 := (x ◇ y) ◇ y = ((x ◇ z) ◇ x) ◇ y
equation 62076 := (x ◇ y) ◇ y = ((x ◇ z) ◇ x) ◇ z
equation 62077 := (x ◇ y) ◇ y = ((x ◇ z) ◇ x) ◇ w
equation 62078 := (x ◇ y) ◇ y = ((x ◇ z) ◇ y) ◇ x
equation 62079 := (x ◇ y) ◇ y = ((x ◇ z) ◇ y) ◇ y
equation 62080 := (x ◇ y) ◇ y = ((x ◇ z) ◇ y) ◇ z
equation 62081 := (x ◇ y) ◇ y = ((x ◇ z) ◇ y) ◇ w
equation 62082 := (x ◇ y) ◇ y = ((x ◇ z) ◇ z) ◇ x
equation 62083 := (x ◇ y) ◇ y = ((x ◇ z) ◇ z) ◇ y
equation 62084 := (x ◇ y) ◇ y = ((x ◇ z) ◇ z) ◇ z
equation 62085 := (x ◇ y) ◇ y = ((x ◇ z) ◇ z) ◇ w
equation 62086 := (x ◇ y) ◇ y = ((x ◇ z) ◇ w) ◇ x
equation 62087 := (x ◇ y) ◇ y = ((x ◇ z) ◇ w) ◇ y
equation 62088 := (x ◇ y) ◇ y = ((x ◇ z) ◇ w) ◇ z
equation 62089 := (x ◇ y) ◇ y = ((x ◇ z) ◇ w) ◇ w
equation 62090 := (x ◇ y) ◇ y = ((x ◇ z) ◇ w) ◇ u
equation 62091 := (x ◇ y) ◇ y = ((y ◇ x) ◇ x) ◇ x
equation 62092 := (x ◇ y) ◇ y = ((y ◇ x) ◇ x) ◇ y
equation 62093 := (x ◇ y) ◇ y = ((y ◇ x) ◇ x) ◇ z
equation 62094 := (x ◇ y) ◇ y = ((y ◇ x) ◇ y) ◇ x
equation 62095 := (x ◇ y) ◇ y = ((y ◇ x) ◇ y) ◇ y
equation 62096 := (x ◇ y) ◇ y = ((y ◇ x) ◇ y) ◇ z
equation 62097 := (x ◇ y) ◇ y = ((y ◇ x) ◇ z) ◇ x
equation 62098 := (x ◇ y) ◇ y = ((y ◇ x) ◇ z) ◇ y
equation 62099 := (x ◇ y) ◇ y = ((y ◇ x) ◇ z) ◇ z
equation 62100 := (x ◇ y) ◇ y = ((y ◇ x) ◇ z) ◇ w
equation 62101 := (x ◇ y) ◇ y = ((y ◇ y) ◇ x) ◇ x
equation 62102 := (x ◇ y) ◇ y = ((y ◇ y) ◇ x) ◇ y
equation 62103 := (x ◇ y) ◇ y = ((y ◇ y) ◇ x) ◇ z
equation 62104 := (x ◇ y) ◇ y = ((y ◇ y) ◇ y) ◇ x
equation 62105 := (x ◇ y) ◇ y = ((y ◇ y) ◇ y) ◇ y
equation 62106 := (x ◇ y) ◇ y = ((y ◇ y) ◇ y) ◇ z
equation 62107 := (x ◇ y) ◇ y = ((y ◇ y) ◇ z) ◇ x
equation 62108 := (x ◇ y) ◇ y = ((y ◇ y) ◇ z) ◇ y
equation 62109 := (x ◇ y) ◇ y = ((y ◇ y) ◇ z) ◇ z
equation 62110 := (x ◇ y) ◇ y = ((y ◇ y) ◇ z) ◇ w
equation 62111 := (x ◇ y) ◇ y = ((y ◇ z) ◇ x) ◇ x
equation 62112 := (x ◇ y) ◇ y = ((y ◇ z) ◇ x) ◇ y
equation 62113 := (x ◇ y) ◇ y = ((y ◇ z) ◇ x) ◇ z
equation 62114 := (x ◇ y) ◇ y = ((y ◇ z) ◇ x) ◇ w
equation 62115 := (x ◇ y) ◇ y = ((y ◇ z) ◇ y) ◇ x
equation 62116 := (x ◇ y) ◇ y = ((y ◇ z) ◇ y) ◇ y
equation 62117 := (x ◇ y) ◇ y = ((y ◇ z) ◇ y) ◇ z
equation 62118 := (x ◇ y) ◇ y = ((y ◇ z) ◇ y) ◇ w
equation 62119 := (x ◇ y) ◇ y = ((y ◇ z) ◇ z) ◇ x
equation 62120 := (x ◇ y) ◇ y = ((y ◇ z) ◇ z) ◇ y
equation 62121 := (x ◇ y) ◇ y = ((y ◇ z) ◇ z) ◇ z
equation 62122 := (x ◇ y) ◇ y = ((y ◇ z) ◇ z) ◇ w
equation 62123 := (x ◇ y) ◇ y = ((y ◇ z) ◇ w) ◇ x
equation 62124 := (x ◇ y) ◇ y = ((y ◇ z) ◇ w) ◇ y
equation 62125 := (x ◇ y) ◇ y = ((y ◇ z) ◇ w) ◇ z
equation 62126 := (x ◇ y) ◇ y = ((y ◇ z) ◇ w) ◇ w
equation 62127 := (x ◇ y) ◇ y = ((y ◇ z) ◇ w) ◇ u
equation 62128 := (x ◇ y) ◇ y = ((z ◇ x) ◇ x) ◇ x
equation 62129 := (x ◇ y) ◇ y = ((z ◇ x) ◇ x) ◇ y
equation 62130 := (x ◇ y) ◇ y = ((z ◇ x) ◇ x) ◇ z
equation 62131 := (x ◇ y) ◇ y = ((z ◇ x) ◇ x) ◇ w
equation 62132 := (x ◇ y) ◇ y = ((z ◇ x) ◇ y) ◇ x
equation 62133 := (x ◇ y) ◇ y = ((z ◇ x) ◇ y) ◇ y
equation 62134 := (x ◇ y) ◇ y = ((z ◇ x) ◇ y) ◇ z
equation 62135 := (x ◇ y) ◇ y = ((z ◇ x) ◇ y) ◇ w
equation 62136 := (x ◇ y) ◇ y = ((z ◇ x) ◇ z) ◇ x
equation 62137 := (x ◇ y) ◇ y = ((z ◇ x) ◇ z) ◇ y
equation 62138 := (x ◇ y) ◇ y = ((z ◇ x) ◇ z) ◇ z
equation 62139 := (x ◇ y) ◇ y = ((z ◇ x) ◇ z) ◇ w
equation 62140 := (x ◇ y) ◇ y = ((z ◇ x) ◇ w) ◇ x
equation 62141 := (x ◇ y) ◇ y = ((z ◇ x) ◇ w) ◇ y
equation 62142 := (x ◇ y) ◇ y = ((z ◇ x) ◇ w) ◇ z
equation 62143 := (x ◇ y) ◇ y = ((z ◇ x) ◇ w) ◇ w
equation 62144 := (x ◇ y) ◇ y = ((z ◇ x) ◇ w) ◇ u
equation 62145 := (x ◇ y) ◇ y = ((z ◇ y) ◇ x) ◇ x
equation 62146 := (x ◇ y) ◇ y = ((z ◇ y) ◇ x) ◇ y
equation 62147 := (x ◇ y) ◇ y = ((z ◇ y) ◇ x) ◇ z
equation 62148 := (x ◇ y) ◇ y = ((z ◇ y) ◇ x) ◇ w
equation 62149 := (x ◇ y) ◇ y = ((z ◇ y) ◇ y) ◇ x
equation 62150 := (x ◇ y) ◇ y = ((z ◇ y) ◇ y) ◇ y
equation 62151 := (x ◇ y) ◇ y = ((z ◇ y) ◇ y) ◇ z
equation 62152 := (x ◇ y) ◇ y = ((z ◇ y) ◇ y) ◇ w
equation 62153 := (x ◇ y) ◇ y = ((z ◇ y) ◇ z) ◇ x
equation 62154 := (x ◇ y) ◇ y = ((z ◇ y) ◇ z) ◇ y
equation 62155 := (x ◇ y) ◇ y = ((z ◇ y) ◇ z) ◇ z
equation 62156 := (x ◇ y) ◇ y = ((z ◇ y) ◇ z) ◇ w
equation 62157 := (x ◇ y) ◇ y = ((z ◇ y) ◇ w) ◇ x
equation 62158 := (x ◇ y) ◇ y = ((z ◇ y) ◇ w) ◇ y
equation 62159 := (x ◇ y) ◇ y = ((z ◇ y) ◇ w) ◇ z
equation 62160 := (x ◇ y) ◇ y = ((z ◇ y) ◇ w) ◇ w
equation 62161 := (x ◇ y) ◇ y = ((z ◇ y) ◇ w) ◇ u
equation 62162 := (x ◇ y) ◇ y = ((z ◇ z) ◇ x) ◇ x
equation 62163 := (x ◇ y) ◇ y = ((z ◇ z) ◇ x) ◇ y
equation 62164 := (x ◇ y) ◇ y = ((z ◇ z) ◇ x) ◇ z
equation 62165 := (x ◇ y) ◇ y = ((z ◇ z) ◇ x) ◇ w
equation 62166 := (x ◇ y) ◇ y = ((z ◇ z) ◇ y) ◇ x
equation 62167 := (x ◇ y) ◇ y = ((z ◇ z) ◇ y) ◇ y
equation 62168 := (x ◇ y) ◇ y = ((z ◇ z) ◇ y) ◇ z
equation 62169 := (x ◇ y) ◇ y = ((z ◇ z) ◇ y) ◇ w
equation 62170 := (x ◇ y) ◇ y = ((z ◇ z) ◇ z) ◇ x
equation 62171 := (x ◇ y) ◇ y = ((z ◇ z) ◇ z) ◇ y
equation 62172 := (x ◇ y) ◇ y = ((z ◇ z) ◇ z) ◇ z
equation 62173 := (x ◇ y) ◇ y = ((z ◇ z) ◇ z) ◇ w
equation 62174 := (x ◇ y) ◇ y = ((z ◇ z) ◇ w) ◇ x
equation 62175 := (x ◇ y) ◇ y = ((z ◇ z) ◇ w) ◇ y
equation 62176 := (x ◇ y) ◇ y = ((z ◇ z) ◇ w) ◇ z
equation 62177 := (x ◇ y) ◇ y = ((z ◇ z) ◇ w) ◇ w
equation 62178 := (x ◇ y) ◇ y = ((z ◇ z) ◇ w) ◇ u
equation 62179 := (x ◇ y) ◇ y = ((z ◇ w) ◇ x) ◇ x
equation 62180 := (x ◇ y) ◇ y = ((z ◇ w) ◇ x) ◇ y
equation 62181 := (x ◇ y) ◇ y = ((z ◇ w) ◇ x) ◇ z
equation 62182 := (x ◇ y) ◇ y = ((z ◇ w) ◇ x) ◇ w
equation 62183 := (x ◇ y) ◇ y = ((z ◇ w) ◇ x) ◇ u
equation 62184 := (x ◇ y) ◇ y = ((z ◇ w) ◇ y) ◇ x
equation 62185 := (x ◇ y) ◇ y = ((z ◇ w) ◇ y) ◇ y
equation 62186 := (x ◇ y) ◇ y = ((z ◇ w) ◇ y) ◇ z
equation 62187 := (x ◇ y) ◇ y = ((z ◇ w) ◇ y) ◇ w
equation 62188 := (x ◇ y) ◇ y = ((z ◇ w) ◇ y) ◇ u
equation 62189 := (x ◇ y) ◇ y = ((z ◇ w) ◇ z) ◇ x
equation 62190 := (x ◇ y) ◇ y = ((z ◇ w) ◇ z) ◇ y
equation 62191 := (x ◇ y) ◇ y = ((z ◇ w) ◇ z) ◇ z
equation 62192 := (x ◇ y) ◇ y = ((z ◇ w) ◇ z) ◇ w
equation 62193 := (x ◇ y) ◇ y = ((z ◇ w) ◇ z) ◇ u
equation 62194 := (x ◇ y) ◇ y = ((z ◇ w) ◇ w) ◇ x
equation 62195 := (x ◇ y) ◇ y = ((z ◇ w) ◇ w) ◇ y
equation 62196 := (x ◇ y) ◇ y = ((z ◇ w) ◇ w) ◇ z
equation 62197 := (x ◇ y) ◇ y = ((z ◇ w) ◇ w) ◇ w
equation 62198 := (x ◇ y) ◇ y = ((z ◇ w) ◇ w) ◇ u
equation 62199 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ x
equation 62200 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ y
equation 62201 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ z
equation 62202 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ w
equation 62203 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ u
equation 62204 := (x ◇ y) ◇ y = ((z ◇ w) ◇ u) ◇ v
equation 62205 := (x ◇ y) ◇ z = ((x ◇ x) ◇ x) ◇ x
equation 62206 := (x ◇ y) ◇ z = ((x ◇ x) ◇ x) ◇ y
equation 62207 := (x ◇ y) ◇ z = ((x ◇ x) ◇ x) ◇ z
equation 62208 := (x ◇ y) ◇ z = ((x ◇ x) ◇ x) ◇ w
equation 62209 := (x ◇ y) ◇ z = ((x ◇ x) ◇ y) ◇ x
equation 62210 := (x ◇ y) ◇ z = ((x ◇ x) ◇ y) ◇ y
equation 62211 := (x ◇ y) ◇ z = ((x ◇ x) ◇ y) ◇ z
equation 62212 := (x ◇ y) ◇ z = ((x ◇ x) ◇ y) ◇ w
equation 62213 := (x ◇ y) ◇ z = ((x ◇ x) ◇ z) ◇ x
equation 62214 := (x ◇ y) ◇ z = ((x ◇ x) ◇ z) ◇ y
equation 62215 := (x ◇ y) ◇ z = ((x ◇ x) ◇ z) ◇ z
equation 62216 := (x ◇ y) ◇ z = ((x ◇ x) ◇ z) ◇ w
equation 62217 := (x ◇ y) ◇ z = ((x ◇ x) ◇ w) ◇ x
equation 62218 := (x ◇ y) ◇ z = ((x ◇ x) ◇ w) ◇ y
equation 62219 := (x ◇ y) ◇ z = ((x ◇ x) ◇ w) ◇ z
equation 62220 := (x ◇ y) ◇ z = ((x ◇ x) ◇ w) ◇ w
equation 62221 := (x ◇ y) ◇ z = ((x ◇ x) ◇ w) ◇ u
equation 62222 := (x ◇ y) ◇ z = ((x ◇ y) ◇ x) ◇ x
equation 62223 := (x ◇ y) ◇ z = ((x ◇ y) ◇ x) ◇ y
equation 62224 := (x ◇ y) ◇ z = ((x ◇ y) ◇ x) ◇ z
equation 62225 := (x ◇ y) ◇ z = ((x ◇ y) ◇ x) ◇ w
equation 62226 := (x ◇ y) ◇ z = ((x ◇ y) ◇ y) ◇ x
equation 62227 := (x ◇ y) ◇ z = ((x ◇ y) ◇ y) ◇ y
equation 62228 := (x ◇ y) ◇ z = ((x ◇ y) ◇ y) ◇ z
equation 62229 := (x ◇ y) ◇ z = ((x ◇ y) ◇ y) ◇ w
equation 62230 := (x ◇ y) ◇ z = ((x ◇ y) ◇ z) ◇ x
equation 62231 := (x ◇ y) ◇ z = ((x ◇ y) ◇ z) ◇ y
equation 62232 := (x ◇ y) ◇ z = ((x ◇ y) ◇ z) ◇ z
equation 62233 := (x ◇ y) ◇ z = ((x ◇ y) ◇ z) ◇ w
equation 62234 := (x ◇ y) ◇ z = ((x ◇ y) ◇ w) ◇ x
equation 62235 := (x ◇ y) ◇ z = ((x ◇ y) ◇ w) ◇ y
equation 62236 := (x ◇ y) ◇ z = ((x ◇ y) ◇ w) ◇ z
equation 62237 := (x ◇ y) ◇ z = ((x ◇ y) ◇ w) ◇ w
equation 62238 := (x ◇ y) ◇ z = ((x ◇ y) ◇ w) ◇ u
equation 62239 := (x ◇ y) ◇ z = ((x ◇ z) ◇ x) ◇ x
equation 62240 := (x ◇ y) ◇ z = ((x ◇ z) ◇ x) ◇ y
equation 62241 := (x ◇ y) ◇ z = ((x ◇ z) ◇ x) ◇ z
equation 62242 := (x ◇ y) ◇ z = ((x ◇ z) ◇ x) ◇ w
equation 62243 := (x ◇ y) ◇ z = ((x ◇ z) ◇ y) ◇ x
equation 62244 := (x ◇ y) ◇ z = ((x ◇ z) ◇ y) ◇ y
equation 62245 := (x ◇ y) ◇ z = ((x ◇ z) ◇ y) ◇ z
equation 62246 := (x ◇ y) ◇ z = ((x ◇ z) ◇ y) ◇ w
equation 62247 := (x ◇ y) ◇ z = ((x ◇ z) ◇ z) ◇ x
equation 62248 := (x ◇ y) ◇ z = ((x ◇ z) ◇ z) ◇ y
equation 62249 := (x ◇ y) ◇ z = ((x ◇ z) ◇ z) ◇ z
equation 62250 := (x ◇ y) ◇ z = ((x ◇ z) ◇ z) ◇ w
equation 62251 := (x ◇ y) ◇ z = ((x ◇ z) ◇ w) ◇ x
equation 62252 := (x ◇ y) ◇ z = ((x ◇ z) ◇ w) ◇ y
equation 62253 := (x ◇ y) ◇ z = ((x ◇ z) ◇ w) ◇ z
equation 62254 := (x ◇ y) ◇ z = ((x ◇ z) ◇ w) ◇ w
equation 62255 := (x ◇ y) ◇ z = ((x ◇ z) ◇ w) ◇ u
equation 62256 := (x ◇ y) ◇ z = ((x ◇ w) ◇ x) ◇ x
equation 62257 := (x ◇ y) ◇ z = ((x ◇ w) ◇ x) ◇ y
equation 62258 := (x ◇ y) ◇ z = ((x ◇ w) ◇ x) ◇ z
equation 62259 := (x ◇ y) ◇ z = ((x ◇ w) ◇ x) ◇ w
equation 62260 := (x ◇ y) ◇ z = ((x ◇ w) ◇ x) ◇ u
equation 62261 := (x ◇ y) ◇ z = ((x ◇ w) ◇ y) ◇ x
equation 62262 := (x ◇ y) ◇ z = ((x ◇ w) ◇ y) ◇ y
equation 62263 := (x ◇ y) ◇ z = ((x ◇ w) ◇ y) ◇ z
equation 62264 := (x ◇ y) ◇ z = ((x ◇ w) ◇ y) ◇ w
equation 62265 := (x ◇ y) ◇ z = ((x ◇ w) ◇ y) ◇ u
equation 62266 := (x ◇ y) ◇ z = ((x ◇ w) ◇ z) ◇ x
equation 62267 := (x ◇ y) ◇ z = ((x ◇ w) ◇ z) ◇ y
equation 62268 := (x ◇ y) ◇ z = ((x ◇ w) ◇ z) ◇ z
equation 62269 := (x ◇ y) ◇ z = ((x ◇ w) ◇ z) ◇ w
equation 62270 := (x ◇ y) ◇ z = ((x ◇ w) ◇ z) ◇ u
equation 62271 := (x ◇ y) ◇ z = ((x ◇ w) ◇ w) ◇ x
equation 62272 := (x ◇ y) ◇ z = ((x ◇ w) ◇ w) ◇ y
equation 62273 := (x ◇ y) ◇ z = ((x ◇ w) ◇ w) ◇ z
equation 62274 := (x ◇ y) ◇ z = ((x ◇ w) ◇ w) ◇ w
equation 62275 := (x ◇ y) ◇ z = ((x ◇ w) ◇ w) ◇ u
equation 62276 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ x
equation 62277 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ y
equation 62278 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ z
equation 62279 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ w
equation 62280 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ u
equation 62281 := (x ◇ y) ◇ z = ((x ◇ w) ◇ u) ◇ v
equation 62282 := (x ◇ y) ◇ z = ((y ◇ x) ◇ x) ◇ x
equation 62283 := (x ◇ y) ◇ z = ((y ◇ x) ◇ x) ◇ y
equation 62284 := (x ◇ y) ◇ z = ((y ◇ x) ◇ x) ◇ z
equation 62285 := (x ◇ y) ◇ z = ((y ◇ x) ◇ x) ◇ w
equation 62286 := (x ◇ y) ◇ z = ((y ◇ x) ◇ y) ◇ x
equation 62287 := (x ◇ y) ◇ z = ((y ◇ x) ◇ y) ◇ y
equation 62288 := (x ◇ y) ◇ z = ((y ◇ x) ◇ y) ◇ z
equation 62289 := (x ◇ y) ◇ z = ((y ◇ x) ◇ y) ◇ w
equation 62290 := (x ◇ y) ◇ z = ((y ◇ x) ◇ z) ◇ x
equation 62291 := (x ◇ y) ◇ z = ((y ◇ x) ◇ z) ◇ y
equation 62292 := (x ◇ y) ◇ z = ((y ◇ x) ◇ z) ◇ z
equation 62293 := (x ◇ y) ◇ z = ((y ◇ x) ◇ z) ◇ w
equation 62294 := (x ◇ y) ◇ z = ((y ◇ x) ◇ w) ◇ x
equation 62295 := (x ◇ y) ◇ z = ((y ◇ x) ◇ w) ◇ y
equation 62296 := (x ◇ y) ◇ z = ((y ◇ x) ◇ w) ◇ z
equation 62297 := (x ◇ y) ◇ z = ((y ◇ x) ◇ w) ◇ w
equation 62298 := (x ◇ y) ◇ z = ((y ◇ x) ◇ w) ◇ u
equation 62299 := (x ◇ y) ◇ z = ((y ◇ y) ◇ x) ◇ x
equation 62300 := (x ◇ y) ◇ z = ((y ◇ y) ◇ x) ◇ y
equation 62301 := (x ◇ y) ◇ z = ((y ◇ y) ◇ x) ◇ z
equation 62302 := (x ◇ y) ◇ z = ((y ◇ y) ◇ x) ◇ w
equation 62303 := (x ◇ y) ◇ z = ((y ◇ y) ◇ y) ◇ x
equation 62304 := (x ◇ y) ◇ z = ((y ◇ y) ◇ y) ◇ y
equation 62305 := (x ◇ y) ◇ z = ((y ◇ y) ◇ y) ◇ z
equation 62306 := (x ◇ y) ◇ z = ((y ◇ y) ◇ y) ◇ w
equation 62307 := (x ◇ y) ◇ z = ((y ◇ y) ◇ z) ◇ x
equation 62308 := (x ◇ y) ◇ z = ((y ◇ y) ◇ z) ◇ y
equation 62309 := (x ◇ y) ◇ z = ((y ◇ y) ◇ z) ◇ z
equation 62310 := (x ◇ y) ◇ z = ((y ◇ y) ◇ z) ◇ w
equation 62311 := (x ◇ y) ◇ z = ((y ◇ y) ◇ w) ◇ x
equation 62312 := (x ◇ y) ◇ z = ((y ◇ y) ◇ w) ◇ y
equation 62313 := (x ◇ y) ◇ z = ((y ◇ y) ◇ w) ◇ z
equation 62314 := (x ◇ y) ◇ z = ((y ◇ y) ◇ w) ◇ w
equation 62315 := (x ◇ y) ◇ z = ((y ◇ y) ◇ w) ◇ u
equation 62316 := (x ◇ y) ◇ z = ((y ◇ z) ◇ x) ◇ x
equation 62317 := (x ◇ y) ◇ z = ((y ◇ z) ◇ x) ◇ y
equation 62318 := (x ◇ y) ◇ z = ((y ◇ z) ◇ x) ◇ z
equation 62319 := (x ◇ y) ◇ z = ((y ◇ z) ◇ x) ◇ w
equation 62320 := (x ◇ y) ◇ z = ((y ◇ z) ◇ y) ◇ x
equation 62321 := (x ◇ y) ◇ z = ((y ◇ z) ◇ y) ◇ y
equation 62322 := (x ◇ y) ◇ z = ((y ◇ z) ◇ y) ◇ z
equation 62323 := (x ◇ y) ◇ z = ((y ◇ z) ◇ y) ◇ w
equation 62324 := (x ◇ y) ◇ z = ((y ◇ z) ◇ z) ◇ x
equation 62325 := (x ◇ y) ◇ z = ((y ◇ z) ◇ z) ◇ y
equation 62326 := (x ◇ y) ◇ z = ((y ◇ z) ◇ z) ◇ z
equation 62327 := (x ◇ y) ◇ z = ((y ◇ z) ◇ z) ◇ w
equation 62328 := (x ◇ y) ◇ z = ((y ◇ z) ◇ w) ◇ x
equation 62329 := (x ◇ y) ◇ z = ((y ◇ z) ◇ w) ◇ y
equation 62330 := (x ◇ y) ◇ z = ((y ◇ z) ◇ w) ◇ z
equation 62331 := (x ◇ y) ◇ z = ((y ◇ z) ◇ w) ◇ w
equation 62332 := (x ◇ y) ◇ z = ((y ◇ z) ◇ w) ◇ u
equation 62333 := (x ◇ y) ◇ z = ((y ◇ w) ◇ x) ◇ x
equation 62334 := (x ◇ y) ◇ z = ((y ◇ w) ◇ x) ◇ y
equation 62335 := (x ◇ y) ◇ z = ((y ◇ w) ◇ x) ◇ z
equation 62336 := (x ◇ y) ◇ z = ((y ◇ w) ◇ x) ◇ w
equation 62337 := (x ◇ y) ◇ z = ((y ◇ w) ◇ x) ◇ u
equation 62338 := (x ◇ y) ◇ z = ((y ◇ w) ◇ y) ◇ x
equation 62339 := (x ◇ y) ◇ z = ((y ◇ w) ◇ y) ◇ y
equation 62340 := (x ◇ y) ◇ z = ((y ◇ w) ◇ y) ◇ z
equation 62341 := (x ◇ y) ◇ z = ((y ◇ w) ◇ y) ◇ w
equation 62342 := (x ◇ y) ◇ z = ((y ◇ w) ◇ y) ◇ u
equation 62343 := (x ◇ y) ◇ z = ((y ◇ w) ◇ z) ◇ x
equation 62344 := (x ◇ y) ◇ z = ((y ◇ w) ◇ z) ◇ y
equation 62345 := (x ◇ y) ◇ z = ((y ◇ w) ◇ z) ◇ z
equation 62346 := (x ◇ y) ◇ z = ((y ◇ w) ◇ z) ◇ w
equation 62347 := (x ◇ y) ◇ z = ((y ◇ w) ◇ z) ◇ u
equation 62348 := (x ◇ y) ◇ z = ((y ◇ w) ◇ w) ◇ x
equation 62349 := (x ◇ y) ◇ z = ((y ◇ w) ◇ w) ◇ y
equation 62350 := (x ◇ y) ◇ z = ((y ◇ w) ◇ w) ◇ z
equation 62351 := (x ◇ y) ◇ z = ((y ◇ w) ◇ w) ◇ w
equation 62352 := (x ◇ y) ◇ z = ((y ◇ w) ◇ w) ◇ u
equation 62353 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ x
equation 62354 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ y
equation 62355 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ z
equation 62356 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ w
equation 62357 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ u
equation 62358 := (x ◇ y) ◇ z = ((y ◇ w) ◇ u) ◇ v
equation 62359 := (x ◇ y) ◇ z = ((z ◇ x) ◇ x) ◇ x
equation 62360 := (x ◇ y) ◇ z = ((z ◇ x) ◇ x) ◇ y
equation 62361 := (x ◇ y) ◇ z = ((z ◇ x) ◇ x) ◇ z
equation 62362 := (x ◇ y) ◇ z = ((z ◇ x) ◇ x) ◇ w
equation 62363 := (x ◇ y) ◇ z = ((z ◇ x) ◇ y) ◇ x
equation 62364 := (x ◇ y) ◇ z = ((z ◇ x) ◇ y) ◇ y
equation 62365 := (x ◇ y) ◇ z = ((z ◇ x) ◇ y) ◇ z
equation 62366 := (x ◇ y) ◇ z = ((z ◇ x) ◇ y) ◇ w
equation 62367 := (x ◇ y) ◇ z = ((z ◇ x) ◇ z) ◇ x
equation 62368 := (x ◇ y) ◇ z = ((z ◇ x) ◇ z) ◇ y
equation 62369 := (x ◇ y) ◇ z = ((z ◇ x) ◇ z) ◇ z
equation 62370 := (x ◇ y) ◇ z = ((z ◇ x) ◇ z) ◇ w
equation 62371 := (x ◇ y) ◇ z = ((z ◇ x) ◇ w) ◇ x
equation 62372 := (x ◇ y) ◇ z = ((z ◇ x) ◇ w) ◇ y
equation 62373 := (x ◇ y) ◇ z = ((z ◇ x) ◇ w) ◇ z
equation 62374 := (x ◇ y) ◇ z = ((z ◇ x) ◇ w) ◇ w
equation 62375 := (x ◇ y) ◇ z = ((z ◇ x) ◇ w) ◇ u
equation 62376 := (x ◇ y) ◇ z = ((z ◇ y) ◇ x) ◇ x
equation 62377 := (x ◇ y) ◇ z = ((z ◇ y) ◇ x) ◇ y
equation 62378 := (x ◇ y) ◇ z = ((z ◇ y) ◇ x) ◇ z
equation 62379 := (x ◇ y) ◇ z = ((z ◇ y) ◇ x) ◇ w
equation 62380 := (x ◇ y) ◇ z = ((z ◇ y) ◇ y) ◇ x
equation 62381 := (x ◇ y) ◇ z = ((z ◇ y) ◇ y) ◇ y
equation 62382 := (x ◇ y) ◇ z = ((z ◇ y) ◇ y) ◇ z
equation 62383 := (x ◇ y) ◇ z = ((z ◇ y) ◇ y) ◇ w
equation 62384 := (x ◇ y) ◇ z = ((z ◇ y) ◇ z) ◇ x
equation 62385 := (x ◇ y) ◇ z = ((z ◇ y) ◇ z) ◇ y
equation 62386 := (x ◇ y) ◇ z = ((z ◇ y) ◇ z) ◇ z
equation 62387 := (x ◇ y) ◇ z = ((z ◇ y) ◇ z) ◇ w
equation 62388 := (x ◇ y) ◇ z = ((z ◇ y) ◇ w) ◇ x
equation 62389 := (x ◇ y) ◇ z = ((z ◇ y) ◇ w) ◇ y
equation 62390 := (x ◇ y) ◇ z = ((z ◇ y) ◇ w) ◇ z
equation 62391 := (x ◇ y) ◇ z = ((z ◇ y) ◇ w) ◇ w
equation 62392 := (x ◇ y) ◇ z = ((z ◇ y) ◇ w) ◇ u
equation 62393 := (x ◇ y) ◇ z = ((z ◇ z) ◇ x) ◇ x
equation 62394 := (x ◇ y) ◇ z = ((z ◇ z) ◇ x) ◇ y
equation 62395 := (x ◇ y) ◇ z = ((z ◇ z) ◇ x) ◇ z
equation 62396 := (x ◇ y) ◇ z = ((z ◇ z) ◇ x) ◇ w
equation 62397 := (x ◇ y) ◇ z = ((z ◇ z) ◇ y) ◇ x
equation 62398 := (x ◇ y) ◇ z = ((z ◇ z) ◇ y) ◇ y
equation 62399 := (x ◇ y) ◇ z = ((z ◇ z) ◇ y) ◇ z
equation 62400 := (x ◇ y) ◇ z = ((z ◇ z) ◇ y) ◇ w
equation 62401 := (x ◇ y) ◇ z = ((z ◇ z) ◇ z) ◇ x
equation 62402 := (x ◇ y) ◇ z = ((z ◇ z) ◇ z) ◇ y
equation 62403 := (x ◇ y) ◇ z = ((z ◇ z) ◇ z) ◇ z
equation 62404 := (x ◇ y) ◇ z = ((z ◇ z) ◇ z) ◇ w
equation 62405 := (x ◇ y) ◇ z = ((z ◇ z) ◇ w) ◇ x
equation 62406 := (x ◇ y) ◇ z = ((z ◇ z) ◇ w) ◇ y
equation 62407 := (x ◇ y) ◇ z = ((z ◇ z) ◇ w) ◇ z
equation 62408 := (x ◇ y) ◇ z = ((z ◇ z) ◇ w) ◇ w
equation 62409 := (x ◇ y) ◇ z = ((z ◇ z) ◇ w) ◇ u
equation 62410 := (x ◇ y) ◇ z = ((z ◇ w) ◇ x) ◇ x
equation 62411 := (x ◇ y) ◇ z = ((z ◇ w) ◇ x) ◇ y
equation 62412 := (x ◇ y) ◇ z = ((z ◇ w) ◇ x) ◇ z
equation 62413 := (x ◇ y) ◇ z = ((z ◇ w) ◇ x) ◇ w
equation 62414 := (x ◇ y) ◇ z = ((z ◇ w) ◇ x) ◇ u
equation 62415 := (x ◇ y) ◇ z = ((z ◇ w) ◇ y) ◇ x
equation 62416 := (x ◇ y) ◇ z = ((z ◇ w) ◇ y) ◇ y
equation 62417 := (x ◇ y) ◇ z = ((z ◇ w) ◇ y) ◇ z
equation 62418 := (x ◇ y) ◇ z = ((z ◇ w) ◇ y) ◇ w
equation 62419 := (x ◇ y) ◇ z = ((z ◇ w) ◇ y) ◇ u
equation 62420 := (x ◇ y) ◇ z = ((z ◇ w) ◇ z) ◇ x
equation 62421 := (x ◇ y) ◇ z = ((z ◇ w) ◇ z) ◇ y
equation 62422 := (x ◇ y) ◇ z = ((z ◇ w) ◇ z) ◇ z
equation 62423 := (x ◇ y) ◇ z = ((z ◇ w) ◇ z) ◇ w
equation 62424 := (x ◇ y) ◇ z = ((z ◇ w) ◇ z) ◇ u
equation 62425 := (x ◇ y) ◇ z = ((z ◇ w) ◇ w) ◇ x
equation 62426 := (x ◇ y) ◇ z = ((z ◇ w) ◇ w) ◇ y
equation 62427 := (x ◇ y) ◇ z = ((z ◇ w) ◇ w) ◇ z
equation 62428 := (x ◇ y) ◇ z = ((z ◇ w) ◇ w) ◇ w
equation 62429 := (x ◇ y) ◇ z = ((z ◇ w) ◇ w) ◇ u
equation 62430 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ x
equation 62431 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ y
equation 62432 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ z
equation 62433 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ w
equation 62434 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ u
equation 62435 := (x ◇ y) ◇ z = ((z ◇ w) ◇ u) ◇ v
equation 62436 := (x ◇ y) ◇ z = ((w ◇ x) ◇ x) ◇ x
equation 62437 := (x ◇ y) ◇ z = ((w ◇ x) ◇ x) ◇ y
equation 62438 := (x ◇ y) ◇ z = ((w ◇ x) ◇ x) ◇ z
equation 62439 := (x ◇ y) ◇ z = ((w ◇ x) ◇ x) ◇ w
equation 62440 := (x ◇ y) ◇ z = ((w ◇ x) ◇ x) ◇ u
equation 62441 := (x ◇ y) ◇ z = ((w ◇ x) ◇ y) ◇ x
equation 62442 := (x ◇ y) ◇ z = ((w ◇ x) ◇ y) ◇ y
equation 62443 := (x ◇ y) ◇ z = ((w ◇ x) ◇ y) ◇ z
equation 62444 := (x ◇ y) ◇ z = ((w ◇ x) ◇ y) ◇ w
equation 62445 := (x ◇ y) ◇ z = ((w ◇ x) ◇ y) ◇ u
equation 62446 := (x ◇ y) ◇ z = ((w ◇ x) ◇ z) ◇ x
equation 62447 := (x ◇ y) ◇ z = ((w ◇ x) ◇ z) ◇ y
equation 62448 := (x ◇ y) ◇ z = ((w ◇ x) ◇ z) ◇ z
equation 62449 := (x ◇ y) ◇ z = ((w ◇ x) ◇ z) ◇ w
equation 62450 := (x ◇ y) ◇ z = ((w ◇ x) ◇ z) ◇ u
equation 62451 := (x ◇ y) ◇ z = ((w ◇ x) ◇ w) ◇ x
equation 62452 := (x ◇ y) ◇ z = ((w ◇ x) ◇ w) ◇ y
equation 62453 := (x ◇ y) ◇ z = ((w ◇ x) ◇ w) ◇ z
equation 62454 := (x ◇ y) ◇ z = ((w ◇ x) ◇ w) ◇ w
equation 62455 := (x ◇ y) ◇ z = ((w ◇ x) ◇ w) ◇ u
equation 62456 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ x
equation 62457 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ y
equation 62458 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ z
equation 62459 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ w
equation 62460 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ u
equation 62461 := (x ◇ y) ◇ z = ((w ◇ x) ◇ u) ◇ v
equation 62462 := (x ◇ y) ◇ z = ((w ◇ y) ◇ x) ◇ x
equation 62463 := (x ◇ y) ◇ z = ((w ◇ y) ◇ x) ◇ y
equation 62464 := (x ◇ y) ◇ z = ((w ◇ y) ◇ x) ◇ z
equation 62465 := (x ◇ y) ◇ z = ((w ◇ y) ◇ x) ◇ w
equation 62466 := (x ◇ y) ◇ z = ((w ◇ y) ◇ x) ◇ u
equation 62467 := (x ◇ y) ◇ z = ((w ◇ y) ◇ y) ◇ x
equation 62468 := (x ◇ y) ◇ z = ((w ◇ y) ◇ y) ◇ y
equation 62469 := (x ◇ y) ◇ z = ((w ◇ y) ◇ y) ◇ z
equation 62470 := (x ◇ y) ◇ z = ((w ◇ y) ◇ y) ◇ w
equation 62471 := (x ◇ y) ◇ z = ((w ◇ y) ◇ y) ◇ u
equation 62472 := (x ◇ y) ◇ z = ((w ◇ y) ◇ z) ◇ x
equation 62473 := (x ◇ y) ◇ z = ((w ◇ y) ◇ z) ◇ y
equation 62474 := (x ◇ y) ◇ z = ((w ◇ y) ◇ z) ◇ z
equation 62475 := (x ◇ y) ◇ z = ((w ◇ y) ◇ z) ◇ w
equation 62476 := (x ◇ y) ◇ z = ((w ◇ y) ◇ z) ◇ u
equation 62477 := (x ◇ y) ◇ z = ((w ◇ y) ◇ w) ◇ x
equation 62478 := (x ◇ y) ◇ z = ((w ◇ y) ◇ w) ◇ y
equation 62479 := (x ◇ y) ◇ z = ((w ◇ y) ◇ w) ◇ z
equation 62480 := (x ◇ y) ◇ z = ((w ◇ y) ◇ w) ◇ w
equation 62481 := (x ◇ y) ◇ z = ((w ◇ y) ◇ w) ◇ u
equation 62482 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ x
equation 62483 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ y
equation 62484 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ z
equation 62485 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ w
equation 62486 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ u
equation 62487 := (x ◇ y) ◇ z = ((w ◇ y) ◇ u) ◇ v
equation 62488 := (x ◇ y) ◇ z = ((w ◇ z) ◇ x) ◇ x
equation 62489 := (x ◇ y) ◇ z = ((w ◇ z) ◇ x) ◇ y
equation 62490 := (x ◇ y) ◇ z = ((w ◇ z) ◇ x) ◇ z
equation 62491 := (x ◇ y) ◇ z = ((w ◇ z) ◇ x) ◇ w
equation 62492 := (x ◇ y) ◇ z = ((w ◇ z) ◇ x) ◇ u
equation 62493 := (x ◇ y) ◇ z = ((w ◇ z) ◇ y) ◇ x
equation 62494 := (x ◇ y) ◇ z = ((w ◇ z) ◇ y) ◇ y
equation 62495 := (x ◇ y) ◇ z = ((w ◇ z) ◇ y) ◇ z
equation 62496 := (x ◇ y) ◇ z = ((w ◇ z) ◇ y) ◇ w
equation 62497 := (x ◇ y) ◇ z = ((w ◇ z) ◇ y) ◇ u
equation 62498 := (x ◇ y) ◇ z = ((w ◇ z) ◇ z) ◇ x
equation 62499 := (x ◇ y) ◇ z = ((w ◇ z) ◇ z) ◇ y
equation 62500 := (x ◇ y) ◇ z = ((w ◇ z) ◇ z) ◇ z
equation 62501 := (x ◇ y) ◇ z = ((w ◇ z) ◇ z) ◇ w
equation 62502 := (x ◇ y) ◇ z = ((w ◇ z) ◇ z) ◇ u
equation 62503 := (x ◇ y) ◇ z = ((w ◇ z) ◇ w) ◇ x
equation 62504 := (x ◇ y) ◇ z = ((w ◇ z) ◇ w) ◇ y
equation 62505 := (x ◇ y) ◇ z = ((w ◇ z) ◇ w) ◇ z
equation 62506 := (x ◇ y) ◇ z = ((w ◇ z) ◇ w) ◇ w
equation 62507 := (x ◇ y) ◇ z = ((w ◇ z) ◇ w) ◇ u
equation 62508 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ x
equation 62509 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ y
equation 62510 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ z
equation 62511 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ w
equation 62512 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ u
equation 62513 := (x ◇ y) ◇ z = ((w ◇ z) ◇ u) ◇ v
equation 62514 := (x ◇ y) ◇ z = ((w ◇ w) ◇ x) ◇ x
equation 62515 := (x ◇ y) ◇ z = ((w ◇ w) ◇ x) ◇ y
equation 62516 := (x ◇ y) ◇ z = ((w ◇ w) ◇ x) ◇ z
equation 62517 := (x ◇ y) ◇ z = ((w ◇ w) ◇ x) ◇ w
equation 62518 := (x ◇ y) ◇ z = ((w ◇ w) ◇ x) ◇ u
equation 62519 := (x ◇ y) ◇ z = ((w ◇ w) ◇ y) ◇ x
equation 62520 := (x ◇ y) ◇ z = ((w ◇ w) ◇ y) ◇ y
equation 62521 := (x ◇ y) ◇ z = ((w ◇ w) ◇ y) ◇ z
equation 62522 := (x ◇ y) ◇ z = ((w ◇ w) ◇ y) ◇ w
equation 62523 := (x ◇ y) ◇ z = ((w ◇ w) ◇ y) ◇ u
equation 62524 := (x ◇ y) ◇ z = ((w ◇ w) ◇ z) ◇ x
equation 62525 := (x ◇ y) ◇ z = ((w ◇ w) ◇ z) ◇ y
equation 62526 := (x ◇ y) ◇ z = ((w ◇ w) ◇ z) ◇ z
equation 62527 := (x ◇ y) ◇ z = ((w ◇ w) ◇ z) ◇ w
equation 62528 := (x ◇ y) ◇ z = ((w ◇ w) ◇ z) ◇ u
equation 62529 := (x ◇ y) ◇ z = ((w ◇ w) ◇ w) ◇ x
equation 62530 := (x ◇ y) ◇ z = ((w ◇ w) ◇ w) ◇ y
equation 62531 := (x ◇ y) ◇ z = ((w ◇ w) ◇ w) ◇ z
equation 62532 := (x ◇ y) ◇ z = ((w ◇ w) ◇ w) ◇ w
equation 62533 := (x ◇ y) ◇ z = ((w ◇ w) ◇ w) ◇ u
equation 62534 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ x
equation 62535 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ y
equation 62536 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ z
equation 62537 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ w
equation 62538 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ u
equation 62539 := (x ◇ y) ◇ z = ((w ◇ w) ◇ u) ◇ v
equation 62540 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ x
equation 62541 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ y
equation 62542 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ z
equation 62543 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ w
equation 62544 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ u
equation 62545 := (x ◇ y) ◇ z = ((w ◇ u) ◇ x) ◇ v
equation 62546 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ x
equation 62547 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ y
equation 62548 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ z
equation 62549 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ w
equation 62550 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ u
equation 62551 := (x ◇ y) ◇ z = ((w ◇ u) ◇ y) ◇ v
equation 62552 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ x
equation 62553 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ y
equation 62554 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ z
equation 62555 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ w
equation 62556 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ u
equation 62557 := (x ◇ y) ◇ z = ((w ◇ u) ◇ z) ◇ v
equation 62558 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ x
equation 62559 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ y
equation 62560 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ z
equation 62561 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ w
equation 62562 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ u
equation 62563 := (x ◇ y) ◇ z = ((w ◇ u) ◇ w) ◇ v
equation 62564 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ x
equation 62565 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ y
equation 62566 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ z
equation 62567 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ w
equation 62568 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ u
equation 62569 := (x ◇ y) ◇ z = ((w ◇ u) ◇ u) ◇ v
equation 62570 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ x
equation 62571 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ y
equation 62572 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ z
equation 62573 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ w
equation 62574 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ u
equation 62575 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ v
equation 62576 := (x ◇ y) ◇ z = ((w ◇ u) ◇ v) ◇ r
