import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 41000-41999 -/

equation 41000 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ x
equation 41001 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ y
equation 41002 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ z
equation 41003 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ w
equation 41004 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ u
equation 41005 := x = ((((y ◇ x) ◇ z) ◇ w) ◇ u) ◇ v
equation 41006 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ x) ◇ x
equation 41007 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ x) ◇ y
equation 41008 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ x) ◇ z
equation 41009 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ y) ◇ x
equation 41010 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ y) ◇ y
equation 41011 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ y) ◇ z
equation 41012 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ z) ◇ x
equation 41013 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ z) ◇ y
equation 41014 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ z) ◇ z
equation 41015 := x = ((((y ◇ y) ◇ x) ◇ x) ◇ z) ◇ w
equation 41016 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ x) ◇ x
equation 41017 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ x) ◇ y
equation 41018 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ x) ◇ z
equation 41019 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ y) ◇ x
equation 41020 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ y) ◇ y
equation 41021 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ y) ◇ z
equation 41022 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ z) ◇ x
equation 41023 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ z) ◇ y
equation 41024 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ z) ◇ z
equation 41025 := x = ((((y ◇ y) ◇ x) ◇ y) ◇ z) ◇ w
equation 41026 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ x) ◇ x
equation 41027 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ x) ◇ y
equation 41028 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ x) ◇ z
equation 41029 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ x) ◇ w
equation 41030 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ y) ◇ x
equation 41031 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ y) ◇ y
equation 41032 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ y) ◇ z
equation 41033 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ y) ◇ w
equation 41034 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ z) ◇ x
equation 41035 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ z) ◇ y
equation 41036 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ z) ◇ z
equation 41037 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ z) ◇ w
equation 41038 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ w) ◇ x
equation 41039 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ w) ◇ y
equation 41040 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ w) ◇ z
equation 41041 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ w) ◇ w
equation 41042 := x = ((((y ◇ y) ◇ x) ◇ z) ◇ w) ◇ u
equation 41043 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ x) ◇ x
equation 41044 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ x) ◇ y
equation 41045 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ x) ◇ z
equation 41046 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ y) ◇ x
equation 41047 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ y) ◇ y
equation 41048 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ y) ◇ z
equation 41049 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ z) ◇ x
equation 41050 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ z) ◇ y
equation 41051 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ z) ◇ z
equation 41052 := x = ((((y ◇ y) ◇ y) ◇ x) ◇ z) ◇ w
equation 41053 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ x) ◇ x
equation 41054 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ x) ◇ y
equation 41055 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ x) ◇ z
equation 41056 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ y) ◇ x
equation 41057 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ y) ◇ y
equation 41058 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ y) ◇ z
equation 41059 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ z) ◇ x
equation 41060 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ z) ◇ y
equation 41061 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ z) ◇ z
equation 41062 := x = ((((y ◇ y) ◇ y) ◇ y) ◇ z) ◇ w
equation 41063 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ x) ◇ x
equation 41064 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ x) ◇ y
equation 41065 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ x) ◇ z
equation 41066 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ x) ◇ w
equation 41067 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ y) ◇ x
equation 41068 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ y) ◇ y
equation 41069 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ y) ◇ z
equation 41070 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ y) ◇ w
equation 41071 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ z) ◇ x
equation 41072 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ z) ◇ y
equation 41073 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ z) ◇ z
equation 41074 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ z) ◇ w
equation 41075 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ w) ◇ x
equation 41076 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ w) ◇ y
equation 41077 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ w) ◇ z
equation 41078 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ w) ◇ w
equation 41079 := x = ((((y ◇ y) ◇ y) ◇ z) ◇ w) ◇ u
equation 41080 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ x) ◇ x
equation 41081 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ x) ◇ y
equation 41082 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ x) ◇ z
equation 41083 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ x) ◇ w
equation 41084 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ y) ◇ x
equation 41085 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ y) ◇ y
equation 41086 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ y) ◇ z
equation 41087 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ y) ◇ w
equation 41088 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ z) ◇ x
equation 41089 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ z) ◇ y
equation 41090 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ z) ◇ z
equation 41091 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ z) ◇ w
equation 41092 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ w) ◇ x
equation 41093 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ w) ◇ y
equation 41094 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ w) ◇ z
equation 41095 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ w) ◇ w
equation 41096 := x = ((((y ◇ y) ◇ z) ◇ x) ◇ w) ◇ u
equation 41097 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ x) ◇ x
equation 41098 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ x) ◇ y
equation 41099 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ x) ◇ z
equation 41100 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ x) ◇ w
equation 41101 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ y) ◇ x
equation 41102 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ y) ◇ y
equation 41103 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ y) ◇ z
equation 41104 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ y) ◇ w
equation 41105 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ z) ◇ x
equation 41106 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ z) ◇ y
equation 41107 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ z) ◇ z
equation 41108 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ z) ◇ w
equation 41109 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ w) ◇ x
equation 41110 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ w) ◇ y
equation 41111 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ w) ◇ z
equation 41112 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ w) ◇ w
equation 41113 := x = ((((y ◇ y) ◇ z) ◇ y) ◇ w) ◇ u
equation 41114 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ x) ◇ x
equation 41115 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ x) ◇ y
equation 41116 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ x) ◇ z
equation 41117 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ x) ◇ w
equation 41118 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ y) ◇ x
equation 41119 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ y) ◇ y
equation 41120 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ y) ◇ z
equation 41121 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ y) ◇ w
equation 41122 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ z) ◇ x
equation 41123 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ z) ◇ y
equation 41124 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ z) ◇ z
equation 41125 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ z) ◇ w
equation 41126 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ w) ◇ x
equation 41127 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ w) ◇ y
equation 41128 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ w) ◇ z
equation 41129 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ w) ◇ w
equation 41130 := x = ((((y ◇ y) ◇ z) ◇ z) ◇ w) ◇ u
equation 41131 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ x) ◇ x
equation 41132 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ x) ◇ y
equation 41133 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ x) ◇ z
equation 41134 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ x) ◇ w
equation 41135 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ x) ◇ u
equation 41136 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ y) ◇ x
equation 41137 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ y) ◇ y
equation 41138 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ y) ◇ z
equation 41139 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ y) ◇ w
equation 41140 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ y) ◇ u
equation 41141 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ z) ◇ x
equation 41142 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ z) ◇ y
equation 41143 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ z) ◇ z
equation 41144 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ z) ◇ w
equation 41145 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ z) ◇ u
equation 41146 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ w) ◇ x
equation 41147 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ w) ◇ y
equation 41148 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ w) ◇ z
equation 41149 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ w) ◇ w
equation 41150 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ w) ◇ u
equation 41151 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ x
equation 41152 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ y
equation 41153 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ z
equation 41154 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ w
equation 41155 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ u
equation 41156 := x = ((((y ◇ y) ◇ z) ◇ w) ◇ u) ◇ v
equation 41157 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ x) ◇ x
equation 41158 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ x) ◇ y
equation 41159 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ x) ◇ z
equation 41160 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ x) ◇ w
equation 41161 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ y) ◇ x
equation 41162 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ y) ◇ y
equation 41163 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ y) ◇ z
equation 41164 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ y) ◇ w
equation 41165 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ z) ◇ x
equation 41166 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ z) ◇ y
equation 41167 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ z) ◇ z
equation 41168 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ z) ◇ w
equation 41169 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ w) ◇ x
equation 41170 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ w) ◇ y
equation 41171 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ w) ◇ z
equation 41172 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ w) ◇ w
equation 41173 := x = ((((y ◇ z) ◇ x) ◇ x) ◇ w) ◇ u
equation 41174 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ x) ◇ x
equation 41175 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ x) ◇ y
equation 41176 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ x) ◇ z
equation 41177 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ x) ◇ w
equation 41178 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ y) ◇ x
equation 41179 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ y) ◇ y
equation 41180 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ y) ◇ z
equation 41181 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ y) ◇ w
equation 41182 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ z) ◇ x
equation 41183 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ z) ◇ y
equation 41184 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ z) ◇ z
equation 41185 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ z) ◇ w
equation 41186 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ w) ◇ x
equation 41187 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ w) ◇ y
equation 41188 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ w) ◇ z
equation 41189 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ w) ◇ w
equation 41190 := x = ((((y ◇ z) ◇ x) ◇ y) ◇ w) ◇ u
equation 41191 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ x) ◇ x
equation 41192 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ x) ◇ y
equation 41193 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ x) ◇ z
equation 41194 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ x) ◇ w
equation 41195 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ y) ◇ x
equation 41196 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ y) ◇ y
equation 41197 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ y) ◇ z
equation 41198 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ y) ◇ w
equation 41199 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ z) ◇ x
equation 41200 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ z) ◇ y
equation 41201 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ z) ◇ z
equation 41202 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ z) ◇ w
equation 41203 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ w) ◇ x
equation 41204 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ w) ◇ y
equation 41205 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ w) ◇ z
equation 41206 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ w) ◇ w
equation 41207 := x = ((((y ◇ z) ◇ x) ◇ z) ◇ w) ◇ u
equation 41208 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ x) ◇ x
equation 41209 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ x) ◇ y
equation 41210 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ x) ◇ z
equation 41211 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ x) ◇ w
equation 41212 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ x) ◇ u
equation 41213 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ y) ◇ x
equation 41214 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ y) ◇ y
equation 41215 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ y) ◇ z
equation 41216 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ y) ◇ w
equation 41217 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ y) ◇ u
equation 41218 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ z) ◇ x
equation 41219 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ z) ◇ y
equation 41220 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ z) ◇ z
equation 41221 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ z) ◇ w
equation 41222 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ z) ◇ u
equation 41223 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ w) ◇ x
equation 41224 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ w) ◇ y
equation 41225 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ w) ◇ z
equation 41226 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ w) ◇ w
equation 41227 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ w) ◇ u
equation 41228 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ x
equation 41229 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ y
equation 41230 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ z
equation 41231 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ w
equation 41232 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ u
equation 41233 := x = ((((y ◇ z) ◇ x) ◇ w) ◇ u) ◇ v
equation 41234 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ x) ◇ x
equation 41235 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ x) ◇ y
equation 41236 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ x) ◇ z
equation 41237 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ x) ◇ w
equation 41238 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ y) ◇ x
equation 41239 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ y) ◇ y
equation 41240 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ y) ◇ z
equation 41241 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ y) ◇ w
equation 41242 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ z) ◇ x
equation 41243 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ z) ◇ y
equation 41244 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ z) ◇ z
equation 41245 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ z) ◇ w
equation 41246 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ w) ◇ x
equation 41247 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ w) ◇ y
equation 41248 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ w) ◇ z
equation 41249 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ w) ◇ w
equation 41250 := x = ((((y ◇ z) ◇ y) ◇ x) ◇ w) ◇ u
equation 41251 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ x) ◇ x
equation 41252 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ x) ◇ y
equation 41253 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ x) ◇ z
equation 41254 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ x) ◇ w
equation 41255 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ y) ◇ x
equation 41256 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ y) ◇ y
equation 41257 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ y) ◇ z
equation 41258 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ y) ◇ w
equation 41259 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ z) ◇ x
equation 41260 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ z) ◇ y
equation 41261 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ z) ◇ z
equation 41262 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ z) ◇ w
equation 41263 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ w) ◇ x
equation 41264 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ w) ◇ y
equation 41265 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ w) ◇ z
equation 41266 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ w) ◇ w
equation 41267 := x = ((((y ◇ z) ◇ y) ◇ y) ◇ w) ◇ u
equation 41268 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ x) ◇ x
equation 41269 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ x) ◇ y
equation 41270 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ x) ◇ z
equation 41271 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ x) ◇ w
equation 41272 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ y) ◇ x
equation 41273 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ y) ◇ y
equation 41274 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ y) ◇ z
equation 41275 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ y) ◇ w
equation 41276 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ z) ◇ x
equation 41277 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ z) ◇ y
equation 41278 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ z) ◇ z
equation 41279 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ z) ◇ w
equation 41280 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ w) ◇ x
equation 41281 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ w) ◇ y
equation 41282 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ w) ◇ z
equation 41283 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ w) ◇ w
equation 41284 := x = ((((y ◇ z) ◇ y) ◇ z) ◇ w) ◇ u
equation 41285 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ x) ◇ x
equation 41286 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ x) ◇ y
equation 41287 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ x) ◇ z
equation 41288 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ x) ◇ w
equation 41289 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ x) ◇ u
equation 41290 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ y) ◇ x
equation 41291 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ y) ◇ y
equation 41292 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ y) ◇ z
equation 41293 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ y) ◇ w
equation 41294 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ y) ◇ u
equation 41295 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ z) ◇ x
equation 41296 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ z) ◇ y
equation 41297 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ z) ◇ z
equation 41298 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ z) ◇ w
equation 41299 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ z) ◇ u
equation 41300 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ w) ◇ x
equation 41301 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ w) ◇ y
equation 41302 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ w) ◇ z
equation 41303 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ w) ◇ w
equation 41304 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ w) ◇ u
equation 41305 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ x
equation 41306 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ y
equation 41307 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ z
equation 41308 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ w
equation 41309 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ u
equation 41310 := x = ((((y ◇ z) ◇ y) ◇ w) ◇ u) ◇ v
equation 41311 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ x) ◇ x
equation 41312 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ x) ◇ y
equation 41313 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ x) ◇ z
equation 41314 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ x) ◇ w
equation 41315 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ y) ◇ x
equation 41316 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ y) ◇ y
equation 41317 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ y) ◇ z
equation 41318 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ y) ◇ w
equation 41319 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ z) ◇ x
equation 41320 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ z) ◇ y
equation 41321 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ z) ◇ z
equation 41322 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ z) ◇ w
equation 41323 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ w) ◇ x
equation 41324 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ w) ◇ y
equation 41325 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ w) ◇ z
equation 41326 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ w) ◇ w
equation 41327 := x = ((((y ◇ z) ◇ z) ◇ x) ◇ w) ◇ u
equation 41328 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ x) ◇ x
equation 41329 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ x) ◇ y
equation 41330 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ x) ◇ z
equation 41331 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ x) ◇ w
equation 41332 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ y) ◇ x
equation 41333 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ y) ◇ y
equation 41334 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ y) ◇ z
equation 41335 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ y) ◇ w
equation 41336 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ z) ◇ x
equation 41337 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ z) ◇ y
equation 41338 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ z) ◇ z
equation 41339 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ z) ◇ w
equation 41340 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ w) ◇ x
equation 41341 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ w) ◇ y
equation 41342 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ w) ◇ z
equation 41343 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ w) ◇ w
equation 41344 := x = ((((y ◇ z) ◇ z) ◇ y) ◇ w) ◇ u
equation 41345 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ x) ◇ x
equation 41346 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ x) ◇ y
equation 41347 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ x) ◇ z
equation 41348 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ x) ◇ w
equation 41349 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ y) ◇ x
equation 41350 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ y) ◇ y
equation 41351 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ y) ◇ z
equation 41352 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ y) ◇ w
equation 41353 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ z) ◇ x
equation 41354 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ z) ◇ y
equation 41355 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ z) ◇ z
equation 41356 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ z) ◇ w
equation 41357 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ w) ◇ x
equation 41358 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ w) ◇ y
equation 41359 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ w) ◇ z
equation 41360 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ w) ◇ w
equation 41361 := x = ((((y ◇ z) ◇ z) ◇ z) ◇ w) ◇ u
equation 41362 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ x) ◇ x
equation 41363 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ x) ◇ y
equation 41364 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ x) ◇ z
equation 41365 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ x) ◇ w
equation 41366 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ x) ◇ u
equation 41367 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ y) ◇ x
equation 41368 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ y) ◇ y
equation 41369 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ y) ◇ z
equation 41370 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ y) ◇ w
equation 41371 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ y) ◇ u
equation 41372 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ z) ◇ x
equation 41373 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ z) ◇ y
equation 41374 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ z) ◇ z
equation 41375 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ z) ◇ w
equation 41376 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ z) ◇ u
equation 41377 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ w) ◇ x
equation 41378 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ w) ◇ y
equation 41379 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ w) ◇ z
equation 41380 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ w) ◇ w
equation 41381 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ w) ◇ u
equation 41382 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ x
equation 41383 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ y
equation 41384 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ z
equation 41385 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ w
equation 41386 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ u
equation 41387 := x = ((((y ◇ z) ◇ z) ◇ w) ◇ u) ◇ v
equation 41388 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ x) ◇ x
equation 41389 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ x) ◇ y
equation 41390 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ x) ◇ z
equation 41391 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ x) ◇ w
equation 41392 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ x) ◇ u
equation 41393 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ y) ◇ x
equation 41394 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ y) ◇ y
equation 41395 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ y) ◇ z
equation 41396 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ y) ◇ w
equation 41397 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ y) ◇ u
equation 41398 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ z) ◇ x
equation 41399 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ z) ◇ y
equation 41400 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ z) ◇ z
equation 41401 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ z) ◇ w
equation 41402 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ z) ◇ u
equation 41403 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ w) ◇ x
equation 41404 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ w) ◇ y
equation 41405 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ w) ◇ z
equation 41406 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ w) ◇ w
equation 41407 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ w) ◇ u
equation 41408 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ x
equation 41409 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ y
equation 41410 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ z
equation 41411 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ w
equation 41412 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ u
equation 41413 := x = ((((y ◇ z) ◇ w) ◇ x) ◇ u) ◇ v
equation 41414 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ x) ◇ x
equation 41415 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ x) ◇ y
equation 41416 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ x) ◇ z
equation 41417 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ x) ◇ w
equation 41418 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ x) ◇ u
equation 41419 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ y) ◇ x
equation 41420 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ y) ◇ y
equation 41421 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ y) ◇ z
equation 41422 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ y) ◇ w
equation 41423 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ y) ◇ u
equation 41424 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ z) ◇ x
equation 41425 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ z) ◇ y
equation 41426 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ z) ◇ z
equation 41427 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ z) ◇ w
equation 41428 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ z) ◇ u
equation 41429 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ w) ◇ x
equation 41430 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ w) ◇ y
equation 41431 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ w) ◇ z
equation 41432 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ w) ◇ w
equation 41433 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ w) ◇ u
equation 41434 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ x
equation 41435 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ y
equation 41436 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ z
equation 41437 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ w
equation 41438 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ u
equation 41439 := x = ((((y ◇ z) ◇ w) ◇ y) ◇ u) ◇ v
equation 41440 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ x) ◇ x
equation 41441 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ x) ◇ y
equation 41442 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ x) ◇ z
equation 41443 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ x) ◇ w
equation 41444 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ x) ◇ u
equation 41445 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ y) ◇ x
equation 41446 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ y) ◇ y
equation 41447 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ y) ◇ z
equation 41448 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ y) ◇ w
equation 41449 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ y) ◇ u
equation 41450 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ z) ◇ x
equation 41451 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ z) ◇ y
equation 41452 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ z) ◇ z
equation 41453 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ z) ◇ w
equation 41454 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ z) ◇ u
equation 41455 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ w) ◇ x
equation 41456 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ w) ◇ y
equation 41457 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ w) ◇ z
equation 41458 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ w) ◇ w
equation 41459 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ w) ◇ u
equation 41460 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ x
equation 41461 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ y
equation 41462 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ z
equation 41463 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ w
equation 41464 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ u
equation 41465 := x = ((((y ◇ z) ◇ w) ◇ z) ◇ u) ◇ v
equation 41466 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ x) ◇ x
equation 41467 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ x) ◇ y
equation 41468 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ x) ◇ z
equation 41469 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ x) ◇ w
equation 41470 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ x) ◇ u
equation 41471 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ y) ◇ x
equation 41472 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ y) ◇ y
equation 41473 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ y) ◇ z
equation 41474 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ y) ◇ w
equation 41475 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ y) ◇ u
equation 41476 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ z) ◇ x
equation 41477 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ z) ◇ y
equation 41478 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ z) ◇ z
equation 41479 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ z) ◇ w
equation 41480 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ z) ◇ u
equation 41481 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ w) ◇ x
equation 41482 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ w) ◇ y
equation 41483 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ w) ◇ z
equation 41484 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ w) ◇ w
equation 41485 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ w) ◇ u
equation 41486 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ x
equation 41487 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ y
equation 41488 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ z
equation 41489 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ w
equation 41490 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ u
equation 41491 := x = ((((y ◇ z) ◇ w) ◇ w) ◇ u) ◇ v
equation 41492 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ x
equation 41493 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ y
equation 41494 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ z
equation 41495 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ w
equation 41496 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ u
equation 41497 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ x) ◇ v
equation 41498 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ x
equation 41499 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ y
equation 41500 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ z
equation 41501 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ w
equation 41502 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ u
equation 41503 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ y) ◇ v
equation 41504 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ x
equation 41505 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ y
equation 41506 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ z
equation 41507 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ w
equation 41508 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ u
equation 41509 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ z) ◇ v
equation 41510 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ x
equation 41511 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ y
equation 41512 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ z
equation 41513 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ w
equation 41514 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ u
equation 41515 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ w) ◇ v
equation 41516 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ x
equation 41517 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ y
equation 41518 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ z
equation 41519 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ w
equation 41520 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ u
equation 41521 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ u) ◇ v
equation 41522 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ x
equation 41523 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ y
equation 41524 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ z
equation 41525 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ w
equation 41526 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ u
equation 41527 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ v
equation 41528 := x = ((((y ◇ z) ◇ w) ◇ u) ◇ v) ◇ r
equation 41529 := x ◇ x = x ◇ (x ◇ (x ◇ (x ◇ x)))
equation 41530 := x ◇ x = x ◇ (x ◇ (x ◇ (x ◇ y)))
equation 41531 := x ◇ x = x ◇ (x ◇ (x ◇ (y ◇ x)))
equation 41532 := x ◇ x = x ◇ (x ◇ (x ◇ (y ◇ y)))
equation 41533 := x ◇ x = x ◇ (x ◇ (x ◇ (y ◇ z)))
equation 41534 := x ◇ x = x ◇ (x ◇ (y ◇ (x ◇ x)))
equation 41535 := x ◇ x = x ◇ (x ◇ (y ◇ (x ◇ y)))
equation 41536 := x ◇ x = x ◇ (x ◇ (y ◇ (x ◇ z)))
equation 41537 := x ◇ x = x ◇ (x ◇ (y ◇ (y ◇ x)))
equation 41538 := x ◇ x = x ◇ (x ◇ (y ◇ (y ◇ y)))
equation 41539 := x ◇ x = x ◇ (x ◇ (y ◇ (y ◇ z)))
equation 41540 := x ◇ x = x ◇ (x ◇ (y ◇ (z ◇ x)))
equation 41541 := x ◇ x = x ◇ (x ◇ (y ◇ (z ◇ y)))
equation 41542 := x ◇ x = x ◇ (x ◇ (y ◇ (z ◇ z)))
equation 41543 := x ◇ x = x ◇ (x ◇ (y ◇ (z ◇ w)))
equation 41544 := x ◇ x = x ◇ (y ◇ (x ◇ (x ◇ x)))
equation 41545 := x ◇ x = x ◇ (y ◇ (x ◇ (x ◇ y)))
equation 41546 := x ◇ x = x ◇ (y ◇ (x ◇ (x ◇ z)))
equation 41547 := x ◇ x = x ◇ (y ◇ (x ◇ (y ◇ x)))
equation 41548 := x ◇ x = x ◇ (y ◇ (x ◇ (y ◇ y)))
equation 41549 := x ◇ x = x ◇ (y ◇ (x ◇ (y ◇ z)))
equation 41550 := x ◇ x = x ◇ (y ◇ (x ◇ (z ◇ x)))
equation 41551 := x ◇ x = x ◇ (y ◇ (x ◇ (z ◇ y)))
equation 41552 := x ◇ x = x ◇ (y ◇ (x ◇ (z ◇ z)))
equation 41553 := x ◇ x = x ◇ (y ◇ (x ◇ (z ◇ w)))
equation 41554 := x ◇ x = x ◇ (y ◇ (y ◇ (x ◇ x)))
equation 41555 := x ◇ x = x ◇ (y ◇ (y ◇ (x ◇ y)))
equation 41556 := x ◇ x = x ◇ (y ◇ (y ◇ (x ◇ z)))
equation 41557 := x ◇ x = x ◇ (y ◇ (y ◇ (y ◇ x)))
equation 41558 := x ◇ x = x ◇ (y ◇ (y ◇ (y ◇ y)))
equation 41559 := x ◇ x = x ◇ (y ◇ (y ◇ (y ◇ z)))
equation 41560 := x ◇ x = x ◇ (y ◇ (y ◇ (z ◇ x)))
equation 41561 := x ◇ x = x ◇ (y ◇ (y ◇ (z ◇ y)))
equation 41562 := x ◇ x = x ◇ (y ◇ (y ◇ (z ◇ z)))
equation 41563 := x ◇ x = x ◇ (y ◇ (y ◇ (z ◇ w)))
equation 41564 := x ◇ x = x ◇ (y ◇ (z ◇ (x ◇ x)))
equation 41565 := x ◇ x = x ◇ (y ◇ (z ◇ (x ◇ y)))
equation 41566 := x ◇ x = x ◇ (y ◇ (z ◇ (x ◇ z)))
equation 41567 := x ◇ x = x ◇ (y ◇ (z ◇ (x ◇ w)))
equation 41568 := x ◇ x = x ◇ (y ◇ (z ◇ (y ◇ x)))
equation 41569 := x ◇ x = x ◇ (y ◇ (z ◇ (y ◇ y)))
equation 41570 := x ◇ x = x ◇ (y ◇ (z ◇ (y ◇ z)))
equation 41571 := x ◇ x = x ◇ (y ◇ (z ◇ (y ◇ w)))
equation 41572 := x ◇ x = x ◇ (y ◇ (z ◇ (z ◇ x)))
equation 41573 := x ◇ x = x ◇ (y ◇ (z ◇ (z ◇ y)))
equation 41574 := x ◇ x = x ◇ (y ◇ (z ◇ (z ◇ z)))
equation 41575 := x ◇ x = x ◇ (y ◇ (z ◇ (z ◇ w)))
equation 41576 := x ◇ x = x ◇ (y ◇ (z ◇ (w ◇ x)))
equation 41577 := x ◇ x = x ◇ (y ◇ (z ◇ (w ◇ y)))
equation 41578 := x ◇ x = x ◇ (y ◇ (z ◇ (w ◇ z)))
equation 41579 := x ◇ x = x ◇ (y ◇ (z ◇ (w ◇ w)))
equation 41580 := x ◇ x = x ◇ (y ◇ (z ◇ (w ◇ u)))
equation 41581 := x ◇ x = y ◇ (x ◇ (x ◇ (x ◇ x)))
equation 41582 := x ◇ x = y ◇ (x ◇ (x ◇ (x ◇ y)))
equation 41583 := x ◇ x = y ◇ (x ◇ (x ◇ (x ◇ z)))
equation 41584 := x ◇ x = y ◇ (x ◇ (x ◇ (y ◇ x)))
equation 41585 := x ◇ x = y ◇ (x ◇ (x ◇ (y ◇ y)))
equation 41586 := x ◇ x = y ◇ (x ◇ (x ◇ (y ◇ z)))
equation 41587 := x ◇ x = y ◇ (x ◇ (x ◇ (z ◇ x)))
equation 41588 := x ◇ x = y ◇ (x ◇ (x ◇ (z ◇ y)))
equation 41589 := x ◇ x = y ◇ (x ◇ (x ◇ (z ◇ z)))
equation 41590 := x ◇ x = y ◇ (x ◇ (x ◇ (z ◇ w)))
equation 41591 := x ◇ x = y ◇ (x ◇ (y ◇ (x ◇ x)))
equation 41592 := x ◇ x = y ◇ (x ◇ (y ◇ (x ◇ y)))
equation 41593 := x ◇ x = y ◇ (x ◇ (y ◇ (x ◇ z)))
equation 41594 := x ◇ x = y ◇ (x ◇ (y ◇ (y ◇ x)))
equation 41595 := x ◇ x = y ◇ (x ◇ (y ◇ (y ◇ y)))
equation 41596 := x ◇ x = y ◇ (x ◇ (y ◇ (y ◇ z)))
equation 41597 := x ◇ x = y ◇ (x ◇ (y ◇ (z ◇ x)))
equation 41598 := x ◇ x = y ◇ (x ◇ (y ◇ (z ◇ y)))
equation 41599 := x ◇ x = y ◇ (x ◇ (y ◇ (z ◇ z)))
equation 41600 := x ◇ x = y ◇ (x ◇ (y ◇ (z ◇ w)))
equation 41601 := x ◇ x = y ◇ (x ◇ (z ◇ (x ◇ x)))
equation 41602 := x ◇ x = y ◇ (x ◇ (z ◇ (x ◇ y)))
equation 41603 := x ◇ x = y ◇ (x ◇ (z ◇ (x ◇ z)))
equation 41604 := x ◇ x = y ◇ (x ◇ (z ◇ (x ◇ w)))
equation 41605 := x ◇ x = y ◇ (x ◇ (z ◇ (y ◇ x)))
equation 41606 := x ◇ x = y ◇ (x ◇ (z ◇ (y ◇ y)))
equation 41607 := x ◇ x = y ◇ (x ◇ (z ◇ (y ◇ z)))
equation 41608 := x ◇ x = y ◇ (x ◇ (z ◇ (y ◇ w)))
equation 41609 := x ◇ x = y ◇ (x ◇ (z ◇ (z ◇ x)))
equation 41610 := x ◇ x = y ◇ (x ◇ (z ◇ (z ◇ y)))
equation 41611 := x ◇ x = y ◇ (x ◇ (z ◇ (z ◇ z)))
equation 41612 := x ◇ x = y ◇ (x ◇ (z ◇ (z ◇ w)))
equation 41613 := x ◇ x = y ◇ (x ◇ (z ◇ (w ◇ x)))
equation 41614 := x ◇ x = y ◇ (x ◇ (z ◇ (w ◇ y)))
equation 41615 := x ◇ x = y ◇ (x ◇ (z ◇ (w ◇ z)))
equation 41616 := x ◇ x = y ◇ (x ◇ (z ◇ (w ◇ w)))
equation 41617 := x ◇ x = y ◇ (x ◇ (z ◇ (w ◇ u)))
equation 41618 := x ◇ x = y ◇ (y ◇ (x ◇ (x ◇ x)))
equation 41619 := x ◇ x = y ◇ (y ◇ (x ◇ (x ◇ y)))
equation 41620 := x ◇ x = y ◇ (y ◇ (x ◇ (x ◇ z)))
equation 41621 := x ◇ x = y ◇ (y ◇ (x ◇ (y ◇ x)))
equation 41622 := x ◇ x = y ◇ (y ◇ (x ◇ (y ◇ y)))
equation 41623 := x ◇ x = y ◇ (y ◇ (x ◇ (y ◇ z)))
equation 41624 := x ◇ x = y ◇ (y ◇ (x ◇ (z ◇ x)))
equation 41625 := x ◇ x = y ◇ (y ◇ (x ◇ (z ◇ y)))
equation 41626 := x ◇ x = y ◇ (y ◇ (x ◇ (z ◇ z)))
equation 41627 := x ◇ x = y ◇ (y ◇ (x ◇ (z ◇ w)))
equation 41628 := x ◇ x = y ◇ (y ◇ (y ◇ (x ◇ x)))
equation 41629 := x ◇ x = y ◇ (y ◇ (y ◇ (x ◇ y)))
equation 41630 := x ◇ x = y ◇ (y ◇ (y ◇ (x ◇ z)))
equation 41631 := x ◇ x = y ◇ (y ◇ (y ◇ (y ◇ x)))
equation 41632 := x ◇ x = y ◇ (y ◇ (y ◇ (y ◇ y)))
equation 41633 := x ◇ x = y ◇ (y ◇ (y ◇ (y ◇ z)))
equation 41634 := x ◇ x = y ◇ (y ◇ (y ◇ (z ◇ x)))
equation 41635 := x ◇ x = y ◇ (y ◇ (y ◇ (z ◇ y)))
equation 41636 := x ◇ x = y ◇ (y ◇ (y ◇ (z ◇ z)))
equation 41637 := x ◇ x = y ◇ (y ◇ (y ◇ (z ◇ w)))
equation 41638 := x ◇ x = y ◇ (y ◇ (z ◇ (x ◇ x)))
equation 41639 := x ◇ x = y ◇ (y ◇ (z ◇ (x ◇ y)))
equation 41640 := x ◇ x = y ◇ (y ◇ (z ◇ (x ◇ z)))
equation 41641 := x ◇ x = y ◇ (y ◇ (z ◇ (x ◇ w)))
equation 41642 := x ◇ x = y ◇ (y ◇ (z ◇ (y ◇ x)))
equation 41643 := x ◇ x = y ◇ (y ◇ (z ◇ (y ◇ y)))
equation 41644 := x ◇ x = y ◇ (y ◇ (z ◇ (y ◇ z)))
equation 41645 := x ◇ x = y ◇ (y ◇ (z ◇ (y ◇ w)))
equation 41646 := x ◇ x = y ◇ (y ◇ (z ◇ (z ◇ x)))
equation 41647 := x ◇ x = y ◇ (y ◇ (z ◇ (z ◇ y)))
equation 41648 := x ◇ x = y ◇ (y ◇ (z ◇ (z ◇ z)))
equation 41649 := x ◇ x = y ◇ (y ◇ (z ◇ (z ◇ w)))
equation 41650 := x ◇ x = y ◇ (y ◇ (z ◇ (w ◇ x)))
equation 41651 := x ◇ x = y ◇ (y ◇ (z ◇ (w ◇ y)))
equation 41652 := x ◇ x = y ◇ (y ◇ (z ◇ (w ◇ z)))
equation 41653 := x ◇ x = y ◇ (y ◇ (z ◇ (w ◇ w)))
equation 41654 := x ◇ x = y ◇ (y ◇ (z ◇ (w ◇ u)))
equation 41655 := x ◇ x = y ◇ (z ◇ (x ◇ (x ◇ x)))
equation 41656 := x ◇ x = y ◇ (z ◇ (x ◇ (x ◇ y)))
equation 41657 := x ◇ x = y ◇ (z ◇ (x ◇ (x ◇ z)))
equation 41658 := x ◇ x = y ◇ (z ◇ (x ◇ (x ◇ w)))
equation 41659 := x ◇ x = y ◇ (z ◇ (x ◇ (y ◇ x)))
equation 41660 := x ◇ x = y ◇ (z ◇ (x ◇ (y ◇ y)))
equation 41661 := x ◇ x = y ◇ (z ◇ (x ◇ (y ◇ z)))
equation 41662 := x ◇ x = y ◇ (z ◇ (x ◇ (y ◇ w)))
equation 41663 := x ◇ x = y ◇ (z ◇ (x ◇ (z ◇ x)))
equation 41664 := x ◇ x = y ◇ (z ◇ (x ◇ (z ◇ y)))
equation 41665 := x ◇ x = y ◇ (z ◇ (x ◇ (z ◇ z)))
equation 41666 := x ◇ x = y ◇ (z ◇ (x ◇ (z ◇ w)))
equation 41667 := x ◇ x = y ◇ (z ◇ (x ◇ (w ◇ x)))
equation 41668 := x ◇ x = y ◇ (z ◇ (x ◇ (w ◇ y)))
equation 41669 := x ◇ x = y ◇ (z ◇ (x ◇ (w ◇ z)))
equation 41670 := x ◇ x = y ◇ (z ◇ (x ◇ (w ◇ w)))
equation 41671 := x ◇ x = y ◇ (z ◇ (x ◇ (w ◇ u)))
equation 41672 := x ◇ x = y ◇ (z ◇ (y ◇ (x ◇ x)))
equation 41673 := x ◇ x = y ◇ (z ◇ (y ◇ (x ◇ y)))
equation 41674 := x ◇ x = y ◇ (z ◇ (y ◇ (x ◇ z)))
equation 41675 := x ◇ x = y ◇ (z ◇ (y ◇ (x ◇ w)))
equation 41676 := x ◇ x = y ◇ (z ◇ (y ◇ (y ◇ x)))
equation 41677 := x ◇ x = y ◇ (z ◇ (y ◇ (y ◇ y)))
equation 41678 := x ◇ x = y ◇ (z ◇ (y ◇ (y ◇ z)))
equation 41679 := x ◇ x = y ◇ (z ◇ (y ◇ (y ◇ w)))
equation 41680 := x ◇ x = y ◇ (z ◇ (y ◇ (z ◇ x)))
equation 41681 := x ◇ x = y ◇ (z ◇ (y ◇ (z ◇ y)))
equation 41682 := x ◇ x = y ◇ (z ◇ (y ◇ (z ◇ z)))
equation 41683 := x ◇ x = y ◇ (z ◇ (y ◇ (z ◇ w)))
equation 41684 := x ◇ x = y ◇ (z ◇ (y ◇ (w ◇ x)))
equation 41685 := x ◇ x = y ◇ (z ◇ (y ◇ (w ◇ y)))
equation 41686 := x ◇ x = y ◇ (z ◇ (y ◇ (w ◇ z)))
equation 41687 := x ◇ x = y ◇ (z ◇ (y ◇ (w ◇ w)))
equation 41688 := x ◇ x = y ◇ (z ◇ (y ◇ (w ◇ u)))
equation 41689 := x ◇ x = y ◇ (z ◇ (z ◇ (x ◇ x)))
equation 41690 := x ◇ x = y ◇ (z ◇ (z ◇ (x ◇ y)))
equation 41691 := x ◇ x = y ◇ (z ◇ (z ◇ (x ◇ z)))
equation 41692 := x ◇ x = y ◇ (z ◇ (z ◇ (x ◇ w)))
equation 41693 := x ◇ x = y ◇ (z ◇ (z ◇ (y ◇ x)))
equation 41694 := x ◇ x = y ◇ (z ◇ (z ◇ (y ◇ y)))
equation 41695 := x ◇ x = y ◇ (z ◇ (z ◇ (y ◇ z)))
equation 41696 := x ◇ x = y ◇ (z ◇ (z ◇ (y ◇ w)))
equation 41697 := x ◇ x = y ◇ (z ◇ (z ◇ (z ◇ x)))
equation 41698 := x ◇ x = y ◇ (z ◇ (z ◇ (z ◇ y)))
equation 41699 := x ◇ x = y ◇ (z ◇ (z ◇ (z ◇ z)))
equation 41700 := x ◇ x = y ◇ (z ◇ (z ◇ (z ◇ w)))
equation 41701 := x ◇ x = y ◇ (z ◇ (z ◇ (w ◇ x)))
equation 41702 := x ◇ x = y ◇ (z ◇ (z ◇ (w ◇ y)))
equation 41703 := x ◇ x = y ◇ (z ◇ (z ◇ (w ◇ z)))
equation 41704 := x ◇ x = y ◇ (z ◇ (z ◇ (w ◇ w)))
equation 41705 := x ◇ x = y ◇ (z ◇ (z ◇ (w ◇ u)))
equation 41706 := x ◇ x = y ◇ (z ◇ (w ◇ (x ◇ x)))
equation 41707 := x ◇ x = y ◇ (z ◇ (w ◇ (x ◇ y)))
equation 41708 := x ◇ x = y ◇ (z ◇ (w ◇ (x ◇ z)))
equation 41709 := x ◇ x = y ◇ (z ◇ (w ◇ (x ◇ w)))
equation 41710 := x ◇ x = y ◇ (z ◇ (w ◇ (x ◇ u)))
equation 41711 := x ◇ x = y ◇ (z ◇ (w ◇ (y ◇ x)))
equation 41712 := x ◇ x = y ◇ (z ◇ (w ◇ (y ◇ y)))
equation 41713 := x ◇ x = y ◇ (z ◇ (w ◇ (y ◇ z)))
equation 41714 := x ◇ x = y ◇ (z ◇ (w ◇ (y ◇ w)))
equation 41715 := x ◇ x = y ◇ (z ◇ (w ◇ (y ◇ u)))
equation 41716 := x ◇ x = y ◇ (z ◇ (w ◇ (z ◇ x)))
equation 41717 := x ◇ x = y ◇ (z ◇ (w ◇ (z ◇ y)))
equation 41718 := x ◇ x = y ◇ (z ◇ (w ◇ (z ◇ z)))
equation 41719 := x ◇ x = y ◇ (z ◇ (w ◇ (z ◇ w)))
equation 41720 := x ◇ x = y ◇ (z ◇ (w ◇ (z ◇ u)))
equation 41721 := x ◇ x = y ◇ (z ◇ (w ◇ (w ◇ x)))
equation 41722 := x ◇ x = y ◇ (z ◇ (w ◇ (w ◇ y)))
equation 41723 := x ◇ x = y ◇ (z ◇ (w ◇ (w ◇ z)))
equation 41724 := x ◇ x = y ◇ (z ◇ (w ◇ (w ◇ w)))
equation 41725 := x ◇ x = y ◇ (z ◇ (w ◇ (w ◇ u)))
equation 41726 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ x)))
equation 41727 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ y)))
equation 41728 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ z)))
equation 41729 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ w)))
equation 41730 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ u)))
equation 41731 := x ◇ x = y ◇ (z ◇ (w ◇ (u ◇ v)))
equation 41732 := x ◇ y = x ◇ (x ◇ (x ◇ (x ◇ x)))
equation 41733 := x ◇ y = x ◇ (x ◇ (x ◇ (x ◇ y)))
equation 41734 := x ◇ y = x ◇ (x ◇ (x ◇ (x ◇ z)))
equation 41735 := x ◇ y = x ◇ (x ◇ (x ◇ (y ◇ x)))
equation 41736 := x ◇ y = x ◇ (x ◇ (x ◇ (y ◇ y)))
equation 41737 := x ◇ y = x ◇ (x ◇ (x ◇ (y ◇ z)))
equation 41738 := x ◇ y = x ◇ (x ◇ (x ◇ (z ◇ x)))
equation 41739 := x ◇ y = x ◇ (x ◇ (x ◇ (z ◇ y)))
equation 41740 := x ◇ y = x ◇ (x ◇ (x ◇ (z ◇ z)))
equation 41741 := x ◇ y = x ◇ (x ◇ (x ◇ (z ◇ w)))
equation 41742 := x ◇ y = x ◇ (x ◇ (y ◇ (x ◇ x)))
equation 41743 := x ◇ y = x ◇ (x ◇ (y ◇ (x ◇ y)))
equation 41744 := x ◇ y = x ◇ (x ◇ (y ◇ (x ◇ z)))
equation 41745 := x ◇ y = x ◇ (x ◇ (y ◇ (y ◇ x)))
equation 41746 := x ◇ y = x ◇ (x ◇ (y ◇ (y ◇ y)))
equation 41747 := x ◇ y = x ◇ (x ◇ (y ◇ (y ◇ z)))
equation 41748 := x ◇ y = x ◇ (x ◇ (y ◇ (z ◇ x)))
equation 41749 := x ◇ y = x ◇ (x ◇ (y ◇ (z ◇ y)))
equation 41750 := x ◇ y = x ◇ (x ◇ (y ◇ (z ◇ z)))
equation 41751 := x ◇ y = x ◇ (x ◇ (y ◇ (z ◇ w)))
equation 41752 := x ◇ y = x ◇ (x ◇ (z ◇ (x ◇ x)))
equation 41753 := x ◇ y = x ◇ (x ◇ (z ◇ (x ◇ y)))
equation 41754 := x ◇ y = x ◇ (x ◇ (z ◇ (x ◇ z)))
equation 41755 := x ◇ y = x ◇ (x ◇ (z ◇ (x ◇ w)))
equation 41756 := x ◇ y = x ◇ (x ◇ (z ◇ (y ◇ x)))
equation 41757 := x ◇ y = x ◇ (x ◇ (z ◇ (y ◇ y)))
equation 41758 := x ◇ y = x ◇ (x ◇ (z ◇ (y ◇ z)))
equation 41759 := x ◇ y = x ◇ (x ◇ (z ◇ (y ◇ w)))
equation 41760 := x ◇ y = x ◇ (x ◇ (z ◇ (z ◇ x)))
equation 41761 := x ◇ y = x ◇ (x ◇ (z ◇ (z ◇ y)))
equation 41762 := x ◇ y = x ◇ (x ◇ (z ◇ (z ◇ z)))
equation 41763 := x ◇ y = x ◇ (x ◇ (z ◇ (z ◇ w)))
equation 41764 := x ◇ y = x ◇ (x ◇ (z ◇ (w ◇ x)))
equation 41765 := x ◇ y = x ◇ (x ◇ (z ◇ (w ◇ y)))
equation 41766 := x ◇ y = x ◇ (x ◇ (z ◇ (w ◇ z)))
equation 41767 := x ◇ y = x ◇ (x ◇ (z ◇ (w ◇ w)))
equation 41768 := x ◇ y = x ◇ (x ◇ (z ◇ (w ◇ u)))
equation 41769 := x ◇ y = x ◇ (y ◇ (x ◇ (x ◇ x)))
equation 41770 := x ◇ y = x ◇ (y ◇ (x ◇ (x ◇ y)))
equation 41771 := x ◇ y = x ◇ (y ◇ (x ◇ (x ◇ z)))
equation 41772 := x ◇ y = x ◇ (y ◇ (x ◇ (y ◇ x)))
equation 41773 := x ◇ y = x ◇ (y ◇ (x ◇ (y ◇ y)))
equation 41774 := x ◇ y = x ◇ (y ◇ (x ◇ (y ◇ z)))
equation 41775 := x ◇ y = x ◇ (y ◇ (x ◇ (z ◇ x)))
equation 41776 := x ◇ y = x ◇ (y ◇ (x ◇ (z ◇ y)))
equation 41777 := x ◇ y = x ◇ (y ◇ (x ◇ (z ◇ z)))
equation 41778 := x ◇ y = x ◇ (y ◇ (x ◇ (z ◇ w)))
equation 41779 := x ◇ y = x ◇ (y ◇ (y ◇ (x ◇ x)))
equation 41780 := x ◇ y = x ◇ (y ◇ (y ◇ (x ◇ y)))
equation 41781 := x ◇ y = x ◇ (y ◇ (y ◇ (x ◇ z)))
equation 41782 := x ◇ y = x ◇ (y ◇ (y ◇ (y ◇ x)))
equation 41783 := x ◇ y = x ◇ (y ◇ (y ◇ (y ◇ y)))
equation 41784 := x ◇ y = x ◇ (y ◇ (y ◇ (y ◇ z)))
equation 41785 := x ◇ y = x ◇ (y ◇ (y ◇ (z ◇ x)))
equation 41786 := x ◇ y = x ◇ (y ◇ (y ◇ (z ◇ y)))
equation 41787 := x ◇ y = x ◇ (y ◇ (y ◇ (z ◇ z)))
equation 41788 := x ◇ y = x ◇ (y ◇ (y ◇ (z ◇ w)))
equation 41789 := x ◇ y = x ◇ (y ◇ (z ◇ (x ◇ x)))
equation 41790 := x ◇ y = x ◇ (y ◇ (z ◇ (x ◇ y)))
equation 41791 := x ◇ y = x ◇ (y ◇ (z ◇ (x ◇ z)))
equation 41792 := x ◇ y = x ◇ (y ◇ (z ◇ (x ◇ w)))
equation 41793 := x ◇ y = x ◇ (y ◇ (z ◇ (y ◇ x)))
equation 41794 := x ◇ y = x ◇ (y ◇ (z ◇ (y ◇ y)))
equation 41795 := x ◇ y = x ◇ (y ◇ (z ◇ (y ◇ z)))
equation 41796 := x ◇ y = x ◇ (y ◇ (z ◇ (y ◇ w)))
equation 41797 := x ◇ y = x ◇ (y ◇ (z ◇ (z ◇ x)))
equation 41798 := x ◇ y = x ◇ (y ◇ (z ◇ (z ◇ y)))
equation 41799 := x ◇ y = x ◇ (y ◇ (z ◇ (z ◇ z)))
equation 41800 := x ◇ y = x ◇ (y ◇ (z ◇ (z ◇ w)))
equation 41801 := x ◇ y = x ◇ (y ◇ (z ◇ (w ◇ x)))
equation 41802 := x ◇ y = x ◇ (y ◇ (z ◇ (w ◇ y)))
equation 41803 := x ◇ y = x ◇ (y ◇ (z ◇ (w ◇ z)))
equation 41804 := x ◇ y = x ◇ (y ◇ (z ◇ (w ◇ w)))
equation 41805 := x ◇ y = x ◇ (y ◇ (z ◇ (w ◇ u)))
equation 41806 := x ◇ y = x ◇ (z ◇ (x ◇ (x ◇ x)))
equation 41807 := x ◇ y = x ◇ (z ◇ (x ◇ (x ◇ y)))
equation 41808 := x ◇ y = x ◇ (z ◇ (x ◇ (x ◇ z)))
equation 41809 := x ◇ y = x ◇ (z ◇ (x ◇ (x ◇ w)))
equation 41810 := x ◇ y = x ◇ (z ◇ (x ◇ (y ◇ x)))
equation 41811 := x ◇ y = x ◇ (z ◇ (x ◇ (y ◇ y)))
equation 41812 := x ◇ y = x ◇ (z ◇ (x ◇ (y ◇ z)))
equation 41813 := x ◇ y = x ◇ (z ◇ (x ◇ (y ◇ w)))
equation 41814 := x ◇ y = x ◇ (z ◇ (x ◇ (z ◇ x)))
equation 41815 := x ◇ y = x ◇ (z ◇ (x ◇ (z ◇ y)))
equation 41816 := x ◇ y = x ◇ (z ◇ (x ◇ (z ◇ z)))
equation 41817 := x ◇ y = x ◇ (z ◇ (x ◇ (z ◇ w)))
equation 41818 := x ◇ y = x ◇ (z ◇ (x ◇ (w ◇ x)))
equation 41819 := x ◇ y = x ◇ (z ◇ (x ◇ (w ◇ y)))
equation 41820 := x ◇ y = x ◇ (z ◇ (x ◇ (w ◇ z)))
equation 41821 := x ◇ y = x ◇ (z ◇ (x ◇ (w ◇ w)))
equation 41822 := x ◇ y = x ◇ (z ◇ (x ◇ (w ◇ u)))
equation 41823 := x ◇ y = x ◇ (z ◇ (y ◇ (x ◇ x)))
equation 41824 := x ◇ y = x ◇ (z ◇ (y ◇ (x ◇ y)))
equation 41825 := x ◇ y = x ◇ (z ◇ (y ◇ (x ◇ z)))
equation 41826 := x ◇ y = x ◇ (z ◇ (y ◇ (x ◇ w)))
equation 41827 := x ◇ y = x ◇ (z ◇ (y ◇ (y ◇ x)))
equation 41828 := x ◇ y = x ◇ (z ◇ (y ◇ (y ◇ y)))
equation 41829 := x ◇ y = x ◇ (z ◇ (y ◇ (y ◇ z)))
equation 41830 := x ◇ y = x ◇ (z ◇ (y ◇ (y ◇ w)))
equation 41831 := x ◇ y = x ◇ (z ◇ (y ◇ (z ◇ x)))
equation 41832 := x ◇ y = x ◇ (z ◇ (y ◇ (z ◇ y)))
equation 41833 := x ◇ y = x ◇ (z ◇ (y ◇ (z ◇ z)))
equation 41834 := x ◇ y = x ◇ (z ◇ (y ◇ (z ◇ w)))
equation 41835 := x ◇ y = x ◇ (z ◇ (y ◇ (w ◇ x)))
equation 41836 := x ◇ y = x ◇ (z ◇ (y ◇ (w ◇ y)))
equation 41837 := x ◇ y = x ◇ (z ◇ (y ◇ (w ◇ z)))
equation 41838 := x ◇ y = x ◇ (z ◇ (y ◇ (w ◇ w)))
equation 41839 := x ◇ y = x ◇ (z ◇ (y ◇ (w ◇ u)))
equation 41840 := x ◇ y = x ◇ (z ◇ (z ◇ (x ◇ x)))
equation 41841 := x ◇ y = x ◇ (z ◇ (z ◇ (x ◇ y)))
equation 41842 := x ◇ y = x ◇ (z ◇ (z ◇ (x ◇ z)))
equation 41843 := x ◇ y = x ◇ (z ◇ (z ◇ (x ◇ w)))
equation 41844 := x ◇ y = x ◇ (z ◇ (z ◇ (y ◇ x)))
equation 41845 := x ◇ y = x ◇ (z ◇ (z ◇ (y ◇ y)))
equation 41846 := x ◇ y = x ◇ (z ◇ (z ◇ (y ◇ z)))
equation 41847 := x ◇ y = x ◇ (z ◇ (z ◇ (y ◇ w)))
equation 41848 := x ◇ y = x ◇ (z ◇ (z ◇ (z ◇ x)))
equation 41849 := x ◇ y = x ◇ (z ◇ (z ◇ (z ◇ y)))
equation 41850 := x ◇ y = x ◇ (z ◇ (z ◇ (z ◇ z)))
equation 41851 := x ◇ y = x ◇ (z ◇ (z ◇ (z ◇ w)))
equation 41852 := x ◇ y = x ◇ (z ◇ (z ◇ (w ◇ x)))
equation 41853 := x ◇ y = x ◇ (z ◇ (z ◇ (w ◇ y)))
equation 41854 := x ◇ y = x ◇ (z ◇ (z ◇ (w ◇ z)))
equation 41855 := x ◇ y = x ◇ (z ◇ (z ◇ (w ◇ w)))
equation 41856 := x ◇ y = x ◇ (z ◇ (z ◇ (w ◇ u)))
equation 41857 := x ◇ y = x ◇ (z ◇ (w ◇ (x ◇ x)))
equation 41858 := x ◇ y = x ◇ (z ◇ (w ◇ (x ◇ y)))
equation 41859 := x ◇ y = x ◇ (z ◇ (w ◇ (x ◇ z)))
equation 41860 := x ◇ y = x ◇ (z ◇ (w ◇ (x ◇ w)))
equation 41861 := x ◇ y = x ◇ (z ◇ (w ◇ (x ◇ u)))
equation 41862 := x ◇ y = x ◇ (z ◇ (w ◇ (y ◇ x)))
equation 41863 := x ◇ y = x ◇ (z ◇ (w ◇ (y ◇ y)))
equation 41864 := x ◇ y = x ◇ (z ◇ (w ◇ (y ◇ z)))
equation 41865 := x ◇ y = x ◇ (z ◇ (w ◇ (y ◇ w)))
equation 41866 := x ◇ y = x ◇ (z ◇ (w ◇ (y ◇ u)))
equation 41867 := x ◇ y = x ◇ (z ◇ (w ◇ (z ◇ x)))
equation 41868 := x ◇ y = x ◇ (z ◇ (w ◇ (z ◇ y)))
equation 41869 := x ◇ y = x ◇ (z ◇ (w ◇ (z ◇ z)))
equation 41870 := x ◇ y = x ◇ (z ◇ (w ◇ (z ◇ w)))
equation 41871 := x ◇ y = x ◇ (z ◇ (w ◇ (z ◇ u)))
equation 41872 := x ◇ y = x ◇ (z ◇ (w ◇ (w ◇ x)))
equation 41873 := x ◇ y = x ◇ (z ◇ (w ◇ (w ◇ y)))
equation 41874 := x ◇ y = x ◇ (z ◇ (w ◇ (w ◇ z)))
equation 41875 := x ◇ y = x ◇ (z ◇ (w ◇ (w ◇ w)))
equation 41876 := x ◇ y = x ◇ (z ◇ (w ◇ (w ◇ u)))
equation 41877 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ x)))
equation 41878 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ y)))
equation 41879 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ z)))
equation 41880 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ w)))
equation 41881 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ u)))
equation 41882 := x ◇ y = x ◇ (z ◇ (w ◇ (u ◇ v)))
equation 41883 := x ◇ y = y ◇ (x ◇ (x ◇ (x ◇ x)))
equation 41884 := x ◇ y = y ◇ (x ◇ (x ◇ (x ◇ y)))
equation 41885 := x ◇ y = y ◇ (x ◇ (x ◇ (x ◇ z)))
equation 41886 := x ◇ y = y ◇ (x ◇ (x ◇ (y ◇ x)))
equation 41887 := x ◇ y = y ◇ (x ◇ (x ◇ (y ◇ y)))
equation 41888 := x ◇ y = y ◇ (x ◇ (x ◇ (y ◇ z)))
equation 41889 := x ◇ y = y ◇ (x ◇ (x ◇ (z ◇ x)))
equation 41890 := x ◇ y = y ◇ (x ◇ (x ◇ (z ◇ y)))
equation 41891 := x ◇ y = y ◇ (x ◇ (x ◇ (z ◇ z)))
equation 41892 := x ◇ y = y ◇ (x ◇ (x ◇ (z ◇ w)))
equation 41893 := x ◇ y = y ◇ (x ◇ (y ◇ (x ◇ x)))
equation 41894 := x ◇ y = y ◇ (x ◇ (y ◇ (x ◇ y)))
equation 41895 := x ◇ y = y ◇ (x ◇ (y ◇ (x ◇ z)))
equation 41896 := x ◇ y = y ◇ (x ◇ (y ◇ (y ◇ x)))
equation 41897 := x ◇ y = y ◇ (x ◇ (y ◇ (y ◇ y)))
equation 41898 := x ◇ y = y ◇ (x ◇ (y ◇ (y ◇ z)))
equation 41899 := x ◇ y = y ◇ (x ◇ (y ◇ (z ◇ x)))
equation 41900 := x ◇ y = y ◇ (x ◇ (y ◇ (z ◇ y)))
equation 41901 := x ◇ y = y ◇ (x ◇ (y ◇ (z ◇ z)))
equation 41902 := x ◇ y = y ◇ (x ◇ (y ◇ (z ◇ w)))
equation 41903 := x ◇ y = y ◇ (x ◇ (z ◇ (x ◇ x)))
equation 41904 := x ◇ y = y ◇ (x ◇ (z ◇ (x ◇ y)))
equation 41905 := x ◇ y = y ◇ (x ◇ (z ◇ (x ◇ z)))
equation 41906 := x ◇ y = y ◇ (x ◇ (z ◇ (x ◇ w)))
equation 41907 := x ◇ y = y ◇ (x ◇ (z ◇ (y ◇ x)))
equation 41908 := x ◇ y = y ◇ (x ◇ (z ◇ (y ◇ y)))
equation 41909 := x ◇ y = y ◇ (x ◇ (z ◇ (y ◇ z)))
equation 41910 := x ◇ y = y ◇ (x ◇ (z ◇ (y ◇ w)))
equation 41911 := x ◇ y = y ◇ (x ◇ (z ◇ (z ◇ x)))
equation 41912 := x ◇ y = y ◇ (x ◇ (z ◇ (z ◇ y)))
equation 41913 := x ◇ y = y ◇ (x ◇ (z ◇ (z ◇ z)))
equation 41914 := x ◇ y = y ◇ (x ◇ (z ◇ (z ◇ w)))
equation 41915 := x ◇ y = y ◇ (x ◇ (z ◇ (w ◇ x)))
equation 41916 := x ◇ y = y ◇ (x ◇ (z ◇ (w ◇ y)))
equation 41917 := x ◇ y = y ◇ (x ◇ (z ◇ (w ◇ z)))
equation 41918 := x ◇ y = y ◇ (x ◇ (z ◇ (w ◇ w)))
equation 41919 := x ◇ y = y ◇ (x ◇ (z ◇ (w ◇ u)))
equation 41920 := x ◇ y = y ◇ (y ◇ (x ◇ (x ◇ x)))
equation 41921 := x ◇ y = y ◇ (y ◇ (x ◇ (x ◇ y)))
equation 41922 := x ◇ y = y ◇ (y ◇ (x ◇ (x ◇ z)))
equation 41923 := x ◇ y = y ◇ (y ◇ (x ◇ (y ◇ x)))
equation 41924 := x ◇ y = y ◇ (y ◇ (x ◇ (y ◇ y)))
equation 41925 := x ◇ y = y ◇ (y ◇ (x ◇ (y ◇ z)))
equation 41926 := x ◇ y = y ◇ (y ◇ (x ◇ (z ◇ x)))
equation 41927 := x ◇ y = y ◇ (y ◇ (x ◇ (z ◇ y)))
equation 41928 := x ◇ y = y ◇ (y ◇ (x ◇ (z ◇ z)))
equation 41929 := x ◇ y = y ◇ (y ◇ (x ◇ (z ◇ w)))
equation 41930 := x ◇ y = y ◇ (y ◇ (y ◇ (x ◇ x)))
equation 41931 := x ◇ y = y ◇ (y ◇ (y ◇ (x ◇ y)))
equation 41932 := x ◇ y = y ◇ (y ◇ (y ◇ (x ◇ z)))
equation 41933 := x ◇ y = y ◇ (y ◇ (y ◇ (y ◇ x)))
equation 41934 := x ◇ y = y ◇ (y ◇ (y ◇ (y ◇ y)))
equation 41935 := x ◇ y = y ◇ (y ◇ (y ◇ (y ◇ z)))
equation 41936 := x ◇ y = y ◇ (y ◇ (y ◇ (z ◇ x)))
equation 41937 := x ◇ y = y ◇ (y ◇ (y ◇ (z ◇ y)))
equation 41938 := x ◇ y = y ◇ (y ◇ (y ◇ (z ◇ z)))
equation 41939 := x ◇ y = y ◇ (y ◇ (y ◇ (z ◇ w)))
equation 41940 := x ◇ y = y ◇ (y ◇ (z ◇ (x ◇ x)))
equation 41941 := x ◇ y = y ◇ (y ◇ (z ◇ (x ◇ y)))
equation 41942 := x ◇ y = y ◇ (y ◇ (z ◇ (x ◇ z)))
equation 41943 := x ◇ y = y ◇ (y ◇ (z ◇ (x ◇ w)))
equation 41944 := x ◇ y = y ◇ (y ◇ (z ◇ (y ◇ x)))
equation 41945 := x ◇ y = y ◇ (y ◇ (z ◇ (y ◇ y)))
equation 41946 := x ◇ y = y ◇ (y ◇ (z ◇ (y ◇ z)))
equation 41947 := x ◇ y = y ◇ (y ◇ (z ◇ (y ◇ w)))
equation 41948 := x ◇ y = y ◇ (y ◇ (z ◇ (z ◇ x)))
equation 41949 := x ◇ y = y ◇ (y ◇ (z ◇ (z ◇ y)))
equation 41950 := x ◇ y = y ◇ (y ◇ (z ◇ (z ◇ z)))
equation 41951 := x ◇ y = y ◇ (y ◇ (z ◇ (z ◇ w)))
equation 41952 := x ◇ y = y ◇ (y ◇ (z ◇ (w ◇ x)))
equation 41953 := x ◇ y = y ◇ (y ◇ (z ◇ (w ◇ y)))
equation 41954 := x ◇ y = y ◇ (y ◇ (z ◇ (w ◇ z)))
equation 41955 := x ◇ y = y ◇ (y ◇ (z ◇ (w ◇ w)))
equation 41956 := x ◇ y = y ◇ (y ◇ (z ◇ (w ◇ u)))
equation 41957 := x ◇ y = y ◇ (z ◇ (x ◇ (x ◇ x)))
equation 41958 := x ◇ y = y ◇ (z ◇ (x ◇ (x ◇ y)))
equation 41959 := x ◇ y = y ◇ (z ◇ (x ◇ (x ◇ z)))
equation 41960 := x ◇ y = y ◇ (z ◇ (x ◇ (x ◇ w)))
equation 41961 := x ◇ y = y ◇ (z ◇ (x ◇ (y ◇ x)))
equation 41962 := x ◇ y = y ◇ (z ◇ (x ◇ (y ◇ y)))
equation 41963 := x ◇ y = y ◇ (z ◇ (x ◇ (y ◇ z)))
equation 41964 := x ◇ y = y ◇ (z ◇ (x ◇ (y ◇ w)))
equation 41965 := x ◇ y = y ◇ (z ◇ (x ◇ (z ◇ x)))
equation 41966 := x ◇ y = y ◇ (z ◇ (x ◇ (z ◇ y)))
equation 41967 := x ◇ y = y ◇ (z ◇ (x ◇ (z ◇ z)))
equation 41968 := x ◇ y = y ◇ (z ◇ (x ◇ (z ◇ w)))
equation 41969 := x ◇ y = y ◇ (z ◇ (x ◇ (w ◇ x)))
equation 41970 := x ◇ y = y ◇ (z ◇ (x ◇ (w ◇ y)))
equation 41971 := x ◇ y = y ◇ (z ◇ (x ◇ (w ◇ z)))
equation 41972 := x ◇ y = y ◇ (z ◇ (x ◇ (w ◇ w)))
equation 41973 := x ◇ y = y ◇ (z ◇ (x ◇ (w ◇ u)))
equation 41974 := x ◇ y = y ◇ (z ◇ (y ◇ (x ◇ x)))
equation 41975 := x ◇ y = y ◇ (z ◇ (y ◇ (x ◇ y)))
equation 41976 := x ◇ y = y ◇ (z ◇ (y ◇ (x ◇ z)))
equation 41977 := x ◇ y = y ◇ (z ◇ (y ◇ (x ◇ w)))
equation 41978 := x ◇ y = y ◇ (z ◇ (y ◇ (y ◇ x)))
equation 41979 := x ◇ y = y ◇ (z ◇ (y ◇ (y ◇ y)))
equation 41980 := x ◇ y = y ◇ (z ◇ (y ◇ (y ◇ z)))
equation 41981 := x ◇ y = y ◇ (z ◇ (y ◇ (y ◇ w)))
equation 41982 := x ◇ y = y ◇ (z ◇ (y ◇ (z ◇ x)))
equation 41983 := x ◇ y = y ◇ (z ◇ (y ◇ (z ◇ y)))
equation 41984 := x ◇ y = y ◇ (z ◇ (y ◇ (z ◇ z)))
equation 41985 := x ◇ y = y ◇ (z ◇ (y ◇ (z ◇ w)))
equation 41986 := x ◇ y = y ◇ (z ◇ (y ◇ (w ◇ x)))
equation 41987 := x ◇ y = y ◇ (z ◇ (y ◇ (w ◇ y)))
equation 41988 := x ◇ y = y ◇ (z ◇ (y ◇ (w ◇ z)))
equation 41989 := x ◇ y = y ◇ (z ◇ (y ◇ (w ◇ w)))
equation 41990 := x ◇ y = y ◇ (z ◇ (y ◇ (w ◇ u)))
equation 41991 := x ◇ y = y ◇ (z ◇ (z ◇ (x ◇ x)))
equation 41992 := x ◇ y = y ◇ (z ◇ (z ◇ (x ◇ y)))
equation 41993 := x ◇ y = y ◇ (z ◇ (z ◇ (x ◇ z)))
equation 41994 := x ◇ y = y ◇ (z ◇ (z ◇ (x ◇ w)))
equation 41995 := x ◇ y = y ◇ (z ◇ (z ◇ (y ◇ x)))
equation 41996 := x ◇ y = y ◇ (z ◇ (z ◇ (y ◇ y)))
equation 41997 := x ◇ y = y ◇ (z ◇ (z ◇ (y ◇ z)))
equation 41998 := x ◇ y = y ◇ (z ◇ (z ◇ (y ◇ w)))
equation 41999 := x ◇ y = y ◇ (z ◇ (z ◇ (z ◇ x)))
