import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 34000-34999 -/

equation 34000 := x = ((y ◇ y) ◇ (x ◇ (y ◇ x))) ◇ x
equation 34001 := x = ((y ◇ y) ◇ (x ◇ (y ◇ x))) ◇ y
equation 34002 := x = ((y ◇ y) ◇ (x ◇ (y ◇ x))) ◇ z
equation 34003 := x = ((y ◇ y) ◇ (x ◇ (y ◇ y))) ◇ x
equation 34004 := x = ((y ◇ y) ◇ (x ◇ (y ◇ y))) ◇ y
equation 34005 := x = ((y ◇ y) ◇ (x ◇ (y ◇ y))) ◇ z
equation 34006 := x = ((y ◇ y) ◇ (x ◇ (y ◇ z))) ◇ x
equation 34007 := x = ((y ◇ y) ◇ (x ◇ (y ◇ z))) ◇ y
equation 34008 := x = ((y ◇ y) ◇ (x ◇ (y ◇ z))) ◇ z
equation 34009 := x = ((y ◇ y) ◇ (x ◇ (y ◇ z))) ◇ w
equation 34010 := x = ((y ◇ y) ◇ (x ◇ (z ◇ x))) ◇ x
equation 34011 := x = ((y ◇ y) ◇ (x ◇ (z ◇ x))) ◇ y
equation 34012 := x = ((y ◇ y) ◇ (x ◇ (z ◇ x))) ◇ z
equation 34013 := x = ((y ◇ y) ◇ (x ◇ (z ◇ x))) ◇ w
equation 34014 := x = ((y ◇ y) ◇ (x ◇ (z ◇ y))) ◇ x
equation 34015 := x = ((y ◇ y) ◇ (x ◇ (z ◇ y))) ◇ y
equation 34016 := x = ((y ◇ y) ◇ (x ◇ (z ◇ y))) ◇ z
equation 34017 := x = ((y ◇ y) ◇ (x ◇ (z ◇ y))) ◇ w
equation 34018 := x = ((y ◇ y) ◇ (x ◇ (z ◇ z))) ◇ x
equation 34019 := x = ((y ◇ y) ◇ (x ◇ (z ◇ z))) ◇ y
equation 34020 := x = ((y ◇ y) ◇ (x ◇ (z ◇ z))) ◇ z
equation 34021 := x = ((y ◇ y) ◇ (x ◇ (z ◇ z))) ◇ w
equation 34022 := x = ((y ◇ y) ◇ (x ◇ (z ◇ w))) ◇ x
equation 34023 := x = ((y ◇ y) ◇ (x ◇ (z ◇ w))) ◇ y
equation 34024 := x = ((y ◇ y) ◇ (x ◇ (z ◇ w))) ◇ z
equation 34025 := x = ((y ◇ y) ◇ (x ◇ (z ◇ w))) ◇ w
equation 34026 := x = ((y ◇ y) ◇ (x ◇ (z ◇ w))) ◇ u
equation 34027 := x = ((y ◇ y) ◇ (y ◇ (x ◇ x))) ◇ x
equation 34028 := x = ((y ◇ y) ◇ (y ◇ (x ◇ x))) ◇ y
equation 34029 := x = ((y ◇ y) ◇ (y ◇ (x ◇ x))) ◇ z
equation 34030 := x = ((y ◇ y) ◇ (y ◇ (x ◇ y))) ◇ x
equation 34031 := x = ((y ◇ y) ◇ (y ◇ (x ◇ y))) ◇ y
equation 34032 := x = ((y ◇ y) ◇ (y ◇ (x ◇ y))) ◇ z
equation 34033 := x = ((y ◇ y) ◇ (y ◇ (x ◇ z))) ◇ x
equation 34034 := x = ((y ◇ y) ◇ (y ◇ (x ◇ z))) ◇ y
equation 34035 := x = ((y ◇ y) ◇ (y ◇ (x ◇ z))) ◇ z
equation 34036 := x = ((y ◇ y) ◇ (y ◇ (x ◇ z))) ◇ w
equation 34037 := x = ((y ◇ y) ◇ (y ◇ (y ◇ x))) ◇ x
equation 34038 := x = ((y ◇ y) ◇ (y ◇ (y ◇ x))) ◇ y
equation 34039 := x = ((y ◇ y) ◇ (y ◇ (y ◇ x))) ◇ z
equation 34040 := x = ((y ◇ y) ◇ (y ◇ (y ◇ y))) ◇ x
equation 34041 := x = ((y ◇ y) ◇ (y ◇ (y ◇ y))) ◇ y
equation 34042 := x = ((y ◇ y) ◇ (y ◇ (y ◇ y))) ◇ z
equation 34043 := x = ((y ◇ y) ◇ (y ◇ (y ◇ z))) ◇ x
equation 34044 := x = ((y ◇ y) ◇ (y ◇ (y ◇ z))) ◇ y
equation 34045 := x = ((y ◇ y) ◇ (y ◇ (y ◇ z))) ◇ z
equation 34046 := x = ((y ◇ y) ◇ (y ◇ (y ◇ z))) ◇ w
equation 34047 := x = ((y ◇ y) ◇ (y ◇ (z ◇ x))) ◇ x
equation 34048 := x = ((y ◇ y) ◇ (y ◇ (z ◇ x))) ◇ y
equation 34049 := x = ((y ◇ y) ◇ (y ◇ (z ◇ x))) ◇ z
equation 34050 := x = ((y ◇ y) ◇ (y ◇ (z ◇ x))) ◇ w
equation 34051 := x = ((y ◇ y) ◇ (y ◇ (z ◇ y))) ◇ x
equation 34052 := x = ((y ◇ y) ◇ (y ◇ (z ◇ y))) ◇ y
equation 34053 := x = ((y ◇ y) ◇ (y ◇ (z ◇ y))) ◇ z
equation 34054 := x = ((y ◇ y) ◇ (y ◇ (z ◇ y))) ◇ w
equation 34055 := x = ((y ◇ y) ◇ (y ◇ (z ◇ z))) ◇ x
equation 34056 := x = ((y ◇ y) ◇ (y ◇ (z ◇ z))) ◇ y
equation 34057 := x = ((y ◇ y) ◇ (y ◇ (z ◇ z))) ◇ z
equation 34058 := x = ((y ◇ y) ◇ (y ◇ (z ◇ z))) ◇ w
equation 34059 := x = ((y ◇ y) ◇ (y ◇ (z ◇ w))) ◇ x
equation 34060 := x = ((y ◇ y) ◇ (y ◇ (z ◇ w))) ◇ y
equation 34061 := x = ((y ◇ y) ◇ (y ◇ (z ◇ w))) ◇ z
equation 34062 := x = ((y ◇ y) ◇ (y ◇ (z ◇ w))) ◇ w
equation 34063 := x = ((y ◇ y) ◇ (y ◇ (z ◇ w))) ◇ u
equation 34064 := x = ((y ◇ y) ◇ (z ◇ (x ◇ x))) ◇ x
equation 34065 := x = ((y ◇ y) ◇ (z ◇ (x ◇ x))) ◇ y
equation 34066 := x = ((y ◇ y) ◇ (z ◇ (x ◇ x))) ◇ z
equation 34067 := x = ((y ◇ y) ◇ (z ◇ (x ◇ x))) ◇ w
equation 34068 := x = ((y ◇ y) ◇ (z ◇ (x ◇ y))) ◇ x
equation 34069 := x = ((y ◇ y) ◇ (z ◇ (x ◇ y))) ◇ y
equation 34070 := x = ((y ◇ y) ◇ (z ◇ (x ◇ y))) ◇ z
equation 34071 := x = ((y ◇ y) ◇ (z ◇ (x ◇ y))) ◇ w
equation 34072 := x = ((y ◇ y) ◇ (z ◇ (x ◇ z))) ◇ x
equation 34073 := x = ((y ◇ y) ◇ (z ◇ (x ◇ z))) ◇ y
equation 34074 := x = ((y ◇ y) ◇ (z ◇ (x ◇ z))) ◇ z
equation 34075 := x = ((y ◇ y) ◇ (z ◇ (x ◇ z))) ◇ w
equation 34076 := x = ((y ◇ y) ◇ (z ◇ (x ◇ w))) ◇ x
equation 34077 := x = ((y ◇ y) ◇ (z ◇ (x ◇ w))) ◇ y
equation 34078 := x = ((y ◇ y) ◇ (z ◇ (x ◇ w))) ◇ z
equation 34079 := x = ((y ◇ y) ◇ (z ◇ (x ◇ w))) ◇ w
equation 34080 := x = ((y ◇ y) ◇ (z ◇ (x ◇ w))) ◇ u
equation 34081 := x = ((y ◇ y) ◇ (z ◇ (y ◇ x))) ◇ x
equation 34082 := x = ((y ◇ y) ◇ (z ◇ (y ◇ x))) ◇ y
equation 34083 := x = ((y ◇ y) ◇ (z ◇ (y ◇ x))) ◇ z
equation 34084 := x = ((y ◇ y) ◇ (z ◇ (y ◇ x))) ◇ w
equation 34085 := x = ((y ◇ y) ◇ (z ◇ (y ◇ y))) ◇ x
equation 34086 := x = ((y ◇ y) ◇ (z ◇ (y ◇ y))) ◇ y
equation 34087 := x = ((y ◇ y) ◇ (z ◇ (y ◇ y))) ◇ z
equation 34088 := x = ((y ◇ y) ◇ (z ◇ (y ◇ y))) ◇ w
equation 34089 := x = ((y ◇ y) ◇ (z ◇ (y ◇ z))) ◇ x
equation 34090 := x = ((y ◇ y) ◇ (z ◇ (y ◇ z))) ◇ y
equation 34091 := x = ((y ◇ y) ◇ (z ◇ (y ◇ z))) ◇ z
equation 34092 := x = ((y ◇ y) ◇ (z ◇ (y ◇ z))) ◇ w
equation 34093 := x = ((y ◇ y) ◇ (z ◇ (y ◇ w))) ◇ x
equation 34094 := x = ((y ◇ y) ◇ (z ◇ (y ◇ w))) ◇ y
equation 34095 := x = ((y ◇ y) ◇ (z ◇ (y ◇ w))) ◇ z
equation 34096 := x = ((y ◇ y) ◇ (z ◇ (y ◇ w))) ◇ w
equation 34097 := x = ((y ◇ y) ◇ (z ◇ (y ◇ w))) ◇ u
equation 34098 := x = ((y ◇ y) ◇ (z ◇ (z ◇ x))) ◇ x
equation 34099 := x = ((y ◇ y) ◇ (z ◇ (z ◇ x))) ◇ y
equation 34100 := x = ((y ◇ y) ◇ (z ◇ (z ◇ x))) ◇ z
equation 34101 := x = ((y ◇ y) ◇ (z ◇ (z ◇ x))) ◇ w
equation 34102 := x = ((y ◇ y) ◇ (z ◇ (z ◇ y))) ◇ x
equation 34103 := x = ((y ◇ y) ◇ (z ◇ (z ◇ y))) ◇ y
equation 34104 := x = ((y ◇ y) ◇ (z ◇ (z ◇ y))) ◇ z
equation 34105 := x = ((y ◇ y) ◇ (z ◇ (z ◇ y))) ◇ w
equation 34106 := x = ((y ◇ y) ◇ (z ◇ (z ◇ z))) ◇ x
equation 34107 := x = ((y ◇ y) ◇ (z ◇ (z ◇ z))) ◇ y
equation 34108 := x = ((y ◇ y) ◇ (z ◇ (z ◇ z))) ◇ z
equation 34109 := x = ((y ◇ y) ◇ (z ◇ (z ◇ z))) ◇ w
equation 34110 := x = ((y ◇ y) ◇ (z ◇ (z ◇ w))) ◇ x
equation 34111 := x = ((y ◇ y) ◇ (z ◇ (z ◇ w))) ◇ y
equation 34112 := x = ((y ◇ y) ◇ (z ◇ (z ◇ w))) ◇ z
equation 34113 := x = ((y ◇ y) ◇ (z ◇ (z ◇ w))) ◇ w
equation 34114 := x = ((y ◇ y) ◇ (z ◇ (z ◇ w))) ◇ u
equation 34115 := x = ((y ◇ y) ◇ (z ◇ (w ◇ x))) ◇ x
equation 34116 := x = ((y ◇ y) ◇ (z ◇ (w ◇ x))) ◇ y
equation 34117 := x = ((y ◇ y) ◇ (z ◇ (w ◇ x))) ◇ z
equation 34118 := x = ((y ◇ y) ◇ (z ◇ (w ◇ x))) ◇ w
equation 34119 := x = ((y ◇ y) ◇ (z ◇ (w ◇ x))) ◇ u
equation 34120 := x = ((y ◇ y) ◇ (z ◇ (w ◇ y))) ◇ x
equation 34121 := x = ((y ◇ y) ◇ (z ◇ (w ◇ y))) ◇ y
equation 34122 := x = ((y ◇ y) ◇ (z ◇ (w ◇ y))) ◇ z
equation 34123 := x = ((y ◇ y) ◇ (z ◇ (w ◇ y))) ◇ w
equation 34124 := x = ((y ◇ y) ◇ (z ◇ (w ◇ y))) ◇ u
equation 34125 := x = ((y ◇ y) ◇ (z ◇ (w ◇ z))) ◇ x
equation 34126 := x = ((y ◇ y) ◇ (z ◇ (w ◇ z))) ◇ y
equation 34127 := x = ((y ◇ y) ◇ (z ◇ (w ◇ z))) ◇ z
equation 34128 := x = ((y ◇ y) ◇ (z ◇ (w ◇ z))) ◇ w
equation 34129 := x = ((y ◇ y) ◇ (z ◇ (w ◇ z))) ◇ u
equation 34130 := x = ((y ◇ y) ◇ (z ◇ (w ◇ w))) ◇ x
equation 34131 := x = ((y ◇ y) ◇ (z ◇ (w ◇ w))) ◇ y
equation 34132 := x = ((y ◇ y) ◇ (z ◇ (w ◇ w))) ◇ z
equation 34133 := x = ((y ◇ y) ◇ (z ◇ (w ◇ w))) ◇ w
equation 34134 := x = ((y ◇ y) ◇ (z ◇ (w ◇ w))) ◇ u
equation 34135 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ x
equation 34136 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ y
equation 34137 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ z
equation 34138 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ w
equation 34139 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ u
equation 34140 := x = ((y ◇ y) ◇ (z ◇ (w ◇ u))) ◇ v
equation 34141 := x = ((y ◇ z) ◇ (x ◇ (x ◇ x))) ◇ x
equation 34142 := x = ((y ◇ z) ◇ (x ◇ (x ◇ x))) ◇ y
equation 34143 := x = ((y ◇ z) ◇ (x ◇ (x ◇ x))) ◇ z
equation 34144 := x = ((y ◇ z) ◇ (x ◇ (x ◇ x))) ◇ w
equation 34145 := x = ((y ◇ z) ◇ (x ◇ (x ◇ y))) ◇ x
equation 34146 := x = ((y ◇ z) ◇ (x ◇ (x ◇ y))) ◇ y
equation 34147 := x = ((y ◇ z) ◇ (x ◇ (x ◇ y))) ◇ z
equation 34148 := x = ((y ◇ z) ◇ (x ◇ (x ◇ y))) ◇ w
equation 34149 := x = ((y ◇ z) ◇ (x ◇ (x ◇ z))) ◇ x
equation 34150 := x = ((y ◇ z) ◇ (x ◇ (x ◇ z))) ◇ y
equation 34151 := x = ((y ◇ z) ◇ (x ◇ (x ◇ z))) ◇ z
equation 34152 := x = ((y ◇ z) ◇ (x ◇ (x ◇ z))) ◇ w
equation 34153 := x = ((y ◇ z) ◇ (x ◇ (x ◇ w))) ◇ x
equation 34154 := x = ((y ◇ z) ◇ (x ◇ (x ◇ w))) ◇ y
equation 34155 := x = ((y ◇ z) ◇ (x ◇ (x ◇ w))) ◇ z
equation 34156 := x = ((y ◇ z) ◇ (x ◇ (x ◇ w))) ◇ w
equation 34157 := x = ((y ◇ z) ◇ (x ◇ (x ◇ w))) ◇ u
equation 34158 := x = ((y ◇ z) ◇ (x ◇ (y ◇ x))) ◇ x
equation 34159 := x = ((y ◇ z) ◇ (x ◇ (y ◇ x))) ◇ y
equation 34160 := x = ((y ◇ z) ◇ (x ◇ (y ◇ x))) ◇ z
equation 34161 := x = ((y ◇ z) ◇ (x ◇ (y ◇ x))) ◇ w
equation 34162 := x = ((y ◇ z) ◇ (x ◇ (y ◇ y))) ◇ x
equation 34163 := x = ((y ◇ z) ◇ (x ◇ (y ◇ y))) ◇ y
equation 34164 := x = ((y ◇ z) ◇ (x ◇ (y ◇ y))) ◇ z
equation 34165 := x = ((y ◇ z) ◇ (x ◇ (y ◇ y))) ◇ w
equation 34166 := x = ((y ◇ z) ◇ (x ◇ (y ◇ z))) ◇ x
equation 34167 := x = ((y ◇ z) ◇ (x ◇ (y ◇ z))) ◇ y
equation 34168 := x = ((y ◇ z) ◇ (x ◇ (y ◇ z))) ◇ z
equation 34169 := x = ((y ◇ z) ◇ (x ◇ (y ◇ z))) ◇ w
equation 34170 := x = ((y ◇ z) ◇ (x ◇ (y ◇ w))) ◇ x
equation 34171 := x = ((y ◇ z) ◇ (x ◇ (y ◇ w))) ◇ y
equation 34172 := x = ((y ◇ z) ◇ (x ◇ (y ◇ w))) ◇ z
equation 34173 := x = ((y ◇ z) ◇ (x ◇ (y ◇ w))) ◇ w
equation 34174 := x = ((y ◇ z) ◇ (x ◇ (y ◇ w))) ◇ u
equation 34175 := x = ((y ◇ z) ◇ (x ◇ (z ◇ x))) ◇ x
equation 34176 := x = ((y ◇ z) ◇ (x ◇ (z ◇ x))) ◇ y
equation 34177 := x = ((y ◇ z) ◇ (x ◇ (z ◇ x))) ◇ z
equation 34178 := x = ((y ◇ z) ◇ (x ◇ (z ◇ x))) ◇ w
equation 34179 := x = ((y ◇ z) ◇ (x ◇ (z ◇ y))) ◇ x
equation 34180 := x = ((y ◇ z) ◇ (x ◇ (z ◇ y))) ◇ y
equation 34181 := x = ((y ◇ z) ◇ (x ◇ (z ◇ y))) ◇ z
equation 34182 := x = ((y ◇ z) ◇ (x ◇ (z ◇ y))) ◇ w
equation 34183 := x = ((y ◇ z) ◇ (x ◇ (z ◇ z))) ◇ x
equation 34184 := x = ((y ◇ z) ◇ (x ◇ (z ◇ z))) ◇ y
equation 34185 := x = ((y ◇ z) ◇ (x ◇ (z ◇ z))) ◇ z
equation 34186 := x = ((y ◇ z) ◇ (x ◇ (z ◇ z))) ◇ w
equation 34187 := x = ((y ◇ z) ◇ (x ◇ (z ◇ w))) ◇ x
equation 34188 := x = ((y ◇ z) ◇ (x ◇ (z ◇ w))) ◇ y
equation 34189 := x = ((y ◇ z) ◇ (x ◇ (z ◇ w))) ◇ z
equation 34190 := x = ((y ◇ z) ◇ (x ◇ (z ◇ w))) ◇ w
equation 34191 := x = ((y ◇ z) ◇ (x ◇ (z ◇ w))) ◇ u
equation 34192 := x = ((y ◇ z) ◇ (x ◇ (w ◇ x))) ◇ x
equation 34193 := x = ((y ◇ z) ◇ (x ◇ (w ◇ x))) ◇ y
equation 34194 := x = ((y ◇ z) ◇ (x ◇ (w ◇ x))) ◇ z
equation 34195 := x = ((y ◇ z) ◇ (x ◇ (w ◇ x))) ◇ w
equation 34196 := x = ((y ◇ z) ◇ (x ◇ (w ◇ x))) ◇ u
equation 34197 := x = ((y ◇ z) ◇ (x ◇ (w ◇ y))) ◇ x
equation 34198 := x = ((y ◇ z) ◇ (x ◇ (w ◇ y))) ◇ y
equation 34199 := x = ((y ◇ z) ◇ (x ◇ (w ◇ y))) ◇ z
equation 34200 := x = ((y ◇ z) ◇ (x ◇ (w ◇ y))) ◇ w
equation 34201 := x = ((y ◇ z) ◇ (x ◇ (w ◇ y))) ◇ u
equation 34202 := x = ((y ◇ z) ◇ (x ◇ (w ◇ z))) ◇ x
equation 34203 := x = ((y ◇ z) ◇ (x ◇ (w ◇ z))) ◇ y
equation 34204 := x = ((y ◇ z) ◇ (x ◇ (w ◇ z))) ◇ z
equation 34205 := x = ((y ◇ z) ◇ (x ◇ (w ◇ z))) ◇ w
equation 34206 := x = ((y ◇ z) ◇ (x ◇ (w ◇ z))) ◇ u
equation 34207 := x = ((y ◇ z) ◇ (x ◇ (w ◇ w))) ◇ x
equation 34208 := x = ((y ◇ z) ◇ (x ◇ (w ◇ w))) ◇ y
equation 34209 := x = ((y ◇ z) ◇ (x ◇ (w ◇ w))) ◇ z
equation 34210 := x = ((y ◇ z) ◇ (x ◇ (w ◇ w))) ◇ w
equation 34211 := x = ((y ◇ z) ◇ (x ◇ (w ◇ w))) ◇ u
equation 34212 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ x
equation 34213 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ y
equation 34214 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ z
equation 34215 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ w
equation 34216 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ u
equation 34217 := x = ((y ◇ z) ◇ (x ◇ (w ◇ u))) ◇ v
equation 34218 := x = ((y ◇ z) ◇ (y ◇ (x ◇ x))) ◇ x
equation 34219 := x = ((y ◇ z) ◇ (y ◇ (x ◇ x))) ◇ y
equation 34220 := x = ((y ◇ z) ◇ (y ◇ (x ◇ x))) ◇ z
equation 34221 := x = ((y ◇ z) ◇ (y ◇ (x ◇ x))) ◇ w
equation 34222 := x = ((y ◇ z) ◇ (y ◇ (x ◇ y))) ◇ x
equation 34223 := x = ((y ◇ z) ◇ (y ◇ (x ◇ y))) ◇ y
equation 34224 := x = ((y ◇ z) ◇ (y ◇ (x ◇ y))) ◇ z
equation 34225 := x = ((y ◇ z) ◇ (y ◇ (x ◇ y))) ◇ w
equation 34226 := x = ((y ◇ z) ◇ (y ◇ (x ◇ z))) ◇ x
equation 34227 := x = ((y ◇ z) ◇ (y ◇ (x ◇ z))) ◇ y
equation 34228 := x = ((y ◇ z) ◇ (y ◇ (x ◇ z))) ◇ z
equation 34229 := x = ((y ◇ z) ◇ (y ◇ (x ◇ z))) ◇ w
equation 34230 := x = ((y ◇ z) ◇ (y ◇ (x ◇ w))) ◇ x
equation 34231 := x = ((y ◇ z) ◇ (y ◇ (x ◇ w))) ◇ y
equation 34232 := x = ((y ◇ z) ◇ (y ◇ (x ◇ w))) ◇ z
equation 34233 := x = ((y ◇ z) ◇ (y ◇ (x ◇ w))) ◇ w
equation 34234 := x = ((y ◇ z) ◇ (y ◇ (x ◇ w))) ◇ u
equation 34235 := x = ((y ◇ z) ◇ (y ◇ (y ◇ x))) ◇ x
equation 34236 := x = ((y ◇ z) ◇ (y ◇ (y ◇ x))) ◇ y
equation 34237 := x = ((y ◇ z) ◇ (y ◇ (y ◇ x))) ◇ z
equation 34238 := x = ((y ◇ z) ◇ (y ◇ (y ◇ x))) ◇ w
equation 34239 := x = ((y ◇ z) ◇ (y ◇ (y ◇ y))) ◇ x
equation 34240 := x = ((y ◇ z) ◇ (y ◇ (y ◇ y))) ◇ y
equation 34241 := x = ((y ◇ z) ◇ (y ◇ (y ◇ y))) ◇ z
equation 34242 := x = ((y ◇ z) ◇ (y ◇ (y ◇ y))) ◇ w
equation 34243 := x = ((y ◇ z) ◇ (y ◇ (y ◇ z))) ◇ x
equation 34244 := x = ((y ◇ z) ◇ (y ◇ (y ◇ z))) ◇ y
equation 34245 := x = ((y ◇ z) ◇ (y ◇ (y ◇ z))) ◇ z
equation 34246 := x = ((y ◇ z) ◇ (y ◇ (y ◇ z))) ◇ w
equation 34247 := x = ((y ◇ z) ◇ (y ◇ (y ◇ w))) ◇ x
equation 34248 := x = ((y ◇ z) ◇ (y ◇ (y ◇ w))) ◇ y
equation 34249 := x = ((y ◇ z) ◇ (y ◇ (y ◇ w))) ◇ z
equation 34250 := x = ((y ◇ z) ◇ (y ◇ (y ◇ w))) ◇ w
equation 34251 := x = ((y ◇ z) ◇ (y ◇ (y ◇ w))) ◇ u
equation 34252 := x = ((y ◇ z) ◇ (y ◇ (z ◇ x))) ◇ x
equation 34253 := x = ((y ◇ z) ◇ (y ◇ (z ◇ x))) ◇ y
equation 34254 := x = ((y ◇ z) ◇ (y ◇ (z ◇ x))) ◇ z
equation 34255 := x = ((y ◇ z) ◇ (y ◇ (z ◇ x))) ◇ w
equation 34256 := x = ((y ◇ z) ◇ (y ◇ (z ◇ y))) ◇ x
equation 34257 := x = ((y ◇ z) ◇ (y ◇ (z ◇ y))) ◇ y
equation 34258 := x = ((y ◇ z) ◇ (y ◇ (z ◇ y))) ◇ z
equation 34259 := x = ((y ◇ z) ◇ (y ◇ (z ◇ y))) ◇ w
equation 34260 := x = ((y ◇ z) ◇ (y ◇ (z ◇ z))) ◇ x
equation 34261 := x = ((y ◇ z) ◇ (y ◇ (z ◇ z))) ◇ y
equation 34262 := x = ((y ◇ z) ◇ (y ◇ (z ◇ z))) ◇ z
equation 34263 := x = ((y ◇ z) ◇ (y ◇ (z ◇ z))) ◇ w
equation 34264 := x = ((y ◇ z) ◇ (y ◇ (z ◇ w))) ◇ x
equation 34265 := x = ((y ◇ z) ◇ (y ◇ (z ◇ w))) ◇ y
equation 34266 := x = ((y ◇ z) ◇ (y ◇ (z ◇ w))) ◇ z
equation 34267 := x = ((y ◇ z) ◇ (y ◇ (z ◇ w))) ◇ w
equation 34268 := x = ((y ◇ z) ◇ (y ◇ (z ◇ w))) ◇ u
equation 34269 := x = ((y ◇ z) ◇ (y ◇ (w ◇ x))) ◇ x
equation 34270 := x = ((y ◇ z) ◇ (y ◇ (w ◇ x))) ◇ y
equation 34271 := x = ((y ◇ z) ◇ (y ◇ (w ◇ x))) ◇ z
equation 34272 := x = ((y ◇ z) ◇ (y ◇ (w ◇ x))) ◇ w
equation 34273 := x = ((y ◇ z) ◇ (y ◇ (w ◇ x))) ◇ u
equation 34274 := x = ((y ◇ z) ◇ (y ◇ (w ◇ y))) ◇ x
equation 34275 := x = ((y ◇ z) ◇ (y ◇ (w ◇ y))) ◇ y
equation 34276 := x = ((y ◇ z) ◇ (y ◇ (w ◇ y))) ◇ z
equation 34277 := x = ((y ◇ z) ◇ (y ◇ (w ◇ y))) ◇ w
equation 34278 := x = ((y ◇ z) ◇ (y ◇ (w ◇ y))) ◇ u
equation 34279 := x = ((y ◇ z) ◇ (y ◇ (w ◇ z))) ◇ x
equation 34280 := x = ((y ◇ z) ◇ (y ◇ (w ◇ z))) ◇ y
equation 34281 := x = ((y ◇ z) ◇ (y ◇ (w ◇ z))) ◇ z
equation 34282 := x = ((y ◇ z) ◇ (y ◇ (w ◇ z))) ◇ w
equation 34283 := x = ((y ◇ z) ◇ (y ◇ (w ◇ z))) ◇ u
equation 34284 := x = ((y ◇ z) ◇ (y ◇ (w ◇ w))) ◇ x
equation 34285 := x = ((y ◇ z) ◇ (y ◇ (w ◇ w))) ◇ y
equation 34286 := x = ((y ◇ z) ◇ (y ◇ (w ◇ w))) ◇ z
equation 34287 := x = ((y ◇ z) ◇ (y ◇ (w ◇ w))) ◇ w
equation 34288 := x = ((y ◇ z) ◇ (y ◇ (w ◇ w))) ◇ u
equation 34289 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ x
equation 34290 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ y
equation 34291 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ z
equation 34292 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ w
equation 34293 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ u
equation 34294 := x = ((y ◇ z) ◇ (y ◇ (w ◇ u))) ◇ v
equation 34295 := x = ((y ◇ z) ◇ (z ◇ (x ◇ x))) ◇ x
equation 34296 := x = ((y ◇ z) ◇ (z ◇ (x ◇ x))) ◇ y
equation 34297 := x = ((y ◇ z) ◇ (z ◇ (x ◇ x))) ◇ z
equation 34298 := x = ((y ◇ z) ◇ (z ◇ (x ◇ x))) ◇ w
equation 34299 := x = ((y ◇ z) ◇ (z ◇ (x ◇ y))) ◇ x
equation 34300 := x = ((y ◇ z) ◇ (z ◇ (x ◇ y))) ◇ y
equation 34301 := x = ((y ◇ z) ◇ (z ◇ (x ◇ y))) ◇ z
equation 34302 := x = ((y ◇ z) ◇ (z ◇ (x ◇ y))) ◇ w
equation 34303 := x = ((y ◇ z) ◇ (z ◇ (x ◇ z))) ◇ x
equation 34304 := x = ((y ◇ z) ◇ (z ◇ (x ◇ z))) ◇ y
equation 34305 := x = ((y ◇ z) ◇ (z ◇ (x ◇ z))) ◇ z
equation 34306 := x = ((y ◇ z) ◇ (z ◇ (x ◇ z))) ◇ w
equation 34307 := x = ((y ◇ z) ◇ (z ◇ (x ◇ w))) ◇ x
equation 34308 := x = ((y ◇ z) ◇ (z ◇ (x ◇ w))) ◇ y
equation 34309 := x = ((y ◇ z) ◇ (z ◇ (x ◇ w))) ◇ z
equation 34310 := x = ((y ◇ z) ◇ (z ◇ (x ◇ w))) ◇ w
equation 34311 := x = ((y ◇ z) ◇ (z ◇ (x ◇ w))) ◇ u
equation 34312 := x = ((y ◇ z) ◇ (z ◇ (y ◇ x))) ◇ x
equation 34313 := x = ((y ◇ z) ◇ (z ◇ (y ◇ x))) ◇ y
equation 34314 := x = ((y ◇ z) ◇ (z ◇ (y ◇ x))) ◇ z
equation 34315 := x = ((y ◇ z) ◇ (z ◇ (y ◇ x))) ◇ w
equation 34316 := x = ((y ◇ z) ◇ (z ◇ (y ◇ y))) ◇ x
equation 34317 := x = ((y ◇ z) ◇ (z ◇ (y ◇ y))) ◇ y
equation 34318 := x = ((y ◇ z) ◇ (z ◇ (y ◇ y))) ◇ z
equation 34319 := x = ((y ◇ z) ◇ (z ◇ (y ◇ y))) ◇ w
equation 34320 := x = ((y ◇ z) ◇ (z ◇ (y ◇ z))) ◇ x
equation 34321 := x = ((y ◇ z) ◇ (z ◇ (y ◇ z))) ◇ y
equation 34322 := x = ((y ◇ z) ◇ (z ◇ (y ◇ z))) ◇ z
equation 34323 := x = ((y ◇ z) ◇ (z ◇ (y ◇ z))) ◇ w
equation 34324 := x = ((y ◇ z) ◇ (z ◇ (y ◇ w))) ◇ x
equation 34325 := x = ((y ◇ z) ◇ (z ◇ (y ◇ w))) ◇ y
equation 34326 := x = ((y ◇ z) ◇ (z ◇ (y ◇ w))) ◇ z
equation 34327 := x = ((y ◇ z) ◇ (z ◇ (y ◇ w))) ◇ w
equation 34328 := x = ((y ◇ z) ◇ (z ◇ (y ◇ w))) ◇ u
equation 34329 := x = ((y ◇ z) ◇ (z ◇ (z ◇ x))) ◇ x
equation 34330 := x = ((y ◇ z) ◇ (z ◇ (z ◇ x))) ◇ y
equation 34331 := x = ((y ◇ z) ◇ (z ◇ (z ◇ x))) ◇ z
equation 34332 := x = ((y ◇ z) ◇ (z ◇ (z ◇ x))) ◇ w
equation 34333 := x = ((y ◇ z) ◇ (z ◇ (z ◇ y))) ◇ x
equation 34334 := x = ((y ◇ z) ◇ (z ◇ (z ◇ y))) ◇ y
equation 34335 := x = ((y ◇ z) ◇ (z ◇ (z ◇ y))) ◇ z
equation 34336 := x = ((y ◇ z) ◇ (z ◇ (z ◇ y))) ◇ w
equation 34337 := x = ((y ◇ z) ◇ (z ◇ (z ◇ z))) ◇ x
equation 34338 := x = ((y ◇ z) ◇ (z ◇ (z ◇ z))) ◇ y
equation 34339 := x = ((y ◇ z) ◇ (z ◇ (z ◇ z))) ◇ z
equation 34340 := x = ((y ◇ z) ◇ (z ◇ (z ◇ z))) ◇ w
equation 34341 := x = ((y ◇ z) ◇ (z ◇ (z ◇ w))) ◇ x
equation 34342 := x = ((y ◇ z) ◇ (z ◇ (z ◇ w))) ◇ y
equation 34343 := x = ((y ◇ z) ◇ (z ◇ (z ◇ w))) ◇ z
equation 34344 := x = ((y ◇ z) ◇ (z ◇ (z ◇ w))) ◇ w
equation 34345 := x = ((y ◇ z) ◇ (z ◇ (z ◇ w))) ◇ u
equation 34346 := x = ((y ◇ z) ◇ (z ◇ (w ◇ x))) ◇ x
equation 34347 := x = ((y ◇ z) ◇ (z ◇ (w ◇ x))) ◇ y
equation 34348 := x = ((y ◇ z) ◇ (z ◇ (w ◇ x))) ◇ z
equation 34349 := x = ((y ◇ z) ◇ (z ◇ (w ◇ x))) ◇ w
equation 34350 := x = ((y ◇ z) ◇ (z ◇ (w ◇ x))) ◇ u
equation 34351 := x = ((y ◇ z) ◇ (z ◇ (w ◇ y))) ◇ x
equation 34352 := x = ((y ◇ z) ◇ (z ◇ (w ◇ y))) ◇ y
equation 34353 := x = ((y ◇ z) ◇ (z ◇ (w ◇ y))) ◇ z
equation 34354 := x = ((y ◇ z) ◇ (z ◇ (w ◇ y))) ◇ w
equation 34355 := x = ((y ◇ z) ◇ (z ◇ (w ◇ y))) ◇ u
equation 34356 := x = ((y ◇ z) ◇ (z ◇ (w ◇ z))) ◇ x
equation 34357 := x = ((y ◇ z) ◇ (z ◇ (w ◇ z))) ◇ y
equation 34358 := x = ((y ◇ z) ◇ (z ◇ (w ◇ z))) ◇ z
equation 34359 := x = ((y ◇ z) ◇ (z ◇ (w ◇ z))) ◇ w
equation 34360 := x = ((y ◇ z) ◇ (z ◇ (w ◇ z))) ◇ u
equation 34361 := x = ((y ◇ z) ◇ (z ◇ (w ◇ w))) ◇ x
equation 34362 := x = ((y ◇ z) ◇ (z ◇ (w ◇ w))) ◇ y
equation 34363 := x = ((y ◇ z) ◇ (z ◇ (w ◇ w))) ◇ z
equation 34364 := x = ((y ◇ z) ◇ (z ◇ (w ◇ w))) ◇ w
equation 34365 := x = ((y ◇ z) ◇ (z ◇ (w ◇ w))) ◇ u
equation 34366 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ x
equation 34367 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ y
equation 34368 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ z
equation 34369 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ w
equation 34370 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ u
equation 34371 := x = ((y ◇ z) ◇ (z ◇ (w ◇ u))) ◇ v
equation 34372 := x = ((y ◇ z) ◇ (w ◇ (x ◇ x))) ◇ x
equation 34373 := x = ((y ◇ z) ◇ (w ◇ (x ◇ x))) ◇ y
equation 34374 := x = ((y ◇ z) ◇ (w ◇ (x ◇ x))) ◇ z
equation 34375 := x = ((y ◇ z) ◇ (w ◇ (x ◇ x))) ◇ w
equation 34376 := x = ((y ◇ z) ◇ (w ◇ (x ◇ x))) ◇ u
equation 34377 := x = ((y ◇ z) ◇ (w ◇ (x ◇ y))) ◇ x
equation 34378 := x = ((y ◇ z) ◇ (w ◇ (x ◇ y))) ◇ y
equation 34379 := x = ((y ◇ z) ◇ (w ◇ (x ◇ y))) ◇ z
equation 34380 := x = ((y ◇ z) ◇ (w ◇ (x ◇ y))) ◇ w
equation 34381 := x = ((y ◇ z) ◇ (w ◇ (x ◇ y))) ◇ u
equation 34382 := x = ((y ◇ z) ◇ (w ◇ (x ◇ z))) ◇ x
equation 34383 := x = ((y ◇ z) ◇ (w ◇ (x ◇ z))) ◇ y
equation 34384 := x = ((y ◇ z) ◇ (w ◇ (x ◇ z))) ◇ z
equation 34385 := x = ((y ◇ z) ◇ (w ◇ (x ◇ z))) ◇ w
equation 34386 := x = ((y ◇ z) ◇ (w ◇ (x ◇ z))) ◇ u
equation 34387 := x = ((y ◇ z) ◇ (w ◇ (x ◇ w))) ◇ x
equation 34388 := x = ((y ◇ z) ◇ (w ◇ (x ◇ w))) ◇ y
equation 34389 := x = ((y ◇ z) ◇ (w ◇ (x ◇ w))) ◇ z
equation 34390 := x = ((y ◇ z) ◇ (w ◇ (x ◇ w))) ◇ w
equation 34391 := x = ((y ◇ z) ◇ (w ◇ (x ◇ w))) ◇ u
equation 34392 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ x
equation 34393 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ y
equation 34394 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ z
equation 34395 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ w
equation 34396 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ u
equation 34397 := x = ((y ◇ z) ◇ (w ◇ (x ◇ u))) ◇ v
equation 34398 := x = ((y ◇ z) ◇ (w ◇ (y ◇ x))) ◇ x
equation 34399 := x = ((y ◇ z) ◇ (w ◇ (y ◇ x))) ◇ y
equation 34400 := x = ((y ◇ z) ◇ (w ◇ (y ◇ x))) ◇ z
equation 34401 := x = ((y ◇ z) ◇ (w ◇ (y ◇ x))) ◇ w
equation 34402 := x = ((y ◇ z) ◇ (w ◇ (y ◇ x))) ◇ u
equation 34403 := x = ((y ◇ z) ◇ (w ◇ (y ◇ y))) ◇ x
equation 34404 := x = ((y ◇ z) ◇ (w ◇ (y ◇ y))) ◇ y
equation 34405 := x = ((y ◇ z) ◇ (w ◇ (y ◇ y))) ◇ z
equation 34406 := x = ((y ◇ z) ◇ (w ◇ (y ◇ y))) ◇ w
equation 34407 := x = ((y ◇ z) ◇ (w ◇ (y ◇ y))) ◇ u
equation 34408 := x = ((y ◇ z) ◇ (w ◇ (y ◇ z))) ◇ x
equation 34409 := x = ((y ◇ z) ◇ (w ◇ (y ◇ z))) ◇ y
equation 34410 := x = ((y ◇ z) ◇ (w ◇ (y ◇ z))) ◇ z
equation 34411 := x = ((y ◇ z) ◇ (w ◇ (y ◇ z))) ◇ w
equation 34412 := x = ((y ◇ z) ◇ (w ◇ (y ◇ z))) ◇ u
equation 34413 := x = ((y ◇ z) ◇ (w ◇ (y ◇ w))) ◇ x
equation 34414 := x = ((y ◇ z) ◇ (w ◇ (y ◇ w))) ◇ y
equation 34415 := x = ((y ◇ z) ◇ (w ◇ (y ◇ w))) ◇ z
equation 34416 := x = ((y ◇ z) ◇ (w ◇ (y ◇ w))) ◇ w
equation 34417 := x = ((y ◇ z) ◇ (w ◇ (y ◇ w))) ◇ u
equation 34418 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ x
equation 34419 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ y
equation 34420 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ z
equation 34421 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ w
equation 34422 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ u
equation 34423 := x = ((y ◇ z) ◇ (w ◇ (y ◇ u))) ◇ v
equation 34424 := x = ((y ◇ z) ◇ (w ◇ (z ◇ x))) ◇ x
equation 34425 := x = ((y ◇ z) ◇ (w ◇ (z ◇ x))) ◇ y
equation 34426 := x = ((y ◇ z) ◇ (w ◇ (z ◇ x))) ◇ z
equation 34427 := x = ((y ◇ z) ◇ (w ◇ (z ◇ x))) ◇ w
equation 34428 := x = ((y ◇ z) ◇ (w ◇ (z ◇ x))) ◇ u
equation 34429 := x = ((y ◇ z) ◇ (w ◇ (z ◇ y))) ◇ x
equation 34430 := x = ((y ◇ z) ◇ (w ◇ (z ◇ y))) ◇ y
equation 34431 := x = ((y ◇ z) ◇ (w ◇ (z ◇ y))) ◇ z
equation 34432 := x = ((y ◇ z) ◇ (w ◇ (z ◇ y))) ◇ w
equation 34433 := x = ((y ◇ z) ◇ (w ◇ (z ◇ y))) ◇ u
equation 34434 := x = ((y ◇ z) ◇ (w ◇ (z ◇ z))) ◇ x
equation 34435 := x = ((y ◇ z) ◇ (w ◇ (z ◇ z))) ◇ y
equation 34436 := x = ((y ◇ z) ◇ (w ◇ (z ◇ z))) ◇ z
equation 34437 := x = ((y ◇ z) ◇ (w ◇ (z ◇ z))) ◇ w
equation 34438 := x = ((y ◇ z) ◇ (w ◇ (z ◇ z))) ◇ u
equation 34439 := x = ((y ◇ z) ◇ (w ◇ (z ◇ w))) ◇ x
equation 34440 := x = ((y ◇ z) ◇ (w ◇ (z ◇ w))) ◇ y
equation 34441 := x = ((y ◇ z) ◇ (w ◇ (z ◇ w))) ◇ z
equation 34442 := x = ((y ◇ z) ◇ (w ◇ (z ◇ w))) ◇ w
equation 34443 := x = ((y ◇ z) ◇ (w ◇ (z ◇ w))) ◇ u
equation 34444 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ x
equation 34445 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ y
equation 34446 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ z
equation 34447 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ w
equation 34448 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ u
equation 34449 := x = ((y ◇ z) ◇ (w ◇ (z ◇ u))) ◇ v
equation 34450 := x = ((y ◇ z) ◇ (w ◇ (w ◇ x))) ◇ x
equation 34451 := x = ((y ◇ z) ◇ (w ◇ (w ◇ x))) ◇ y
equation 34452 := x = ((y ◇ z) ◇ (w ◇ (w ◇ x))) ◇ z
equation 34453 := x = ((y ◇ z) ◇ (w ◇ (w ◇ x))) ◇ w
equation 34454 := x = ((y ◇ z) ◇ (w ◇ (w ◇ x))) ◇ u
equation 34455 := x = ((y ◇ z) ◇ (w ◇ (w ◇ y))) ◇ x
equation 34456 := x = ((y ◇ z) ◇ (w ◇ (w ◇ y))) ◇ y
equation 34457 := x = ((y ◇ z) ◇ (w ◇ (w ◇ y))) ◇ z
equation 34458 := x = ((y ◇ z) ◇ (w ◇ (w ◇ y))) ◇ w
equation 34459 := x = ((y ◇ z) ◇ (w ◇ (w ◇ y))) ◇ u
equation 34460 := x = ((y ◇ z) ◇ (w ◇ (w ◇ z))) ◇ x
equation 34461 := x = ((y ◇ z) ◇ (w ◇ (w ◇ z))) ◇ y
equation 34462 := x = ((y ◇ z) ◇ (w ◇ (w ◇ z))) ◇ z
equation 34463 := x = ((y ◇ z) ◇ (w ◇ (w ◇ z))) ◇ w
equation 34464 := x = ((y ◇ z) ◇ (w ◇ (w ◇ z))) ◇ u
equation 34465 := x = ((y ◇ z) ◇ (w ◇ (w ◇ w))) ◇ x
equation 34466 := x = ((y ◇ z) ◇ (w ◇ (w ◇ w))) ◇ y
equation 34467 := x = ((y ◇ z) ◇ (w ◇ (w ◇ w))) ◇ z
equation 34468 := x = ((y ◇ z) ◇ (w ◇ (w ◇ w))) ◇ w
equation 34469 := x = ((y ◇ z) ◇ (w ◇ (w ◇ w))) ◇ u
equation 34470 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ x
equation 34471 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ y
equation 34472 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ z
equation 34473 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ w
equation 34474 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ u
equation 34475 := x = ((y ◇ z) ◇ (w ◇ (w ◇ u))) ◇ v
equation 34476 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ x
equation 34477 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ y
equation 34478 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ z
equation 34479 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ w
equation 34480 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ u
equation 34481 := x = ((y ◇ z) ◇ (w ◇ (u ◇ x))) ◇ v
equation 34482 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ x
equation 34483 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ y
equation 34484 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ z
equation 34485 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ w
equation 34486 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ u
equation 34487 := x = ((y ◇ z) ◇ (w ◇ (u ◇ y))) ◇ v
equation 34488 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ x
equation 34489 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ y
equation 34490 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ z
equation 34491 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ w
equation 34492 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ u
equation 34493 := x = ((y ◇ z) ◇ (w ◇ (u ◇ z))) ◇ v
equation 34494 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ x
equation 34495 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ y
equation 34496 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ z
equation 34497 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ w
equation 34498 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ u
equation 34499 := x = ((y ◇ z) ◇ (w ◇ (u ◇ w))) ◇ v
equation 34500 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ x
equation 34501 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ y
equation 34502 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ z
equation 34503 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ w
equation 34504 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ u
equation 34505 := x = ((y ◇ z) ◇ (w ◇ (u ◇ u))) ◇ v
equation 34506 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ x
equation 34507 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ y
equation 34508 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ z
equation 34509 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ w
equation 34510 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ u
equation 34511 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ v
equation 34512 := x = ((y ◇ z) ◇ (w ◇ (u ◇ v))) ◇ r
equation 34513 := x = ((x ◇ x) ◇ ((x ◇ x) ◇ x)) ◇ x
equation 34514 := x = ((x ◇ x) ◇ ((x ◇ x) ◇ x)) ◇ y
equation 34515 := x = ((x ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ x
equation 34516 := x = ((x ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ y
equation 34517 := x = ((x ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ z
equation 34518 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ x
equation 34519 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ y
equation 34520 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ z
equation 34521 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ x
equation 34522 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ y
equation 34523 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ z
equation 34524 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ x
equation 34525 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ y
equation 34526 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ z
equation 34527 := x = ((x ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ w
equation 34528 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ x
equation 34529 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ y
equation 34530 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ z
equation 34531 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ x
equation 34532 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ y
equation 34533 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ z
equation 34534 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ x
equation 34535 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ y
equation 34536 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ z
equation 34537 := x = ((x ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ w
equation 34538 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ x
equation 34539 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ y
equation 34540 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ z
equation 34541 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ x
equation 34542 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ y
equation 34543 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ z
equation 34544 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ x
equation 34545 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ y
equation 34546 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ z
equation 34547 := x = ((x ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ w
equation 34548 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ x
equation 34549 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ y
equation 34550 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ z
equation 34551 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ w
equation 34552 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ x
equation 34553 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ y
equation 34554 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ z
equation 34555 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ w
equation 34556 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ x
equation 34557 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ y
equation 34558 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ z
equation 34559 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ w
equation 34560 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ x
equation 34561 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ y
equation 34562 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ z
equation 34563 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ w
equation 34564 := x = ((x ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ u
equation 34565 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ x
equation 34566 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ y
equation 34567 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ z
equation 34568 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ x
equation 34569 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ y
equation 34570 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ z
equation 34571 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ x
equation 34572 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ y
equation 34573 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ z
equation 34574 := x = ((x ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ w
equation 34575 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ x
equation 34576 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ y
equation 34577 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ z
equation 34578 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ x
equation 34579 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ y
equation 34580 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ z
equation 34581 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ x
equation 34582 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ y
equation 34583 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ z
equation 34584 := x = ((x ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ w
equation 34585 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ x
equation 34586 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ y
equation 34587 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ z
equation 34588 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ w
equation 34589 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ x
equation 34590 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ y
equation 34591 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ z
equation 34592 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ w
equation 34593 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ x
equation 34594 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ y
equation 34595 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ z
equation 34596 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ w
equation 34597 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ x
equation 34598 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ y
equation 34599 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ z
equation 34600 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ w
equation 34601 := x = ((x ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ u
equation 34602 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ x
equation 34603 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ y
equation 34604 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ z
equation 34605 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ x
equation 34606 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ y
equation 34607 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ z
equation 34608 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ x
equation 34609 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ y
equation 34610 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ z
equation 34611 := x = ((x ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ w
equation 34612 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ x
equation 34613 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ y
equation 34614 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ z
equation 34615 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ x
equation 34616 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ y
equation 34617 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ z
equation 34618 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ x
equation 34619 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ y
equation 34620 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ z
equation 34621 := x = ((x ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ w
equation 34622 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ x
equation 34623 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ y
equation 34624 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ z
equation 34625 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ w
equation 34626 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ x
equation 34627 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ y
equation 34628 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ z
equation 34629 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ w
equation 34630 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ x
equation 34631 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ y
equation 34632 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ z
equation 34633 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ w
equation 34634 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ x
equation 34635 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ y
equation 34636 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ z
equation 34637 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ w
equation 34638 := x = ((x ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ u
equation 34639 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ x
equation 34640 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ y
equation 34641 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ z
equation 34642 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ w
equation 34643 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ x
equation 34644 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ y
equation 34645 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ z
equation 34646 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ w
equation 34647 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ x
equation 34648 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ y
equation 34649 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ z
equation 34650 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ w
equation 34651 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ x
equation 34652 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ y
equation 34653 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ z
equation 34654 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ w
equation 34655 := x = ((x ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ u
equation 34656 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ x
equation 34657 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ y
equation 34658 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ z
equation 34659 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ w
equation 34660 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ x
equation 34661 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ y
equation 34662 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ z
equation 34663 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ w
equation 34664 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ x
equation 34665 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ y
equation 34666 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ z
equation 34667 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ w
equation 34668 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ x
equation 34669 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ y
equation 34670 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ z
equation 34671 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ w
equation 34672 := x = ((x ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ u
equation 34673 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ x
equation 34674 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ y
equation 34675 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ z
equation 34676 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ w
equation 34677 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ x
equation 34678 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ y
equation 34679 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ z
equation 34680 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ w
equation 34681 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ x
equation 34682 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ y
equation 34683 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ z
equation 34684 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ w
equation 34685 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ x
equation 34686 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ y
equation 34687 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ z
equation 34688 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ w
equation 34689 := x = ((x ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ u
equation 34690 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ x
equation 34691 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ y
equation 34692 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ z
equation 34693 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ w
equation 34694 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ u
equation 34695 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ x
equation 34696 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ y
equation 34697 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ z
equation 34698 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ w
equation 34699 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ u
equation 34700 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ x
equation 34701 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ y
equation 34702 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ z
equation 34703 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ w
equation 34704 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ z)) ◇ u
equation 34705 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ x
equation 34706 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ y
equation 34707 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ z
equation 34708 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ w
equation 34709 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ w)) ◇ u
equation 34710 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ x
equation 34711 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ y
equation 34712 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ z
equation 34713 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ w
equation 34714 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ u
equation 34715 := x = ((x ◇ y) ◇ ((z ◇ w) ◇ u)) ◇ v
equation 34716 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ x)) ◇ x
equation 34717 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ x)) ◇ y
equation 34718 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ x)) ◇ z
equation 34719 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ x
equation 34720 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ y
equation 34721 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ y)) ◇ z
equation 34722 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ z)) ◇ x
equation 34723 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ z)) ◇ y
equation 34724 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ z)) ◇ z
equation 34725 := x = ((y ◇ x) ◇ ((x ◇ x) ◇ z)) ◇ w
equation 34726 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ x
equation 34727 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ y
equation 34728 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ x)) ◇ z
equation 34729 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ x
equation 34730 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ y
equation 34731 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ y)) ◇ z
equation 34732 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ x
equation 34733 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ y
equation 34734 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ z
equation 34735 := x = ((y ◇ x) ◇ ((x ◇ y) ◇ z)) ◇ w
equation 34736 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ x)) ◇ x
equation 34737 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ x)) ◇ y
equation 34738 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ x)) ◇ z
equation 34739 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ x)) ◇ w
equation 34740 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ y)) ◇ x
equation 34741 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ y)) ◇ y
equation 34742 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ y)) ◇ z
equation 34743 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ y)) ◇ w
equation 34744 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ z)) ◇ x
equation 34745 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ z)) ◇ y
equation 34746 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ z)) ◇ z
equation 34747 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ z)) ◇ w
equation 34748 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ w)) ◇ x
equation 34749 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ w)) ◇ y
equation 34750 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ w)) ◇ z
equation 34751 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ w)) ◇ w
equation 34752 := x = ((y ◇ x) ◇ ((x ◇ z) ◇ w)) ◇ u
equation 34753 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ x
equation 34754 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ y
equation 34755 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ x)) ◇ z
equation 34756 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ x
equation 34757 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ y
equation 34758 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ y)) ◇ z
equation 34759 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ x
equation 34760 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ y
equation 34761 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ z
equation 34762 := x = ((y ◇ x) ◇ ((y ◇ x) ◇ z)) ◇ w
equation 34763 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ x
equation 34764 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ y
equation 34765 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ x)) ◇ z
equation 34766 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ x
equation 34767 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ y
equation 34768 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ y)) ◇ z
equation 34769 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ x
equation 34770 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ y
equation 34771 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ z
equation 34772 := x = ((y ◇ x) ◇ ((y ◇ y) ◇ z)) ◇ w
equation 34773 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ x
equation 34774 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ y
equation 34775 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ z
equation 34776 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ x)) ◇ w
equation 34777 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ x
equation 34778 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ y
equation 34779 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ z
equation 34780 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ y)) ◇ w
equation 34781 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ x
equation 34782 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ y
equation 34783 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ z
equation 34784 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ z)) ◇ w
equation 34785 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ x
equation 34786 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ y
equation 34787 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ z
equation 34788 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ w
equation 34789 := x = ((y ◇ x) ◇ ((y ◇ z) ◇ w)) ◇ u
equation 34790 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ x)) ◇ x
equation 34791 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ x)) ◇ y
equation 34792 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ x)) ◇ z
equation 34793 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ x)) ◇ w
equation 34794 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ y)) ◇ x
equation 34795 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ y)) ◇ y
equation 34796 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ y)) ◇ z
equation 34797 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ y)) ◇ w
equation 34798 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ z)) ◇ x
equation 34799 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ z)) ◇ y
equation 34800 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ z)) ◇ z
equation 34801 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ z)) ◇ w
equation 34802 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ w)) ◇ x
equation 34803 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ w)) ◇ y
equation 34804 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ w)) ◇ z
equation 34805 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ w)) ◇ w
equation 34806 := x = ((y ◇ x) ◇ ((z ◇ x) ◇ w)) ◇ u
equation 34807 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ x)) ◇ x
equation 34808 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ x)) ◇ y
equation 34809 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ x)) ◇ z
equation 34810 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ x)) ◇ w
equation 34811 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ y)) ◇ x
equation 34812 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ y)) ◇ y
equation 34813 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ y)) ◇ z
equation 34814 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ y)) ◇ w
equation 34815 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ z)) ◇ x
equation 34816 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ z)) ◇ y
equation 34817 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ z)) ◇ z
equation 34818 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ z)) ◇ w
equation 34819 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ w)) ◇ x
equation 34820 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ w)) ◇ y
equation 34821 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ w)) ◇ z
equation 34822 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ w)) ◇ w
equation 34823 := x = ((y ◇ x) ◇ ((z ◇ y) ◇ w)) ◇ u
equation 34824 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ x)) ◇ x
equation 34825 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ x)) ◇ y
equation 34826 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ x)) ◇ z
equation 34827 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ x)) ◇ w
equation 34828 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ y)) ◇ x
equation 34829 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ y)) ◇ y
equation 34830 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ y)) ◇ z
equation 34831 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ y)) ◇ w
equation 34832 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ z)) ◇ x
equation 34833 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ z)) ◇ y
equation 34834 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ z)) ◇ z
equation 34835 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ z)) ◇ w
equation 34836 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ w)) ◇ x
equation 34837 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ w)) ◇ y
equation 34838 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ w)) ◇ z
equation 34839 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ w)) ◇ w
equation 34840 := x = ((y ◇ x) ◇ ((z ◇ z) ◇ w)) ◇ u
equation 34841 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ x)) ◇ x
equation 34842 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ x)) ◇ y
equation 34843 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ x)) ◇ z
equation 34844 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ x)) ◇ w
equation 34845 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ x)) ◇ u
equation 34846 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ y)) ◇ x
equation 34847 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ y)) ◇ y
equation 34848 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ y)) ◇ z
equation 34849 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ y)) ◇ w
equation 34850 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ y)) ◇ u
equation 34851 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ z)) ◇ x
equation 34852 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ z)) ◇ y
equation 34853 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ z)) ◇ z
equation 34854 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ z)) ◇ w
equation 34855 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ z)) ◇ u
equation 34856 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ w)) ◇ x
equation 34857 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ w)) ◇ y
equation 34858 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ w)) ◇ z
equation 34859 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ w)) ◇ w
equation 34860 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ w)) ◇ u
equation 34861 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ x
equation 34862 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ y
equation 34863 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ z
equation 34864 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ w
equation 34865 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ u
equation 34866 := x = ((y ◇ x) ◇ ((z ◇ w) ◇ u)) ◇ v
equation 34867 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ x
equation 34868 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ y
equation 34869 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ x)) ◇ z
equation 34870 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ x
equation 34871 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ y
equation 34872 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ y)) ◇ z
equation 34873 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ x
equation 34874 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ y
equation 34875 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ z
equation 34876 := x = ((y ◇ y) ◇ ((x ◇ x) ◇ z)) ◇ w
equation 34877 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ x
equation 34878 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ y
equation 34879 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ x)) ◇ z
equation 34880 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ x
equation 34881 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ y
equation 34882 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ y)) ◇ z
equation 34883 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ x
equation 34884 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ y
equation 34885 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ z
equation 34886 := x = ((y ◇ y) ◇ ((x ◇ y) ◇ z)) ◇ w
equation 34887 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ x
equation 34888 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ y
equation 34889 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ z
equation 34890 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ x)) ◇ w
equation 34891 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ x
equation 34892 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ y
equation 34893 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ z
equation 34894 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ y)) ◇ w
equation 34895 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ x
equation 34896 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ y
equation 34897 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ z
equation 34898 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ z)) ◇ w
equation 34899 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ x
equation 34900 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ y
equation 34901 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ z
equation 34902 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ w
equation 34903 := x = ((y ◇ y) ◇ ((x ◇ z) ◇ w)) ◇ u
equation 34904 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ x
equation 34905 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ y
equation 34906 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ x)) ◇ z
equation 34907 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ x
equation 34908 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ y
equation 34909 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ y)) ◇ z
equation 34910 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ x
equation 34911 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ y
equation 34912 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ z
equation 34913 := x = ((y ◇ y) ◇ ((y ◇ x) ◇ z)) ◇ w
equation 34914 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ x
equation 34915 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ y
equation 34916 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ x)) ◇ z
equation 34917 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ x
equation 34918 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ y
equation 34919 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ y)) ◇ z
equation 34920 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ x
equation 34921 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ y
equation 34922 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ z
equation 34923 := x = ((y ◇ y) ◇ ((y ◇ y) ◇ z)) ◇ w
equation 34924 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ x
equation 34925 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ y
equation 34926 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ z
equation 34927 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ x)) ◇ w
equation 34928 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ x
equation 34929 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ y
equation 34930 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ z
equation 34931 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ y)) ◇ w
equation 34932 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ x
equation 34933 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ y
equation 34934 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ z
equation 34935 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ z)) ◇ w
equation 34936 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ x
equation 34937 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ y
equation 34938 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ z
equation 34939 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ w
equation 34940 := x = ((y ◇ y) ◇ ((y ◇ z) ◇ w)) ◇ u
equation 34941 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ x
equation 34942 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ y
equation 34943 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ z
equation 34944 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ x)) ◇ w
equation 34945 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ x
equation 34946 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ y
equation 34947 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ z
equation 34948 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ y)) ◇ w
equation 34949 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ x
equation 34950 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ y
equation 34951 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ z
equation 34952 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ z)) ◇ w
equation 34953 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ x
equation 34954 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ y
equation 34955 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ z
equation 34956 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ w
equation 34957 := x = ((y ◇ y) ◇ ((z ◇ x) ◇ w)) ◇ u
equation 34958 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ x
equation 34959 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ y
equation 34960 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ z
equation 34961 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ x)) ◇ w
equation 34962 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ x
equation 34963 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ y
equation 34964 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ z
equation 34965 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ y)) ◇ w
equation 34966 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ x
equation 34967 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ y
equation 34968 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ z
equation 34969 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ z)) ◇ w
equation 34970 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ x
equation 34971 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ y
equation 34972 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ z
equation 34973 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ w
equation 34974 := x = ((y ◇ y) ◇ ((z ◇ y) ◇ w)) ◇ u
equation 34975 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ x
equation 34976 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ y
equation 34977 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ z
equation 34978 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ x)) ◇ w
equation 34979 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ x
equation 34980 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ y
equation 34981 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ z
equation 34982 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ y)) ◇ w
equation 34983 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ x
equation 34984 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ y
equation 34985 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ z
equation 34986 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ z)) ◇ w
equation 34987 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ x
equation 34988 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ y
equation 34989 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ z
equation 34990 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ w
equation 34991 := x = ((y ◇ y) ◇ ((z ◇ z) ◇ w)) ◇ u
equation 34992 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ x
equation 34993 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ y
equation 34994 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ z
equation 34995 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ w
equation 34996 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ x)) ◇ u
equation 34997 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ x
equation 34998 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ y
equation 34999 := x = ((y ◇ y) ◇ ((z ◇ w) ◇ y)) ◇ z
