import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 61000-61999 -/

equation 61000 := (x ◇ x) ◇ y = (z ◇ (w ◇ x)) ◇ x
equation 61001 := (x ◇ x) ◇ y = (z ◇ (w ◇ x)) ◇ y
equation 61002 := (x ◇ x) ◇ y = (z ◇ (w ◇ x)) ◇ z
equation 61003 := (x ◇ x) ◇ y = (z ◇ (w ◇ x)) ◇ w
equation 61004 := (x ◇ x) ◇ y = (z ◇ (w ◇ x)) ◇ u
equation 61005 := (x ◇ x) ◇ y = (z ◇ (w ◇ y)) ◇ x
equation 61006 := (x ◇ x) ◇ y = (z ◇ (w ◇ y)) ◇ y
equation 61007 := (x ◇ x) ◇ y = (z ◇ (w ◇ y)) ◇ z
equation 61008 := (x ◇ x) ◇ y = (z ◇ (w ◇ y)) ◇ w
equation 61009 := (x ◇ x) ◇ y = (z ◇ (w ◇ y)) ◇ u
equation 61010 := (x ◇ x) ◇ y = (z ◇ (w ◇ z)) ◇ x
equation 61011 := (x ◇ x) ◇ y = (z ◇ (w ◇ z)) ◇ y
equation 61012 := (x ◇ x) ◇ y = (z ◇ (w ◇ z)) ◇ z
equation 61013 := (x ◇ x) ◇ y = (z ◇ (w ◇ z)) ◇ w
equation 61014 := (x ◇ x) ◇ y = (z ◇ (w ◇ z)) ◇ u
equation 61015 := (x ◇ x) ◇ y = (z ◇ (w ◇ w)) ◇ x
equation 61016 := (x ◇ x) ◇ y = (z ◇ (w ◇ w)) ◇ y
equation 61017 := (x ◇ x) ◇ y = (z ◇ (w ◇ w)) ◇ z
equation 61018 := (x ◇ x) ◇ y = (z ◇ (w ◇ w)) ◇ w
equation 61019 := (x ◇ x) ◇ y = (z ◇ (w ◇ w)) ◇ u
equation 61020 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ x
equation 61021 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ y
equation 61022 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ z
equation 61023 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ w
equation 61024 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ u
equation 61025 := (x ◇ x) ◇ y = (z ◇ (w ◇ u)) ◇ v
equation 61026 := (x ◇ y) ◇ x = (x ◇ (x ◇ x)) ◇ x
equation 61027 := (x ◇ y) ◇ x = (x ◇ (x ◇ x)) ◇ y
equation 61028 := (x ◇ y) ◇ x = (x ◇ (x ◇ x)) ◇ z
equation 61029 := (x ◇ y) ◇ x = (x ◇ (x ◇ y)) ◇ x
equation 61030 := (x ◇ y) ◇ x = (x ◇ (x ◇ y)) ◇ y
equation 61031 := (x ◇ y) ◇ x = (x ◇ (x ◇ y)) ◇ z
equation 61032 := (x ◇ y) ◇ x = (x ◇ (x ◇ z)) ◇ x
equation 61033 := (x ◇ y) ◇ x = (x ◇ (x ◇ z)) ◇ y
equation 61034 := (x ◇ y) ◇ x = (x ◇ (x ◇ z)) ◇ z
equation 61035 := (x ◇ y) ◇ x = (x ◇ (x ◇ z)) ◇ w
equation 61036 := (x ◇ y) ◇ x = (x ◇ (y ◇ x)) ◇ x
equation 61037 := (x ◇ y) ◇ x = (x ◇ (y ◇ x)) ◇ y
equation 61038 := (x ◇ y) ◇ x = (x ◇ (y ◇ x)) ◇ z
equation 61039 := (x ◇ y) ◇ x = (x ◇ (y ◇ y)) ◇ x
equation 61040 := (x ◇ y) ◇ x = (x ◇ (y ◇ y)) ◇ y
equation 61041 := (x ◇ y) ◇ x = (x ◇ (y ◇ y)) ◇ z
equation 61042 := (x ◇ y) ◇ x = (x ◇ (y ◇ z)) ◇ x
equation 61043 := (x ◇ y) ◇ x = (x ◇ (y ◇ z)) ◇ y
equation 61044 := (x ◇ y) ◇ x = (x ◇ (y ◇ z)) ◇ z
equation 61045 := (x ◇ y) ◇ x = (x ◇ (y ◇ z)) ◇ w
equation 61046 := (x ◇ y) ◇ x = (x ◇ (z ◇ x)) ◇ x
equation 61047 := (x ◇ y) ◇ x = (x ◇ (z ◇ x)) ◇ y
equation 61048 := (x ◇ y) ◇ x = (x ◇ (z ◇ x)) ◇ z
equation 61049 := (x ◇ y) ◇ x = (x ◇ (z ◇ x)) ◇ w
equation 61050 := (x ◇ y) ◇ x = (x ◇ (z ◇ y)) ◇ x
equation 61051 := (x ◇ y) ◇ x = (x ◇ (z ◇ y)) ◇ y
equation 61052 := (x ◇ y) ◇ x = (x ◇ (z ◇ y)) ◇ z
equation 61053 := (x ◇ y) ◇ x = (x ◇ (z ◇ y)) ◇ w
equation 61054 := (x ◇ y) ◇ x = (x ◇ (z ◇ z)) ◇ x
equation 61055 := (x ◇ y) ◇ x = (x ◇ (z ◇ z)) ◇ y
equation 61056 := (x ◇ y) ◇ x = (x ◇ (z ◇ z)) ◇ z
equation 61057 := (x ◇ y) ◇ x = (x ◇ (z ◇ z)) ◇ w
equation 61058 := (x ◇ y) ◇ x = (x ◇ (z ◇ w)) ◇ x
equation 61059 := (x ◇ y) ◇ x = (x ◇ (z ◇ w)) ◇ y
equation 61060 := (x ◇ y) ◇ x = (x ◇ (z ◇ w)) ◇ z
equation 61061 := (x ◇ y) ◇ x = (x ◇ (z ◇ w)) ◇ w
equation 61062 := (x ◇ y) ◇ x = (x ◇ (z ◇ w)) ◇ u
equation 61063 := (x ◇ y) ◇ x = (y ◇ (x ◇ x)) ◇ x
equation 61064 := (x ◇ y) ◇ x = (y ◇ (x ◇ x)) ◇ y
equation 61065 := (x ◇ y) ◇ x = (y ◇ (x ◇ x)) ◇ z
equation 61066 := (x ◇ y) ◇ x = (y ◇ (x ◇ y)) ◇ x
equation 61067 := (x ◇ y) ◇ x = (y ◇ (x ◇ y)) ◇ y
equation 61068 := (x ◇ y) ◇ x = (y ◇ (x ◇ y)) ◇ z
equation 61069 := (x ◇ y) ◇ x = (y ◇ (x ◇ z)) ◇ x
equation 61070 := (x ◇ y) ◇ x = (y ◇ (x ◇ z)) ◇ y
equation 61071 := (x ◇ y) ◇ x = (y ◇ (x ◇ z)) ◇ z
equation 61072 := (x ◇ y) ◇ x = (y ◇ (x ◇ z)) ◇ w
equation 61073 := (x ◇ y) ◇ x = (y ◇ (y ◇ x)) ◇ x
equation 61074 := (x ◇ y) ◇ x = (y ◇ (y ◇ x)) ◇ y
equation 61075 := (x ◇ y) ◇ x = (y ◇ (y ◇ x)) ◇ z
equation 61076 := (x ◇ y) ◇ x = (y ◇ (y ◇ y)) ◇ x
equation 61077 := (x ◇ y) ◇ x = (y ◇ (y ◇ y)) ◇ y
equation 61078 := (x ◇ y) ◇ x = (y ◇ (y ◇ y)) ◇ z
equation 61079 := (x ◇ y) ◇ x = (y ◇ (y ◇ z)) ◇ x
equation 61080 := (x ◇ y) ◇ x = (y ◇ (y ◇ z)) ◇ y
equation 61081 := (x ◇ y) ◇ x = (y ◇ (y ◇ z)) ◇ z
equation 61082 := (x ◇ y) ◇ x = (y ◇ (y ◇ z)) ◇ w
equation 61083 := (x ◇ y) ◇ x = (y ◇ (z ◇ x)) ◇ x
equation 61084 := (x ◇ y) ◇ x = (y ◇ (z ◇ x)) ◇ y
equation 61085 := (x ◇ y) ◇ x = (y ◇ (z ◇ x)) ◇ z
equation 61086 := (x ◇ y) ◇ x = (y ◇ (z ◇ x)) ◇ w
equation 61087 := (x ◇ y) ◇ x = (y ◇ (z ◇ y)) ◇ x
equation 61088 := (x ◇ y) ◇ x = (y ◇ (z ◇ y)) ◇ y
equation 61089 := (x ◇ y) ◇ x = (y ◇ (z ◇ y)) ◇ z
equation 61090 := (x ◇ y) ◇ x = (y ◇ (z ◇ y)) ◇ w
equation 61091 := (x ◇ y) ◇ x = (y ◇ (z ◇ z)) ◇ x
equation 61092 := (x ◇ y) ◇ x = (y ◇ (z ◇ z)) ◇ y
equation 61093 := (x ◇ y) ◇ x = (y ◇ (z ◇ z)) ◇ z
equation 61094 := (x ◇ y) ◇ x = (y ◇ (z ◇ z)) ◇ w
equation 61095 := (x ◇ y) ◇ x = (y ◇ (z ◇ w)) ◇ x
equation 61096 := (x ◇ y) ◇ x = (y ◇ (z ◇ w)) ◇ y
equation 61097 := (x ◇ y) ◇ x = (y ◇ (z ◇ w)) ◇ z
equation 61098 := (x ◇ y) ◇ x = (y ◇ (z ◇ w)) ◇ w
equation 61099 := (x ◇ y) ◇ x = (y ◇ (z ◇ w)) ◇ u
equation 61100 := (x ◇ y) ◇ x = (z ◇ (x ◇ x)) ◇ x
equation 61101 := (x ◇ y) ◇ x = (z ◇ (x ◇ x)) ◇ y
equation 61102 := (x ◇ y) ◇ x = (z ◇ (x ◇ x)) ◇ z
equation 61103 := (x ◇ y) ◇ x = (z ◇ (x ◇ x)) ◇ w
equation 61104 := (x ◇ y) ◇ x = (z ◇ (x ◇ y)) ◇ x
equation 61105 := (x ◇ y) ◇ x = (z ◇ (x ◇ y)) ◇ y
equation 61106 := (x ◇ y) ◇ x = (z ◇ (x ◇ y)) ◇ z
equation 61107 := (x ◇ y) ◇ x = (z ◇ (x ◇ y)) ◇ w
equation 61108 := (x ◇ y) ◇ x = (z ◇ (x ◇ z)) ◇ x
equation 61109 := (x ◇ y) ◇ x = (z ◇ (x ◇ z)) ◇ y
equation 61110 := (x ◇ y) ◇ x = (z ◇ (x ◇ z)) ◇ z
equation 61111 := (x ◇ y) ◇ x = (z ◇ (x ◇ z)) ◇ w
equation 61112 := (x ◇ y) ◇ x = (z ◇ (x ◇ w)) ◇ x
equation 61113 := (x ◇ y) ◇ x = (z ◇ (x ◇ w)) ◇ y
equation 61114 := (x ◇ y) ◇ x = (z ◇ (x ◇ w)) ◇ z
equation 61115 := (x ◇ y) ◇ x = (z ◇ (x ◇ w)) ◇ w
equation 61116 := (x ◇ y) ◇ x = (z ◇ (x ◇ w)) ◇ u
equation 61117 := (x ◇ y) ◇ x = (z ◇ (y ◇ x)) ◇ x
equation 61118 := (x ◇ y) ◇ x = (z ◇ (y ◇ x)) ◇ y
equation 61119 := (x ◇ y) ◇ x = (z ◇ (y ◇ x)) ◇ z
equation 61120 := (x ◇ y) ◇ x = (z ◇ (y ◇ x)) ◇ w
equation 61121 := (x ◇ y) ◇ x = (z ◇ (y ◇ y)) ◇ x
equation 61122 := (x ◇ y) ◇ x = (z ◇ (y ◇ y)) ◇ y
equation 61123 := (x ◇ y) ◇ x = (z ◇ (y ◇ y)) ◇ z
equation 61124 := (x ◇ y) ◇ x = (z ◇ (y ◇ y)) ◇ w
equation 61125 := (x ◇ y) ◇ x = (z ◇ (y ◇ z)) ◇ x
equation 61126 := (x ◇ y) ◇ x = (z ◇ (y ◇ z)) ◇ y
equation 61127 := (x ◇ y) ◇ x = (z ◇ (y ◇ z)) ◇ z
equation 61128 := (x ◇ y) ◇ x = (z ◇ (y ◇ z)) ◇ w
equation 61129 := (x ◇ y) ◇ x = (z ◇ (y ◇ w)) ◇ x
equation 61130 := (x ◇ y) ◇ x = (z ◇ (y ◇ w)) ◇ y
equation 61131 := (x ◇ y) ◇ x = (z ◇ (y ◇ w)) ◇ z
equation 61132 := (x ◇ y) ◇ x = (z ◇ (y ◇ w)) ◇ w
equation 61133 := (x ◇ y) ◇ x = (z ◇ (y ◇ w)) ◇ u
equation 61134 := (x ◇ y) ◇ x = (z ◇ (z ◇ x)) ◇ x
equation 61135 := (x ◇ y) ◇ x = (z ◇ (z ◇ x)) ◇ y
equation 61136 := (x ◇ y) ◇ x = (z ◇ (z ◇ x)) ◇ z
equation 61137 := (x ◇ y) ◇ x = (z ◇ (z ◇ x)) ◇ w
equation 61138 := (x ◇ y) ◇ x = (z ◇ (z ◇ y)) ◇ x
equation 61139 := (x ◇ y) ◇ x = (z ◇ (z ◇ y)) ◇ y
equation 61140 := (x ◇ y) ◇ x = (z ◇ (z ◇ y)) ◇ z
equation 61141 := (x ◇ y) ◇ x = (z ◇ (z ◇ y)) ◇ w
equation 61142 := (x ◇ y) ◇ x = (z ◇ (z ◇ z)) ◇ x
equation 61143 := (x ◇ y) ◇ x = (z ◇ (z ◇ z)) ◇ y
equation 61144 := (x ◇ y) ◇ x = (z ◇ (z ◇ z)) ◇ z
equation 61145 := (x ◇ y) ◇ x = (z ◇ (z ◇ z)) ◇ w
equation 61146 := (x ◇ y) ◇ x = (z ◇ (z ◇ w)) ◇ x
equation 61147 := (x ◇ y) ◇ x = (z ◇ (z ◇ w)) ◇ y
equation 61148 := (x ◇ y) ◇ x = (z ◇ (z ◇ w)) ◇ z
equation 61149 := (x ◇ y) ◇ x = (z ◇ (z ◇ w)) ◇ w
equation 61150 := (x ◇ y) ◇ x = (z ◇ (z ◇ w)) ◇ u
equation 61151 := (x ◇ y) ◇ x = (z ◇ (w ◇ x)) ◇ x
equation 61152 := (x ◇ y) ◇ x = (z ◇ (w ◇ x)) ◇ y
equation 61153 := (x ◇ y) ◇ x = (z ◇ (w ◇ x)) ◇ z
equation 61154 := (x ◇ y) ◇ x = (z ◇ (w ◇ x)) ◇ w
equation 61155 := (x ◇ y) ◇ x = (z ◇ (w ◇ x)) ◇ u
equation 61156 := (x ◇ y) ◇ x = (z ◇ (w ◇ y)) ◇ x
equation 61157 := (x ◇ y) ◇ x = (z ◇ (w ◇ y)) ◇ y
equation 61158 := (x ◇ y) ◇ x = (z ◇ (w ◇ y)) ◇ z
equation 61159 := (x ◇ y) ◇ x = (z ◇ (w ◇ y)) ◇ w
equation 61160 := (x ◇ y) ◇ x = (z ◇ (w ◇ y)) ◇ u
equation 61161 := (x ◇ y) ◇ x = (z ◇ (w ◇ z)) ◇ x
equation 61162 := (x ◇ y) ◇ x = (z ◇ (w ◇ z)) ◇ y
equation 61163 := (x ◇ y) ◇ x = (z ◇ (w ◇ z)) ◇ z
equation 61164 := (x ◇ y) ◇ x = (z ◇ (w ◇ z)) ◇ w
equation 61165 := (x ◇ y) ◇ x = (z ◇ (w ◇ z)) ◇ u
equation 61166 := (x ◇ y) ◇ x = (z ◇ (w ◇ w)) ◇ x
equation 61167 := (x ◇ y) ◇ x = (z ◇ (w ◇ w)) ◇ y
equation 61168 := (x ◇ y) ◇ x = (z ◇ (w ◇ w)) ◇ z
equation 61169 := (x ◇ y) ◇ x = (z ◇ (w ◇ w)) ◇ w
equation 61170 := (x ◇ y) ◇ x = (z ◇ (w ◇ w)) ◇ u
equation 61171 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ x
equation 61172 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ y
equation 61173 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ z
equation 61174 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ w
equation 61175 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ u
equation 61176 := (x ◇ y) ◇ x = (z ◇ (w ◇ u)) ◇ v
equation 61177 := (x ◇ y) ◇ y = (x ◇ (x ◇ x)) ◇ x
equation 61178 := (x ◇ y) ◇ y = (x ◇ (x ◇ x)) ◇ y
equation 61179 := (x ◇ y) ◇ y = (x ◇ (x ◇ x)) ◇ z
equation 61180 := (x ◇ y) ◇ y = (x ◇ (x ◇ y)) ◇ x
equation 61181 := (x ◇ y) ◇ y = (x ◇ (x ◇ y)) ◇ y
equation 61182 := (x ◇ y) ◇ y = (x ◇ (x ◇ y)) ◇ z
equation 61183 := (x ◇ y) ◇ y = (x ◇ (x ◇ z)) ◇ x
equation 61184 := (x ◇ y) ◇ y = (x ◇ (x ◇ z)) ◇ y
equation 61185 := (x ◇ y) ◇ y = (x ◇ (x ◇ z)) ◇ z
equation 61186 := (x ◇ y) ◇ y = (x ◇ (x ◇ z)) ◇ w
equation 61187 := (x ◇ y) ◇ y = (x ◇ (y ◇ x)) ◇ x
equation 61188 := (x ◇ y) ◇ y = (x ◇ (y ◇ x)) ◇ y
equation 61189 := (x ◇ y) ◇ y = (x ◇ (y ◇ x)) ◇ z
equation 61190 := (x ◇ y) ◇ y = (x ◇ (y ◇ y)) ◇ x
equation 61191 := (x ◇ y) ◇ y = (x ◇ (y ◇ y)) ◇ y
equation 61192 := (x ◇ y) ◇ y = (x ◇ (y ◇ y)) ◇ z
equation 61193 := (x ◇ y) ◇ y = (x ◇ (y ◇ z)) ◇ x
equation 61194 := (x ◇ y) ◇ y = (x ◇ (y ◇ z)) ◇ y
equation 61195 := (x ◇ y) ◇ y = (x ◇ (y ◇ z)) ◇ z
equation 61196 := (x ◇ y) ◇ y = (x ◇ (y ◇ z)) ◇ w
equation 61197 := (x ◇ y) ◇ y = (x ◇ (z ◇ x)) ◇ x
equation 61198 := (x ◇ y) ◇ y = (x ◇ (z ◇ x)) ◇ y
equation 61199 := (x ◇ y) ◇ y = (x ◇ (z ◇ x)) ◇ z
equation 61200 := (x ◇ y) ◇ y = (x ◇ (z ◇ x)) ◇ w
equation 61201 := (x ◇ y) ◇ y = (x ◇ (z ◇ y)) ◇ x
equation 61202 := (x ◇ y) ◇ y = (x ◇ (z ◇ y)) ◇ y
equation 61203 := (x ◇ y) ◇ y = (x ◇ (z ◇ y)) ◇ z
equation 61204 := (x ◇ y) ◇ y = (x ◇ (z ◇ y)) ◇ w
equation 61205 := (x ◇ y) ◇ y = (x ◇ (z ◇ z)) ◇ x
equation 61206 := (x ◇ y) ◇ y = (x ◇ (z ◇ z)) ◇ y
equation 61207 := (x ◇ y) ◇ y = (x ◇ (z ◇ z)) ◇ z
equation 61208 := (x ◇ y) ◇ y = (x ◇ (z ◇ z)) ◇ w
equation 61209 := (x ◇ y) ◇ y = (x ◇ (z ◇ w)) ◇ x
equation 61210 := (x ◇ y) ◇ y = (x ◇ (z ◇ w)) ◇ y
equation 61211 := (x ◇ y) ◇ y = (x ◇ (z ◇ w)) ◇ z
equation 61212 := (x ◇ y) ◇ y = (x ◇ (z ◇ w)) ◇ w
equation 61213 := (x ◇ y) ◇ y = (x ◇ (z ◇ w)) ◇ u
equation 61214 := (x ◇ y) ◇ y = (y ◇ (x ◇ x)) ◇ x
equation 61215 := (x ◇ y) ◇ y = (y ◇ (x ◇ x)) ◇ y
equation 61216 := (x ◇ y) ◇ y = (y ◇ (x ◇ x)) ◇ z
equation 61217 := (x ◇ y) ◇ y = (y ◇ (x ◇ y)) ◇ x
equation 61218 := (x ◇ y) ◇ y = (y ◇ (x ◇ y)) ◇ y
equation 61219 := (x ◇ y) ◇ y = (y ◇ (x ◇ y)) ◇ z
equation 61220 := (x ◇ y) ◇ y = (y ◇ (x ◇ z)) ◇ x
equation 61221 := (x ◇ y) ◇ y = (y ◇ (x ◇ z)) ◇ y
equation 61222 := (x ◇ y) ◇ y = (y ◇ (x ◇ z)) ◇ z
equation 61223 := (x ◇ y) ◇ y = (y ◇ (x ◇ z)) ◇ w
equation 61224 := (x ◇ y) ◇ y = (y ◇ (y ◇ x)) ◇ x
equation 61225 := (x ◇ y) ◇ y = (y ◇ (y ◇ x)) ◇ y
equation 61226 := (x ◇ y) ◇ y = (y ◇ (y ◇ x)) ◇ z
equation 61227 := (x ◇ y) ◇ y = (y ◇ (y ◇ y)) ◇ x
equation 61228 := (x ◇ y) ◇ y = (y ◇ (y ◇ y)) ◇ y
equation 61229 := (x ◇ y) ◇ y = (y ◇ (y ◇ y)) ◇ z
equation 61230 := (x ◇ y) ◇ y = (y ◇ (y ◇ z)) ◇ x
equation 61231 := (x ◇ y) ◇ y = (y ◇ (y ◇ z)) ◇ y
equation 61232 := (x ◇ y) ◇ y = (y ◇ (y ◇ z)) ◇ z
equation 61233 := (x ◇ y) ◇ y = (y ◇ (y ◇ z)) ◇ w
equation 61234 := (x ◇ y) ◇ y = (y ◇ (z ◇ x)) ◇ x
equation 61235 := (x ◇ y) ◇ y = (y ◇ (z ◇ x)) ◇ y
equation 61236 := (x ◇ y) ◇ y = (y ◇ (z ◇ x)) ◇ z
equation 61237 := (x ◇ y) ◇ y = (y ◇ (z ◇ x)) ◇ w
equation 61238 := (x ◇ y) ◇ y = (y ◇ (z ◇ y)) ◇ x
equation 61239 := (x ◇ y) ◇ y = (y ◇ (z ◇ y)) ◇ y
equation 61240 := (x ◇ y) ◇ y = (y ◇ (z ◇ y)) ◇ z
equation 61241 := (x ◇ y) ◇ y = (y ◇ (z ◇ y)) ◇ w
equation 61242 := (x ◇ y) ◇ y = (y ◇ (z ◇ z)) ◇ x
equation 61243 := (x ◇ y) ◇ y = (y ◇ (z ◇ z)) ◇ y
equation 61244 := (x ◇ y) ◇ y = (y ◇ (z ◇ z)) ◇ z
equation 61245 := (x ◇ y) ◇ y = (y ◇ (z ◇ z)) ◇ w
equation 61246 := (x ◇ y) ◇ y = (y ◇ (z ◇ w)) ◇ x
equation 61247 := (x ◇ y) ◇ y = (y ◇ (z ◇ w)) ◇ y
equation 61248 := (x ◇ y) ◇ y = (y ◇ (z ◇ w)) ◇ z
equation 61249 := (x ◇ y) ◇ y = (y ◇ (z ◇ w)) ◇ w
equation 61250 := (x ◇ y) ◇ y = (y ◇ (z ◇ w)) ◇ u
equation 61251 := (x ◇ y) ◇ y = (z ◇ (x ◇ x)) ◇ x
equation 61252 := (x ◇ y) ◇ y = (z ◇ (x ◇ x)) ◇ y
equation 61253 := (x ◇ y) ◇ y = (z ◇ (x ◇ x)) ◇ z
equation 61254 := (x ◇ y) ◇ y = (z ◇ (x ◇ x)) ◇ w
equation 61255 := (x ◇ y) ◇ y = (z ◇ (x ◇ y)) ◇ x
equation 61256 := (x ◇ y) ◇ y = (z ◇ (x ◇ y)) ◇ y
equation 61257 := (x ◇ y) ◇ y = (z ◇ (x ◇ y)) ◇ z
equation 61258 := (x ◇ y) ◇ y = (z ◇ (x ◇ y)) ◇ w
equation 61259 := (x ◇ y) ◇ y = (z ◇ (x ◇ z)) ◇ x
equation 61260 := (x ◇ y) ◇ y = (z ◇ (x ◇ z)) ◇ y
equation 61261 := (x ◇ y) ◇ y = (z ◇ (x ◇ z)) ◇ z
equation 61262 := (x ◇ y) ◇ y = (z ◇ (x ◇ z)) ◇ w
equation 61263 := (x ◇ y) ◇ y = (z ◇ (x ◇ w)) ◇ x
equation 61264 := (x ◇ y) ◇ y = (z ◇ (x ◇ w)) ◇ y
equation 61265 := (x ◇ y) ◇ y = (z ◇ (x ◇ w)) ◇ z
equation 61266 := (x ◇ y) ◇ y = (z ◇ (x ◇ w)) ◇ w
equation 61267 := (x ◇ y) ◇ y = (z ◇ (x ◇ w)) ◇ u
equation 61268 := (x ◇ y) ◇ y = (z ◇ (y ◇ x)) ◇ x
equation 61269 := (x ◇ y) ◇ y = (z ◇ (y ◇ x)) ◇ y
equation 61270 := (x ◇ y) ◇ y = (z ◇ (y ◇ x)) ◇ z
equation 61271 := (x ◇ y) ◇ y = (z ◇ (y ◇ x)) ◇ w
equation 61272 := (x ◇ y) ◇ y = (z ◇ (y ◇ y)) ◇ x
equation 61273 := (x ◇ y) ◇ y = (z ◇ (y ◇ y)) ◇ y
equation 61274 := (x ◇ y) ◇ y = (z ◇ (y ◇ y)) ◇ z
equation 61275 := (x ◇ y) ◇ y = (z ◇ (y ◇ y)) ◇ w
equation 61276 := (x ◇ y) ◇ y = (z ◇ (y ◇ z)) ◇ x
equation 61277 := (x ◇ y) ◇ y = (z ◇ (y ◇ z)) ◇ y
equation 61278 := (x ◇ y) ◇ y = (z ◇ (y ◇ z)) ◇ z
equation 61279 := (x ◇ y) ◇ y = (z ◇ (y ◇ z)) ◇ w
equation 61280 := (x ◇ y) ◇ y = (z ◇ (y ◇ w)) ◇ x
equation 61281 := (x ◇ y) ◇ y = (z ◇ (y ◇ w)) ◇ y
equation 61282 := (x ◇ y) ◇ y = (z ◇ (y ◇ w)) ◇ z
equation 61283 := (x ◇ y) ◇ y = (z ◇ (y ◇ w)) ◇ w
equation 61284 := (x ◇ y) ◇ y = (z ◇ (y ◇ w)) ◇ u
equation 61285 := (x ◇ y) ◇ y = (z ◇ (z ◇ x)) ◇ x
equation 61286 := (x ◇ y) ◇ y = (z ◇ (z ◇ x)) ◇ y
equation 61287 := (x ◇ y) ◇ y = (z ◇ (z ◇ x)) ◇ z
equation 61288 := (x ◇ y) ◇ y = (z ◇ (z ◇ x)) ◇ w
equation 61289 := (x ◇ y) ◇ y = (z ◇ (z ◇ y)) ◇ x
equation 61290 := (x ◇ y) ◇ y = (z ◇ (z ◇ y)) ◇ y
equation 61291 := (x ◇ y) ◇ y = (z ◇ (z ◇ y)) ◇ z
equation 61292 := (x ◇ y) ◇ y = (z ◇ (z ◇ y)) ◇ w
equation 61293 := (x ◇ y) ◇ y = (z ◇ (z ◇ z)) ◇ x
equation 61294 := (x ◇ y) ◇ y = (z ◇ (z ◇ z)) ◇ y
equation 61295 := (x ◇ y) ◇ y = (z ◇ (z ◇ z)) ◇ z
equation 61296 := (x ◇ y) ◇ y = (z ◇ (z ◇ z)) ◇ w
equation 61297 := (x ◇ y) ◇ y = (z ◇ (z ◇ w)) ◇ x
equation 61298 := (x ◇ y) ◇ y = (z ◇ (z ◇ w)) ◇ y
equation 61299 := (x ◇ y) ◇ y = (z ◇ (z ◇ w)) ◇ z
equation 61300 := (x ◇ y) ◇ y = (z ◇ (z ◇ w)) ◇ w
equation 61301 := (x ◇ y) ◇ y = (z ◇ (z ◇ w)) ◇ u
equation 61302 := (x ◇ y) ◇ y = (z ◇ (w ◇ x)) ◇ x
equation 61303 := (x ◇ y) ◇ y = (z ◇ (w ◇ x)) ◇ y
equation 61304 := (x ◇ y) ◇ y = (z ◇ (w ◇ x)) ◇ z
equation 61305 := (x ◇ y) ◇ y = (z ◇ (w ◇ x)) ◇ w
equation 61306 := (x ◇ y) ◇ y = (z ◇ (w ◇ x)) ◇ u
equation 61307 := (x ◇ y) ◇ y = (z ◇ (w ◇ y)) ◇ x
equation 61308 := (x ◇ y) ◇ y = (z ◇ (w ◇ y)) ◇ y
equation 61309 := (x ◇ y) ◇ y = (z ◇ (w ◇ y)) ◇ z
equation 61310 := (x ◇ y) ◇ y = (z ◇ (w ◇ y)) ◇ w
equation 61311 := (x ◇ y) ◇ y = (z ◇ (w ◇ y)) ◇ u
equation 61312 := (x ◇ y) ◇ y = (z ◇ (w ◇ z)) ◇ x
equation 61313 := (x ◇ y) ◇ y = (z ◇ (w ◇ z)) ◇ y
equation 61314 := (x ◇ y) ◇ y = (z ◇ (w ◇ z)) ◇ z
equation 61315 := (x ◇ y) ◇ y = (z ◇ (w ◇ z)) ◇ w
equation 61316 := (x ◇ y) ◇ y = (z ◇ (w ◇ z)) ◇ u
equation 61317 := (x ◇ y) ◇ y = (z ◇ (w ◇ w)) ◇ x
equation 61318 := (x ◇ y) ◇ y = (z ◇ (w ◇ w)) ◇ y
equation 61319 := (x ◇ y) ◇ y = (z ◇ (w ◇ w)) ◇ z
equation 61320 := (x ◇ y) ◇ y = (z ◇ (w ◇ w)) ◇ w
equation 61321 := (x ◇ y) ◇ y = (z ◇ (w ◇ w)) ◇ u
equation 61322 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ x
equation 61323 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ y
equation 61324 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ z
equation 61325 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ w
equation 61326 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ u
equation 61327 := (x ◇ y) ◇ y = (z ◇ (w ◇ u)) ◇ v
equation 61328 := (x ◇ y) ◇ z = (x ◇ (x ◇ x)) ◇ x
equation 61329 := (x ◇ y) ◇ z = (x ◇ (x ◇ x)) ◇ y
equation 61330 := (x ◇ y) ◇ z = (x ◇ (x ◇ x)) ◇ z
equation 61331 := (x ◇ y) ◇ z = (x ◇ (x ◇ x)) ◇ w
equation 61332 := (x ◇ y) ◇ z = (x ◇ (x ◇ y)) ◇ x
equation 61333 := (x ◇ y) ◇ z = (x ◇ (x ◇ y)) ◇ y
equation 61334 := (x ◇ y) ◇ z = (x ◇ (x ◇ y)) ◇ z
equation 61335 := (x ◇ y) ◇ z = (x ◇ (x ◇ y)) ◇ w
equation 61336 := (x ◇ y) ◇ z = (x ◇ (x ◇ z)) ◇ x
equation 61337 := (x ◇ y) ◇ z = (x ◇ (x ◇ z)) ◇ y
equation 61338 := (x ◇ y) ◇ z = (x ◇ (x ◇ z)) ◇ z
equation 61339 := (x ◇ y) ◇ z = (x ◇ (x ◇ z)) ◇ w
equation 61340 := (x ◇ y) ◇ z = (x ◇ (x ◇ w)) ◇ x
equation 61341 := (x ◇ y) ◇ z = (x ◇ (x ◇ w)) ◇ y
equation 61342 := (x ◇ y) ◇ z = (x ◇ (x ◇ w)) ◇ z
equation 61343 := (x ◇ y) ◇ z = (x ◇ (x ◇ w)) ◇ w
equation 61344 := (x ◇ y) ◇ z = (x ◇ (x ◇ w)) ◇ u
equation 61345 := (x ◇ y) ◇ z = (x ◇ (y ◇ x)) ◇ x
equation 61346 := (x ◇ y) ◇ z = (x ◇ (y ◇ x)) ◇ y
equation 61347 := (x ◇ y) ◇ z = (x ◇ (y ◇ x)) ◇ z
equation 61348 := (x ◇ y) ◇ z = (x ◇ (y ◇ x)) ◇ w
equation 61349 := (x ◇ y) ◇ z = (x ◇ (y ◇ y)) ◇ x
equation 61350 := (x ◇ y) ◇ z = (x ◇ (y ◇ y)) ◇ y
equation 61351 := (x ◇ y) ◇ z = (x ◇ (y ◇ y)) ◇ z
equation 61352 := (x ◇ y) ◇ z = (x ◇ (y ◇ y)) ◇ w
equation 61353 := (x ◇ y) ◇ z = (x ◇ (y ◇ z)) ◇ x
equation 61354 := (x ◇ y) ◇ z = (x ◇ (y ◇ z)) ◇ y
equation 61355 := (x ◇ y) ◇ z = (x ◇ (y ◇ z)) ◇ z
equation 61356 := (x ◇ y) ◇ z = (x ◇ (y ◇ z)) ◇ w
equation 61357 := (x ◇ y) ◇ z = (x ◇ (y ◇ w)) ◇ x
equation 61358 := (x ◇ y) ◇ z = (x ◇ (y ◇ w)) ◇ y
equation 61359 := (x ◇ y) ◇ z = (x ◇ (y ◇ w)) ◇ z
equation 61360 := (x ◇ y) ◇ z = (x ◇ (y ◇ w)) ◇ w
equation 61361 := (x ◇ y) ◇ z = (x ◇ (y ◇ w)) ◇ u
equation 61362 := (x ◇ y) ◇ z = (x ◇ (z ◇ x)) ◇ x
equation 61363 := (x ◇ y) ◇ z = (x ◇ (z ◇ x)) ◇ y
equation 61364 := (x ◇ y) ◇ z = (x ◇ (z ◇ x)) ◇ z
equation 61365 := (x ◇ y) ◇ z = (x ◇ (z ◇ x)) ◇ w
equation 61366 := (x ◇ y) ◇ z = (x ◇ (z ◇ y)) ◇ x
equation 61367 := (x ◇ y) ◇ z = (x ◇ (z ◇ y)) ◇ y
equation 61368 := (x ◇ y) ◇ z = (x ◇ (z ◇ y)) ◇ z
equation 61369 := (x ◇ y) ◇ z = (x ◇ (z ◇ y)) ◇ w
equation 61370 := (x ◇ y) ◇ z = (x ◇ (z ◇ z)) ◇ x
equation 61371 := (x ◇ y) ◇ z = (x ◇ (z ◇ z)) ◇ y
equation 61372 := (x ◇ y) ◇ z = (x ◇ (z ◇ z)) ◇ z
equation 61373 := (x ◇ y) ◇ z = (x ◇ (z ◇ z)) ◇ w
equation 61374 := (x ◇ y) ◇ z = (x ◇ (z ◇ w)) ◇ x
equation 61375 := (x ◇ y) ◇ z = (x ◇ (z ◇ w)) ◇ y
equation 61376 := (x ◇ y) ◇ z = (x ◇ (z ◇ w)) ◇ z
equation 61377 := (x ◇ y) ◇ z = (x ◇ (z ◇ w)) ◇ w
equation 61378 := (x ◇ y) ◇ z = (x ◇ (z ◇ w)) ◇ u
equation 61379 := (x ◇ y) ◇ z = (x ◇ (w ◇ x)) ◇ x
equation 61380 := (x ◇ y) ◇ z = (x ◇ (w ◇ x)) ◇ y
equation 61381 := (x ◇ y) ◇ z = (x ◇ (w ◇ x)) ◇ z
equation 61382 := (x ◇ y) ◇ z = (x ◇ (w ◇ x)) ◇ w
equation 61383 := (x ◇ y) ◇ z = (x ◇ (w ◇ x)) ◇ u
equation 61384 := (x ◇ y) ◇ z = (x ◇ (w ◇ y)) ◇ x
equation 61385 := (x ◇ y) ◇ z = (x ◇ (w ◇ y)) ◇ y
equation 61386 := (x ◇ y) ◇ z = (x ◇ (w ◇ y)) ◇ z
equation 61387 := (x ◇ y) ◇ z = (x ◇ (w ◇ y)) ◇ w
equation 61388 := (x ◇ y) ◇ z = (x ◇ (w ◇ y)) ◇ u
equation 61389 := (x ◇ y) ◇ z = (x ◇ (w ◇ z)) ◇ x
equation 61390 := (x ◇ y) ◇ z = (x ◇ (w ◇ z)) ◇ y
equation 61391 := (x ◇ y) ◇ z = (x ◇ (w ◇ z)) ◇ z
equation 61392 := (x ◇ y) ◇ z = (x ◇ (w ◇ z)) ◇ w
equation 61393 := (x ◇ y) ◇ z = (x ◇ (w ◇ z)) ◇ u
equation 61394 := (x ◇ y) ◇ z = (x ◇ (w ◇ w)) ◇ x
equation 61395 := (x ◇ y) ◇ z = (x ◇ (w ◇ w)) ◇ y
equation 61396 := (x ◇ y) ◇ z = (x ◇ (w ◇ w)) ◇ z
equation 61397 := (x ◇ y) ◇ z = (x ◇ (w ◇ w)) ◇ w
equation 61398 := (x ◇ y) ◇ z = (x ◇ (w ◇ w)) ◇ u
equation 61399 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ x
equation 61400 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ y
equation 61401 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ z
equation 61402 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ w
equation 61403 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ u
equation 61404 := (x ◇ y) ◇ z = (x ◇ (w ◇ u)) ◇ v
equation 61405 := (x ◇ y) ◇ z = (y ◇ (x ◇ x)) ◇ x
equation 61406 := (x ◇ y) ◇ z = (y ◇ (x ◇ x)) ◇ y
equation 61407 := (x ◇ y) ◇ z = (y ◇ (x ◇ x)) ◇ z
equation 61408 := (x ◇ y) ◇ z = (y ◇ (x ◇ x)) ◇ w
equation 61409 := (x ◇ y) ◇ z = (y ◇ (x ◇ y)) ◇ x
equation 61410 := (x ◇ y) ◇ z = (y ◇ (x ◇ y)) ◇ y
equation 61411 := (x ◇ y) ◇ z = (y ◇ (x ◇ y)) ◇ z
equation 61412 := (x ◇ y) ◇ z = (y ◇ (x ◇ y)) ◇ w
equation 61413 := (x ◇ y) ◇ z = (y ◇ (x ◇ z)) ◇ x
equation 61414 := (x ◇ y) ◇ z = (y ◇ (x ◇ z)) ◇ y
equation 61415 := (x ◇ y) ◇ z = (y ◇ (x ◇ z)) ◇ z
equation 61416 := (x ◇ y) ◇ z = (y ◇ (x ◇ z)) ◇ w
equation 61417 := (x ◇ y) ◇ z = (y ◇ (x ◇ w)) ◇ x
equation 61418 := (x ◇ y) ◇ z = (y ◇ (x ◇ w)) ◇ y
equation 61419 := (x ◇ y) ◇ z = (y ◇ (x ◇ w)) ◇ z
equation 61420 := (x ◇ y) ◇ z = (y ◇ (x ◇ w)) ◇ w
equation 61421 := (x ◇ y) ◇ z = (y ◇ (x ◇ w)) ◇ u
equation 61422 := (x ◇ y) ◇ z = (y ◇ (y ◇ x)) ◇ x
equation 61423 := (x ◇ y) ◇ z = (y ◇ (y ◇ x)) ◇ y
equation 61424 := (x ◇ y) ◇ z = (y ◇ (y ◇ x)) ◇ z
equation 61425 := (x ◇ y) ◇ z = (y ◇ (y ◇ x)) ◇ w
equation 61426 := (x ◇ y) ◇ z = (y ◇ (y ◇ y)) ◇ x
equation 61427 := (x ◇ y) ◇ z = (y ◇ (y ◇ y)) ◇ y
equation 61428 := (x ◇ y) ◇ z = (y ◇ (y ◇ y)) ◇ z
equation 61429 := (x ◇ y) ◇ z = (y ◇ (y ◇ y)) ◇ w
equation 61430 := (x ◇ y) ◇ z = (y ◇ (y ◇ z)) ◇ x
equation 61431 := (x ◇ y) ◇ z = (y ◇ (y ◇ z)) ◇ y
equation 61432 := (x ◇ y) ◇ z = (y ◇ (y ◇ z)) ◇ z
equation 61433 := (x ◇ y) ◇ z = (y ◇ (y ◇ z)) ◇ w
equation 61434 := (x ◇ y) ◇ z = (y ◇ (y ◇ w)) ◇ x
equation 61435 := (x ◇ y) ◇ z = (y ◇ (y ◇ w)) ◇ y
equation 61436 := (x ◇ y) ◇ z = (y ◇ (y ◇ w)) ◇ z
equation 61437 := (x ◇ y) ◇ z = (y ◇ (y ◇ w)) ◇ w
equation 61438 := (x ◇ y) ◇ z = (y ◇ (y ◇ w)) ◇ u
equation 61439 := (x ◇ y) ◇ z = (y ◇ (z ◇ x)) ◇ x
equation 61440 := (x ◇ y) ◇ z = (y ◇ (z ◇ x)) ◇ y
equation 61441 := (x ◇ y) ◇ z = (y ◇ (z ◇ x)) ◇ z
equation 61442 := (x ◇ y) ◇ z = (y ◇ (z ◇ x)) ◇ w
equation 61443 := (x ◇ y) ◇ z = (y ◇ (z ◇ y)) ◇ x
equation 61444 := (x ◇ y) ◇ z = (y ◇ (z ◇ y)) ◇ y
equation 61445 := (x ◇ y) ◇ z = (y ◇ (z ◇ y)) ◇ z
equation 61446 := (x ◇ y) ◇ z = (y ◇ (z ◇ y)) ◇ w
equation 61447 := (x ◇ y) ◇ z = (y ◇ (z ◇ z)) ◇ x
equation 61448 := (x ◇ y) ◇ z = (y ◇ (z ◇ z)) ◇ y
equation 61449 := (x ◇ y) ◇ z = (y ◇ (z ◇ z)) ◇ z
equation 61450 := (x ◇ y) ◇ z = (y ◇ (z ◇ z)) ◇ w
equation 61451 := (x ◇ y) ◇ z = (y ◇ (z ◇ w)) ◇ x
equation 61452 := (x ◇ y) ◇ z = (y ◇ (z ◇ w)) ◇ y
equation 61453 := (x ◇ y) ◇ z = (y ◇ (z ◇ w)) ◇ z
equation 61454 := (x ◇ y) ◇ z = (y ◇ (z ◇ w)) ◇ w
equation 61455 := (x ◇ y) ◇ z = (y ◇ (z ◇ w)) ◇ u
equation 61456 := (x ◇ y) ◇ z = (y ◇ (w ◇ x)) ◇ x
equation 61457 := (x ◇ y) ◇ z = (y ◇ (w ◇ x)) ◇ y
equation 61458 := (x ◇ y) ◇ z = (y ◇ (w ◇ x)) ◇ z
equation 61459 := (x ◇ y) ◇ z = (y ◇ (w ◇ x)) ◇ w
equation 61460 := (x ◇ y) ◇ z = (y ◇ (w ◇ x)) ◇ u
equation 61461 := (x ◇ y) ◇ z = (y ◇ (w ◇ y)) ◇ x
equation 61462 := (x ◇ y) ◇ z = (y ◇ (w ◇ y)) ◇ y
equation 61463 := (x ◇ y) ◇ z = (y ◇ (w ◇ y)) ◇ z
equation 61464 := (x ◇ y) ◇ z = (y ◇ (w ◇ y)) ◇ w
equation 61465 := (x ◇ y) ◇ z = (y ◇ (w ◇ y)) ◇ u
equation 61466 := (x ◇ y) ◇ z = (y ◇ (w ◇ z)) ◇ x
equation 61467 := (x ◇ y) ◇ z = (y ◇ (w ◇ z)) ◇ y
equation 61468 := (x ◇ y) ◇ z = (y ◇ (w ◇ z)) ◇ z
equation 61469 := (x ◇ y) ◇ z = (y ◇ (w ◇ z)) ◇ w
equation 61470 := (x ◇ y) ◇ z = (y ◇ (w ◇ z)) ◇ u
equation 61471 := (x ◇ y) ◇ z = (y ◇ (w ◇ w)) ◇ x
equation 61472 := (x ◇ y) ◇ z = (y ◇ (w ◇ w)) ◇ y
equation 61473 := (x ◇ y) ◇ z = (y ◇ (w ◇ w)) ◇ z
equation 61474 := (x ◇ y) ◇ z = (y ◇ (w ◇ w)) ◇ w
equation 61475 := (x ◇ y) ◇ z = (y ◇ (w ◇ w)) ◇ u
equation 61476 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ x
equation 61477 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ y
equation 61478 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ z
equation 61479 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ w
equation 61480 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ u
equation 61481 := (x ◇ y) ◇ z = (y ◇ (w ◇ u)) ◇ v
equation 61482 := (x ◇ y) ◇ z = (z ◇ (x ◇ x)) ◇ x
equation 61483 := (x ◇ y) ◇ z = (z ◇ (x ◇ x)) ◇ y
equation 61484 := (x ◇ y) ◇ z = (z ◇ (x ◇ x)) ◇ z
equation 61485 := (x ◇ y) ◇ z = (z ◇ (x ◇ x)) ◇ w
equation 61486 := (x ◇ y) ◇ z = (z ◇ (x ◇ y)) ◇ x
equation 61487 := (x ◇ y) ◇ z = (z ◇ (x ◇ y)) ◇ y
equation 61488 := (x ◇ y) ◇ z = (z ◇ (x ◇ y)) ◇ z
equation 61489 := (x ◇ y) ◇ z = (z ◇ (x ◇ y)) ◇ w
equation 61490 := (x ◇ y) ◇ z = (z ◇ (x ◇ z)) ◇ x
equation 61491 := (x ◇ y) ◇ z = (z ◇ (x ◇ z)) ◇ y
equation 61492 := (x ◇ y) ◇ z = (z ◇ (x ◇ z)) ◇ z
equation 61493 := (x ◇ y) ◇ z = (z ◇ (x ◇ z)) ◇ w
equation 61494 := (x ◇ y) ◇ z = (z ◇ (x ◇ w)) ◇ x
equation 61495 := (x ◇ y) ◇ z = (z ◇ (x ◇ w)) ◇ y
equation 61496 := (x ◇ y) ◇ z = (z ◇ (x ◇ w)) ◇ z
equation 61497 := (x ◇ y) ◇ z = (z ◇ (x ◇ w)) ◇ w
equation 61498 := (x ◇ y) ◇ z = (z ◇ (x ◇ w)) ◇ u
equation 61499 := (x ◇ y) ◇ z = (z ◇ (y ◇ x)) ◇ x
equation 61500 := (x ◇ y) ◇ z = (z ◇ (y ◇ x)) ◇ y
equation 61501 := (x ◇ y) ◇ z = (z ◇ (y ◇ x)) ◇ z
equation 61502 := (x ◇ y) ◇ z = (z ◇ (y ◇ x)) ◇ w
equation 61503 := (x ◇ y) ◇ z = (z ◇ (y ◇ y)) ◇ x
equation 61504 := (x ◇ y) ◇ z = (z ◇ (y ◇ y)) ◇ y
equation 61505 := (x ◇ y) ◇ z = (z ◇ (y ◇ y)) ◇ z
equation 61506 := (x ◇ y) ◇ z = (z ◇ (y ◇ y)) ◇ w
equation 61507 := (x ◇ y) ◇ z = (z ◇ (y ◇ z)) ◇ x
equation 61508 := (x ◇ y) ◇ z = (z ◇ (y ◇ z)) ◇ y
equation 61509 := (x ◇ y) ◇ z = (z ◇ (y ◇ z)) ◇ z
equation 61510 := (x ◇ y) ◇ z = (z ◇ (y ◇ z)) ◇ w
equation 61511 := (x ◇ y) ◇ z = (z ◇ (y ◇ w)) ◇ x
equation 61512 := (x ◇ y) ◇ z = (z ◇ (y ◇ w)) ◇ y
equation 61513 := (x ◇ y) ◇ z = (z ◇ (y ◇ w)) ◇ z
equation 61514 := (x ◇ y) ◇ z = (z ◇ (y ◇ w)) ◇ w
equation 61515 := (x ◇ y) ◇ z = (z ◇ (y ◇ w)) ◇ u
equation 61516 := (x ◇ y) ◇ z = (z ◇ (z ◇ x)) ◇ x
equation 61517 := (x ◇ y) ◇ z = (z ◇ (z ◇ x)) ◇ y
equation 61518 := (x ◇ y) ◇ z = (z ◇ (z ◇ x)) ◇ z
equation 61519 := (x ◇ y) ◇ z = (z ◇ (z ◇ x)) ◇ w
equation 61520 := (x ◇ y) ◇ z = (z ◇ (z ◇ y)) ◇ x
equation 61521 := (x ◇ y) ◇ z = (z ◇ (z ◇ y)) ◇ y
equation 61522 := (x ◇ y) ◇ z = (z ◇ (z ◇ y)) ◇ z
equation 61523 := (x ◇ y) ◇ z = (z ◇ (z ◇ y)) ◇ w
equation 61524 := (x ◇ y) ◇ z = (z ◇ (z ◇ z)) ◇ x
equation 61525 := (x ◇ y) ◇ z = (z ◇ (z ◇ z)) ◇ y
equation 61526 := (x ◇ y) ◇ z = (z ◇ (z ◇ z)) ◇ z
equation 61527 := (x ◇ y) ◇ z = (z ◇ (z ◇ z)) ◇ w
equation 61528 := (x ◇ y) ◇ z = (z ◇ (z ◇ w)) ◇ x
equation 61529 := (x ◇ y) ◇ z = (z ◇ (z ◇ w)) ◇ y
equation 61530 := (x ◇ y) ◇ z = (z ◇ (z ◇ w)) ◇ z
equation 61531 := (x ◇ y) ◇ z = (z ◇ (z ◇ w)) ◇ w
equation 61532 := (x ◇ y) ◇ z = (z ◇ (z ◇ w)) ◇ u
equation 61533 := (x ◇ y) ◇ z = (z ◇ (w ◇ x)) ◇ x
equation 61534 := (x ◇ y) ◇ z = (z ◇ (w ◇ x)) ◇ y
equation 61535 := (x ◇ y) ◇ z = (z ◇ (w ◇ x)) ◇ z
equation 61536 := (x ◇ y) ◇ z = (z ◇ (w ◇ x)) ◇ w
equation 61537 := (x ◇ y) ◇ z = (z ◇ (w ◇ x)) ◇ u
equation 61538 := (x ◇ y) ◇ z = (z ◇ (w ◇ y)) ◇ x
equation 61539 := (x ◇ y) ◇ z = (z ◇ (w ◇ y)) ◇ y
equation 61540 := (x ◇ y) ◇ z = (z ◇ (w ◇ y)) ◇ z
equation 61541 := (x ◇ y) ◇ z = (z ◇ (w ◇ y)) ◇ w
equation 61542 := (x ◇ y) ◇ z = (z ◇ (w ◇ y)) ◇ u
equation 61543 := (x ◇ y) ◇ z = (z ◇ (w ◇ z)) ◇ x
equation 61544 := (x ◇ y) ◇ z = (z ◇ (w ◇ z)) ◇ y
equation 61545 := (x ◇ y) ◇ z = (z ◇ (w ◇ z)) ◇ z
equation 61546 := (x ◇ y) ◇ z = (z ◇ (w ◇ z)) ◇ w
equation 61547 := (x ◇ y) ◇ z = (z ◇ (w ◇ z)) ◇ u
equation 61548 := (x ◇ y) ◇ z = (z ◇ (w ◇ w)) ◇ x
equation 61549 := (x ◇ y) ◇ z = (z ◇ (w ◇ w)) ◇ y
equation 61550 := (x ◇ y) ◇ z = (z ◇ (w ◇ w)) ◇ z
equation 61551 := (x ◇ y) ◇ z = (z ◇ (w ◇ w)) ◇ w
equation 61552 := (x ◇ y) ◇ z = (z ◇ (w ◇ w)) ◇ u
equation 61553 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ x
equation 61554 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ y
equation 61555 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ z
equation 61556 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ w
equation 61557 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ u
equation 61558 := (x ◇ y) ◇ z = (z ◇ (w ◇ u)) ◇ v
equation 61559 := (x ◇ y) ◇ z = (w ◇ (x ◇ x)) ◇ x
equation 61560 := (x ◇ y) ◇ z = (w ◇ (x ◇ x)) ◇ y
equation 61561 := (x ◇ y) ◇ z = (w ◇ (x ◇ x)) ◇ z
equation 61562 := (x ◇ y) ◇ z = (w ◇ (x ◇ x)) ◇ w
equation 61563 := (x ◇ y) ◇ z = (w ◇ (x ◇ x)) ◇ u
equation 61564 := (x ◇ y) ◇ z = (w ◇ (x ◇ y)) ◇ x
equation 61565 := (x ◇ y) ◇ z = (w ◇ (x ◇ y)) ◇ y
equation 61566 := (x ◇ y) ◇ z = (w ◇ (x ◇ y)) ◇ z
equation 61567 := (x ◇ y) ◇ z = (w ◇ (x ◇ y)) ◇ w
equation 61568 := (x ◇ y) ◇ z = (w ◇ (x ◇ y)) ◇ u
equation 61569 := (x ◇ y) ◇ z = (w ◇ (x ◇ z)) ◇ x
equation 61570 := (x ◇ y) ◇ z = (w ◇ (x ◇ z)) ◇ y
equation 61571 := (x ◇ y) ◇ z = (w ◇ (x ◇ z)) ◇ z
equation 61572 := (x ◇ y) ◇ z = (w ◇ (x ◇ z)) ◇ w
equation 61573 := (x ◇ y) ◇ z = (w ◇ (x ◇ z)) ◇ u
equation 61574 := (x ◇ y) ◇ z = (w ◇ (x ◇ w)) ◇ x
equation 61575 := (x ◇ y) ◇ z = (w ◇ (x ◇ w)) ◇ y
equation 61576 := (x ◇ y) ◇ z = (w ◇ (x ◇ w)) ◇ z
equation 61577 := (x ◇ y) ◇ z = (w ◇ (x ◇ w)) ◇ w
equation 61578 := (x ◇ y) ◇ z = (w ◇ (x ◇ w)) ◇ u
equation 61579 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ x
equation 61580 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ y
equation 61581 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ z
equation 61582 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ w
equation 61583 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ u
equation 61584 := (x ◇ y) ◇ z = (w ◇ (x ◇ u)) ◇ v
equation 61585 := (x ◇ y) ◇ z = (w ◇ (y ◇ x)) ◇ x
equation 61586 := (x ◇ y) ◇ z = (w ◇ (y ◇ x)) ◇ y
equation 61587 := (x ◇ y) ◇ z = (w ◇ (y ◇ x)) ◇ z
equation 61588 := (x ◇ y) ◇ z = (w ◇ (y ◇ x)) ◇ w
equation 61589 := (x ◇ y) ◇ z = (w ◇ (y ◇ x)) ◇ u
equation 61590 := (x ◇ y) ◇ z = (w ◇ (y ◇ y)) ◇ x
equation 61591 := (x ◇ y) ◇ z = (w ◇ (y ◇ y)) ◇ y
equation 61592 := (x ◇ y) ◇ z = (w ◇ (y ◇ y)) ◇ z
equation 61593 := (x ◇ y) ◇ z = (w ◇ (y ◇ y)) ◇ w
equation 61594 := (x ◇ y) ◇ z = (w ◇ (y ◇ y)) ◇ u
equation 61595 := (x ◇ y) ◇ z = (w ◇ (y ◇ z)) ◇ x
equation 61596 := (x ◇ y) ◇ z = (w ◇ (y ◇ z)) ◇ y
equation 61597 := (x ◇ y) ◇ z = (w ◇ (y ◇ z)) ◇ z
equation 61598 := (x ◇ y) ◇ z = (w ◇ (y ◇ z)) ◇ w
equation 61599 := (x ◇ y) ◇ z = (w ◇ (y ◇ z)) ◇ u
equation 61600 := (x ◇ y) ◇ z = (w ◇ (y ◇ w)) ◇ x
equation 61601 := (x ◇ y) ◇ z = (w ◇ (y ◇ w)) ◇ y
equation 61602 := (x ◇ y) ◇ z = (w ◇ (y ◇ w)) ◇ z
equation 61603 := (x ◇ y) ◇ z = (w ◇ (y ◇ w)) ◇ w
equation 61604 := (x ◇ y) ◇ z = (w ◇ (y ◇ w)) ◇ u
equation 61605 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ x
equation 61606 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ y
equation 61607 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ z
equation 61608 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ w
equation 61609 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ u
equation 61610 := (x ◇ y) ◇ z = (w ◇ (y ◇ u)) ◇ v
equation 61611 := (x ◇ y) ◇ z = (w ◇ (z ◇ x)) ◇ x
equation 61612 := (x ◇ y) ◇ z = (w ◇ (z ◇ x)) ◇ y
equation 61613 := (x ◇ y) ◇ z = (w ◇ (z ◇ x)) ◇ z
equation 61614 := (x ◇ y) ◇ z = (w ◇ (z ◇ x)) ◇ w
equation 61615 := (x ◇ y) ◇ z = (w ◇ (z ◇ x)) ◇ u
equation 61616 := (x ◇ y) ◇ z = (w ◇ (z ◇ y)) ◇ x
equation 61617 := (x ◇ y) ◇ z = (w ◇ (z ◇ y)) ◇ y
equation 61618 := (x ◇ y) ◇ z = (w ◇ (z ◇ y)) ◇ z
equation 61619 := (x ◇ y) ◇ z = (w ◇ (z ◇ y)) ◇ w
equation 61620 := (x ◇ y) ◇ z = (w ◇ (z ◇ y)) ◇ u
equation 61621 := (x ◇ y) ◇ z = (w ◇ (z ◇ z)) ◇ x
equation 61622 := (x ◇ y) ◇ z = (w ◇ (z ◇ z)) ◇ y
equation 61623 := (x ◇ y) ◇ z = (w ◇ (z ◇ z)) ◇ z
equation 61624 := (x ◇ y) ◇ z = (w ◇ (z ◇ z)) ◇ w
equation 61625 := (x ◇ y) ◇ z = (w ◇ (z ◇ z)) ◇ u
equation 61626 := (x ◇ y) ◇ z = (w ◇ (z ◇ w)) ◇ x
equation 61627 := (x ◇ y) ◇ z = (w ◇ (z ◇ w)) ◇ y
equation 61628 := (x ◇ y) ◇ z = (w ◇ (z ◇ w)) ◇ z
equation 61629 := (x ◇ y) ◇ z = (w ◇ (z ◇ w)) ◇ w
equation 61630 := (x ◇ y) ◇ z = (w ◇ (z ◇ w)) ◇ u
equation 61631 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ x
equation 61632 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ y
equation 61633 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ z
equation 61634 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ w
equation 61635 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ u
equation 61636 := (x ◇ y) ◇ z = (w ◇ (z ◇ u)) ◇ v
equation 61637 := (x ◇ y) ◇ z = (w ◇ (w ◇ x)) ◇ x
equation 61638 := (x ◇ y) ◇ z = (w ◇ (w ◇ x)) ◇ y
equation 61639 := (x ◇ y) ◇ z = (w ◇ (w ◇ x)) ◇ z
equation 61640 := (x ◇ y) ◇ z = (w ◇ (w ◇ x)) ◇ w
equation 61641 := (x ◇ y) ◇ z = (w ◇ (w ◇ x)) ◇ u
equation 61642 := (x ◇ y) ◇ z = (w ◇ (w ◇ y)) ◇ x
equation 61643 := (x ◇ y) ◇ z = (w ◇ (w ◇ y)) ◇ y
equation 61644 := (x ◇ y) ◇ z = (w ◇ (w ◇ y)) ◇ z
equation 61645 := (x ◇ y) ◇ z = (w ◇ (w ◇ y)) ◇ w
equation 61646 := (x ◇ y) ◇ z = (w ◇ (w ◇ y)) ◇ u
equation 61647 := (x ◇ y) ◇ z = (w ◇ (w ◇ z)) ◇ x
equation 61648 := (x ◇ y) ◇ z = (w ◇ (w ◇ z)) ◇ y
equation 61649 := (x ◇ y) ◇ z = (w ◇ (w ◇ z)) ◇ z
equation 61650 := (x ◇ y) ◇ z = (w ◇ (w ◇ z)) ◇ w
equation 61651 := (x ◇ y) ◇ z = (w ◇ (w ◇ z)) ◇ u
equation 61652 := (x ◇ y) ◇ z = (w ◇ (w ◇ w)) ◇ x
equation 61653 := (x ◇ y) ◇ z = (w ◇ (w ◇ w)) ◇ y
equation 61654 := (x ◇ y) ◇ z = (w ◇ (w ◇ w)) ◇ z
equation 61655 := (x ◇ y) ◇ z = (w ◇ (w ◇ w)) ◇ w
equation 61656 := (x ◇ y) ◇ z = (w ◇ (w ◇ w)) ◇ u
equation 61657 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ x
equation 61658 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ y
equation 61659 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ z
equation 61660 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ w
equation 61661 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ u
equation 61662 := (x ◇ y) ◇ z = (w ◇ (w ◇ u)) ◇ v
equation 61663 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ x
equation 61664 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ y
equation 61665 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ z
equation 61666 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ w
equation 61667 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ u
equation 61668 := (x ◇ y) ◇ z = (w ◇ (u ◇ x)) ◇ v
equation 61669 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ x
equation 61670 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ y
equation 61671 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ z
equation 61672 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ w
equation 61673 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ u
equation 61674 := (x ◇ y) ◇ z = (w ◇ (u ◇ y)) ◇ v
equation 61675 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ x
equation 61676 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ y
equation 61677 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ z
equation 61678 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ w
equation 61679 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ u
equation 61680 := (x ◇ y) ◇ z = (w ◇ (u ◇ z)) ◇ v
equation 61681 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ x
equation 61682 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ y
equation 61683 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ z
equation 61684 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ w
equation 61685 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ u
equation 61686 := (x ◇ y) ◇ z = (w ◇ (u ◇ w)) ◇ v
equation 61687 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ x
equation 61688 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ y
equation 61689 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ z
equation 61690 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ w
equation 61691 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ u
equation 61692 := (x ◇ y) ◇ z = (w ◇ (u ◇ u)) ◇ v
equation 61693 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ x
equation 61694 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ y
equation 61695 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ z
equation 61696 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ w
equation 61697 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ u
equation 61698 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ v
equation 61699 := (x ◇ y) ◇ z = (w ◇ (u ◇ v)) ◇ r
equation 61700 := (x ◇ x) ◇ x = ((x ◇ x) ◇ x) ◇ x
equation 61701 := (x ◇ x) ◇ x = ((x ◇ x) ◇ x) ◇ y
equation 61702 := (x ◇ x) ◇ x = ((x ◇ x) ◇ y) ◇ x
equation 61703 := (x ◇ x) ◇ x = ((x ◇ x) ◇ y) ◇ y
equation 61704 := (x ◇ x) ◇ x = ((x ◇ x) ◇ y) ◇ z
equation 61705 := (x ◇ x) ◇ x = ((x ◇ y) ◇ x) ◇ x
equation 61706 := (x ◇ x) ◇ x = ((x ◇ y) ◇ x) ◇ y
equation 61707 := (x ◇ x) ◇ x = ((x ◇ y) ◇ x) ◇ z
equation 61708 := (x ◇ x) ◇ x = ((x ◇ y) ◇ y) ◇ x
equation 61709 := (x ◇ x) ◇ x = ((x ◇ y) ◇ y) ◇ y
equation 61710 := (x ◇ x) ◇ x = ((x ◇ y) ◇ y) ◇ z
equation 61711 := (x ◇ x) ◇ x = ((x ◇ y) ◇ z) ◇ x
equation 61712 := (x ◇ x) ◇ x = ((x ◇ y) ◇ z) ◇ y
equation 61713 := (x ◇ x) ◇ x = ((x ◇ y) ◇ z) ◇ z
equation 61714 := (x ◇ x) ◇ x = ((x ◇ y) ◇ z) ◇ w
equation 61715 := (x ◇ x) ◇ x = ((y ◇ x) ◇ x) ◇ x
equation 61716 := (x ◇ x) ◇ x = ((y ◇ x) ◇ x) ◇ y
equation 61717 := (x ◇ x) ◇ x = ((y ◇ x) ◇ x) ◇ z
equation 61718 := (x ◇ x) ◇ x = ((y ◇ x) ◇ y) ◇ x
equation 61719 := (x ◇ x) ◇ x = ((y ◇ x) ◇ y) ◇ y
equation 61720 := (x ◇ x) ◇ x = ((y ◇ x) ◇ y) ◇ z
equation 61721 := (x ◇ x) ◇ x = ((y ◇ x) ◇ z) ◇ x
equation 61722 := (x ◇ x) ◇ x = ((y ◇ x) ◇ z) ◇ y
equation 61723 := (x ◇ x) ◇ x = ((y ◇ x) ◇ z) ◇ z
equation 61724 := (x ◇ x) ◇ x = ((y ◇ x) ◇ z) ◇ w
equation 61725 := (x ◇ x) ◇ x = ((y ◇ y) ◇ x) ◇ x
equation 61726 := (x ◇ x) ◇ x = ((y ◇ y) ◇ x) ◇ y
equation 61727 := (x ◇ x) ◇ x = ((y ◇ y) ◇ x) ◇ z
equation 61728 := (x ◇ x) ◇ x = ((y ◇ y) ◇ y) ◇ x
equation 61729 := (x ◇ x) ◇ x = ((y ◇ y) ◇ y) ◇ y
equation 61730 := (x ◇ x) ◇ x = ((y ◇ y) ◇ y) ◇ z
equation 61731 := (x ◇ x) ◇ x = ((y ◇ y) ◇ z) ◇ x
equation 61732 := (x ◇ x) ◇ x = ((y ◇ y) ◇ z) ◇ y
equation 61733 := (x ◇ x) ◇ x = ((y ◇ y) ◇ z) ◇ z
equation 61734 := (x ◇ x) ◇ x = ((y ◇ y) ◇ z) ◇ w
equation 61735 := (x ◇ x) ◇ x = ((y ◇ z) ◇ x) ◇ x
equation 61736 := (x ◇ x) ◇ x = ((y ◇ z) ◇ x) ◇ y
equation 61737 := (x ◇ x) ◇ x = ((y ◇ z) ◇ x) ◇ z
equation 61738 := (x ◇ x) ◇ x = ((y ◇ z) ◇ x) ◇ w
equation 61739 := (x ◇ x) ◇ x = ((y ◇ z) ◇ y) ◇ x
equation 61740 := (x ◇ x) ◇ x = ((y ◇ z) ◇ y) ◇ y
equation 61741 := (x ◇ x) ◇ x = ((y ◇ z) ◇ y) ◇ z
equation 61742 := (x ◇ x) ◇ x = ((y ◇ z) ◇ y) ◇ w
equation 61743 := (x ◇ x) ◇ x = ((y ◇ z) ◇ z) ◇ x
equation 61744 := (x ◇ x) ◇ x = ((y ◇ z) ◇ z) ◇ y
equation 61745 := (x ◇ x) ◇ x = ((y ◇ z) ◇ z) ◇ z
equation 61746 := (x ◇ x) ◇ x = ((y ◇ z) ◇ z) ◇ w
equation 61747 := (x ◇ x) ◇ x = ((y ◇ z) ◇ w) ◇ x
equation 61748 := (x ◇ x) ◇ x = ((y ◇ z) ◇ w) ◇ y
equation 61749 := (x ◇ x) ◇ x = ((y ◇ z) ◇ w) ◇ z
equation 61750 := (x ◇ x) ◇ x = ((y ◇ z) ◇ w) ◇ w
equation 61751 := (x ◇ x) ◇ x = ((y ◇ z) ◇ w) ◇ u
equation 61752 := (x ◇ x) ◇ y = ((x ◇ x) ◇ x) ◇ x
equation 61753 := (x ◇ x) ◇ y = ((x ◇ x) ◇ x) ◇ y
equation 61754 := (x ◇ x) ◇ y = ((x ◇ x) ◇ x) ◇ z
equation 61755 := (x ◇ x) ◇ y = ((x ◇ x) ◇ y) ◇ x
equation 61756 := (x ◇ x) ◇ y = ((x ◇ x) ◇ y) ◇ y
equation 61757 := (x ◇ x) ◇ y = ((x ◇ x) ◇ y) ◇ z
equation 61758 := (x ◇ x) ◇ y = ((x ◇ x) ◇ z) ◇ x
equation 61759 := (x ◇ x) ◇ y = ((x ◇ x) ◇ z) ◇ y
equation 61760 := (x ◇ x) ◇ y = ((x ◇ x) ◇ z) ◇ z
equation 61761 := (x ◇ x) ◇ y = ((x ◇ x) ◇ z) ◇ w
equation 61762 := (x ◇ x) ◇ y = ((x ◇ y) ◇ x) ◇ x
equation 61763 := (x ◇ x) ◇ y = ((x ◇ y) ◇ x) ◇ y
equation 61764 := (x ◇ x) ◇ y = ((x ◇ y) ◇ x) ◇ z
equation 61765 := (x ◇ x) ◇ y = ((x ◇ y) ◇ y) ◇ x
equation 61766 := (x ◇ x) ◇ y = ((x ◇ y) ◇ y) ◇ y
equation 61767 := (x ◇ x) ◇ y = ((x ◇ y) ◇ y) ◇ z
equation 61768 := (x ◇ x) ◇ y = ((x ◇ y) ◇ z) ◇ x
equation 61769 := (x ◇ x) ◇ y = ((x ◇ y) ◇ z) ◇ y
equation 61770 := (x ◇ x) ◇ y = ((x ◇ y) ◇ z) ◇ z
equation 61771 := (x ◇ x) ◇ y = ((x ◇ y) ◇ z) ◇ w
equation 61772 := (x ◇ x) ◇ y = ((x ◇ z) ◇ x) ◇ x
equation 61773 := (x ◇ x) ◇ y = ((x ◇ z) ◇ x) ◇ y
equation 61774 := (x ◇ x) ◇ y = ((x ◇ z) ◇ x) ◇ z
equation 61775 := (x ◇ x) ◇ y = ((x ◇ z) ◇ x) ◇ w
equation 61776 := (x ◇ x) ◇ y = ((x ◇ z) ◇ y) ◇ x
equation 61777 := (x ◇ x) ◇ y = ((x ◇ z) ◇ y) ◇ y
equation 61778 := (x ◇ x) ◇ y = ((x ◇ z) ◇ y) ◇ z
equation 61779 := (x ◇ x) ◇ y = ((x ◇ z) ◇ y) ◇ w
equation 61780 := (x ◇ x) ◇ y = ((x ◇ z) ◇ z) ◇ x
equation 61781 := (x ◇ x) ◇ y = ((x ◇ z) ◇ z) ◇ y
equation 61782 := (x ◇ x) ◇ y = ((x ◇ z) ◇ z) ◇ z
equation 61783 := (x ◇ x) ◇ y = ((x ◇ z) ◇ z) ◇ w
equation 61784 := (x ◇ x) ◇ y = ((x ◇ z) ◇ w) ◇ x
equation 61785 := (x ◇ x) ◇ y = ((x ◇ z) ◇ w) ◇ y
equation 61786 := (x ◇ x) ◇ y = ((x ◇ z) ◇ w) ◇ z
equation 61787 := (x ◇ x) ◇ y = ((x ◇ z) ◇ w) ◇ w
equation 61788 := (x ◇ x) ◇ y = ((x ◇ z) ◇ w) ◇ u
equation 61789 := (x ◇ x) ◇ y = ((y ◇ x) ◇ x) ◇ x
equation 61790 := (x ◇ x) ◇ y = ((y ◇ x) ◇ x) ◇ y
equation 61791 := (x ◇ x) ◇ y = ((y ◇ x) ◇ x) ◇ z
equation 61792 := (x ◇ x) ◇ y = ((y ◇ x) ◇ y) ◇ x
equation 61793 := (x ◇ x) ◇ y = ((y ◇ x) ◇ y) ◇ y
equation 61794 := (x ◇ x) ◇ y = ((y ◇ x) ◇ y) ◇ z
equation 61795 := (x ◇ x) ◇ y = ((y ◇ x) ◇ z) ◇ x
equation 61796 := (x ◇ x) ◇ y = ((y ◇ x) ◇ z) ◇ y
equation 61797 := (x ◇ x) ◇ y = ((y ◇ x) ◇ z) ◇ z
equation 61798 := (x ◇ x) ◇ y = ((y ◇ x) ◇ z) ◇ w
equation 61799 := (x ◇ x) ◇ y = ((y ◇ y) ◇ x) ◇ x
equation 61800 := (x ◇ x) ◇ y = ((y ◇ y) ◇ x) ◇ y
equation 61801 := (x ◇ x) ◇ y = ((y ◇ y) ◇ x) ◇ z
equation 61802 := (x ◇ x) ◇ y = ((y ◇ y) ◇ y) ◇ x
equation 61803 := (x ◇ x) ◇ y = ((y ◇ y) ◇ y) ◇ y
equation 61804 := (x ◇ x) ◇ y = ((y ◇ y) ◇ y) ◇ z
equation 61805 := (x ◇ x) ◇ y = ((y ◇ y) ◇ z) ◇ x
equation 61806 := (x ◇ x) ◇ y = ((y ◇ y) ◇ z) ◇ y
equation 61807 := (x ◇ x) ◇ y = ((y ◇ y) ◇ z) ◇ z
equation 61808 := (x ◇ x) ◇ y = ((y ◇ y) ◇ z) ◇ w
equation 61809 := (x ◇ x) ◇ y = ((y ◇ z) ◇ x) ◇ x
equation 61810 := (x ◇ x) ◇ y = ((y ◇ z) ◇ x) ◇ y
equation 61811 := (x ◇ x) ◇ y = ((y ◇ z) ◇ x) ◇ z
equation 61812 := (x ◇ x) ◇ y = ((y ◇ z) ◇ x) ◇ w
equation 61813 := (x ◇ x) ◇ y = ((y ◇ z) ◇ y) ◇ x
equation 61814 := (x ◇ x) ◇ y = ((y ◇ z) ◇ y) ◇ y
equation 61815 := (x ◇ x) ◇ y = ((y ◇ z) ◇ y) ◇ z
equation 61816 := (x ◇ x) ◇ y = ((y ◇ z) ◇ y) ◇ w
equation 61817 := (x ◇ x) ◇ y = ((y ◇ z) ◇ z) ◇ x
equation 61818 := (x ◇ x) ◇ y = ((y ◇ z) ◇ z) ◇ y
equation 61819 := (x ◇ x) ◇ y = ((y ◇ z) ◇ z) ◇ z
equation 61820 := (x ◇ x) ◇ y = ((y ◇ z) ◇ z) ◇ w
equation 61821 := (x ◇ x) ◇ y = ((y ◇ z) ◇ w) ◇ x
equation 61822 := (x ◇ x) ◇ y = ((y ◇ z) ◇ w) ◇ y
equation 61823 := (x ◇ x) ◇ y = ((y ◇ z) ◇ w) ◇ z
equation 61824 := (x ◇ x) ◇ y = ((y ◇ z) ◇ w) ◇ w
equation 61825 := (x ◇ x) ◇ y = ((y ◇ z) ◇ w) ◇ u
equation 61826 := (x ◇ x) ◇ y = ((z ◇ x) ◇ x) ◇ x
equation 61827 := (x ◇ x) ◇ y = ((z ◇ x) ◇ x) ◇ y
equation 61828 := (x ◇ x) ◇ y = ((z ◇ x) ◇ x) ◇ z
equation 61829 := (x ◇ x) ◇ y = ((z ◇ x) ◇ x) ◇ w
equation 61830 := (x ◇ x) ◇ y = ((z ◇ x) ◇ y) ◇ x
equation 61831 := (x ◇ x) ◇ y = ((z ◇ x) ◇ y) ◇ y
equation 61832 := (x ◇ x) ◇ y = ((z ◇ x) ◇ y) ◇ z
equation 61833 := (x ◇ x) ◇ y = ((z ◇ x) ◇ y) ◇ w
equation 61834 := (x ◇ x) ◇ y = ((z ◇ x) ◇ z) ◇ x
equation 61835 := (x ◇ x) ◇ y = ((z ◇ x) ◇ z) ◇ y
equation 61836 := (x ◇ x) ◇ y = ((z ◇ x) ◇ z) ◇ z
equation 61837 := (x ◇ x) ◇ y = ((z ◇ x) ◇ z) ◇ w
equation 61838 := (x ◇ x) ◇ y = ((z ◇ x) ◇ w) ◇ x
equation 61839 := (x ◇ x) ◇ y = ((z ◇ x) ◇ w) ◇ y
equation 61840 := (x ◇ x) ◇ y = ((z ◇ x) ◇ w) ◇ z
equation 61841 := (x ◇ x) ◇ y = ((z ◇ x) ◇ w) ◇ w
equation 61842 := (x ◇ x) ◇ y = ((z ◇ x) ◇ w) ◇ u
equation 61843 := (x ◇ x) ◇ y = ((z ◇ y) ◇ x) ◇ x
equation 61844 := (x ◇ x) ◇ y = ((z ◇ y) ◇ x) ◇ y
equation 61845 := (x ◇ x) ◇ y = ((z ◇ y) ◇ x) ◇ z
equation 61846 := (x ◇ x) ◇ y = ((z ◇ y) ◇ x) ◇ w
equation 61847 := (x ◇ x) ◇ y = ((z ◇ y) ◇ y) ◇ x
equation 61848 := (x ◇ x) ◇ y = ((z ◇ y) ◇ y) ◇ y
equation 61849 := (x ◇ x) ◇ y = ((z ◇ y) ◇ y) ◇ z
equation 61850 := (x ◇ x) ◇ y = ((z ◇ y) ◇ y) ◇ w
equation 61851 := (x ◇ x) ◇ y = ((z ◇ y) ◇ z) ◇ x
equation 61852 := (x ◇ x) ◇ y = ((z ◇ y) ◇ z) ◇ y
equation 61853 := (x ◇ x) ◇ y = ((z ◇ y) ◇ z) ◇ z
equation 61854 := (x ◇ x) ◇ y = ((z ◇ y) ◇ z) ◇ w
equation 61855 := (x ◇ x) ◇ y = ((z ◇ y) ◇ w) ◇ x
equation 61856 := (x ◇ x) ◇ y = ((z ◇ y) ◇ w) ◇ y
equation 61857 := (x ◇ x) ◇ y = ((z ◇ y) ◇ w) ◇ z
equation 61858 := (x ◇ x) ◇ y = ((z ◇ y) ◇ w) ◇ w
equation 61859 := (x ◇ x) ◇ y = ((z ◇ y) ◇ w) ◇ u
equation 61860 := (x ◇ x) ◇ y = ((z ◇ z) ◇ x) ◇ x
equation 61861 := (x ◇ x) ◇ y = ((z ◇ z) ◇ x) ◇ y
equation 61862 := (x ◇ x) ◇ y = ((z ◇ z) ◇ x) ◇ z
equation 61863 := (x ◇ x) ◇ y = ((z ◇ z) ◇ x) ◇ w
equation 61864 := (x ◇ x) ◇ y = ((z ◇ z) ◇ y) ◇ x
equation 61865 := (x ◇ x) ◇ y = ((z ◇ z) ◇ y) ◇ y
equation 61866 := (x ◇ x) ◇ y = ((z ◇ z) ◇ y) ◇ z
equation 61867 := (x ◇ x) ◇ y = ((z ◇ z) ◇ y) ◇ w
equation 61868 := (x ◇ x) ◇ y = ((z ◇ z) ◇ z) ◇ x
equation 61869 := (x ◇ x) ◇ y = ((z ◇ z) ◇ z) ◇ y
equation 61870 := (x ◇ x) ◇ y = ((z ◇ z) ◇ z) ◇ z
equation 61871 := (x ◇ x) ◇ y = ((z ◇ z) ◇ z) ◇ w
equation 61872 := (x ◇ x) ◇ y = ((z ◇ z) ◇ w) ◇ x
equation 61873 := (x ◇ x) ◇ y = ((z ◇ z) ◇ w) ◇ y
equation 61874 := (x ◇ x) ◇ y = ((z ◇ z) ◇ w) ◇ z
equation 61875 := (x ◇ x) ◇ y = ((z ◇ z) ◇ w) ◇ w
equation 61876 := (x ◇ x) ◇ y = ((z ◇ z) ◇ w) ◇ u
equation 61877 := (x ◇ x) ◇ y = ((z ◇ w) ◇ x) ◇ x
equation 61878 := (x ◇ x) ◇ y = ((z ◇ w) ◇ x) ◇ y
equation 61879 := (x ◇ x) ◇ y = ((z ◇ w) ◇ x) ◇ z
equation 61880 := (x ◇ x) ◇ y = ((z ◇ w) ◇ x) ◇ w
equation 61881 := (x ◇ x) ◇ y = ((z ◇ w) ◇ x) ◇ u
equation 61882 := (x ◇ x) ◇ y = ((z ◇ w) ◇ y) ◇ x
equation 61883 := (x ◇ x) ◇ y = ((z ◇ w) ◇ y) ◇ y
equation 61884 := (x ◇ x) ◇ y = ((z ◇ w) ◇ y) ◇ z
equation 61885 := (x ◇ x) ◇ y = ((z ◇ w) ◇ y) ◇ w
equation 61886 := (x ◇ x) ◇ y = ((z ◇ w) ◇ y) ◇ u
equation 61887 := (x ◇ x) ◇ y = ((z ◇ w) ◇ z) ◇ x
equation 61888 := (x ◇ x) ◇ y = ((z ◇ w) ◇ z) ◇ y
equation 61889 := (x ◇ x) ◇ y = ((z ◇ w) ◇ z) ◇ z
equation 61890 := (x ◇ x) ◇ y = ((z ◇ w) ◇ z) ◇ w
equation 61891 := (x ◇ x) ◇ y = ((z ◇ w) ◇ z) ◇ u
equation 61892 := (x ◇ x) ◇ y = ((z ◇ w) ◇ w) ◇ x
equation 61893 := (x ◇ x) ◇ y = ((z ◇ w) ◇ w) ◇ y
equation 61894 := (x ◇ x) ◇ y = ((z ◇ w) ◇ w) ◇ z
equation 61895 := (x ◇ x) ◇ y = ((z ◇ w) ◇ w) ◇ w
equation 61896 := (x ◇ x) ◇ y = ((z ◇ w) ◇ w) ◇ u
equation 61897 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ x
equation 61898 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ y
equation 61899 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ z
equation 61900 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ w
equation 61901 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ u
equation 61902 := (x ◇ x) ◇ y = ((z ◇ w) ◇ u) ◇ v
equation 61903 := (x ◇ y) ◇ x = ((x ◇ x) ◇ x) ◇ x
equation 61904 := (x ◇ y) ◇ x = ((x ◇ x) ◇ x) ◇ y
equation 61905 := (x ◇ y) ◇ x = ((x ◇ x) ◇ x) ◇ z
equation 61906 := (x ◇ y) ◇ x = ((x ◇ x) ◇ y) ◇ x
equation 61907 := (x ◇ y) ◇ x = ((x ◇ x) ◇ y) ◇ y
equation 61908 := (x ◇ y) ◇ x = ((x ◇ x) ◇ y) ◇ z
equation 61909 := (x ◇ y) ◇ x = ((x ◇ x) ◇ z) ◇ x
equation 61910 := (x ◇ y) ◇ x = ((x ◇ x) ◇ z) ◇ y
equation 61911 := (x ◇ y) ◇ x = ((x ◇ x) ◇ z) ◇ z
equation 61912 := (x ◇ y) ◇ x = ((x ◇ x) ◇ z) ◇ w
equation 61913 := (x ◇ y) ◇ x = ((x ◇ y) ◇ x) ◇ x
equation 61914 := (x ◇ y) ◇ x = ((x ◇ y) ◇ x) ◇ y
equation 61915 := (x ◇ y) ◇ x = ((x ◇ y) ◇ x) ◇ z
equation 61916 := (x ◇ y) ◇ x = ((x ◇ y) ◇ y) ◇ x
equation 61917 := (x ◇ y) ◇ x = ((x ◇ y) ◇ y) ◇ y
equation 61918 := (x ◇ y) ◇ x = ((x ◇ y) ◇ y) ◇ z
equation 61919 := (x ◇ y) ◇ x = ((x ◇ y) ◇ z) ◇ x
equation 61920 := (x ◇ y) ◇ x = ((x ◇ y) ◇ z) ◇ y
equation 61921 := (x ◇ y) ◇ x = ((x ◇ y) ◇ z) ◇ z
equation 61922 := (x ◇ y) ◇ x = ((x ◇ y) ◇ z) ◇ w
equation 61923 := (x ◇ y) ◇ x = ((x ◇ z) ◇ x) ◇ x
equation 61924 := (x ◇ y) ◇ x = ((x ◇ z) ◇ x) ◇ y
equation 61925 := (x ◇ y) ◇ x = ((x ◇ z) ◇ x) ◇ z
equation 61926 := (x ◇ y) ◇ x = ((x ◇ z) ◇ x) ◇ w
equation 61927 := (x ◇ y) ◇ x = ((x ◇ z) ◇ y) ◇ x
equation 61928 := (x ◇ y) ◇ x = ((x ◇ z) ◇ y) ◇ y
equation 61929 := (x ◇ y) ◇ x = ((x ◇ z) ◇ y) ◇ z
equation 61930 := (x ◇ y) ◇ x = ((x ◇ z) ◇ y) ◇ w
equation 61931 := (x ◇ y) ◇ x = ((x ◇ z) ◇ z) ◇ x
equation 61932 := (x ◇ y) ◇ x = ((x ◇ z) ◇ z) ◇ y
equation 61933 := (x ◇ y) ◇ x = ((x ◇ z) ◇ z) ◇ z
equation 61934 := (x ◇ y) ◇ x = ((x ◇ z) ◇ z) ◇ w
equation 61935 := (x ◇ y) ◇ x = ((x ◇ z) ◇ w) ◇ x
equation 61936 := (x ◇ y) ◇ x = ((x ◇ z) ◇ w) ◇ y
equation 61937 := (x ◇ y) ◇ x = ((x ◇ z) ◇ w) ◇ z
equation 61938 := (x ◇ y) ◇ x = ((x ◇ z) ◇ w) ◇ w
equation 61939 := (x ◇ y) ◇ x = ((x ◇ z) ◇ w) ◇ u
equation 61940 := (x ◇ y) ◇ x = ((y ◇ x) ◇ x) ◇ x
equation 61941 := (x ◇ y) ◇ x = ((y ◇ x) ◇ x) ◇ y
equation 61942 := (x ◇ y) ◇ x = ((y ◇ x) ◇ x) ◇ z
equation 61943 := (x ◇ y) ◇ x = ((y ◇ x) ◇ y) ◇ x
equation 61944 := (x ◇ y) ◇ x = ((y ◇ x) ◇ y) ◇ y
equation 61945 := (x ◇ y) ◇ x = ((y ◇ x) ◇ y) ◇ z
equation 61946 := (x ◇ y) ◇ x = ((y ◇ x) ◇ z) ◇ x
equation 61947 := (x ◇ y) ◇ x = ((y ◇ x) ◇ z) ◇ y
equation 61948 := (x ◇ y) ◇ x = ((y ◇ x) ◇ z) ◇ z
equation 61949 := (x ◇ y) ◇ x = ((y ◇ x) ◇ z) ◇ w
equation 61950 := (x ◇ y) ◇ x = ((y ◇ y) ◇ x) ◇ x
equation 61951 := (x ◇ y) ◇ x = ((y ◇ y) ◇ x) ◇ y
equation 61952 := (x ◇ y) ◇ x = ((y ◇ y) ◇ x) ◇ z
equation 61953 := (x ◇ y) ◇ x = ((y ◇ y) ◇ y) ◇ x
equation 61954 := (x ◇ y) ◇ x = ((y ◇ y) ◇ y) ◇ y
equation 61955 := (x ◇ y) ◇ x = ((y ◇ y) ◇ y) ◇ z
equation 61956 := (x ◇ y) ◇ x = ((y ◇ y) ◇ z) ◇ x
equation 61957 := (x ◇ y) ◇ x = ((y ◇ y) ◇ z) ◇ y
equation 61958 := (x ◇ y) ◇ x = ((y ◇ y) ◇ z) ◇ z
equation 61959 := (x ◇ y) ◇ x = ((y ◇ y) ◇ z) ◇ w
equation 61960 := (x ◇ y) ◇ x = ((y ◇ z) ◇ x) ◇ x
equation 61961 := (x ◇ y) ◇ x = ((y ◇ z) ◇ x) ◇ y
equation 61962 := (x ◇ y) ◇ x = ((y ◇ z) ◇ x) ◇ z
equation 61963 := (x ◇ y) ◇ x = ((y ◇ z) ◇ x) ◇ w
equation 61964 := (x ◇ y) ◇ x = ((y ◇ z) ◇ y) ◇ x
equation 61965 := (x ◇ y) ◇ x = ((y ◇ z) ◇ y) ◇ y
equation 61966 := (x ◇ y) ◇ x = ((y ◇ z) ◇ y) ◇ z
equation 61967 := (x ◇ y) ◇ x = ((y ◇ z) ◇ y) ◇ w
equation 61968 := (x ◇ y) ◇ x = ((y ◇ z) ◇ z) ◇ x
equation 61969 := (x ◇ y) ◇ x = ((y ◇ z) ◇ z) ◇ y
equation 61970 := (x ◇ y) ◇ x = ((y ◇ z) ◇ z) ◇ z
equation 61971 := (x ◇ y) ◇ x = ((y ◇ z) ◇ z) ◇ w
equation 61972 := (x ◇ y) ◇ x = ((y ◇ z) ◇ w) ◇ x
equation 61973 := (x ◇ y) ◇ x = ((y ◇ z) ◇ w) ◇ y
equation 61974 := (x ◇ y) ◇ x = ((y ◇ z) ◇ w) ◇ z
equation 61975 := (x ◇ y) ◇ x = ((y ◇ z) ◇ w) ◇ w
equation 61976 := (x ◇ y) ◇ x = ((y ◇ z) ◇ w) ◇ u
equation 61977 := (x ◇ y) ◇ x = ((z ◇ x) ◇ x) ◇ x
equation 61978 := (x ◇ y) ◇ x = ((z ◇ x) ◇ x) ◇ y
equation 61979 := (x ◇ y) ◇ x = ((z ◇ x) ◇ x) ◇ z
equation 61980 := (x ◇ y) ◇ x = ((z ◇ x) ◇ x) ◇ w
equation 61981 := (x ◇ y) ◇ x = ((z ◇ x) ◇ y) ◇ x
equation 61982 := (x ◇ y) ◇ x = ((z ◇ x) ◇ y) ◇ y
equation 61983 := (x ◇ y) ◇ x = ((z ◇ x) ◇ y) ◇ z
equation 61984 := (x ◇ y) ◇ x = ((z ◇ x) ◇ y) ◇ w
equation 61985 := (x ◇ y) ◇ x = ((z ◇ x) ◇ z) ◇ x
equation 61986 := (x ◇ y) ◇ x = ((z ◇ x) ◇ z) ◇ y
equation 61987 := (x ◇ y) ◇ x = ((z ◇ x) ◇ z) ◇ z
equation 61988 := (x ◇ y) ◇ x = ((z ◇ x) ◇ z) ◇ w
equation 61989 := (x ◇ y) ◇ x = ((z ◇ x) ◇ w) ◇ x
equation 61990 := (x ◇ y) ◇ x = ((z ◇ x) ◇ w) ◇ y
equation 61991 := (x ◇ y) ◇ x = ((z ◇ x) ◇ w) ◇ z
equation 61992 := (x ◇ y) ◇ x = ((z ◇ x) ◇ w) ◇ w
equation 61993 := (x ◇ y) ◇ x = ((z ◇ x) ◇ w) ◇ u
equation 61994 := (x ◇ y) ◇ x = ((z ◇ y) ◇ x) ◇ x
equation 61995 := (x ◇ y) ◇ x = ((z ◇ y) ◇ x) ◇ y
equation 61996 := (x ◇ y) ◇ x = ((z ◇ y) ◇ x) ◇ z
equation 61997 := (x ◇ y) ◇ x = ((z ◇ y) ◇ x) ◇ w
equation 61998 := (x ◇ y) ◇ x = ((z ◇ y) ◇ y) ◇ x
equation 61999 := (x ◇ y) ◇ x = ((z ◇ y) ◇ y) ◇ y
