import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 32000-32999 -/

equation 32000 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ y
equation 32001 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ z
equation 32002 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ w
equation 32003 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ x
equation 32004 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ y
equation 32005 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ z
equation 32006 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ w
equation 32007 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ u
equation 32008 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ x
equation 32009 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ y
equation 32010 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ z
equation 32011 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ w
equation 32012 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ x
equation 32013 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ y
equation 32014 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ z
equation 32015 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ w
equation 32016 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ x
equation 32017 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ y
equation 32018 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ z
equation 32019 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ w
equation 32020 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ x
equation 32021 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ y
equation 32022 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ z
equation 32023 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ w
equation 32024 := x = (x ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ u
equation 32025 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ x
equation 32026 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ y
equation 32027 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ z
equation 32028 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ w
equation 32029 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ x
equation 32030 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ y
equation 32031 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ z
equation 32032 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ w
equation 32033 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ x
equation 32034 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ y
equation 32035 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ z
equation 32036 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ w
equation 32037 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ x
equation 32038 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ y
equation 32039 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ z
equation 32040 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ w
equation 32041 := x = (x ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ u
equation 32042 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ x
equation 32043 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ y
equation 32044 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ z
equation 32045 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ w
equation 32046 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ x
equation 32047 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ y
equation 32048 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ z
equation 32049 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ w
equation 32050 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ x
equation 32051 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ y
equation 32052 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ z
equation 32053 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ w
equation 32054 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ x
equation 32055 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ y
equation 32056 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ z
equation 32057 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ w
equation 32058 := x = (x ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ u
equation 32059 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ x
equation 32060 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ y
equation 32061 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ z
equation 32062 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ w
equation 32063 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ u
equation 32064 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ x
equation 32065 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ y
equation 32066 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ z
equation 32067 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ w
equation 32068 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ u
equation 32069 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ x
equation 32070 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ y
equation 32071 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ z
equation 32072 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ w
equation 32073 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ u
equation 32074 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ x
equation 32075 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ y
equation 32076 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ z
equation 32077 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ w
equation 32078 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ u
equation 32079 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ x
equation 32080 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ y
equation 32081 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ z
equation 32082 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ w
equation 32083 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ u
equation 32084 := x = (x ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ v
equation 32085 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ x)) ◇ x
equation 32086 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ x)) ◇ y
equation 32087 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ x)) ◇ z
equation 32088 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ x
equation 32089 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ y
equation 32090 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ z
equation 32091 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ z)) ◇ x
equation 32092 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ z)) ◇ y
equation 32093 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ z)) ◇ z
equation 32094 := x = (y ◇ ((x ◇ (x ◇ x)) ◇ z)) ◇ w
equation 32095 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ x
equation 32096 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ y
equation 32097 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ z
equation 32098 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ x
equation 32099 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ y
equation 32100 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ z
equation 32101 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ x
equation 32102 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ y
equation 32103 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ z
equation 32104 := x = (y ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ w
equation 32105 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ x)) ◇ x
equation 32106 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ x)) ◇ y
equation 32107 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ x)) ◇ z
equation 32108 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ x)) ◇ w
equation 32109 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ y)) ◇ x
equation 32110 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ y)) ◇ y
equation 32111 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ y)) ◇ z
equation 32112 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ y)) ◇ w
equation 32113 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ z)) ◇ x
equation 32114 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ z)) ◇ y
equation 32115 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ z)) ◇ z
equation 32116 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ z)) ◇ w
equation 32117 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ w)) ◇ x
equation 32118 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ w)) ◇ y
equation 32119 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ w)) ◇ z
equation 32120 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ w)) ◇ w
equation 32121 := x = (y ◇ ((x ◇ (x ◇ z)) ◇ w)) ◇ u
equation 32122 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ x
equation 32123 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ y
equation 32124 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ z
equation 32125 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ x
equation 32126 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ y
equation 32127 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ z
equation 32128 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ x
equation 32129 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ y
equation 32130 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ z
equation 32131 := x = (y ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ w
equation 32132 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ x
equation 32133 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ y
equation 32134 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ z
equation 32135 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ x
equation 32136 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ y
equation 32137 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ z
equation 32138 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ x
equation 32139 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ y
equation 32140 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ z
equation 32141 := x = (y ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ w
equation 32142 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ x
equation 32143 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ y
equation 32144 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ z
equation 32145 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ w
equation 32146 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ x
equation 32147 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ y
equation 32148 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ z
equation 32149 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ w
equation 32150 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ x
equation 32151 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ y
equation 32152 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ z
equation 32153 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ w
equation 32154 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ x
equation 32155 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ y
equation 32156 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ z
equation 32157 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ w
equation 32158 := x = (y ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ u
equation 32159 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ x)) ◇ x
equation 32160 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ x)) ◇ y
equation 32161 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ x)) ◇ z
equation 32162 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ x)) ◇ w
equation 32163 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ y)) ◇ x
equation 32164 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ y)) ◇ y
equation 32165 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ y)) ◇ z
equation 32166 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ y)) ◇ w
equation 32167 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ z)) ◇ x
equation 32168 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ z)) ◇ y
equation 32169 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ z)) ◇ z
equation 32170 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ z)) ◇ w
equation 32171 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ w)) ◇ x
equation 32172 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ w)) ◇ y
equation 32173 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ w)) ◇ z
equation 32174 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ w)) ◇ w
equation 32175 := x = (y ◇ ((x ◇ (z ◇ x)) ◇ w)) ◇ u
equation 32176 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ x)) ◇ x
equation 32177 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ x)) ◇ y
equation 32178 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ x)) ◇ z
equation 32179 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ x)) ◇ w
equation 32180 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ y)) ◇ x
equation 32181 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ y)) ◇ y
equation 32182 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ y)) ◇ z
equation 32183 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ y)) ◇ w
equation 32184 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ z)) ◇ x
equation 32185 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ z)) ◇ y
equation 32186 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ z)) ◇ z
equation 32187 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ z)) ◇ w
equation 32188 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ w)) ◇ x
equation 32189 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ w)) ◇ y
equation 32190 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ w)) ◇ z
equation 32191 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ w)) ◇ w
equation 32192 := x = (y ◇ ((x ◇ (z ◇ y)) ◇ w)) ◇ u
equation 32193 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ x)) ◇ x
equation 32194 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ x)) ◇ y
equation 32195 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ x)) ◇ z
equation 32196 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ x)) ◇ w
equation 32197 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ y)) ◇ x
equation 32198 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ y)) ◇ y
equation 32199 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ y)) ◇ z
equation 32200 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ y)) ◇ w
equation 32201 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ z)) ◇ x
equation 32202 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ z)) ◇ y
equation 32203 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ z)) ◇ z
equation 32204 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ z)) ◇ w
equation 32205 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ w)) ◇ x
equation 32206 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ w)) ◇ y
equation 32207 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ w)) ◇ z
equation 32208 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ w)) ◇ w
equation 32209 := x = (y ◇ ((x ◇ (z ◇ z)) ◇ w)) ◇ u
equation 32210 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ x)) ◇ x
equation 32211 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ x)) ◇ y
equation 32212 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ x)) ◇ z
equation 32213 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ x)) ◇ w
equation 32214 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ x)) ◇ u
equation 32215 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ y)) ◇ x
equation 32216 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ y)) ◇ y
equation 32217 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ y)) ◇ z
equation 32218 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ y)) ◇ w
equation 32219 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ y)) ◇ u
equation 32220 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ z)) ◇ x
equation 32221 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ z)) ◇ y
equation 32222 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ z)) ◇ z
equation 32223 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ z)) ◇ w
equation 32224 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ z)) ◇ u
equation 32225 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ w)) ◇ x
equation 32226 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ w)) ◇ y
equation 32227 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ w)) ◇ z
equation 32228 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ w)) ◇ w
equation 32229 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ w)) ◇ u
equation 32230 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ x
equation 32231 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ y
equation 32232 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ z
equation 32233 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ w
equation 32234 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ u
equation 32235 := x = (y ◇ ((x ◇ (z ◇ w)) ◇ u)) ◇ v
equation 32236 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ x
equation 32237 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ y
equation 32238 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ z
equation 32239 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ x
equation 32240 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ y
equation 32241 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ z
equation 32242 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ x
equation 32243 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ y
equation 32244 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ z
equation 32245 := x = (y ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ w
equation 32246 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ x
equation 32247 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ y
equation 32248 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ z
equation 32249 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ x
equation 32250 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ y
equation 32251 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ z
equation 32252 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ x
equation 32253 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ y
equation 32254 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ z
equation 32255 := x = (y ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ w
equation 32256 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ x
equation 32257 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ y
equation 32258 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ z
equation 32259 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ w
equation 32260 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ x
equation 32261 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ y
equation 32262 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ z
equation 32263 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ w
equation 32264 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ x
equation 32265 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ y
equation 32266 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ z
equation 32267 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ w
equation 32268 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ x
equation 32269 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ y
equation 32270 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ z
equation 32271 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ w
equation 32272 := x = (y ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ u
equation 32273 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ x
equation 32274 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ y
equation 32275 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ z
equation 32276 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ x
equation 32277 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ y
equation 32278 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ z
equation 32279 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ x
equation 32280 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ y
equation 32281 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ z
equation 32282 := x = (y ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ w
equation 32283 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ x
equation 32284 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ y
equation 32285 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ z
equation 32286 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ x
equation 32287 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ y
equation 32288 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ z
equation 32289 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ x
equation 32290 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ y
equation 32291 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ z
equation 32292 := x = (y ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ w
equation 32293 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ x
equation 32294 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ y
equation 32295 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ z
equation 32296 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ w
equation 32297 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ x
equation 32298 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ y
equation 32299 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ z
equation 32300 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ w
equation 32301 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ x
equation 32302 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ y
equation 32303 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ z
equation 32304 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ w
equation 32305 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ x
equation 32306 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ y
equation 32307 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ z
equation 32308 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ w
equation 32309 := x = (y ◇ ((y ◇ (y ◇ z)) ◇ w)) ◇ u
equation 32310 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ x
equation 32311 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ y
equation 32312 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ z
equation 32313 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ x)) ◇ w
equation 32314 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ x
equation 32315 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ y
equation 32316 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ z
equation 32317 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ y)) ◇ w
equation 32318 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ x
equation 32319 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ y
equation 32320 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ z
equation 32321 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ z)) ◇ w
equation 32322 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ x
equation 32323 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ y
equation 32324 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ z
equation 32325 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ w
equation 32326 := x = (y ◇ ((y ◇ (z ◇ x)) ◇ w)) ◇ u
equation 32327 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ x
equation 32328 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ y
equation 32329 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ z
equation 32330 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ x)) ◇ w
equation 32331 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ x
equation 32332 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ y
equation 32333 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ z
equation 32334 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ y)) ◇ w
equation 32335 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ x
equation 32336 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ y
equation 32337 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ z
equation 32338 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ z)) ◇ w
equation 32339 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ x
equation 32340 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ y
equation 32341 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ z
equation 32342 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ w
equation 32343 := x = (y ◇ ((y ◇ (z ◇ y)) ◇ w)) ◇ u
equation 32344 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ x
equation 32345 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ y
equation 32346 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ z
equation 32347 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ x)) ◇ w
equation 32348 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ x
equation 32349 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ y
equation 32350 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ z
equation 32351 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ y)) ◇ w
equation 32352 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ x
equation 32353 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ y
equation 32354 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ z
equation 32355 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ z)) ◇ w
equation 32356 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ x
equation 32357 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ y
equation 32358 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ z
equation 32359 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ w
equation 32360 := x = (y ◇ ((y ◇ (z ◇ z)) ◇ w)) ◇ u
equation 32361 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ x
equation 32362 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ y
equation 32363 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ z
equation 32364 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ w
equation 32365 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ x)) ◇ u
equation 32366 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ x
equation 32367 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ y
equation 32368 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ z
equation 32369 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ w
equation 32370 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ y)) ◇ u
equation 32371 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ x
equation 32372 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ y
equation 32373 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ z
equation 32374 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ w
equation 32375 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ z)) ◇ u
equation 32376 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ x
equation 32377 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ y
equation 32378 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ z
equation 32379 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ w
equation 32380 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ w)) ◇ u
equation 32381 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ x
equation 32382 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ y
equation 32383 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ z
equation 32384 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ w
equation 32385 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ u
equation 32386 := x = (y ◇ ((y ◇ (z ◇ w)) ◇ u)) ◇ v
equation 32387 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ x)) ◇ x
equation 32388 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ x)) ◇ y
equation 32389 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ x)) ◇ z
equation 32390 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ x)) ◇ w
equation 32391 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ y)) ◇ x
equation 32392 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ y)) ◇ y
equation 32393 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ y)) ◇ z
equation 32394 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ y)) ◇ w
equation 32395 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ z)) ◇ x
equation 32396 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ z)) ◇ y
equation 32397 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ z)) ◇ z
equation 32398 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ z)) ◇ w
equation 32399 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ w)) ◇ x
equation 32400 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ w)) ◇ y
equation 32401 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ w)) ◇ z
equation 32402 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ w)) ◇ w
equation 32403 := x = (y ◇ ((z ◇ (x ◇ x)) ◇ w)) ◇ u
equation 32404 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ x)) ◇ x
equation 32405 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ x)) ◇ y
equation 32406 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ x)) ◇ z
equation 32407 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ x)) ◇ w
equation 32408 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ y)) ◇ x
equation 32409 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ y)) ◇ y
equation 32410 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ y)) ◇ z
equation 32411 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ y)) ◇ w
equation 32412 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ z)) ◇ x
equation 32413 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ z)) ◇ y
equation 32414 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ z)) ◇ z
equation 32415 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ z)) ◇ w
equation 32416 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ w)) ◇ x
equation 32417 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ w)) ◇ y
equation 32418 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ w)) ◇ z
equation 32419 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ w)) ◇ w
equation 32420 := x = (y ◇ ((z ◇ (x ◇ y)) ◇ w)) ◇ u
equation 32421 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ x)) ◇ x
equation 32422 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ x)) ◇ y
equation 32423 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ x)) ◇ z
equation 32424 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ x)) ◇ w
equation 32425 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ y)) ◇ x
equation 32426 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ y)) ◇ y
equation 32427 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ y)) ◇ z
equation 32428 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ y)) ◇ w
equation 32429 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ z)) ◇ x
equation 32430 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ z)) ◇ y
equation 32431 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ z)) ◇ z
equation 32432 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ z)) ◇ w
equation 32433 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ w)) ◇ x
equation 32434 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ w)) ◇ y
equation 32435 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ w)) ◇ z
equation 32436 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ w)) ◇ w
equation 32437 := x = (y ◇ ((z ◇ (x ◇ z)) ◇ w)) ◇ u
equation 32438 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ x)) ◇ x
equation 32439 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ x)) ◇ y
equation 32440 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ x)) ◇ z
equation 32441 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ x)) ◇ w
equation 32442 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ x)) ◇ u
equation 32443 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ y)) ◇ x
equation 32444 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ y)) ◇ y
equation 32445 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ y)) ◇ z
equation 32446 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ y)) ◇ w
equation 32447 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ y)) ◇ u
equation 32448 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ z)) ◇ x
equation 32449 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ z)) ◇ y
equation 32450 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ z)) ◇ z
equation 32451 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ z)) ◇ w
equation 32452 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ z)) ◇ u
equation 32453 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ w)) ◇ x
equation 32454 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ w)) ◇ y
equation 32455 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ w)) ◇ z
equation 32456 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ w)) ◇ w
equation 32457 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ w)) ◇ u
equation 32458 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ x
equation 32459 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ y
equation 32460 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ z
equation 32461 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ w
equation 32462 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ u
equation 32463 := x = (y ◇ ((z ◇ (x ◇ w)) ◇ u)) ◇ v
equation 32464 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ x)) ◇ x
equation 32465 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ x)) ◇ y
equation 32466 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ x)) ◇ z
equation 32467 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ x)) ◇ w
equation 32468 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ y)) ◇ x
equation 32469 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ y)) ◇ y
equation 32470 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ y)) ◇ z
equation 32471 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ y)) ◇ w
equation 32472 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ z)) ◇ x
equation 32473 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ z)) ◇ y
equation 32474 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ z)) ◇ z
equation 32475 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ z)) ◇ w
equation 32476 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ w)) ◇ x
equation 32477 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ w)) ◇ y
equation 32478 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ w)) ◇ z
equation 32479 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ w)) ◇ w
equation 32480 := x = (y ◇ ((z ◇ (y ◇ x)) ◇ w)) ◇ u
equation 32481 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ x)) ◇ x
equation 32482 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ x)) ◇ y
equation 32483 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ x)) ◇ z
equation 32484 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ x)) ◇ w
equation 32485 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ y)) ◇ x
equation 32486 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ y)) ◇ y
equation 32487 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ y)) ◇ z
equation 32488 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ y)) ◇ w
equation 32489 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ z)) ◇ x
equation 32490 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ z)) ◇ y
equation 32491 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ z)) ◇ z
equation 32492 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ z)) ◇ w
equation 32493 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ w)) ◇ x
equation 32494 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ w)) ◇ y
equation 32495 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ w)) ◇ z
equation 32496 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ w)) ◇ w
equation 32497 := x = (y ◇ ((z ◇ (y ◇ y)) ◇ w)) ◇ u
equation 32498 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ x)) ◇ x
equation 32499 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ x)) ◇ y
equation 32500 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ x)) ◇ z
equation 32501 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ x)) ◇ w
equation 32502 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ y)) ◇ x
equation 32503 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ y)) ◇ y
equation 32504 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ y)) ◇ z
equation 32505 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ y)) ◇ w
equation 32506 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ z)) ◇ x
equation 32507 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ z)) ◇ y
equation 32508 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ z)) ◇ z
equation 32509 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ z)) ◇ w
equation 32510 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ w)) ◇ x
equation 32511 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ w)) ◇ y
equation 32512 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ w)) ◇ z
equation 32513 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ w)) ◇ w
equation 32514 := x = (y ◇ ((z ◇ (y ◇ z)) ◇ w)) ◇ u
equation 32515 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ x)) ◇ x
equation 32516 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ x)) ◇ y
equation 32517 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ x)) ◇ z
equation 32518 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ x)) ◇ w
equation 32519 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ x)) ◇ u
equation 32520 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ y)) ◇ x
equation 32521 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ y)) ◇ y
equation 32522 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ y)) ◇ z
equation 32523 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ y)) ◇ w
equation 32524 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ y)) ◇ u
equation 32525 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ z)) ◇ x
equation 32526 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ z)) ◇ y
equation 32527 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ z)) ◇ z
equation 32528 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ z)) ◇ w
equation 32529 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ z)) ◇ u
equation 32530 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ w)) ◇ x
equation 32531 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ w)) ◇ y
equation 32532 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ w)) ◇ z
equation 32533 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ w)) ◇ w
equation 32534 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ w)) ◇ u
equation 32535 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ x
equation 32536 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ y
equation 32537 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ z
equation 32538 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ w
equation 32539 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ u
equation 32540 := x = (y ◇ ((z ◇ (y ◇ w)) ◇ u)) ◇ v
equation 32541 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ x)) ◇ x
equation 32542 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ x)) ◇ y
equation 32543 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ x)) ◇ z
equation 32544 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ x)) ◇ w
equation 32545 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ y)) ◇ x
equation 32546 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ y)) ◇ y
equation 32547 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ y)) ◇ z
equation 32548 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ y)) ◇ w
equation 32549 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ z)) ◇ x
equation 32550 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ z)) ◇ y
equation 32551 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ z)) ◇ z
equation 32552 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ z)) ◇ w
equation 32553 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ w)) ◇ x
equation 32554 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ w)) ◇ y
equation 32555 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ w)) ◇ z
equation 32556 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ w)) ◇ w
equation 32557 := x = (y ◇ ((z ◇ (z ◇ x)) ◇ w)) ◇ u
equation 32558 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ x)) ◇ x
equation 32559 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ x)) ◇ y
equation 32560 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ x)) ◇ z
equation 32561 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ x)) ◇ w
equation 32562 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ y)) ◇ x
equation 32563 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ y)) ◇ y
equation 32564 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ y)) ◇ z
equation 32565 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ y)) ◇ w
equation 32566 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ z)) ◇ x
equation 32567 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ z)) ◇ y
equation 32568 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ z)) ◇ z
equation 32569 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ z)) ◇ w
equation 32570 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ w)) ◇ x
equation 32571 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ w)) ◇ y
equation 32572 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ w)) ◇ z
equation 32573 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ w)) ◇ w
equation 32574 := x = (y ◇ ((z ◇ (z ◇ y)) ◇ w)) ◇ u
equation 32575 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ x)) ◇ x
equation 32576 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ x)) ◇ y
equation 32577 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ x)) ◇ z
equation 32578 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ x)) ◇ w
equation 32579 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ y)) ◇ x
equation 32580 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ y)) ◇ y
equation 32581 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ y)) ◇ z
equation 32582 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ y)) ◇ w
equation 32583 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ z)) ◇ x
equation 32584 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ z)) ◇ y
equation 32585 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ z)) ◇ z
equation 32586 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ z)) ◇ w
equation 32587 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ w)) ◇ x
equation 32588 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ w)) ◇ y
equation 32589 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ w)) ◇ z
equation 32590 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ w)) ◇ w
equation 32591 := x = (y ◇ ((z ◇ (z ◇ z)) ◇ w)) ◇ u
equation 32592 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ x)) ◇ x
equation 32593 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ x)) ◇ y
equation 32594 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ x)) ◇ z
equation 32595 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ x)) ◇ w
equation 32596 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ x)) ◇ u
equation 32597 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ y)) ◇ x
equation 32598 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ y)) ◇ y
equation 32599 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ y)) ◇ z
equation 32600 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ y)) ◇ w
equation 32601 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ y)) ◇ u
equation 32602 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ z)) ◇ x
equation 32603 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ z)) ◇ y
equation 32604 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ z)) ◇ z
equation 32605 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ z)) ◇ w
equation 32606 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ z)) ◇ u
equation 32607 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ w)) ◇ x
equation 32608 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ w)) ◇ y
equation 32609 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ w)) ◇ z
equation 32610 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ w)) ◇ w
equation 32611 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ w)) ◇ u
equation 32612 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ x
equation 32613 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ y
equation 32614 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ z
equation 32615 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ w
equation 32616 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ u
equation 32617 := x = (y ◇ ((z ◇ (z ◇ w)) ◇ u)) ◇ v
equation 32618 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ x)) ◇ x
equation 32619 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ x)) ◇ y
equation 32620 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ x)) ◇ z
equation 32621 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ x)) ◇ w
equation 32622 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ x)) ◇ u
equation 32623 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ y)) ◇ x
equation 32624 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ y)) ◇ y
equation 32625 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ y)) ◇ z
equation 32626 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ y)) ◇ w
equation 32627 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ y)) ◇ u
equation 32628 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ z)) ◇ x
equation 32629 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ z)) ◇ y
equation 32630 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ z)) ◇ z
equation 32631 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ z)) ◇ w
equation 32632 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ z)) ◇ u
equation 32633 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ w)) ◇ x
equation 32634 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ w)) ◇ y
equation 32635 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ w)) ◇ z
equation 32636 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ w)) ◇ w
equation 32637 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ w)) ◇ u
equation 32638 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ x
equation 32639 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ y
equation 32640 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ z
equation 32641 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ w
equation 32642 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ u
equation 32643 := x = (y ◇ ((z ◇ (w ◇ x)) ◇ u)) ◇ v
equation 32644 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ x)) ◇ x
equation 32645 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ x)) ◇ y
equation 32646 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ x)) ◇ z
equation 32647 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ x)) ◇ w
equation 32648 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ x)) ◇ u
equation 32649 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ y)) ◇ x
equation 32650 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ y)) ◇ y
equation 32651 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ y)) ◇ z
equation 32652 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ y)) ◇ w
equation 32653 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ y)) ◇ u
equation 32654 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ z)) ◇ x
equation 32655 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ z)) ◇ y
equation 32656 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ z)) ◇ z
equation 32657 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ z)) ◇ w
equation 32658 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ z)) ◇ u
equation 32659 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ w)) ◇ x
equation 32660 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ w)) ◇ y
equation 32661 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ w)) ◇ z
equation 32662 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ w)) ◇ w
equation 32663 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ w)) ◇ u
equation 32664 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ x
equation 32665 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ y
equation 32666 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ z
equation 32667 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ w
equation 32668 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ u
equation 32669 := x = (y ◇ ((z ◇ (w ◇ y)) ◇ u)) ◇ v
equation 32670 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ x)) ◇ x
equation 32671 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ x)) ◇ y
equation 32672 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ x)) ◇ z
equation 32673 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ x)) ◇ w
equation 32674 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ x)) ◇ u
equation 32675 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ y)) ◇ x
equation 32676 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ y)) ◇ y
equation 32677 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ y)) ◇ z
equation 32678 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ y)) ◇ w
equation 32679 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ y)) ◇ u
equation 32680 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ z)) ◇ x
equation 32681 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ z)) ◇ y
equation 32682 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ z)) ◇ z
equation 32683 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ z)) ◇ w
equation 32684 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ z)) ◇ u
equation 32685 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ w)) ◇ x
equation 32686 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ w)) ◇ y
equation 32687 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ w)) ◇ z
equation 32688 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ w)) ◇ w
equation 32689 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ w)) ◇ u
equation 32690 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ x
equation 32691 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ y
equation 32692 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ z
equation 32693 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ w
equation 32694 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ u
equation 32695 := x = (y ◇ ((z ◇ (w ◇ z)) ◇ u)) ◇ v
equation 32696 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ x)) ◇ x
equation 32697 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ x)) ◇ y
equation 32698 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ x)) ◇ z
equation 32699 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ x)) ◇ w
equation 32700 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ x)) ◇ u
equation 32701 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ y)) ◇ x
equation 32702 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ y)) ◇ y
equation 32703 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ y)) ◇ z
equation 32704 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ y)) ◇ w
equation 32705 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ y)) ◇ u
equation 32706 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ z)) ◇ x
equation 32707 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ z)) ◇ y
equation 32708 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ z)) ◇ z
equation 32709 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ z)) ◇ w
equation 32710 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ z)) ◇ u
equation 32711 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ w)) ◇ x
equation 32712 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ w)) ◇ y
equation 32713 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ w)) ◇ z
equation 32714 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ w)) ◇ w
equation 32715 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ w)) ◇ u
equation 32716 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ x
equation 32717 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ y
equation 32718 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ z
equation 32719 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ w
equation 32720 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ u
equation 32721 := x = (y ◇ ((z ◇ (w ◇ w)) ◇ u)) ◇ v
equation 32722 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ x
equation 32723 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ y
equation 32724 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ z
equation 32725 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ w
equation 32726 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ u
equation 32727 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ x)) ◇ v
equation 32728 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ x
equation 32729 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ y
equation 32730 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ z
equation 32731 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ w
equation 32732 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ u
equation 32733 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ y)) ◇ v
equation 32734 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ x
equation 32735 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ y
equation 32736 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ z
equation 32737 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ w
equation 32738 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ u
equation 32739 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ z)) ◇ v
equation 32740 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ x
equation 32741 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ y
equation 32742 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ z
equation 32743 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ w
equation 32744 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ u
equation 32745 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ w)) ◇ v
equation 32746 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ x
equation 32747 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ y
equation 32748 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ z
equation 32749 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ w
equation 32750 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ u
equation 32751 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ u)) ◇ v
equation 32752 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ x
equation 32753 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ y
equation 32754 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ z
equation 32755 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ w
equation 32756 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ u
equation 32757 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ v
equation 32758 := x = (y ◇ ((z ◇ (w ◇ u)) ◇ v)) ◇ r
equation 32759 := x = (x ◇ (((x ◇ x) ◇ x) ◇ x)) ◇ x
equation 32760 := x = (x ◇ (((x ◇ x) ◇ x) ◇ x)) ◇ y
equation 32761 := x = (x ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ x
equation 32762 := x = (x ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ y
equation 32763 := x = (x ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ z
equation 32764 := x = (x ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ x
equation 32765 := x = (x ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ y
equation 32766 := x = (x ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ z
equation 32767 := x = (x ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ x
equation 32768 := x = (x ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ y
equation 32769 := x = (x ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ z
equation 32770 := x = (x ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ x
equation 32771 := x = (x ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ y
equation 32772 := x = (x ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ z
equation 32773 := x = (x ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ w
equation 32774 := x = (x ◇ (((x ◇ y) ◇ x) ◇ x)) ◇ x
equation 32775 := x = (x ◇ (((x ◇ y) ◇ x) ◇ x)) ◇ y
equation 32776 := x = (x ◇ (((x ◇ y) ◇ x) ◇ x)) ◇ z
equation 32777 := x = (x ◇ (((x ◇ y) ◇ x) ◇ y)) ◇ x
equation 32778 := x = (x ◇ (((x ◇ y) ◇ x) ◇ y)) ◇ y
equation 32779 := x = (x ◇ (((x ◇ y) ◇ x) ◇ y)) ◇ z
equation 32780 := x = (x ◇ (((x ◇ y) ◇ x) ◇ z)) ◇ x
equation 32781 := x = (x ◇ (((x ◇ y) ◇ x) ◇ z)) ◇ y
equation 32782 := x = (x ◇ (((x ◇ y) ◇ x) ◇ z)) ◇ z
equation 32783 := x = (x ◇ (((x ◇ y) ◇ x) ◇ z)) ◇ w
equation 32784 := x = (x ◇ (((x ◇ y) ◇ y) ◇ x)) ◇ x
equation 32785 := x = (x ◇ (((x ◇ y) ◇ y) ◇ x)) ◇ y
equation 32786 := x = (x ◇ (((x ◇ y) ◇ y) ◇ x)) ◇ z
equation 32787 := x = (x ◇ (((x ◇ y) ◇ y) ◇ y)) ◇ x
equation 32788 := x = (x ◇ (((x ◇ y) ◇ y) ◇ y)) ◇ y
equation 32789 := x = (x ◇ (((x ◇ y) ◇ y) ◇ y)) ◇ z
equation 32790 := x = (x ◇ (((x ◇ y) ◇ y) ◇ z)) ◇ x
equation 32791 := x = (x ◇ (((x ◇ y) ◇ y) ◇ z)) ◇ y
equation 32792 := x = (x ◇ (((x ◇ y) ◇ y) ◇ z)) ◇ z
equation 32793 := x = (x ◇ (((x ◇ y) ◇ y) ◇ z)) ◇ w
equation 32794 := x = (x ◇ (((x ◇ y) ◇ z) ◇ x)) ◇ x
equation 32795 := x = (x ◇ (((x ◇ y) ◇ z) ◇ x)) ◇ y
equation 32796 := x = (x ◇ (((x ◇ y) ◇ z) ◇ x)) ◇ z
equation 32797 := x = (x ◇ (((x ◇ y) ◇ z) ◇ x)) ◇ w
equation 32798 := x = (x ◇ (((x ◇ y) ◇ z) ◇ y)) ◇ x
equation 32799 := x = (x ◇ (((x ◇ y) ◇ z) ◇ y)) ◇ y
equation 32800 := x = (x ◇ (((x ◇ y) ◇ z) ◇ y)) ◇ z
equation 32801 := x = (x ◇ (((x ◇ y) ◇ z) ◇ y)) ◇ w
equation 32802 := x = (x ◇ (((x ◇ y) ◇ z) ◇ z)) ◇ x
equation 32803 := x = (x ◇ (((x ◇ y) ◇ z) ◇ z)) ◇ y
equation 32804 := x = (x ◇ (((x ◇ y) ◇ z) ◇ z)) ◇ z
equation 32805 := x = (x ◇ (((x ◇ y) ◇ z) ◇ z)) ◇ w
equation 32806 := x = (x ◇ (((x ◇ y) ◇ z) ◇ w)) ◇ x
equation 32807 := x = (x ◇ (((x ◇ y) ◇ z) ◇ w)) ◇ y
equation 32808 := x = (x ◇ (((x ◇ y) ◇ z) ◇ w)) ◇ z
equation 32809 := x = (x ◇ (((x ◇ y) ◇ z) ◇ w)) ◇ w
equation 32810 := x = (x ◇ (((x ◇ y) ◇ z) ◇ w)) ◇ u
equation 32811 := x = (x ◇ (((y ◇ x) ◇ x) ◇ x)) ◇ x
equation 32812 := x = (x ◇ (((y ◇ x) ◇ x) ◇ x)) ◇ y
equation 32813 := x = (x ◇ (((y ◇ x) ◇ x) ◇ x)) ◇ z
equation 32814 := x = (x ◇ (((y ◇ x) ◇ x) ◇ y)) ◇ x
equation 32815 := x = (x ◇ (((y ◇ x) ◇ x) ◇ y)) ◇ y
equation 32816 := x = (x ◇ (((y ◇ x) ◇ x) ◇ y)) ◇ z
equation 32817 := x = (x ◇ (((y ◇ x) ◇ x) ◇ z)) ◇ x
equation 32818 := x = (x ◇ (((y ◇ x) ◇ x) ◇ z)) ◇ y
equation 32819 := x = (x ◇ (((y ◇ x) ◇ x) ◇ z)) ◇ z
equation 32820 := x = (x ◇ (((y ◇ x) ◇ x) ◇ z)) ◇ w
equation 32821 := x = (x ◇ (((y ◇ x) ◇ y) ◇ x)) ◇ x
equation 32822 := x = (x ◇ (((y ◇ x) ◇ y) ◇ x)) ◇ y
equation 32823 := x = (x ◇ (((y ◇ x) ◇ y) ◇ x)) ◇ z
equation 32824 := x = (x ◇ (((y ◇ x) ◇ y) ◇ y)) ◇ x
equation 32825 := x = (x ◇ (((y ◇ x) ◇ y) ◇ y)) ◇ y
equation 32826 := x = (x ◇ (((y ◇ x) ◇ y) ◇ y)) ◇ z
equation 32827 := x = (x ◇ (((y ◇ x) ◇ y) ◇ z)) ◇ x
equation 32828 := x = (x ◇ (((y ◇ x) ◇ y) ◇ z)) ◇ y
equation 32829 := x = (x ◇ (((y ◇ x) ◇ y) ◇ z)) ◇ z
equation 32830 := x = (x ◇ (((y ◇ x) ◇ y) ◇ z)) ◇ w
equation 32831 := x = (x ◇ (((y ◇ x) ◇ z) ◇ x)) ◇ x
equation 32832 := x = (x ◇ (((y ◇ x) ◇ z) ◇ x)) ◇ y
equation 32833 := x = (x ◇ (((y ◇ x) ◇ z) ◇ x)) ◇ z
equation 32834 := x = (x ◇ (((y ◇ x) ◇ z) ◇ x)) ◇ w
equation 32835 := x = (x ◇ (((y ◇ x) ◇ z) ◇ y)) ◇ x
equation 32836 := x = (x ◇ (((y ◇ x) ◇ z) ◇ y)) ◇ y
equation 32837 := x = (x ◇ (((y ◇ x) ◇ z) ◇ y)) ◇ z
equation 32838 := x = (x ◇ (((y ◇ x) ◇ z) ◇ y)) ◇ w
equation 32839 := x = (x ◇ (((y ◇ x) ◇ z) ◇ z)) ◇ x
equation 32840 := x = (x ◇ (((y ◇ x) ◇ z) ◇ z)) ◇ y
equation 32841 := x = (x ◇ (((y ◇ x) ◇ z) ◇ z)) ◇ z
equation 32842 := x = (x ◇ (((y ◇ x) ◇ z) ◇ z)) ◇ w
equation 32843 := x = (x ◇ (((y ◇ x) ◇ z) ◇ w)) ◇ x
equation 32844 := x = (x ◇ (((y ◇ x) ◇ z) ◇ w)) ◇ y
equation 32845 := x = (x ◇ (((y ◇ x) ◇ z) ◇ w)) ◇ z
equation 32846 := x = (x ◇ (((y ◇ x) ◇ z) ◇ w)) ◇ w
equation 32847 := x = (x ◇ (((y ◇ x) ◇ z) ◇ w)) ◇ u
equation 32848 := x = (x ◇ (((y ◇ y) ◇ x) ◇ x)) ◇ x
equation 32849 := x = (x ◇ (((y ◇ y) ◇ x) ◇ x)) ◇ y
equation 32850 := x = (x ◇ (((y ◇ y) ◇ x) ◇ x)) ◇ z
equation 32851 := x = (x ◇ (((y ◇ y) ◇ x) ◇ y)) ◇ x
equation 32852 := x = (x ◇ (((y ◇ y) ◇ x) ◇ y)) ◇ y
equation 32853 := x = (x ◇ (((y ◇ y) ◇ x) ◇ y)) ◇ z
equation 32854 := x = (x ◇ (((y ◇ y) ◇ x) ◇ z)) ◇ x
equation 32855 := x = (x ◇ (((y ◇ y) ◇ x) ◇ z)) ◇ y
equation 32856 := x = (x ◇ (((y ◇ y) ◇ x) ◇ z)) ◇ z
equation 32857 := x = (x ◇ (((y ◇ y) ◇ x) ◇ z)) ◇ w
equation 32858 := x = (x ◇ (((y ◇ y) ◇ y) ◇ x)) ◇ x
equation 32859 := x = (x ◇ (((y ◇ y) ◇ y) ◇ x)) ◇ y
equation 32860 := x = (x ◇ (((y ◇ y) ◇ y) ◇ x)) ◇ z
equation 32861 := x = (x ◇ (((y ◇ y) ◇ y) ◇ y)) ◇ x
equation 32862 := x = (x ◇ (((y ◇ y) ◇ y) ◇ y)) ◇ y
equation 32863 := x = (x ◇ (((y ◇ y) ◇ y) ◇ y)) ◇ z
equation 32864 := x = (x ◇ (((y ◇ y) ◇ y) ◇ z)) ◇ x
equation 32865 := x = (x ◇ (((y ◇ y) ◇ y) ◇ z)) ◇ y
equation 32866 := x = (x ◇ (((y ◇ y) ◇ y) ◇ z)) ◇ z
equation 32867 := x = (x ◇ (((y ◇ y) ◇ y) ◇ z)) ◇ w
equation 32868 := x = (x ◇ (((y ◇ y) ◇ z) ◇ x)) ◇ x
equation 32869 := x = (x ◇ (((y ◇ y) ◇ z) ◇ x)) ◇ y
equation 32870 := x = (x ◇ (((y ◇ y) ◇ z) ◇ x)) ◇ z
equation 32871 := x = (x ◇ (((y ◇ y) ◇ z) ◇ x)) ◇ w
equation 32872 := x = (x ◇ (((y ◇ y) ◇ z) ◇ y)) ◇ x
equation 32873 := x = (x ◇ (((y ◇ y) ◇ z) ◇ y)) ◇ y
equation 32874 := x = (x ◇ (((y ◇ y) ◇ z) ◇ y)) ◇ z
equation 32875 := x = (x ◇ (((y ◇ y) ◇ z) ◇ y)) ◇ w
equation 32876 := x = (x ◇ (((y ◇ y) ◇ z) ◇ z)) ◇ x
equation 32877 := x = (x ◇ (((y ◇ y) ◇ z) ◇ z)) ◇ y
equation 32878 := x = (x ◇ (((y ◇ y) ◇ z) ◇ z)) ◇ z
equation 32879 := x = (x ◇ (((y ◇ y) ◇ z) ◇ z)) ◇ w
equation 32880 := x = (x ◇ (((y ◇ y) ◇ z) ◇ w)) ◇ x
equation 32881 := x = (x ◇ (((y ◇ y) ◇ z) ◇ w)) ◇ y
equation 32882 := x = (x ◇ (((y ◇ y) ◇ z) ◇ w)) ◇ z
equation 32883 := x = (x ◇ (((y ◇ y) ◇ z) ◇ w)) ◇ w
equation 32884 := x = (x ◇ (((y ◇ y) ◇ z) ◇ w)) ◇ u
equation 32885 := x = (x ◇ (((y ◇ z) ◇ x) ◇ x)) ◇ x
equation 32886 := x = (x ◇ (((y ◇ z) ◇ x) ◇ x)) ◇ y
equation 32887 := x = (x ◇ (((y ◇ z) ◇ x) ◇ x)) ◇ z
equation 32888 := x = (x ◇ (((y ◇ z) ◇ x) ◇ x)) ◇ w
equation 32889 := x = (x ◇ (((y ◇ z) ◇ x) ◇ y)) ◇ x
equation 32890 := x = (x ◇ (((y ◇ z) ◇ x) ◇ y)) ◇ y
equation 32891 := x = (x ◇ (((y ◇ z) ◇ x) ◇ y)) ◇ z
equation 32892 := x = (x ◇ (((y ◇ z) ◇ x) ◇ y)) ◇ w
equation 32893 := x = (x ◇ (((y ◇ z) ◇ x) ◇ z)) ◇ x
equation 32894 := x = (x ◇ (((y ◇ z) ◇ x) ◇ z)) ◇ y
equation 32895 := x = (x ◇ (((y ◇ z) ◇ x) ◇ z)) ◇ z
equation 32896 := x = (x ◇ (((y ◇ z) ◇ x) ◇ z)) ◇ w
equation 32897 := x = (x ◇ (((y ◇ z) ◇ x) ◇ w)) ◇ x
equation 32898 := x = (x ◇ (((y ◇ z) ◇ x) ◇ w)) ◇ y
equation 32899 := x = (x ◇ (((y ◇ z) ◇ x) ◇ w)) ◇ z
equation 32900 := x = (x ◇ (((y ◇ z) ◇ x) ◇ w)) ◇ w
equation 32901 := x = (x ◇ (((y ◇ z) ◇ x) ◇ w)) ◇ u
equation 32902 := x = (x ◇ (((y ◇ z) ◇ y) ◇ x)) ◇ x
equation 32903 := x = (x ◇ (((y ◇ z) ◇ y) ◇ x)) ◇ y
equation 32904 := x = (x ◇ (((y ◇ z) ◇ y) ◇ x)) ◇ z
equation 32905 := x = (x ◇ (((y ◇ z) ◇ y) ◇ x)) ◇ w
equation 32906 := x = (x ◇ (((y ◇ z) ◇ y) ◇ y)) ◇ x
equation 32907 := x = (x ◇ (((y ◇ z) ◇ y) ◇ y)) ◇ y
equation 32908 := x = (x ◇ (((y ◇ z) ◇ y) ◇ y)) ◇ z
equation 32909 := x = (x ◇ (((y ◇ z) ◇ y) ◇ y)) ◇ w
equation 32910 := x = (x ◇ (((y ◇ z) ◇ y) ◇ z)) ◇ x
equation 32911 := x = (x ◇ (((y ◇ z) ◇ y) ◇ z)) ◇ y
equation 32912 := x = (x ◇ (((y ◇ z) ◇ y) ◇ z)) ◇ z
equation 32913 := x = (x ◇ (((y ◇ z) ◇ y) ◇ z)) ◇ w
equation 32914 := x = (x ◇ (((y ◇ z) ◇ y) ◇ w)) ◇ x
equation 32915 := x = (x ◇ (((y ◇ z) ◇ y) ◇ w)) ◇ y
equation 32916 := x = (x ◇ (((y ◇ z) ◇ y) ◇ w)) ◇ z
equation 32917 := x = (x ◇ (((y ◇ z) ◇ y) ◇ w)) ◇ w
equation 32918 := x = (x ◇ (((y ◇ z) ◇ y) ◇ w)) ◇ u
equation 32919 := x = (x ◇ (((y ◇ z) ◇ z) ◇ x)) ◇ x
equation 32920 := x = (x ◇ (((y ◇ z) ◇ z) ◇ x)) ◇ y
equation 32921 := x = (x ◇ (((y ◇ z) ◇ z) ◇ x)) ◇ z
equation 32922 := x = (x ◇ (((y ◇ z) ◇ z) ◇ x)) ◇ w
equation 32923 := x = (x ◇ (((y ◇ z) ◇ z) ◇ y)) ◇ x
equation 32924 := x = (x ◇ (((y ◇ z) ◇ z) ◇ y)) ◇ y
equation 32925 := x = (x ◇ (((y ◇ z) ◇ z) ◇ y)) ◇ z
equation 32926 := x = (x ◇ (((y ◇ z) ◇ z) ◇ y)) ◇ w
equation 32927 := x = (x ◇ (((y ◇ z) ◇ z) ◇ z)) ◇ x
equation 32928 := x = (x ◇ (((y ◇ z) ◇ z) ◇ z)) ◇ y
equation 32929 := x = (x ◇ (((y ◇ z) ◇ z) ◇ z)) ◇ z
equation 32930 := x = (x ◇ (((y ◇ z) ◇ z) ◇ z)) ◇ w
equation 32931 := x = (x ◇ (((y ◇ z) ◇ z) ◇ w)) ◇ x
equation 32932 := x = (x ◇ (((y ◇ z) ◇ z) ◇ w)) ◇ y
equation 32933 := x = (x ◇ (((y ◇ z) ◇ z) ◇ w)) ◇ z
equation 32934 := x = (x ◇ (((y ◇ z) ◇ z) ◇ w)) ◇ w
equation 32935 := x = (x ◇ (((y ◇ z) ◇ z) ◇ w)) ◇ u
equation 32936 := x = (x ◇ (((y ◇ z) ◇ w) ◇ x)) ◇ x
equation 32937 := x = (x ◇ (((y ◇ z) ◇ w) ◇ x)) ◇ y
equation 32938 := x = (x ◇ (((y ◇ z) ◇ w) ◇ x)) ◇ z
equation 32939 := x = (x ◇ (((y ◇ z) ◇ w) ◇ x)) ◇ w
equation 32940 := x = (x ◇ (((y ◇ z) ◇ w) ◇ x)) ◇ u
equation 32941 := x = (x ◇ (((y ◇ z) ◇ w) ◇ y)) ◇ x
equation 32942 := x = (x ◇ (((y ◇ z) ◇ w) ◇ y)) ◇ y
equation 32943 := x = (x ◇ (((y ◇ z) ◇ w) ◇ y)) ◇ z
equation 32944 := x = (x ◇ (((y ◇ z) ◇ w) ◇ y)) ◇ w
equation 32945 := x = (x ◇ (((y ◇ z) ◇ w) ◇ y)) ◇ u
equation 32946 := x = (x ◇ (((y ◇ z) ◇ w) ◇ z)) ◇ x
equation 32947 := x = (x ◇ (((y ◇ z) ◇ w) ◇ z)) ◇ y
equation 32948 := x = (x ◇ (((y ◇ z) ◇ w) ◇ z)) ◇ z
equation 32949 := x = (x ◇ (((y ◇ z) ◇ w) ◇ z)) ◇ w
equation 32950 := x = (x ◇ (((y ◇ z) ◇ w) ◇ z)) ◇ u
equation 32951 := x = (x ◇ (((y ◇ z) ◇ w) ◇ w)) ◇ x
equation 32952 := x = (x ◇ (((y ◇ z) ◇ w) ◇ w)) ◇ y
equation 32953 := x = (x ◇ (((y ◇ z) ◇ w) ◇ w)) ◇ z
equation 32954 := x = (x ◇ (((y ◇ z) ◇ w) ◇ w)) ◇ w
equation 32955 := x = (x ◇ (((y ◇ z) ◇ w) ◇ w)) ◇ u
equation 32956 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ x
equation 32957 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ y
equation 32958 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ z
equation 32959 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ w
equation 32960 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ u
equation 32961 := x = (x ◇ (((y ◇ z) ◇ w) ◇ u)) ◇ v
equation 32962 := x = (y ◇ (((x ◇ x) ◇ x) ◇ x)) ◇ x
equation 32963 := x = (y ◇ (((x ◇ x) ◇ x) ◇ x)) ◇ y
equation 32964 := x = (y ◇ (((x ◇ x) ◇ x) ◇ x)) ◇ z
equation 32965 := x = (y ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ x
equation 32966 := x = (y ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ y
equation 32967 := x = (y ◇ (((x ◇ x) ◇ x) ◇ y)) ◇ z
equation 32968 := x = (y ◇ (((x ◇ x) ◇ x) ◇ z)) ◇ x
equation 32969 := x = (y ◇ (((x ◇ x) ◇ x) ◇ z)) ◇ y
equation 32970 := x = (y ◇ (((x ◇ x) ◇ x) ◇ z)) ◇ z
equation 32971 := x = (y ◇ (((x ◇ x) ◇ x) ◇ z)) ◇ w
equation 32972 := x = (y ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ x
equation 32973 := x = (y ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ y
equation 32974 := x = (y ◇ (((x ◇ x) ◇ y) ◇ x)) ◇ z
equation 32975 := x = (y ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ x
equation 32976 := x = (y ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ y
equation 32977 := x = (y ◇ (((x ◇ x) ◇ y) ◇ y)) ◇ z
equation 32978 := x = (y ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ x
equation 32979 := x = (y ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ y
equation 32980 := x = (y ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ z
equation 32981 := x = (y ◇ (((x ◇ x) ◇ y) ◇ z)) ◇ w
equation 32982 := x = (y ◇ (((x ◇ x) ◇ z) ◇ x)) ◇ x
equation 32983 := x = (y ◇ (((x ◇ x) ◇ z) ◇ x)) ◇ y
equation 32984 := x = (y ◇ (((x ◇ x) ◇ z) ◇ x)) ◇ z
equation 32985 := x = (y ◇ (((x ◇ x) ◇ z) ◇ x)) ◇ w
equation 32986 := x = (y ◇ (((x ◇ x) ◇ z) ◇ y)) ◇ x
equation 32987 := x = (y ◇ (((x ◇ x) ◇ z) ◇ y)) ◇ y
equation 32988 := x = (y ◇ (((x ◇ x) ◇ z) ◇ y)) ◇ z
equation 32989 := x = (y ◇ (((x ◇ x) ◇ z) ◇ y)) ◇ w
equation 32990 := x = (y ◇ (((x ◇ x) ◇ z) ◇ z)) ◇ x
equation 32991 := x = (y ◇ (((x ◇ x) ◇ z) ◇ z)) ◇ y
equation 32992 := x = (y ◇ (((x ◇ x) ◇ z) ◇ z)) ◇ z
equation 32993 := x = (y ◇ (((x ◇ x) ◇ z) ◇ z)) ◇ w
equation 32994 := x = (y ◇ (((x ◇ x) ◇ z) ◇ w)) ◇ x
equation 32995 := x = (y ◇ (((x ◇ x) ◇ z) ◇ w)) ◇ y
equation 32996 := x = (y ◇ (((x ◇ x) ◇ z) ◇ w)) ◇ z
equation 32997 := x = (y ◇ (((x ◇ x) ◇ z) ◇ w)) ◇ w
equation 32998 := x = (y ◇ (((x ◇ x) ◇ z) ◇ w)) ◇ u
equation 32999 := x = (y ◇ (((x ◇ y) ◇ x) ◇ x)) ◇ x
