import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 57000-57999 -/

equation 57000 := x ◇ (y ◇ z) = (x ◇ (w ◇ y)) ◇ y
equation 57001 := x ◇ (y ◇ z) = (x ◇ (w ◇ y)) ◇ z
equation 57002 := x ◇ (y ◇ z) = (x ◇ (w ◇ y)) ◇ w
equation 57003 := x ◇ (y ◇ z) = (x ◇ (w ◇ y)) ◇ u
equation 57004 := x ◇ (y ◇ z) = (x ◇ (w ◇ z)) ◇ x
equation 57005 := x ◇ (y ◇ z) = (x ◇ (w ◇ z)) ◇ y
equation 57006 := x ◇ (y ◇ z) = (x ◇ (w ◇ z)) ◇ z
equation 57007 := x ◇ (y ◇ z) = (x ◇ (w ◇ z)) ◇ w
equation 57008 := x ◇ (y ◇ z) = (x ◇ (w ◇ z)) ◇ u
equation 57009 := x ◇ (y ◇ z) = (x ◇ (w ◇ w)) ◇ x
equation 57010 := x ◇ (y ◇ z) = (x ◇ (w ◇ w)) ◇ y
equation 57011 := x ◇ (y ◇ z) = (x ◇ (w ◇ w)) ◇ z
equation 57012 := x ◇ (y ◇ z) = (x ◇ (w ◇ w)) ◇ w
equation 57013 := x ◇ (y ◇ z) = (x ◇ (w ◇ w)) ◇ u
equation 57014 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ x
equation 57015 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ y
equation 57016 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ z
equation 57017 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ w
equation 57018 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ u
equation 57019 := x ◇ (y ◇ z) = (x ◇ (w ◇ u)) ◇ v
equation 57020 := x ◇ (y ◇ z) = (y ◇ (x ◇ x)) ◇ x
equation 57021 := x ◇ (y ◇ z) = (y ◇ (x ◇ x)) ◇ y
equation 57022 := x ◇ (y ◇ z) = (y ◇ (x ◇ x)) ◇ z
equation 57023 := x ◇ (y ◇ z) = (y ◇ (x ◇ x)) ◇ w
equation 57024 := x ◇ (y ◇ z) = (y ◇ (x ◇ y)) ◇ x
equation 57025 := x ◇ (y ◇ z) = (y ◇ (x ◇ y)) ◇ y
equation 57026 := x ◇ (y ◇ z) = (y ◇ (x ◇ y)) ◇ z
equation 57027 := x ◇ (y ◇ z) = (y ◇ (x ◇ y)) ◇ w
equation 57028 := x ◇ (y ◇ z) = (y ◇ (x ◇ z)) ◇ x
equation 57029 := x ◇ (y ◇ z) = (y ◇ (x ◇ z)) ◇ y
equation 57030 := x ◇ (y ◇ z) = (y ◇ (x ◇ z)) ◇ z
equation 57031 := x ◇ (y ◇ z) = (y ◇ (x ◇ z)) ◇ w
equation 57032 := x ◇ (y ◇ z) = (y ◇ (x ◇ w)) ◇ x
equation 57033 := x ◇ (y ◇ z) = (y ◇ (x ◇ w)) ◇ y
equation 57034 := x ◇ (y ◇ z) = (y ◇ (x ◇ w)) ◇ z
equation 57035 := x ◇ (y ◇ z) = (y ◇ (x ◇ w)) ◇ w
equation 57036 := x ◇ (y ◇ z) = (y ◇ (x ◇ w)) ◇ u
equation 57037 := x ◇ (y ◇ z) = (y ◇ (y ◇ x)) ◇ x
equation 57038 := x ◇ (y ◇ z) = (y ◇ (y ◇ x)) ◇ y
equation 57039 := x ◇ (y ◇ z) = (y ◇ (y ◇ x)) ◇ z
equation 57040 := x ◇ (y ◇ z) = (y ◇ (y ◇ x)) ◇ w
equation 57041 := x ◇ (y ◇ z) = (y ◇ (y ◇ y)) ◇ x
equation 57042 := x ◇ (y ◇ z) = (y ◇ (y ◇ y)) ◇ y
equation 57043 := x ◇ (y ◇ z) = (y ◇ (y ◇ y)) ◇ z
equation 57044 := x ◇ (y ◇ z) = (y ◇ (y ◇ y)) ◇ w
equation 57045 := x ◇ (y ◇ z) = (y ◇ (y ◇ z)) ◇ x
equation 57046 := x ◇ (y ◇ z) = (y ◇ (y ◇ z)) ◇ y
equation 57047 := x ◇ (y ◇ z) = (y ◇ (y ◇ z)) ◇ z
equation 57048 := x ◇ (y ◇ z) = (y ◇ (y ◇ z)) ◇ w
equation 57049 := x ◇ (y ◇ z) = (y ◇ (y ◇ w)) ◇ x
equation 57050 := x ◇ (y ◇ z) = (y ◇ (y ◇ w)) ◇ y
equation 57051 := x ◇ (y ◇ z) = (y ◇ (y ◇ w)) ◇ z
equation 57052 := x ◇ (y ◇ z) = (y ◇ (y ◇ w)) ◇ w
equation 57053 := x ◇ (y ◇ z) = (y ◇ (y ◇ w)) ◇ u
equation 57054 := x ◇ (y ◇ z) = (y ◇ (z ◇ x)) ◇ x
equation 57055 := x ◇ (y ◇ z) = (y ◇ (z ◇ x)) ◇ y
equation 57056 := x ◇ (y ◇ z) = (y ◇ (z ◇ x)) ◇ z
equation 57057 := x ◇ (y ◇ z) = (y ◇ (z ◇ x)) ◇ w
equation 57058 := x ◇ (y ◇ z) = (y ◇ (z ◇ y)) ◇ x
equation 57059 := x ◇ (y ◇ z) = (y ◇ (z ◇ y)) ◇ y
equation 57060 := x ◇ (y ◇ z) = (y ◇ (z ◇ y)) ◇ z
equation 57061 := x ◇ (y ◇ z) = (y ◇ (z ◇ y)) ◇ w
equation 57062 := x ◇ (y ◇ z) = (y ◇ (z ◇ z)) ◇ x
equation 57063 := x ◇ (y ◇ z) = (y ◇ (z ◇ z)) ◇ y
equation 57064 := x ◇ (y ◇ z) = (y ◇ (z ◇ z)) ◇ z
equation 57065 := x ◇ (y ◇ z) = (y ◇ (z ◇ z)) ◇ w
equation 57066 := x ◇ (y ◇ z) = (y ◇ (z ◇ w)) ◇ x
equation 57067 := x ◇ (y ◇ z) = (y ◇ (z ◇ w)) ◇ y
equation 57068 := x ◇ (y ◇ z) = (y ◇ (z ◇ w)) ◇ z
equation 57069 := x ◇ (y ◇ z) = (y ◇ (z ◇ w)) ◇ w
equation 57070 := x ◇ (y ◇ z) = (y ◇ (z ◇ w)) ◇ u
equation 57071 := x ◇ (y ◇ z) = (y ◇ (w ◇ x)) ◇ x
equation 57072 := x ◇ (y ◇ z) = (y ◇ (w ◇ x)) ◇ y
equation 57073 := x ◇ (y ◇ z) = (y ◇ (w ◇ x)) ◇ z
equation 57074 := x ◇ (y ◇ z) = (y ◇ (w ◇ x)) ◇ w
equation 57075 := x ◇ (y ◇ z) = (y ◇ (w ◇ x)) ◇ u
equation 57076 := x ◇ (y ◇ z) = (y ◇ (w ◇ y)) ◇ x
equation 57077 := x ◇ (y ◇ z) = (y ◇ (w ◇ y)) ◇ y
equation 57078 := x ◇ (y ◇ z) = (y ◇ (w ◇ y)) ◇ z
equation 57079 := x ◇ (y ◇ z) = (y ◇ (w ◇ y)) ◇ w
equation 57080 := x ◇ (y ◇ z) = (y ◇ (w ◇ y)) ◇ u
equation 57081 := x ◇ (y ◇ z) = (y ◇ (w ◇ z)) ◇ x
equation 57082 := x ◇ (y ◇ z) = (y ◇ (w ◇ z)) ◇ y
equation 57083 := x ◇ (y ◇ z) = (y ◇ (w ◇ z)) ◇ z
equation 57084 := x ◇ (y ◇ z) = (y ◇ (w ◇ z)) ◇ w
equation 57085 := x ◇ (y ◇ z) = (y ◇ (w ◇ z)) ◇ u
equation 57086 := x ◇ (y ◇ z) = (y ◇ (w ◇ w)) ◇ x
equation 57087 := x ◇ (y ◇ z) = (y ◇ (w ◇ w)) ◇ y
equation 57088 := x ◇ (y ◇ z) = (y ◇ (w ◇ w)) ◇ z
equation 57089 := x ◇ (y ◇ z) = (y ◇ (w ◇ w)) ◇ w
equation 57090 := x ◇ (y ◇ z) = (y ◇ (w ◇ w)) ◇ u
equation 57091 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ x
equation 57092 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ y
equation 57093 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ z
equation 57094 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ w
equation 57095 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ u
equation 57096 := x ◇ (y ◇ z) = (y ◇ (w ◇ u)) ◇ v
equation 57097 := x ◇ (y ◇ z) = (z ◇ (x ◇ x)) ◇ x
equation 57098 := x ◇ (y ◇ z) = (z ◇ (x ◇ x)) ◇ y
equation 57099 := x ◇ (y ◇ z) = (z ◇ (x ◇ x)) ◇ z
equation 57100 := x ◇ (y ◇ z) = (z ◇ (x ◇ x)) ◇ w
equation 57101 := x ◇ (y ◇ z) = (z ◇ (x ◇ y)) ◇ x
equation 57102 := x ◇ (y ◇ z) = (z ◇ (x ◇ y)) ◇ y
equation 57103 := x ◇ (y ◇ z) = (z ◇ (x ◇ y)) ◇ z
equation 57104 := x ◇ (y ◇ z) = (z ◇ (x ◇ y)) ◇ w
equation 57105 := x ◇ (y ◇ z) = (z ◇ (x ◇ z)) ◇ x
equation 57106 := x ◇ (y ◇ z) = (z ◇ (x ◇ z)) ◇ y
equation 57107 := x ◇ (y ◇ z) = (z ◇ (x ◇ z)) ◇ z
equation 57108 := x ◇ (y ◇ z) = (z ◇ (x ◇ z)) ◇ w
equation 57109 := x ◇ (y ◇ z) = (z ◇ (x ◇ w)) ◇ x
equation 57110 := x ◇ (y ◇ z) = (z ◇ (x ◇ w)) ◇ y
equation 57111 := x ◇ (y ◇ z) = (z ◇ (x ◇ w)) ◇ z
equation 57112 := x ◇ (y ◇ z) = (z ◇ (x ◇ w)) ◇ w
equation 57113 := x ◇ (y ◇ z) = (z ◇ (x ◇ w)) ◇ u
equation 57114 := x ◇ (y ◇ z) = (z ◇ (y ◇ x)) ◇ x
equation 57115 := x ◇ (y ◇ z) = (z ◇ (y ◇ x)) ◇ y
equation 57116 := x ◇ (y ◇ z) = (z ◇ (y ◇ x)) ◇ z
equation 57117 := x ◇ (y ◇ z) = (z ◇ (y ◇ x)) ◇ w
equation 57118 := x ◇ (y ◇ z) = (z ◇ (y ◇ y)) ◇ x
equation 57119 := x ◇ (y ◇ z) = (z ◇ (y ◇ y)) ◇ y
equation 57120 := x ◇ (y ◇ z) = (z ◇ (y ◇ y)) ◇ z
equation 57121 := x ◇ (y ◇ z) = (z ◇ (y ◇ y)) ◇ w
equation 57122 := x ◇ (y ◇ z) = (z ◇ (y ◇ z)) ◇ x
equation 57123 := x ◇ (y ◇ z) = (z ◇ (y ◇ z)) ◇ y
equation 57124 := x ◇ (y ◇ z) = (z ◇ (y ◇ z)) ◇ z
equation 57125 := x ◇ (y ◇ z) = (z ◇ (y ◇ z)) ◇ w
equation 57126 := x ◇ (y ◇ z) = (z ◇ (y ◇ w)) ◇ x
equation 57127 := x ◇ (y ◇ z) = (z ◇ (y ◇ w)) ◇ y
equation 57128 := x ◇ (y ◇ z) = (z ◇ (y ◇ w)) ◇ z
equation 57129 := x ◇ (y ◇ z) = (z ◇ (y ◇ w)) ◇ w
equation 57130 := x ◇ (y ◇ z) = (z ◇ (y ◇ w)) ◇ u
equation 57131 := x ◇ (y ◇ z) = (z ◇ (z ◇ x)) ◇ x
equation 57132 := x ◇ (y ◇ z) = (z ◇ (z ◇ x)) ◇ y
equation 57133 := x ◇ (y ◇ z) = (z ◇ (z ◇ x)) ◇ z
equation 57134 := x ◇ (y ◇ z) = (z ◇ (z ◇ x)) ◇ w
equation 57135 := x ◇ (y ◇ z) = (z ◇ (z ◇ y)) ◇ x
equation 57136 := x ◇ (y ◇ z) = (z ◇ (z ◇ y)) ◇ y
equation 57137 := x ◇ (y ◇ z) = (z ◇ (z ◇ y)) ◇ z
equation 57138 := x ◇ (y ◇ z) = (z ◇ (z ◇ y)) ◇ w
equation 57139 := x ◇ (y ◇ z) = (z ◇ (z ◇ z)) ◇ x
equation 57140 := x ◇ (y ◇ z) = (z ◇ (z ◇ z)) ◇ y
equation 57141 := x ◇ (y ◇ z) = (z ◇ (z ◇ z)) ◇ z
equation 57142 := x ◇ (y ◇ z) = (z ◇ (z ◇ z)) ◇ w
equation 57143 := x ◇ (y ◇ z) = (z ◇ (z ◇ w)) ◇ x
equation 57144 := x ◇ (y ◇ z) = (z ◇ (z ◇ w)) ◇ y
equation 57145 := x ◇ (y ◇ z) = (z ◇ (z ◇ w)) ◇ z
equation 57146 := x ◇ (y ◇ z) = (z ◇ (z ◇ w)) ◇ w
equation 57147 := x ◇ (y ◇ z) = (z ◇ (z ◇ w)) ◇ u
equation 57148 := x ◇ (y ◇ z) = (z ◇ (w ◇ x)) ◇ x
equation 57149 := x ◇ (y ◇ z) = (z ◇ (w ◇ x)) ◇ y
equation 57150 := x ◇ (y ◇ z) = (z ◇ (w ◇ x)) ◇ z
equation 57151 := x ◇ (y ◇ z) = (z ◇ (w ◇ x)) ◇ w
equation 57152 := x ◇ (y ◇ z) = (z ◇ (w ◇ x)) ◇ u
equation 57153 := x ◇ (y ◇ z) = (z ◇ (w ◇ y)) ◇ x
equation 57154 := x ◇ (y ◇ z) = (z ◇ (w ◇ y)) ◇ y
equation 57155 := x ◇ (y ◇ z) = (z ◇ (w ◇ y)) ◇ z
equation 57156 := x ◇ (y ◇ z) = (z ◇ (w ◇ y)) ◇ w
equation 57157 := x ◇ (y ◇ z) = (z ◇ (w ◇ y)) ◇ u
equation 57158 := x ◇ (y ◇ z) = (z ◇ (w ◇ z)) ◇ x
equation 57159 := x ◇ (y ◇ z) = (z ◇ (w ◇ z)) ◇ y
equation 57160 := x ◇ (y ◇ z) = (z ◇ (w ◇ z)) ◇ z
equation 57161 := x ◇ (y ◇ z) = (z ◇ (w ◇ z)) ◇ w
equation 57162 := x ◇ (y ◇ z) = (z ◇ (w ◇ z)) ◇ u
equation 57163 := x ◇ (y ◇ z) = (z ◇ (w ◇ w)) ◇ x
equation 57164 := x ◇ (y ◇ z) = (z ◇ (w ◇ w)) ◇ y
equation 57165 := x ◇ (y ◇ z) = (z ◇ (w ◇ w)) ◇ z
equation 57166 := x ◇ (y ◇ z) = (z ◇ (w ◇ w)) ◇ w
equation 57167 := x ◇ (y ◇ z) = (z ◇ (w ◇ w)) ◇ u
equation 57168 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ x
equation 57169 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ y
equation 57170 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ z
equation 57171 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ w
equation 57172 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ u
equation 57173 := x ◇ (y ◇ z) = (z ◇ (w ◇ u)) ◇ v
equation 57174 := x ◇ (y ◇ z) = (w ◇ (x ◇ x)) ◇ x
equation 57175 := x ◇ (y ◇ z) = (w ◇ (x ◇ x)) ◇ y
equation 57176 := x ◇ (y ◇ z) = (w ◇ (x ◇ x)) ◇ z
equation 57177 := x ◇ (y ◇ z) = (w ◇ (x ◇ x)) ◇ w
equation 57178 := x ◇ (y ◇ z) = (w ◇ (x ◇ x)) ◇ u
equation 57179 := x ◇ (y ◇ z) = (w ◇ (x ◇ y)) ◇ x
equation 57180 := x ◇ (y ◇ z) = (w ◇ (x ◇ y)) ◇ y
equation 57181 := x ◇ (y ◇ z) = (w ◇ (x ◇ y)) ◇ z
equation 57182 := x ◇ (y ◇ z) = (w ◇ (x ◇ y)) ◇ w
equation 57183 := x ◇ (y ◇ z) = (w ◇ (x ◇ y)) ◇ u
equation 57184 := x ◇ (y ◇ z) = (w ◇ (x ◇ z)) ◇ x
equation 57185 := x ◇ (y ◇ z) = (w ◇ (x ◇ z)) ◇ y
equation 57186 := x ◇ (y ◇ z) = (w ◇ (x ◇ z)) ◇ z
equation 57187 := x ◇ (y ◇ z) = (w ◇ (x ◇ z)) ◇ w
equation 57188 := x ◇ (y ◇ z) = (w ◇ (x ◇ z)) ◇ u
equation 57189 := x ◇ (y ◇ z) = (w ◇ (x ◇ w)) ◇ x
equation 57190 := x ◇ (y ◇ z) = (w ◇ (x ◇ w)) ◇ y
equation 57191 := x ◇ (y ◇ z) = (w ◇ (x ◇ w)) ◇ z
equation 57192 := x ◇ (y ◇ z) = (w ◇ (x ◇ w)) ◇ w
equation 57193 := x ◇ (y ◇ z) = (w ◇ (x ◇ w)) ◇ u
equation 57194 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ x
equation 57195 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ y
equation 57196 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ z
equation 57197 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ w
equation 57198 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ u
equation 57199 := x ◇ (y ◇ z) = (w ◇ (x ◇ u)) ◇ v
equation 57200 := x ◇ (y ◇ z) = (w ◇ (y ◇ x)) ◇ x
equation 57201 := x ◇ (y ◇ z) = (w ◇ (y ◇ x)) ◇ y
equation 57202 := x ◇ (y ◇ z) = (w ◇ (y ◇ x)) ◇ z
equation 57203 := x ◇ (y ◇ z) = (w ◇ (y ◇ x)) ◇ w
equation 57204 := x ◇ (y ◇ z) = (w ◇ (y ◇ x)) ◇ u
equation 57205 := x ◇ (y ◇ z) = (w ◇ (y ◇ y)) ◇ x
equation 57206 := x ◇ (y ◇ z) = (w ◇ (y ◇ y)) ◇ y
equation 57207 := x ◇ (y ◇ z) = (w ◇ (y ◇ y)) ◇ z
equation 57208 := x ◇ (y ◇ z) = (w ◇ (y ◇ y)) ◇ w
equation 57209 := x ◇ (y ◇ z) = (w ◇ (y ◇ y)) ◇ u
equation 57210 := x ◇ (y ◇ z) = (w ◇ (y ◇ z)) ◇ x
equation 57211 := x ◇ (y ◇ z) = (w ◇ (y ◇ z)) ◇ y
equation 57212 := x ◇ (y ◇ z) = (w ◇ (y ◇ z)) ◇ z
equation 57213 := x ◇ (y ◇ z) = (w ◇ (y ◇ z)) ◇ w
equation 57214 := x ◇ (y ◇ z) = (w ◇ (y ◇ z)) ◇ u
equation 57215 := x ◇ (y ◇ z) = (w ◇ (y ◇ w)) ◇ x
equation 57216 := x ◇ (y ◇ z) = (w ◇ (y ◇ w)) ◇ y
equation 57217 := x ◇ (y ◇ z) = (w ◇ (y ◇ w)) ◇ z
equation 57218 := x ◇ (y ◇ z) = (w ◇ (y ◇ w)) ◇ w
equation 57219 := x ◇ (y ◇ z) = (w ◇ (y ◇ w)) ◇ u
equation 57220 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ x
equation 57221 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ y
equation 57222 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ z
equation 57223 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ w
equation 57224 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ u
equation 57225 := x ◇ (y ◇ z) = (w ◇ (y ◇ u)) ◇ v
equation 57226 := x ◇ (y ◇ z) = (w ◇ (z ◇ x)) ◇ x
equation 57227 := x ◇ (y ◇ z) = (w ◇ (z ◇ x)) ◇ y
equation 57228 := x ◇ (y ◇ z) = (w ◇ (z ◇ x)) ◇ z
equation 57229 := x ◇ (y ◇ z) = (w ◇ (z ◇ x)) ◇ w
equation 57230 := x ◇ (y ◇ z) = (w ◇ (z ◇ x)) ◇ u
equation 57231 := x ◇ (y ◇ z) = (w ◇ (z ◇ y)) ◇ x
equation 57232 := x ◇ (y ◇ z) = (w ◇ (z ◇ y)) ◇ y
equation 57233 := x ◇ (y ◇ z) = (w ◇ (z ◇ y)) ◇ z
equation 57234 := x ◇ (y ◇ z) = (w ◇ (z ◇ y)) ◇ w
equation 57235 := x ◇ (y ◇ z) = (w ◇ (z ◇ y)) ◇ u
equation 57236 := x ◇ (y ◇ z) = (w ◇ (z ◇ z)) ◇ x
equation 57237 := x ◇ (y ◇ z) = (w ◇ (z ◇ z)) ◇ y
equation 57238 := x ◇ (y ◇ z) = (w ◇ (z ◇ z)) ◇ z
equation 57239 := x ◇ (y ◇ z) = (w ◇ (z ◇ z)) ◇ w
equation 57240 := x ◇ (y ◇ z) = (w ◇ (z ◇ z)) ◇ u
equation 57241 := x ◇ (y ◇ z) = (w ◇ (z ◇ w)) ◇ x
equation 57242 := x ◇ (y ◇ z) = (w ◇ (z ◇ w)) ◇ y
equation 57243 := x ◇ (y ◇ z) = (w ◇ (z ◇ w)) ◇ z
equation 57244 := x ◇ (y ◇ z) = (w ◇ (z ◇ w)) ◇ w
equation 57245 := x ◇ (y ◇ z) = (w ◇ (z ◇ w)) ◇ u
equation 57246 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ x
equation 57247 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ y
equation 57248 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ z
equation 57249 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ w
equation 57250 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ u
equation 57251 := x ◇ (y ◇ z) = (w ◇ (z ◇ u)) ◇ v
equation 57252 := x ◇ (y ◇ z) = (w ◇ (w ◇ x)) ◇ x
equation 57253 := x ◇ (y ◇ z) = (w ◇ (w ◇ x)) ◇ y
equation 57254 := x ◇ (y ◇ z) = (w ◇ (w ◇ x)) ◇ z
equation 57255 := x ◇ (y ◇ z) = (w ◇ (w ◇ x)) ◇ w
equation 57256 := x ◇ (y ◇ z) = (w ◇ (w ◇ x)) ◇ u
equation 57257 := x ◇ (y ◇ z) = (w ◇ (w ◇ y)) ◇ x
equation 57258 := x ◇ (y ◇ z) = (w ◇ (w ◇ y)) ◇ y
equation 57259 := x ◇ (y ◇ z) = (w ◇ (w ◇ y)) ◇ z
equation 57260 := x ◇ (y ◇ z) = (w ◇ (w ◇ y)) ◇ w
equation 57261 := x ◇ (y ◇ z) = (w ◇ (w ◇ y)) ◇ u
equation 57262 := x ◇ (y ◇ z) = (w ◇ (w ◇ z)) ◇ x
equation 57263 := x ◇ (y ◇ z) = (w ◇ (w ◇ z)) ◇ y
equation 57264 := x ◇ (y ◇ z) = (w ◇ (w ◇ z)) ◇ z
equation 57265 := x ◇ (y ◇ z) = (w ◇ (w ◇ z)) ◇ w
equation 57266 := x ◇ (y ◇ z) = (w ◇ (w ◇ z)) ◇ u
equation 57267 := x ◇ (y ◇ z) = (w ◇ (w ◇ w)) ◇ x
equation 57268 := x ◇ (y ◇ z) = (w ◇ (w ◇ w)) ◇ y
equation 57269 := x ◇ (y ◇ z) = (w ◇ (w ◇ w)) ◇ z
equation 57270 := x ◇ (y ◇ z) = (w ◇ (w ◇ w)) ◇ w
equation 57271 := x ◇ (y ◇ z) = (w ◇ (w ◇ w)) ◇ u
equation 57272 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ x
equation 57273 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ y
equation 57274 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ z
equation 57275 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ w
equation 57276 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ u
equation 57277 := x ◇ (y ◇ z) = (w ◇ (w ◇ u)) ◇ v
equation 57278 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ x
equation 57279 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ y
equation 57280 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ z
equation 57281 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ w
equation 57282 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ u
equation 57283 := x ◇ (y ◇ z) = (w ◇ (u ◇ x)) ◇ v
equation 57284 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ x
equation 57285 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ y
equation 57286 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ z
equation 57287 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ w
equation 57288 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ u
equation 57289 := x ◇ (y ◇ z) = (w ◇ (u ◇ y)) ◇ v
equation 57290 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ x
equation 57291 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ y
equation 57292 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ z
equation 57293 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ w
equation 57294 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ u
equation 57295 := x ◇ (y ◇ z) = (w ◇ (u ◇ z)) ◇ v
equation 57296 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ x
equation 57297 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ y
equation 57298 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ z
equation 57299 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ w
equation 57300 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ u
equation 57301 := x ◇ (y ◇ z) = (w ◇ (u ◇ w)) ◇ v
equation 57302 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ x
equation 57303 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ y
equation 57304 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ z
equation 57305 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ w
equation 57306 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ u
equation 57307 := x ◇ (y ◇ z) = (w ◇ (u ◇ u)) ◇ v
equation 57308 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ x
equation 57309 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ y
equation 57310 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ z
equation 57311 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ w
equation 57312 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ u
equation 57313 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ v
equation 57314 := x ◇ (y ◇ z) = (w ◇ (u ◇ v)) ◇ r
equation 57315 := x ◇ (x ◇ x) = ((x ◇ x) ◇ x) ◇ x
equation 57316 := x ◇ (x ◇ x) = ((x ◇ x) ◇ x) ◇ y
equation 57317 := x ◇ (x ◇ x) = ((x ◇ x) ◇ y) ◇ x
equation 57318 := x ◇ (x ◇ x) = ((x ◇ x) ◇ y) ◇ y
equation 57319 := x ◇ (x ◇ x) = ((x ◇ x) ◇ y) ◇ z
equation 57320 := x ◇ (x ◇ x) = ((x ◇ y) ◇ x) ◇ x
equation 57321 := x ◇ (x ◇ x) = ((x ◇ y) ◇ x) ◇ y
equation 57322 := x ◇ (x ◇ x) = ((x ◇ y) ◇ x) ◇ z
equation 57323 := x ◇ (x ◇ x) = ((x ◇ y) ◇ y) ◇ x
equation 57324 := x ◇ (x ◇ x) = ((x ◇ y) ◇ y) ◇ y
equation 57325 := x ◇ (x ◇ x) = ((x ◇ y) ◇ y) ◇ z
equation 57326 := x ◇ (x ◇ x) = ((x ◇ y) ◇ z) ◇ x
equation 57327 := x ◇ (x ◇ x) = ((x ◇ y) ◇ z) ◇ y
equation 57328 := x ◇ (x ◇ x) = ((x ◇ y) ◇ z) ◇ z
equation 57329 := x ◇ (x ◇ x) = ((x ◇ y) ◇ z) ◇ w
equation 57330 := x ◇ (x ◇ x) = ((y ◇ x) ◇ x) ◇ x
equation 57331 := x ◇ (x ◇ x) = ((y ◇ x) ◇ x) ◇ y
equation 57332 := x ◇ (x ◇ x) = ((y ◇ x) ◇ x) ◇ z
equation 57333 := x ◇ (x ◇ x) = ((y ◇ x) ◇ y) ◇ x
equation 57334 := x ◇ (x ◇ x) = ((y ◇ x) ◇ y) ◇ y
equation 57335 := x ◇ (x ◇ x) = ((y ◇ x) ◇ y) ◇ z
equation 57336 := x ◇ (x ◇ x) = ((y ◇ x) ◇ z) ◇ x
equation 57337 := x ◇ (x ◇ x) = ((y ◇ x) ◇ z) ◇ y
equation 57338 := x ◇ (x ◇ x) = ((y ◇ x) ◇ z) ◇ z
equation 57339 := x ◇ (x ◇ x) = ((y ◇ x) ◇ z) ◇ w
equation 57340 := x ◇ (x ◇ x) = ((y ◇ y) ◇ x) ◇ x
equation 57341 := x ◇ (x ◇ x) = ((y ◇ y) ◇ x) ◇ y
equation 57342 := x ◇ (x ◇ x) = ((y ◇ y) ◇ x) ◇ z
equation 57343 := x ◇ (x ◇ x) = ((y ◇ y) ◇ y) ◇ x
equation 57344 := x ◇ (x ◇ x) = ((y ◇ y) ◇ y) ◇ y
equation 57345 := x ◇ (x ◇ x) = ((y ◇ y) ◇ y) ◇ z
equation 57346 := x ◇ (x ◇ x) = ((y ◇ y) ◇ z) ◇ x
equation 57347 := x ◇ (x ◇ x) = ((y ◇ y) ◇ z) ◇ y
equation 57348 := x ◇ (x ◇ x) = ((y ◇ y) ◇ z) ◇ z
equation 57349 := x ◇ (x ◇ x) = ((y ◇ y) ◇ z) ◇ w
equation 57350 := x ◇ (x ◇ x) = ((y ◇ z) ◇ x) ◇ x
equation 57351 := x ◇ (x ◇ x) = ((y ◇ z) ◇ x) ◇ y
equation 57352 := x ◇ (x ◇ x) = ((y ◇ z) ◇ x) ◇ z
equation 57353 := x ◇ (x ◇ x) = ((y ◇ z) ◇ x) ◇ w
equation 57354 := x ◇ (x ◇ x) = ((y ◇ z) ◇ y) ◇ x
equation 57355 := x ◇ (x ◇ x) = ((y ◇ z) ◇ y) ◇ y
equation 57356 := x ◇ (x ◇ x) = ((y ◇ z) ◇ y) ◇ z
equation 57357 := x ◇ (x ◇ x) = ((y ◇ z) ◇ y) ◇ w
equation 57358 := x ◇ (x ◇ x) = ((y ◇ z) ◇ z) ◇ x
equation 57359 := x ◇ (x ◇ x) = ((y ◇ z) ◇ z) ◇ y
equation 57360 := x ◇ (x ◇ x) = ((y ◇ z) ◇ z) ◇ z
equation 57361 := x ◇ (x ◇ x) = ((y ◇ z) ◇ z) ◇ w
equation 57362 := x ◇ (x ◇ x) = ((y ◇ z) ◇ w) ◇ x
equation 57363 := x ◇ (x ◇ x) = ((y ◇ z) ◇ w) ◇ y
equation 57364 := x ◇ (x ◇ x) = ((y ◇ z) ◇ w) ◇ z
equation 57365 := x ◇ (x ◇ x) = ((y ◇ z) ◇ w) ◇ w
equation 57366 := x ◇ (x ◇ x) = ((y ◇ z) ◇ w) ◇ u
equation 57367 := x ◇ (x ◇ y) = ((x ◇ x) ◇ x) ◇ x
equation 57368 := x ◇ (x ◇ y) = ((x ◇ x) ◇ x) ◇ y
equation 57369 := x ◇ (x ◇ y) = ((x ◇ x) ◇ x) ◇ z
equation 57370 := x ◇ (x ◇ y) = ((x ◇ x) ◇ y) ◇ x
equation 57371 := x ◇ (x ◇ y) = ((x ◇ x) ◇ y) ◇ y
equation 57372 := x ◇ (x ◇ y) = ((x ◇ x) ◇ y) ◇ z
equation 57373 := x ◇ (x ◇ y) = ((x ◇ x) ◇ z) ◇ x
equation 57374 := x ◇ (x ◇ y) = ((x ◇ x) ◇ z) ◇ y
equation 57375 := x ◇ (x ◇ y) = ((x ◇ x) ◇ z) ◇ z
equation 57376 := x ◇ (x ◇ y) = ((x ◇ x) ◇ z) ◇ w
equation 57377 := x ◇ (x ◇ y) = ((x ◇ y) ◇ x) ◇ x
equation 57378 := x ◇ (x ◇ y) = ((x ◇ y) ◇ x) ◇ y
equation 57379 := x ◇ (x ◇ y) = ((x ◇ y) ◇ x) ◇ z
equation 57380 := x ◇ (x ◇ y) = ((x ◇ y) ◇ y) ◇ x
equation 57381 := x ◇ (x ◇ y) = ((x ◇ y) ◇ y) ◇ y
equation 57382 := x ◇ (x ◇ y) = ((x ◇ y) ◇ y) ◇ z
equation 57383 := x ◇ (x ◇ y) = ((x ◇ y) ◇ z) ◇ x
equation 57384 := x ◇ (x ◇ y) = ((x ◇ y) ◇ z) ◇ y
equation 57385 := x ◇ (x ◇ y) = ((x ◇ y) ◇ z) ◇ z
equation 57386 := x ◇ (x ◇ y) = ((x ◇ y) ◇ z) ◇ w
equation 57387 := x ◇ (x ◇ y) = ((x ◇ z) ◇ x) ◇ x
equation 57388 := x ◇ (x ◇ y) = ((x ◇ z) ◇ x) ◇ y
equation 57389 := x ◇ (x ◇ y) = ((x ◇ z) ◇ x) ◇ z
equation 57390 := x ◇ (x ◇ y) = ((x ◇ z) ◇ x) ◇ w
equation 57391 := x ◇ (x ◇ y) = ((x ◇ z) ◇ y) ◇ x
equation 57392 := x ◇ (x ◇ y) = ((x ◇ z) ◇ y) ◇ y
equation 57393 := x ◇ (x ◇ y) = ((x ◇ z) ◇ y) ◇ z
equation 57394 := x ◇ (x ◇ y) = ((x ◇ z) ◇ y) ◇ w
equation 57395 := x ◇ (x ◇ y) = ((x ◇ z) ◇ z) ◇ x
equation 57396 := x ◇ (x ◇ y) = ((x ◇ z) ◇ z) ◇ y
equation 57397 := x ◇ (x ◇ y) = ((x ◇ z) ◇ z) ◇ z
equation 57398 := x ◇ (x ◇ y) = ((x ◇ z) ◇ z) ◇ w
equation 57399 := x ◇ (x ◇ y) = ((x ◇ z) ◇ w) ◇ x
equation 57400 := x ◇ (x ◇ y) = ((x ◇ z) ◇ w) ◇ y
equation 57401 := x ◇ (x ◇ y) = ((x ◇ z) ◇ w) ◇ z
equation 57402 := x ◇ (x ◇ y) = ((x ◇ z) ◇ w) ◇ w
equation 57403 := x ◇ (x ◇ y) = ((x ◇ z) ◇ w) ◇ u
equation 57404 := x ◇ (x ◇ y) = ((y ◇ x) ◇ x) ◇ x
equation 57405 := x ◇ (x ◇ y) = ((y ◇ x) ◇ x) ◇ y
equation 57406 := x ◇ (x ◇ y) = ((y ◇ x) ◇ x) ◇ z
equation 57407 := x ◇ (x ◇ y) = ((y ◇ x) ◇ y) ◇ x
equation 57408 := x ◇ (x ◇ y) = ((y ◇ x) ◇ y) ◇ y
equation 57409 := x ◇ (x ◇ y) = ((y ◇ x) ◇ y) ◇ z
equation 57410 := x ◇ (x ◇ y) = ((y ◇ x) ◇ z) ◇ x
equation 57411 := x ◇ (x ◇ y) = ((y ◇ x) ◇ z) ◇ y
equation 57412 := x ◇ (x ◇ y) = ((y ◇ x) ◇ z) ◇ z
equation 57413 := x ◇ (x ◇ y) = ((y ◇ x) ◇ z) ◇ w
equation 57414 := x ◇ (x ◇ y) = ((y ◇ y) ◇ x) ◇ x
equation 57415 := x ◇ (x ◇ y) = ((y ◇ y) ◇ x) ◇ y
equation 57416 := x ◇ (x ◇ y) = ((y ◇ y) ◇ x) ◇ z
equation 57417 := x ◇ (x ◇ y) = ((y ◇ y) ◇ y) ◇ x
equation 57418 := x ◇ (x ◇ y) = ((y ◇ y) ◇ y) ◇ y
equation 57419 := x ◇ (x ◇ y) = ((y ◇ y) ◇ y) ◇ z
equation 57420 := x ◇ (x ◇ y) = ((y ◇ y) ◇ z) ◇ x
equation 57421 := x ◇ (x ◇ y) = ((y ◇ y) ◇ z) ◇ y
equation 57422 := x ◇ (x ◇ y) = ((y ◇ y) ◇ z) ◇ z
equation 57423 := x ◇ (x ◇ y) = ((y ◇ y) ◇ z) ◇ w
equation 57424 := x ◇ (x ◇ y) = ((y ◇ z) ◇ x) ◇ x
equation 57425 := x ◇ (x ◇ y) = ((y ◇ z) ◇ x) ◇ y
equation 57426 := x ◇ (x ◇ y) = ((y ◇ z) ◇ x) ◇ z
equation 57427 := x ◇ (x ◇ y) = ((y ◇ z) ◇ x) ◇ w
equation 57428 := x ◇ (x ◇ y) = ((y ◇ z) ◇ y) ◇ x
equation 57429 := x ◇ (x ◇ y) = ((y ◇ z) ◇ y) ◇ y
equation 57430 := x ◇ (x ◇ y) = ((y ◇ z) ◇ y) ◇ z
equation 57431 := x ◇ (x ◇ y) = ((y ◇ z) ◇ y) ◇ w
equation 57432 := x ◇ (x ◇ y) = ((y ◇ z) ◇ z) ◇ x
equation 57433 := x ◇ (x ◇ y) = ((y ◇ z) ◇ z) ◇ y
equation 57434 := x ◇ (x ◇ y) = ((y ◇ z) ◇ z) ◇ z
equation 57435 := x ◇ (x ◇ y) = ((y ◇ z) ◇ z) ◇ w
equation 57436 := x ◇ (x ◇ y) = ((y ◇ z) ◇ w) ◇ x
equation 57437 := x ◇ (x ◇ y) = ((y ◇ z) ◇ w) ◇ y
equation 57438 := x ◇ (x ◇ y) = ((y ◇ z) ◇ w) ◇ z
equation 57439 := x ◇ (x ◇ y) = ((y ◇ z) ◇ w) ◇ w
equation 57440 := x ◇ (x ◇ y) = ((y ◇ z) ◇ w) ◇ u
equation 57441 := x ◇ (x ◇ y) = ((z ◇ x) ◇ x) ◇ x
equation 57442 := x ◇ (x ◇ y) = ((z ◇ x) ◇ x) ◇ y
equation 57443 := x ◇ (x ◇ y) = ((z ◇ x) ◇ x) ◇ z
equation 57444 := x ◇ (x ◇ y) = ((z ◇ x) ◇ x) ◇ w
equation 57445 := x ◇ (x ◇ y) = ((z ◇ x) ◇ y) ◇ x
equation 57446 := x ◇ (x ◇ y) = ((z ◇ x) ◇ y) ◇ y
equation 57447 := x ◇ (x ◇ y) = ((z ◇ x) ◇ y) ◇ z
equation 57448 := x ◇ (x ◇ y) = ((z ◇ x) ◇ y) ◇ w
equation 57449 := x ◇ (x ◇ y) = ((z ◇ x) ◇ z) ◇ x
equation 57450 := x ◇ (x ◇ y) = ((z ◇ x) ◇ z) ◇ y
equation 57451 := x ◇ (x ◇ y) = ((z ◇ x) ◇ z) ◇ z
equation 57452 := x ◇ (x ◇ y) = ((z ◇ x) ◇ z) ◇ w
equation 57453 := x ◇ (x ◇ y) = ((z ◇ x) ◇ w) ◇ x
equation 57454 := x ◇ (x ◇ y) = ((z ◇ x) ◇ w) ◇ y
equation 57455 := x ◇ (x ◇ y) = ((z ◇ x) ◇ w) ◇ z
equation 57456 := x ◇ (x ◇ y) = ((z ◇ x) ◇ w) ◇ w
equation 57457 := x ◇ (x ◇ y) = ((z ◇ x) ◇ w) ◇ u
equation 57458 := x ◇ (x ◇ y) = ((z ◇ y) ◇ x) ◇ x
equation 57459 := x ◇ (x ◇ y) = ((z ◇ y) ◇ x) ◇ y
equation 57460 := x ◇ (x ◇ y) = ((z ◇ y) ◇ x) ◇ z
equation 57461 := x ◇ (x ◇ y) = ((z ◇ y) ◇ x) ◇ w
equation 57462 := x ◇ (x ◇ y) = ((z ◇ y) ◇ y) ◇ x
equation 57463 := x ◇ (x ◇ y) = ((z ◇ y) ◇ y) ◇ y
equation 57464 := x ◇ (x ◇ y) = ((z ◇ y) ◇ y) ◇ z
equation 57465 := x ◇ (x ◇ y) = ((z ◇ y) ◇ y) ◇ w
equation 57466 := x ◇ (x ◇ y) = ((z ◇ y) ◇ z) ◇ x
equation 57467 := x ◇ (x ◇ y) = ((z ◇ y) ◇ z) ◇ y
equation 57468 := x ◇ (x ◇ y) = ((z ◇ y) ◇ z) ◇ z
equation 57469 := x ◇ (x ◇ y) = ((z ◇ y) ◇ z) ◇ w
equation 57470 := x ◇ (x ◇ y) = ((z ◇ y) ◇ w) ◇ x
equation 57471 := x ◇ (x ◇ y) = ((z ◇ y) ◇ w) ◇ y
equation 57472 := x ◇ (x ◇ y) = ((z ◇ y) ◇ w) ◇ z
equation 57473 := x ◇ (x ◇ y) = ((z ◇ y) ◇ w) ◇ w
equation 57474 := x ◇ (x ◇ y) = ((z ◇ y) ◇ w) ◇ u
equation 57475 := x ◇ (x ◇ y) = ((z ◇ z) ◇ x) ◇ x
equation 57476 := x ◇ (x ◇ y) = ((z ◇ z) ◇ x) ◇ y
equation 57477 := x ◇ (x ◇ y) = ((z ◇ z) ◇ x) ◇ z
equation 57478 := x ◇ (x ◇ y) = ((z ◇ z) ◇ x) ◇ w
equation 57479 := x ◇ (x ◇ y) = ((z ◇ z) ◇ y) ◇ x
equation 57480 := x ◇ (x ◇ y) = ((z ◇ z) ◇ y) ◇ y
equation 57481 := x ◇ (x ◇ y) = ((z ◇ z) ◇ y) ◇ z
equation 57482 := x ◇ (x ◇ y) = ((z ◇ z) ◇ y) ◇ w
equation 57483 := x ◇ (x ◇ y) = ((z ◇ z) ◇ z) ◇ x
equation 57484 := x ◇ (x ◇ y) = ((z ◇ z) ◇ z) ◇ y
equation 57485 := x ◇ (x ◇ y) = ((z ◇ z) ◇ z) ◇ z
equation 57486 := x ◇ (x ◇ y) = ((z ◇ z) ◇ z) ◇ w
equation 57487 := x ◇ (x ◇ y) = ((z ◇ z) ◇ w) ◇ x
equation 57488 := x ◇ (x ◇ y) = ((z ◇ z) ◇ w) ◇ y
equation 57489 := x ◇ (x ◇ y) = ((z ◇ z) ◇ w) ◇ z
equation 57490 := x ◇ (x ◇ y) = ((z ◇ z) ◇ w) ◇ w
equation 57491 := x ◇ (x ◇ y) = ((z ◇ z) ◇ w) ◇ u
equation 57492 := x ◇ (x ◇ y) = ((z ◇ w) ◇ x) ◇ x
equation 57493 := x ◇ (x ◇ y) = ((z ◇ w) ◇ x) ◇ y
equation 57494 := x ◇ (x ◇ y) = ((z ◇ w) ◇ x) ◇ z
equation 57495 := x ◇ (x ◇ y) = ((z ◇ w) ◇ x) ◇ w
equation 57496 := x ◇ (x ◇ y) = ((z ◇ w) ◇ x) ◇ u
equation 57497 := x ◇ (x ◇ y) = ((z ◇ w) ◇ y) ◇ x
equation 57498 := x ◇ (x ◇ y) = ((z ◇ w) ◇ y) ◇ y
equation 57499 := x ◇ (x ◇ y) = ((z ◇ w) ◇ y) ◇ z
equation 57500 := x ◇ (x ◇ y) = ((z ◇ w) ◇ y) ◇ w
equation 57501 := x ◇ (x ◇ y) = ((z ◇ w) ◇ y) ◇ u
equation 57502 := x ◇ (x ◇ y) = ((z ◇ w) ◇ z) ◇ x
equation 57503 := x ◇ (x ◇ y) = ((z ◇ w) ◇ z) ◇ y
equation 57504 := x ◇ (x ◇ y) = ((z ◇ w) ◇ z) ◇ z
equation 57505 := x ◇ (x ◇ y) = ((z ◇ w) ◇ z) ◇ w
equation 57506 := x ◇ (x ◇ y) = ((z ◇ w) ◇ z) ◇ u
equation 57507 := x ◇ (x ◇ y) = ((z ◇ w) ◇ w) ◇ x
equation 57508 := x ◇ (x ◇ y) = ((z ◇ w) ◇ w) ◇ y
equation 57509 := x ◇ (x ◇ y) = ((z ◇ w) ◇ w) ◇ z
equation 57510 := x ◇ (x ◇ y) = ((z ◇ w) ◇ w) ◇ w
equation 57511 := x ◇ (x ◇ y) = ((z ◇ w) ◇ w) ◇ u
equation 57512 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ x
equation 57513 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ y
equation 57514 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ z
equation 57515 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ w
equation 57516 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ u
equation 57517 := x ◇ (x ◇ y) = ((z ◇ w) ◇ u) ◇ v
equation 57518 := x ◇ (y ◇ x) = ((x ◇ x) ◇ x) ◇ x
equation 57519 := x ◇ (y ◇ x) = ((x ◇ x) ◇ x) ◇ y
equation 57520 := x ◇ (y ◇ x) = ((x ◇ x) ◇ x) ◇ z
equation 57521 := x ◇ (y ◇ x) = ((x ◇ x) ◇ y) ◇ x
equation 57522 := x ◇ (y ◇ x) = ((x ◇ x) ◇ y) ◇ y
equation 57523 := x ◇ (y ◇ x) = ((x ◇ x) ◇ y) ◇ z
equation 57524 := x ◇ (y ◇ x) = ((x ◇ x) ◇ z) ◇ x
equation 57525 := x ◇ (y ◇ x) = ((x ◇ x) ◇ z) ◇ y
equation 57526 := x ◇ (y ◇ x) = ((x ◇ x) ◇ z) ◇ z
equation 57527 := x ◇ (y ◇ x) = ((x ◇ x) ◇ z) ◇ w
equation 57528 := x ◇ (y ◇ x) = ((x ◇ y) ◇ x) ◇ x
equation 57529 := x ◇ (y ◇ x) = ((x ◇ y) ◇ x) ◇ y
equation 57530 := x ◇ (y ◇ x) = ((x ◇ y) ◇ x) ◇ z
equation 57531 := x ◇ (y ◇ x) = ((x ◇ y) ◇ y) ◇ x
equation 57532 := x ◇ (y ◇ x) = ((x ◇ y) ◇ y) ◇ y
equation 57533 := x ◇ (y ◇ x) = ((x ◇ y) ◇ y) ◇ z
equation 57534 := x ◇ (y ◇ x) = ((x ◇ y) ◇ z) ◇ x
equation 57535 := x ◇ (y ◇ x) = ((x ◇ y) ◇ z) ◇ y
equation 57536 := x ◇ (y ◇ x) = ((x ◇ y) ◇ z) ◇ z
equation 57537 := x ◇ (y ◇ x) = ((x ◇ y) ◇ z) ◇ w
equation 57538 := x ◇ (y ◇ x) = ((x ◇ z) ◇ x) ◇ x
equation 57539 := x ◇ (y ◇ x) = ((x ◇ z) ◇ x) ◇ y
equation 57540 := x ◇ (y ◇ x) = ((x ◇ z) ◇ x) ◇ z
equation 57541 := x ◇ (y ◇ x) = ((x ◇ z) ◇ x) ◇ w
equation 57542 := x ◇ (y ◇ x) = ((x ◇ z) ◇ y) ◇ x
equation 57543 := x ◇ (y ◇ x) = ((x ◇ z) ◇ y) ◇ y
equation 57544 := x ◇ (y ◇ x) = ((x ◇ z) ◇ y) ◇ z
equation 57545 := x ◇ (y ◇ x) = ((x ◇ z) ◇ y) ◇ w
equation 57546 := x ◇ (y ◇ x) = ((x ◇ z) ◇ z) ◇ x
equation 57547 := x ◇ (y ◇ x) = ((x ◇ z) ◇ z) ◇ y
equation 57548 := x ◇ (y ◇ x) = ((x ◇ z) ◇ z) ◇ z
equation 57549 := x ◇ (y ◇ x) = ((x ◇ z) ◇ z) ◇ w
equation 57550 := x ◇ (y ◇ x) = ((x ◇ z) ◇ w) ◇ x
equation 57551 := x ◇ (y ◇ x) = ((x ◇ z) ◇ w) ◇ y
equation 57552 := x ◇ (y ◇ x) = ((x ◇ z) ◇ w) ◇ z
equation 57553 := x ◇ (y ◇ x) = ((x ◇ z) ◇ w) ◇ w
equation 57554 := x ◇ (y ◇ x) = ((x ◇ z) ◇ w) ◇ u
equation 57555 := x ◇ (y ◇ x) = ((y ◇ x) ◇ x) ◇ x
equation 57556 := x ◇ (y ◇ x) = ((y ◇ x) ◇ x) ◇ y
equation 57557 := x ◇ (y ◇ x) = ((y ◇ x) ◇ x) ◇ z
equation 57558 := x ◇ (y ◇ x) = ((y ◇ x) ◇ y) ◇ x
equation 57559 := x ◇ (y ◇ x) = ((y ◇ x) ◇ y) ◇ y
equation 57560 := x ◇ (y ◇ x) = ((y ◇ x) ◇ y) ◇ z
equation 57561 := x ◇ (y ◇ x) = ((y ◇ x) ◇ z) ◇ x
equation 57562 := x ◇ (y ◇ x) = ((y ◇ x) ◇ z) ◇ y
equation 57563 := x ◇ (y ◇ x) = ((y ◇ x) ◇ z) ◇ z
equation 57564 := x ◇ (y ◇ x) = ((y ◇ x) ◇ z) ◇ w
equation 57565 := x ◇ (y ◇ x) = ((y ◇ y) ◇ x) ◇ x
equation 57566 := x ◇ (y ◇ x) = ((y ◇ y) ◇ x) ◇ y
equation 57567 := x ◇ (y ◇ x) = ((y ◇ y) ◇ x) ◇ z
equation 57568 := x ◇ (y ◇ x) = ((y ◇ y) ◇ y) ◇ x
equation 57569 := x ◇ (y ◇ x) = ((y ◇ y) ◇ y) ◇ y
equation 57570 := x ◇ (y ◇ x) = ((y ◇ y) ◇ y) ◇ z
equation 57571 := x ◇ (y ◇ x) = ((y ◇ y) ◇ z) ◇ x
equation 57572 := x ◇ (y ◇ x) = ((y ◇ y) ◇ z) ◇ y
equation 57573 := x ◇ (y ◇ x) = ((y ◇ y) ◇ z) ◇ z
equation 57574 := x ◇ (y ◇ x) = ((y ◇ y) ◇ z) ◇ w
equation 57575 := x ◇ (y ◇ x) = ((y ◇ z) ◇ x) ◇ x
equation 57576 := x ◇ (y ◇ x) = ((y ◇ z) ◇ x) ◇ y
equation 57577 := x ◇ (y ◇ x) = ((y ◇ z) ◇ x) ◇ z
equation 57578 := x ◇ (y ◇ x) = ((y ◇ z) ◇ x) ◇ w
equation 57579 := x ◇ (y ◇ x) = ((y ◇ z) ◇ y) ◇ x
equation 57580 := x ◇ (y ◇ x) = ((y ◇ z) ◇ y) ◇ y
equation 57581 := x ◇ (y ◇ x) = ((y ◇ z) ◇ y) ◇ z
equation 57582 := x ◇ (y ◇ x) = ((y ◇ z) ◇ y) ◇ w
equation 57583 := x ◇ (y ◇ x) = ((y ◇ z) ◇ z) ◇ x
equation 57584 := x ◇ (y ◇ x) = ((y ◇ z) ◇ z) ◇ y
equation 57585 := x ◇ (y ◇ x) = ((y ◇ z) ◇ z) ◇ z
equation 57586 := x ◇ (y ◇ x) = ((y ◇ z) ◇ z) ◇ w
equation 57587 := x ◇ (y ◇ x) = ((y ◇ z) ◇ w) ◇ x
equation 57588 := x ◇ (y ◇ x) = ((y ◇ z) ◇ w) ◇ y
equation 57589 := x ◇ (y ◇ x) = ((y ◇ z) ◇ w) ◇ z
equation 57590 := x ◇ (y ◇ x) = ((y ◇ z) ◇ w) ◇ w
equation 57591 := x ◇ (y ◇ x) = ((y ◇ z) ◇ w) ◇ u
equation 57592 := x ◇ (y ◇ x) = ((z ◇ x) ◇ x) ◇ x
equation 57593 := x ◇ (y ◇ x) = ((z ◇ x) ◇ x) ◇ y
equation 57594 := x ◇ (y ◇ x) = ((z ◇ x) ◇ x) ◇ z
equation 57595 := x ◇ (y ◇ x) = ((z ◇ x) ◇ x) ◇ w
equation 57596 := x ◇ (y ◇ x) = ((z ◇ x) ◇ y) ◇ x
equation 57597 := x ◇ (y ◇ x) = ((z ◇ x) ◇ y) ◇ y
equation 57598 := x ◇ (y ◇ x) = ((z ◇ x) ◇ y) ◇ z
equation 57599 := x ◇ (y ◇ x) = ((z ◇ x) ◇ y) ◇ w
equation 57600 := x ◇ (y ◇ x) = ((z ◇ x) ◇ z) ◇ x
equation 57601 := x ◇ (y ◇ x) = ((z ◇ x) ◇ z) ◇ y
equation 57602 := x ◇ (y ◇ x) = ((z ◇ x) ◇ z) ◇ z
equation 57603 := x ◇ (y ◇ x) = ((z ◇ x) ◇ z) ◇ w
equation 57604 := x ◇ (y ◇ x) = ((z ◇ x) ◇ w) ◇ x
equation 57605 := x ◇ (y ◇ x) = ((z ◇ x) ◇ w) ◇ y
equation 57606 := x ◇ (y ◇ x) = ((z ◇ x) ◇ w) ◇ z
equation 57607 := x ◇ (y ◇ x) = ((z ◇ x) ◇ w) ◇ w
equation 57608 := x ◇ (y ◇ x) = ((z ◇ x) ◇ w) ◇ u
equation 57609 := x ◇ (y ◇ x) = ((z ◇ y) ◇ x) ◇ x
equation 57610 := x ◇ (y ◇ x) = ((z ◇ y) ◇ x) ◇ y
equation 57611 := x ◇ (y ◇ x) = ((z ◇ y) ◇ x) ◇ z
equation 57612 := x ◇ (y ◇ x) = ((z ◇ y) ◇ x) ◇ w
equation 57613 := x ◇ (y ◇ x) = ((z ◇ y) ◇ y) ◇ x
equation 57614 := x ◇ (y ◇ x) = ((z ◇ y) ◇ y) ◇ y
equation 57615 := x ◇ (y ◇ x) = ((z ◇ y) ◇ y) ◇ z
equation 57616 := x ◇ (y ◇ x) = ((z ◇ y) ◇ y) ◇ w
equation 57617 := x ◇ (y ◇ x) = ((z ◇ y) ◇ z) ◇ x
equation 57618 := x ◇ (y ◇ x) = ((z ◇ y) ◇ z) ◇ y
equation 57619 := x ◇ (y ◇ x) = ((z ◇ y) ◇ z) ◇ z
equation 57620 := x ◇ (y ◇ x) = ((z ◇ y) ◇ z) ◇ w
equation 57621 := x ◇ (y ◇ x) = ((z ◇ y) ◇ w) ◇ x
equation 57622 := x ◇ (y ◇ x) = ((z ◇ y) ◇ w) ◇ y
equation 57623 := x ◇ (y ◇ x) = ((z ◇ y) ◇ w) ◇ z
equation 57624 := x ◇ (y ◇ x) = ((z ◇ y) ◇ w) ◇ w
equation 57625 := x ◇ (y ◇ x) = ((z ◇ y) ◇ w) ◇ u
equation 57626 := x ◇ (y ◇ x) = ((z ◇ z) ◇ x) ◇ x
equation 57627 := x ◇ (y ◇ x) = ((z ◇ z) ◇ x) ◇ y
equation 57628 := x ◇ (y ◇ x) = ((z ◇ z) ◇ x) ◇ z
equation 57629 := x ◇ (y ◇ x) = ((z ◇ z) ◇ x) ◇ w
equation 57630 := x ◇ (y ◇ x) = ((z ◇ z) ◇ y) ◇ x
equation 57631 := x ◇ (y ◇ x) = ((z ◇ z) ◇ y) ◇ y
equation 57632 := x ◇ (y ◇ x) = ((z ◇ z) ◇ y) ◇ z
equation 57633 := x ◇ (y ◇ x) = ((z ◇ z) ◇ y) ◇ w
equation 57634 := x ◇ (y ◇ x) = ((z ◇ z) ◇ z) ◇ x
equation 57635 := x ◇ (y ◇ x) = ((z ◇ z) ◇ z) ◇ y
equation 57636 := x ◇ (y ◇ x) = ((z ◇ z) ◇ z) ◇ z
equation 57637 := x ◇ (y ◇ x) = ((z ◇ z) ◇ z) ◇ w
equation 57638 := x ◇ (y ◇ x) = ((z ◇ z) ◇ w) ◇ x
equation 57639 := x ◇ (y ◇ x) = ((z ◇ z) ◇ w) ◇ y
equation 57640 := x ◇ (y ◇ x) = ((z ◇ z) ◇ w) ◇ z
equation 57641 := x ◇ (y ◇ x) = ((z ◇ z) ◇ w) ◇ w
equation 57642 := x ◇ (y ◇ x) = ((z ◇ z) ◇ w) ◇ u
equation 57643 := x ◇ (y ◇ x) = ((z ◇ w) ◇ x) ◇ x
equation 57644 := x ◇ (y ◇ x) = ((z ◇ w) ◇ x) ◇ y
equation 57645 := x ◇ (y ◇ x) = ((z ◇ w) ◇ x) ◇ z
equation 57646 := x ◇ (y ◇ x) = ((z ◇ w) ◇ x) ◇ w
equation 57647 := x ◇ (y ◇ x) = ((z ◇ w) ◇ x) ◇ u
equation 57648 := x ◇ (y ◇ x) = ((z ◇ w) ◇ y) ◇ x
equation 57649 := x ◇ (y ◇ x) = ((z ◇ w) ◇ y) ◇ y
equation 57650 := x ◇ (y ◇ x) = ((z ◇ w) ◇ y) ◇ z
equation 57651 := x ◇ (y ◇ x) = ((z ◇ w) ◇ y) ◇ w
equation 57652 := x ◇ (y ◇ x) = ((z ◇ w) ◇ y) ◇ u
equation 57653 := x ◇ (y ◇ x) = ((z ◇ w) ◇ z) ◇ x
equation 57654 := x ◇ (y ◇ x) = ((z ◇ w) ◇ z) ◇ y
equation 57655 := x ◇ (y ◇ x) = ((z ◇ w) ◇ z) ◇ z
equation 57656 := x ◇ (y ◇ x) = ((z ◇ w) ◇ z) ◇ w
equation 57657 := x ◇ (y ◇ x) = ((z ◇ w) ◇ z) ◇ u
equation 57658 := x ◇ (y ◇ x) = ((z ◇ w) ◇ w) ◇ x
equation 57659 := x ◇ (y ◇ x) = ((z ◇ w) ◇ w) ◇ y
equation 57660 := x ◇ (y ◇ x) = ((z ◇ w) ◇ w) ◇ z
equation 57661 := x ◇ (y ◇ x) = ((z ◇ w) ◇ w) ◇ w
equation 57662 := x ◇ (y ◇ x) = ((z ◇ w) ◇ w) ◇ u
equation 57663 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ x
equation 57664 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ y
equation 57665 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ z
equation 57666 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ w
equation 57667 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ u
equation 57668 := x ◇ (y ◇ x) = ((z ◇ w) ◇ u) ◇ v
equation 57669 := x ◇ (y ◇ y) = ((x ◇ x) ◇ x) ◇ x
equation 57670 := x ◇ (y ◇ y) = ((x ◇ x) ◇ x) ◇ y
equation 57671 := x ◇ (y ◇ y) = ((x ◇ x) ◇ x) ◇ z
equation 57672 := x ◇ (y ◇ y) = ((x ◇ x) ◇ y) ◇ x
equation 57673 := x ◇ (y ◇ y) = ((x ◇ x) ◇ y) ◇ y
equation 57674 := x ◇ (y ◇ y) = ((x ◇ x) ◇ y) ◇ z
equation 57675 := x ◇ (y ◇ y) = ((x ◇ x) ◇ z) ◇ x
equation 57676 := x ◇ (y ◇ y) = ((x ◇ x) ◇ z) ◇ y
equation 57677 := x ◇ (y ◇ y) = ((x ◇ x) ◇ z) ◇ z
equation 57678 := x ◇ (y ◇ y) = ((x ◇ x) ◇ z) ◇ w
equation 57679 := x ◇ (y ◇ y) = ((x ◇ y) ◇ x) ◇ x
equation 57680 := x ◇ (y ◇ y) = ((x ◇ y) ◇ x) ◇ y
equation 57681 := x ◇ (y ◇ y) = ((x ◇ y) ◇ x) ◇ z
equation 57682 := x ◇ (y ◇ y) = ((x ◇ y) ◇ y) ◇ x
equation 57683 := x ◇ (y ◇ y) = ((x ◇ y) ◇ y) ◇ y
equation 57684 := x ◇ (y ◇ y) = ((x ◇ y) ◇ y) ◇ z
equation 57685 := x ◇ (y ◇ y) = ((x ◇ y) ◇ z) ◇ x
equation 57686 := x ◇ (y ◇ y) = ((x ◇ y) ◇ z) ◇ y
equation 57687 := x ◇ (y ◇ y) = ((x ◇ y) ◇ z) ◇ z
equation 57688 := x ◇ (y ◇ y) = ((x ◇ y) ◇ z) ◇ w
equation 57689 := x ◇ (y ◇ y) = ((x ◇ z) ◇ x) ◇ x
equation 57690 := x ◇ (y ◇ y) = ((x ◇ z) ◇ x) ◇ y
equation 57691 := x ◇ (y ◇ y) = ((x ◇ z) ◇ x) ◇ z
equation 57692 := x ◇ (y ◇ y) = ((x ◇ z) ◇ x) ◇ w
equation 57693 := x ◇ (y ◇ y) = ((x ◇ z) ◇ y) ◇ x
equation 57694 := x ◇ (y ◇ y) = ((x ◇ z) ◇ y) ◇ y
equation 57695 := x ◇ (y ◇ y) = ((x ◇ z) ◇ y) ◇ z
equation 57696 := x ◇ (y ◇ y) = ((x ◇ z) ◇ y) ◇ w
equation 57697 := x ◇ (y ◇ y) = ((x ◇ z) ◇ z) ◇ x
equation 57698 := x ◇ (y ◇ y) = ((x ◇ z) ◇ z) ◇ y
equation 57699 := x ◇ (y ◇ y) = ((x ◇ z) ◇ z) ◇ z
equation 57700 := x ◇ (y ◇ y) = ((x ◇ z) ◇ z) ◇ w
equation 57701 := x ◇ (y ◇ y) = ((x ◇ z) ◇ w) ◇ x
equation 57702 := x ◇ (y ◇ y) = ((x ◇ z) ◇ w) ◇ y
equation 57703 := x ◇ (y ◇ y) = ((x ◇ z) ◇ w) ◇ z
equation 57704 := x ◇ (y ◇ y) = ((x ◇ z) ◇ w) ◇ w
equation 57705 := x ◇ (y ◇ y) = ((x ◇ z) ◇ w) ◇ u
equation 57706 := x ◇ (y ◇ y) = ((y ◇ x) ◇ x) ◇ x
equation 57707 := x ◇ (y ◇ y) = ((y ◇ x) ◇ x) ◇ y
equation 57708 := x ◇ (y ◇ y) = ((y ◇ x) ◇ x) ◇ z
equation 57709 := x ◇ (y ◇ y) = ((y ◇ x) ◇ y) ◇ x
equation 57710 := x ◇ (y ◇ y) = ((y ◇ x) ◇ y) ◇ y
equation 57711 := x ◇ (y ◇ y) = ((y ◇ x) ◇ y) ◇ z
equation 57712 := x ◇ (y ◇ y) = ((y ◇ x) ◇ z) ◇ x
equation 57713 := x ◇ (y ◇ y) = ((y ◇ x) ◇ z) ◇ y
equation 57714 := x ◇ (y ◇ y) = ((y ◇ x) ◇ z) ◇ z
equation 57715 := x ◇ (y ◇ y) = ((y ◇ x) ◇ z) ◇ w
equation 57716 := x ◇ (y ◇ y) = ((y ◇ y) ◇ x) ◇ x
equation 57717 := x ◇ (y ◇ y) = ((y ◇ y) ◇ x) ◇ y
equation 57718 := x ◇ (y ◇ y) = ((y ◇ y) ◇ x) ◇ z
equation 57719 := x ◇ (y ◇ y) = ((y ◇ y) ◇ y) ◇ x
equation 57720 := x ◇ (y ◇ y) = ((y ◇ y) ◇ y) ◇ y
equation 57721 := x ◇ (y ◇ y) = ((y ◇ y) ◇ y) ◇ z
equation 57722 := x ◇ (y ◇ y) = ((y ◇ y) ◇ z) ◇ x
equation 57723 := x ◇ (y ◇ y) = ((y ◇ y) ◇ z) ◇ y
equation 57724 := x ◇ (y ◇ y) = ((y ◇ y) ◇ z) ◇ z
equation 57725 := x ◇ (y ◇ y) = ((y ◇ y) ◇ z) ◇ w
equation 57726 := x ◇ (y ◇ y) = ((y ◇ z) ◇ x) ◇ x
equation 57727 := x ◇ (y ◇ y) = ((y ◇ z) ◇ x) ◇ y
equation 57728 := x ◇ (y ◇ y) = ((y ◇ z) ◇ x) ◇ z
equation 57729 := x ◇ (y ◇ y) = ((y ◇ z) ◇ x) ◇ w
equation 57730 := x ◇ (y ◇ y) = ((y ◇ z) ◇ y) ◇ x
equation 57731 := x ◇ (y ◇ y) = ((y ◇ z) ◇ y) ◇ y
equation 57732 := x ◇ (y ◇ y) = ((y ◇ z) ◇ y) ◇ z
equation 57733 := x ◇ (y ◇ y) = ((y ◇ z) ◇ y) ◇ w
equation 57734 := x ◇ (y ◇ y) = ((y ◇ z) ◇ z) ◇ x
equation 57735 := x ◇ (y ◇ y) = ((y ◇ z) ◇ z) ◇ y
equation 57736 := x ◇ (y ◇ y) = ((y ◇ z) ◇ z) ◇ z
equation 57737 := x ◇ (y ◇ y) = ((y ◇ z) ◇ z) ◇ w
equation 57738 := x ◇ (y ◇ y) = ((y ◇ z) ◇ w) ◇ x
equation 57739 := x ◇ (y ◇ y) = ((y ◇ z) ◇ w) ◇ y
equation 57740 := x ◇ (y ◇ y) = ((y ◇ z) ◇ w) ◇ z
equation 57741 := x ◇ (y ◇ y) = ((y ◇ z) ◇ w) ◇ w
equation 57742 := x ◇ (y ◇ y) = ((y ◇ z) ◇ w) ◇ u
equation 57743 := x ◇ (y ◇ y) = ((z ◇ x) ◇ x) ◇ x
equation 57744 := x ◇ (y ◇ y) = ((z ◇ x) ◇ x) ◇ y
equation 57745 := x ◇ (y ◇ y) = ((z ◇ x) ◇ x) ◇ z
equation 57746 := x ◇ (y ◇ y) = ((z ◇ x) ◇ x) ◇ w
equation 57747 := x ◇ (y ◇ y) = ((z ◇ x) ◇ y) ◇ x
equation 57748 := x ◇ (y ◇ y) = ((z ◇ x) ◇ y) ◇ y
equation 57749 := x ◇ (y ◇ y) = ((z ◇ x) ◇ y) ◇ z
equation 57750 := x ◇ (y ◇ y) = ((z ◇ x) ◇ y) ◇ w
equation 57751 := x ◇ (y ◇ y) = ((z ◇ x) ◇ z) ◇ x
equation 57752 := x ◇ (y ◇ y) = ((z ◇ x) ◇ z) ◇ y
equation 57753 := x ◇ (y ◇ y) = ((z ◇ x) ◇ z) ◇ z
equation 57754 := x ◇ (y ◇ y) = ((z ◇ x) ◇ z) ◇ w
equation 57755 := x ◇ (y ◇ y) = ((z ◇ x) ◇ w) ◇ x
equation 57756 := x ◇ (y ◇ y) = ((z ◇ x) ◇ w) ◇ y
equation 57757 := x ◇ (y ◇ y) = ((z ◇ x) ◇ w) ◇ z
equation 57758 := x ◇ (y ◇ y) = ((z ◇ x) ◇ w) ◇ w
equation 57759 := x ◇ (y ◇ y) = ((z ◇ x) ◇ w) ◇ u
equation 57760 := x ◇ (y ◇ y) = ((z ◇ y) ◇ x) ◇ x
equation 57761 := x ◇ (y ◇ y) = ((z ◇ y) ◇ x) ◇ y
equation 57762 := x ◇ (y ◇ y) = ((z ◇ y) ◇ x) ◇ z
equation 57763 := x ◇ (y ◇ y) = ((z ◇ y) ◇ x) ◇ w
equation 57764 := x ◇ (y ◇ y) = ((z ◇ y) ◇ y) ◇ x
equation 57765 := x ◇ (y ◇ y) = ((z ◇ y) ◇ y) ◇ y
equation 57766 := x ◇ (y ◇ y) = ((z ◇ y) ◇ y) ◇ z
equation 57767 := x ◇ (y ◇ y) = ((z ◇ y) ◇ y) ◇ w
equation 57768 := x ◇ (y ◇ y) = ((z ◇ y) ◇ z) ◇ x
equation 57769 := x ◇ (y ◇ y) = ((z ◇ y) ◇ z) ◇ y
equation 57770 := x ◇ (y ◇ y) = ((z ◇ y) ◇ z) ◇ z
equation 57771 := x ◇ (y ◇ y) = ((z ◇ y) ◇ z) ◇ w
equation 57772 := x ◇ (y ◇ y) = ((z ◇ y) ◇ w) ◇ x
equation 57773 := x ◇ (y ◇ y) = ((z ◇ y) ◇ w) ◇ y
equation 57774 := x ◇ (y ◇ y) = ((z ◇ y) ◇ w) ◇ z
equation 57775 := x ◇ (y ◇ y) = ((z ◇ y) ◇ w) ◇ w
equation 57776 := x ◇ (y ◇ y) = ((z ◇ y) ◇ w) ◇ u
equation 57777 := x ◇ (y ◇ y) = ((z ◇ z) ◇ x) ◇ x
equation 57778 := x ◇ (y ◇ y) = ((z ◇ z) ◇ x) ◇ y
equation 57779 := x ◇ (y ◇ y) = ((z ◇ z) ◇ x) ◇ z
equation 57780 := x ◇ (y ◇ y) = ((z ◇ z) ◇ x) ◇ w
equation 57781 := x ◇ (y ◇ y) = ((z ◇ z) ◇ y) ◇ x
equation 57782 := x ◇ (y ◇ y) = ((z ◇ z) ◇ y) ◇ y
equation 57783 := x ◇ (y ◇ y) = ((z ◇ z) ◇ y) ◇ z
equation 57784 := x ◇ (y ◇ y) = ((z ◇ z) ◇ y) ◇ w
equation 57785 := x ◇ (y ◇ y) = ((z ◇ z) ◇ z) ◇ x
equation 57786 := x ◇ (y ◇ y) = ((z ◇ z) ◇ z) ◇ y
equation 57787 := x ◇ (y ◇ y) = ((z ◇ z) ◇ z) ◇ z
equation 57788 := x ◇ (y ◇ y) = ((z ◇ z) ◇ z) ◇ w
equation 57789 := x ◇ (y ◇ y) = ((z ◇ z) ◇ w) ◇ x
equation 57790 := x ◇ (y ◇ y) = ((z ◇ z) ◇ w) ◇ y
equation 57791 := x ◇ (y ◇ y) = ((z ◇ z) ◇ w) ◇ z
equation 57792 := x ◇ (y ◇ y) = ((z ◇ z) ◇ w) ◇ w
equation 57793 := x ◇ (y ◇ y) = ((z ◇ z) ◇ w) ◇ u
equation 57794 := x ◇ (y ◇ y) = ((z ◇ w) ◇ x) ◇ x
equation 57795 := x ◇ (y ◇ y) = ((z ◇ w) ◇ x) ◇ y
equation 57796 := x ◇ (y ◇ y) = ((z ◇ w) ◇ x) ◇ z
equation 57797 := x ◇ (y ◇ y) = ((z ◇ w) ◇ x) ◇ w
equation 57798 := x ◇ (y ◇ y) = ((z ◇ w) ◇ x) ◇ u
equation 57799 := x ◇ (y ◇ y) = ((z ◇ w) ◇ y) ◇ x
equation 57800 := x ◇ (y ◇ y) = ((z ◇ w) ◇ y) ◇ y
equation 57801 := x ◇ (y ◇ y) = ((z ◇ w) ◇ y) ◇ z
equation 57802 := x ◇ (y ◇ y) = ((z ◇ w) ◇ y) ◇ w
equation 57803 := x ◇ (y ◇ y) = ((z ◇ w) ◇ y) ◇ u
equation 57804 := x ◇ (y ◇ y) = ((z ◇ w) ◇ z) ◇ x
equation 57805 := x ◇ (y ◇ y) = ((z ◇ w) ◇ z) ◇ y
equation 57806 := x ◇ (y ◇ y) = ((z ◇ w) ◇ z) ◇ z
equation 57807 := x ◇ (y ◇ y) = ((z ◇ w) ◇ z) ◇ w
equation 57808 := x ◇ (y ◇ y) = ((z ◇ w) ◇ z) ◇ u
equation 57809 := x ◇ (y ◇ y) = ((z ◇ w) ◇ w) ◇ x
equation 57810 := x ◇ (y ◇ y) = ((z ◇ w) ◇ w) ◇ y
equation 57811 := x ◇ (y ◇ y) = ((z ◇ w) ◇ w) ◇ z
equation 57812 := x ◇ (y ◇ y) = ((z ◇ w) ◇ w) ◇ w
equation 57813 := x ◇ (y ◇ y) = ((z ◇ w) ◇ w) ◇ u
equation 57814 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ x
equation 57815 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ y
equation 57816 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ z
equation 57817 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ w
equation 57818 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ u
equation 57819 := x ◇ (y ◇ y) = ((z ◇ w) ◇ u) ◇ v
equation 57820 := x ◇ (y ◇ z) = ((x ◇ x) ◇ x) ◇ x
equation 57821 := x ◇ (y ◇ z) = ((x ◇ x) ◇ x) ◇ y
equation 57822 := x ◇ (y ◇ z) = ((x ◇ x) ◇ x) ◇ z
equation 57823 := x ◇ (y ◇ z) = ((x ◇ x) ◇ x) ◇ w
equation 57824 := x ◇ (y ◇ z) = ((x ◇ x) ◇ y) ◇ x
equation 57825 := x ◇ (y ◇ z) = ((x ◇ x) ◇ y) ◇ y
equation 57826 := x ◇ (y ◇ z) = ((x ◇ x) ◇ y) ◇ z
equation 57827 := x ◇ (y ◇ z) = ((x ◇ x) ◇ y) ◇ w
equation 57828 := x ◇ (y ◇ z) = ((x ◇ x) ◇ z) ◇ x
equation 57829 := x ◇ (y ◇ z) = ((x ◇ x) ◇ z) ◇ y
equation 57830 := x ◇ (y ◇ z) = ((x ◇ x) ◇ z) ◇ z
equation 57831 := x ◇ (y ◇ z) = ((x ◇ x) ◇ z) ◇ w
equation 57832 := x ◇ (y ◇ z) = ((x ◇ x) ◇ w) ◇ x
equation 57833 := x ◇ (y ◇ z) = ((x ◇ x) ◇ w) ◇ y
equation 57834 := x ◇ (y ◇ z) = ((x ◇ x) ◇ w) ◇ z
equation 57835 := x ◇ (y ◇ z) = ((x ◇ x) ◇ w) ◇ w
equation 57836 := x ◇ (y ◇ z) = ((x ◇ x) ◇ w) ◇ u
equation 57837 := x ◇ (y ◇ z) = ((x ◇ y) ◇ x) ◇ x
equation 57838 := x ◇ (y ◇ z) = ((x ◇ y) ◇ x) ◇ y
equation 57839 := x ◇ (y ◇ z) = ((x ◇ y) ◇ x) ◇ z
equation 57840 := x ◇ (y ◇ z) = ((x ◇ y) ◇ x) ◇ w
equation 57841 := x ◇ (y ◇ z) = ((x ◇ y) ◇ y) ◇ x
equation 57842 := x ◇ (y ◇ z) = ((x ◇ y) ◇ y) ◇ y
equation 57843 := x ◇ (y ◇ z) = ((x ◇ y) ◇ y) ◇ z
equation 57844 := x ◇ (y ◇ z) = ((x ◇ y) ◇ y) ◇ w
equation 57845 := x ◇ (y ◇ z) = ((x ◇ y) ◇ z) ◇ x
equation 57846 := x ◇ (y ◇ z) = ((x ◇ y) ◇ z) ◇ y
equation 57847 := x ◇ (y ◇ z) = ((x ◇ y) ◇ z) ◇ z
equation 57848 := x ◇ (y ◇ z) = ((x ◇ y) ◇ z) ◇ w
equation 57849 := x ◇ (y ◇ z) = ((x ◇ y) ◇ w) ◇ x
equation 57850 := x ◇ (y ◇ z) = ((x ◇ y) ◇ w) ◇ y
equation 57851 := x ◇ (y ◇ z) = ((x ◇ y) ◇ w) ◇ z
equation 57852 := x ◇ (y ◇ z) = ((x ◇ y) ◇ w) ◇ w
equation 57853 := x ◇ (y ◇ z) = ((x ◇ y) ◇ w) ◇ u
equation 57854 := x ◇ (y ◇ z) = ((x ◇ z) ◇ x) ◇ x
equation 57855 := x ◇ (y ◇ z) = ((x ◇ z) ◇ x) ◇ y
equation 57856 := x ◇ (y ◇ z) = ((x ◇ z) ◇ x) ◇ z
equation 57857 := x ◇ (y ◇ z) = ((x ◇ z) ◇ x) ◇ w
equation 57858 := x ◇ (y ◇ z) = ((x ◇ z) ◇ y) ◇ x
equation 57859 := x ◇ (y ◇ z) = ((x ◇ z) ◇ y) ◇ y
equation 57860 := x ◇ (y ◇ z) = ((x ◇ z) ◇ y) ◇ z
equation 57861 := x ◇ (y ◇ z) = ((x ◇ z) ◇ y) ◇ w
equation 57862 := x ◇ (y ◇ z) = ((x ◇ z) ◇ z) ◇ x
equation 57863 := x ◇ (y ◇ z) = ((x ◇ z) ◇ z) ◇ y
equation 57864 := x ◇ (y ◇ z) = ((x ◇ z) ◇ z) ◇ z
equation 57865 := x ◇ (y ◇ z) = ((x ◇ z) ◇ z) ◇ w
equation 57866 := x ◇ (y ◇ z) = ((x ◇ z) ◇ w) ◇ x
equation 57867 := x ◇ (y ◇ z) = ((x ◇ z) ◇ w) ◇ y
equation 57868 := x ◇ (y ◇ z) = ((x ◇ z) ◇ w) ◇ z
equation 57869 := x ◇ (y ◇ z) = ((x ◇ z) ◇ w) ◇ w
equation 57870 := x ◇ (y ◇ z) = ((x ◇ z) ◇ w) ◇ u
equation 57871 := x ◇ (y ◇ z) = ((x ◇ w) ◇ x) ◇ x
equation 57872 := x ◇ (y ◇ z) = ((x ◇ w) ◇ x) ◇ y
equation 57873 := x ◇ (y ◇ z) = ((x ◇ w) ◇ x) ◇ z
equation 57874 := x ◇ (y ◇ z) = ((x ◇ w) ◇ x) ◇ w
equation 57875 := x ◇ (y ◇ z) = ((x ◇ w) ◇ x) ◇ u
equation 57876 := x ◇ (y ◇ z) = ((x ◇ w) ◇ y) ◇ x
equation 57877 := x ◇ (y ◇ z) = ((x ◇ w) ◇ y) ◇ y
equation 57878 := x ◇ (y ◇ z) = ((x ◇ w) ◇ y) ◇ z
equation 57879 := x ◇ (y ◇ z) = ((x ◇ w) ◇ y) ◇ w
equation 57880 := x ◇ (y ◇ z) = ((x ◇ w) ◇ y) ◇ u
equation 57881 := x ◇ (y ◇ z) = ((x ◇ w) ◇ z) ◇ x
equation 57882 := x ◇ (y ◇ z) = ((x ◇ w) ◇ z) ◇ y
equation 57883 := x ◇ (y ◇ z) = ((x ◇ w) ◇ z) ◇ z
equation 57884 := x ◇ (y ◇ z) = ((x ◇ w) ◇ z) ◇ w
equation 57885 := x ◇ (y ◇ z) = ((x ◇ w) ◇ z) ◇ u
equation 57886 := x ◇ (y ◇ z) = ((x ◇ w) ◇ w) ◇ x
equation 57887 := x ◇ (y ◇ z) = ((x ◇ w) ◇ w) ◇ y
equation 57888 := x ◇ (y ◇ z) = ((x ◇ w) ◇ w) ◇ z
equation 57889 := x ◇ (y ◇ z) = ((x ◇ w) ◇ w) ◇ w
equation 57890 := x ◇ (y ◇ z) = ((x ◇ w) ◇ w) ◇ u
equation 57891 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ x
equation 57892 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ y
equation 57893 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ z
equation 57894 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ w
equation 57895 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ u
equation 57896 := x ◇ (y ◇ z) = ((x ◇ w) ◇ u) ◇ v
equation 57897 := x ◇ (y ◇ z) = ((y ◇ x) ◇ x) ◇ x
equation 57898 := x ◇ (y ◇ z) = ((y ◇ x) ◇ x) ◇ y
equation 57899 := x ◇ (y ◇ z) = ((y ◇ x) ◇ x) ◇ z
equation 57900 := x ◇ (y ◇ z) = ((y ◇ x) ◇ x) ◇ w
equation 57901 := x ◇ (y ◇ z) = ((y ◇ x) ◇ y) ◇ x
equation 57902 := x ◇ (y ◇ z) = ((y ◇ x) ◇ y) ◇ y
equation 57903 := x ◇ (y ◇ z) = ((y ◇ x) ◇ y) ◇ z
equation 57904 := x ◇ (y ◇ z) = ((y ◇ x) ◇ y) ◇ w
equation 57905 := x ◇ (y ◇ z) = ((y ◇ x) ◇ z) ◇ x
equation 57906 := x ◇ (y ◇ z) = ((y ◇ x) ◇ z) ◇ y
equation 57907 := x ◇ (y ◇ z) = ((y ◇ x) ◇ z) ◇ z
equation 57908 := x ◇ (y ◇ z) = ((y ◇ x) ◇ z) ◇ w
equation 57909 := x ◇ (y ◇ z) = ((y ◇ x) ◇ w) ◇ x
equation 57910 := x ◇ (y ◇ z) = ((y ◇ x) ◇ w) ◇ y
equation 57911 := x ◇ (y ◇ z) = ((y ◇ x) ◇ w) ◇ z
equation 57912 := x ◇ (y ◇ z) = ((y ◇ x) ◇ w) ◇ w
equation 57913 := x ◇ (y ◇ z) = ((y ◇ x) ◇ w) ◇ u
equation 57914 := x ◇ (y ◇ z) = ((y ◇ y) ◇ x) ◇ x
equation 57915 := x ◇ (y ◇ z) = ((y ◇ y) ◇ x) ◇ y
equation 57916 := x ◇ (y ◇ z) = ((y ◇ y) ◇ x) ◇ z
equation 57917 := x ◇ (y ◇ z) = ((y ◇ y) ◇ x) ◇ w
equation 57918 := x ◇ (y ◇ z) = ((y ◇ y) ◇ y) ◇ x
equation 57919 := x ◇ (y ◇ z) = ((y ◇ y) ◇ y) ◇ y
equation 57920 := x ◇ (y ◇ z) = ((y ◇ y) ◇ y) ◇ z
equation 57921 := x ◇ (y ◇ z) = ((y ◇ y) ◇ y) ◇ w
equation 57922 := x ◇ (y ◇ z) = ((y ◇ y) ◇ z) ◇ x
equation 57923 := x ◇ (y ◇ z) = ((y ◇ y) ◇ z) ◇ y
equation 57924 := x ◇ (y ◇ z) = ((y ◇ y) ◇ z) ◇ z
equation 57925 := x ◇ (y ◇ z) = ((y ◇ y) ◇ z) ◇ w
equation 57926 := x ◇ (y ◇ z) = ((y ◇ y) ◇ w) ◇ x
equation 57927 := x ◇ (y ◇ z) = ((y ◇ y) ◇ w) ◇ y
equation 57928 := x ◇ (y ◇ z) = ((y ◇ y) ◇ w) ◇ z
equation 57929 := x ◇ (y ◇ z) = ((y ◇ y) ◇ w) ◇ w
equation 57930 := x ◇ (y ◇ z) = ((y ◇ y) ◇ w) ◇ u
equation 57931 := x ◇ (y ◇ z) = ((y ◇ z) ◇ x) ◇ x
equation 57932 := x ◇ (y ◇ z) = ((y ◇ z) ◇ x) ◇ y
equation 57933 := x ◇ (y ◇ z) = ((y ◇ z) ◇ x) ◇ z
equation 57934 := x ◇ (y ◇ z) = ((y ◇ z) ◇ x) ◇ w
equation 57935 := x ◇ (y ◇ z) = ((y ◇ z) ◇ y) ◇ x
equation 57936 := x ◇ (y ◇ z) = ((y ◇ z) ◇ y) ◇ y
equation 57937 := x ◇ (y ◇ z) = ((y ◇ z) ◇ y) ◇ z
equation 57938 := x ◇ (y ◇ z) = ((y ◇ z) ◇ y) ◇ w
equation 57939 := x ◇ (y ◇ z) = ((y ◇ z) ◇ z) ◇ x
equation 57940 := x ◇ (y ◇ z) = ((y ◇ z) ◇ z) ◇ y
equation 57941 := x ◇ (y ◇ z) = ((y ◇ z) ◇ z) ◇ z
equation 57942 := x ◇ (y ◇ z) = ((y ◇ z) ◇ z) ◇ w
equation 57943 := x ◇ (y ◇ z) = ((y ◇ z) ◇ w) ◇ x
equation 57944 := x ◇ (y ◇ z) = ((y ◇ z) ◇ w) ◇ y
equation 57945 := x ◇ (y ◇ z) = ((y ◇ z) ◇ w) ◇ z
equation 57946 := x ◇ (y ◇ z) = ((y ◇ z) ◇ w) ◇ w
equation 57947 := x ◇ (y ◇ z) = ((y ◇ z) ◇ w) ◇ u
equation 57948 := x ◇ (y ◇ z) = ((y ◇ w) ◇ x) ◇ x
equation 57949 := x ◇ (y ◇ z) = ((y ◇ w) ◇ x) ◇ y
equation 57950 := x ◇ (y ◇ z) = ((y ◇ w) ◇ x) ◇ z
equation 57951 := x ◇ (y ◇ z) = ((y ◇ w) ◇ x) ◇ w
equation 57952 := x ◇ (y ◇ z) = ((y ◇ w) ◇ x) ◇ u
equation 57953 := x ◇ (y ◇ z) = ((y ◇ w) ◇ y) ◇ x
equation 57954 := x ◇ (y ◇ z) = ((y ◇ w) ◇ y) ◇ y
equation 57955 := x ◇ (y ◇ z) = ((y ◇ w) ◇ y) ◇ z
equation 57956 := x ◇ (y ◇ z) = ((y ◇ w) ◇ y) ◇ w
equation 57957 := x ◇ (y ◇ z) = ((y ◇ w) ◇ y) ◇ u
equation 57958 := x ◇ (y ◇ z) = ((y ◇ w) ◇ z) ◇ x
equation 57959 := x ◇ (y ◇ z) = ((y ◇ w) ◇ z) ◇ y
equation 57960 := x ◇ (y ◇ z) = ((y ◇ w) ◇ z) ◇ z
equation 57961 := x ◇ (y ◇ z) = ((y ◇ w) ◇ z) ◇ w
equation 57962 := x ◇ (y ◇ z) = ((y ◇ w) ◇ z) ◇ u
equation 57963 := x ◇ (y ◇ z) = ((y ◇ w) ◇ w) ◇ x
equation 57964 := x ◇ (y ◇ z) = ((y ◇ w) ◇ w) ◇ y
equation 57965 := x ◇ (y ◇ z) = ((y ◇ w) ◇ w) ◇ z
equation 57966 := x ◇ (y ◇ z) = ((y ◇ w) ◇ w) ◇ w
equation 57967 := x ◇ (y ◇ z) = ((y ◇ w) ◇ w) ◇ u
equation 57968 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ x
equation 57969 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ y
equation 57970 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ z
equation 57971 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ w
equation 57972 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ u
equation 57973 := x ◇ (y ◇ z) = ((y ◇ w) ◇ u) ◇ v
equation 57974 := x ◇ (y ◇ z) = ((z ◇ x) ◇ x) ◇ x
equation 57975 := x ◇ (y ◇ z) = ((z ◇ x) ◇ x) ◇ y
equation 57976 := x ◇ (y ◇ z) = ((z ◇ x) ◇ x) ◇ z
equation 57977 := x ◇ (y ◇ z) = ((z ◇ x) ◇ x) ◇ w
equation 57978 := x ◇ (y ◇ z) = ((z ◇ x) ◇ y) ◇ x
equation 57979 := x ◇ (y ◇ z) = ((z ◇ x) ◇ y) ◇ y
equation 57980 := x ◇ (y ◇ z) = ((z ◇ x) ◇ y) ◇ z
equation 57981 := x ◇ (y ◇ z) = ((z ◇ x) ◇ y) ◇ w
equation 57982 := x ◇ (y ◇ z) = ((z ◇ x) ◇ z) ◇ x
equation 57983 := x ◇ (y ◇ z) = ((z ◇ x) ◇ z) ◇ y
equation 57984 := x ◇ (y ◇ z) = ((z ◇ x) ◇ z) ◇ z
equation 57985 := x ◇ (y ◇ z) = ((z ◇ x) ◇ z) ◇ w
equation 57986 := x ◇ (y ◇ z) = ((z ◇ x) ◇ w) ◇ x
equation 57987 := x ◇ (y ◇ z) = ((z ◇ x) ◇ w) ◇ y
equation 57988 := x ◇ (y ◇ z) = ((z ◇ x) ◇ w) ◇ z
equation 57989 := x ◇ (y ◇ z) = ((z ◇ x) ◇ w) ◇ w
equation 57990 := x ◇ (y ◇ z) = ((z ◇ x) ◇ w) ◇ u
equation 57991 := x ◇ (y ◇ z) = ((z ◇ y) ◇ x) ◇ x
equation 57992 := x ◇ (y ◇ z) = ((z ◇ y) ◇ x) ◇ y
equation 57993 := x ◇ (y ◇ z) = ((z ◇ y) ◇ x) ◇ z
equation 57994 := x ◇ (y ◇ z) = ((z ◇ y) ◇ x) ◇ w
equation 57995 := x ◇ (y ◇ z) = ((z ◇ y) ◇ y) ◇ x
equation 57996 := x ◇ (y ◇ z) = ((z ◇ y) ◇ y) ◇ y
equation 57997 := x ◇ (y ◇ z) = ((z ◇ y) ◇ y) ◇ z
equation 57998 := x ◇ (y ◇ z) = ((z ◇ y) ◇ y) ◇ w
equation 57999 := x ◇ (y ◇ z) = ((z ◇ y) ◇ z) ◇ x
