import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 37000-37999 -/

equation 37000 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ w
equation 37001 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ u
equation 37002 := x = (((y ◇ z) ◇ z) ◇ (w ◇ u)) ◇ v
equation 37003 := x = (((y ◇ z) ◇ w) ◇ (x ◇ x)) ◇ x
equation 37004 := x = (((y ◇ z) ◇ w) ◇ (x ◇ x)) ◇ y
equation 37005 := x = (((y ◇ z) ◇ w) ◇ (x ◇ x)) ◇ z
equation 37006 := x = (((y ◇ z) ◇ w) ◇ (x ◇ x)) ◇ w
equation 37007 := x = (((y ◇ z) ◇ w) ◇ (x ◇ x)) ◇ u
equation 37008 := x = (((y ◇ z) ◇ w) ◇ (x ◇ y)) ◇ x
equation 37009 := x = (((y ◇ z) ◇ w) ◇ (x ◇ y)) ◇ y
equation 37010 := x = (((y ◇ z) ◇ w) ◇ (x ◇ y)) ◇ z
equation 37011 := x = (((y ◇ z) ◇ w) ◇ (x ◇ y)) ◇ w
equation 37012 := x = (((y ◇ z) ◇ w) ◇ (x ◇ y)) ◇ u
equation 37013 := x = (((y ◇ z) ◇ w) ◇ (x ◇ z)) ◇ x
equation 37014 := x = (((y ◇ z) ◇ w) ◇ (x ◇ z)) ◇ y
equation 37015 := x = (((y ◇ z) ◇ w) ◇ (x ◇ z)) ◇ z
equation 37016 := x = (((y ◇ z) ◇ w) ◇ (x ◇ z)) ◇ w
equation 37017 := x = (((y ◇ z) ◇ w) ◇ (x ◇ z)) ◇ u
equation 37018 := x = (((y ◇ z) ◇ w) ◇ (x ◇ w)) ◇ x
equation 37019 := x = (((y ◇ z) ◇ w) ◇ (x ◇ w)) ◇ y
equation 37020 := x = (((y ◇ z) ◇ w) ◇ (x ◇ w)) ◇ z
equation 37021 := x = (((y ◇ z) ◇ w) ◇ (x ◇ w)) ◇ w
equation 37022 := x = (((y ◇ z) ◇ w) ◇ (x ◇ w)) ◇ u
equation 37023 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ x
equation 37024 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ y
equation 37025 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ z
equation 37026 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ w
equation 37027 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ u
equation 37028 := x = (((y ◇ z) ◇ w) ◇ (x ◇ u)) ◇ v
equation 37029 := x = (((y ◇ z) ◇ w) ◇ (y ◇ x)) ◇ x
equation 37030 := x = (((y ◇ z) ◇ w) ◇ (y ◇ x)) ◇ y
equation 37031 := x = (((y ◇ z) ◇ w) ◇ (y ◇ x)) ◇ z
equation 37032 := x = (((y ◇ z) ◇ w) ◇ (y ◇ x)) ◇ w
equation 37033 := x = (((y ◇ z) ◇ w) ◇ (y ◇ x)) ◇ u
equation 37034 := x = (((y ◇ z) ◇ w) ◇ (y ◇ y)) ◇ x
equation 37035 := x = (((y ◇ z) ◇ w) ◇ (y ◇ y)) ◇ y
equation 37036 := x = (((y ◇ z) ◇ w) ◇ (y ◇ y)) ◇ z
equation 37037 := x = (((y ◇ z) ◇ w) ◇ (y ◇ y)) ◇ w
equation 37038 := x = (((y ◇ z) ◇ w) ◇ (y ◇ y)) ◇ u
equation 37039 := x = (((y ◇ z) ◇ w) ◇ (y ◇ z)) ◇ x
equation 37040 := x = (((y ◇ z) ◇ w) ◇ (y ◇ z)) ◇ y
equation 37041 := x = (((y ◇ z) ◇ w) ◇ (y ◇ z)) ◇ z
equation 37042 := x = (((y ◇ z) ◇ w) ◇ (y ◇ z)) ◇ w
equation 37043 := x = (((y ◇ z) ◇ w) ◇ (y ◇ z)) ◇ u
equation 37044 := x = (((y ◇ z) ◇ w) ◇ (y ◇ w)) ◇ x
equation 37045 := x = (((y ◇ z) ◇ w) ◇ (y ◇ w)) ◇ y
equation 37046 := x = (((y ◇ z) ◇ w) ◇ (y ◇ w)) ◇ z
equation 37047 := x = (((y ◇ z) ◇ w) ◇ (y ◇ w)) ◇ w
equation 37048 := x = (((y ◇ z) ◇ w) ◇ (y ◇ w)) ◇ u
equation 37049 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ x
equation 37050 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ y
equation 37051 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ z
equation 37052 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ w
equation 37053 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ u
equation 37054 := x = (((y ◇ z) ◇ w) ◇ (y ◇ u)) ◇ v
equation 37055 := x = (((y ◇ z) ◇ w) ◇ (z ◇ x)) ◇ x
equation 37056 := x = (((y ◇ z) ◇ w) ◇ (z ◇ x)) ◇ y
equation 37057 := x = (((y ◇ z) ◇ w) ◇ (z ◇ x)) ◇ z
equation 37058 := x = (((y ◇ z) ◇ w) ◇ (z ◇ x)) ◇ w
equation 37059 := x = (((y ◇ z) ◇ w) ◇ (z ◇ x)) ◇ u
equation 37060 := x = (((y ◇ z) ◇ w) ◇ (z ◇ y)) ◇ x
equation 37061 := x = (((y ◇ z) ◇ w) ◇ (z ◇ y)) ◇ y
equation 37062 := x = (((y ◇ z) ◇ w) ◇ (z ◇ y)) ◇ z
equation 37063 := x = (((y ◇ z) ◇ w) ◇ (z ◇ y)) ◇ w
equation 37064 := x = (((y ◇ z) ◇ w) ◇ (z ◇ y)) ◇ u
equation 37065 := x = (((y ◇ z) ◇ w) ◇ (z ◇ z)) ◇ x
equation 37066 := x = (((y ◇ z) ◇ w) ◇ (z ◇ z)) ◇ y
equation 37067 := x = (((y ◇ z) ◇ w) ◇ (z ◇ z)) ◇ z
equation 37068 := x = (((y ◇ z) ◇ w) ◇ (z ◇ z)) ◇ w
equation 37069 := x = (((y ◇ z) ◇ w) ◇ (z ◇ z)) ◇ u
equation 37070 := x = (((y ◇ z) ◇ w) ◇ (z ◇ w)) ◇ x
equation 37071 := x = (((y ◇ z) ◇ w) ◇ (z ◇ w)) ◇ y
equation 37072 := x = (((y ◇ z) ◇ w) ◇ (z ◇ w)) ◇ z
equation 37073 := x = (((y ◇ z) ◇ w) ◇ (z ◇ w)) ◇ w
equation 37074 := x = (((y ◇ z) ◇ w) ◇ (z ◇ w)) ◇ u
equation 37075 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ x
equation 37076 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ y
equation 37077 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ z
equation 37078 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ w
equation 37079 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ u
equation 37080 := x = (((y ◇ z) ◇ w) ◇ (z ◇ u)) ◇ v
equation 37081 := x = (((y ◇ z) ◇ w) ◇ (w ◇ x)) ◇ x
equation 37082 := x = (((y ◇ z) ◇ w) ◇ (w ◇ x)) ◇ y
equation 37083 := x = (((y ◇ z) ◇ w) ◇ (w ◇ x)) ◇ z
equation 37084 := x = (((y ◇ z) ◇ w) ◇ (w ◇ x)) ◇ w
equation 37085 := x = (((y ◇ z) ◇ w) ◇ (w ◇ x)) ◇ u
equation 37086 := x = (((y ◇ z) ◇ w) ◇ (w ◇ y)) ◇ x
equation 37087 := x = (((y ◇ z) ◇ w) ◇ (w ◇ y)) ◇ y
equation 37088 := x = (((y ◇ z) ◇ w) ◇ (w ◇ y)) ◇ z
equation 37089 := x = (((y ◇ z) ◇ w) ◇ (w ◇ y)) ◇ w
equation 37090 := x = (((y ◇ z) ◇ w) ◇ (w ◇ y)) ◇ u
equation 37091 := x = (((y ◇ z) ◇ w) ◇ (w ◇ z)) ◇ x
equation 37092 := x = (((y ◇ z) ◇ w) ◇ (w ◇ z)) ◇ y
equation 37093 := x = (((y ◇ z) ◇ w) ◇ (w ◇ z)) ◇ z
equation 37094 := x = (((y ◇ z) ◇ w) ◇ (w ◇ z)) ◇ w
equation 37095 := x = (((y ◇ z) ◇ w) ◇ (w ◇ z)) ◇ u
equation 37096 := x = (((y ◇ z) ◇ w) ◇ (w ◇ w)) ◇ x
equation 37097 := x = (((y ◇ z) ◇ w) ◇ (w ◇ w)) ◇ y
equation 37098 := x = (((y ◇ z) ◇ w) ◇ (w ◇ w)) ◇ z
equation 37099 := x = (((y ◇ z) ◇ w) ◇ (w ◇ w)) ◇ w
equation 37100 := x = (((y ◇ z) ◇ w) ◇ (w ◇ w)) ◇ u
equation 37101 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ x
equation 37102 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ y
equation 37103 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ z
equation 37104 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ w
equation 37105 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ u
equation 37106 := x = (((y ◇ z) ◇ w) ◇ (w ◇ u)) ◇ v
equation 37107 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ x
equation 37108 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ y
equation 37109 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ z
equation 37110 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ w
equation 37111 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ u
equation 37112 := x = (((y ◇ z) ◇ w) ◇ (u ◇ x)) ◇ v
equation 37113 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ x
equation 37114 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ y
equation 37115 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ z
equation 37116 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ w
equation 37117 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ u
equation 37118 := x = (((y ◇ z) ◇ w) ◇ (u ◇ y)) ◇ v
equation 37119 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ x
equation 37120 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ y
equation 37121 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ z
equation 37122 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ w
equation 37123 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ u
equation 37124 := x = (((y ◇ z) ◇ w) ◇ (u ◇ z)) ◇ v
equation 37125 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ x
equation 37126 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ y
equation 37127 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ z
equation 37128 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ w
equation 37129 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ u
equation 37130 := x = (((y ◇ z) ◇ w) ◇ (u ◇ w)) ◇ v
equation 37131 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ x
equation 37132 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ y
equation 37133 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ z
equation 37134 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ w
equation 37135 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ u
equation 37136 := x = (((y ◇ z) ◇ w) ◇ (u ◇ u)) ◇ v
equation 37137 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ x
equation 37138 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ y
equation 37139 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ z
equation 37140 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ w
equation 37141 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ u
equation 37142 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ v
equation 37143 := x = (((y ◇ z) ◇ w) ◇ (u ◇ v)) ◇ r
equation 37144 := x = ((x ◇ (x ◇ (x ◇ x))) ◇ x) ◇ x
equation 37145 := x = ((x ◇ (x ◇ (x ◇ x))) ◇ x) ◇ y
equation 37146 := x = ((x ◇ (x ◇ (x ◇ x))) ◇ y) ◇ x
equation 37147 := x = ((x ◇ (x ◇ (x ◇ x))) ◇ y) ◇ y
equation 37148 := x = ((x ◇ (x ◇ (x ◇ x))) ◇ y) ◇ z
equation 37149 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ x) ◇ x
equation 37150 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ x) ◇ y
equation 37151 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ x) ◇ z
equation 37152 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ y) ◇ x
equation 37153 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ y) ◇ y
equation 37154 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ y) ◇ z
equation 37155 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ z) ◇ x
equation 37156 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ z) ◇ y
equation 37157 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ z) ◇ z
equation 37158 := x = ((x ◇ (x ◇ (x ◇ y))) ◇ z) ◇ w
equation 37159 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ x) ◇ x
equation 37160 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ x) ◇ y
equation 37161 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ x) ◇ z
equation 37162 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ y) ◇ x
equation 37163 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ y) ◇ y
equation 37164 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ y) ◇ z
equation 37165 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ z) ◇ x
equation 37166 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ z) ◇ y
equation 37167 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ z) ◇ z
equation 37168 := x = ((x ◇ (x ◇ (y ◇ x))) ◇ z) ◇ w
equation 37169 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ x) ◇ x
equation 37170 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ x) ◇ y
equation 37171 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ x) ◇ z
equation 37172 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ y) ◇ x
equation 37173 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ y) ◇ y
equation 37174 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ y) ◇ z
equation 37175 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ z) ◇ x
equation 37176 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ z) ◇ y
equation 37177 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ z) ◇ z
equation 37178 := x = ((x ◇ (x ◇ (y ◇ y))) ◇ z) ◇ w
equation 37179 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ x) ◇ x
equation 37180 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ x) ◇ y
equation 37181 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ x) ◇ z
equation 37182 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ x) ◇ w
equation 37183 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ y) ◇ x
equation 37184 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ y) ◇ y
equation 37185 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ y) ◇ z
equation 37186 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ y) ◇ w
equation 37187 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ z) ◇ x
equation 37188 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ z) ◇ y
equation 37189 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ z) ◇ z
equation 37190 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ z) ◇ w
equation 37191 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ w) ◇ x
equation 37192 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ w) ◇ y
equation 37193 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ w) ◇ z
equation 37194 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ w) ◇ w
equation 37195 := x = ((x ◇ (x ◇ (y ◇ z))) ◇ w) ◇ u
equation 37196 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ x) ◇ x
equation 37197 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ x) ◇ y
equation 37198 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ x) ◇ z
equation 37199 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ y) ◇ x
equation 37200 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ y) ◇ y
equation 37201 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ y) ◇ z
equation 37202 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ z) ◇ x
equation 37203 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ z) ◇ y
equation 37204 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ z) ◇ z
equation 37205 := x = ((x ◇ (y ◇ (x ◇ x))) ◇ z) ◇ w
equation 37206 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ x) ◇ x
equation 37207 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ x) ◇ y
equation 37208 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ x) ◇ z
equation 37209 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ y) ◇ x
equation 37210 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ y) ◇ y
equation 37211 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ y) ◇ z
equation 37212 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ z) ◇ x
equation 37213 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ z) ◇ y
equation 37214 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ z) ◇ z
equation 37215 := x = ((x ◇ (y ◇ (x ◇ y))) ◇ z) ◇ w
equation 37216 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ x) ◇ x
equation 37217 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ x) ◇ y
equation 37218 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ x) ◇ z
equation 37219 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ x) ◇ w
equation 37220 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ y) ◇ x
equation 37221 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ y) ◇ y
equation 37222 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ y) ◇ z
equation 37223 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ y) ◇ w
equation 37224 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ z) ◇ x
equation 37225 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ z) ◇ y
equation 37226 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ z) ◇ z
equation 37227 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ z) ◇ w
equation 37228 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ w) ◇ x
equation 37229 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ w) ◇ y
equation 37230 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ w) ◇ z
equation 37231 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ w) ◇ w
equation 37232 := x = ((x ◇ (y ◇ (x ◇ z))) ◇ w) ◇ u
equation 37233 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ x) ◇ x
equation 37234 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ x) ◇ y
equation 37235 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ x) ◇ z
equation 37236 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ y) ◇ x
equation 37237 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ y) ◇ y
equation 37238 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ y) ◇ z
equation 37239 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ z) ◇ x
equation 37240 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ z) ◇ y
equation 37241 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ z) ◇ z
equation 37242 := x = ((x ◇ (y ◇ (y ◇ x))) ◇ z) ◇ w
equation 37243 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ x) ◇ x
equation 37244 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ x) ◇ y
equation 37245 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ x) ◇ z
equation 37246 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ y) ◇ x
equation 37247 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ y) ◇ y
equation 37248 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ y) ◇ z
equation 37249 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ z) ◇ x
equation 37250 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ z) ◇ y
equation 37251 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ z) ◇ z
equation 37252 := x = ((x ◇ (y ◇ (y ◇ y))) ◇ z) ◇ w
equation 37253 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ x) ◇ x
equation 37254 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ x) ◇ y
equation 37255 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ x) ◇ z
equation 37256 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ x) ◇ w
equation 37257 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ y) ◇ x
equation 37258 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ y) ◇ y
equation 37259 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ y) ◇ z
equation 37260 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ y) ◇ w
equation 37261 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ z) ◇ x
equation 37262 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ z) ◇ y
equation 37263 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ z) ◇ z
equation 37264 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ z) ◇ w
equation 37265 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ w) ◇ x
equation 37266 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ w) ◇ y
equation 37267 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ w) ◇ z
equation 37268 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ w) ◇ w
equation 37269 := x = ((x ◇ (y ◇ (y ◇ z))) ◇ w) ◇ u
equation 37270 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ x) ◇ x
equation 37271 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ x) ◇ y
equation 37272 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ x) ◇ z
equation 37273 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ x) ◇ w
equation 37274 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ y) ◇ x
equation 37275 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ y) ◇ y
equation 37276 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ y) ◇ z
equation 37277 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ y) ◇ w
equation 37278 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ z) ◇ x
equation 37279 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ z) ◇ y
equation 37280 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ z) ◇ z
equation 37281 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ z) ◇ w
equation 37282 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ w) ◇ x
equation 37283 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ w) ◇ y
equation 37284 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ w) ◇ z
equation 37285 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ w) ◇ w
equation 37286 := x = ((x ◇ (y ◇ (z ◇ x))) ◇ w) ◇ u
equation 37287 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ x) ◇ x
equation 37288 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ x) ◇ y
equation 37289 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ x) ◇ z
equation 37290 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ x) ◇ w
equation 37291 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ y) ◇ x
equation 37292 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ y) ◇ y
equation 37293 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ y) ◇ z
equation 37294 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ y) ◇ w
equation 37295 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ z) ◇ x
equation 37296 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ z) ◇ y
equation 37297 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ z) ◇ z
equation 37298 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ z) ◇ w
equation 37299 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ w) ◇ x
equation 37300 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ w) ◇ y
equation 37301 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ w) ◇ z
equation 37302 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ w) ◇ w
equation 37303 := x = ((x ◇ (y ◇ (z ◇ y))) ◇ w) ◇ u
equation 37304 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ x) ◇ x
equation 37305 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ x) ◇ y
equation 37306 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ x) ◇ z
equation 37307 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ x) ◇ w
equation 37308 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ y) ◇ x
equation 37309 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ y) ◇ y
equation 37310 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ y) ◇ z
equation 37311 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ y) ◇ w
equation 37312 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ z) ◇ x
equation 37313 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ z) ◇ y
equation 37314 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ z) ◇ z
equation 37315 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ z) ◇ w
equation 37316 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ w) ◇ x
equation 37317 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ w) ◇ y
equation 37318 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ w) ◇ z
equation 37319 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ w) ◇ w
equation 37320 := x = ((x ◇ (y ◇ (z ◇ z))) ◇ w) ◇ u
equation 37321 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ x) ◇ x
equation 37322 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ x) ◇ y
equation 37323 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ x) ◇ z
equation 37324 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ x) ◇ w
equation 37325 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ x) ◇ u
equation 37326 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ y) ◇ x
equation 37327 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ y) ◇ y
equation 37328 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ y) ◇ z
equation 37329 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ y) ◇ w
equation 37330 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ y) ◇ u
equation 37331 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ z) ◇ x
equation 37332 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ z) ◇ y
equation 37333 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ z) ◇ z
equation 37334 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ z) ◇ w
equation 37335 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ z) ◇ u
equation 37336 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ w) ◇ x
equation 37337 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ w) ◇ y
equation 37338 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ w) ◇ z
equation 37339 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ w) ◇ w
equation 37340 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ w) ◇ u
equation 37341 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ x
equation 37342 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ y
equation 37343 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ z
equation 37344 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ w
equation 37345 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ u
equation 37346 := x = ((x ◇ (y ◇ (z ◇ w))) ◇ u) ◇ v
equation 37347 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ x) ◇ x
equation 37348 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ x) ◇ y
equation 37349 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ x) ◇ z
equation 37350 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ y) ◇ x
equation 37351 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ y) ◇ y
equation 37352 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ y) ◇ z
equation 37353 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ z) ◇ x
equation 37354 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ z) ◇ y
equation 37355 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ z) ◇ z
equation 37356 := x = ((y ◇ (x ◇ (x ◇ x))) ◇ z) ◇ w
equation 37357 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ x) ◇ x
equation 37358 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ x) ◇ y
equation 37359 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ x) ◇ z
equation 37360 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ y) ◇ x
equation 37361 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ y) ◇ y
equation 37362 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ y) ◇ z
equation 37363 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ z) ◇ x
equation 37364 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ z) ◇ y
equation 37365 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ z) ◇ z
equation 37366 := x = ((y ◇ (x ◇ (x ◇ y))) ◇ z) ◇ w
equation 37367 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ x) ◇ x
equation 37368 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ x) ◇ y
equation 37369 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ x) ◇ z
equation 37370 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ x) ◇ w
equation 37371 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ y) ◇ x
equation 37372 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ y) ◇ y
equation 37373 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ y) ◇ z
equation 37374 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ y) ◇ w
equation 37375 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ z) ◇ x
equation 37376 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ z) ◇ y
equation 37377 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ z) ◇ z
equation 37378 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ z) ◇ w
equation 37379 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ w) ◇ x
equation 37380 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ w) ◇ y
equation 37381 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ w) ◇ z
equation 37382 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ w) ◇ w
equation 37383 := x = ((y ◇ (x ◇ (x ◇ z))) ◇ w) ◇ u
equation 37384 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ x) ◇ x
equation 37385 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ x) ◇ y
equation 37386 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ x) ◇ z
equation 37387 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ y) ◇ x
equation 37388 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ y) ◇ y
equation 37389 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ y) ◇ z
equation 37390 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ z) ◇ x
equation 37391 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ z) ◇ y
equation 37392 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ z) ◇ z
equation 37393 := x = ((y ◇ (x ◇ (y ◇ x))) ◇ z) ◇ w
equation 37394 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ x) ◇ x
equation 37395 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ x) ◇ y
equation 37396 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ x) ◇ z
equation 37397 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ y) ◇ x
equation 37398 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ y) ◇ y
equation 37399 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ y) ◇ z
equation 37400 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ z) ◇ x
equation 37401 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ z) ◇ y
equation 37402 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ z) ◇ z
equation 37403 := x = ((y ◇ (x ◇ (y ◇ y))) ◇ z) ◇ w
equation 37404 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ x) ◇ x
equation 37405 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ x) ◇ y
equation 37406 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ x) ◇ z
equation 37407 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ x) ◇ w
equation 37408 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ y) ◇ x
equation 37409 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ y) ◇ y
equation 37410 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ y) ◇ z
equation 37411 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ y) ◇ w
equation 37412 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ z) ◇ x
equation 37413 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ z) ◇ y
equation 37414 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ z) ◇ z
equation 37415 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ z) ◇ w
equation 37416 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ w) ◇ x
equation 37417 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ w) ◇ y
equation 37418 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ w) ◇ z
equation 37419 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ w) ◇ w
equation 37420 := x = ((y ◇ (x ◇ (y ◇ z))) ◇ w) ◇ u
equation 37421 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ x) ◇ x
equation 37422 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ x) ◇ y
equation 37423 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ x) ◇ z
equation 37424 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ x) ◇ w
equation 37425 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ y) ◇ x
equation 37426 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ y) ◇ y
equation 37427 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ y) ◇ z
equation 37428 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ y) ◇ w
equation 37429 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ z) ◇ x
equation 37430 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ z) ◇ y
equation 37431 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ z) ◇ z
equation 37432 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ z) ◇ w
equation 37433 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ w) ◇ x
equation 37434 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ w) ◇ y
equation 37435 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ w) ◇ z
equation 37436 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ w) ◇ w
equation 37437 := x = ((y ◇ (x ◇ (z ◇ x))) ◇ w) ◇ u
equation 37438 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ x) ◇ x
equation 37439 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ x) ◇ y
equation 37440 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ x) ◇ z
equation 37441 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ x) ◇ w
equation 37442 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ y) ◇ x
equation 37443 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ y) ◇ y
equation 37444 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ y) ◇ z
equation 37445 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ y) ◇ w
equation 37446 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ z) ◇ x
equation 37447 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ z) ◇ y
equation 37448 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ z) ◇ z
equation 37449 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ z) ◇ w
equation 37450 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ w) ◇ x
equation 37451 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ w) ◇ y
equation 37452 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ w) ◇ z
equation 37453 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ w) ◇ w
equation 37454 := x = ((y ◇ (x ◇ (z ◇ y))) ◇ w) ◇ u
equation 37455 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ x) ◇ x
equation 37456 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ x) ◇ y
equation 37457 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ x) ◇ z
equation 37458 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ x) ◇ w
equation 37459 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ y) ◇ x
equation 37460 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ y) ◇ y
equation 37461 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ y) ◇ z
equation 37462 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ y) ◇ w
equation 37463 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ z) ◇ x
equation 37464 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ z) ◇ y
equation 37465 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ z) ◇ z
equation 37466 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ z) ◇ w
equation 37467 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ w) ◇ x
equation 37468 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ w) ◇ y
equation 37469 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ w) ◇ z
equation 37470 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ w) ◇ w
equation 37471 := x = ((y ◇ (x ◇ (z ◇ z))) ◇ w) ◇ u
equation 37472 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ x) ◇ x
equation 37473 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ x) ◇ y
equation 37474 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ x) ◇ z
equation 37475 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ x) ◇ w
equation 37476 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ x) ◇ u
equation 37477 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ y) ◇ x
equation 37478 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ y) ◇ y
equation 37479 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ y) ◇ z
equation 37480 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ y) ◇ w
equation 37481 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ y) ◇ u
equation 37482 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ z) ◇ x
equation 37483 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ z) ◇ y
equation 37484 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ z) ◇ z
equation 37485 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ z) ◇ w
equation 37486 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ z) ◇ u
equation 37487 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ w) ◇ x
equation 37488 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ w) ◇ y
equation 37489 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ w) ◇ z
equation 37490 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ w) ◇ w
equation 37491 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ w) ◇ u
equation 37492 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ x
equation 37493 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ y
equation 37494 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ z
equation 37495 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ w
equation 37496 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ u
equation 37497 := x = ((y ◇ (x ◇ (z ◇ w))) ◇ u) ◇ v
equation 37498 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ x) ◇ x
equation 37499 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ x) ◇ y
equation 37500 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ x) ◇ z
equation 37501 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ y) ◇ x
equation 37502 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ y) ◇ y
equation 37503 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ y) ◇ z
equation 37504 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ z) ◇ x
equation 37505 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ z) ◇ y
equation 37506 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ z) ◇ z
equation 37507 := x = ((y ◇ (y ◇ (x ◇ x))) ◇ z) ◇ w
equation 37508 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ x) ◇ x
equation 37509 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ x) ◇ y
equation 37510 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ x) ◇ z
equation 37511 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ y) ◇ x
equation 37512 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ y) ◇ y
equation 37513 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ y) ◇ z
equation 37514 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ z) ◇ x
equation 37515 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ z) ◇ y
equation 37516 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ z) ◇ z
equation 37517 := x = ((y ◇ (y ◇ (x ◇ y))) ◇ z) ◇ w
equation 37518 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ x) ◇ x
equation 37519 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ x) ◇ y
equation 37520 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ x) ◇ z
equation 37521 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ x) ◇ w
equation 37522 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ y) ◇ x
equation 37523 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ y) ◇ y
equation 37524 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ y) ◇ z
equation 37525 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ y) ◇ w
equation 37526 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ z) ◇ x
equation 37527 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ z) ◇ y
equation 37528 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ z) ◇ z
equation 37529 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ z) ◇ w
equation 37530 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ w) ◇ x
equation 37531 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ w) ◇ y
equation 37532 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ w) ◇ z
equation 37533 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ w) ◇ w
equation 37534 := x = ((y ◇ (y ◇ (x ◇ z))) ◇ w) ◇ u
equation 37535 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ x) ◇ x
equation 37536 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ x) ◇ y
equation 37537 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ x) ◇ z
equation 37538 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ y) ◇ x
equation 37539 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ y) ◇ y
equation 37540 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ y) ◇ z
equation 37541 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ z) ◇ x
equation 37542 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ z) ◇ y
equation 37543 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ z) ◇ z
equation 37544 := x = ((y ◇ (y ◇ (y ◇ x))) ◇ z) ◇ w
equation 37545 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ x) ◇ x
equation 37546 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ x) ◇ y
equation 37547 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ x) ◇ z
equation 37548 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ y) ◇ x
equation 37549 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ y) ◇ y
equation 37550 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ y) ◇ z
equation 37551 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ z) ◇ x
equation 37552 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ z) ◇ y
equation 37553 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ z) ◇ z
equation 37554 := x = ((y ◇ (y ◇ (y ◇ y))) ◇ z) ◇ w
equation 37555 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ x) ◇ x
equation 37556 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ x) ◇ y
equation 37557 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ x) ◇ z
equation 37558 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ x) ◇ w
equation 37559 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ y) ◇ x
equation 37560 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ y) ◇ y
equation 37561 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ y) ◇ z
equation 37562 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ y) ◇ w
equation 37563 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ z) ◇ x
equation 37564 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ z) ◇ y
equation 37565 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ z) ◇ z
equation 37566 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ z) ◇ w
equation 37567 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ w) ◇ x
equation 37568 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ w) ◇ y
equation 37569 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ w) ◇ z
equation 37570 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ w) ◇ w
equation 37571 := x = ((y ◇ (y ◇ (y ◇ z))) ◇ w) ◇ u
equation 37572 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ x) ◇ x
equation 37573 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ x) ◇ y
equation 37574 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ x) ◇ z
equation 37575 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ x) ◇ w
equation 37576 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ y) ◇ x
equation 37577 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ y) ◇ y
equation 37578 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ y) ◇ z
equation 37579 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ y) ◇ w
equation 37580 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ z) ◇ x
equation 37581 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ z) ◇ y
equation 37582 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ z) ◇ z
equation 37583 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ z) ◇ w
equation 37584 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ w) ◇ x
equation 37585 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ w) ◇ y
equation 37586 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ w) ◇ z
equation 37587 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ w) ◇ w
equation 37588 := x = ((y ◇ (y ◇ (z ◇ x))) ◇ w) ◇ u
equation 37589 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ x) ◇ x
equation 37590 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ x) ◇ y
equation 37591 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ x) ◇ z
equation 37592 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ x) ◇ w
equation 37593 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ y) ◇ x
equation 37594 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ y) ◇ y
equation 37595 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ y) ◇ z
equation 37596 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ y) ◇ w
equation 37597 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ z) ◇ x
equation 37598 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ z) ◇ y
equation 37599 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ z) ◇ z
equation 37600 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ z) ◇ w
equation 37601 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ w) ◇ x
equation 37602 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ w) ◇ y
equation 37603 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ w) ◇ z
equation 37604 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ w) ◇ w
equation 37605 := x = ((y ◇ (y ◇ (z ◇ y))) ◇ w) ◇ u
equation 37606 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ x) ◇ x
equation 37607 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ x) ◇ y
equation 37608 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ x) ◇ z
equation 37609 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ x) ◇ w
equation 37610 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ y) ◇ x
equation 37611 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ y) ◇ y
equation 37612 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ y) ◇ z
equation 37613 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ y) ◇ w
equation 37614 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ z) ◇ x
equation 37615 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ z) ◇ y
equation 37616 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ z) ◇ z
equation 37617 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ z) ◇ w
equation 37618 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ w) ◇ x
equation 37619 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ w) ◇ y
equation 37620 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ w) ◇ z
equation 37621 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ w) ◇ w
equation 37622 := x = ((y ◇ (y ◇ (z ◇ z))) ◇ w) ◇ u
equation 37623 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ x) ◇ x
equation 37624 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ x) ◇ y
equation 37625 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ x) ◇ z
equation 37626 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ x) ◇ w
equation 37627 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ x) ◇ u
equation 37628 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ y) ◇ x
equation 37629 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ y) ◇ y
equation 37630 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ y) ◇ z
equation 37631 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ y) ◇ w
equation 37632 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ y) ◇ u
equation 37633 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ z) ◇ x
equation 37634 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ z) ◇ y
equation 37635 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ z) ◇ z
equation 37636 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ z) ◇ w
equation 37637 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ z) ◇ u
equation 37638 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ w) ◇ x
equation 37639 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ w) ◇ y
equation 37640 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ w) ◇ z
equation 37641 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ w) ◇ w
equation 37642 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ w) ◇ u
equation 37643 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ x
equation 37644 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ y
equation 37645 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ z
equation 37646 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ w
equation 37647 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ u
equation 37648 := x = ((y ◇ (y ◇ (z ◇ w))) ◇ u) ◇ v
equation 37649 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ x) ◇ x
equation 37650 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ x) ◇ y
equation 37651 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ x) ◇ z
equation 37652 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ x) ◇ w
equation 37653 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ y) ◇ x
equation 37654 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ y) ◇ y
equation 37655 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ y) ◇ z
equation 37656 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ y) ◇ w
equation 37657 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ z) ◇ x
equation 37658 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ z) ◇ y
equation 37659 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ z) ◇ z
equation 37660 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ z) ◇ w
equation 37661 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ w) ◇ x
equation 37662 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ w) ◇ y
equation 37663 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ w) ◇ z
equation 37664 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ w) ◇ w
equation 37665 := x = ((y ◇ (z ◇ (x ◇ x))) ◇ w) ◇ u
equation 37666 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ x) ◇ x
equation 37667 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ x) ◇ y
equation 37668 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ x) ◇ z
equation 37669 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ x) ◇ w
equation 37670 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ y) ◇ x
equation 37671 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ y) ◇ y
equation 37672 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ y) ◇ z
equation 37673 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ y) ◇ w
equation 37674 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ z) ◇ x
equation 37675 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ z) ◇ y
equation 37676 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ z) ◇ z
equation 37677 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ z) ◇ w
equation 37678 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ w) ◇ x
equation 37679 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ w) ◇ y
equation 37680 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ w) ◇ z
equation 37681 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ w) ◇ w
equation 37682 := x = ((y ◇ (z ◇ (x ◇ y))) ◇ w) ◇ u
equation 37683 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ x) ◇ x
equation 37684 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ x) ◇ y
equation 37685 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ x) ◇ z
equation 37686 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ x) ◇ w
equation 37687 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ y) ◇ x
equation 37688 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ y) ◇ y
equation 37689 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ y) ◇ z
equation 37690 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ y) ◇ w
equation 37691 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ z) ◇ x
equation 37692 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ z) ◇ y
equation 37693 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ z) ◇ z
equation 37694 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ z) ◇ w
equation 37695 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ w) ◇ x
equation 37696 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ w) ◇ y
equation 37697 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ w) ◇ z
equation 37698 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ w) ◇ w
equation 37699 := x = ((y ◇ (z ◇ (x ◇ z))) ◇ w) ◇ u
equation 37700 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ x) ◇ x
equation 37701 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ x) ◇ y
equation 37702 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ x) ◇ z
equation 37703 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ x) ◇ w
equation 37704 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ x) ◇ u
equation 37705 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ y) ◇ x
equation 37706 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ y) ◇ y
equation 37707 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ y) ◇ z
equation 37708 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ y) ◇ w
equation 37709 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ y) ◇ u
equation 37710 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ z) ◇ x
equation 37711 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ z) ◇ y
equation 37712 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ z) ◇ z
equation 37713 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ z) ◇ w
equation 37714 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ z) ◇ u
equation 37715 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ w) ◇ x
equation 37716 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ w) ◇ y
equation 37717 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ w) ◇ z
equation 37718 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ w) ◇ w
equation 37719 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ w) ◇ u
equation 37720 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ x
equation 37721 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ y
equation 37722 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ z
equation 37723 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ w
equation 37724 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ u
equation 37725 := x = ((y ◇ (z ◇ (x ◇ w))) ◇ u) ◇ v
equation 37726 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ x) ◇ x
equation 37727 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ x) ◇ y
equation 37728 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ x) ◇ z
equation 37729 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ x) ◇ w
equation 37730 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ y) ◇ x
equation 37731 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ y) ◇ y
equation 37732 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ y) ◇ z
equation 37733 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ y) ◇ w
equation 37734 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ z) ◇ x
equation 37735 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ z) ◇ y
equation 37736 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ z) ◇ z
equation 37737 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ z) ◇ w
equation 37738 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ w) ◇ x
equation 37739 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ w) ◇ y
equation 37740 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ w) ◇ z
equation 37741 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ w) ◇ w
equation 37742 := x = ((y ◇ (z ◇ (y ◇ x))) ◇ w) ◇ u
equation 37743 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ x) ◇ x
equation 37744 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ x) ◇ y
equation 37745 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ x) ◇ z
equation 37746 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ x) ◇ w
equation 37747 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ y) ◇ x
equation 37748 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ y) ◇ y
equation 37749 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ y) ◇ z
equation 37750 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ y) ◇ w
equation 37751 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ z) ◇ x
equation 37752 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ z) ◇ y
equation 37753 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ z) ◇ z
equation 37754 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ z) ◇ w
equation 37755 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ w) ◇ x
equation 37756 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ w) ◇ y
equation 37757 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ w) ◇ z
equation 37758 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ w) ◇ w
equation 37759 := x = ((y ◇ (z ◇ (y ◇ y))) ◇ w) ◇ u
equation 37760 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ x) ◇ x
equation 37761 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ x) ◇ y
equation 37762 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ x) ◇ z
equation 37763 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ x) ◇ w
equation 37764 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ y) ◇ x
equation 37765 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ y) ◇ y
equation 37766 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ y) ◇ z
equation 37767 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ y) ◇ w
equation 37768 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ z) ◇ x
equation 37769 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ z) ◇ y
equation 37770 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ z) ◇ z
equation 37771 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ z) ◇ w
equation 37772 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ w) ◇ x
equation 37773 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ w) ◇ y
equation 37774 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ w) ◇ z
equation 37775 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ w) ◇ w
equation 37776 := x = ((y ◇ (z ◇ (y ◇ z))) ◇ w) ◇ u
equation 37777 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ x) ◇ x
equation 37778 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ x) ◇ y
equation 37779 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ x) ◇ z
equation 37780 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ x) ◇ w
equation 37781 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ x) ◇ u
equation 37782 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ y) ◇ x
equation 37783 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ y) ◇ y
equation 37784 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ y) ◇ z
equation 37785 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ y) ◇ w
equation 37786 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ y) ◇ u
equation 37787 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ z) ◇ x
equation 37788 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ z) ◇ y
equation 37789 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ z) ◇ z
equation 37790 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ z) ◇ w
equation 37791 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ z) ◇ u
equation 37792 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ w) ◇ x
equation 37793 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ w) ◇ y
equation 37794 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ w) ◇ z
equation 37795 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ w) ◇ w
equation 37796 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ w) ◇ u
equation 37797 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ x
equation 37798 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ y
equation 37799 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ z
equation 37800 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ w
equation 37801 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ u
equation 37802 := x = ((y ◇ (z ◇ (y ◇ w))) ◇ u) ◇ v
equation 37803 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ x) ◇ x
equation 37804 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ x) ◇ y
equation 37805 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ x) ◇ z
equation 37806 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ x) ◇ w
equation 37807 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ y) ◇ x
equation 37808 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ y) ◇ y
equation 37809 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ y) ◇ z
equation 37810 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ y) ◇ w
equation 37811 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ z) ◇ x
equation 37812 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ z) ◇ y
equation 37813 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ z) ◇ z
equation 37814 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ z) ◇ w
equation 37815 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ w) ◇ x
equation 37816 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ w) ◇ y
equation 37817 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ w) ◇ z
equation 37818 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ w) ◇ w
equation 37819 := x = ((y ◇ (z ◇ (z ◇ x))) ◇ w) ◇ u
equation 37820 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ x) ◇ x
equation 37821 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ x) ◇ y
equation 37822 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ x) ◇ z
equation 37823 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ x) ◇ w
equation 37824 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ y) ◇ x
equation 37825 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ y) ◇ y
equation 37826 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ y) ◇ z
equation 37827 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ y) ◇ w
equation 37828 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ z) ◇ x
equation 37829 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ z) ◇ y
equation 37830 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ z) ◇ z
equation 37831 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ z) ◇ w
equation 37832 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ x
equation 37833 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ y
equation 37834 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ z
equation 37835 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ w
equation 37836 := x = ((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ u
equation 37837 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ x) ◇ x
equation 37838 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ x) ◇ y
equation 37839 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ x) ◇ z
equation 37840 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ x) ◇ w
equation 37841 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ y) ◇ x
equation 37842 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ y) ◇ y
equation 37843 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ y) ◇ z
equation 37844 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ y) ◇ w
equation 37845 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ z) ◇ x
equation 37846 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ z) ◇ y
equation 37847 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ z) ◇ z
equation 37848 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ z) ◇ w
equation 37849 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ w) ◇ x
equation 37850 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ w) ◇ y
equation 37851 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ w) ◇ z
equation 37852 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ w) ◇ w
equation 37853 := x = ((y ◇ (z ◇ (z ◇ z))) ◇ w) ◇ u
equation 37854 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ x) ◇ x
equation 37855 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ x) ◇ y
equation 37856 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ x) ◇ z
equation 37857 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ x) ◇ w
equation 37858 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ x) ◇ u
equation 37859 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ y) ◇ x
equation 37860 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ y) ◇ y
equation 37861 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ y) ◇ z
equation 37862 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ y) ◇ w
equation 37863 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ y) ◇ u
equation 37864 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ z) ◇ x
equation 37865 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ z) ◇ y
equation 37866 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ z) ◇ z
equation 37867 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ z) ◇ w
equation 37868 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ z) ◇ u
equation 37869 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ w) ◇ x
equation 37870 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ w) ◇ y
equation 37871 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ w) ◇ z
equation 37872 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ w) ◇ w
equation 37873 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ w) ◇ u
equation 37874 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ x
equation 37875 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ y
equation 37876 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ z
equation 37877 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ w
equation 37878 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ u
equation 37879 := x = ((y ◇ (z ◇ (z ◇ w))) ◇ u) ◇ v
equation 37880 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ x) ◇ x
equation 37881 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ x) ◇ y
equation 37882 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ x) ◇ z
equation 37883 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ x) ◇ w
equation 37884 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ x) ◇ u
equation 37885 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ y) ◇ x
equation 37886 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ y) ◇ y
equation 37887 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ y) ◇ z
equation 37888 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ y) ◇ w
equation 37889 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ y) ◇ u
equation 37890 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ z) ◇ x
equation 37891 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ z) ◇ y
equation 37892 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ z) ◇ z
equation 37893 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ z) ◇ w
equation 37894 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ z) ◇ u
equation 37895 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ w) ◇ x
equation 37896 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ w) ◇ y
equation 37897 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ w) ◇ z
equation 37898 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ w) ◇ w
equation 37899 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ w) ◇ u
equation 37900 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ x
equation 37901 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ y
equation 37902 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ z
equation 37903 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ w
equation 37904 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ u
equation 37905 := x = ((y ◇ (z ◇ (w ◇ x))) ◇ u) ◇ v
equation 37906 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ x) ◇ x
equation 37907 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ x) ◇ y
equation 37908 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ x) ◇ z
equation 37909 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ x) ◇ w
equation 37910 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ x) ◇ u
equation 37911 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ y) ◇ x
equation 37912 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ y) ◇ y
equation 37913 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ y) ◇ z
equation 37914 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ y) ◇ w
equation 37915 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ y) ◇ u
equation 37916 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ z) ◇ x
equation 37917 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ z) ◇ y
equation 37918 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ z) ◇ z
equation 37919 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ z) ◇ w
equation 37920 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ z) ◇ u
equation 37921 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ w) ◇ x
equation 37922 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ w) ◇ y
equation 37923 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ w) ◇ z
equation 37924 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ w) ◇ w
equation 37925 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ w) ◇ u
equation 37926 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ x
equation 37927 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ y
equation 37928 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ z
equation 37929 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ w
equation 37930 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ u
equation 37931 := x = ((y ◇ (z ◇ (w ◇ y))) ◇ u) ◇ v
equation 37932 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ x) ◇ x
equation 37933 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ x) ◇ y
equation 37934 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ x) ◇ z
equation 37935 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ x) ◇ w
equation 37936 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ x) ◇ u
equation 37937 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ y) ◇ x
equation 37938 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ y) ◇ y
equation 37939 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ y) ◇ z
equation 37940 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ y) ◇ w
equation 37941 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ y) ◇ u
equation 37942 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ z) ◇ x
equation 37943 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ z) ◇ y
equation 37944 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ z) ◇ z
equation 37945 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ z) ◇ w
equation 37946 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ z) ◇ u
equation 37947 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ w) ◇ x
equation 37948 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ w) ◇ y
equation 37949 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ w) ◇ z
equation 37950 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ w) ◇ w
equation 37951 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ w) ◇ u
equation 37952 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ x
equation 37953 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ y
equation 37954 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ z
equation 37955 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ w
equation 37956 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ u
equation 37957 := x = ((y ◇ (z ◇ (w ◇ z))) ◇ u) ◇ v
equation 37958 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ x) ◇ x
equation 37959 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ x) ◇ y
equation 37960 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ x) ◇ z
equation 37961 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ x) ◇ w
equation 37962 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ x) ◇ u
equation 37963 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ y) ◇ x
equation 37964 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ y) ◇ y
equation 37965 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ y) ◇ z
equation 37966 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ y) ◇ w
equation 37967 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ y) ◇ u
equation 37968 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ z) ◇ x
equation 37969 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ z) ◇ y
equation 37970 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ z) ◇ z
equation 37971 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ z) ◇ w
equation 37972 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ z) ◇ u
equation 37973 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ w) ◇ x
equation 37974 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ w) ◇ y
equation 37975 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ w) ◇ z
equation 37976 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ w) ◇ w
equation 37977 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ w) ◇ u
equation 37978 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ x
equation 37979 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ y
equation 37980 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ z
equation 37981 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ w
equation 37982 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ u
equation 37983 := x = ((y ◇ (z ◇ (w ◇ w))) ◇ u) ◇ v
equation 37984 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ x
equation 37985 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ y
equation 37986 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ z
equation 37987 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ w
equation 37988 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ u
equation 37989 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ x) ◇ v
equation 37990 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ x
equation 37991 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ y
equation 37992 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ z
equation 37993 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ w
equation 37994 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ u
equation 37995 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ y) ◇ v
equation 37996 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ x
equation 37997 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ y
equation 37998 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ z
equation 37999 := x = ((y ◇ (z ◇ (w ◇ u))) ◇ z) ◇ w
