import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 30000-30999 -/

equation 30000 := x = (y ◇ (z ◇ (w ◇ (x ◇ z)))) ◇ w
equation 30001 := x = (y ◇ (z ◇ (w ◇ (x ◇ z)))) ◇ u
equation 30002 := x = (y ◇ (z ◇ (w ◇ (x ◇ w)))) ◇ x
equation 30003 := x = (y ◇ (z ◇ (w ◇ (x ◇ w)))) ◇ y
equation 30004 := x = (y ◇ (z ◇ (w ◇ (x ◇ w)))) ◇ z
equation 30005 := x = (y ◇ (z ◇ (w ◇ (x ◇ w)))) ◇ w
equation 30006 := x = (y ◇ (z ◇ (w ◇ (x ◇ w)))) ◇ u
equation 30007 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ x
equation 30008 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ y
equation 30009 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ z
equation 30010 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ w
equation 30011 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ u
equation 30012 := x = (y ◇ (z ◇ (w ◇ (x ◇ u)))) ◇ v
equation 30013 := x = (y ◇ (z ◇ (w ◇ (y ◇ x)))) ◇ x
equation 30014 := x = (y ◇ (z ◇ (w ◇ (y ◇ x)))) ◇ y
equation 30015 := x = (y ◇ (z ◇ (w ◇ (y ◇ x)))) ◇ z
equation 30016 := x = (y ◇ (z ◇ (w ◇ (y ◇ x)))) ◇ w
equation 30017 := x = (y ◇ (z ◇ (w ◇ (y ◇ x)))) ◇ u
equation 30018 := x = (y ◇ (z ◇ (w ◇ (y ◇ y)))) ◇ x
equation 30019 := x = (y ◇ (z ◇ (w ◇ (y ◇ y)))) ◇ y
equation 30020 := x = (y ◇ (z ◇ (w ◇ (y ◇ y)))) ◇ z
equation 30021 := x = (y ◇ (z ◇ (w ◇ (y ◇ y)))) ◇ w
equation 30022 := x = (y ◇ (z ◇ (w ◇ (y ◇ y)))) ◇ u
equation 30023 := x = (y ◇ (z ◇ (w ◇ (y ◇ z)))) ◇ x
equation 30024 := x = (y ◇ (z ◇ (w ◇ (y ◇ z)))) ◇ y
equation 30025 := x = (y ◇ (z ◇ (w ◇ (y ◇ z)))) ◇ z
equation 30026 := x = (y ◇ (z ◇ (w ◇ (y ◇ z)))) ◇ w
equation 30027 := x = (y ◇ (z ◇ (w ◇ (y ◇ z)))) ◇ u
equation 30028 := x = (y ◇ (z ◇ (w ◇ (y ◇ w)))) ◇ x
equation 30029 := x = (y ◇ (z ◇ (w ◇ (y ◇ w)))) ◇ y
equation 30030 := x = (y ◇ (z ◇ (w ◇ (y ◇ w)))) ◇ z
equation 30031 := x = (y ◇ (z ◇ (w ◇ (y ◇ w)))) ◇ w
equation 30032 := x = (y ◇ (z ◇ (w ◇ (y ◇ w)))) ◇ u
equation 30033 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ x
equation 30034 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ y
equation 30035 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ z
equation 30036 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ w
equation 30037 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ u
equation 30038 := x = (y ◇ (z ◇ (w ◇ (y ◇ u)))) ◇ v
equation 30039 := x = (y ◇ (z ◇ (w ◇ (z ◇ x)))) ◇ x
equation 30040 := x = (y ◇ (z ◇ (w ◇ (z ◇ x)))) ◇ y
equation 30041 := x = (y ◇ (z ◇ (w ◇ (z ◇ x)))) ◇ z
equation 30042 := x = (y ◇ (z ◇ (w ◇ (z ◇ x)))) ◇ w
equation 30043 := x = (y ◇ (z ◇ (w ◇ (z ◇ x)))) ◇ u
equation 30044 := x = (y ◇ (z ◇ (w ◇ (z ◇ y)))) ◇ x
equation 30045 := x = (y ◇ (z ◇ (w ◇ (z ◇ y)))) ◇ y
equation 30046 := x = (y ◇ (z ◇ (w ◇ (z ◇ y)))) ◇ z
equation 30047 := x = (y ◇ (z ◇ (w ◇ (z ◇ y)))) ◇ w
equation 30048 := x = (y ◇ (z ◇ (w ◇ (z ◇ y)))) ◇ u
equation 30049 := x = (y ◇ (z ◇ (w ◇ (z ◇ z)))) ◇ x
equation 30050 := x = (y ◇ (z ◇ (w ◇ (z ◇ z)))) ◇ y
equation 30051 := x = (y ◇ (z ◇ (w ◇ (z ◇ z)))) ◇ z
equation 30052 := x = (y ◇ (z ◇ (w ◇ (z ◇ z)))) ◇ w
equation 30053 := x = (y ◇ (z ◇ (w ◇ (z ◇ z)))) ◇ u
equation 30054 := x = (y ◇ (z ◇ (w ◇ (z ◇ w)))) ◇ x
equation 30055 := x = (y ◇ (z ◇ (w ◇ (z ◇ w)))) ◇ y
equation 30056 := x = (y ◇ (z ◇ (w ◇ (z ◇ w)))) ◇ z
equation 30057 := x = (y ◇ (z ◇ (w ◇ (z ◇ w)))) ◇ w
equation 30058 := x = (y ◇ (z ◇ (w ◇ (z ◇ w)))) ◇ u
equation 30059 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ x
equation 30060 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ y
equation 30061 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ z
equation 30062 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ w
equation 30063 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ u
equation 30064 := x = (y ◇ (z ◇ (w ◇ (z ◇ u)))) ◇ v
equation 30065 := x = (y ◇ (z ◇ (w ◇ (w ◇ x)))) ◇ x
equation 30066 := x = (y ◇ (z ◇ (w ◇ (w ◇ x)))) ◇ y
equation 30067 := x = (y ◇ (z ◇ (w ◇ (w ◇ x)))) ◇ z
equation 30068 := x = (y ◇ (z ◇ (w ◇ (w ◇ x)))) ◇ w
equation 30069 := x = (y ◇ (z ◇ (w ◇ (w ◇ x)))) ◇ u
equation 30070 := x = (y ◇ (z ◇ (w ◇ (w ◇ y)))) ◇ x
equation 30071 := x = (y ◇ (z ◇ (w ◇ (w ◇ y)))) ◇ y
equation 30072 := x = (y ◇ (z ◇ (w ◇ (w ◇ y)))) ◇ z
equation 30073 := x = (y ◇ (z ◇ (w ◇ (w ◇ y)))) ◇ w
equation 30074 := x = (y ◇ (z ◇ (w ◇ (w ◇ y)))) ◇ u
equation 30075 := x = (y ◇ (z ◇ (w ◇ (w ◇ z)))) ◇ x
equation 30076 := x = (y ◇ (z ◇ (w ◇ (w ◇ z)))) ◇ y
equation 30077 := x = (y ◇ (z ◇ (w ◇ (w ◇ z)))) ◇ z
equation 30078 := x = (y ◇ (z ◇ (w ◇ (w ◇ z)))) ◇ w
equation 30079 := x = (y ◇ (z ◇ (w ◇ (w ◇ z)))) ◇ u
equation 30080 := x = (y ◇ (z ◇ (w ◇ (w ◇ w)))) ◇ x
equation 30081 := x = (y ◇ (z ◇ (w ◇ (w ◇ w)))) ◇ y
equation 30082 := x = (y ◇ (z ◇ (w ◇ (w ◇ w)))) ◇ z
equation 30083 := x = (y ◇ (z ◇ (w ◇ (w ◇ w)))) ◇ w
equation 30084 := x = (y ◇ (z ◇ (w ◇ (w ◇ w)))) ◇ u
equation 30085 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ x
equation 30086 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ y
equation 30087 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ z
equation 30088 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ w
equation 30089 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ u
equation 30090 := x = (y ◇ (z ◇ (w ◇ (w ◇ u)))) ◇ v
equation 30091 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ x
equation 30092 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ y
equation 30093 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ z
equation 30094 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ w
equation 30095 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ u
equation 30096 := x = (y ◇ (z ◇ (w ◇ (u ◇ x)))) ◇ v
equation 30097 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ x
equation 30098 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ y
equation 30099 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ z
equation 30100 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ w
equation 30101 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ u
equation 30102 := x = (y ◇ (z ◇ (w ◇ (u ◇ y)))) ◇ v
equation 30103 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ x
equation 30104 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ y
equation 30105 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ z
equation 30106 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ w
equation 30107 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ u
equation 30108 := x = (y ◇ (z ◇ (w ◇ (u ◇ z)))) ◇ v
equation 30109 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ x
equation 30110 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ y
equation 30111 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ z
equation 30112 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ w
equation 30113 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ u
equation 30114 := x = (y ◇ (z ◇ (w ◇ (u ◇ w)))) ◇ v
equation 30115 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ x
equation 30116 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ y
equation 30117 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ z
equation 30118 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ w
equation 30119 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ u
equation 30120 := x = (y ◇ (z ◇ (w ◇ (u ◇ u)))) ◇ v
equation 30121 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ x
equation 30122 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ y
equation 30123 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ z
equation 30124 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ w
equation 30125 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ u
equation 30126 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ v
equation 30127 := x = (y ◇ (z ◇ (w ◇ (u ◇ v)))) ◇ r
equation 30128 := x = (x ◇ (x ◇ ((x ◇ x) ◇ x))) ◇ x
equation 30129 := x = (x ◇ (x ◇ ((x ◇ x) ◇ x))) ◇ y
equation 30130 := x = (x ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ x
equation 30131 := x = (x ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ y
equation 30132 := x = (x ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ z
equation 30133 := x = (x ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ x
equation 30134 := x = (x ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ y
equation 30135 := x = (x ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ z
equation 30136 := x = (x ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ x
equation 30137 := x = (x ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ y
equation 30138 := x = (x ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ z
equation 30139 := x = (x ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ x
equation 30140 := x = (x ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ y
equation 30141 := x = (x ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ z
equation 30142 := x = (x ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ w
equation 30143 := x = (x ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ x
equation 30144 := x = (x ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ y
equation 30145 := x = (x ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ z
equation 30146 := x = (x ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ x
equation 30147 := x = (x ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ y
equation 30148 := x = (x ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ z
equation 30149 := x = (x ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ x
equation 30150 := x = (x ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ y
equation 30151 := x = (x ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ z
equation 30152 := x = (x ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ w
equation 30153 := x = (x ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ x
equation 30154 := x = (x ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ y
equation 30155 := x = (x ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ z
equation 30156 := x = (x ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ x
equation 30157 := x = (x ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ y
equation 30158 := x = (x ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ z
equation 30159 := x = (x ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ x
equation 30160 := x = (x ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ y
equation 30161 := x = (x ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ z
equation 30162 := x = (x ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ w
equation 30163 := x = (x ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ x
equation 30164 := x = (x ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ y
equation 30165 := x = (x ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ z
equation 30166 := x = (x ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ w
equation 30167 := x = (x ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ x
equation 30168 := x = (x ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ y
equation 30169 := x = (x ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ z
equation 30170 := x = (x ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ w
equation 30171 := x = (x ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ x
equation 30172 := x = (x ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ y
equation 30173 := x = (x ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ z
equation 30174 := x = (x ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ w
equation 30175 := x = (x ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ x
equation 30176 := x = (x ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ y
equation 30177 := x = (x ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ z
equation 30178 := x = (x ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ w
equation 30179 := x = (x ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ u
equation 30180 := x = (x ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ x
equation 30181 := x = (x ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ y
equation 30182 := x = (x ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ z
equation 30183 := x = (x ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ x
equation 30184 := x = (x ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ y
equation 30185 := x = (x ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ z
equation 30186 := x = (x ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ x
equation 30187 := x = (x ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ y
equation 30188 := x = (x ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ z
equation 30189 := x = (x ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ w
equation 30190 := x = (x ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ x
equation 30191 := x = (x ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ y
equation 30192 := x = (x ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ z
equation 30193 := x = (x ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ x
equation 30194 := x = (x ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ y
equation 30195 := x = (x ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ z
equation 30196 := x = (x ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ x
equation 30197 := x = (x ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ y
equation 30198 := x = (x ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ z
equation 30199 := x = (x ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ w
equation 30200 := x = (x ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ x
equation 30201 := x = (x ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ y
equation 30202 := x = (x ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ z
equation 30203 := x = (x ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ w
equation 30204 := x = (x ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ x
equation 30205 := x = (x ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ y
equation 30206 := x = (x ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ z
equation 30207 := x = (x ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ w
equation 30208 := x = (x ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ x
equation 30209 := x = (x ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ y
equation 30210 := x = (x ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ z
equation 30211 := x = (x ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ w
equation 30212 := x = (x ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ x
equation 30213 := x = (x ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ y
equation 30214 := x = (x ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ z
equation 30215 := x = (x ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ w
equation 30216 := x = (x ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ u
equation 30217 := x = (x ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ x
equation 30218 := x = (x ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ y
equation 30219 := x = (x ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ z
equation 30220 := x = (x ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ x
equation 30221 := x = (x ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ y
equation 30222 := x = (x ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ z
equation 30223 := x = (x ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ x
equation 30224 := x = (x ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ y
equation 30225 := x = (x ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ z
equation 30226 := x = (x ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ w
equation 30227 := x = (x ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ x
equation 30228 := x = (x ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ y
equation 30229 := x = (x ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ z
equation 30230 := x = (x ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ x
equation 30231 := x = (x ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ y
equation 30232 := x = (x ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ z
equation 30233 := x = (x ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ x
equation 30234 := x = (x ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ y
equation 30235 := x = (x ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ z
equation 30236 := x = (x ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ w
equation 30237 := x = (x ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ x
equation 30238 := x = (x ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ y
equation 30239 := x = (x ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ z
equation 30240 := x = (x ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ w
equation 30241 := x = (x ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ x
equation 30242 := x = (x ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ y
equation 30243 := x = (x ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ z
equation 30244 := x = (x ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ w
equation 30245 := x = (x ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ x
equation 30246 := x = (x ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ y
equation 30247 := x = (x ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ z
equation 30248 := x = (x ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ w
equation 30249 := x = (x ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ x
equation 30250 := x = (x ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ y
equation 30251 := x = (x ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ z
equation 30252 := x = (x ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ w
equation 30253 := x = (x ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ u
equation 30254 := x = (x ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ x
equation 30255 := x = (x ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ y
equation 30256 := x = (x ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ z
equation 30257 := x = (x ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ w
equation 30258 := x = (x ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ x
equation 30259 := x = (x ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ y
equation 30260 := x = (x ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ z
equation 30261 := x = (x ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ w
equation 30262 := x = (x ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ x
equation 30263 := x = (x ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ y
equation 30264 := x = (x ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ z
equation 30265 := x = (x ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ w
equation 30266 := x = (x ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ x
equation 30267 := x = (x ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ y
equation 30268 := x = (x ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ z
equation 30269 := x = (x ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ w
equation 30270 := x = (x ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ u
equation 30271 := x = (x ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ x
equation 30272 := x = (x ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ y
equation 30273 := x = (x ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ z
equation 30274 := x = (x ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ w
equation 30275 := x = (x ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ x
equation 30276 := x = (x ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ y
equation 30277 := x = (x ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ z
equation 30278 := x = (x ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ w
equation 30279 := x = (x ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ x
equation 30280 := x = (x ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ y
equation 30281 := x = (x ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ z
equation 30282 := x = (x ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ w
equation 30283 := x = (x ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ x
equation 30284 := x = (x ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ y
equation 30285 := x = (x ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ z
equation 30286 := x = (x ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ w
equation 30287 := x = (x ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ u
equation 30288 := x = (x ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ x
equation 30289 := x = (x ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ y
equation 30290 := x = (x ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ z
equation 30291 := x = (x ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ w
equation 30292 := x = (x ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ x
equation 30293 := x = (x ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ y
equation 30294 := x = (x ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ z
equation 30295 := x = (x ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ w
equation 30296 := x = (x ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ x
equation 30297 := x = (x ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ y
equation 30298 := x = (x ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ z
equation 30299 := x = (x ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ w
equation 30300 := x = (x ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ x
equation 30301 := x = (x ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ y
equation 30302 := x = (x ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ z
equation 30303 := x = (x ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ w
equation 30304 := x = (x ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ u
equation 30305 := x = (x ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ x
equation 30306 := x = (x ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ y
equation 30307 := x = (x ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ z
equation 30308 := x = (x ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ w
equation 30309 := x = (x ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ u
equation 30310 := x = (x ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ x
equation 30311 := x = (x ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ y
equation 30312 := x = (x ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ z
equation 30313 := x = (x ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ w
equation 30314 := x = (x ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ u
equation 30315 := x = (x ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ x
equation 30316 := x = (x ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ y
equation 30317 := x = (x ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ z
equation 30318 := x = (x ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ w
equation 30319 := x = (x ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ u
equation 30320 := x = (x ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ x
equation 30321 := x = (x ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ y
equation 30322 := x = (x ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ z
equation 30323 := x = (x ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ w
equation 30324 := x = (x ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ u
equation 30325 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ x
equation 30326 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ y
equation 30327 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ z
equation 30328 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ w
equation 30329 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ u
equation 30330 := x = (x ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ v
equation 30331 := x = (y ◇ (x ◇ ((x ◇ x) ◇ x))) ◇ x
equation 30332 := x = (y ◇ (x ◇ ((x ◇ x) ◇ x))) ◇ y
equation 30333 := x = (y ◇ (x ◇ ((x ◇ x) ◇ x))) ◇ z
equation 30334 := x = (y ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ x
equation 30335 := x = (y ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ y
equation 30336 := x = (y ◇ (x ◇ ((x ◇ x) ◇ y))) ◇ z
equation 30337 := x = (y ◇ (x ◇ ((x ◇ x) ◇ z))) ◇ x
equation 30338 := x = (y ◇ (x ◇ ((x ◇ x) ◇ z))) ◇ y
equation 30339 := x = (y ◇ (x ◇ ((x ◇ x) ◇ z))) ◇ z
equation 30340 := x = (y ◇ (x ◇ ((x ◇ x) ◇ z))) ◇ w
equation 30341 := x = (y ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ x
equation 30342 := x = (y ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ y
equation 30343 := x = (y ◇ (x ◇ ((x ◇ y) ◇ x))) ◇ z
equation 30344 := x = (y ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ x
equation 30345 := x = (y ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ y
equation 30346 := x = (y ◇ (x ◇ ((x ◇ y) ◇ y))) ◇ z
equation 30347 := x = (y ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ x
equation 30348 := x = (y ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ y
equation 30349 := x = (y ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ z
equation 30350 := x = (y ◇ (x ◇ ((x ◇ y) ◇ z))) ◇ w
equation 30351 := x = (y ◇ (x ◇ ((x ◇ z) ◇ x))) ◇ x
equation 30352 := x = (y ◇ (x ◇ ((x ◇ z) ◇ x))) ◇ y
equation 30353 := x = (y ◇ (x ◇ ((x ◇ z) ◇ x))) ◇ z
equation 30354 := x = (y ◇ (x ◇ ((x ◇ z) ◇ x))) ◇ w
equation 30355 := x = (y ◇ (x ◇ ((x ◇ z) ◇ y))) ◇ x
equation 30356 := x = (y ◇ (x ◇ ((x ◇ z) ◇ y))) ◇ y
equation 30357 := x = (y ◇ (x ◇ ((x ◇ z) ◇ y))) ◇ z
equation 30358 := x = (y ◇ (x ◇ ((x ◇ z) ◇ y))) ◇ w
equation 30359 := x = (y ◇ (x ◇ ((x ◇ z) ◇ z))) ◇ x
equation 30360 := x = (y ◇ (x ◇ ((x ◇ z) ◇ z))) ◇ y
equation 30361 := x = (y ◇ (x ◇ ((x ◇ z) ◇ z))) ◇ z
equation 30362 := x = (y ◇ (x ◇ ((x ◇ z) ◇ z))) ◇ w
equation 30363 := x = (y ◇ (x ◇ ((x ◇ z) ◇ w))) ◇ x
equation 30364 := x = (y ◇ (x ◇ ((x ◇ z) ◇ w))) ◇ y
equation 30365 := x = (y ◇ (x ◇ ((x ◇ z) ◇ w))) ◇ z
equation 30366 := x = (y ◇ (x ◇ ((x ◇ z) ◇ w))) ◇ w
equation 30367 := x = (y ◇ (x ◇ ((x ◇ z) ◇ w))) ◇ u
equation 30368 := x = (y ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ x
equation 30369 := x = (y ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ y
equation 30370 := x = (y ◇ (x ◇ ((y ◇ x) ◇ x))) ◇ z
equation 30371 := x = (y ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ x
equation 30372 := x = (y ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ y
equation 30373 := x = (y ◇ (x ◇ ((y ◇ x) ◇ y))) ◇ z
equation 30374 := x = (y ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ x
equation 30375 := x = (y ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ y
equation 30376 := x = (y ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ z
equation 30377 := x = (y ◇ (x ◇ ((y ◇ x) ◇ z))) ◇ w
equation 30378 := x = (y ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ x
equation 30379 := x = (y ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ y
equation 30380 := x = (y ◇ (x ◇ ((y ◇ y) ◇ x))) ◇ z
equation 30381 := x = (y ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ x
equation 30382 := x = (y ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ y
equation 30383 := x = (y ◇ (x ◇ ((y ◇ y) ◇ y))) ◇ z
equation 30384 := x = (y ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ x
equation 30385 := x = (y ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ y
equation 30386 := x = (y ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ z
equation 30387 := x = (y ◇ (x ◇ ((y ◇ y) ◇ z))) ◇ w
equation 30388 := x = (y ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ x
equation 30389 := x = (y ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ y
equation 30390 := x = (y ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ z
equation 30391 := x = (y ◇ (x ◇ ((y ◇ z) ◇ x))) ◇ w
equation 30392 := x = (y ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ x
equation 30393 := x = (y ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ y
equation 30394 := x = (y ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ z
equation 30395 := x = (y ◇ (x ◇ ((y ◇ z) ◇ y))) ◇ w
equation 30396 := x = (y ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ x
equation 30397 := x = (y ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ y
equation 30398 := x = (y ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ z
equation 30399 := x = (y ◇ (x ◇ ((y ◇ z) ◇ z))) ◇ w
equation 30400 := x = (y ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ x
equation 30401 := x = (y ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ y
equation 30402 := x = (y ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ z
equation 30403 := x = (y ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ w
equation 30404 := x = (y ◇ (x ◇ ((y ◇ z) ◇ w))) ◇ u
equation 30405 := x = (y ◇ (x ◇ ((z ◇ x) ◇ x))) ◇ x
equation 30406 := x = (y ◇ (x ◇ ((z ◇ x) ◇ x))) ◇ y
equation 30407 := x = (y ◇ (x ◇ ((z ◇ x) ◇ x))) ◇ z
equation 30408 := x = (y ◇ (x ◇ ((z ◇ x) ◇ x))) ◇ w
equation 30409 := x = (y ◇ (x ◇ ((z ◇ x) ◇ y))) ◇ x
equation 30410 := x = (y ◇ (x ◇ ((z ◇ x) ◇ y))) ◇ y
equation 30411 := x = (y ◇ (x ◇ ((z ◇ x) ◇ y))) ◇ z
equation 30412 := x = (y ◇ (x ◇ ((z ◇ x) ◇ y))) ◇ w
equation 30413 := x = (y ◇ (x ◇ ((z ◇ x) ◇ z))) ◇ x
equation 30414 := x = (y ◇ (x ◇ ((z ◇ x) ◇ z))) ◇ y
equation 30415 := x = (y ◇ (x ◇ ((z ◇ x) ◇ z))) ◇ z
equation 30416 := x = (y ◇ (x ◇ ((z ◇ x) ◇ z))) ◇ w
equation 30417 := x = (y ◇ (x ◇ ((z ◇ x) ◇ w))) ◇ x
equation 30418 := x = (y ◇ (x ◇ ((z ◇ x) ◇ w))) ◇ y
equation 30419 := x = (y ◇ (x ◇ ((z ◇ x) ◇ w))) ◇ z
equation 30420 := x = (y ◇ (x ◇ ((z ◇ x) ◇ w))) ◇ w
equation 30421 := x = (y ◇ (x ◇ ((z ◇ x) ◇ w))) ◇ u
equation 30422 := x = (y ◇ (x ◇ ((z ◇ y) ◇ x))) ◇ x
equation 30423 := x = (y ◇ (x ◇ ((z ◇ y) ◇ x))) ◇ y
equation 30424 := x = (y ◇ (x ◇ ((z ◇ y) ◇ x))) ◇ z
equation 30425 := x = (y ◇ (x ◇ ((z ◇ y) ◇ x))) ◇ w
equation 30426 := x = (y ◇ (x ◇ ((z ◇ y) ◇ y))) ◇ x
equation 30427 := x = (y ◇ (x ◇ ((z ◇ y) ◇ y))) ◇ y
equation 30428 := x = (y ◇ (x ◇ ((z ◇ y) ◇ y))) ◇ z
equation 30429 := x = (y ◇ (x ◇ ((z ◇ y) ◇ y))) ◇ w
equation 30430 := x = (y ◇ (x ◇ ((z ◇ y) ◇ z))) ◇ x
equation 30431 := x = (y ◇ (x ◇ ((z ◇ y) ◇ z))) ◇ y
equation 30432 := x = (y ◇ (x ◇ ((z ◇ y) ◇ z))) ◇ z
equation 30433 := x = (y ◇ (x ◇ ((z ◇ y) ◇ z))) ◇ w
equation 30434 := x = (y ◇ (x ◇ ((z ◇ y) ◇ w))) ◇ x
equation 30435 := x = (y ◇ (x ◇ ((z ◇ y) ◇ w))) ◇ y
equation 30436 := x = (y ◇ (x ◇ ((z ◇ y) ◇ w))) ◇ z
equation 30437 := x = (y ◇ (x ◇ ((z ◇ y) ◇ w))) ◇ w
equation 30438 := x = (y ◇ (x ◇ ((z ◇ y) ◇ w))) ◇ u
equation 30439 := x = (y ◇ (x ◇ ((z ◇ z) ◇ x))) ◇ x
equation 30440 := x = (y ◇ (x ◇ ((z ◇ z) ◇ x))) ◇ y
equation 30441 := x = (y ◇ (x ◇ ((z ◇ z) ◇ x))) ◇ z
equation 30442 := x = (y ◇ (x ◇ ((z ◇ z) ◇ x))) ◇ w
equation 30443 := x = (y ◇ (x ◇ ((z ◇ z) ◇ y))) ◇ x
equation 30444 := x = (y ◇ (x ◇ ((z ◇ z) ◇ y))) ◇ y
equation 30445 := x = (y ◇ (x ◇ ((z ◇ z) ◇ y))) ◇ z
equation 30446 := x = (y ◇ (x ◇ ((z ◇ z) ◇ y))) ◇ w
equation 30447 := x = (y ◇ (x ◇ ((z ◇ z) ◇ z))) ◇ x
equation 30448 := x = (y ◇ (x ◇ ((z ◇ z) ◇ z))) ◇ y
equation 30449 := x = (y ◇ (x ◇ ((z ◇ z) ◇ z))) ◇ z
equation 30450 := x = (y ◇ (x ◇ ((z ◇ z) ◇ z))) ◇ w
equation 30451 := x = (y ◇ (x ◇ ((z ◇ z) ◇ w))) ◇ x
equation 30452 := x = (y ◇ (x ◇ ((z ◇ z) ◇ w))) ◇ y
equation 30453 := x = (y ◇ (x ◇ ((z ◇ z) ◇ w))) ◇ z
equation 30454 := x = (y ◇ (x ◇ ((z ◇ z) ◇ w))) ◇ w
equation 30455 := x = (y ◇ (x ◇ ((z ◇ z) ◇ w))) ◇ u
equation 30456 := x = (y ◇ (x ◇ ((z ◇ w) ◇ x))) ◇ x
equation 30457 := x = (y ◇ (x ◇ ((z ◇ w) ◇ x))) ◇ y
equation 30458 := x = (y ◇ (x ◇ ((z ◇ w) ◇ x))) ◇ z
equation 30459 := x = (y ◇ (x ◇ ((z ◇ w) ◇ x))) ◇ w
equation 30460 := x = (y ◇ (x ◇ ((z ◇ w) ◇ x))) ◇ u
equation 30461 := x = (y ◇ (x ◇ ((z ◇ w) ◇ y))) ◇ x
equation 30462 := x = (y ◇ (x ◇ ((z ◇ w) ◇ y))) ◇ y
equation 30463 := x = (y ◇ (x ◇ ((z ◇ w) ◇ y))) ◇ z
equation 30464 := x = (y ◇ (x ◇ ((z ◇ w) ◇ y))) ◇ w
equation 30465 := x = (y ◇ (x ◇ ((z ◇ w) ◇ y))) ◇ u
equation 30466 := x = (y ◇ (x ◇ ((z ◇ w) ◇ z))) ◇ x
equation 30467 := x = (y ◇ (x ◇ ((z ◇ w) ◇ z))) ◇ y
equation 30468 := x = (y ◇ (x ◇ ((z ◇ w) ◇ z))) ◇ z
equation 30469 := x = (y ◇ (x ◇ ((z ◇ w) ◇ z))) ◇ w
equation 30470 := x = (y ◇ (x ◇ ((z ◇ w) ◇ z))) ◇ u
equation 30471 := x = (y ◇ (x ◇ ((z ◇ w) ◇ w))) ◇ x
equation 30472 := x = (y ◇ (x ◇ ((z ◇ w) ◇ w))) ◇ y
equation 30473 := x = (y ◇ (x ◇ ((z ◇ w) ◇ w))) ◇ z
equation 30474 := x = (y ◇ (x ◇ ((z ◇ w) ◇ w))) ◇ w
equation 30475 := x = (y ◇ (x ◇ ((z ◇ w) ◇ w))) ◇ u
equation 30476 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ x
equation 30477 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ y
equation 30478 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ z
equation 30479 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ w
equation 30480 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ u
equation 30481 := x = (y ◇ (x ◇ ((z ◇ w) ◇ u))) ◇ v
equation 30482 := x = (y ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ x
equation 30483 := x = (y ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ y
equation 30484 := x = (y ◇ (y ◇ ((x ◇ x) ◇ x))) ◇ z
equation 30485 := x = (y ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ x
equation 30486 := x = (y ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ y
equation 30487 := x = (y ◇ (y ◇ ((x ◇ x) ◇ y))) ◇ z
equation 30488 := x = (y ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ x
equation 30489 := x = (y ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ y
equation 30490 := x = (y ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ z
equation 30491 := x = (y ◇ (y ◇ ((x ◇ x) ◇ z))) ◇ w
equation 30492 := x = (y ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ x
equation 30493 := x = (y ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ y
equation 30494 := x = (y ◇ (y ◇ ((x ◇ y) ◇ x))) ◇ z
equation 30495 := x = (y ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ x
equation 30496 := x = (y ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ y
equation 30497 := x = (y ◇ (y ◇ ((x ◇ y) ◇ y))) ◇ z
equation 30498 := x = (y ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ x
equation 30499 := x = (y ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ y
equation 30500 := x = (y ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ z
equation 30501 := x = (y ◇ (y ◇ ((x ◇ y) ◇ z))) ◇ w
equation 30502 := x = (y ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ x
equation 30503 := x = (y ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ y
equation 30504 := x = (y ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ z
equation 30505 := x = (y ◇ (y ◇ ((x ◇ z) ◇ x))) ◇ w
equation 30506 := x = (y ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ x
equation 30507 := x = (y ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ y
equation 30508 := x = (y ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ z
equation 30509 := x = (y ◇ (y ◇ ((x ◇ z) ◇ y))) ◇ w
equation 30510 := x = (y ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ x
equation 30511 := x = (y ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ y
equation 30512 := x = (y ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ z
equation 30513 := x = (y ◇ (y ◇ ((x ◇ z) ◇ z))) ◇ w
equation 30514 := x = (y ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ x
equation 30515 := x = (y ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ y
equation 30516 := x = (y ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ z
equation 30517 := x = (y ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ w
equation 30518 := x = (y ◇ (y ◇ ((x ◇ z) ◇ w))) ◇ u
equation 30519 := x = (y ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ x
equation 30520 := x = (y ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ y
equation 30521 := x = (y ◇ (y ◇ ((y ◇ x) ◇ x))) ◇ z
equation 30522 := x = (y ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ x
equation 30523 := x = (y ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ y
equation 30524 := x = (y ◇ (y ◇ ((y ◇ x) ◇ y))) ◇ z
equation 30525 := x = (y ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ x
equation 30526 := x = (y ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ y
equation 30527 := x = (y ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ z
equation 30528 := x = (y ◇ (y ◇ ((y ◇ x) ◇ z))) ◇ w
equation 30529 := x = (y ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ x
equation 30530 := x = (y ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ y
equation 30531 := x = (y ◇ (y ◇ ((y ◇ y) ◇ x))) ◇ z
equation 30532 := x = (y ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ x
equation 30533 := x = (y ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ y
equation 30534 := x = (y ◇ (y ◇ ((y ◇ y) ◇ y))) ◇ z
equation 30535 := x = (y ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ x
equation 30536 := x = (y ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ y
equation 30537 := x = (y ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ z
equation 30538 := x = (y ◇ (y ◇ ((y ◇ y) ◇ z))) ◇ w
equation 30539 := x = (y ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ x
equation 30540 := x = (y ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ y
equation 30541 := x = (y ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ z
equation 30542 := x = (y ◇ (y ◇ ((y ◇ z) ◇ x))) ◇ w
equation 30543 := x = (y ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ x
equation 30544 := x = (y ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ y
equation 30545 := x = (y ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ z
equation 30546 := x = (y ◇ (y ◇ ((y ◇ z) ◇ y))) ◇ w
equation 30547 := x = (y ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ x
equation 30548 := x = (y ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ y
equation 30549 := x = (y ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ z
equation 30550 := x = (y ◇ (y ◇ ((y ◇ z) ◇ z))) ◇ w
equation 30551 := x = (y ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ x
equation 30552 := x = (y ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ y
equation 30553 := x = (y ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ z
equation 30554 := x = (y ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ w
equation 30555 := x = (y ◇ (y ◇ ((y ◇ z) ◇ w))) ◇ u
equation 30556 := x = (y ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ x
equation 30557 := x = (y ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ y
equation 30558 := x = (y ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ z
equation 30559 := x = (y ◇ (y ◇ ((z ◇ x) ◇ x))) ◇ w
equation 30560 := x = (y ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ x
equation 30561 := x = (y ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ y
equation 30562 := x = (y ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ z
equation 30563 := x = (y ◇ (y ◇ ((z ◇ x) ◇ y))) ◇ w
equation 30564 := x = (y ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ x
equation 30565 := x = (y ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ y
equation 30566 := x = (y ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ z
equation 30567 := x = (y ◇ (y ◇ ((z ◇ x) ◇ z))) ◇ w
equation 30568 := x = (y ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ x
equation 30569 := x = (y ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ y
equation 30570 := x = (y ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ z
equation 30571 := x = (y ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ w
equation 30572 := x = (y ◇ (y ◇ ((z ◇ x) ◇ w))) ◇ u
equation 30573 := x = (y ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ x
equation 30574 := x = (y ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ y
equation 30575 := x = (y ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ z
equation 30576 := x = (y ◇ (y ◇ ((z ◇ y) ◇ x))) ◇ w
equation 30577 := x = (y ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ x
equation 30578 := x = (y ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ y
equation 30579 := x = (y ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ z
equation 30580 := x = (y ◇ (y ◇ ((z ◇ y) ◇ y))) ◇ w
equation 30581 := x = (y ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ x
equation 30582 := x = (y ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ y
equation 30583 := x = (y ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ z
equation 30584 := x = (y ◇ (y ◇ ((z ◇ y) ◇ z))) ◇ w
equation 30585 := x = (y ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ x
equation 30586 := x = (y ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ y
equation 30587 := x = (y ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ z
equation 30588 := x = (y ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ w
equation 30589 := x = (y ◇ (y ◇ ((z ◇ y) ◇ w))) ◇ u
equation 30590 := x = (y ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ x
equation 30591 := x = (y ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ y
equation 30592 := x = (y ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ z
equation 30593 := x = (y ◇ (y ◇ ((z ◇ z) ◇ x))) ◇ w
equation 30594 := x = (y ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ x
equation 30595 := x = (y ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ y
equation 30596 := x = (y ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ z
equation 30597 := x = (y ◇ (y ◇ ((z ◇ z) ◇ y))) ◇ w
equation 30598 := x = (y ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ x
equation 30599 := x = (y ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ y
equation 30600 := x = (y ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ z
equation 30601 := x = (y ◇ (y ◇ ((z ◇ z) ◇ z))) ◇ w
equation 30602 := x = (y ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ x
equation 30603 := x = (y ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ y
equation 30604 := x = (y ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ z
equation 30605 := x = (y ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ w
equation 30606 := x = (y ◇ (y ◇ ((z ◇ z) ◇ w))) ◇ u
equation 30607 := x = (y ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ x
equation 30608 := x = (y ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ y
equation 30609 := x = (y ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ z
equation 30610 := x = (y ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ w
equation 30611 := x = (y ◇ (y ◇ ((z ◇ w) ◇ x))) ◇ u
equation 30612 := x = (y ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ x
equation 30613 := x = (y ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ y
equation 30614 := x = (y ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ z
equation 30615 := x = (y ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ w
equation 30616 := x = (y ◇ (y ◇ ((z ◇ w) ◇ y))) ◇ u
equation 30617 := x = (y ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ x
equation 30618 := x = (y ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ y
equation 30619 := x = (y ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ z
equation 30620 := x = (y ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ w
equation 30621 := x = (y ◇ (y ◇ ((z ◇ w) ◇ z))) ◇ u
equation 30622 := x = (y ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ x
equation 30623 := x = (y ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ y
equation 30624 := x = (y ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ z
equation 30625 := x = (y ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ w
equation 30626 := x = (y ◇ (y ◇ ((z ◇ w) ◇ w))) ◇ u
equation 30627 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ x
equation 30628 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ y
equation 30629 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ z
equation 30630 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ w
equation 30631 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ u
equation 30632 := x = (y ◇ (y ◇ ((z ◇ w) ◇ u))) ◇ v
equation 30633 := x = (y ◇ (z ◇ ((x ◇ x) ◇ x))) ◇ x
equation 30634 := x = (y ◇ (z ◇ ((x ◇ x) ◇ x))) ◇ y
equation 30635 := x = (y ◇ (z ◇ ((x ◇ x) ◇ x))) ◇ z
equation 30636 := x = (y ◇ (z ◇ ((x ◇ x) ◇ x))) ◇ w
equation 30637 := x = (y ◇ (z ◇ ((x ◇ x) ◇ y))) ◇ x
equation 30638 := x = (y ◇ (z ◇ ((x ◇ x) ◇ y))) ◇ y
equation 30639 := x = (y ◇ (z ◇ ((x ◇ x) ◇ y))) ◇ z
equation 30640 := x = (y ◇ (z ◇ ((x ◇ x) ◇ y))) ◇ w
equation 30641 := x = (y ◇ (z ◇ ((x ◇ x) ◇ z))) ◇ x
equation 30642 := x = (y ◇ (z ◇ ((x ◇ x) ◇ z))) ◇ y
equation 30643 := x = (y ◇ (z ◇ ((x ◇ x) ◇ z))) ◇ z
equation 30644 := x = (y ◇ (z ◇ ((x ◇ x) ◇ z))) ◇ w
equation 30645 := x = (y ◇ (z ◇ ((x ◇ x) ◇ w))) ◇ x
equation 30646 := x = (y ◇ (z ◇ ((x ◇ x) ◇ w))) ◇ y
equation 30647 := x = (y ◇ (z ◇ ((x ◇ x) ◇ w))) ◇ z
equation 30648 := x = (y ◇ (z ◇ ((x ◇ x) ◇ w))) ◇ w
equation 30649 := x = (y ◇ (z ◇ ((x ◇ x) ◇ w))) ◇ u
equation 30650 := x = (y ◇ (z ◇ ((x ◇ y) ◇ x))) ◇ x
equation 30651 := x = (y ◇ (z ◇ ((x ◇ y) ◇ x))) ◇ y
equation 30652 := x = (y ◇ (z ◇ ((x ◇ y) ◇ x))) ◇ z
equation 30653 := x = (y ◇ (z ◇ ((x ◇ y) ◇ x))) ◇ w
equation 30654 := x = (y ◇ (z ◇ ((x ◇ y) ◇ y))) ◇ x
equation 30655 := x = (y ◇ (z ◇ ((x ◇ y) ◇ y))) ◇ y
equation 30656 := x = (y ◇ (z ◇ ((x ◇ y) ◇ y))) ◇ z
equation 30657 := x = (y ◇ (z ◇ ((x ◇ y) ◇ y))) ◇ w
equation 30658 := x = (y ◇ (z ◇ ((x ◇ y) ◇ z))) ◇ x
equation 30659 := x = (y ◇ (z ◇ ((x ◇ y) ◇ z))) ◇ y
equation 30660 := x = (y ◇ (z ◇ ((x ◇ y) ◇ z))) ◇ z
equation 30661 := x = (y ◇ (z ◇ ((x ◇ y) ◇ z))) ◇ w
equation 30662 := x = (y ◇ (z ◇ ((x ◇ y) ◇ w))) ◇ x
equation 30663 := x = (y ◇ (z ◇ ((x ◇ y) ◇ w))) ◇ y
equation 30664 := x = (y ◇ (z ◇ ((x ◇ y) ◇ w))) ◇ z
equation 30665 := x = (y ◇ (z ◇ ((x ◇ y) ◇ w))) ◇ w
equation 30666 := x = (y ◇ (z ◇ ((x ◇ y) ◇ w))) ◇ u
equation 30667 := x = (y ◇ (z ◇ ((x ◇ z) ◇ x))) ◇ x
equation 30668 := x = (y ◇ (z ◇ ((x ◇ z) ◇ x))) ◇ y
equation 30669 := x = (y ◇ (z ◇ ((x ◇ z) ◇ x))) ◇ z
equation 30670 := x = (y ◇ (z ◇ ((x ◇ z) ◇ x))) ◇ w
equation 30671 := x = (y ◇ (z ◇ ((x ◇ z) ◇ y))) ◇ x
equation 30672 := x = (y ◇ (z ◇ ((x ◇ z) ◇ y))) ◇ y
equation 30673 := x = (y ◇ (z ◇ ((x ◇ z) ◇ y))) ◇ z
equation 30674 := x = (y ◇ (z ◇ ((x ◇ z) ◇ y))) ◇ w
equation 30675 := x = (y ◇ (z ◇ ((x ◇ z) ◇ z))) ◇ x
equation 30676 := x = (y ◇ (z ◇ ((x ◇ z) ◇ z))) ◇ y
equation 30677 := x = (y ◇ (z ◇ ((x ◇ z) ◇ z))) ◇ z
equation 30678 := x = (y ◇ (z ◇ ((x ◇ z) ◇ z))) ◇ w
equation 30679 := x = (y ◇ (z ◇ ((x ◇ z) ◇ w))) ◇ x
equation 30680 := x = (y ◇ (z ◇ ((x ◇ z) ◇ w))) ◇ y
equation 30681 := x = (y ◇ (z ◇ ((x ◇ z) ◇ w))) ◇ z
equation 30682 := x = (y ◇ (z ◇ ((x ◇ z) ◇ w))) ◇ w
equation 30683 := x = (y ◇ (z ◇ ((x ◇ z) ◇ w))) ◇ u
equation 30684 := x = (y ◇ (z ◇ ((x ◇ w) ◇ x))) ◇ x
equation 30685 := x = (y ◇ (z ◇ ((x ◇ w) ◇ x))) ◇ y
equation 30686 := x = (y ◇ (z ◇ ((x ◇ w) ◇ x))) ◇ z
equation 30687 := x = (y ◇ (z ◇ ((x ◇ w) ◇ x))) ◇ w
equation 30688 := x = (y ◇ (z ◇ ((x ◇ w) ◇ x))) ◇ u
equation 30689 := x = (y ◇ (z ◇ ((x ◇ w) ◇ y))) ◇ x
equation 30690 := x = (y ◇ (z ◇ ((x ◇ w) ◇ y))) ◇ y
equation 30691 := x = (y ◇ (z ◇ ((x ◇ w) ◇ y))) ◇ z
equation 30692 := x = (y ◇ (z ◇ ((x ◇ w) ◇ y))) ◇ w
equation 30693 := x = (y ◇ (z ◇ ((x ◇ w) ◇ y))) ◇ u
equation 30694 := x = (y ◇ (z ◇ ((x ◇ w) ◇ z))) ◇ x
equation 30695 := x = (y ◇ (z ◇ ((x ◇ w) ◇ z))) ◇ y
equation 30696 := x = (y ◇ (z ◇ ((x ◇ w) ◇ z))) ◇ z
equation 30697 := x = (y ◇ (z ◇ ((x ◇ w) ◇ z))) ◇ w
equation 30698 := x = (y ◇ (z ◇ ((x ◇ w) ◇ z))) ◇ u
equation 30699 := x = (y ◇ (z ◇ ((x ◇ w) ◇ w))) ◇ x
equation 30700 := x = (y ◇ (z ◇ ((x ◇ w) ◇ w))) ◇ y
equation 30701 := x = (y ◇ (z ◇ ((x ◇ w) ◇ w))) ◇ z
equation 30702 := x = (y ◇ (z ◇ ((x ◇ w) ◇ w))) ◇ w
equation 30703 := x = (y ◇ (z ◇ ((x ◇ w) ◇ w))) ◇ u
equation 30704 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ x
equation 30705 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ y
equation 30706 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ z
equation 30707 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ w
equation 30708 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ u
equation 30709 := x = (y ◇ (z ◇ ((x ◇ w) ◇ u))) ◇ v
equation 30710 := x = (y ◇ (z ◇ ((y ◇ x) ◇ x))) ◇ x
equation 30711 := x = (y ◇ (z ◇ ((y ◇ x) ◇ x))) ◇ y
equation 30712 := x = (y ◇ (z ◇ ((y ◇ x) ◇ x))) ◇ z
equation 30713 := x = (y ◇ (z ◇ ((y ◇ x) ◇ x))) ◇ w
equation 30714 := x = (y ◇ (z ◇ ((y ◇ x) ◇ y))) ◇ x
equation 30715 := x = (y ◇ (z ◇ ((y ◇ x) ◇ y))) ◇ y
equation 30716 := x = (y ◇ (z ◇ ((y ◇ x) ◇ y))) ◇ z
equation 30717 := x = (y ◇ (z ◇ ((y ◇ x) ◇ y))) ◇ w
equation 30718 := x = (y ◇ (z ◇ ((y ◇ x) ◇ z))) ◇ x
equation 30719 := x = (y ◇ (z ◇ ((y ◇ x) ◇ z))) ◇ y
equation 30720 := x = (y ◇ (z ◇ ((y ◇ x) ◇ z))) ◇ z
equation 30721 := x = (y ◇ (z ◇ ((y ◇ x) ◇ z))) ◇ w
equation 30722 := x = (y ◇ (z ◇ ((y ◇ x) ◇ w))) ◇ x
equation 30723 := x = (y ◇ (z ◇ ((y ◇ x) ◇ w))) ◇ y
equation 30724 := x = (y ◇ (z ◇ ((y ◇ x) ◇ w))) ◇ z
equation 30725 := x = (y ◇ (z ◇ ((y ◇ x) ◇ w))) ◇ w
equation 30726 := x = (y ◇ (z ◇ ((y ◇ x) ◇ w))) ◇ u
equation 30727 := x = (y ◇ (z ◇ ((y ◇ y) ◇ x))) ◇ x
equation 30728 := x = (y ◇ (z ◇ ((y ◇ y) ◇ x))) ◇ y
equation 30729 := x = (y ◇ (z ◇ ((y ◇ y) ◇ x))) ◇ z
equation 30730 := x = (y ◇ (z ◇ ((y ◇ y) ◇ x))) ◇ w
equation 30731 := x = (y ◇ (z ◇ ((y ◇ y) ◇ y))) ◇ x
equation 30732 := x = (y ◇ (z ◇ ((y ◇ y) ◇ y))) ◇ y
equation 30733 := x = (y ◇ (z ◇ ((y ◇ y) ◇ y))) ◇ z
equation 30734 := x = (y ◇ (z ◇ ((y ◇ y) ◇ y))) ◇ w
equation 30735 := x = (y ◇ (z ◇ ((y ◇ y) ◇ z))) ◇ x
equation 30736 := x = (y ◇ (z ◇ ((y ◇ y) ◇ z))) ◇ y
equation 30737 := x = (y ◇ (z ◇ ((y ◇ y) ◇ z))) ◇ z
equation 30738 := x = (y ◇ (z ◇ ((y ◇ y) ◇ z))) ◇ w
equation 30739 := x = (y ◇ (z ◇ ((y ◇ y) ◇ w))) ◇ x
equation 30740 := x = (y ◇ (z ◇ ((y ◇ y) ◇ w))) ◇ y
equation 30741 := x = (y ◇ (z ◇ ((y ◇ y) ◇ w))) ◇ z
equation 30742 := x = (y ◇ (z ◇ ((y ◇ y) ◇ w))) ◇ w
equation 30743 := x = (y ◇ (z ◇ ((y ◇ y) ◇ w))) ◇ u
equation 30744 := x = (y ◇ (z ◇ ((y ◇ z) ◇ x))) ◇ x
equation 30745 := x = (y ◇ (z ◇ ((y ◇ z) ◇ x))) ◇ y
equation 30746 := x = (y ◇ (z ◇ ((y ◇ z) ◇ x))) ◇ z
equation 30747 := x = (y ◇ (z ◇ ((y ◇ z) ◇ x))) ◇ w
equation 30748 := x = (y ◇ (z ◇ ((y ◇ z) ◇ y))) ◇ x
equation 30749 := x = (y ◇ (z ◇ ((y ◇ z) ◇ y))) ◇ y
equation 30750 := x = (y ◇ (z ◇ ((y ◇ z) ◇ y))) ◇ z
equation 30751 := x = (y ◇ (z ◇ ((y ◇ z) ◇ y))) ◇ w
equation 30752 := x = (y ◇ (z ◇ ((y ◇ z) ◇ z))) ◇ x
equation 30753 := x = (y ◇ (z ◇ ((y ◇ z) ◇ z))) ◇ y
equation 30754 := x = (y ◇ (z ◇ ((y ◇ z) ◇ z))) ◇ z
equation 30755 := x = (y ◇ (z ◇ ((y ◇ z) ◇ z))) ◇ w
equation 30756 := x = (y ◇ (z ◇ ((y ◇ z) ◇ w))) ◇ x
equation 30757 := x = (y ◇ (z ◇ ((y ◇ z) ◇ w))) ◇ y
equation 30758 := x = (y ◇ (z ◇ ((y ◇ z) ◇ w))) ◇ z
equation 30759 := x = (y ◇ (z ◇ ((y ◇ z) ◇ w))) ◇ w
equation 30760 := x = (y ◇ (z ◇ ((y ◇ z) ◇ w))) ◇ u
equation 30761 := x = (y ◇ (z ◇ ((y ◇ w) ◇ x))) ◇ x
equation 30762 := x = (y ◇ (z ◇ ((y ◇ w) ◇ x))) ◇ y
equation 30763 := x = (y ◇ (z ◇ ((y ◇ w) ◇ x))) ◇ z
equation 30764 := x = (y ◇ (z ◇ ((y ◇ w) ◇ x))) ◇ w
equation 30765 := x = (y ◇ (z ◇ ((y ◇ w) ◇ x))) ◇ u
equation 30766 := x = (y ◇ (z ◇ ((y ◇ w) ◇ y))) ◇ x
equation 30767 := x = (y ◇ (z ◇ ((y ◇ w) ◇ y))) ◇ y
equation 30768 := x = (y ◇ (z ◇ ((y ◇ w) ◇ y))) ◇ z
equation 30769 := x = (y ◇ (z ◇ ((y ◇ w) ◇ y))) ◇ w
equation 30770 := x = (y ◇ (z ◇ ((y ◇ w) ◇ y))) ◇ u
equation 30771 := x = (y ◇ (z ◇ ((y ◇ w) ◇ z))) ◇ x
equation 30772 := x = (y ◇ (z ◇ ((y ◇ w) ◇ z))) ◇ y
equation 30773 := x = (y ◇ (z ◇ ((y ◇ w) ◇ z))) ◇ z
equation 30774 := x = (y ◇ (z ◇ ((y ◇ w) ◇ z))) ◇ w
equation 30775 := x = (y ◇ (z ◇ ((y ◇ w) ◇ z))) ◇ u
equation 30776 := x = (y ◇ (z ◇ ((y ◇ w) ◇ w))) ◇ x
equation 30777 := x = (y ◇ (z ◇ ((y ◇ w) ◇ w))) ◇ y
equation 30778 := x = (y ◇ (z ◇ ((y ◇ w) ◇ w))) ◇ z
equation 30779 := x = (y ◇ (z ◇ ((y ◇ w) ◇ w))) ◇ w
equation 30780 := x = (y ◇ (z ◇ ((y ◇ w) ◇ w))) ◇ u
equation 30781 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ x
equation 30782 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ y
equation 30783 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ z
equation 30784 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ w
equation 30785 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ u
equation 30786 := x = (y ◇ (z ◇ ((y ◇ w) ◇ u))) ◇ v
equation 30787 := x = (y ◇ (z ◇ ((z ◇ x) ◇ x))) ◇ x
equation 30788 := x = (y ◇ (z ◇ ((z ◇ x) ◇ x))) ◇ y
equation 30789 := x = (y ◇ (z ◇ ((z ◇ x) ◇ x))) ◇ z
equation 30790 := x = (y ◇ (z ◇ ((z ◇ x) ◇ x))) ◇ w
equation 30791 := x = (y ◇ (z ◇ ((z ◇ x) ◇ y))) ◇ x
equation 30792 := x = (y ◇ (z ◇ ((z ◇ x) ◇ y))) ◇ y
equation 30793 := x = (y ◇ (z ◇ ((z ◇ x) ◇ y))) ◇ z
equation 30794 := x = (y ◇ (z ◇ ((z ◇ x) ◇ y))) ◇ w
equation 30795 := x = (y ◇ (z ◇ ((z ◇ x) ◇ z))) ◇ x
equation 30796 := x = (y ◇ (z ◇ ((z ◇ x) ◇ z))) ◇ y
equation 30797 := x = (y ◇ (z ◇ ((z ◇ x) ◇ z))) ◇ z
equation 30798 := x = (y ◇ (z ◇ ((z ◇ x) ◇ z))) ◇ w
equation 30799 := x = (y ◇ (z ◇ ((z ◇ x) ◇ w))) ◇ x
equation 30800 := x = (y ◇ (z ◇ ((z ◇ x) ◇ w))) ◇ y
equation 30801 := x = (y ◇ (z ◇ ((z ◇ x) ◇ w))) ◇ z
equation 30802 := x = (y ◇ (z ◇ ((z ◇ x) ◇ w))) ◇ w
equation 30803 := x = (y ◇ (z ◇ ((z ◇ x) ◇ w))) ◇ u
equation 30804 := x = (y ◇ (z ◇ ((z ◇ y) ◇ x))) ◇ x
equation 30805 := x = (y ◇ (z ◇ ((z ◇ y) ◇ x))) ◇ y
equation 30806 := x = (y ◇ (z ◇ ((z ◇ y) ◇ x))) ◇ z
equation 30807 := x = (y ◇ (z ◇ ((z ◇ y) ◇ x))) ◇ w
equation 30808 := x = (y ◇ (z ◇ ((z ◇ y) ◇ y))) ◇ x
equation 30809 := x = (y ◇ (z ◇ ((z ◇ y) ◇ y))) ◇ y
equation 30810 := x = (y ◇ (z ◇ ((z ◇ y) ◇ y))) ◇ z
equation 30811 := x = (y ◇ (z ◇ ((z ◇ y) ◇ y))) ◇ w
equation 30812 := x = (y ◇ (z ◇ ((z ◇ y) ◇ z))) ◇ x
equation 30813 := x = (y ◇ (z ◇ ((z ◇ y) ◇ z))) ◇ y
equation 30814 := x = (y ◇ (z ◇ ((z ◇ y) ◇ z))) ◇ z
equation 30815 := x = (y ◇ (z ◇ ((z ◇ y) ◇ z))) ◇ w
equation 30816 := x = (y ◇ (z ◇ ((z ◇ y) ◇ w))) ◇ x
equation 30817 := x = (y ◇ (z ◇ ((z ◇ y) ◇ w))) ◇ y
equation 30818 := x = (y ◇ (z ◇ ((z ◇ y) ◇ w))) ◇ z
equation 30819 := x = (y ◇ (z ◇ ((z ◇ y) ◇ w))) ◇ w
equation 30820 := x = (y ◇ (z ◇ ((z ◇ y) ◇ w))) ◇ u
equation 30821 := x = (y ◇ (z ◇ ((z ◇ z) ◇ x))) ◇ x
equation 30822 := x = (y ◇ (z ◇ ((z ◇ z) ◇ x))) ◇ y
equation 30823 := x = (y ◇ (z ◇ ((z ◇ z) ◇ x))) ◇ z
equation 30824 := x = (y ◇ (z ◇ ((z ◇ z) ◇ x))) ◇ w
equation 30825 := x = (y ◇ (z ◇ ((z ◇ z) ◇ y))) ◇ x
equation 30826 := x = (y ◇ (z ◇ ((z ◇ z) ◇ y))) ◇ y
equation 30827 := x = (y ◇ (z ◇ ((z ◇ z) ◇ y))) ◇ z
equation 30828 := x = (y ◇ (z ◇ ((z ◇ z) ◇ y))) ◇ w
equation 30829 := x = (y ◇ (z ◇ ((z ◇ z) ◇ z))) ◇ x
equation 30830 := x = (y ◇ (z ◇ ((z ◇ z) ◇ z))) ◇ y
equation 30831 := x = (y ◇ (z ◇ ((z ◇ z) ◇ z))) ◇ z
equation 30832 := x = (y ◇ (z ◇ ((z ◇ z) ◇ z))) ◇ w
equation 30833 := x = (y ◇ (z ◇ ((z ◇ z) ◇ w))) ◇ x
equation 30834 := x = (y ◇ (z ◇ ((z ◇ z) ◇ w))) ◇ y
equation 30835 := x = (y ◇ (z ◇ ((z ◇ z) ◇ w))) ◇ z
equation 30836 := x = (y ◇ (z ◇ ((z ◇ z) ◇ w))) ◇ w
equation 30837 := x = (y ◇ (z ◇ ((z ◇ z) ◇ w))) ◇ u
equation 30838 := x = (y ◇ (z ◇ ((z ◇ w) ◇ x))) ◇ x
equation 30839 := x = (y ◇ (z ◇ ((z ◇ w) ◇ x))) ◇ y
equation 30840 := x = (y ◇ (z ◇ ((z ◇ w) ◇ x))) ◇ z
equation 30841 := x = (y ◇ (z ◇ ((z ◇ w) ◇ x))) ◇ w
equation 30842 := x = (y ◇ (z ◇ ((z ◇ w) ◇ x))) ◇ u
equation 30843 := x = (y ◇ (z ◇ ((z ◇ w) ◇ y))) ◇ x
equation 30844 := x = (y ◇ (z ◇ ((z ◇ w) ◇ y))) ◇ y
equation 30845 := x = (y ◇ (z ◇ ((z ◇ w) ◇ y))) ◇ z
equation 30846 := x = (y ◇ (z ◇ ((z ◇ w) ◇ y))) ◇ w
equation 30847 := x = (y ◇ (z ◇ ((z ◇ w) ◇ y))) ◇ u
equation 30848 := x = (y ◇ (z ◇ ((z ◇ w) ◇ z))) ◇ x
equation 30849 := x = (y ◇ (z ◇ ((z ◇ w) ◇ z))) ◇ y
equation 30850 := x = (y ◇ (z ◇ ((z ◇ w) ◇ z))) ◇ z
equation 30851 := x = (y ◇ (z ◇ ((z ◇ w) ◇ z))) ◇ w
equation 30852 := x = (y ◇ (z ◇ ((z ◇ w) ◇ z))) ◇ u
equation 30853 := x = (y ◇ (z ◇ ((z ◇ w) ◇ w))) ◇ x
equation 30854 := x = (y ◇ (z ◇ ((z ◇ w) ◇ w))) ◇ y
equation 30855 := x = (y ◇ (z ◇ ((z ◇ w) ◇ w))) ◇ z
equation 30856 := x = (y ◇ (z ◇ ((z ◇ w) ◇ w))) ◇ w
equation 30857 := x = (y ◇ (z ◇ ((z ◇ w) ◇ w))) ◇ u
equation 30858 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ x
equation 30859 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ y
equation 30860 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ z
equation 30861 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ w
equation 30862 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ u
equation 30863 := x = (y ◇ (z ◇ ((z ◇ w) ◇ u))) ◇ v
equation 30864 := x = (y ◇ (z ◇ ((w ◇ x) ◇ x))) ◇ x
equation 30865 := x = (y ◇ (z ◇ ((w ◇ x) ◇ x))) ◇ y
equation 30866 := x = (y ◇ (z ◇ ((w ◇ x) ◇ x))) ◇ z
equation 30867 := x = (y ◇ (z ◇ ((w ◇ x) ◇ x))) ◇ w
equation 30868 := x = (y ◇ (z ◇ ((w ◇ x) ◇ x))) ◇ u
equation 30869 := x = (y ◇ (z ◇ ((w ◇ x) ◇ y))) ◇ x
equation 30870 := x = (y ◇ (z ◇ ((w ◇ x) ◇ y))) ◇ y
equation 30871 := x = (y ◇ (z ◇ ((w ◇ x) ◇ y))) ◇ z
equation 30872 := x = (y ◇ (z ◇ ((w ◇ x) ◇ y))) ◇ w
equation 30873 := x = (y ◇ (z ◇ ((w ◇ x) ◇ y))) ◇ u
equation 30874 := x = (y ◇ (z ◇ ((w ◇ x) ◇ z))) ◇ x
equation 30875 := x = (y ◇ (z ◇ ((w ◇ x) ◇ z))) ◇ y
equation 30876 := x = (y ◇ (z ◇ ((w ◇ x) ◇ z))) ◇ z
equation 30877 := x = (y ◇ (z ◇ ((w ◇ x) ◇ z))) ◇ w
equation 30878 := x = (y ◇ (z ◇ ((w ◇ x) ◇ z))) ◇ u
equation 30879 := x = (y ◇ (z ◇ ((w ◇ x) ◇ w))) ◇ x
equation 30880 := x = (y ◇ (z ◇ ((w ◇ x) ◇ w))) ◇ y
equation 30881 := x = (y ◇ (z ◇ ((w ◇ x) ◇ w))) ◇ z
equation 30882 := x = (y ◇ (z ◇ ((w ◇ x) ◇ w))) ◇ w
equation 30883 := x = (y ◇ (z ◇ ((w ◇ x) ◇ w))) ◇ u
equation 30884 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ x
equation 30885 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ y
equation 30886 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ z
equation 30887 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ w
equation 30888 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ u
equation 30889 := x = (y ◇ (z ◇ ((w ◇ x) ◇ u))) ◇ v
equation 30890 := x = (y ◇ (z ◇ ((w ◇ y) ◇ x))) ◇ x
equation 30891 := x = (y ◇ (z ◇ ((w ◇ y) ◇ x))) ◇ y
equation 30892 := x = (y ◇ (z ◇ ((w ◇ y) ◇ x))) ◇ z
equation 30893 := x = (y ◇ (z ◇ ((w ◇ y) ◇ x))) ◇ w
equation 30894 := x = (y ◇ (z ◇ ((w ◇ y) ◇ x))) ◇ u
equation 30895 := x = (y ◇ (z ◇ ((w ◇ y) ◇ y))) ◇ x
equation 30896 := x = (y ◇ (z ◇ ((w ◇ y) ◇ y))) ◇ y
equation 30897 := x = (y ◇ (z ◇ ((w ◇ y) ◇ y))) ◇ z
equation 30898 := x = (y ◇ (z ◇ ((w ◇ y) ◇ y))) ◇ w
equation 30899 := x = (y ◇ (z ◇ ((w ◇ y) ◇ y))) ◇ u
equation 30900 := x = (y ◇ (z ◇ ((w ◇ y) ◇ z))) ◇ x
equation 30901 := x = (y ◇ (z ◇ ((w ◇ y) ◇ z))) ◇ y
equation 30902 := x = (y ◇ (z ◇ ((w ◇ y) ◇ z))) ◇ z
equation 30903 := x = (y ◇ (z ◇ ((w ◇ y) ◇ z))) ◇ w
equation 30904 := x = (y ◇ (z ◇ ((w ◇ y) ◇ z))) ◇ u
equation 30905 := x = (y ◇ (z ◇ ((w ◇ y) ◇ w))) ◇ x
equation 30906 := x = (y ◇ (z ◇ ((w ◇ y) ◇ w))) ◇ y
equation 30907 := x = (y ◇ (z ◇ ((w ◇ y) ◇ w))) ◇ z
equation 30908 := x = (y ◇ (z ◇ ((w ◇ y) ◇ w))) ◇ w
equation 30909 := x = (y ◇ (z ◇ ((w ◇ y) ◇ w))) ◇ u
equation 30910 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ x
equation 30911 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ y
equation 30912 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ z
equation 30913 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ w
equation 30914 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ u
equation 30915 := x = (y ◇ (z ◇ ((w ◇ y) ◇ u))) ◇ v
equation 30916 := x = (y ◇ (z ◇ ((w ◇ z) ◇ x))) ◇ x
equation 30917 := x = (y ◇ (z ◇ ((w ◇ z) ◇ x))) ◇ y
equation 30918 := x = (y ◇ (z ◇ ((w ◇ z) ◇ x))) ◇ z
equation 30919 := x = (y ◇ (z ◇ ((w ◇ z) ◇ x))) ◇ w
equation 30920 := x = (y ◇ (z ◇ ((w ◇ z) ◇ x))) ◇ u
equation 30921 := x = (y ◇ (z ◇ ((w ◇ z) ◇ y))) ◇ x
equation 30922 := x = (y ◇ (z ◇ ((w ◇ z) ◇ y))) ◇ y
equation 30923 := x = (y ◇ (z ◇ ((w ◇ z) ◇ y))) ◇ z
equation 30924 := x = (y ◇ (z ◇ ((w ◇ z) ◇ y))) ◇ w
equation 30925 := x = (y ◇ (z ◇ ((w ◇ z) ◇ y))) ◇ u
equation 30926 := x = (y ◇ (z ◇ ((w ◇ z) ◇ z))) ◇ x
equation 30927 := x = (y ◇ (z ◇ ((w ◇ z) ◇ z))) ◇ y
equation 30928 := x = (y ◇ (z ◇ ((w ◇ z) ◇ z))) ◇ z
equation 30929 := x = (y ◇ (z ◇ ((w ◇ z) ◇ z))) ◇ w
equation 30930 := x = (y ◇ (z ◇ ((w ◇ z) ◇ z))) ◇ u
equation 30931 := x = (y ◇ (z ◇ ((w ◇ z) ◇ w))) ◇ x
equation 30932 := x = (y ◇ (z ◇ ((w ◇ z) ◇ w))) ◇ y
equation 30933 := x = (y ◇ (z ◇ ((w ◇ z) ◇ w))) ◇ z
equation 30934 := x = (y ◇ (z ◇ ((w ◇ z) ◇ w))) ◇ w
equation 30935 := x = (y ◇ (z ◇ ((w ◇ z) ◇ w))) ◇ u
equation 30936 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ x
equation 30937 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ y
equation 30938 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ z
equation 30939 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ w
equation 30940 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ u
equation 30941 := x = (y ◇ (z ◇ ((w ◇ z) ◇ u))) ◇ v
equation 30942 := x = (y ◇ (z ◇ ((w ◇ w) ◇ x))) ◇ x
equation 30943 := x = (y ◇ (z ◇ ((w ◇ w) ◇ x))) ◇ y
equation 30944 := x = (y ◇ (z ◇ ((w ◇ w) ◇ x))) ◇ z
equation 30945 := x = (y ◇ (z ◇ ((w ◇ w) ◇ x))) ◇ w
equation 30946 := x = (y ◇ (z ◇ ((w ◇ w) ◇ x))) ◇ u
equation 30947 := x = (y ◇ (z ◇ ((w ◇ w) ◇ y))) ◇ x
equation 30948 := x = (y ◇ (z ◇ ((w ◇ w) ◇ y))) ◇ y
equation 30949 := x = (y ◇ (z ◇ ((w ◇ w) ◇ y))) ◇ z
equation 30950 := x = (y ◇ (z ◇ ((w ◇ w) ◇ y))) ◇ w
equation 30951 := x = (y ◇ (z ◇ ((w ◇ w) ◇ y))) ◇ u
equation 30952 := x = (y ◇ (z ◇ ((w ◇ w) ◇ z))) ◇ x
equation 30953 := x = (y ◇ (z ◇ ((w ◇ w) ◇ z))) ◇ y
equation 30954 := x = (y ◇ (z ◇ ((w ◇ w) ◇ z))) ◇ z
equation 30955 := x = (y ◇ (z ◇ ((w ◇ w) ◇ z))) ◇ w
equation 30956 := x = (y ◇ (z ◇ ((w ◇ w) ◇ z))) ◇ u
equation 30957 := x = (y ◇ (z ◇ ((w ◇ w) ◇ w))) ◇ x
equation 30958 := x = (y ◇ (z ◇ ((w ◇ w) ◇ w))) ◇ y
equation 30959 := x = (y ◇ (z ◇ ((w ◇ w) ◇ w))) ◇ z
equation 30960 := x = (y ◇ (z ◇ ((w ◇ w) ◇ w))) ◇ w
equation 30961 := x = (y ◇ (z ◇ ((w ◇ w) ◇ w))) ◇ u
equation 30962 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ x
equation 30963 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ y
equation 30964 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ z
equation 30965 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ w
equation 30966 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ u
equation 30967 := x = (y ◇ (z ◇ ((w ◇ w) ◇ u))) ◇ v
equation 30968 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ x
equation 30969 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ y
equation 30970 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ z
equation 30971 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ w
equation 30972 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ u
equation 30973 := x = (y ◇ (z ◇ ((w ◇ u) ◇ x))) ◇ v
equation 30974 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ x
equation 30975 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ y
equation 30976 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ z
equation 30977 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ w
equation 30978 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ u
equation 30979 := x = (y ◇ (z ◇ ((w ◇ u) ◇ y))) ◇ v
equation 30980 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ x
equation 30981 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ y
equation 30982 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ z
equation 30983 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ w
equation 30984 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ u
equation 30985 := x = (y ◇ (z ◇ ((w ◇ u) ◇ z))) ◇ v
equation 30986 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ x
equation 30987 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ y
equation 30988 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ z
equation 30989 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ w
equation 30990 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ u
equation 30991 := x = (y ◇ (z ◇ ((w ◇ u) ◇ w))) ◇ v
equation 30992 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ x
equation 30993 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ y
equation 30994 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ z
equation 30995 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ w
equation 30996 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ u
equation 30997 := x = (y ◇ (z ◇ ((w ◇ u) ◇ u))) ◇ v
equation 30998 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ x
equation 30999 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ y
