import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 29000-29999 -/

equation 29000 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (z ◇ z)
equation 29001 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (z ◇ w)
equation 29002 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (w ◇ x)
equation 29003 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (w ◇ y)
equation 29004 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (w ◇ z)
equation 29005 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (w ◇ w)
equation 29006 := x = (((y ◇ z) ◇ y) ◇ z) ◇ (w ◇ u)
equation 29007 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (x ◇ x)
equation 29008 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (x ◇ y)
equation 29009 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (x ◇ z)
equation 29010 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (x ◇ w)
equation 29011 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (x ◇ u)
equation 29012 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (y ◇ x)
equation 29013 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (y ◇ y)
equation 29014 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (y ◇ z)
equation 29015 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (y ◇ w)
equation 29016 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (y ◇ u)
equation 29017 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (z ◇ x)
equation 29018 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (z ◇ y)
equation 29019 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (z ◇ z)
equation 29020 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (z ◇ w)
equation 29021 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (z ◇ u)
equation 29022 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (w ◇ x)
equation 29023 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (w ◇ y)
equation 29024 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (w ◇ z)
equation 29025 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (w ◇ w)
equation 29026 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (w ◇ u)
equation 29027 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ x)
equation 29028 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ y)
equation 29029 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ z)
equation 29030 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ w)
equation 29031 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ u)
equation 29032 := x = (((y ◇ z) ◇ y) ◇ w) ◇ (u ◇ v)
equation 29033 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (x ◇ x)
equation 29034 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (x ◇ y)
equation 29035 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (x ◇ z)
equation 29036 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (x ◇ w)
equation 29037 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (y ◇ x)
equation 29038 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (y ◇ y)
equation 29039 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (y ◇ z)
equation 29040 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (y ◇ w)
equation 29041 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (z ◇ x)
equation 29042 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (z ◇ y)
equation 29043 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (z ◇ z)
equation 29044 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (z ◇ w)
equation 29045 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (w ◇ x)
equation 29046 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (w ◇ y)
equation 29047 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (w ◇ z)
equation 29048 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (w ◇ w)
equation 29049 := x = (((y ◇ z) ◇ z) ◇ x) ◇ (w ◇ u)
equation 29050 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (x ◇ x)
equation 29051 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (x ◇ y)
equation 29052 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (x ◇ z)
equation 29053 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (x ◇ w)
equation 29054 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (y ◇ x)
equation 29055 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (y ◇ y)
equation 29056 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (y ◇ z)
equation 29057 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (y ◇ w)
equation 29058 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (z ◇ x)
equation 29059 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (z ◇ y)
equation 29060 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (z ◇ z)
equation 29061 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (z ◇ w)
equation 29062 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (w ◇ x)
equation 29063 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (w ◇ y)
equation 29064 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (w ◇ z)
equation 29065 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (w ◇ w)
equation 29066 := x = (((y ◇ z) ◇ z) ◇ y) ◇ (w ◇ u)
equation 29067 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (x ◇ x)
equation 29068 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (x ◇ y)
equation 29069 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (x ◇ z)
equation 29070 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (x ◇ w)
equation 29071 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (y ◇ x)
equation 29072 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (y ◇ y)
equation 29073 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (y ◇ z)
equation 29074 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (y ◇ w)
equation 29075 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (z ◇ x)
equation 29076 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (z ◇ y)
equation 29077 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (z ◇ z)
equation 29078 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (z ◇ w)
equation 29079 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (w ◇ x)
equation 29080 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (w ◇ y)
equation 29081 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (w ◇ z)
equation 29082 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (w ◇ w)
equation 29083 := x = (((y ◇ z) ◇ z) ◇ z) ◇ (w ◇ u)
equation 29084 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (x ◇ x)
equation 29085 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (x ◇ y)
equation 29086 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (x ◇ z)
equation 29087 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (x ◇ w)
equation 29088 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (x ◇ u)
equation 29089 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (y ◇ x)
equation 29090 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (y ◇ y)
equation 29091 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (y ◇ z)
equation 29092 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (y ◇ w)
equation 29093 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (y ◇ u)
equation 29094 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (z ◇ x)
equation 29095 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (z ◇ y)
equation 29096 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (z ◇ z)
equation 29097 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (z ◇ w)
equation 29098 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (z ◇ u)
equation 29099 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (w ◇ x)
equation 29100 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (w ◇ y)
equation 29101 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (w ◇ z)
equation 29102 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (w ◇ w)
equation 29103 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (w ◇ u)
equation 29104 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ x)
equation 29105 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ y)
equation 29106 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ z)
equation 29107 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ w)
equation 29108 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ u)
equation 29109 := x = (((y ◇ z) ◇ z) ◇ w) ◇ (u ◇ v)
equation 29110 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (x ◇ x)
equation 29111 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (x ◇ y)
equation 29112 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (x ◇ z)
equation 29113 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (x ◇ w)
equation 29114 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (x ◇ u)
equation 29115 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (y ◇ x)
equation 29116 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (y ◇ y)
equation 29117 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (y ◇ z)
equation 29118 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (y ◇ w)
equation 29119 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (y ◇ u)
equation 29120 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (z ◇ x)
equation 29121 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (z ◇ y)
equation 29122 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (z ◇ z)
equation 29123 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (z ◇ w)
equation 29124 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (z ◇ u)
equation 29125 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (w ◇ x)
equation 29126 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (w ◇ y)
equation 29127 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (w ◇ z)
equation 29128 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (w ◇ w)
equation 29129 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (w ◇ u)
equation 29130 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ x)
equation 29131 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ y)
equation 29132 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ z)
equation 29133 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ w)
equation 29134 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ u)
equation 29135 := x = (((y ◇ z) ◇ w) ◇ x) ◇ (u ◇ v)
equation 29136 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (x ◇ x)
equation 29137 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (x ◇ y)
equation 29138 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (x ◇ z)
equation 29139 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (x ◇ w)
equation 29140 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (x ◇ u)
equation 29141 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (y ◇ x)
equation 29142 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (y ◇ y)
equation 29143 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (y ◇ z)
equation 29144 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (y ◇ w)
equation 29145 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (y ◇ u)
equation 29146 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (z ◇ x)
equation 29147 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (z ◇ y)
equation 29148 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (z ◇ z)
equation 29149 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (z ◇ w)
equation 29150 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (z ◇ u)
equation 29151 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (w ◇ x)
equation 29152 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (w ◇ y)
equation 29153 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (w ◇ z)
equation 29154 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (w ◇ w)
equation 29155 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (w ◇ u)
equation 29156 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ x)
equation 29157 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ y)
equation 29158 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ z)
equation 29159 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ w)
equation 29160 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ u)
equation 29161 := x = (((y ◇ z) ◇ w) ◇ y) ◇ (u ◇ v)
equation 29162 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (x ◇ x)
equation 29163 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (x ◇ y)
equation 29164 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (x ◇ z)
equation 29165 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (x ◇ w)
equation 29166 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (x ◇ u)
equation 29167 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (y ◇ x)
equation 29168 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (y ◇ y)
equation 29169 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (y ◇ z)
equation 29170 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (y ◇ w)
equation 29171 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (y ◇ u)
equation 29172 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (z ◇ x)
equation 29173 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (z ◇ y)
equation 29174 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (z ◇ z)
equation 29175 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (z ◇ w)
equation 29176 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (z ◇ u)
equation 29177 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (w ◇ x)
equation 29178 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (w ◇ y)
equation 29179 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (w ◇ z)
equation 29180 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (w ◇ w)
equation 29181 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (w ◇ u)
equation 29182 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ x)
equation 29183 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ y)
equation 29184 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ z)
equation 29185 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ w)
equation 29186 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ u)
equation 29187 := x = (((y ◇ z) ◇ w) ◇ z) ◇ (u ◇ v)
equation 29188 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (x ◇ x)
equation 29189 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (x ◇ y)
equation 29190 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (x ◇ z)
equation 29191 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (x ◇ w)
equation 29192 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (x ◇ u)
equation 29193 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (y ◇ x)
equation 29194 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (y ◇ y)
equation 29195 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (y ◇ z)
equation 29196 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (y ◇ w)
equation 29197 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (y ◇ u)
equation 29198 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (z ◇ x)
equation 29199 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (z ◇ y)
equation 29200 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (z ◇ z)
equation 29201 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (z ◇ w)
equation 29202 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (z ◇ u)
equation 29203 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (w ◇ x)
equation 29204 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (w ◇ y)
equation 29205 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (w ◇ z)
equation 29206 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (w ◇ w)
equation 29207 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (w ◇ u)
equation 29208 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ x)
equation 29209 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ y)
equation 29210 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ z)
equation 29211 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ w)
equation 29212 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ u)
equation 29213 := x = (((y ◇ z) ◇ w) ◇ w) ◇ (u ◇ v)
equation 29214 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ x)
equation 29215 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ y)
equation 29216 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ z)
equation 29217 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ w)
equation 29218 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ u)
equation 29219 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (x ◇ v)
equation 29220 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ x)
equation 29221 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ y)
equation 29222 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ z)
equation 29223 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ w)
equation 29224 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ u)
equation 29225 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (y ◇ v)
equation 29226 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ x)
equation 29227 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ y)
equation 29228 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ z)
equation 29229 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ w)
equation 29230 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ u)
equation 29231 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (z ◇ v)
equation 29232 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ x)
equation 29233 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ y)
equation 29234 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ z)
equation 29235 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ w)
equation 29236 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ u)
equation 29237 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (w ◇ v)
equation 29238 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ x)
equation 29239 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ y)
equation 29240 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ z)
equation 29241 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ w)
equation 29242 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ u)
equation 29243 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (u ◇ v)
equation 29244 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ x)
equation 29245 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ y)
equation 29246 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ z)
equation 29247 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ w)
equation 29248 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ u)
equation 29249 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ v)
equation 29250 := x = (((y ◇ z) ◇ w) ◇ u) ◇ (v ◇ r)
equation 29251 := x = (x ◇ (x ◇ (x ◇ (x ◇ x)))) ◇ x
equation 29252 := x = (x ◇ (x ◇ (x ◇ (x ◇ x)))) ◇ y
equation 29253 := x = (x ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ x
equation 29254 := x = (x ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ y
equation 29255 := x = (x ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ z
equation 29256 := x = (x ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ x
equation 29257 := x = (x ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ y
equation 29258 := x = (x ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ z
equation 29259 := x = (x ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ x
equation 29260 := x = (x ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ y
equation 29261 := x = (x ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ z
equation 29262 := x = (x ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ x
equation 29263 := x = (x ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ y
equation 29264 := x = (x ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ z
equation 29265 := x = (x ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ w
equation 29266 := x = (x ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ x
equation 29267 := x = (x ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ y
equation 29268 := x = (x ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ z
equation 29269 := x = (x ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ x
equation 29270 := x = (x ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ y
equation 29271 := x = (x ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ z
equation 29272 := x = (x ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ x
equation 29273 := x = (x ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ y
equation 29274 := x = (x ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ z
equation 29275 := x = (x ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ w
equation 29276 := x = (x ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ x
equation 29277 := x = (x ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ y
equation 29278 := x = (x ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ z
equation 29279 := x = (x ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ x
equation 29280 := x = (x ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ y
equation 29281 := x = (x ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ z
equation 29282 := x = (x ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ x
equation 29283 := x = (x ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ y
equation 29284 := x = (x ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ z
equation 29285 := x = (x ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ w
equation 29286 := x = (x ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ x
equation 29287 := x = (x ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ y
equation 29288 := x = (x ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ z
equation 29289 := x = (x ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ w
equation 29290 := x = (x ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ x
equation 29291 := x = (x ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ y
equation 29292 := x = (x ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ z
equation 29293 := x = (x ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ w
equation 29294 := x = (x ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ x
equation 29295 := x = (x ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ y
equation 29296 := x = (x ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ z
equation 29297 := x = (x ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ w
equation 29298 := x = (x ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ x
equation 29299 := x = (x ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ y
equation 29300 := x = (x ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ z
equation 29301 := x = (x ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ w
equation 29302 := x = (x ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ u
equation 29303 := x = (x ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ x
equation 29304 := x = (x ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ y
equation 29305 := x = (x ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ z
equation 29306 := x = (x ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ x
equation 29307 := x = (x ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ y
equation 29308 := x = (x ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ z
equation 29309 := x = (x ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ x
equation 29310 := x = (x ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ y
equation 29311 := x = (x ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ z
equation 29312 := x = (x ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ w
equation 29313 := x = (x ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ x
equation 29314 := x = (x ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ y
equation 29315 := x = (x ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ z
equation 29316 := x = (x ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ x
equation 29317 := x = (x ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ y
equation 29318 := x = (x ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ z
equation 29319 := x = (x ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ x
equation 29320 := x = (x ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ y
equation 29321 := x = (x ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ z
equation 29322 := x = (x ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ w
equation 29323 := x = (x ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ x
equation 29324 := x = (x ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ y
equation 29325 := x = (x ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ z
equation 29326 := x = (x ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ w
equation 29327 := x = (x ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ x
equation 29328 := x = (x ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ y
equation 29329 := x = (x ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ z
equation 29330 := x = (x ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ w
equation 29331 := x = (x ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ x
equation 29332 := x = (x ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ y
equation 29333 := x = (x ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ z
equation 29334 := x = (x ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ w
equation 29335 := x = (x ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ x
equation 29336 := x = (x ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ y
equation 29337 := x = (x ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ z
equation 29338 := x = (x ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ w
equation 29339 := x = (x ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ u
equation 29340 := x = (x ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ x
equation 29341 := x = (x ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ y
equation 29342 := x = (x ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ z
equation 29343 := x = (x ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ x
equation 29344 := x = (x ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ y
equation 29345 := x = (x ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ z
equation 29346 := x = (x ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ x
equation 29347 := x = (x ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ y
equation 29348 := x = (x ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ z
equation 29349 := x = (x ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ w
equation 29350 := x = (x ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ x
equation 29351 := x = (x ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ y
equation 29352 := x = (x ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ z
equation 29353 := x = (x ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ x
equation 29354 := x = (x ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ y
equation 29355 := x = (x ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ z
equation 29356 := x = (x ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ x
equation 29357 := x = (x ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ y
equation 29358 := x = (x ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ z
equation 29359 := x = (x ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ w
equation 29360 := x = (x ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ x
equation 29361 := x = (x ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ y
equation 29362 := x = (x ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ z
equation 29363 := x = (x ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ w
equation 29364 := x = (x ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ x
equation 29365 := x = (x ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ y
equation 29366 := x = (x ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ z
equation 29367 := x = (x ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ w
equation 29368 := x = (x ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ x
equation 29369 := x = (x ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ y
equation 29370 := x = (x ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ z
equation 29371 := x = (x ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ w
equation 29372 := x = (x ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ x
equation 29373 := x = (x ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ y
equation 29374 := x = (x ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ z
equation 29375 := x = (x ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ w
equation 29376 := x = (x ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ u
equation 29377 := x = (x ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ x
equation 29378 := x = (x ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ y
equation 29379 := x = (x ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ z
equation 29380 := x = (x ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ w
equation 29381 := x = (x ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ x
equation 29382 := x = (x ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ y
equation 29383 := x = (x ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ z
equation 29384 := x = (x ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ w
equation 29385 := x = (x ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ x
equation 29386 := x = (x ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ y
equation 29387 := x = (x ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ z
equation 29388 := x = (x ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ w
equation 29389 := x = (x ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ x
equation 29390 := x = (x ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ y
equation 29391 := x = (x ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ z
equation 29392 := x = (x ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ w
equation 29393 := x = (x ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ u
equation 29394 := x = (x ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ x
equation 29395 := x = (x ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ y
equation 29396 := x = (x ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ z
equation 29397 := x = (x ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ w
equation 29398 := x = (x ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ x
equation 29399 := x = (x ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ y
equation 29400 := x = (x ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ z
equation 29401 := x = (x ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ w
equation 29402 := x = (x ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ x
equation 29403 := x = (x ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ y
equation 29404 := x = (x ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ z
equation 29405 := x = (x ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ w
equation 29406 := x = (x ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ x
equation 29407 := x = (x ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ y
equation 29408 := x = (x ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ z
equation 29409 := x = (x ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ w
equation 29410 := x = (x ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ u
equation 29411 := x = (x ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ x
equation 29412 := x = (x ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ y
equation 29413 := x = (x ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ z
equation 29414 := x = (x ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ w
equation 29415 := x = (x ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ x
equation 29416 := x = (x ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ y
equation 29417 := x = (x ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ z
equation 29418 := x = (x ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ w
equation 29419 := x = (x ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ x
equation 29420 := x = (x ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ y
equation 29421 := x = (x ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ z
equation 29422 := x = (x ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ w
equation 29423 := x = (x ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ x
equation 29424 := x = (x ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ y
equation 29425 := x = (x ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ z
equation 29426 := x = (x ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ w
equation 29427 := x = (x ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ u
equation 29428 := x = (x ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ x
equation 29429 := x = (x ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ y
equation 29430 := x = (x ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ z
equation 29431 := x = (x ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ w
equation 29432 := x = (x ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ u
equation 29433 := x = (x ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ x
equation 29434 := x = (x ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ y
equation 29435 := x = (x ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ z
equation 29436 := x = (x ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ w
equation 29437 := x = (x ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ u
equation 29438 := x = (x ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ x
equation 29439 := x = (x ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ y
equation 29440 := x = (x ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ z
equation 29441 := x = (x ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ w
equation 29442 := x = (x ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ u
equation 29443 := x = (x ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ x
equation 29444 := x = (x ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ y
equation 29445 := x = (x ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ z
equation 29446 := x = (x ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ w
equation 29447 := x = (x ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ u
equation 29448 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ x
equation 29449 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ y
equation 29450 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ z
equation 29451 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ w
equation 29452 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ u
equation 29453 := x = (x ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ v
equation 29454 := x = (y ◇ (x ◇ (x ◇ (x ◇ x)))) ◇ x
equation 29455 := x = (y ◇ (x ◇ (x ◇ (x ◇ x)))) ◇ y
equation 29456 := x = (y ◇ (x ◇ (x ◇ (x ◇ x)))) ◇ z
equation 29457 := x = (y ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ x
equation 29458 := x = (y ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ y
equation 29459 := x = (y ◇ (x ◇ (x ◇ (x ◇ y)))) ◇ z
equation 29460 := x = (y ◇ (x ◇ (x ◇ (x ◇ z)))) ◇ x
equation 29461 := x = (y ◇ (x ◇ (x ◇ (x ◇ z)))) ◇ y
equation 29462 := x = (y ◇ (x ◇ (x ◇ (x ◇ z)))) ◇ z
equation 29463 := x = (y ◇ (x ◇ (x ◇ (x ◇ z)))) ◇ w
equation 29464 := x = (y ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ x
equation 29465 := x = (y ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ y
equation 29466 := x = (y ◇ (x ◇ (x ◇ (y ◇ x)))) ◇ z
equation 29467 := x = (y ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ x
equation 29468 := x = (y ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ y
equation 29469 := x = (y ◇ (x ◇ (x ◇ (y ◇ y)))) ◇ z
equation 29470 := x = (y ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ x
equation 29471 := x = (y ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ y
equation 29472 := x = (y ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ z
equation 29473 := x = (y ◇ (x ◇ (x ◇ (y ◇ z)))) ◇ w
equation 29474 := x = (y ◇ (x ◇ (x ◇ (z ◇ x)))) ◇ x
equation 29475 := x = (y ◇ (x ◇ (x ◇ (z ◇ x)))) ◇ y
equation 29476 := x = (y ◇ (x ◇ (x ◇ (z ◇ x)))) ◇ z
equation 29477 := x = (y ◇ (x ◇ (x ◇ (z ◇ x)))) ◇ w
equation 29478 := x = (y ◇ (x ◇ (x ◇ (z ◇ y)))) ◇ x
equation 29479 := x = (y ◇ (x ◇ (x ◇ (z ◇ y)))) ◇ y
equation 29480 := x = (y ◇ (x ◇ (x ◇ (z ◇ y)))) ◇ z
equation 29481 := x = (y ◇ (x ◇ (x ◇ (z ◇ y)))) ◇ w
equation 29482 := x = (y ◇ (x ◇ (x ◇ (z ◇ z)))) ◇ x
equation 29483 := x = (y ◇ (x ◇ (x ◇ (z ◇ z)))) ◇ y
equation 29484 := x = (y ◇ (x ◇ (x ◇ (z ◇ z)))) ◇ z
equation 29485 := x = (y ◇ (x ◇ (x ◇ (z ◇ z)))) ◇ w
equation 29486 := x = (y ◇ (x ◇ (x ◇ (z ◇ w)))) ◇ x
equation 29487 := x = (y ◇ (x ◇ (x ◇ (z ◇ w)))) ◇ y
equation 29488 := x = (y ◇ (x ◇ (x ◇ (z ◇ w)))) ◇ z
equation 29489 := x = (y ◇ (x ◇ (x ◇ (z ◇ w)))) ◇ w
equation 29490 := x = (y ◇ (x ◇ (x ◇ (z ◇ w)))) ◇ u
equation 29491 := x = (y ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ x
equation 29492 := x = (y ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ y
equation 29493 := x = (y ◇ (x ◇ (y ◇ (x ◇ x)))) ◇ z
equation 29494 := x = (y ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ x
equation 29495 := x = (y ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ y
equation 29496 := x = (y ◇ (x ◇ (y ◇ (x ◇ y)))) ◇ z
equation 29497 := x = (y ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ x
equation 29498 := x = (y ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ y
equation 29499 := x = (y ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ z
equation 29500 := x = (y ◇ (x ◇ (y ◇ (x ◇ z)))) ◇ w
equation 29501 := x = (y ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ x
equation 29502 := x = (y ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ y
equation 29503 := x = (y ◇ (x ◇ (y ◇ (y ◇ x)))) ◇ z
equation 29504 := x = (y ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ x
equation 29505 := x = (y ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ y
equation 29506 := x = (y ◇ (x ◇ (y ◇ (y ◇ y)))) ◇ z
equation 29507 := x = (y ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ x
equation 29508 := x = (y ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ y
equation 29509 := x = (y ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ z
equation 29510 := x = (y ◇ (x ◇ (y ◇ (y ◇ z)))) ◇ w
equation 29511 := x = (y ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ x
equation 29512 := x = (y ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ y
equation 29513 := x = (y ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ z
equation 29514 := x = (y ◇ (x ◇ (y ◇ (z ◇ x)))) ◇ w
equation 29515 := x = (y ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ x
equation 29516 := x = (y ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ y
equation 29517 := x = (y ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ z
equation 29518 := x = (y ◇ (x ◇ (y ◇ (z ◇ y)))) ◇ w
equation 29519 := x = (y ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ x
equation 29520 := x = (y ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ y
equation 29521 := x = (y ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ z
equation 29522 := x = (y ◇ (x ◇ (y ◇ (z ◇ z)))) ◇ w
equation 29523 := x = (y ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ x
equation 29524 := x = (y ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ y
equation 29525 := x = (y ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ z
equation 29526 := x = (y ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ w
equation 29527 := x = (y ◇ (x ◇ (y ◇ (z ◇ w)))) ◇ u
equation 29528 := x = (y ◇ (x ◇ (z ◇ (x ◇ x)))) ◇ x
equation 29529 := x = (y ◇ (x ◇ (z ◇ (x ◇ x)))) ◇ y
equation 29530 := x = (y ◇ (x ◇ (z ◇ (x ◇ x)))) ◇ z
equation 29531 := x = (y ◇ (x ◇ (z ◇ (x ◇ x)))) ◇ w
equation 29532 := x = (y ◇ (x ◇ (z ◇ (x ◇ y)))) ◇ x
equation 29533 := x = (y ◇ (x ◇ (z ◇ (x ◇ y)))) ◇ y
equation 29534 := x = (y ◇ (x ◇ (z ◇ (x ◇ y)))) ◇ z
equation 29535 := x = (y ◇ (x ◇ (z ◇ (x ◇ y)))) ◇ w
equation 29536 := x = (y ◇ (x ◇ (z ◇ (x ◇ z)))) ◇ x
equation 29537 := x = (y ◇ (x ◇ (z ◇ (x ◇ z)))) ◇ y
equation 29538 := x = (y ◇ (x ◇ (z ◇ (x ◇ z)))) ◇ z
equation 29539 := x = (y ◇ (x ◇ (z ◇ (x ◇ z)))) ◇ w
equation 29540 := x = (y ◇ (x ◇ (z ◇ (x ◇ w)))) ◇ x
equation 29541 := x = (y ◇ (x ◇ (z ◇ (x ◇ w)))) ◇ y
equation 29542 := x = (y ◇ (x ◇ (z ◇ (x ◇ w)))) ◇ z
equation 29543 := x = (y ◇ (x ◇ (z ◇ (x ◇ w)))) ◇ w
equation 29544 := x = (y ◇ (x ◇ (z ◇ (x ◇ w)))) ◇ u
equation 29545 := x = (y ◇ (x ◇ (z ◇ (y ◇ x)))) ◇ x
equation 29546 := x = (y ◇ (x ◇ (z ◇ (y ◇ x)))) ◇ y
equation 29547 := x = (y ◇ (x ◇ (z ◇ (y ◇ x)))) ◇ z
equation 29548 := x = (y ◇ (x ◇ (z ◇ (y ◇ x)))) ◇ w
equation 29549 := x = (y ◇ (x ◇ (z ◇ (y ◇ y)))) ◇ x
equation 29550 := x = (y ◇ (x ◇ (z ◇ (y ◇ y)))) ◇ y
equation 29551 := x = (y ◇ (x ◇ (z ◇ (y ◇ y)))) ◇ z
equation 29552 := x = (y ◇ (x ◇ (z ◇ (y ◇ y)))) ◇ w
equation 29553 := x = (y ◇ (x ◇ (z ◇ (y ◇ z)))) ◇ x
equation 29554 := x = (y ◇ (x ◇ (z ◇ (y ◇ z)))) ◇ y
equation 29555 := x = (y ◇ (x ◇ (z ◇ (y ◇ z)))) ◇ z
equation 29556 := x = (y ◇ (x ◇ (z ◇ (y ◇ z)))) ◇ w
equation 29557 := x = (y ◇ (x ◇ (z ◇ (y ◇ w)))) ◇ x
equation 29558 := x = (y ◇ (x ◇ (z ◇ (y ◇ w)))) ◇ y
equation 29559 := x = (y ◇ (x ◇ (z ◇ (y ◇ w)))) ◇ z
equation 29560 := x = (y ◇ (x ◇ (z ◇ (y ◇ w)))) ◇ w
equation 29561 := x = (y ◇ (x ◇ (z ◇ (y ◇ w)))) ◇ u
equation 29562 := x = (y ◇ (x ◇ (z ◇ (z ◇ x)))) ◇ x
equation 29563 := x = (y ◇ (x ◇ (z ◇ (z ◇ x)))) ◇ y
equation 29564 := x = (y ◇ (x ◇ (z ◇ (z ◇ x)))) ◇ z
equation 29565 := x = (y ◇ (x ◇ (z ◇ (z ◇ x)))) ◇ w
equation 29566 := x = (y ◇ (x ◇ (z ◇ (z ◇ y)))) ◇ x
equation 29567 := x = (y ◇ (x ◇ (z ◇ (z ◇ y)))) ◇ y
equation 29568 := x = (y ◇ (x ◇ (z ◇ (z ◇ y)))) ◇ z
equation 29569 := x = (y ◇ (x ◇ (z ◇ (z ◇ y)))) ◇ w
equation 29570 := x = (y ◇ (x ◇ (z ◇ (z ◇ z)))) ◇ x
equation 29571 := x = (y ◇ (x ◇ (z ◇ (z ◇ z)))) ◇ y
equation 29572 := x = (y ◇ (x ◇ (z ◇ (z ◇ z)))) ◇ z
equation 29573 := x = (y ◇ (x ◇ (z ◇ (z ◇ z)))) ◇ w
equation 29574 := x = (y ◇ (x ◇ (z ◇ (z ◇ w)))) ◇ x
equation 29575 := x = (y ◇ (x ◇ (z ◇ (z ◇ w)))) ◇ y
equation 29576 := x = (y ◇ (x ◇ (z ◇ (z ◇ w)))) ◇ z
equation 29577 := x = (y ◇ (x ◇ (z ◇ (z ◇ w)))) ◇ w
equation 29578 := x = (y ◇ (x ◇ (z ◇ (z ◇ w)))) ◇ u
equation 29579 := x = (y ◇ (x ◇ (z ◇ (w ◇ x)))) ◇ x
equation 29580 := x = (y ◇ (x ◇ (z ◇ (w ◇ x)))) ◇ y
equation 29581 := x = (y ◇ (x ◇ (z ◇ (w ◇ x)))) ◇ z
equation 29582 := x = (y ◇ (x ◇ (z ◇ (w ◇ x)))) ◇ w
equation 29583 := x = (y ◇ (x ◇ (z ◇ (w ◇ x)))) ◇ u
equation 29584 := x = (y ◇ (x ◇ (z ◇ (w ◇ y)))) ◇ x
equation 29585 := x = (y ◇ (x ◇ (z ◇ (w ◇ y)))) ◇ y
equation 29586 := x = (y ◇ (x ◇ (z ◇ (w ◇ y)))) ◇ z
equation 29587 := x = (y ◇ (x ◇ (z ◇ (w ◇ y)))) ◇ w
equation 29588 := x = (y ◇ (x ◇ (z ◇ (w ◇ y)))) ◇ u
equation 29589 := x = (y ◇ (x ◇ (z ◇ (w ◇ z)))) ◇ x
equation 29590 := x = (y ◇ (x ◇ (z ◇ (w ◇ z)))) ◇ y
equation 29591 := x = (y ◇ (x ◇ (z ◇ (w ◇ z)))) ◇ z
equation 29592 := x = (y ◇ (x ◇ (z ◇ (w ◇ z)))) ◇ w
equation 29593 := x = (y ◇ (x ◇ (z ◇ (w ◇ z)))) ◇ u
equation 29594 := x = (y ◇ (x ◇ (z ◇ (w ◇ w)))) ◇ x
equation 29595 := x = (y ◇ (x ◇ (z ◇ (w ◇ w)))) ◇ y
equation 29596 := x = (y ◇ (x ◇ (z ◇ (w ◇ w)))) ◇ z
equation 29597 := x = (y ◇ (x ◇ (z ◇ (w ◇ w)))) ◇ w
equation 29598 := x = (y ◇ (x ◇ (z ◇ (w ◇ w)))) ◇ u
equation 29599 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ x
equation 29600 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ y
equation 29601 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ z
equation 29602 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ w
equation 29603 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ u
equation 29604 := x = (y ◇ (x ◇ (z ◇ (w ◇ u)))) ◇ v
equation 29605 := x = (y ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ x
equation 29606 := x = (y ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ y
equation 29607 := x = (y ◇ (y ◇ (x ◇ (x ◇ x)))) ◇ z
equation 29608 := x = (y ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ x
equation 29609 := x = (y ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ y
equation 29610 := x = (y ◇ (y ◇ (x ◇ (x ◇ y)))) ◇ z
equation 29611 := x = (y ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ x
equation 29612 := x = (y ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ y
equation 29613 := x = (y ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ z
equation 29614 := x = (y ◇ (y ◇ (x ◇ (x ◇ z)))) ◇ w
equation 29615 := x = (y ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ x
equation 29616 := x = (y ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ y
equation 29617 := x = (y ◇ (y ◇ (x ◇ (y ◇ x)))) ◇ z
equation 29618 := x = (y ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ x
equation 29619 := x = (y ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ y
equation 29620 := x = (y ◇ (y ◇ (x ◇ (y ◇ y)))) ◇ z
equation 29621 := x = (y ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ x
equation 29622 := x = (y ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ y
equation 29623 := x = (y ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ z
equation 29624 := x = (y ◇ (y ◇ (x ◇ (y ◇ z)))) ◇ w
equation 29625 := x = (y ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ x
equation 29626 := x = (y ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ y
equation 29627 := x = (y ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ z
equation 29628 := x = (y ◇ (y ◇ (x ◇ (z ◇ x)))) ◇ w
equation 29629 := x = (y ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ x
equation 29630 := x = (y ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ y
equation 29631 := x = (y ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ z
equation 29632 := x = (y ◇ (y ◇ (x ◇ (z ◇ y)))) ◇ w
equation 29633 := x = (y ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ x
equation 29634 := x = (y ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ y
equation 29635 := x = (y ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ z
equation 29636 := x = (y ◇ (y ◇ (x ◇ (z ◇ z)))) ◇ w
equation 29637 := x = (y ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ x
equation 29638 := x = (y ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ y
equation 29639 := x = (y ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ z
equation 29640 := x = (y ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ w
equation 29641 := x = (y ◇ (y ◇ (x ◇ (z ◇ w)))) ◇ u
equation 29642 := x = (y ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ x
equation 29643 := x = (y ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ y
equation 29644 := x = (y ◇ (y ◇ (y ◇ (x ◇ x)))) ◇ z
equation 29645 := x = (y ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ x
equation 29646 := x = (y ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ y
equation 29647 := x = (y ◇ (y ◇ (y ◇ (x ◇ y)))) ◇ z
equation 29648 := x = (y ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ x
equation 29649 := x = (y ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ y
equation 29650 := x = (y ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ z
equation 29651 := x = (y ◇ (y ◇ (y ◇ (x ◇ z)))) ◇ w
equation 29652 := x = (y ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ x
equation 29653 := x = (y ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ y
equation 29654 := x = (y ◇ (y ◇ (y ◇ (y ◇ x)))) ◇ z
equation 29655 := x = (y ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ x
equation 29656 := x = (y ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ y
equation 29657 := x = (y ◇ (y ◇ (y ◇ (y ◇ y)))) ◇ z
equation 29658 := x = (y ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ x
equation 29659 := x = (y ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ y
equation 29660 := x = (y ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ z
equation 29661 := x = (y ◇ (y ◇ (y ◇ (y ◇ z)))) ◇ w
equation 29662 := x = (y ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ x
equation 29663 := x = (y ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ y
equation 29664 := x = (y ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ z
equation 29665 := x = (y ◇ (y ◇ (y ◇ (z ◇ x)))) ◇ w
equation 29666 := x = (y ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ x
equation 29667 := x = (y ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ y
equation 29668 := x = (y ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ z
equation 29669 := x = (y ◇ (y ◇ (y ◇ (z ◇ y)))) ◇ w
equation 29670 := x = (y ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ x
equation 29671 := x = (y ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ y
equation 29672 := x = (y ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ z
equation 29673 := x = (y ◇ (y ◇ (y ◇ (z ◇ z)))) ◇ w
equation 29674 := x = (y ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ x
equation 29675 := x = (y ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ y
equation 29676 := x = (y ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ z
equation 29677 := x = (y ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ w
equation 29678 := x = (y ◇ (y ◇ (y ◇ (z ◇ w)))) ◇ u
equation 29679 := x = (y ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ x
equation 29680 := x = (y ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ y
equation 29681 := x = (y ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ z
equation 29682 := x = (y ◇ (y ◇ (z ◇ (x ◇ x)))) ◇ w
equation 29683 := x = (y ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ x
equation 29684 := x = (y ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ y
equation 29685 := x = (y ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ z
equation 29686 := x = (y ◇ (y ◇ (z ◇ (x ◇ y)))) ◇ w
equation 29687 := x = (y ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ x
equation 29688 := x = (y ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ y
equation 29689 := x = (y ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ z
equation 29690 := x = (y ◇ (y ◇ (z ◇ (x ◇ z)))) ◇ w
equation 29691 := x = (y ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ x
equation 29692 := x = (y ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ y
equation 29693 := x = (y ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ z
equation 29694 := x = (y ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ w
equation 29695 := x = (y ◇ (y ◇ (z ◇ (x ◇ w)))) ◇ u
equation 29696 := x = (y ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ x
equation 29697 := x = (y ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ y
equation 29698 := x = (y ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ z
equation 29699 := x = (y ◇ (y ◇ (z ◇ (y ◇ x)))) ◇ w
equation 29700 := x = (y ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ x
equation 29701 := x = (y ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ y
equation 29702 := x = (y ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ z
equation 29703 := x = (y ◇ (y ◇ (z ◇ (y ◇ y)))) ◇ w
equation 29704 := x = (y ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ x
equation 29705 := x = (y ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ y
equation 29706 := x = (y ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ z
equation 29707 := x = (y ◇ (y ◇ (z ◇ (y ◇ z)))) ◇ w
equation 29708 := x = (y ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ x
equation 29709 := x = (y ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ y
equation 29710 := x = (y ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ z
equation 29711 := x = (y ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ w
equation 29712 := x = (y ◇ (y ◇ (z ◇ (y ◇ w)))) ◇ u
equation 29713 := x = (y ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ x
equation 29714 := x = (y ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ y
equation 29715 := x = (y ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ z
equation 29716 := x = (y ◇ (y ◇ (z ◇ (z ◇ x)))) ◇ w
equation 29717 := x = (y ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ x
equation 29718 := x = (y ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ y
equation 29719 := x = (y ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ z
equation 29720 := x = (y ◇ (y ◇ (z ◇ (z ◇ y)))) ◇ w
equation 29721 := x = (y ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ x
equation 29722 := x = (y ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ y
equation 29723 := x = (y ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ z
equation 29724 := x = (y ◇ (y ◇ (z ◇ (z ◇ z)))) ◇ w
equation 29725 := x = (y ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ x
equation 29726 := x = (y ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ y
equation 29727 := x = (y ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ z
equation 29728 := x = (y ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ w
equation 29729 := x = (y ◇ (y ◇ (z ◇ (z ◇ w)))) ◇ u
equation 29730 := x = (y ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ x
equation 29731 := x = (y ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ y
equation 29732 := x = (y ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ z
equation 29733 := x = (y ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ w
equation 29734 := x = (y ◇ (y ◇ (z ◇ (w ◇ x)))) ◇ u
equation 29735 := x = (y ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ x
equation 29736 := x = (y ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ y
equation 29737 := x = (y ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ z
equation 29738 := x = (y ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ w
equation 29739 := x = (y ◇ (y ◇ (z ◇ (w ◇ y)))) ◇ u
equation 29740 := x = (y ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ x
equation 29741 := x = (y ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ y
equation 29742 := x = (y ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ z
equation 29743 := x = (y ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ w
equation 29744 := x = (y ◇ (y ◇ (z ◇ (w ◇ z)))) ◇ u
equation 29745 := x = (y ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ x
equation 29746 := x = (y ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ y
equation 29747 := x = (y ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ z
equation 29748 := x = (y ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ w
equation 29749 := x = (y ◇ (y ◇ (z ◇ (w ◇ w)))) ◇ u
equation 29750 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ x
equation 29751 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ y
equation 29752 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ z
equation 29753 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ w
equation 29754 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ u
equation 29755 := x = (y ◇ (y ◇ (z ◇ (w ◇ u)))) ◇ v
equation 29756 := x = (y ◇ (z ◇ (x ◇ (x ◇ x)))) ◇ x
equation 29757 := x = (y ◇ (z ◇ (x ◇ (x ◇ x)))) ◇ y
equation 29758 := x = (y ◇ (z ◇ (x ◇ (x ◇ x)))) ◇ z
equation 29759 := x = (y ◇ (z ◇ (x ◇ (x ◇ x)))) ◇ w
equation 29760 := x = (y ◇ (z ◇ (x ◇ (x ◇ y)))) ◇ x
equation 29761 := x = (y ◇ (z ◇ (x ◇ (x ◇ y)))) ◇ y
equation 29762 := x = (y ◇ (z ◇ (x ◇ (x ◇ y)))) ◇ z
equation 29763 := x = (y ◇ (z ◇ (x ◇ (x ◇ y)))) ◇ w
equation 29764 := x = (y ◇ (z ◇ (x ◇ (x ◇ z)))) ◇ x
equation 29765 := x = (y ◇ (z ◇ (x ◇ (x ◇ z)))) ◇ y
equation 29766 := x = (y ◇ (z ◇ (x ◇ (x ◇ z)))) ◇ z
equation 29767 := x = (y ◇ (z ◇ (x ◇ (x ◇ z)))) ◇ w
equation 29768 := x = (y ◇ (z ◇ (x ◇ (x ◇ w)))) ◇ x
equation 29769 := x = (y ◇ (z ◇ (x ◇ (x ◇ w)))) ◇ y
equation 29770 := x = (y ◇ (z ◇ (x ◇ (x ◇ w)))) ◇ z
equation 29771 := x = (y ◇ (z ◇ (x ◇ (x ◇ w)))) ◇ w
equation 29772 := x = (y ◇ (z ◇ (x ◇ (x ◇ w)))) ◇ u
equation 29773 := x = (y ◇ (z ◇ (x ◇ (y ◇ x)))) ◇ x
equation 29774 := x = (y ◇ (z ◇ (x ◇ (y ◇ x)))) ◇ y
equation 29775 := x = (y ◇ (z ◇ (x ◇ (y ◇ x)))) ◇ z
equation 29776 := x = (y ◇ (z ◇ (x ◇ (y ◇ x)))) ◇ w
equation 29777 := x = (y ◇ (z ◇ (x ◇ (y ◇ y)))) ◇ x
equation 29778 := x = (y ◇ (z ◇ (x ◇ (y ◇ y)))) ◇ y
equation 29779 := x = (y ◇ (z ◇ (x ◇ (y ◇ y)))) ◇ z
equation 29780 := x = (y ◇ (z ◇ (x ◇ (y ◇ y)))) ◇ w
equation 29781 := x = (y ◇ (z ◇ (x ◇ (y ◇ z)))) ◇ x
equation 29782 := x = (y ◇ (z ◇ (x ◇ (y ◇ z)))) ◇ y
equation 29783 := x = (y ◇ (z ◇ (x ◇ (y ◇ z)))) ◇ z
equation 29784 := x = (y ◇ (z ◇ (x ◇ (y ◇ z)))) ◇ w
equation 29785 := x = (y ◇ (z ◇ (x ◇ (y ◇ w)))) ◇ x
equation 29786 := x = (y ◇ (z ◇ (x ◇ (y ◇ w)))) ◇ y
equation 29787 := x = (y ◇ (z ◇ (x ◇ (y ◇ w)))) ◇ z
equation 29788 := x = (y ◇ (z ◇ (x ◇ (y ◇ w)))) ◇ w
equation 29789 := x = (y ◇ (z ◇ (x ◇ (y ◇ w)))) ◇ u
equation 29790 := x = (y ◇ (z ◇ (x ◇ (z ◇ x)))) ◇ x
equation 29791 := x = (y ◇ (z ◇ (x ◇ (z ◇ x)))) ◇ y
equation 29792 := x = (y ◇ (z ◇ (x ◇ (z ◇ x)))) ◇ z
equation 29793 := x = (y ◇ (z ◇ (x ◇ (z ◇ x)))) ◇ w
equation 29794 := x = (y ◇ (z ◇ (x ◇ (z ◇ y)))) ◇ x
equation 29795 := x = (y ◇ (z ◇ (x ◇ (z ◇ y)))) ◇ y
equation 29796 := x = (y ◇ (z ◇ (x ◇ (z ◇ y)))) ◇ z
equation 29797 := x = (y ◇ (z ◇ (x ◇ (z ◇ y)))) ◇ w
equation 29798 := x = (y ◇ (z ◇ (x ◇ (z ◇ z)))) ◇ x
equation 29799 := x = (y ◇ (z ◇ (x ◇ (z ◇ z)))) ◇ y
equation 29800 := x = (y ◇ (z ◇ (x ◇ (z ◇ z)))) ◇ z
equation 29801 := x = (y ◇ (z ◇ (x ◇ (z ◇ z)))) ◇ w
equation 29802 := x = (y ◇ (z ◇ (x ◇ (z ◇ w)))) ◇ x
equation 29803 := x = (y ◇ (z ◇ (x ◇ (z ◇ w)))) ◇ y
equation 29804 := x = (y ◇ (z ◇ (x ◇ (z ◇ w)))) ◇ z
equation 29805 := x = (y ◇ (z ◇ (x ◇ (z ◇ w)))) ◇ w
equation 29806 := x = (y ◇ (z ◇ (x ◇ (z ◇ w)))) ◇ u
equation 29807 := x = (y ◇ (z ◇ (x ◇ (w ◇ x)))) ◇ x
equation 29808 := x = (y ◇ (z ◇ (x ◇ (w ◇ x)))) ◇ y
equation 29809 := x = (y ◇ (z ◇ (x ◇ (w ◇ x)))) ◇ z
equation 29810 := x = (y ◇ (z ◇ (x ◇ (w ◇ x)))) ◇ w
equation 29811 := x = (y ◇ (z ◇ (x ◇ (w ◇ x)))) ◇ u
equation 29812 := x = (y ◇ (z ◇ (x ◇ (w ◇ y)))) ◇ x
equation 29813 := x = (y ◇ (z ◇ (x ◇ (w ◇ y)))) ◇ y
equation 29814 := x = (y ◇ (z ◇ (x ◇ (w ◇ y)))) ◇ z
equation 29815 := x = (y ◇ (z ◇ (x ◇ (w ◇ y)))) ◇ w
equation 29816 := x = (y ◇ (z ◇ (x ◇ (w ◇ y)))) ◇ u
equation 29817 := x = (y ◇ (z ◇ (x ◇ (w ◇ z)))) ◇ x
equation 29818 := x = (y ◇ (z ◇ (x ◇ (w ◇ z)))) ◇ y
equation 29819 := x = (y ◇ (z ◇ (x ◇ (w ◇ z)))) ◇ z
equation 29820 := x = (y ◇ (z ◇ (x ◇ (w ◇ z)))) ◇ w
equation 29821 := x = (y ◇ (z ◇ (x ◇ (w ◇ z)))) ◇ u
equation 29822 := x = (y ◇ (z ◇ (x ◇ (w ◇ w)))) ◇ x
equation 29823 := x = (y ◇ (z ◇ (x ◇ (w ◇ w)))) ◇ y
equation 29824 := x = (y ◇ (z ◇ (x ◇ (w ◇ w)))) ◇ z
equation 29825 := x = (y ◇ (z ◇ (x ◇ (w ◇ w)))) ◇ w
equation 29826 := x = (y ◇ (z ◇ (x ◇ (w ◇ w)))) ◇ u
equation 29827 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ x
equation 29828 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ y
equation 29829 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ z
equation 29830 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ w
equation 29831 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ u
equation 29832 := x = (y ◇ (z ◇ (x ◇ (w ◇ u)))) ◇ v
equation 29833 := x = (y ◇ (z ◇ (y ◇ (x ◇ x)))) ◇ x
equation 29834 := x = (y ◇ (z ◇ (y ◇ (x ◇ x)))) ◇ y
equation 29835 := x = (y ◇ (z ◇ (y ◇ (x ◇ x)))) ◇ z
equation 29836 := x = (y ◇ (z ◇ (y ◇ (x ◇ x)))) ◇ w
equation 29837 := x = (y ◇ (z ◇ (y ◇ (x ◇ y)))) ◇ x
equation 29838 := x = (y ◇ (z ◇ (y ◇ (x ◇ y)))) ◇ y
equation 29839 := x = (y ◇ (z ◇ (y ◇ (x ◇ y)))) ◇ z
equation 29840 := x = (y ◇ (z ◇ (y ◇ (x ◇ y)))) ◇ w
equation 29841 := x = (y ◇ (z ◇ (y ◇ (x ◇ z)))) ◇ x
equation 29842 := x = (y ◇ (z ◇ (y ◇ (x ◇ z)))) ◇ y
equation 29843 := x = (y ◇ (z ◇ (y ◇ (x ◇ z)))) ◇ z
equation 29844 := x = (y ◇ (z ◇ (y ◇ (x ◇ z)))) ◇ w
equation 29845 := x = (y ◇ (z ◇ (y ◇ (x ◇ w)))) ◇ x
equation 29846 := x = (y ◇ (z ◇ (y ◇ (x ◇ w)))) ◇ y
equation 29847 := x = (y ◇ (z ◇ (y ◇ (x ◇ w)))) ◇ z
equation 29848 := x = (y ◇ (z ◇ (y ◇ (x ◇ w)))) ◇ w
equation 29849 := x = (y ◇ (z ◇ (y ◇ (x ◇ w)))) ◇ u
equation 29850 := x = (y ◇ (z ◇ (y ◇ (y ◇ x)))) ◇ x
equation 29851 := x = (y ◇ (z ◇ (y ◇ (y ◇ x)))) ◇ y
equation 29852 := x = (y ◇ (z ◇ (y ◇ (y ◇ x)))) ◇ z
equation 29853 := x = (y ◇ (z ◇ (y ◇ (y ◇ x)))) ◇ w
equation 29854 := x = (y ◇ (z ◇ (y ◇ (y ◇ y)))) ◇ x
equation 29855 := x = (y ◇ (z ◇ (y ◇ (y ◇ y)))) ◇ y
equation 29856 := x = (y ◇ (z ◇ (y ◇ (y ◇ y)))) ◇ z
equation 29857 := x = (y ◇ (z ◇ (y ◇ (y ◇ y)))) ◇ w
equation 29858 := x = (y ◇ (z ◇ (y ◇ (y ◇ z)))) ◇ x
equation 29859 := x = (y ◇ (z ◇ (y ◇ (y ◇ z)))) ◇ y
equation 29860 := x = (y ◇ (z ◇ (y ◇ (y ◇ z)))) ◇ z
equation 29861 := x = (y ◇ (z ◇ (y ◇ (y ◇ z)))) ◇ w
equation 29862 := x = (y ◇ (z ◇ (y ◇ (y ◇ w)))) ◇ x
equation 29863 := x = (y ◇ (z ◇ (y ◇ (y ◇ w)))) ◇ y
equation 29864 := x = (y ◇ (z ◇ (y ◇ (y ◇ w)))) ◇ z
equation 29865 := x = (y ◇ (z ◇ (y ◇ (y ◇ w)))) ◇ w
equation 29866 := x = (y ◇ (z ◇ (y ◇ (y ◇ w)))) ◇ u
equation 29867 := x = (y ◇ (z ◇ (y ◇ (z ◇ x)))) ◇ x
equation 29868 := x = (y ◇ (z ◇ (y ◇ (z ◇ x)))) ◇ y
equation 29869 := x = (y ◇ (z ◇ (y ◇ (z ◇ x)))) ◇ z
equation 29870 := x = (y ◇ (z ◇ (y ◇ (z ◇ x)))) ◇ w
equation 29871 := x = (y ◇ (z ◇ (y ◇ (z ◇ y)))) ◇ x
equation 29872 := x = (y ◇ (z ◇ (y ◇ (z ◇ y)))) ◇ y
equation 29873 := x = (y ◇ (z ◇ (y ◇ (z ◇ y)))) ◇ z
equation 29874 := x = (y ◇ (z ◇ (y ◇ (z ◇ y)))) ◇ w
equation 29875 := x = (y ◇ (z ◇ (y ◇ (z ◇ z)))) ◇ x
equation 29876 := x = (y ◇ (z ◇ (y ◇ (z ◇ z)))) ◇ y
equation 29877 := x = (y ◇ (z ◇ (y ◇ (z ◇ z)))) ◇ z
equation 29878 := x = (y ◇ (z ◇ (y ◇ (z ◇ z)))) ◇ w
equation 29879 := x = (y ◇ (z ◇ (y ◇ (z ◇ w)))) ◇ x
equation 29880 := x = (y ◇ (z ◇ (y ◇ (z ◇ w)))) ◇ y
equation 29881 := x = (y ◇ (z ◇ (y ◇ (z ◇ w)))) ◇ z
equation 29882 := x = (y ◇ (z ◇ (y ◇ (z ◇ w)))) ◇ w
equation 29883 := x = (y ◇ (z ◇ (y ◇ (z ◇ w)))) ◇ u
equation 29884 := x = (y ◇ (z ◇ (y ◇ (w ◇ x)))) ◇ x
equation 29885 := x = (y ◇ (z ◇ (y ◇ (w ◇ x)))) ◇ y
equation 29886 := x = (y ◇ (z ◇ (y ◇ (w ◇ x)))) ◇ z
equation 29887 := x = (y ◇ (z ◇ (y ◇ (w ◇ x)))) ◇ w
equation 29888 := x = (y ◇ (z ◇ (y ◇ (w ◇ x)))) ◇ u
equation 29889 := x = (y ◇ (z ◇ (y ◇ (w ◇ y)))) ◇ x
equation 29890 := x = (y ◇ (z ◇ (y ◇ (w ◇ y)))) ◇ y
equation 29891 := x = (y ◇ (z ◇ (y ◇ (w ◇ y)))) ◇ z
equation 29892 := x = (y ◇ (z ◇ (y ◇ (w ◇ y)))) ◇ w
equation 29893 := x = (y ◇ (z ◇ (y ◇ (w ◇ y)))) ◇ u
equation 29894 := x = (y ◇ (z ◇ (y ◇ (w ◇ z)))) ◇ x
equation 29895 := x = (y ◇ (z ◇ (y ◇ (w ◇ z)))) ◇ y
equation 29896 := x = (y ◇ (z ◇ (y ◇ (w ◇ z)))) ◇ z
equation 29897 := x = (y ◇ (z ◇ (y ◇ (w ◇ z)))) ◇ w
equation 29898 := x = (y ◇ (z ◇ (y ◇ (w ◇ z)))) ◇ u
equation 29899 := x = (y ◇ (z ◇ (y ◇ (w ◇ w)))) ◇ x
equation 29900 := x = (y ◇ (z ◇ (y ◇ (w ◇ w)))) ◇ y
equation 29901 := x = (y ◇ (z ◇ (y ◇ (w ◇ w)))) ◇ z
equation 29902 := x = (y ◇ (z ◇ (y ◇ (w ◇ w)))) ◇ w
equation 29903 := x = (y ◇ (z ◇ (y ◇ (w ◇ w)))) ◇ u
equation 29904 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ x
equation 29905 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ y
equation 29906 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ z
equation 29907 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ w
equation 29908 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ u
equation 29909 := x = (y ◇ (z ◇ (y ◇ (w ◇ u)))) ◇ v
equation 29910 := x = (y ◇ (z ◇ (z ◇ (x ◇ x)))) ◇ x
equation 29911 := x = (y ◇ (z ◇ (z ◇ (x ◇ x)))) ◇ y
equation 29912 := x = (y ◇ (z ◇ (z ◇ (x ◇ x)))) ◇ z
equation 29913 := x = (y ◇ (z ◇ (z ◇ (x ◇ x)))) ◇ w
equation 29914 := x = (y ◇ (z ◇ (z ◇ (x ◇ y)))) ◇ x
equation 29915 := x = (y ◇ (z ◇ (z ◇ (x ◇ y)))) ◇ y
equation 29916 := x = (y ◇ (z ◇ (z ◇ (x ◇ y)))) ◇ z
equation 29917 := x = (y ◇ (z ◇ (z ◇ (x ◇ y)))) ◇ w
equation 29918 := x = (y ◇ (z ◇ (z ◇ (x ◇ z)))) ◇ x
equation 29919 := x = (y ◇ (z ◇ (z ◇ (x ◇ z)))) ◇ y
equation 29920 := x = (y ◇ (z ◇ (z ◇ (x ◇ z)))) ◇ z
equation 29921 := x = (y ◇ (z ◇ (z ◇ (x ◇ z)))) ◇ w
equation 29922 := x = (y ◇ (z ◇ (z ◇ (x ◇ w)))) ◇ x
equation 29923 := x = (y ◇ (z ◇ (z ◇ (x ◇ w)))) ◇ y
equation 29924 := x = (y ◇ (z ◇ (z ◇ (x ◇ w)))) ◇ z
equation 29925 := x = (y ◇ (z ◇ (z ◇ (x ◇ w)))) ◇ w
equation 29926 := x = (y ◇ (z ◇ (z ◇ (x ◇ w)))) ◇ u
equation 29927 := x = (y ◇ (z ◇ (z ◇ (y ◇ x)))) ◇ x
equation 29928 := x = (y ◇ (z ◇ (z ◇ (y ◇ x)))) ◇ y
equation 29929 := x = (y ◇ (z ◇ (z ◇ (y ◇ x)))) ◇ z
equation 29930 := x = (y ◇ (z ◇ (z ◇ (y ◇ x)))) ◇ w
equation 29931 := x = (y ◇ (z ◇ (z ◇ (y ◇ y)))) ◇ x
equation 29932 := x = (y ◇ (z ◇ (z ◇ (y ◇ y)))) ◇ y
equation 29933 := x = (y ◇ (z ◇ (z ◇ (y ◇ y)))) ◇ z
equation 29934 := x = (y ◇ (z ◇ (z ◇ (y ◇ y)))) ◇ w
equation 29935 := x = (y ◇ (z ◇ (z ◇ (y ◇ z)))) ◇ x
equation 29936 := x = (y ◇ (z ◇ (z ◇ (y ◇ z)))) ◇ y
equation 29937 := x = (y ◇ (z ◇ (z ◇ (y ◇ z)))) ◇ z
equation 29938 := x = (y ◇ (z ◇ (z ◇ (y ◇ z)))) ◇ w
equation 29939 := x = (y ◇ (z ◇ (z ◇ (y ◇ w)))) ◇ x
equation 29940 := x = (y ◇ (z ◇ (z ◇ (y ◇ w)))) ◇ y
equation 29941 := x = (y ◇ (z ◇ (z ◇ (y ◇ w)))) ◇ z
equation 29942 := x = (y ◇ (z ◇ (z ◇ (y ◇ w)))) ◇ w
equation 29943 := x = (y ◇ (z ◇ (z ◇ (y ◇ w)))) ◇ u
equation 29944 := x = (y ◇ (z ◇ (z ◇ (z ◇ x)))) ◇ x
equation 29945 := x = (y ◇ (z ◇ (z ◇ (z ◇ x)))) ◇ y
equation 29946 := x = (y ◇ (z ◇ (z ◇ (z ◇ x)))) ◇ z
equation 29947 := x = (y ◇ (z ◇ (z ◇ (z ◇ x)))) ◇ w
equation 29948 := x = (y ◇ (z ◇ (z ◇ (z ◇ y)))) ◇ x
equation 29949 := x = (y ◇ (z ◇ (z ◇ (z ◇ y)))) ◇ y
equation 29950 := x = (y ◇ (z ◇ (z ◇ (z ◇ y)))) ◇ z
equation 29951 := x = (y ◇ (z ◇ (z ◇ (z ◇ y)))) ◇ w
equation 29952 := x = (y ◇ (z ◇ (z ◇ (z ◇ z)))) ◇ x
equation 29953 := x = (y ◇ (z ◇ (z ◇ (z ◇ z)))) ◇ y
equation 29954 := x = (y ◇ (z ◇ (z ◇ (z ◇ z)))) ◇ z
equation 29955 := x = (y ◇ (z ◇ (z ◇ (z ◇ z)))) ◇ w
equation 29956 := x = (y ◇ (z ◇ (z ◇ (z ◇ w)))) ◇ x
equation 29957 := x = (y ◇ (z ◇ (z ◇ (z ◇ w)))) ◇ y
equation 29958 := x = (y ◇ (z ◇ (z ◇ (z ◇ w)))) ◇ z
equation 29959 := x = (y ◇ (z ◇ (z ◇ (z ◇ w)))) ◇ w
equation 29960 := x = (y ◇ (z ◇ (z ◇ (z ◇ w)))) ◇ u
equation 29961 := x = (y ◇ (z ◇ (z ◇ (w ◇ x)))) ◇ x
equation 29962 := x = (y ◇ (z ◇ (z ◇ (w ◇ x)))) ◇ y
equation 29963 := x = (y ◇ (z ◇ (z ◇ (w ◇ x)))) ◇ z
equation 29964 := x = (y ◇ (z ◇ (z ◇ (w ◇ x)))) ◇ w
equation 29965 := x = (y ◇ (z ◇ (z ◇ (w ◇ x)))) ◇ u
equation 29966 := x = (y ◇ (z ◇ (z ◇ (w ◇ y)))) ◇ x
equation 29967 := x = (y ◇ (z ◇ (z ◇ (w ◇ y)))) ◇ y
equation 29968 := x = (y ◇ (z ◇ (z ◇ (w ◇ y)))) ◇ z
equation 29969 := x = (y ◇ (z ◇ (z ◇ (w ◇ y)))) ◇ w
equation 29970 := x = (y ◇ (z ◇ (z ◇ (w ◇ y)))) ◇ u
equation 29971 := x = (y ◇ (z ◇ (z ◇ (w ◇ z)))) ◇ x
equation 29972 := x = (y ◇ (z ◇ (z ◇ (w ◇ z)))) ◇ y
equation 29973 := x = (y ◇ (z ◇ (z ◇ (w ◇ z)))) ◇ z
equation 29974 := x = (y ◇ (z ◇ (z ◇ (w ◇ z)))) ◇ w
equation 29975 := x = (y ◇ (z ◇ (z ◇ (w ◇ z)))) ◇ u
equation 29976 := x = (y ◇ (z ◇ (z ◇ (w ◇ w)))) ◇ x
equation 29977 := x = (y ◇ (z ◇ (z ◇ (w ◇ w)))) ◇ y
equation 29978 := x = (y ◇ (z ◇ (z ◇ (w ◇ w)))) ◇ z
equation 29979 := x = (y ◇ (z ◇ (z ◇ (w ◇ w)))) ◇ w
equation 29980 := x = (y ◇ (z ◇ (z ◇ (w ◇ w)))) ◇ u
equation 29981 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ x
equation 29982 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ y
equation 29983 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ z
equation 29984 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ w
equation 29985 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ u
equation 29986 := x = (y ◇ (z ◇ (z ◇ (w ◇ u)))) ◇ v
equation 29987 := x = (y ◇ (z ◇ (w ◇ (x ◇ x)))) ◇ x
equation 29988 := x = (y ◇ (z ◇ (w ◇ (x ◇ x)))) ◇ y
equation 29989 := x = (y ◇ (z ◇ (w ◇ (x ◇ x)))) ◇ z
equation 29990 := x = (y ◇ (z ◇ (w ◇ (x ◇ x)))) ◇ w
equation 29991 := x = (y ◇ (z ◇ (w ◇ (x ◇ x)))) ◇ u
equation 29992 := x = (y ◇ (z ◇ (w ◇ (x ◇ y)))) ◇ x
equation 29993 := x = (y ◇ (z ◇ (w ◇ (x ◇ y)))) ◇ y
equation 29994 := x = (y ◇ (z ◇ (w ◇ (x ◇ y)))) ◇ z
equation 29995 := x = (y ◇ (z ◇ (w ◇ (x ◇ y)))) ◇ w
equation 29996 := x = (y ◇ (z ◇ (w ◇ (x ◇ y)))) ◇ u
equation 29997 := x = (y ◇ (z ◇ (w ◇ (x ◇ z)))) ◇ x
equation 29998 := x = (y ◇ (z ◇ (w ◇ (x ◇ z)))) ◇ y
equation 29999 := x = (y ◇ (z ◇ (w ◇ (x ◇ z)))) ◇ z
