import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 31000-31999 -/

equation 31000 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ z
equation 31001 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ w
equation 31002 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ u
equation 31003 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ v
equation 31004 := x = (y ◇ (z ◇ ((w ◇ u) ◇ v))) ◇ r
equation 31005 := x = (x ◇ ((x ◇ x) ◇ (x ◇ x))) ◇ x
equation 31006 := x = (x ◇ ((x ◇ x) ◇ (x ◇ x))) ◇ y
equation 31007 := x = (x ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ x
equation 31008 := x = (x ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ y
equation 31009 := x = (x ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ z
equation 31010 := x = (x ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ x
equation 31011 := x = (x ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ y
equation 31012 := x = (x ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ z
equation 31013 := x = (x ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ x
equation 31014 := x = (x ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ y
equation 31015 := x = (x ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ z
equation 31016 := x = (x ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ x
equation 31017 := x = (x ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ y
equation 31018 := x = (x ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ z
equation 31019 := x = (x ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ w
equation 31020 := x = (x ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ x
equation 31021 := x = (x ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ y
equation 31022 := x = (x ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ z
equation 31023 := x = (x ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ x
equation 31024 := x = (x ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ y
equation 31025 := x = (x ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ z
equation 31026 := x = (x ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ x
equation 31027 := x = (x ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ y
equation 31028 := x = (x ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ z
equation 31029 := x = (x ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ w
equation 31030 := x = (x ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ x
equation 31031 := x = (x ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ y
equation 31032 := x = (x ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ z
equation 31033 := x = (x ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ x
equation 31034 := x = (x ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ y
equation 31035 := x = (x ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ z
equation 31036 := x = (x ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ x
equation 31037 := x = (x ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ y
equation 31038 := x = (x ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ z
equation 31039 := x = (x ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ w
equation 31040 := x = (x ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ x
equation 31041 := x = (x ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ y
equation 31042 := x = (x ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ z
equation 31043 := x = (x ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ w
equation 31044 := x = (x ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ x
equation 31045 := x = (x ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ y
equation 31046 := x = (x ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ z
equation 31047 := x = (x ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ w
equation 31048 := x = (x ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ x
equation 31049 := x = (x ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ y
equation 31050 := x = (x ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ z
equation 31051 := x = (x ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ w
equation 31052 := x = (x ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ x
equation 31053 := x = (x ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ y
equation 31054 := x = (x ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ z
equation 31055 := x = (x ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ w
equation 31056 := x = (x ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ u
equation 31057 := x = (x ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ x
equation 31058 := x = (x ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ y
equation 31059 := x = (x ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ z
equation 31060 := x = (x ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ x
equation 31061 := x = (x ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ y
equation 31062 := x = (x ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ z
equation 31063 := x = (x ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ x
equation 31064 := x = (x ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ y
equation 31065 := x = (x ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ z
equation 31066 := x = (x ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ w
equation 31067 := x = (x ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ x
equation 31068 := x = (x ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ y
equation 31069 := x = (x ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ z
equation 31070 := x = (x ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ x
equation 31071 := x = (x ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ y
equation 31072 := x = (x ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ z
equation 31073 := x = (x ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ x
equation 31074 := x = (x ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ y
equation 31075 := x = (x ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ z
equation 31076 := x = (x ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ w
equation 31077 := x = (x ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ x
equation 31078 := x = (x ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ y
equation 31079 := x = (x ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ z
equation 31080 := x = (x ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ w
equation 31081 := x = (x ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ x
equation 31082 := x = (x ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ y
equation 31083 := x = (x ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ z
equation 31084 := x = (x ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ w
equation 31085 := x = (x ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ x
equation 31086 := x = (x ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ y
equation 31087 := x = (x ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ z
equation 31088 := x = (x ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ w
equation 31089 := x = (x ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ x
equation 31090 := x = (x ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ y
equation 31091 := x = (x ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ z
equation 31092 := x = (x ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ w
equation 31093 := x = (x ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ u
equation 31094 := x = (x ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ x
equation 31095 := x = (x ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ y
equation 31096 := x = (x ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ z
equation 31097 := x = (x ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ x
equation 31098 := x = (x ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ y
equation 31099 := x = (x ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ z
equation 31100 := x = (x ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ x
equation 31101 := x = (x ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ y
equation 31102 := x = (x ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ z
equation 31103 := x = (x ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ w
equation 31104 := x = (x ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ x
equation 31105 := x = (x ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ y
equation 31106 := x = (x ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ z
equation 31107 := x = (x ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ x
equation 31108 := x = (x ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ y
equation 31109 := x = (x ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ z
equation 31110 := x = (x ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ x
equation 31111 := x = (x ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ y
equation 31112 := x = (x ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ z
equation 31113 := x = (x ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ w
equation 31114 := x = (x ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ x
equation 31115 := x = (x ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ y
equation 31116 := x = (x ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ z
equation 31117 := x = (x ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ w
equation 31118 := x = (x ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ x
equation 31119 := x = (x ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ y
equation 31120 := x = (x ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ z
equation 31121 := x = (x ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ w
equation 31122 := x = (x ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ x
equation 31123 := x = (x ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ y
equation 31124 := x = (x ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ z
equation 31125 := x = (x ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ w
equation 31126 := x = (x ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ x
equation 31127 := x = (x ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ y
equation 31128 := x = (x ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ z
equation 31129 := x = (x ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ w
equation 31130 := x = (x ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ u
equation 31131 := x = (x ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ x
equation 31132 := x = (x ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ y
equation 31133 := x = (x ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ z
equation 31134 := x = (x ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ w
equation 31135 := x = (x ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ x
equation 31136 := x = (x ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ y
equation 31137 := x = (x ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ z
equation 31138 := x = (x ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ w
equation 31139 := x = (x ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ x
equation 31140 := x = (x ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ y
equation 31141 := x = (x ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ z
equation 31142 := x = (x ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ w
equation 31143 := x = (x ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ x
equation 31144 := x = (x ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ y
equation 31145 := x = (x ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ z
equation 31146 := x = (x ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ w
equation 31147 := x = (x ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ u
equation 31148 := x = (x ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ x
equation 31149 := x = (x ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ y
equation 31150 := x = (x ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ z
equation 31151 := x = (x ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ w
equation 31152 := x = (x ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ x
equation 31153 := x = (x ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ y
equation 31154 := x = (x ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ z
equation 31155 := x = (x ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ w
equation 31156 := x = (x ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ x
equation 31157 := x = (x ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ y
equation 31158 := x = (x ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ z
equation 31159 := x = (x ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ w
equation 31160 := x = (x ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ x
equation 31161 := x = (x ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ y
equation 31162 := x = (x ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ z
equation 31163 := x = (x ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ w
equation 31164 := x = (x ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ u
equation 31165 := x = (x ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ x
equation 31166 := x = (x ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ y
equation 31167 := x = (x ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ z
equation 31168 := x = (x ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ w
equation 31169 := x = (x ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ x
equation 31170 := x = (x ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ y
equation 31171 := x = (x ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ z
equation 31172 := x = (x ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ w
equation 31173 := x = (x ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ x
equation 31174 := x = (x ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ y
equation 31175 := x = (x ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ z
equation 31176 := x = (x ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ w
equation 31177 := x = (x ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ x
equation 31178 := x = (x ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ y
equation 31179 := x = (x ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ z
equation 31180 := x = (x ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ w
equation 31181 := x = (x ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ u
equation 31182 := x = (x ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ x
equation 31183 := x = (x ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ y
equation 31184 := x = (x ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ z
equation 31185 := x = (x ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ w
equation 31186 := x = (x ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ u
equation 31187 := x = (x ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ x
equation 31188 := x = (x ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ y
equation 31189 := x = (x ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ z
equation 31190 := x = (x ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ w
equation 31191 := x = (x ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ u
equation 31192 := x = (x ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ x
equation 31193 := x = (x ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ y
equation 31194 := x = (x ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ z
equation 31195 := x = (x ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ w
equation 31196 := x = (x ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ u
equation 31197 := x = (x ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ x
equation 31198 := x = (x ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ y
equation 31199 := x = (x ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ z
equation 31200 := x = (x ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ w
equation 31201 := x = (x ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ u
equation 31202 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ x
equation 31203 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ y
equation 31204 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ z
equation 31205 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ w
equation 31206 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ u
equation 31207 := x = (x ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ v
equation 31208 := x = (y ◇ ((x ◇ x) ◇ (x ◇ x))) ◇ x
equation 31209 := x = (y ◇ ((x ◇ x) ◇ (x ◇ x))) ◇ y
equation 31210 := x = (y ◇ ((x ◇ x) ◇ (x ◇ x))) ◇ z
equation 31211 := x = (y ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ x
equation 31212 := x = (y ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ y
equation 31213 := x = (y ◇ ((x ◇ x) ◇ (x ◇ y))) ◇ z
equation 31214 := x = (y ◇ ((x ◇ x) ◇ (x ◇ z))) ◇ x
equation 31215 := x = (y ◇ ((x ◇ x) ◇ (x ◇ z))) ◇ y
equation 31216 := x = (y ◇ ((x ◇ x) ◇ (x ◇ z))) ◇ z
equation 31217 := x = (y ◇ ((x ◇ x) ◇ (x ◇ z))) ◇ w
equation 31218 := x = (y ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ x
equation 31219 := x = (y ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ y
equation 31220 := x = (y ◇ ((x ◇ x) ◇ (y ◇ x))) ◇ z
equation 31221 := x = (y ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ x
equation 31222 := x = (y ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ y
equation 31223 := x = (y ◇ ((x ◇ x) ◇ (y ◇ y))) ◇ z
equation 31224 := x = (y ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ x
equation 31225 := x = (y ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ y
equation 31226 := x = (y ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ z
equation 31227 := x = (y ◇ ((x ◇ x) ◇ (y ◇ z))) ◇ w
equation 31228 := x = (y ◇ ((x ◇ x) ◇ (z ◇ x))) ◇ x
equation 31229 := x = (y ◇ ((x ◇ x) ◇ (z ◇ x))) ◇ y
equation 31230 := x = (y ◇ ((x ◇ x) ◇ (z ◇ x))) ◇ z
equation 31231 := x = (y ◇ ((x ◇ x) ◇ (z ◇ x))) ◇ w
equation 31232 := x = (y ◇ ((x ◇ x) ◇ (z ◇ y))) ◇ x
equation 31233 := x = (y ◇ ((x ◇ x) ◇ (z ◇ y))) ◇ y
equation 31234 := x = (y ◇ ((x ◇ x) ◇ (z ◇ y))) ◇ z
equation 31235 := x = (y ◇ ((x ◇ x) ◇ (z ◇ y))) ◇ w
equation 31236 := x = (y ◇ ((x ◇ x) ◇ (z ◇ z))) ◇ x
equation 31237 := x = (y ◇ ((x ◇ x) ◇ (z ◇ z))) ◇ y
equation 31238 := x = (y ◇ ((x ◇ x) ◇ (z ◇ z))) ◇ z
equation 31239 := x = (y ◇ ((x ◇ x) ◇ (z ◇ z))) ◇ w
equation 31240 := x = (y ◇ ((x ◇ x) ◇ (z ◇ w))) ◇ x
equation 31241 := x = (y ◇ ((x ◇ x) ◇ (z ◇ w))) ◇ y
equation 31242 := x = (y ◇ ((x ◇ x) ◇ (z ◇ w))) ◇ z
equation 31243 := x = (y ◇ ((x ◇ x) ◇ (z ◇ w))) ◇ w
equation 31244 := x = (y ◇ ((x ◇ x) ◇ (z ◇ w))) ◇ u
equation 31245 := x = (y ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ x
equation 31246 := x = (y ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ y
equation 31247 := x = (y ◇ ((x ◇ y) ◇ (x ◇ x))) ◇ z
equation 31248 := x = (y ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ x
equation 31249 := x = (y ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ y
equation 31250 := x = (y ◇ ((x ◇ y) ◇ (x ◇ y))) ◇ z
equation 31251 := x = (y ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ x
equation 31252 := x = (y ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ y
equation 31253 := x = (y ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ z
equation 31254 := x = (y ◇ ((x ◇ y) ◇ (x ◇ z))) ◇ w
equation 31255 := x = (y ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ x
equation 31256 := x = (y ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ y
equation 31257 := x = (y ◇ ((x ◇ y) ◇ (y ◇ x))) ◇ z
equation 31258 := x = (y ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ x
equation 31259 := x = (y ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ y
equation 31260 := x = (y ◇ ((x ◇ y) ◇ (y ◇ y))) ◇ z
equation 31261 := x = (y ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ x
equation 31262 := x = (y ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ y
equation 31263 := x = (y ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ z
equation 31264 := x = (y ◇ ((x ◇ y) ◇ (y ◇ z))) ◇ w
equation 31265 := x = (y ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ x
equation 31266 := x = (y ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ y
equation 31267 := x = (y ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ z
equation 31268 := x = (y ◇ ((x ◇ y) ◇ (z ◇ x))) ◇ w
equation 31269 := x = (y ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ x
equation 31270 := x = (y ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ y
equation 31271 := x = (y ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ z
equation 31272 := x = (y ◇ ((x ◇ y) ◇ (z ◇ y))) ◇ w
equation 31273 := x = (y ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ x
equation 31274 := x = (y ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ y
equation 31275 := x = (y ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ z
equation 31276 := x = (y ◇ ((x ◇ y) ◇ (z ◇ z))) ◇ w
equation 31277 := x = (y ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ x
equation 31278 := x = (y ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ y
equation 31279 := x = (y ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ z
equation 31280 := x = (y ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ w
equation 31281 := x = (y ◇ ((x ◇ y) ◇ (z ◇ w))) ◇ u
equation 31282 := x = (y ◇ ((x ◇ z) ◇ (x ◇ x))) ◇ x
equation 31283 := x = (y ◇ ((x ◇ z) ◇ (x ◇ x))) ◇ y
equation 31284 := x = (y ◇ ((x ◇ z) ◇ (x ◇ x))) ◇ z
equation 31285 := x = (y ◇ ((x ◇ z) ◇ (x ◇ x))) ◇ w
equation 31286 := x = (y ◇ ((x ◇ z) ◇ (x ◇ y))) ◇ x
equation 31287 := x = (y ◇ ((x ◇ z) ◇ (x ◇ y))) ◇ y
equation 31288 := x = (y ◇ ((x ◇ z) ◇ (x ◇ y))) ◇ z
equation 31289 := x = (y ◇ ((x ◇ z) ◇ (x ◇ y))) ◇ w
equation 31290 := x = (y ◇ ((x ◇ z) ◇ (x ◇ z))) ◇ x
equation 31291 := x = (y ◇ ((x ◇ z) ◇ (x ◇ z))) ◇ y
equation 31292 := x = (y ◇ ((x ◇ z) ◇ (x ◇ z))) ◇ z
equation 31293 := x = (y ◇ ((x ◇ z) ◇ (x ◇ z))) ◇ w
equation 31294 := x = (y ◇ ((x ◇ z) ◇ (x ◇ w))) ◇ x
equation 31295 := x = (y ◇ ((x ◇ z) ◇ (x ◇ w))) ◇ y
equation 31296 := x = (y ◇ ((x ◇ z) ◇ (x ◇ w))) ◇ z
equation 31297 := x = (y ◇ ((x ◇ z) ◇ (x ◇ w))) ◇ w
equation 31298 := x = (y ◇ ((x ◇ z) ◇ (x ◇ w))) ◇ u
equation 31299 := x = (y ◇ ((x ◇ z) ◇ (y ◇ x))) ◇ x
equation 31300 := x = (y ◇ ((x ◇ z) ◇ (y ◇ x))) ◇ y
equation 31301 := x = (y ◇ ((x ◇ z) ◇ (y ◇ x))) ◇ z
equation 31302 := x = (y ◇ ((x ◇ z) ◇ (y ◇ x))) ◇ w
equation 31303 := x = (y ◇ ((x ◇ z) ◇ (y ◇ y))) ◇ x
equation 31304 := x = (y ◇ ((x ◇ z) ◇ (y ◇ y))) ◇ y
equation 31305 := x = (y ◇ ((x ◇ z) ◇ (y ◇ y))) ◇ z
equation 31306 := x = (y ◇ ((x ◇ z) ◇ (y ◇ y))) ◇ w
equation 31307 := x = (y ◇ ((x ◇ z) ◇ (y ◇ z))) ◇ x
equation 31308 := x = (y ◇ ((x ◇ z) ◇ (y ◇ z))) ◇ y
equation 31309 := x = (y ◇ ((x ◇ z) ◇ (y ◇ z))) ◇ z
equation 31310 := x = (y ◇ ((x ◇ z) ◇ (y ◇ z))) ◇ w
equation 31311 := x = (y ◇ ((x ◇ z) ◇ (y ◇ w))) ◇ x
equation 31312 := x = (y ◇ ((x ◇ z) ◇ (y ◇ w))) ◇ y
equation 31313 := x = (y ◇ ((x ◇ z) ◇ (y ◇ w))) ◇ z
equation 31314 := x = (y ◇ ((x ◇ z) ◇ (y ◇ w))) ◇ w
equation 31315 := x = (y ◇ ((x ◇ z) ◇ (y ◇ w))) ◇ u
equation 31316 := x = (y ◇ ((x ◇ z) ◇ (z ◇ x))) ◇ x
equation 31317 := x = (y ◇ ((x ◇ z) ◇ (z ◇ x))) ◇ y
equation 31318 := x = (y ◇ ((x ◇ z) ◇ (z ◇ x))) ◇ z
equation 31319 := x = (y ◇ ((x ◇ z) ◇ (z ◇ x))) ◇ w
equation 31320 := x = (y ◇ ((x ◇ z) ◇ (z ◇ y))) ◇ x
equation 31321 := x = (y ◇ ((x ◇ z) ◇ (z ◇ y))) ◇ y
equation 31322 := x = (y ◇ ((x ◇ z) ◇ (z ◇ y))) ◇ z
equation 31323 := x = (y ◇ ((x ◇ z) ◇ (z ◇ y))) ◇ w
equation 31324 := x = (y ◇ ((x ◇ z) ◇ (z ◇ z))) ◇ x
equation 31325 := x = (y ◇ ((x ◇ z) ◇ (z ◇ z))) ◇ y
equation 31326 := x = (y ◇ ((x ◇ z) ◇ (z ◇ z))) ◇ z
equation 31327 := x = (y ◇ ((x ◇ z) ◇ (z ◇ z))) ◇ w
equation 31328 := x = (y ◇ ((x ◇ z) ◇ (z ◇ w))) ◇ x
equation 31329 := x = (y ◇ ((x ◇ z) ◇ (z ◇ w))) ◇ y
equation 31330 := x = (y ◇ ((x ◇ z) ◇ (z ◇ w))) ◇ z
equation 31331 := x = (y ◇ ((x ◇ z) ◇ (z ◇ w))) ◇ w
equation 31332 := x = (y ◇ ((x ◇ z) ◇ (z ◇ w))) ◇ u
equation 31333 := x = (y ◇ ((x ◇ z) ◇ (w ◇ x))) ◇ x
equation 31334 := x = (y ◇ ((x ◇ z) ◇ (w ◇ x))) ◇ y
equation 31335 := x = (y ◇ ((x ◇ z) ◇ (w ◇ x))) ◇ z
equation 31336 := x = (y ◇ ((x ◇ z) ◇ (w ◇ x))) ◇ w
equation 31337 := x = (y ◇ ((x ◇ z) ◇ (w ◇ x))) ◇ u
equation 31338 := x = (y ◇ ((x ◇ z) ◇ (w ◇ y))) ◇ x
equation 31339 := x = (y ◇ ((x ◇ z) ◇ (w ◇ y))) ◇ y
equation 31340 := x = (y ◇ ((x ◇ z) ◇ (w ◇ y))) ◇ z
equation 31341 := x = (y ◇ ((x ◇ z) ◇ (w ◇ y))) ◇ w
equation 31342 := x = (y ◇ ((x ◇ z) ◇ (w ◇ y))) ◇ u
equation 31343 := x = (y ◇ ((x ◇ z) ◇ (w ◇ z))) ◇ x
equation 31344 := x = (y ◇ ((x ◇ z) ◇ (w ◇ z))) ◇ y
equation 31345 := x = (y ◇ ((x ◇ z) ◇ (w ◇ z))) ◇ z
equation 31346 := x = (y ◇ ((x ◇ z) ◇ (w ◇ z))) ◇ w
equation 31347 := x = (y ◇ ((x ◇ z) ◇ (w ◇ z))) ◇ u
equation 31348 := x = (y ◇ ((x ◇ z) ◇ (w ◇ w))) ◇ x
equation 31349 := x = (y ◇ ((x ◇ z) ◇ (w ◇ w))) ◇ y
equation 31350 := x = (y ◇ ((x ◇ z) ◇ (w ◇ w))) ◇ z
equation 31351 := x = (y ◇ ((x ◇ z) ◇ (w ◇ w))) ◇ w
equation 31352 := x = (y ◇ ((x ◇ z) ◇ (w ◇ w))) ◇ u
equation 31353 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ x
equation 31354 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ y
equation 31355 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ z
equation 31356 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ w
equation 31357 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ u
equation 31358 := x = (y ◇ ((x ◇ z) ◇ (w ◇ u))) ◇ v
equation 31359 := x = (y ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ x
equation 31360 := x = (y ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ y
equation 31361 := x = (y ◇ ((y ◇ x) ◇ (x ◇ x))) ◇ z
equation 31362 := x = (y ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ x
equation 31363 := x = (y ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ y
equation 31364 := x = (y ◇ ((y ◇ x) ◇ (x ◇ y))) ◇ z
equation 31365 := x = (y ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ x
equation 31366 := x = (y ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ y
equation 31367 := x = (y ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ z
equation 31368 := x = (y ◇ ((y ◇ x) ◇ (x ◇ z))) ◇ w
equation 31369 := x = (y ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ x
equation 31370 := x = (y ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ y
equation 31371 := x = (y ◇ ((y ◇ x) ◇ (y ◇ x))) ◇ z
equation 31372 := x = (y ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ x
equation 31373 := x = (y ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ y
equation 31374 := x = (y ◇ ((y ◇ x) ◇ (y ◇ y))) ◇ z
equation 31375 := x = (y ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ x
equation 31376 := x = (y ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ y
equation 31377 := x = (y ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ z
equation 31378 := x = (y ◇ ((y ◇ x) ◇ (y ◇ z))) ◇ w
equation 31379 := x = (y ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ x
equation 31380 := x = (y ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ y
equation 31381 := x = (y ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ z
equation 31382 := x = (y ◇ ((y ◇ x) ◇ (z ◇ x))) ◇ w
equation 31383 := x = (y ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ x
equation 31384 := x = (y ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ y
equation 31385 := x = (y ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ z
equation 31386 := x = (y ◇ ((y ◇ x) ◇ (z ◇ y))) ◇ w
equation 31387 := x = (y ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ x
equation 31388 := x = (y ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ y
equation 31389 := x = (y ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ z
equation 31390 := x = (y ◇ ((y ◇ x) ◇ (z ◇ z))) ◇ w
equation 31391 := x = (y ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ x
equation 31392 := x = (y ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ y
equation 31393 := x = (y ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ z
equation 31394 := x = (y ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ w
equation 31395 := x = (y ◇ ((y ◇ x) ◇ (z ◇ w))) ◇ u
equation 31396 := x = (y ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ x
equation 31397 := x = (y ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ y
equation 31398 := x = (y ◇ ((y ◇ y) ◇ (x ◇ x))) ◇ z
equation 31399 := x = (y ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ x
equation 31400 := x = (y ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ y
equation 31401 := x = (y ◇ ((y ◇ y) ◇ (x ◇ y))) ◇ z
equation 31402 := x = (y ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ x
equation 31403 := x = (y ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ y
equation 31404 := x = (y ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ z
equation 31405 := x = (y ◇ ((y ◇ y) ◇ (x ◇ z))) ◇ w
equation 31406 := x = (y ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ x
equation 31407 := x = (y ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ y
equation 31408 := x = (y ◇ ((y ◇ y) ◇ (y ◇ x))) ◇ z
equation 31409 := x = (y ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ x
equation 31410 := x = (y ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ y
equation 31411 := x = (y ◇ ((y ◇ y) ◇ (y ◇ y))) ◇ z
equation 31412 := x = (y ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ x
equation 31413 := x = (y ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ y
equation 31414 := x = (y ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ z
equation 31415 := x = (y ◇ ((y ◇ y) ◇ (y ◇ z))) ◇ w
equation 31416 := x = (y ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ x
equation 31417 := x = (y ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ y
equation 31418 := x = (y ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ z
equation 31419 := x = (y ◇ ((y ◇ y) ◇ (z ◇ x))) ◇ w
equation 31420 := x = (y ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ x
equation 31421 := x = (y ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ y
equation 31422 := x = (y ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ z
equation 31423 := x = (y ◇ ((y ◇ y) ◇ (z ◇ y))) ◇ w
equation 31424 := x = (y ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ x
equation 31425 := x = (y ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ y
equation 31426 := x = (y ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ z
equation 31427 := x = (y ◇ ((y ◇ y) ◇ (z ◇ z))) ◇ w
equation 31428 := x = (y ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ x
equation 31429 := x = (y ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ y
equation 31430 := x = (y ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ z
equation 31431 := x = (y ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ w
equation 31432 := x = (y ◇ ((y ◇ y) ◇ (z ◇ w))) ◇ u
equation 31433 := x = (y ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ x
equation 31434 := x = (y ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ y
equation 31435 := x = (y ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ z
equation 31436 := x = (y ◇ ((y ◇ z) ◇ (x ◇ x))) ◇ w
equation 31437 := x = (y ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ x
equation 31438 := x = (y ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ y
equation 31439 := x = (y ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ z
equation 31440 := x = (y ◇ ((y ◇ z) ◇ (x ◇ y))) ◇ w
equation 31441 := x = (y ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ x
equation 31442 := x = (y ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ y
equation 31443 := x = (y ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ z
equation 31444 := x = (y ◇ ((y ◇ z) ◇ (x ◇ z))) ◇ w
equation 31445 := x = (y ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ x
equation 31446 := x = (y ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ y
equation 31447 := x = (y ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ z
equation 31448 := x = (y ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ w
equation 31449 := x = (y ◇ ((y ◇ z) ◇ (x ◇ w))) ◇ u
equation 31450 := x = (y ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ x
equation 31451 := x = (y ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ y
equation 31452 := x = (y ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ z
equation 31453 := x = (y ◇ ((y ◇ z) ◇ (y ◇ x))) ◇ w
equation 31454 := x = (y ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ x
equation 31455 := x = (y ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ y
equation 31456 := x = (y ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ z
equation 31457 := x = (y ◇ ((y ◇ z) ◇ (y ◇ y))) ◇ w
equation 31458 := x = (y ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ x
equation 31459 := x = (y ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ y
equation 31460 := x = (y ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ z
equation 31461 := x = (y ◇ ((y ◇ z) ◇ (y ◇ z))) ◇ w
equation 31462 := x = (y ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ x
equation 31463 := x = (y ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ y
equation 31464 := x = (y ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ z
equation 31465 := x = (y ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ w
equation 31466 := x = (y ◇ ((y ◇ z) ◇ (y ◇ w))) ◇ u
equation 31467 := x = (y ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ x
equation 31468 := x = (y ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ y
equation 31469 := x = (y ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ z
equation 31470 := x = (y ◇ ((y ◇ z) ◇ (z ◇ x))) ◇ w
equation 31471 := x = (y ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ x
equation 31472 := x = (y ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ y
equation 31473 := x = (y ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ z
equation 31474 := x = (y ◇ ((y ◇ z) ◇ (z ◇ y))) ◇ w
equation 31475 := x = (y ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ x
equation 31476 := x = (y ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ y
equation 31477 := x = (y ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ z
equation 31478 := x = (y ◇ ((y ◇ z) ◇ (z ◇ z))) ◇ w
equation 31479 := x = (y ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ x
equation 31480 := x = (y ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ y
equation 31481 := x = (y ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ z
equation 31482 := x = (y ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ w
equation 31483 := x = (y ◇ ((y ◇ z) ◇ (z ◇ w))) ◇ u
equation 31484 := x = (y ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ x
equation 31485 := x = (y ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ y
equation 31486 := x = (y ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ z
equation 31487 := x = (y ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ w
equation 31488 := x = (y ◇ ((y ◇ z) ◇ (w ◇ x))) ◇ u
equation 31489 := x = (y ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ x
equation 31490 := x = (y ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ y
equation 31491 := x = (y ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ z
equation 31492 := x = (y ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ w
equation 31493 := x = (y ◇ ((y ◇ z) ◇ (w ◇ y))) ◇ u
equation 31494 := x = (y ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ x
equation 31495 := x = (y ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ y
equation 31496 := x = (y ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ z
equation 31497 := x = (y ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ w
equation 31498 := x = (y ◇ ((y ◇ z) ◇ (w ◇ z))) ◇ u
equation 31499 := x = (y ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ x
equation 31500 := x = (y ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ y
equation 31501 := x = (y ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ z
equation 31502 := x = (y ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ w
equation 31503 := x = (y ◇ ((y ◇ z) ◇ (w ◇ w))) ◇ u
equation 31504 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ x
equation 31505 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ y
equation 31506 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ z
equation 31507 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ w
equation 31508 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ u
equation 31509 := x = (y ◇ ((y ◇ z) ◇ (w ◇ u))) ◇ v
equation 31510 := x = (y ◇ ((z ◇ x) ◇ (x ◇ x))) ◇ x
equation 31511 := x = (y ◇ ((z ◇ x) ◇ (x ◇ x))) ◇ y
equation 31512 := x = (y ◇ ((z ◇ x) ◇ (x ◇ x))) ◇ z
equation 31513 := x = (y ◇ ((z ◇ x) ◇ (x ◇ x))) ◇ w
equation 31514 := x = (y ◇ ((z ◇ x) ◇ (x ◇ y))) ◇ x
equation 31515 := x = (y ◇ ((z ◇ x) ◇ (x ◇ y))) ◇ y
equation 31516 := x = (y ◇ ((z ◇ x) ◇ (x ◇ y))) ◇ z
equation 31517 := x = (y ◇ ((z ◇ x) ◇ (x ◇ y))) ◇ w
equation 31518 := x = (y ◇ ((z ◇ x) ◇ (x ◇ z))) ◇ x
equation 31519 := x = (y ◇ ((z ◇ x) ◇ (x ◇ z))) ◇ y
equation 31520 := x = (y ◇ ((z ◇ x) ◇ (x ◇ z))) ◇ z
equation 31521 := x = (y ◇ ((z ◇ x) ◇ (x ◇ z))) ◇ w
equation 31522 := x = (y ◇ ((z ◇ x) ◇ (x ◇ w))) ◇ x
equation 31523 := x = (y ◇ ((z ◇ x) ◇ (x ◇ w))) ◇ y
equation 31524 := x = (y ◇ ((z ◇ x) ◇ (x ◇ w))) ◇ z
equation 31525 := x = (y ◇ ((z ◇ x) ◇ (x ◇ w))) ◇ w
equation 31526 := x = (y ◇ ((z ◇ x) ◇ (x ◇ w))) ◇ u
equation 31527 := x = (y ◇ ((z ◇ x) ◇ (y ◇ x))) ◇ x
equation 31528 := x = (y ◇ ((z ◇ x) ◇ (y ◇ x))) ◇ y
equation 31529 := x = (y ◇ ((z ◇ x) ◇ (y ◇ x))) ◇ z
equation 31530 := x = (y ◇ ((z ◇ x) ◇ (y ◇ x))) ◇ w
equation 31531 := x = (y ◇ ((z ◇ x) ◇ (y ◇ y))) ◇ x
equation 31532 := x = (y ◇ ((z ◇ x) ◇ (y ◇ y))) ◇ y
equation 31533 := x = (y ◇ ((z ◇ x) ◇ (y ◇ y))) ◇ z
equation 31534 := x = (y ◇ ((z ◇ x) ◇ (y ◇ y))) ◇ w
equation 31535 := x = (y ◇ ((z ◇ x) ◇ (y ◇ z))) ◇ x
equation 31536 := x = (y ◇ ((z ◇ x) ◇ (y ◇ z))) ◇ y
equation 31537 := x = (y ◇ ((z ◇ x) ◇ (y ◇ z))) ◇ z
equation 31538 := x = (y ◇ ((z ◇ x) ◇ (y ◇ z))) ◇ w
equation 31539 := x = (y ◇ ((z ◇ x) ◇ (y ◇ w))) ◇ x
equation 31540 := x = (y ◇ ((z ◇ x) ◇ (y ◇ w))) ◇ y
equation 31541 := x = (y ◇ ((z ◇ x) ◇ (y ◇ w))) ◇ z
equation 31542 := x = (y ◇ ((z ◇ x) ◇ (y ◇ w))) ◇ w
equation 31543 := x = (y ◇ ((z ◇ x) ◇ (y ◇ w))) ◇ u
equation 31544 := x = (y ◇ ((z ◇ x) ◇ (z ◇ x))) ◇ x
equation 31545 := x = (y ◇ ((z ◇ x) ◇ (z ◇ x))) ◇ y
equation 31546 := x = (y ◇ ((z ◇ x) ◇ (z ◇ x))) ◇ z
equation 31547 := x = (y ◇ ((z ◇ x) ◇ (z ◇ x))) ◇ w
equation 31548 := x = (y ◇ ((z ◇ x) ◇ (z ◇ y))) ◇ x
equation 31549 := x = (y ◇ ((z ◇ x) ◇ (z ◇ y))) ◇ y
equation 31550 := x = (y ◇ ((z ◇ x) ◇ (z ◇ y))) ◇ z
equation 31551 := x = (y ◇ ((z ◇ x) ◇ (z ◇ y))) ◇ w
equation 31552 := x = (y ◇ ((z ◇ x) ◇ (z ◇ z))) ◇ x
equation 31553 := x = (y ◇ ((z ◇ x) ◇ (z ◇ z))) ◇ y
equation 31554 := x = (y ◇ ((z ◇ x) ◇ (z ◇ z))) ◇ z
equation 31555 := x = (y ◇ ((z ◇ x) ◇ (z ◇ z))) ◇ w
equation 31556 := x = (y ◇ ((z ◇ x) ◇ (z ◇ w))) ◇ x
equation 31557 := x = (y ◇ ((z ◇ x) ◇ (z ◇ w))) ◇ y
equation 31558 := x = (y ◇ ((z ◇ x) ◇ (z ◇ w))) ◇ z
equation 31559 := x = (y ◇ ((z ◇ x) ◇ (z ◇ w))) ◇ w
equation 31560 := x = (y ◇ ((z ◇ x) ◇ (z ◇ w))) ◇ u
equation 31561 := x = (y ◇ ((z ◇ x) ◇ (w ◇ x))) ◇ x
equation 31562 := x = (y ◇ ((z ◇ x) ◇ (w ◇ x))) ◇ y
equation 31563 := x = (y ◇ ((z ◇ x) ◇ (w ◇ x))) ◇ z
equation 31564 := x = (y ◇ ((z ◇ x) ◇ (w ◇ x))) ◇ w
equation 31565 := x = (y ◇ ((z ◇ x) ◇ (w ◇ x))) ◇ u
equation 31566 := x = (y ◇ ((z ◇ x) ◇ (w ◇ y))) ◇ x
equation 31567 := x = (y ◇ ((z ◇ x) ◇ (w ◇ y))) ◇ y
equation 31568 := x = (y ◇ ((z ◇ x) ◇ (w ◇ y))) ◇ z
equation 31569 := x = (y ◇ ((z ◇ x) ◇ (w ◇ y))) ◇ w
equation 31570 := x = (y ◇ ((z ◇ x) ◇ (w ◇ y))) ◇ u
equation 31571 := x = (y ◇ ((z ◇ x) ◇ (w ◇ z))) ◇ x
equation 31572 := x = (y ◇ ((z ◇ x) ◇ (w ◇ z))) ◇ y
equation 31573 := x = (y ◇ ((z ◇ x) ◇ (w ◇ z))) ◇ z
equation 31574 := x = (y ◇ ((z ◇ x) ◇ (w ◇ z))) ◇ w
equation 31575 := x = (y ◇ ((z ◇ x) ◇ (w ◇ z))) ◇ u
equation 31576 := x = (y ◇ ((z ◇ x) ◇ (w ◇ w))) ◇ x
equation 31577 := x = (y ◇ ((z ◇ x) ◇ (w ◇ w))) ◇ y
equation 31578 := x = (y ◇ ((z ◇ x) ◇ (w ◇ w))) ◇ z
equation 31579 := x = (y ◇ ((z ◇ x) ◇ (w ◇ w))) ◇ w
equation 31580 := x = (y ◇ ((z ◇ x) ◇ (w ◇ w))) ◇ u
equation 31581 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ x
equation 31582 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ y
equation 31583 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ z
equation 31584 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ w
equation 31585 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ u
equation 31586 := x = (y ◇ ((z ◇ x) ◇ (w ◇ u))) ◇ v
equation 31587 := x = (y ◇ ((z ◇ y) ◇ (x ◇ x))) ◇ x
equation 31588 := x = (y ◇ ((z ◇ y) ◇ (x ◇ x))) ◇ y
equation 31589 := x = (y ◇ ((z ◇ y) ◇ (x ◇ x))) ◇ z
equation 31590 := x = (y ◇ ((z ◇ y) ◇ (x ◇ x))) ◇ w
equation 31591 := x = (y ◇ ((z ◇ y) ◇ (x ◇ y))) ◇ x
equation 31592 := x = (y ◇ ((z ◇ y) ◇ (x ◇ y))) ◇ y
equation 31593 := x = (y ◇ ((z ◇ y) ◇ (x ◇ y))) ◇ z
equation 31594 := x = (y ◇ ((z ◇ y) ◇ (x ◇ y))) ◇ w
equation 31595 := x = (y ◇ ((z ◇ y) ◇ (x ◇ z))) ◇ x
equation 31596 := x = (y ◇ ((z ◇ y) ◇ (x ◇ z))) ◇ y
equation 31597 := x = (y ◇ ((z ◇ y) ◇ (x ◇ z))) ◇ z
equation 31598 := x = (y ◇ ((z ◇ y) ◇ (x ◇ z))) ◇ w
equation 31599 := x = (y ◇ ((z ◇ y) ◇ (x ◇ w))) ◇ x
equation 31600 := x = (y ◇ ((z ◇ y) ◇ (x ◇ w))) ◇ y
equation 31601 := x = (y ◇ ((z ◇ y) ◇ (x ◇ w))) ◇ z
equation 31602 := x = (y ◇ ((z ◇ y) ◇ (x ◇ w))) ◇ w
equation 31603 := x = (y ◇ ((z ◇ y) ◇ (x ◇ w))) ◇ u
equation 31604 := x = (y ◇ ((z ◇ y) ◇ (y ◇ x))) ◇ x
equation 31605 := x = (y ◇ ((z ◇ y) ◇ (y ◇ x))) ◇ y
equation 31606 := x = (y ◇ ((z ◇ y) ◇ (y ◇ x))) ◇ z
equation 31607 := x = (y ◇ ((z ◇ y) ◇ (y ◇ x))) ◇ w
equation 31608 := x = (y ◇ ((z ◇ y) ◇ (y ◇ y))) ◇ x
equation 31609 := x = (y ◇ ((z ◇ y) ◇ (y ◇ y))) ◇ y
equation 31610 := x = (y ◇ ((z ◇ y) ◇ (y ◇ y))) ◇ z
equation 31611 := x = (y ◇ ((z ◇ y) ◇ (y ◇ y))) ◇ w
equation 31612 := x = (y ◇ ((z ◇ y) ◇ (y ◇ z))) ◇ x
equation 31613 := x = (y ◇ ((z ◇ y) ◇ (y ◇ z))) ◇ y
equation 31614 := x = (y ◇ ((z ◇ y) ◇ (y ◇ z))) ◇ z
equation 31615 := x = (y ◇ ((z ◇ y) ◇ (y ◇ z))) ◇ w
equation 31616 := x = (y ◇ ((z ◇ y) ◇ (y ◇ w))) ◇ x
equation 31617 := x = (y ◇ ((z ◇ y) ◇ (y ◇ w))) ◇ y
equation 31618 := x = (y ◇ ((z ◇ y) ◇ (y ◇ w))) ◇ z
equation 31619 := x = (y ◇ ((z ◇ y) ◇ (y ◇ w))) ◇ w
equation 31620 := x = (y ◇ ((z ◇ y) ◇ (y ◇ w))) ◇ u
equation 31621 := x = (y ◇ ((z ◇ y) ◇ (z ◇ x))) ◇ x
equation 31622 := x = (y ◇ ((z ◇ y) ◇ (z ◇ x))) ◇ y
equation 31623 := x = (y ◇ ((z ◇ y) ◇ (z ◇ x))) ◇ z
equation 31624 := x = (y ◇ ((z ◇ y) ◇ (z ◇ x))) ◇ w
equation 31625 := x = (y ◇ ((z ◇ y) ◇ (z ◇ y))) ◇ x
equation 31626 := x = (y ◇ ((z ◇ y) ◇ (z ◇ y))) ◇ y
equation 31627 := x = (y ◇ ((z ◇ y) ◇ (z ◇ y))) ◇ z
equation 31628 := x = (y ◇ ((z ◇ y) ◇ (z ◇ y))) ◇ w
equation 31629 := x = (y ◇ ((z ◇ y) ◇ (z ◇ z))) ◇ x
equation 31630 := x = (y ◇ ((z ◇ y) ◇ (z ◇ z))) ◇ y
equation 31631 := x = (y ◇ ((z ◇ y) ◇ (z ◇ z))) ◇ z
equation 31632 := x = (y ◇ ((z ◇ y) ◇ (z ◇ z))) ◇ w
equation 31633 := x = (y ◇ ((z ◇ y) ◇ (z ◇ w))) ◇ x
equation 31634 := x = (y ◇ ((z ◇ y) ◇ (z ◇ w))) ◇ y
equation 31635 := x = (y ◇ ((z ◇ y) ◇ (z ◇ w))) ◇ z
equation 31636 := x = (y ◇ ((z ◇ y) ◇ (z ◇ w))) ◇ w
equation 31637 := x = (y ◇ ((z ◇ y) ◇ (z ◇ w))) ◇ u
equation 31638 := x = (y ◇ ((z ◇ y) ◇ (w ◇ x))) ◇ x
equation 31639 := x = (y ◇ ((z ◇ y) ◇ (w ◇ x))) ◇ y
equation 31640 := x = (y ◇ ((z ◇ y) ◇ (w ◇ x))) ◇ z
equation 31641 := x = (y ◇ ((z ◇ y) ◇ (w ◇ x))) ◇ w
equation 31642 := x = (y ◇ ((z ◇ y) ◇ (w ◇ x))) ◇ u
equation 31643 := x = (y ◇ ((z ◇ y) ◇ (w ◇ y))) ◇ x
equation 31644 := x = (y ◇ ((z ◇ y) ◇ (w ◇ y))) ◇ y
equation 31645 := x = (y ◇ ((z ◇ y) ◇ (w ◇ y))) ◇ z
equation 31646 := x = (y ◇ ((z ◇ y) ◇ (w ◇ y))) ◇ w
equation 31647 := x = (y ◇ ((z ◇ y) ◇ (w ◇ y))) ◇ u
equation 31648 := x = (y ◇ ((z ◇ y) ◇ (w ◇ z))) ◇ x
equation 31649 := x = (y ◇ ((z ◇ y) ◇ (w ◇ z))) ◇ y
equation 31650 := x = (y ◇ ((z ◇ y) ◇ (w ◇ z))) ◇ z
equation 31651 := x = (y ◇ ((z ◇ y) ◇ (w ◇ z))) ◇ w
equation 31652 := x = (y ◇ ((z ◇ y) ◇ (w ◇ z))) ◇ u
equation 31653 := x = (y ◇ ((z ◇ y) ◇ (w ◇ w))) ◇ x
equation 31654 := x = (y ◇ ((z ◇ y) ◇ (w ◇ w))) ◇ y
equation 31655 := x = (y ◇ ((z ◇ y) ◇ (w ◇ w))) ◇ z
equation 31656 := x = (y ◇ ((z ◇ y) ◇ (w ◇ w))) ◇ w
equation 31657 := x = (y ◇ ((z ◇ y) ◇ (w ◇ w))) ◇ u
equation 31658 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ x
equation 31659 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ y
equation 31660 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ z
equation 31661 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ w
equation 31662 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ u
equation 31663 := x = (y ◇ ((z ◇ y) ◇ (w ◇ u))) ◇ v
equation 31664 := x = (y ◇ ((z ◇ z) ◇ (x ◇ x))) ◇ x
equation 31665 := x = (y ◇ ((z ◇ z) ◇ (x ◇ x))) ◇ y
equation 31666 := x = (y ◇ ((z ◇ z) ◇ (x ◇ x))) ◇ z
equation 31667 := x = (y ◇ ((z ◇ z) ◇ (x ◇ x))) ◇ w
equation 31668 := x = (y ◇ ((z ◇ z) ◇ (x ◇ y))) ◇ x
equation 31669 := x = (y ◇ ((z ◇ z) ◇ (x ◇ y))) ◇ y
equation 31670 := x = (y ◇ ((z ◇ z) ◇ (x ◇ y))) ◇ z
equation 31671 := x = (y ◇ ((z ◇ z) ◇ (x ◇ y))) ◇ w
equation 31672 := x = (y ◇ ((z ◇ z) ◇ (x ◇ z))) ◇ x
equation 31673 := x = (y ◇ ((z ◇ z) ◇ (x ◇ z))) ◇ y
equation 31674 := x = (y ◇ ((z ◇ z) ◇ (x ◇ z))) ◇ z
equation 31675 := x = (y ◇ ((z ◇ z) ◇ (x ◇ z))) ◇ w
equation 31676 := x = (y ◇ ((z ◇ z) ◇ (x ◇ w))) ◇ x
equation 31677 := x = (y ◇ ((z ◇ z) ◇ (x ◇ w))) ◇ y
equation 31678 := x = (y ◇ ((z ◇ z) ◇ (x ◇ w))) ◇ z
equation 31679 := x = (y ◇ ((z ◇ z) ◇ (x ◇ w))) ◇ w
equation 31680 := x = (y ◇ ((z ◇ z) ◇ (x ◇ w))) ◇ u
equation 31681 := x = (y ◇ ((z ◇ z) ◇ (y ◇ x))) ◇ x
equation 31682 := x = (y ◇ ((z ◇ z) ◇ (y ◇ x))) ◇ y
equation 31683 := x = (y ◇ ((z ◇ z) ◇ (y ◇ x))) ◇ z
equation 31684 := x = (y ◇ ((z ◇ z) ◇ (y ◇ x))) ◇ w
equation 31685 := x = (y ◇ ((z ◇ z) ◇ (y ◇ y))) ◇ x
equation 31686 := x = (y ◇ ((z ◇ z) ◇ (y ◇ y))) ◇ y
equation 31687 := x = (y ◇ ((z ◇ z) ◇ (y ◇ y))) ◇ z
equation 31688 := x = (y ◇ ((z ◇ z) ◇ (y ◇ y))) ◇ w
equation 31689 := x = (y ◇ ((z ◇ z) ◇ (y ◇ z))) ◇ x
equation 31690 := x = (y ◇ ((z ◇ z) ◇ (y ◇ z))) ◇ y
equation 31691 := x = (y ◇ ((z ◇ z) ◇ (y ◇ z))) ◇ z
equation 31692 := x = (y ◇ ((z ◇ z) ◇ (y ◇ z))) ◇ w
equation 31693 := x = (y ◇ ((z ◇ z) ◇ (y ◇ w))) ◇ x
equation 31694 := x = (y ◇ ((z ◇ z) ◇ (y ◇ w))) ◇ y
equation 31695 := x = (y ◇ ((z ◇ z) ◇ (y ◇ w))) ◇ z
equation 31696 := x = (y ◇ ((z ◇ z) ◇ (y ◇ w))) ◇ w
equation 31697 := x = (y ◇ ((z ◇ z) ◇ (y ◇ w))) ◇ u
equation 31698 := x = (y ◇ ((z ◇ z) ◇ (z ◇ x))) ◇ x
equation 31699 := x = (y ◇ ((z ◇ z) ◇ (z ◇ x))) ◇ y
equation 31700 := x = (y ◇ ((z ◇ z) ◇ (z ◇ x))) ◇ z
equation 31701 := x = (y ◇ ((z ◇ z) ◇ (z ◇ x))) ◇ w
equation 31702 := x = (y ◇ ((z ◇ z) ◇ (z ◇ y))) ◇ x
equation 31703 := x = (y ◇ ((z ◇ z) ◇ (z ◇ y))) ◇ y
equation 31704 := x = (y ◇ ((z ◇ z) ◇ (z ◇ y))) ◇ z
equation 31705 := x = (y ◇ ((z ◇ z) ◇ (z ◇ y))) ◇ w
equation 31706 := x = (y ◇ ((z ◇ z) ◇ (z ◇ z))) ◇ x
equation 31707 := x = (y ◇ ((z ◇ z) ◇ (z ◇ z))) ◇ y
equation 31708 := x = (y ◇ ((z ◇ z) ◇ (z ◇ z))) ◇ z
equation 31709 := x = (y ◇ ((z ◇ z) ◇ (z ◇ z))) ◇ w
equation 31710 := x = (y ◇ ((z ◇ z) ◇ (z ◇ w))) ◇ x
equation 31711 := x = (y ◇ ((z ◇ z) ◇ (z ◇ w))) ◇ y
equation 31712 := x = (y ◇ ((z ◇ z) ◇ (z ◇ w))) ◇ z
equation 31713 := x = (y ◇ ((z ◇ z) ◇ (z ◇ w))) ◇ w
equation 31714 := x = (y ◇ ((z ◇ z) ◇ (z ◇ w))) ◇ u
equation 31715 := x = (y ◇ ((z ◇ z) ◇ (w ◇ x))) ◇ x
equation 31716 := x = (y ◇ ((z ◇ z) ◇ (w ◇ x))) ◇ y
equation 31717 := x = (y ◇ ((z ◇ z) ◇ (w ◇ x))) ◇ z
equation 31718 := x = (y ◇ ((z ◇ z) ◇ (w ◇ x))) ◇ w
equation 31719 := x = (y ◇ ((z ◇ z) ◇ (w ◇ x))) ◇ u
equation 31720 := x = (y ◇ ((z ◇ z) ◇ (w ◇ y))) ◇ x
equation 31721 := x = (y ◇ ((z ◇ z) ◇ (w ◇ y))) ◇ y
equation 31722 := x = (y ◇ ((z ◇ z) ◇ (w ◇ y))) ◇ z
equation 31723 := x = (y ◇ ((z ◇ z) ◇ (w ◇ y))) ◇ w
equation 31724 := x = (y ◇ ((z ◇ z) ◇ (w ◇ y))) ◇ u
equation 31725 := x = (y ◇ ((z ◇ z) ◇ (w ◇ z))) ◇ x
equation 31726 := x = (y ◇ ((z ◇ z) ◇ (w ◇ z))) ◇ y
equation 31727 := x = (y ◇ ((z ◇ z) ◇ (w ◇ z))) ◇ z
equation 31728 := x = (y ◇ ((z ◇ z) ◇ (w ◇ z))) ◇ w
equation 31729 := x = (y ◇ ((z ◇ z) ◇ (w ◇ z))) ◇ u
equation 31730 := x = (y ◇ ((z ◇ z) ◇ (w ◇ w))) ◇ x
equation 31731 := x = (y ◇ ((z ◇ z) ◇ (w ◇ w))) ◇ y
equation 31732 := x = (y ◇ ((z ◇ z) ◇ (w ◇ w))) ◇ z
equation 31733 := x = (y ◇ ((z ◇ z) ◇ (w ◇ w))) ◇ w
equation 31734 := x = (y ◇ ((z ◇ z) ◇ (w ◇ w))) ◇ u
equation 31735 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ x
equation 31736 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ y
equation 31737 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ z
equation 31738 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ w
equation 31739 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ u
equation 31740 := x = (y ◇ ((z ◇ z) ◇ (w ◇ u))) ◇ v
equation 31741 := x = (y ◇ ((z ◇ w) ◇ (x ◇ x))) ◇ x
equation 31742 := x = (y ◇ ((z ◇ w) ◇ (x ◇ x))) ◇ y
equation 31743 := x = (y ◇ ((z ◇ w) ◇ (x ◇ x))) ◇ z
equation 31744 := x = (y ◇ ((z ◇ w) ◇ (x ◇ x))) ◇ w
equation 31745 := x = (y ◇ ((z ◇ w) ◇ (x ◇ x))) ◇ u
equation 31746 := x = (y ◇ ((z ◇ w) ◇ (x ◇ y))) ◇ x
equation 31747 := x = (y ◇ ((z ◇ w) ◇ (x ◇ y))) ◇ y
equation 31748 := x = (y ◇ ((z ◇ w) ◇ (x ◇ y))) ◇ z
equation 31749 := x = (y ◇ ((z ◇ w) ◇ (x ◇ y))) ◇ w
equation 31750 := x = (y ◇ ((z ◇ w) ◇ (x ◇ y))) ◇ u
equation 31751 := x = (y ◇ ((z ◇ w) ◇ (x ◇ z))) ◇ x
equation 31752 := x = (y ◇ ((z ◇ w) ◇ (x ◇ z))) ◇ y
equation 31753 := x = (y ◇ ((z ◇ w) ◇ (x ◇ z))) ◇ z
equation 31754 := x = (y ◇ ((z ◇ w) ◇ (x ◇ z))) ◇ w
equation 31755 := x = (y ◇ ((z ◇ w) ◇ (x ◇ z))) ◇ u
equation 31756 := x = (y ◇ ((z ◇ w) ◇ (x ◇ w))) ◇ x
equation 31757 := x = (y ◇ ((z ◇ w) ◇ (x ◇ w))) ◇ y
equation 31758 := x = (y ◇ ((z ◇ w) ◇ (x ◇ w))) ◇ z
equation 31759 := x = (y ◇ ((z ◇ w) ◇ (x ◇ w))) ◇ w
equation 31760 := x = (y ◇ ((z ◇ w) ◇ (x ◇ w))) ◇ u
equation 31761 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ x
equation 31762 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ y
equation 31763 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ z
equation 31764 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ w
equation 31765 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ u
equation 31766 := x = (y ◇ ((z ◇ w) ◇ (x ◇ u))) ◇ v
equation 31767 := x = (y ◇ ((z ◇ w) ◇ (y ◇ x))) ◇ x
equation 31768 := x = (y ◇ ((z ◇ w) ◇ (y ◇ x))) ◇ y
equation 31769 := x = (y ◇ ((z ◇ w) ◇ (y ◇ x))) ◇ z
equation 31770 := x = (y ◇ ((z ◇ w) ◇ (y ◇ x))) ◇ w
equation 31771 := x = (y ◇ ((z ◇ w) ◇ (y ◇ x))) ◇ u
equation 31772 := x = (y ◇ ((z ◇ w) ◇ (y ◇ y))) ◇ x
equation 31773 := x = (y ◇ ((z ◇ w) ◇ (y ◇ y))) ◇ y
equation 31774 := x = (y ◇ ((z ◇ w) ◇ (y ◇ y))) ◇ z
equation 31775 := x = (y ◇ ((z ◇ w) ◇ (y ◇ y))) ◇ w
equation 31776 := x = (y ◇ ((z ◇ w) ◇ (y ◇ y))) ◇ u
equation 31777 := x = (y ◇ ((z ◇ w) ◇ (y ◇ z))) ◇ x
equation 31778 := x = (y ◇ ((z ◇ w) ◇ (y ◇ z))) ◇ y
equation 31779 := x = (y ◇ ((z ◇ w) ◇ (y ◇ z))) ◇ z
equation 31780 := x = (y ◇ ((z ◇ w) ◇ (y ◇ z))) ◇ w
equation 31781 := x = (y ◇ ((z ◇ w) ◇ (y ◇ z))) ◇ u
equation 31782 := x = (y ◇ ((z ◇ w) ◇ (y ◇ w))) ◇ x
equation 31783 := x = (y ◇ ((z ◇ w) ◇ (y ◇ w))) ◇ y
equation 31784 := x = (y ◇ ((z ◇ w) ◇ (y ◇ w))) ◇ z
equation 31785 := x = (y ◇ ((z ◇ w) ◇ (y ◇ w))) ◇ w
equation 31786 := x = (y ◇ ((z ◇ w) ◇ (y ◇ w))) ◇ u
equation 31787 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ x
equation 31788 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ y
equation 31789 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ z
equation 31790 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ w
equation 31791 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ u
equation 31792 := x = (y ◇ ((z ◇ w) ◇ (y ◇ u))) ◇ v
equation 31793 := x = (y ◇ ((z ◇ w) ◇ (z ◇ x))) ◇ x
equation 31794 := x = (y ◇ ((z ◇ w) ◇ (z ◇ x))) ◇ y
equation 31795 := x = (y ◇ ((z ◇ w) ◇ (z ◇ x))) ◇ z
equation 31796 := x = (y ◇ ((z ◇ w) ◇ (z ◇ x))) ◇ w
equation 31797 := x = (y ◇ ((z ◇ w) ◇ (z ◇ x))) ◇ u
equation 31798 := x = (y ◇ ((z ◇ w) ◇ (z ◇ y))) ◇ x
equation 31799 := x = (y ◇ ((z ◇ w) ◇ (z ◇ y))) ◇ y
equation 31800 := x = (y ◇ ((z ◇ w) ◇ (z ◇ y))) ◇ z
equation 31801 := x = (y ◇ ((z ◇ w) ◇ (z ◇ y))) ◇ w
equation 31802 := x = (y ◇ ((z ◇ w) ◇ (z ◇ y))) ◇ u
equation 31803 := x = (y ◇ ((z ◇ w) ◇ (z ◇ z))) ◇ x
equation 31804 := x = (y ◇ ((z ◇ w) ◇ (z ◇ z))) ◇ y
equation 31805 := x = (y ◇ ((z ◇ w) ◇ (z ◇ z))) ◇ z
equation 31806 := x = (y ◇ ((z ◇ w) ◇ (z ◇ z))) ◇ w
equation 31807 := x = (y ◇ ((z ◇ w) ◇ (z ◇ z))) ◇ u
equation 31808 := x = (y ◇ ((z ◇ w) ◇ (z ◇ w))) ◇ x
equation 31809 := x = (y ◇ ((z ◇ w) ◇ (z ◇ w))) ◇ y
equation 31810 := x = (y ◇ ((z ◇ w) ◇ (z ◇ w))) ◇ z
equation 31811 := x = (y ◇ ((z ◇ w) ◇ (z ◇ w))) ◇ w
equation 31812 := x = (y ◇ ((z ◇ w) ◇ (z ◇ w))) ◇ u
equation 31813 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ x
equation 31814 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ y
equation 31815 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ z
equation 31816 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ w
equation 31817 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ u
equation 31818 := x = (y ◇ ((z ◇ w) ◇ (z ◇ u))) ◇ v
equation 31819 := x = (y ◇ ((z ◇ w) ◇ (w ◇ x))) ◇ x
equation 31820 := x = (y ◇ ((z ◇ w) ◇ (w ◇ x))) ◇ y
equation 31821 := x = (y ◇ ((z ◇ w) ◇ (w ◇ x))) ◇ z
equation 31822 := x = (y ◇ ((z ◇ w) ◇ (w ◇ x))) ◇ w
equation 31823 := x = (y ◇ ((z ◇ w) ◇ (w ◇ x))) ◇ u
equation 31824 := x = (y ◇ ((z ◇ w) ◇ (w ◇ y))) ◇ x
equation 31825 := x = (y ◇ ((z ◇ w) ◇ (w ◇ y))) ◇ y
equation 31826 := x = (y ◇ ((z ◇ w) ◇ (w ◇ y))) ◇ z
equation 31827 := x = (y ◇ ((z ◇ w) ◇ (w ◇ y))) ◇ w
equation 31828 := x = (y ◇ ((z ◇ w) ◇ (w ◇ y))) ◇ u
equation 31829 := x = (y ◇ ((z ◇ w) ◇ (w ◇ z))) ◇ x
equation 31830 := x = (y ◇ ((z ◇ w) ◇ (w ◇ z))) ◇ y
equation 31831 := x = (y ◇ ((z ◇ w) ◇ (w ◇ z))) ◇ z
equation 31832 := x = (y ◇ ((z ◇ w) ◇ (w ◇ z))) ◇ w
equation 31833 := x = (y ◇ ((z ◇ w) ◇ (w ◇ z))) ◇ u
equation 31834 := x = (y ◇ ((z ◇ w) ◇ (w ◇ w))) ◇ x
equation 31835 := x = (y ◇ ((z ◇ w) ◇ (w ◇ w))) ◇ y
equation 31836 := x = (y ◇ ((z ◇ w) ◇ (w ◇ w))) ◇ z
equation 31837 := x = (y ◇ ((z ◇ w) ◇ (w ◇ w))) ◇ w
equation 31838 := x = (y ◇ ((z ◇ w) ◇ (w ◇ w))) ◇ u
equation 31839 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ x
equation 31840 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ y
equation 31841 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ z
equation 31842 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ w
equation 31843 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ u
equation 31844 := x = (y ◇ ((z ◇ w) ◇ (w ◇ u))) ◇ v
equation 31845 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ x
equation 31846 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ y
equation 31847 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ z
equation 31848 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ w
equation 31849 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ u
equation 31850 := x = (y ◇ ((z ◇ w) ◇ (u ◇ x))) ◇ v
equation 31851 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ x
equation 31852 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ y
equation 31853 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ z
equation 31854 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ w
equation 31855 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ u
equation 31856 := x = (y ◇ ((z ◇ w) ◇ (u ◇ y))) ◇ v
equation 31857 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ x
equation 31858 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ y
equation 31859 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ z
equation 31860 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ w
equation 31861 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ u
equation 31862 := x = (y ◇ ((z ◇ w) ◇ (u ◇ z))) ◇ v
equation 31863 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ x
equation 31864 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ y
equation 31865 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ z
equation 31866 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ w
equation 31867 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ u
equation 31868 := x = (y ◇ ((z ◇ w) ◇ (u ◇ w))) ◇ v
equation 31869 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ x
equation 31870 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ y
equation 31871 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ z
equation 31872 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ w
equation 31873 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ u
equation 31874 := x = (y ◇ ((z ◇ w) ◇ (u ◇ u))) ◇ v
equation 31875 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ x
equation 31876 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ y
equation 31877 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ z
equation 31878 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ w
equation 31879 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ u
equation 31880 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ v
equation 31881 := x = (y ◇ ((z ◇ w) ◇ (u ◇ v))) ◇ r
equation 31882 := x = (x ◇ ((x ◇ (x ◇ x)) ◇ x)) ◇ x
equation 31883 := x = (x ◇ ((x ◇ (x ◇ x)) ◇ x)) ◇ y
equation 31884 := x = (x ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ x
equation 31885 := x = (x ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ y
equation 31886 := x = (x ◇ ((x ◇ (x ◇ x)) ◇ y)) ◇ z
equation 31887 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ x
equation 31888 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ y
equation 31889 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ x)) ◇ z
equation 31890 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ x
equation 31891 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ y
equation 31892 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ y)) ◇ z
equation 31893 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ x
equation 31894 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ y
equation 31895 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ z
equation 31896 := x = (x ◇ ((x ◇ (x ◇ y)) ◇ z)) ◇ w
equation 31897 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ x
equation 31898 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ y
equation 31899 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ x)) ◇ z
equation 31900 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ x
equation 31901 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ y
equation 31902 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ y)) ◇ z
equation 31903 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ x
equation 31904 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ y
equation 31905 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ z
equation 31906 := x = (x ◇ ((x ◇ (y ◇ x)) ◇ z)) ◇ w
equation 31907 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ x
equation 31908 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ y
equation 31909 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ x)) ◇ z
equation 31910 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ x
equation 31911 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ y
equation 31912 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ y)) ◇ z
equation 31913 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ x
equation 31914 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ y
equation 31915 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ z
equation 31916 := x = (x ◇ ((x ◇ (y ◇ y)) ◇ z)) ◇ w
equation 31917 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ x
equation 31918 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ y
equation 31919 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ z
equation 31920 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ x)) ◇ w
equation 31921 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ x
equation 31922 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ y
equation 31923 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ z
equation 31924 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ y)) ◇ w
equation 31925 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ x
equation 31926 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ y
equation 31927 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ z
equation 31928 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ z)) ◇ w
equation 31929 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ x
equation 31930 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ y
equation 31931 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ z
equation 31932 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ w
equation 31933 := x = (x ◇ ((x ◇ (y ◇ z)) ◇ w)) ◇ u
equation 31934 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ x
equation 31935 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ y
equation 31936 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ x)) ◇ z
equation 31937 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ x
equation 31938 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ y
equation 31939 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ y)) ◇ z
equation 31940 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ x
equation 31941 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ y
equation 31942 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ z
equation 31943 := x = (x ◇ ((y ◇ (x ◇ x)) ◇ z)) ◇ w
equation 31944 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ x
equation 31945 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ y
equation 31946 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ x)) ◇ z
equation 31947 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ x
equation 31948 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ y
equation 31949 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ y)) ◇ z
equation 31950 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ x
equation 31951 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ y
equation 31952 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ z
equation 31953 := x = (x ◇ ((y ◇ (x ◇ y)) ◇ z)) ◇ w
equation 31954 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ x
equation 31955 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ y
equation 31956 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ z
equation 31957 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ x)) ◇ w
equation 31958 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ x
equation 31959 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ y
equation 31960 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ z
equation 31961 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ y)) ◇ w
equation 31962 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ x
equation 31963 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ y
equation 31964 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ z
equation 31965 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ z)) ◇ w
equation 31966 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ x
equation 31967 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ y
equation 31968 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ z
equation 31969 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ w
equation 31970 := x = (x ◇ ((y ◇ (x ◇ z)) ◇ w)) ◇ u
equation 31971 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ x
equation 31972 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ y
equation 31973 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ x)) ◇ z
equation 31974 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ x
equation 31975 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ y
equation 31976 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ y)) ◇ z
equation 31977 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ x
equation 31978 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ y
equation 31979 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ z
equation 31980 := x = (x ◇ ((y ◇ (y ◇ x)) ◇ z)) ◇ w
equation 31981 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ x
equation 31982 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ y
equation 31983 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ x)) ◇ z
equation 31984 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ x
equation 31985 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ y
equation 31986 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ y)) ◇ z
equation 31987 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ x
equation 31988 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ y
equation 31989 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ z
equation 31990 := x = (x ◇ ((y ◇ (y ◇ y)) ◇ z)) ◇ w
equation 31991 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ x
equation 31992 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ y
equation 31993 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ z
equation 31994 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ x)) ◇ w
equation 31995 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ x
equation 31996 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ y
equation 31997 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ z
equation 31998 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ y)) ◇ w
equation 31999 := x = (x ◇ ((y ◇ (y ◇ z)) ◇ z)) ◇ x
