import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 49000-49999 -/

equation 49000 := x ◇ y = ((y ◇ z) ◇ y) ◇ (z ◇ z)
equation 49001 := x ◇ y = ((y ◇ z) ◇ y) ◇ (z ◇ w)
equation 49002 := x ◇ y = ((y ◇ z) ◇ y) ◇ (w ◇ x)
equation 49003 := x ◇ y = ((y ◇ z) ◇ y) ◇ (w ◇ y)
equation 49004 := x ◇ y = ((y ◇ z) ◇ y) ◇ (w ◇ z)
equation 49005 := x ◇ y = ((y ◇ z) ◇ y) ◇ (w ◇ w)
equation 49006 := x ◇ y = ((y ◇ z) ◇ y) ◇ (w ◇ u)
equation 49007 := x ◇ y = ((y ◇ z) ◇ z) ◇ (x ◇ x)
equation 49008 := x ◇ y = ((y ◇ z) ◇ z) ◇ (x ◇ y)
equation 49009 := x ◇ y = ((y ◇ z) ◇ z) ◇ (x ◇ z)
equation 49010 := x ◇ y = ((y ◇ z) ◇ z) ◇ (x ◇ w)
equation 49011 := x ◇ y = ((y ◇ z) ◇ z) ◇ (y ◇ x)
equation 49012 := x ◇ y = ((y ◇ z) ◇ z) ◇ (y ◇ y)
equation 49013 := x ◇ y = ((y ◇ z) ◇ z) ◇ (y ◇ z)
equation 49014 := x ◇ y = ((y ◇ z) ◇ z) ◇ (y ◇ w)
equation 49015 := x ◇ y = ((y ◇ z) ◇ z) ◇ (z ◇ x)
equation 49016 := x ◇ y = ((y ◇ z) ◇ z) ◇ (z ◇ y)
equation 49017 := x ◇ y = ((y ◇ z) ◇ z) ◇ (z ◇ z)
equation 49018 := x ◇ y = ((y ◇ z) ◇ z) ◇ (z ◇ w)
equation 49019 := x ◇ y = ((y ◇ z) ◇ z) ◇ (w ◇ x)
equation 49020 := x ◇ y = ((y ◇ z) ◇ z) ◇ (w ◇ y)
equation 49021 := x ◇ y = ((y ◇ z) ◇ z) ◇ (w ◇ z)
equation 49022 := x ◇ y = ((y ◇ z) ◇ z) ◇ (w ◇ w)
equation 49023 := x ◇ y = ((y ◇ z) ◇ z) ◇ (w ◇ u)
equation 49024 := x ◇ y = ((y ◇ z) ◇ w) ◇ (x ◇ x)
equation 49025 := x ◇ y = ((y ◇ z) ◇ w) ◇ (x ◇ y)
equation 49026 := x ◇ y = ((y ◇ z) ◇ w) ◇ (x ◇ z)
equation 49027 := x ◇ y = ((y ◇ z) ◇ w) ◇ (x ◇ w)
equation 49028 := x ◇ y = ((y ◇ z) ◇ w) ◇ (x ◇ u)
equation 49029 := x ◇ y = ((y ◇ z) ◇ w) ◇ (y ◇ x)
equation 49030 := x ◇ y = ((y ◇ z) ◇ w) ◇ (y ◇ y)
equation 49031 := x ◇ y = ((y ◇ z) ◇ w) ◇ (y ◇ z)
equation 49032 := x ◇ y = ((y ◇ z) ◇ w) ◇ (y ◇ w)
equation 49033 := x ◇ y = ((y ◇ z) ◇ w) ◇ (y ◇ u)
equation 49034 := x ◇ y = ((y ◇ z) ◇ w) ◇ (z ◇ x)
equation 49035 := x ◇ y = ((y ◇ z) ◇ w) ◇ (z ◇ y)
equation 49036 := x ◇ y = ((y ◇ z) ◇ w) ◇ (z ◇ z)
equation 49037 := x ◇ y = ((y ◇ z) ◇ w) ◇ (z ◇ w)
equation 49038 := x ◇ y = ((y ◇ z) ◇ w) ◇ (z ◇ u)
equation 49039 := x ◇ y = ((y ◇ z) ◇ w) ◇ (w ◇ x)
equation 49040 := x ◇ y = ((y ◇ z) ◇ w) ◇ (w ◇ y)
equation 49041 := x ◇ y = ((y ◇ z) ◇ w) ◇ (w ◇ z)
equation 49042 := x ◇ y = ((y ◇ z) ◇ w) ◇ (w ◇ w)
equation 49043 := x ◇ y = ((y ◇ z) ◇ w) ◇ (w ◇ u)
equation 49044 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ x)
equation 49045 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ y)
equation 49046 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ z)
equation 49047 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ w)
equation 49048 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ u)
equation 49049 := x ◇ y = ((y ◇ z) ◇ w) ◇ (u ◇ v)
equation 49050 := x ◇ y = ((z ◇ x) ◇ x) ◇ (x ◇ x)
equation 49051 := x ◇ y = ((z ◇ x) ◇ x) ◇ (x ◇ y)
equation 49052 := x ◇ y = ((z ◇ x) ◇ x) ◇ (x ◇ z)
equation 49053 := x ◇ y = ((z ◇ x) ◇ x) ◇ (x ◇ w)
equation 49054 := x ◇ y = ((z ◇ x) ◇ x) ◇ (y ◇ x)
equation 49055 := x ◇ y = ((z ◇ x) ◇ x) ◇ (y ◇ y)
equation 49056 := x ◇ y = ((z ◇ x) ◇ x) ◇ (y ◇ z)
equation 49057 := x ◇ y = ((z ◇ x) ◇ x) ◇ (y ◇ w)
equation 49058 := x ◇ y = ((z ◇ x) ◇ x) ◇ (z ◇ x)
equation 49059 := x ◇ y = ((z ◇ x) ◇ x) ◇ (z ◇ y)
equation 49060 := x ◇ y = ((z ◇ x) ◇ x) ◇ (z ◇ z)
equation 49061 := x ◇ y = ((z ◇ x) ◇ x) ◇ (z ◇ w)
equation 49062 := x ◇ y = ((z ◇ x) ◇ x) ◇ (w ◇ x)
equation 49063 := x ◇ y = ((z ◇ x) ◇ x) ◇ (w ◇ y)
equation 49064 := x ◇ y = ((z ◇ x) ◇ x) ◇ (w ◇ z)
equation 49065 := x ◇ y = ((z ◇ x) ◇ x) ◇ (w ◇ w)
equation 49066 := x ◇ y = ((z ◇ x) ◇ x) ◇ (w ◇ u)
equation 49067 := x ◇ y = ((z ◇ x) ◇ y) ◇ (x ◇ x)
equation 49068 := x ◇ y = ((z ◇ x) ◇ y) ◇ (x ◇ y)
equation 49069 := x ◇ y = ((z ◇ x) ◇ y) ◇ (x ◇ z)
equation 49070 := x ◇ y = ((z ◇ x) ◇ y) ◇ (x ◇ w)
equation 49071 := x ◇ y = ((z ◇ x) ◇ y) ◇ (y ◇ x)
equation 49072 := x ◇ y = ((z ◇ x) ◇ y) ◇ (y ◇ y)
equation 49073 := x ◇ y = ((z ◇ x) ◇ y) ◇ (y ◇ z)
equation 49074 := x ◇ y = ((z ◇ x) ◇ y) ◇ (y ◇ w)
equation 49075 := x ◇ y = ((z ◇ x) ◇ y) ◇ (z ◇ x)
equation 49076 := x ◇ y = ((z ◇ x) ◇ y) ◇ (z ◇ y)
equation 49077 := x ◇ y = ((z ◇ x) ◇ y) ◇ (z ◇ z)
equation 49078 := x ◇ y = ((z ◇ x) ◇ y) ◇ (z ◇ w)
equation 49079 := x ◇ y = ((z ◇ x) ◇ y) ◇ (w ◇ x)
equation 49080 := x ◇ y = ((z ◇ x) ◇ y) ◇ (w ◇ y)
equation 49081 := x ◇ y = ((z ◇ x) ◇ y) ◇ (w ◇ z)
equation 49082 := x ◇ y = ((z ◇ x) ◇ y) ◇ (w ◇ w)
equation 49083 := x ◇ y = ((z ◇ x) ◇ y) ◇ (w ◇ u)
equation 49084 := x ◇ y = ((z ◇ x) ◇ z) ◇ (x ◇ x)
equation 49085 := x ◇ y = ((z ◇ x) ◇ z) ◇ (x ◇ y)
equation 49086 := x ◇ y = ((z ◇ x) ◇ z) ◇ (x ◇ z)
equation 49087 := x ◇ y = ((z ◇ x) ◇ z) ◇ (x ◇ w)
equation 49088 := x ◇ y = ((z ◇ x) ◇ z) ◇ (y ◇ x)
equation 49089 := x ◇ y = ((z ◇ x) ◇ z) ◇ (y ◇ y)
equation 49090 := x ◇ y = ((z ◇ x) ◇ z) ◇ (y ◇ z)
equation 49091 := x ◇ y = ((z ◇ x) ◇ z) ◇ (y ◇ w)
equation 49092 := x ◇ y = ((z ◇ x) ◇ z) ◇ (z ◇ x)
equation 49093 := x ◇ y = ((z ◇ x) ◇ z) ◇ (z ◇ y)
equation 49094 := x ◇ y = ((z ◇ x) ◇ z) ◇ (z ◇ z)
equation 49095 := x ◇ y = ((z ◇ x) ◇ z) ◇ (z ◇ w)
equation 49096 := x ◇ y = ((z ◇ x) ◇ z) ◇ (w ◇ x)
equation 49097 := x ◇ y = ((z ◇ x) ◇ z) ◇ (w ◇ y)
equation 49098 := x ◇ y = ((z ◇ x) ◇ z) ◇ (w ◇ z)
equation 49099 := x ◇ y = ((z ◇ x) ◇ z) ◇ (w ◇ w)
equation 49100 := x ◇ y = ((z ◇ x) ◇ z) ◇ (w ◇ u)
equation 49101 := x ◇ y = ((z ◇ x) ◇ w) ◇ (x ◇ x)
equation 49102 := x ◇ y = ((z ◇ x) ◇ w) ◇ (x ◇ y)
equation 49103 := x ◇ y = ((z ◇ x) ◇ w) ◇ (x ◇ z)
equation 49104 := x ◇ y = ((z ◇ x) ◇ w) ◇ (x ◇ w)
equation 49105 := x ◇ y = ((z ◇ x) ◇ w) ◇ (x ◇ u)
equation 49106 := x ◇ y = ((z ◇ x) ◇ w) ◇ (y ◇ x)
equation 49107 := x ◇ y = ((z ◇ x) ◇ w) ◇ (y ◇ y)
equation 49108 := x ◇ y = ((z ◇ x) ◇ w) ◇ (y ◇ z)
equation 49109 := x ◇ y = ((z ◇ x) ◇ w) ◇ (y ◇ w)
equation 49110 := x ◇ y = ((z ◇ x) ◇ w) ◇ (y ◇ u)
equation 49111 := x ◇ y = ((z ◇ x) ◇ w) ◇ (z ◇ x)
equation 49112 := x ◇ y = ((z ◇ x) ◇ w) ◇ (z ◇ y)
equation 49113 := x ◇ y = ((z ◇ x) ◇ w) ◇ (z ◇ z)
equation 49114 := x ◇ y = ((z ◇ x) ◇ w) ◇ (z ◇ w)
equation 49115 := x ◇ y = ((z ◇ x) ◇ w) ◇ (z ◇ u)
equation 49116 := x ◇ y = ((z ◇ x) ◇ w) ◇ (w ◇ x)
equation 49117 := x ◇ y = ((z ◇ x) ◇ w) ◇ (w ◇ y)
equation 49118 := x ◇ y = ((z ◇ x) ◇ w) ◇ (w ◇ z)
equation 49119 := x ◇ y = ((z ◇ x) ◇ w) ◇ (w ◇ w)
equation 49120 := x ◇ y = ((z ◇ x) ◇ w) ◇ (w ◇ u)
equation 49121 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ x)
equation 49122 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ y)
equation 49123 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ z)
equation 49124 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ w)
equation 49125 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ u)
equation 49126 := x ◇ y = ((z ◇ x) ◇ w) ◇ (u ◇ v)
equation 49127 := x ◇ y = ((z ◇ y) ◇ x) ◇ (x ◇ x)
equation 49128 := x ◇ y = ((z ◇ y) ◇ x) ◇ (x ◇ y)
equation 49129 := x ◇ y = ((z ◇ y) ◇ x) ◇ (x ◇ z)
equation 49130 := x ◇ y = ((z ◇ y) ◇ x) ◇ (x ◇ w)
equation 49131 := x ◇ y = ((z ◇ y) ◇ x) ◇ (y ◇ x)
equation 49132 := x ◇ y = ((z ◇ y) ◇ x) ◇ (y ◇ y)
equation 49133 := x ◇ y = ((z ◇ y) ◇ x) ◇ (y ◇ z)
equation 49134 := x ◇ y = ((z ◇ y) ◇ x) ◇ (y ◇ w)
equation 49135 := x ◇ y = ((z ◇ y) ◇ x) ◇ (z ◇ x)
equation 49136 := x ◇ y = ((z ◇ y) ◇ x) ◇ (z ◇ y)
equation 49137 := x ◇ y = ((z ◇ y) ◇ x) ◇ (z ◇ z)
equation 49138 := x ◇ y = ((z ◇ y) ◇ x) ◇ (z ◇ w)
equation 49139 := x ◇ y = ((z ◇ y) ◇ x) ◇ (w ◇ x)
equation 49140 := x ◇ y = ((z ◇ y) ◇ x) ◇ (w ◇ y)
equation 49141 := x ◇ y = ((z ◇ y) ◇ x) ◇ (w ◇ z)
equation 49142 := x ◇ y = ((z ◇ y) ◇ x) ◇ (w ◇ w)
equation 49143 := x ◇ y = ((z ◇ y) ◇ x) ◇ (w ◇ u)
equation 49144 := x ◇ y = ((z ◇ y) ◇ y) ◇ (x ◇ x)
equation 49145 := x ◇ y = ((z ◇ y) ◇ y) ◇ (x ◇ y)
equation 49146 := x ◇ y = ((z ◇ y) ◇ y) ◇ (x ◇ z)
equation 49147 := x ◇ y = ((z ◇ y) ◇ y) ◇ (x ◇ w)
equation 49148 := x ◇ y = ((z ◇ y) ◇ y) ◇ (y ◇ x)
equation 49149 := x ◇ y = ((z ◇ y) ◇ y) ◇ (y ◇ y)
equation 49150 := x ◇ y = ((z ◇ y) ◇ y) ◇ (y ◇ z)
equation 49151 := x ◇ y = ((z ◇ y) ◇ y) ◇ (y ◇ w)
equation 49152 := x ◇ y = ((z ◇ y) ◇ y) ◇ (z ◇ x)
equation 49153 := x ◇ y = ((z ◇ y) ◇ y) ◇ (z ◇ y)
equation 49154 := x ◇ y = ((z ◇ y) ◇ y) ◇ (z ◇ z)
equation 49155 := x ◇ y = ((z ◇ y) ◇ y) ◇ (z ◇ w)
equation 49156 := x ◇ y = ((z ◇ y) ◇ y) ◇ (w ◇ x)
equation 49157 := x ◇ y = ((z ◇ y) ◇ y) ◇ (w ◇ y)
equation 49158 := x ◇ y = ((z ◇ y) ◇ y) ◇ (w ◇ z)
equation 49159 := x ◇ y = ((z ◇ y) ◇ y) ◇ (w ◇ w)
equation 49160 := x ◇ y = ((z ◇ y) ◇ y) ◇ (w ◇ u)
equation 49161 := x ◇ y = ((z ◇ y) ◇ z) ◇ (x ◇ x)
equation 49162 := x ◇ y = ((z ◇ y) ◇ z) ◇ (x ◇ y)
equation 49163 := x ◇ y = ((z ◇ y) ◇ z) ◇ (x ◇ z)
equation 49164 := x ◇ y = ((z ◇ y) ◇ z) ◇ (x ◇ w)
equation 49165 := x ◇ y = ((z ◇ y) ◇ z) ◇ (y ◇ x)
equation 49166 := x ◇ y = ((z ◇ y) ◇ z) ◇ (y ◇ y)
equation 49167 := x ◇ y = ((z ◇ y) ◇ z) ◇ (y ◇ z)
equation 49168 := x ◇ y = ((z ◇ y) ◇ z) ◇ (y ◇ w)
equation 49169 := x ◇ y = ((z ◇ y) ◇ z) ◇ (z ◇ x)
equation 49170 := x ◇ y = ((z ◇ y) ◇ z) ◇ (z ◇ y)
equation 49171 := x ◇ y = ((z ◇ y) ◇ z) ◇ (z ◇ z)
equation 49172 := x ◇ y = ((z ◇ y) ◇ z) ◇ (z ◇ w)
equation 49173 := x ◇ y = ((z ◇ y) ◇ z) ◇ (w ◇ x)
equation 49174 := x ◇ y = ((z ◇ y) ◇ z) ◇ (w ◇ y)
equation 49175 := x ◇ y = ((z ◇ y) ◇ z) ◇ (w ◇ z)
equation 49176 := x ◇ y = ((z ◇ y) ◇ z) ◇ (w ◇ w)
equation 49177 := x ◇ y = ((z ◇ y) ◇ z) ◇ (w ◇ u)
equation 49178 := x ◇ y = ((z ◇ y) ◇ w) ◇ (x ◇ x)
equation 49179 := x ◇ y = ((z ◇ y) ◇ w) ◇ (x ◇ y)
equation 49180 := x ◇ y = ((z ◇ y) ◇ w) ◇ (x ◇ z)
equation 49181 := x ◇ y = ((z ◇ y) ◇ w) ◇ (x ◇ w)
equation 49182 := x ◇ y = ((z ◇ y) ◇ w) ◇ (x ◇ u)
equation 49183 := x ◇ y = ((z ◇ y) ◇ w) ◇ (y ◇ x)
equation 49184 := x ◇ y = ((z ◇ y) ◇ w) ◇ (y ◇ y)
equation 49185 := x ◇ y = ((z ◇ y) ◇ w) ◇ (y ◇ z)
equation 49186 := x ◇ y = ((z ◇ y) ◇ w) ◇ (y ◇ w)
equation 49187 := x ◇ y = ((z ◇ y) ◇ w) ◇ (y ◇ u)
equation 49188 := x ◇ y = ((z ◇ y) ◇ w) ◇ (z ◇ x)
equation 49189 := x ◇ y = ((z ◇ y) ◇ w) ◇ (z ◇ y)
equation 49190 := x ◇ y = ((z ◇ y) ◇ w) ◇ (z ◇ z)
equation 49191 := x ◇ y = ((z ◇ y) ◇ w) ◇ (z ◇ w)
equation 49192 := x ◇ y = ((z ◇ y) ◇ w) ◇ (z ◇ u)
equation 49193 := x ◇ y = ((z ◇ y) ◇ w) ◇ (w ◇ x)
equation 49194 := x ◇ y = ((z ◇ y) ◇ w) ◇ (w ◇ y)
equation 49195 := x ◇ y = ((z ◇ y) ◇ w) ◇ (w ◇ z)
equation 49196 := x ◇ y = ((z ◇ y) ◇ w) ◇ (w ◇ w)
equation 49197 := x ◇ y = ((z ◇ y) ◇ w) ◇ (w ◇ u)
equation 49198 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ x)
equation 49199 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ y)
equation 49200 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ z)
equation 49201 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ w)
equation 49202 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ u)
equation 49203 := x ◇ y = ((z ◇ y) ◇ w) ◇ (u ◇ v)
equation 49204 := x ◇ y = ((z ◇ z) ◇ x) ◇ (x ◇ x)
equation 49205 := x ◇ y = ((z ◇ z) ◇ x) ◇ (x ◇ y)
equation 49206 := x ◇ y = ((z ◇ z) ◇ x) ◇ (x ◇ z)
equation 49207 := x ◇ y = ((z ◇ z) ◇ x) ◇ (x ◇ w)
equation 49208 := x ◇ y = ((z ◇ z) ◇ x) ◇ (y ◇ x)
equation 49209 := x ◇ y = ((z ◇ z) ◇ x) ◇ (y ◇ y)
equation 49210 := x ◇ y = ((z ◇ z) ◇ x) ◇ (y ◇ z)
equation 49211 := x ◇ y = ((z ◇ z) ◇ x) ◇ (y ◇ w)
equation 49212 := x ◇ y = ((z ◇ z) ◇ x) ◇ (z ◇ x)
equation 49213 := x ◇ y = ((z ◇ z) ◇ x) ◇ (z ◇ y)
equation 49214 := x ◇ y = ((z ◇ z) ◇ x) ◇ (z ◇ z)
equation 49215 := x ◇ y = ((z ◇ z) ◇ x) ◇ (z ◇ w)
equation 49216 := x ◇ y = ((z ◇ z) ◇ x) ◇ (w ◇ x)
equation 49217 := x ◇ y = ((z ◇ z) ◇ x) ◇ (w ◇ y)
equation 49218 := x ◇ y = ((z ◇ z) ◇ x) ◇ (w ◇ z)
equation 49219 := x ◇ y = ((z ◇ z) ◇ x) ◇ (w ◇ w)
equation 49220 := x ◇ y = ((z ◇ z) ◇ x) ◇ (w ◇ u)
equation 49221 := x ◇ y = ((z ◇ z) ◇ y) ◇ (x ◇ x)
equation 49222 := x ◇ y = ((z ◇ z) ◇ y) ◇ (x ◇ y)
equation 49223 := x ◇ y = ((z ◇ z) ◇ y) ◇ (x ◇ z)
equation 49224 := x ◇ y = ((z ◇ z) ◇ y) ◇ (x ◇ w)
equation 49225 := x ◇ y = ((z ◇ z) ◇ y) ◇ (y ◇ x)
equation 49226 := x ◇ y = ((z ◇ z) ◇ y) ◇ (y ◇ y)
equation 49227 := x ◇ y = ((z ◇ z) ◇ y) ◇ (y ◇ z)
equation 49228 := x ◇ y = ((z ◇ z) ◇ y) ◇ (y ◇ w)
equation 49229 := x ◇ y = ((z ◇ z) ◇ y) ◇ (z ◇ x)
equation 49230 := x ◇ y = ((z ◇ z) ◇ y) ◇ (z ◇ y)
equation 49231 := x ◇ y = ((z ◇ z) ◇ y) ◇ (z ◇ z)
equation 49232 := x ◇ y = ((z ◇ z) ◇ y) ◇ (z ◇ w)
equation 49233 := x ◇ y = ((z ◇ z) ◇ y) ◇ (w ◇ x)
equation 49234 := x ◇ y = ((z ◇ z) ◇ y) ◇ (w ◇ y)
equation 49235 := x ◇ y = ((z ◇ z) ◇ y) ◇ (w ◇ z)
equation 49236 := x ◇ y = ((z ◇ z) ◇ y) ◇ (w ◇ w)
equation 49237 := x ◇ y = ((z ◇ z) ◇ y) ◇ (w ◇ u)
equation 49238 := x ◇ y = ((z ◇ z) ◇ z) ◇ (x ◇ x)
equation 49239 := x ◇ y = ((z ◇ z) ◇ z) ◇ (x ◇ y)
equation 49240 := x ◇ y = ((z ◇ z) ◇ z) ◇ (x ◇ z)
equation 49241 := x ◇ y = ((z ◇ z) ◇ z) ◇ (x ◇ w)
equation 49242 := x ◇ y = ((z ◇ z) ◇ z) ◇ (y ◇ x)
equation 49243 := x ◇ y = ((z ◇ z) ◇ z) ◇ (y ◇ y)
equation 49244 := x ◇ y = ((z ◇ z) ◇ z) ◇ (y ◇ z)
equation 49245 := x ◇ y = ((z ◇ z) ◇ z) ◇ (y ◇ w)
equation 49246 := x ◇ y = ((z ◇ z) ◇ z) ◇ (z ◇ x)
equation 49247 := x ◇ y = ((z ◇ z) ◇ z) ◇ (z ◇ y)
equation 49248 := x ◇ y = ((z ◇ z) ◇ z) ◇ (z ◇ z)
equation 49249 := x ◇ y = ((z ◇ z) ◇ z) ◇ (z ◇ w)
equation 49250 := x ◇ y = ((z ◇ z) ◇ z) ◇ (w ◇ x)
equation 49251 := x ◇ y = ((z ◇ z) ◇ z) ◇ (w ◇ y)
equation 49252 := x ◇ y = ((z ◇ z) ◇ z) ◇ (w ◇ z)
equation 49253 := x ◇ y = ((z ◇ z) ◇ z) ◇ (w ◇ w)
equation 49254 := x ◇ y = ((z ◇ z) ◇ z) ◇ (w ◇ u)
equation 49255 := x ◇ y = ((z ◇ z) ◇ w) ◇ (x ◇ x)
equation 49256 := x ◇ y = ((z ◇ z) ◇ w) ◇ (x ◇ y)
equation 49257 := x ◇ y = ((z ◇ z) ◇ w) ◇ (x ◇ z)
equation 49258 := x ◇ y = ((z ◇ z) ◇ w) ◇ (x ◇ w)
equation 49259 := x ◇ y = ((z ◇ z) ◇ w) ◇ (x ◇ u)
equation 49260 := x ◇ y = ((z ◇ z) ◇ w) ◇ (y ◇ x)
equation 49261 := x ◇ y = ((z ◇ z) ◇ w) ◇ (y ◇ y)
equation 49262 := x ◇ y = ((z ◇ z) ◇ w) ◇ (y ◇ z)
equation 49263 := x ◇ y = ((z ◇ z) ◇ w) ◇ (y ◇ w)
equation 49264 := x ◇ y = ((z ◇ z) ◇ w) ◇ (y ◇ u)
equation 49265 := x ◇ y = ((z ◇ z) ◇ w) ◇ (z ◇ x)
equation 49266 := x ◇ y = ((z ◇ z) ◇ w) ◇ (z ◇ y)
equation 49267 := x ◇ y = ((z ◇ z) ◇ w) ◇ (z ◇ z)
equation 49268 := x ◇ y = ((z ◇ z) ◇ w) ◇ (z ◇ w)
equation 49269 := x ◇ y = ((z ◇ z) ◇ w) ◇ (z ◇ u)
equation 49270 := x ◇ y = ((z ◇ z) ◇ w) ◇ (w ◇ x)
equation 49271 := x ◇ y = ((z ◇ z) ◇ w) ◇ (w ◇ y)
equation 49272 := x ◇ y = ((z ◇ z) ◇ w) ◇ (w ◇ z)
equation 49273 := x ◇ y = ((z ◇ z) ◇ w) ◇ (w ◇ w)
equation 49274 := x ◇ y = ((z ◇ z) ◇ w) ◇ (w ◇ u)
equation 49275 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ x)
equation 49276 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ y)
equation 49277 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ z)
equation 49278 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ w)
equation 49279 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ u)
equation 49280 := x ◇ y = ((z ◇ z) ◇ w) ◇ (u ◇ v)
equation 49281 := x ◇ y = ((z ◇ w) ◇ x) ◇ (x ◇ x)
equation 49282 := x ◇ y = ((z ◇ w) ◇ x) ◇ (x ◇ y)
equation 49283 := x ◇ y = ((z ◇ w) ◇ x) ◇ (x ◇ z)
equation 49284 := x ◇ y = ((z ◇ w) ◇ x) ◇ (x ◇ w)
equation 49285 := x ◇ y = ((z ◇ w) ◇ x) ◇ (x ◇ u)
equation 49286 := x ◇ y = ((z ◇ w) ◇ x) ◇ (y ◇ x)
equation 49287 := x ◇ y = ((z ◇ w) ◇ x) ◇ (y ◇ y)
equation 49288 := x ◇ y = ((z ◇ w) ◇ x) ◇ (y ◇ z)
equation 49289 := x ◇ y = ((z ◇ w) ◇ x) ◇ (y ◇ w)
equation 49290 := x ◇ y = ((z ◇ w) ◇ x) ◇ (y ◇ u)
equation 49291 := x ◇ y = ((z ◇ w) ◇ x) ◇ (z ◇ x)
equation 49292 := x ◇ y = ((z ◇ w) ◇ x) ◇ (z ◇ y)
equation 49293 := x ◇ y = ((z ◇ w) ◇ x) ◇ (z ◇ z)
equation 49294 := x ◇ y = ((z ◇ w) ◇ x) ◇ (z ◇ w)
equation 49295 := x ◇ y = ((z ◇ w) ◇ x) ◇ (z ◇ u)
equation 49296 := x ◇ y = ((z ◇ w) ◇ x) ◇ (w ◇ x)
equation 49297 := x ◇ y = ((z ◇ w) ◇ x) ◇ (w ◇ y)
equation 49298 := x ◇ y = ((z ◇ w) ◇ x) ◇ (w ◇ z)
equation 49299 := x ◇ y = ((z ◇ w) ◇ x) ◇ (w ◇ w)
equation 49300 := x ◇ y = ((z ◇ w) ◇ x) ◇ (w ◇ u)
equation 49301 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ x)
equation 49302 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ y)
equation 49303 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ z)
equation 49304 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ w)
equation 49305 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ u)
equation 49306 := x ◇ y = ((z ◇ w) ◇ x) ◇ (u ◇ v)
equation 49307 := x ◇ y = ((z ◇ w) ◇ y) ◇ (x ◇ x)
equation 49308 := x ◇ y = ((z ◇ w) ◇ y) ◇ (x ◇ y)
equation 49309 := x ◇ y = ((z ◇ w) ◇ y) ◇ (x ◇ z)
equation 49310 := x ◇ y = ((z ◇ w) ◇ y) ◇ (x ◇ w)
equation 49311 := x ◇ y = ((z ◇ w) ◇ y) ◇ (x ◇ u)
equation 49312 := x ◇ y = ((z ◇ w) ◇ y) ◇ (y ◇ x)
equation 49313 := x ◇ y = ((z ◇ w) ◇ y) ◇ (y ◇ y)
equation 49314 := x ◇ y = ((z ◇ w) ◇ y) ◇ (y ◇ z)
equation 49315 := x ◇ y = ((z ◇ w) ◇ y) ◇ (y ◇ w)
equation 49316 := x ◇ y = ((z ◇ w) ◇ y) ◇ (y ◇ u)
equation 49317 := x ◇ y = ((z ◇ w) ◇ y) ◇ (z ◇ x)
equation 49318 := x ◇ y = ((z ◇ w) ◇ y) ◇ (z ◇ y)
equation 49319 := x ◇ y = ((z ◇ w) ◇ y) ◇ (z ◇ z)
equation 49320 := x ◇ y = ((z ◇ w) ◇ y) ◇ (z ◇ w)
equation 49321 := x ◇ y = ((z ◇ w) ◇ y) ◇ (z ◇ u)
equation 49322 := x ◇ y = ((z ◇ w) ◇ y) ◇ (w ◇ x)
equation 49323 := x ◇ y = ((z ◇ w) ◇ y) ◇ (w ◇ y)
equation 49324 := x ◇ y = ((z ◇ w) ◇ y) ◇ (w ◇ z)
equation 49325 := x ◇ y = ((z ◇ w) ◇ y) ◇ (w ◇ w)
equation 49326 := x ◇ y = ((z ◇ w) ◇ y) ◇ (w ◇ u)
equation 49327 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ x)
equation 49328 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ y)
equation 49329 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ z)
equation 49330 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ w)
equation 49331 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ u)
equation 49332 := x ◇ y = ((z ◇ w) ◇ y) ◇ (u ◇ v)
equation 49333 := x ◇ y = ((z ◇ w) ◇ z) ◇ (x ◇ x)
equation 49334 := x ◇ y = ((z ◇ w) ◇ z) ◇ (x ◇ y)
equation 49335 := x ◇ y = ((z ◇ w) ◇ z) ◇ (x ◇ z)
equation 49336 := x ◇ y = ((z ◇ w) ◇ z) ◇ (x ◇ w)
equation 49337 := x ◇ y = ((z ◇ w) ◇ z) ◇ (x ◇ u)
equation 49338 := x ◇ y = ((z ◇ w) ◇ z) ◇ (y ◇ x)
equation 49339 := x ◇ y = ((z ◇ w) ◇ z) ◇ (y ◇ y)
equation 49340 := x ◇ y = ((z ◇ w) ◇ z) ◇ (y ◇ z)
equation 49341 := x ◇ y = ((z ◇ w) ◇ z) ◇ (y ◇ w)
equation 49342 := x ◇ y = ((z ◇ w) ◇ z) ◇ (y ◇ u)
equation 49343 := x ◇ y = ((z ◇ w) ◇ z) ◇ (z ◇ x)
equation 49344 := x ◇ y = ((z ◇ w) ◇ z) ◇ (z ◇ y)
equation 49345 := x ◇ y = ((z ◇ w) ◇ z) ◇ (z ◇ z)
equation 49346 := x ◇ y = ((z ◇ w) ◇ z) ◇ (z ◇ w)
equation 49347 := x ◇ y = ((z ◇ w) ◇ z) ◇ (z ◇ u)
equation 49348 := x ◇ y = ((z ◇ w) ◇ z) ◇ (w ◇ x)
equation 49349 := x ◇ y = ((z ◇ w) ◇ z) ◇ (w ◇ y)
equation 49350 := x ◇ y = ((z ◇ w) ◇ z) ◇ (w ◇ z)
equation 49351 := x ◇ y = ((z ◇ w) ◇ z) ◇ (w ◇ w)
equation 49352 := x ◇ y = ((z ◇ w) ◇ z) ◇ (w ◇ u)
equation 49353 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ x)
equation 49354 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ y)
equation 49355 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ z)
equation 49356 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ w)
equation 49357 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ u)
equation 49358 := x ◇ y = ((z ◇ w) ◇ z) ◇ (u ◇ v)
equation 49359 := x ◇ y = ((z ◇ w) ◇ w) ◇ (x ◇ x)
equation 49360 := x ◇ y = ((z ◇ w) ◇ w) ◇ (x ◇ y)
equation 49361 := x ◇ y = ((z ◇ w) ◇ w) ◇ (x ◇ z)
equation 49362 := x ◇ y = ((z ◇ w) ◇ w) ◇ (x ◇ w)
equation 49363 := x ◇ y = ((z ◇ w) ◇ w) ◇ (x ◇ u)
equation 49364 := x ◇ y = ((z ◇ w) ◇ w) ◇ (y ◇ x)
equation 49365 := x ◇ y = ((z ◇ w) ◇ w) ◇ (y ◇ y)
equation 49366 := x ◇ y = ((z ◇ w) ◇ w) ◇ (y ◇ z)
equation 49367 := x ◇ y = ((z ◇ w) ◇ w) ◇ (y ◇ w)
equation 49368 := x ◇ y = ((z ◇ w) ◇ w) ◇ (y ◇ u)
equation 49369 := x ◇ y = ((z ◇ w) ◇ w) ◇ (z ◇ x)
equation 49370 := x ◇ y = ((z ◇ w) ◇ w) ◇ (z ◇ y)
equation 49371 := x ◇ y = ((z ◇ w) ◇ w) ◇ (z ◇ z)
equation 49372 := x ◇ y = ((z ◇ w) ◇ w) ◇ (z ◇ w)
equation 49373 := x ◇ y = ((z ◇ w) ◇ w) ◇ (z ◇ u)
equation 49374 := x ◇ y = ((z ◇ w) ◇ w) ◇ (w ◇ x)
equation 49375 := x ◇ y = ((z ◇ w) ◇ w) ◇ (w ◇ y)
equation 49376 := x ◇ y = ((z ◇ w) ◇ w) ◇ (w ◇ z)
equation 49377 := x ◇ y = ((z ◇ w) ◇ w) ◇ (w ◇ w)
equation 49378 := x ◇ y = ((z ◇ w) ◇ w) ◇ (w ◇ u)
equation 49379 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ x)
equation 49380 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ y)
equation 49381 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ z)
equation 49382 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ w)
equation 49383 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ u)
equation 49384 := x ◇ y = ((z ◇ w) ◇ w) ◇ (u ◇ v)
equation 49385 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ x)
equation 49386 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ y)
equation 49387 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ z)
equation 49388 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ w)
equation 49389 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ u)
equation 49390 := x ◇ y = ((z ◇ w) ◇ u) ◇ (x ◇ v)
equation 49391 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ x)
equation 49392 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ y)
equation 49393 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ z)
equation 49394 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ w)
equation 49395 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ u)
equation 49396 := x ◇ y = ((z ◇ w) ◇ u) ◇ (y ◇ v)
equation 49397 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ x)
equation 49398 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ y)
equation 49399 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ z)
equation 49400 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ w)
equation 49401 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ u)
equation 49402 := x ◇ y = ((z ◇ w) ◇ u) ◇ (z ◇ v)
equation 49403 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ x)
equation 49404 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ y)
equation 49405 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ z)
equation 49406 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ w)
equation 49407 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ u)
equation 49408 := x ◇ y = ((z ◇ w) ◇ u) ◇ (w ◇ v)
equation 49409 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ x)
equation 49410 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ y)
equation 49411 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ z)
equation 49412 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ w)
equation 49413 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ u)
equation 49414 := x ◇ y = ((z ◇ w) ◇ u) ◇ (u ◇ v)
equation 49415 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ x)
equation 49416 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ y)
equation 49417 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ z)
equation 49418 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ w)
equation 49419 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ u)
equation 49420 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ v)
equation 49421 := x ◇ y = ((z ◇ w) ◇ u) ◇ (v ◇ r)
equation 49422 := x ◇ x = (x ◇ (x ◇ (x ◇ x))) ◇ x
equation 49423 := x ◇ x = (x ◇ (x ◇ (x ◇ x))) ◇ y
equation 49424 := x ◇ x = (x ◇ (x ◇ (x ◇ y))) ◇ x
equation 49425 := x ◇ x = (x ◇ (x ◇ (x ◇ y))) ◇ y
equation 49426 := x ◇ x = (x ◇ (x ◇ (x ◇ y))) ◇ z
equation 49427 := x ◇ x = (x ◇ (x ◇ (y ◇ x))) ◇ x
equation 49428 := x ◇ x = (x ◇ (x ◇ (y ◇ x))) ◇ y
equation 49429 := x ◇ x = (x ◇ (x ◇ (y ◇ x))) ◇ z
equation 49430 := x ◇ x = (x ◇ (x ◇ (y ◇ y))) ◇ x
equation 49431 := x ◇ x = (x ◇ (x ◇ (y ◇ y))) ◇ y
equation 49432 := x ◇ x = (x ◇ (x ◇ (y ◇ y))) ◇ z
equation 49433 := x ◇ x = (x ◇ (x ◇ (y ◇ z))) ◇ x
equation 49434 := x ◇ x = (x ◇ (x ◇ (y ◇ z))) ◇ y
equation 49435 := x ◇ x = (x ◇ (x ◇ (y ◇ z))) ◇ z
equation 49436 := x ◇ x = (x ◇ (x ◇ (y ◇ z))) ◇ w
equation 49437 := x ◇ x = (x ◇ (y ◇ (x ◇ x))) ◇ x
equation 49438 := x ◇ x = (x ◇ (y ◇ (x ◇ x))) ◇ y
equation 49439 := x ◇ x = (x ◇ (y ◇ (x ◇ x))) ◇ z
equation 49440 := x ◇ x = (x ◇ (y ◇ (x ◇ y))) ◇ x
equation 49441 := x ◇ x = (x ◇ (y ◇ (x ◇ y))) ◇ y
equation 49442 := x ◇ x = (x ◇ (y ◇ (x ◇ y))) ◇ z
equation 49443 := x ◇ x = (x ◇ (y ◇ (x ◇ z))) ◇ x
equation 49444 := x ◇ x = (x ◇ (y ◇ (x ◇ z))) ◇ y
equation 49445 := x ◇ x = (x ◇ (y ◇ (x ◇ z))) ◇ z
equation 49446 := x ◇ x = (x ◇ (y ◇ (x ◇ z))) ◇ w
equation 49447 := x ◇ x = (x ◇ (y ◇ (y ◇ x))) ◇ x
equation 49448 := x ◇ x = (x ◇ (y ◇ (y ◇ x))) ◇ y
equation 49449 := x ◇ x = (x ◇ (y ◇ (y ◇ x))) ◇ z
equation 49450 := x ◇ x = (x ◇ (y ◇ (y ◇ y))) ◇ x
equation 49451 := x ◇ x = (x ◇ (y ◇ (y ◇ y))) ◇ y
equation 49452 := x ◇ x = (x ◇ (y ◇ (y ◇ y))) ◇ z
equation 49453 := x ◇ x = (x ◇ (y ◇ (y ◇ z))) ◇ x
equation 49454 := x ◇ x = (x ◇ (y ◇ (y ◇ z))) ◇ y
equation 49455 := x ◇ x = (x ◇ (y ◇ (y ◇ z))) ◇ z
equation 49456 := x ◇ x = (x ◇ (y ◇ (y ◇ z))) ◇ w
equation 49457 := x ◇ x = (x ◇ (y ◇ (z ◇ x))) ◇ x
equation 49458 := x ◇ x = (x ◇ (y ◇ (z ◇ x))) ◇ y
equation 49459 := x ◇ x = (x ◇ (y ◇ (z ◇ x))) ◇ z
equation 49460 := x ◇ x = (x ◇ (y ◇ (z ◇ x))) ◇ w
equation 49461 := x ◇ x = (x ◇ (y ◇ (z ◇ y))) ◇ x
equation 49462 := x ◇ x = (x ◇ (y ◇ (z ◇ y))) ◇ y
equation 49463 := x ◇ x = (x ◇ (y ◇ (z ◇ y))) ◇ z
equation 49464 := x ◇ x = (x ◇ (y ◇ (z ◇ y))) ◇ w
equation 49465 := x ◇ x = (x ◇ (y ◇ (z ◇ z))) ◇ x
equation 49466 := x ◇ x = (x ◇ (y ◇ (z ◇ z))) ◇ y
equation 49467 := x ◇ x = (x ◇ (y ◇ (z ◇ z))) ◇ z
equation 49468 := x ◇ x = (x ◇ (y ◇ (z ◇ z))) ◇ w
equation 49469 := x ◇ x = (x ◇ (y ◇ (z ◇ w))) ◇ x
equation 49470 := x ◇ x = (x ◇ (y ◇ (z ◇ w))) ◇ y
equation 49471 := x ◇ x = (x ◇ (y ◇ (z ◇ w))) ◇ z
equation 49472 := x ◇ x = (x ◇ (y ◇ (z ◇ w))) ◇ w
equation 49473 := x ◇ x = (x ◇ (y ◇ (z ◇ w))) ◇ u
equation 49474 := x ◇ x = (y ◇ (x ◇ (x ◇ x))) ◇ x
equation 49475 := x ◇ x = (y ◇ (x ◇ (x ◇ x))) ◇ y
equation 49476 := x ◇ x = (y ◇ (x ◇ (x ◇ x))) ◇ z
equation 49477 := x ◇ x = (y ◇ (x ◇ (x ◇ y))) ◇ x
equation 49478 := x ◇ x = (y ◇ (x ◇ (x ◇ y))) ◇ y
equation 49479 := x ◇ x = (y ◇ (x ◇ (x ◇ y))) ◇ z
equation 49480 := x ◇ x = (y ◇ (x ◇ (x ◇ z))) ◇ x
equation 49481 := x ◇ x = (y ◇ (x ◇ (x ◇ z))) ◇ y
equation 49482 := x ◇ x = (y ◇ (x ◇ (x ◇ z))) ◇ z
equation 49483 := x ◇ x = (y ◇ (x ◇ (x ◇ z))) ◇ w
equation 49484 := x ◇ x = (y ◇ (x ◇ (y ◇ x))) ◇ x
equation 49485 := x ◇ x = (y ◇ (x ◇ (y ◇ x))) ◇ y
equation 49486 := x ◇ x = (y ◇ (x ◇ (y ◇ x))) ◇ z
equation 49487 := x ◇ x = (y ◇ (x ◇ (y ◇ y))) ◇ x
equation 49488 := x ◇ x = (y ◇ (x ◇ (y ◇ y))) ◇ y
equation 49489 := x ◇ x = (y ◇ (x ◇ (y ◇ y))) ◇ z
equation 49490 := x ◇ x = (y ◇ (x ◇ (y ◇ z))) ◇ x
equation 49491 := x ◇ x = (y ◇ (x ◇ (y ◇ z))) ◇ y
equation 49492 := x ◇ x = (y ◇ (x ◇ (y ◇ z))) ◇ z
equation 49493 := x ◇ x = (y ◇ (x ◇ (y ◇ z))) ◇ w
equation 49494 := x ◇ x = (y ◇ (x ◇ (z ◇ x))) ◇ x
equation 49495 := x ◇ x = (y ◇ (x ◇ (z ◇ x))) ◇ y
equation 49496 := x ◇ x = (y ◇ (x ◇ (z ◇ x))) ◇ z
equation 49497 := x ◇ x = (y ◇ (x ◇ (z ◇ x))) ◇ w
equation 49498 := x ◇ x = (y ◇ (x ◇ (z ◇ y))) ◇ x
equation 49499 := x ◇ x = (y ◇ (x ◇ (z ◇ y))) ◇ y
equation 49500 := x ◇ x = (y ◇ (x ◇ (z ◇ y))) ◇ z
equation 49501 := x ◇ x = (y ◇ (x ◇ (z ◇ y))) ◇ w
equation 49502 := x ◇ x = (y ◇ (x ◇ (z ◇ z))) ◇ x
equation 49503 := x ◇ x = (y ◇ (x ◇ (z ◇ z))) ◇ y
equation 49504 := x ◇ x = (y ◇ (x ◇ (z ◇ z))) ◇ z
equation 49505 := x ◇ x = (y ◇ (x ◇ (z ◇ z))) ◇ w
equation 49506 := x ◇ x = (y ◇ (x ◇ (z ◇ w))) ◇ x
equation 49507 := x ◇ x = (y ◇ (x ◇ (z ◇ w))) ◇ y
equation 49508 := x ◇ x = (y ◇ (x ◇ (z ◇ w))) ◇ z
equation 49509 := x ◇ x = (y ◇ (x ◇ (z ◇ w))) ◇ w
equation 49510 := x ◇ x = (y ◇ (x ◇ (z ◇ w))) ◇ u
equation 49511 := x ◇ x = (y ◇ (y ◇ (x ◇ x))) ◇ x
equation 49512 := x ◇ x = (y ◇ (y ◇ (x ◇ x))) ◇ y
equation 49513 := x ◇ x = (y ◇ (y ◇ (x ◇ x))) ◇ z
equation 49514 := x ◇ x = (y ◇ (y ◇ (x ◇ y))) ◇ x
equation 49515 := x ◇ x = (y ◇ (y ◇ (x ◇ y))) ◇ y
equation 49516 := x ◇ x = (y ◇ (y ◇ (x ◇ y))) ◇ z
equation 49517 := x ◇ x = (y ◇ (y ◇ (x ◇ z))) ◇ x
equation 49518 := x ◇ x = (y ◇ (y ◇ (x ◇ z))) ◇ y
equation 49519 := x ◇ x = (y ◇ (y ◇ (x ◇ z))) ◇ z
equation 49520 := x ◇ x = (y ◇ (y ◇ (x ◇ z))) ◇ w
equation 49521 := x ◇ x = (y ◇ (y ◇ (y ◇ x))) ◇ x
equation 49522 := x ◇ x = (y ◇ (y ◇ (y ◇ x))) ◇ y
equation 49523 := x ◇ x = (y ◇ (y ◇ (y ◇ x))) ◇ z
equation 49524 := x ◇ x = (y ◇ (y ◇ (y ◇ y))) ◇ x
equation 49525 := x ◇ x = (y ◇ (y ◇ (y ◇ y))) ◇ y
equation 49526 := x ◇ x = (y ◇ (y ◇ (y ◇ y))) ◇ z
equation 49527 := x ◇ x = (y ◇ (y ◇ (y ◇ z))) ◇ x
equation 49528 := x ◇ x = (y ◇ (y ◇ (y ◇ z))) ◇ y
equation 49529 := x ◇ x = (y ◇ (y ◇ (y ◇ z))) ◇ z
equation 49530 := x ◇ x = (y ◇ (y ◇ (y ◇ z))) ◇ w
equation 49531 := x ◇ x = (y ◇ (y ◇ (z ◇ x))) ◇ x
equation 49532 := x ◇ x = (y ◇ (y ◇ (z ◇ x))) ◇ y
equation 49533 := x ◇ x = (y ◇ (y ◇ (z ◇ x))) ◇ z
equation 49534 := x ◇ x = (y ◇ (y ◇ (z ◇ x))) ◇ w
equation 49535 := x ◇ x = (y ◇ (y ◇ (z ◇ y))) ◇ x
equation 49536 := x ◇ x = (y ◇ (y ◇ (z ◇ y))) ◇ y
equation 49537 := x ◇ x = (y ◇ (y ◇ (z ◇ y))) ◇ z
equation 49538 := x ◇ x = (y ◇ (y ◇ (z ◇ y))) ◇ w
equation 49539 := x ◇ x = (y ◇ (y ◇ (z ◇ z))) ◇ x
equation 49540 := x ◇ x = (y ◇ (y ◇ (z ◇ z))) ◇ y
equation 49541 := x ◇ x = (y ◇ (y ◇ (z ◇ z))) ◇ z
equation 49542 := x ◇ x = (y ◇ (y ◇ (z ◇ z))) ◇ w
equation 49543 := x ◇ x = (y ◇ (y ◇ (z ◇ w))) ◇ x
equation 49544 := x ◇ x = (y ◇ (y ◇ (z ◇ w))) ◇ y
equation 49545 := x ◇ x = (y ◇ (y ◇ (z ◇ w))) ◇ z
equation 49546 := x ◇ x = (y ◇ (y ◇ (z ◇ w))) ◇ w
equation 49547 := x ◇ x = (y ◇ (y ◇ (z ◇ w))) ◇ u
equation 49548 := x ◇ x = (y ◇ (z ◇ (x ◇ x))) ◇ x
equation 49549 := x ◇ x = (y ◇ (z ◇ (x ◇ x))) ◇ y
equation 49550 := x ◇ x = (y ◇ (z ◇ (x ◇ x))) ◇ z
equation 49551 := x ◇ x = (y ◇ (z ◇ (x ◇ x))) ◇ w
equation 49552 := x ◇ x = (y ◇ (z ◇ (x ◇ y))) ◇ x
equation 49553 := x ◇ x = (y ◇ (z ◇ (x ◇ y))) ◇ y
equation 49554 := x ◇ x = (y ◇ (z ◇ (x ◇ y))) ◇ z
equation 49555 := x ◇ x = (y ◇ (z ◇ (x ◇ y))) ◇ w
equation 49556 := x ◇ x = (y ◇ (z ◇ (x ◇ z))) ◇ x
equation 49557 := x ◇ x = (y ◇ (z ◇ (x ◇ z))) ◇ y
equation 49558 := x ◇ x = (y ◇ (z ◇ (x ◇ z))) ◇ z
equation 49559 := x ◇ x = (y ◇ (z ◇ (x ◇ z))) ◇ w
equation 49560 := x ◇ x = (y ◇ (z ◇ (x ◇ w))) ◇ x
equation 49561 := x ◇ x = (y ◇ (z ◇ (x ◇ w))) ◇ y
equation 49562 := x ◇ x = (y ◇ (z ◇ (x ◇ w))) ◇ z
equation 49563 := x ◇ x = (y ◇ (z ◇ (x ◇ w))) ◇ w
equation 49564 := x ◇ x = (y ◇ (z ◇ (x ◇ w))) ◇ u
equation 49565 := x ◇ x = (y ◇ (z ◇ (y ◇ x))) ◇ x
equation 49566 := x ◇ x = (y ◇ (z ◇ (y ◇ x))) ◇ y
equation 49567 := x ◇ x = (y ◇ (z ◇ (y ◇ x))) ◇ z
equation 49568 := x ◇ x = (y ◇ (z ◇ (y ◇ x))) ◇ w
equation 49569 := x ◇ x = (y ◇ (z ◇ (y ◇ y))) ◇ x
equation 49570 := x ◇ x = (y ◇ (z ◇ (y ◇ y))) ◇ y
equation 49571 := x ◇ x = (y ◇ (z ◇ (y ◇ y))) ◇ z
equation 49572 := x ◇ x = (y ◇ (z ◇ (y ◇ y))) ◇ w
equation 49573 := x ◇ x = (y ◇ (z ◇ (y ◇ z))) ◇ x
equation 49574 := x ◇ x = (y ◇ (z ◇ (y ◇ z))) ◇ y
equation 49575 := x ◇ x = (y ◇ (z ◇ (y ◇ z))) ◇ z
equation 49576 := x ◇ x = (y ◇ (z ◇ (y ◇ z))) ◇ w
equation 49577 := x ◇ x = (y ◇ (z ◇ (y ◇ w))) ◇ x
equation 49578 := x ◇ x = (y ◇ (z ◇ (y ◇ w))) ◇ y
equation 49579 := x ◇ x = (y ◇ (z ◇ (y ◇ w))) ◇ z
equation 49580 := x ◇ x = (y ◇ (z ◇ (y ◇ w))) ◇ w
equation 49581 := x ◇ x = (y ◇ (z ◇ (y ◇ w))) ◇ u
equation 49582 := x ◇ x = (y ◇ (z ◇ (z ◇ x))) ◇ x
equation 49583 := x ◇ x = (y ◇ (z ◇ (z ◇ x))) ◇ y
equation 49584 := x ◇ x = (y ◇ (z ◇ (z ◇ x))) ◇ z
equation 49585 := x ◇ x = (y ◇ (z ◇ (z ◇ x))) ◇ w
equation 49586 := x ◇ x = (y ◇ (z ◇ (z ◇ y))) ◇ x
equation 49587 := x ◇ x = (y ◇ (z ◇ (z ◇ y))) ◇ y
equation 49588 := x ◇ x = (y ◇ (z ◇ (z ◇ y))) ◇ z
equation 49589 := x ◇ x = (y ◇ (z ◇ (z ◇ y))) ◇ w
equation 49590 := x ◇ x = (y ◇ (z ◇ (z ◇ z))) ◇ x
equation 49591 := x ◇ x = (y ◇ (z ◇ (z ◇ z))) ◇ y
equation 49592 := x ◇ x = (y ◇ (z ◇ (z ◇ z))) ◇ z
equation 49593 := x ◇ x = (y ◇ (z ◇ (z ◇ z))) ◇ w
equation 49594 := x ◇ x = (y ◇ (z ◇ (z ◇ w))) ◇ x
equation 49595 := x ◇ x = (y ◇ (z ◇ (z ◇ w))) ◇ y
equation 49596 := x ◇ x = (y ◇ (z ◇ (z ◇ w))) ◇ z
equation 49597 := x ◇ x = (y ◇ (z ◇ (z ◇ w))) ◇ w
equation 49598 := x ◇ x = (y ◇ (z ◇ (z ◇ w))) ◇ u
equation 49599 := x ◇ x = (y ◇ (z ◇ (w ◇ x))) ◇ x
equation 49600 := x ◇ x = (y ◇ (z ◇ (w ◇ x))) ◇ y
equation 49601 := x ◇ x = (y ◇ (z ◇ (w ◇ x))) ◇ z
equation 49602 := x ◇ x = (y ◇ (z ◇ (w ◇ x))) ◇ w
equation 49603 := x ◇ x = (y ◇ (z ◇ (w ◇ x))) ◇ u
equation 49604 := x ◇ x = (y ◇ (z ◇ (w ◇ y))) ◇ x
equation 49605 := x ◇ x = (y ◇ (z ◇ (w ◇ y))) ◇ y
equation 49606 := x ◇ x = (y ◇ (z ◇ (w ◇ y))) ◇ z
equation 49607 := x ◇ x = (y ◇ (z ◇ (w ◇ y))) ◇ w
equation 49608 := x ◇ x = (y ◇ (z ◇ (w ◇ y))) ◇ u
equation 49609 := x ◇ x = (y ◇ (z ◇ (w ◇ z))) ◇ x
equation 49610 := x ◇ x = (y ◇ (z ◇ (w ◇ z))) ◇ y
equation 49611 := x ◇ x = (y ◇ (z ◇ (w ◇ z))) ◇ z
equation 49612 := x ◇ x = (y ◇ (z ◇ (w ◇ z))) ◇ w
equation 49613 := x ◇ x = (y ◇ (z ◇ (w ◇ z))) ◇ u
equation 49614 := x ◇ x = (y ◇ (z ◇ (w ◇ w))) ◇ x
equation 49615 := x ◇ x = (y ◇ (z ◇ (w ◇ w))) ◇ y
equation 49616 := x ◇ x = (y ◇ (z ◇ (w ◇ w))) ◇ z
equation 49617 := x ◇ x = (y ◇ (z ◇ (w ◇ w))) ◇ w
equation 49618 := x ◇ x = (y ◇ (z ◇ (w ◇ w))) ◇ u
equation 49619 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ x
equation 49620 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ y
equation 49621 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ z
equation 49622 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ w
equation 49623 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ u
equation 49624 := x ◇ x = (y ◇ (z ◇ (w ◇ u))) ◇ v
equation 49625 := x ◇ y = (x ◇ (x ◇ (x ◇ x))) ◇ x
equation 49626 := x ◇ y = (x ◇ (x ◇ (x ◇ x))) ◇ y
equation 49627 := x ◇ y = (x ◇ (x ◇ (x ◇ x))) ◇ z
equation 49628 := x ◇ y = (x ◇ (x ◇ (x ◇ y))) ◇ x
equation 49629 := x ◇ y = (x ◇ (x ◇ (x ◇ y))) ◇ y
equation 49630 := x ◇ y = (x ◇ (x ◇ (x ◇ y))) ◇ z
equation 49631 := x ◇ y = (x ◇ (x ◇ (x ◇ z))) ◇ x
equation 49632 := x ◇ y = (x ◇ (x ◇ (x ◇ z))) ◇ y
equation 49633 := x ◇ y = (x ◇ (x ◇ (x ◇ z))) ◇ z
equation 49634 := x ◇ y = (x ◇ (x ◇ (x ◇ z))) ◇ w
equation 49635 := x ◇ y = (x ◇ (x ◇ (y ◇ x))) ◇ x
equation 49636 := x ◇ y = (x ◇ (x ◇ (y ◇ x))) ◇ y
equation 49637 := x ◇ y = (x ◇ (x ◇ (y ◇ x))) ◇ z
equation 49638 := x ◇ y = (x ◇ (x ◇ (y ◇ y))) ◇ x
equation 49639 := x ◇ y = (x ◇ (x ◇ (y ◇ y))) ◇ y
equation 49640 := x ◇ y = (x ◇ (x ◇ (y ◇ y))) ◇ z
equation 49641 := x ◇ y = (x ◇ (x ◇ (y ◇ z))) ◇ x
equation 49642 := x ◇ y = (x ◇ (x ◇ (y ◇ z))) ◇ y
equation 49643 := x ◇ y = (x ◇ (x ◇ (y ◇ z))) ◇ z
equation 49644 := x ◇ y = (x ◇ (x ◇ (y ◇ z))) ◇ w
equation 49645 := x ◇ y = (x ◇ (x ◇ (z ◇ x))) ◇ x
equation 49646 := x ◇ y = (x ◇ (x ◇ (z ◇ x))) ◇ y
equation 49647 := x ◇ y = (x ◇ (x ◇ (z ◇ x))) ◇ z
equation 49648 := x ◇ y = (x ◇ (x ◇ (z ◇ x))) ◇ w
equation 49649 := x ◇ y = (x ◇ (x ◇ (z ◇ y))) ◇ x
equation 49650 := x ◇ y = (x ◇ (x ◇ (z ◇ y))) ◇ y
equation 49651 := x ◇ y = (x ◇ (x ◇ (z ◇ y))) ◇ z
equation 49652 := x ◇ y = (x ◇ (x ◇ (z ◇ y))) ◇ w
equation 49653 := x ◇ y = (x ◇ (x ◇ (z ◇ z))) ◇ x
equation 49654 := x ◇ y = (x ◇ (x ◇ (z ◇ z))) ◇ y
equation 49655 := x ◇ y = (x ◇ (x ◇ (z ◇ z))) ◇ z
equation 49656 := x ◇ y = (x ◇ (x ◇ (z ◇ z))) ◇ w
equation 49657 := x ◇ y = (x ◇ (x ◇ (z ◇ w))) ◇ x
equation 49658 := x ◇ y = (x ◇ (x ◇ (z ◇ w))) ◇ y
equation 49659 := x ◇ y = (x ◇ (x ◇ (z ◇ w))) ◇ z
equation 49660 := x ◇ y = (x ◇ (x ◇ (z ◇ w))) ◇ w
equation 49661 := x ◇ y = (x ◇ (x ◇ (z ◇ w))) ◇ u
equation 49662 := x ◇ y = (x ◇ (y ◇ (x ◇ x))) ◇ x
equation 49663 := x ◇ y = (x ◇ (y ◇ (x ◇ x))) ◇ y
equation 49664 := x ◇ y = (x ◇ (y ◇ (x ◇ x))) ◇ z
equation 49665 := x ◇ y = (x ◇ (y ◇ (x ◇ y))) ◇ x
equation 49666 := x ◇ y = (x ◇ (y ◇ (x ◇ y))) ◇ y
equation 49667 := x ◇ y = (x ◇ (y ◇ (x ◇ y))) ◇ z
equation 49668 := x ◇ y = (x ◇ (y ◇ (x ◇ z))) ◇ x
equation 49669 := x ◇ y = (x ◇ (y ◇ (x ◇ z))) ◇ y
equation 49670 := x ◇ y = (x ◇ (y ◇ (x ◇ z))) ◇ z
equation 49671 := x ◇ y = (x ◇ (y ◇ (x ◇ z))) ◇ w
equation 49672 := x ◇ y = (x ◇ (y ◇ (y ◇ x))) ◇ x
equation 49673 := x ◇ y = (x ◇ (y ◇ (y ◇ x))) ◇ y
equation 49674 := x ◇ y = (x ◇ (y ◇ (y ◇ x))) ◇ z
equation 49675 := x ◇ y = (x ◇ (y ◇ (y ◇ y))) ◇ x
equation 49676 := x ◇ y = (x ◇ (y ◇ (y ◇ y))) ◇ y
equation 49677 := x ◇ y = (x ◇ (y ◇ (y ◇ y))) ◇ z
equation 49678 := x ◇ y = (x ◇ (y ◇ (y ◇ z))) ◇ x
equation 49679 := x ◇ y = (x ◇ (y ◇ (y ◇ z))) ◇ y
equation 49680 := x ◇ y = (x ◇ (y ◇ (y ◇ z))) ◇ z
equation 49681 := x ◇ y = (x ◇ (y ◇ (y ◇ z))) ◇ w
equation 49682 := x ◇ y = (x ◇ (y ◇ (z ◇ x))) ◇ x
equation 49683 := x ◇ y = (x ◇ (y ◇ (z ◇ x))) ◇ y
equation 49684 := x ◇ y = (x ◇ (y ◇ (z ◇ x))) ◇ z
equation 49685 := x ◇ y = (x ◇ (y ◇ (z ◇ x))) ◇ w
equation 49686 := x ◇ y = (x ◇ (y ◇ (z ◇ y))) ◇ x
equation 49687 := x ◇ y = (x ◇ (y ◇ (z ◇ y))) ◇ y
equation 49688 := x ◇ y = (x ◇ (y ◇ (z ◇ y))) ◇ z
equation 49689 := x ◇ y = (x ◇ (y ◇ (z ◇ y))) ◇ w
equation 49690 := x ◇ y = (x ◇ (y ◇ (z ◇ z))) ◇ x
equation 49691 := x ◇ y = (x ◇ (y ◇ (z ◇ z))) ◇ y
equation 49692 := x ◇ y = (x ◇ (y ◇ (z ◇ z))) ◇ z
equation 49693 := x ◇ y = (x ◇ (y ◇ (z ◇ z))) ◇ w
equation 49694 := x ◇ y = (x ◇ (y ◇ (z ◇ w))) ◇ x
equation 49695 := x ◇ y = (x ◇ (y ◇ (z ◇ w))) ◇ y
equation 49696 := x ◇ y = (x ◇ (y ◇ (z ◇ w))) ◇ z
equation 49697 := x ◇ y = (x ◇ (y ◇ (z ◇ w))) ◇ w
equation 49698 := x ◇ y = (x ◇ (y ◇ (z ◇ w))) ◇ u
equation 49699 := x ◇ y = (x ◇ (z ◇ (x ◇ x))) ◇ x
equation 49700 := x ◇ y = (x ◇ (z ◇ (x ◇ x))) ◇ y
equation 49701 := x ◇ y = (x ◇ (z ◇ (x ◇ x))) ◇ z
equation 49702 := x ◇ y = (x ◇ (z ◇ (x ◇ x))) ◇ w
equation 49703 := x ◇ y = (x ◇ (z ◇ (x ◇ y))) ◇ x
equation 49704 := x ◇ y = (x ◇ (z ◇ (x ◇ y))) ◇ y
equation 49705 := x ◇ y = (x ◇ (z ◇ (x ◇ y))) ◇ z
equation 49706 := x ◇ y = (x ◇ (z ◇ (x ◇ y))) ◇ w
equation 49707 := x ◇ y = (x ◇ (z ◇ (x ◇ z))) ◇ x
equation 49708 := x ◇ y = (x ◇ (z ◇ (x ◇ z))) ◇ y
equation 49709 := x ◇ y = (x ◇ (z ◇ (x ◇ z))) ◇ z
equation 49710 := x ◇ y = (x ◇ (z ◇ (x ◇ z))) ◇ w
equation 49711 := x ◇ y = (x ◇ (z ◇ (x ◇ w))) ◇ x
equation 49712 := x ◇ y = (x ◇ (z ◇ (x ◇ w))) ◇ y
equation 49713 := x ◇ y = (x ◇ (z ◇ (x ◇ w))) ◇ z
equation 49714 := x ◇ y = (x ◇ (z ◇ (x ◇ w))) ◇ w
equation 49715 := x ◇ y = (x ◇ (z ◇ (x ◇ w))) ◇ u
equation 49716 := x ◇ y = (x ◇ (z ◇ (y ◇ x))) ◇ x
equation 49717 := x ◇ y = (x ◇ (z ◇ (y ◇ x))) ◇ y
equation 49718 := x ◇ y = (x ◇ (z ◇ (y ◇ x))) ◇ z
equation 49719 := x ◇ y = (x ◇ (z ◇ (y ◇ x))) ◇ w
equation 49720 := x ◇ y = (x ◇ (z ◇ (y ◇ y))) ◇ x
equation 49721 := x ◇ y = (x ◇ (z ◇ (y ◇ y))) ◇ y
equation 49722 := x ◇ y = (x ◇ (z ◇ (y ◇ y))) ◇ z
equation 49723 := x ◇ y = (x ◇ (z ◇ (y ◇ y))) ◇ w
equation 49724 := x ◇ y = (x ◇ (z ◇ (y ◇ z))) ◇ x
equation 49725 := x ◇ y = (x ◇ (z ◇ (y ◇ z))) ◇ y
equation 49726 := x ◇ y = (x ◇ (z ◇ (y ◇ z))) ◇ z
equation 49727 := x ◇ y = (x ◇ (z ◇ (y ◇ z))) ◇ w
equation 49728 := x ◇ y = (x ◇ (z ◇ (y ◇ w))) ◇ x
equation 49729 := x ◇ y = (x ◇ (z ◇ (y ◇ w))) ◇ y
equation 49730 := x ◇ y = (x ◇ (z ◇ (y ◇ w))) ◇ z
equation 49731 := x ◇ y = (x ◇ (z ◇ (y ◇ w))) ◇ w
equation 49732 := x ◇ y = (x ◇ (z ◇ (y ◇ w))) ◇ u
equation 49733 := x ◇ y = (x ◇ (z ◇ (z ◇ x))) ◇ x
equation 49734 := x ◇ y = (x ◇ (z ◇ (z ◇ x))) ◇ y
equation 49735 := x ◇ y = (x ◇ (z ◇ (z ◇ x))) ◇ z
equation 49736 := x ◇ y = (x ◇ (z ◇ (z ◇ x))) ◇ w
equation 49737 := x ◇ y = (x ◇ (z ◇ (z ◇ y))) ◇ x
equation 49738 := x ◇ y = (x ◇ (z ◇ (z ◇ y))) ◇ y
equation 49739 := x ◇ y = (x ◇ (z ◇ (z ◇ y))) ◇ z
equation 49740 := x ◇ y = (x ◇ (z ◇ (z ◇ y))) ◇ w
equation 49741 := x ◇ y = (x ◇ (z ◇ (z ◇ z))) ◇ x
equation 49742 := x ◇ y = (x ◇ (z ◇ (z ◇ z))) ◇ y
equation 49743 := x ◇ y = (x ◇ (z ◇ (z ◇ z))) ◇ z
equation 49744 := x ◇ y = (x ◇ (z ◇ (z ◇ z))) ◇ w
equation 49745 := x ◇ y = (x ◇ (z ◇ (z ◇ w))) ◇ x
equation 49746 := x ◇ y = (x ◇ (z ◇ (z ◇ w))) ◇ y
equation 49747 := x ◇ y = (x ◇ (z ◇ (z ◇ w))) ◇ z
equation 49748 := x ◇ y = (x ◇ (z ◇ (z ◇ w))) ◇ w
equation 49749 := x ◇ y = (x ◇ (z ◇ (z ◇ w))) ◇ u
equation 49750 := x ◇ y = (x ◇ (z ◇ (w ◇ x))) ◇ x
equation 49751 := x ◇ y = (x ◇ (z ◇ (w ◇ x))) ◇ y
equation 49752 := x ◇ y = (x ◇ (z ◇ (w ◇ x))) ◇ z
equation 49753 := x ◇ y = (x ◇ (z ◇ (w ◇ x))) ◇ w
equation 49754 := x ◇ y = (x ◇ (z ◇ (w ◇ x))) ◇ u
equation 49755 := x ◇ y = (x ◇ (z ◇ (w ◇ y))) ◇ x
equation 49756 := x ◇ y = (x ◇ (z ◇ (w ◇ y))) ◇ y
equation 49757 := x ◇ y = (x ◇ (z ◇ (w ◇ y))) ◇ z
equation 49758 := x ◇ y = (x ◇ (z ◇ (w ◇ y))) ◇ w
equation 49759 := x ◇ y = (x ◇ (z ◇ (w ◇ y))) ◇ u
equation 49760 := x ◇ y = (x ◇ (z ◇ (w ◇ z))) ◇ x
equation 49761 := x ◇ y = (x ◇ (z ◇ (w ◇ z))) ◇ y
equation 49762 := x ◇ y = (x ◇ (z ◇ (w ◇ z))) ◇ z
equation 49763 := x ◇ y = (x ◇ (z ◇ (w ◇ z))) ◇ w
equation 49764 := x ◇ y = (x ◇ (z ◇ (w ◇ z))) ◇ u
equation 49765 := x ◇ y = (x ◇ (z ◇ (w ◇ w))) ◇ x
equation 49766 := x ◇ y = (x ◇ (z ◇ (w ◇ w))) ◇ y
equation 49767 := x ◇ y = (x ◇ (z ◇ (w ◇ w))) ◇ z
equation 49768 := x ◇ y = (x ◇ (z ◇ (w ◇ w))) ◇ w
equation 49769 := x ◇ y = (x ◇ (z ◇ (w ◇ w))) ◇ u
equation 49770 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ x
equation 49771 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ y
equation 49772 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ z
equation 49773 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ w
equation 49774 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ u
equation 49775 := x ◇ y = (x ◇ (z ◇ (w ◇ u))) ◇ v
equation 49776 := x ◇ y = (y ◇ (x ◇ (x ◇ x))) ◇ x
equation 49777 := x ◇ y = (y ◇ (x ◇ (x ◇ x))) ◇ y
equation 49778 := x ◇ y = (y ◇ (x ◇ (x ◇ x))) ◇ z
equation 49779 := x ◇ y = (y ◇ (x ◇ (x ◇ y))) ◇ x
equation 49780 := x ◇ y = (y ◇ (x ◇ (x ◇ y))) ◇ y
equation 49781 := x ◇ y = (y ◇ (x ◇ (x ◇ y))) ◇ z
equation 49782 := x ◇ y = (y ◇ (x ◇ (x ◇ z))) ◇ x
equation 49783 := x ◇ y = (y ◇ (x ◇ (x ◇ z))) ◇ y
equation 49784 := x ◇ y = (y ◇ (x ◇ (x ◇ z))) ◇ z
equation 49785 := x ◇ y = (y ◇ (x ◇ (x ◇ z))) ◇ w
equation 49786 := x ◇ y = (y ◇ (x ◇ (y ◇ x))) ◇ x
equation 49787 := x ◇ y = (y ◇ (x ◇ (y ◇ x))) ◇ y
equation 49788 := x ◇ y = (y ◇ (x ◇ (y ◇ x))) ◇ z
equation 49789 := x ◇ y = (y ◇ (x ◇ (y ◇ y))) ◇ x
equation 49790 := x ◇ y = (y ◇ (x ◇ (y ◇ y))) ◇ y
equation 49791 := x ◇ y = (y ◇ (x ◇ (y ◇ y))) ◇ z
equation 49792 := x ◇ y = (y ◇ (x ◇ (y ◇ z))) ◇ x
equation 49793 := x ◇ y = (y ◇ (x ◇ (y ◇ z))) ◇ y
equation 49794 := x ◇ y = (y ◇ (x ◇ (y ◇ z))) ◇ z
equation 49795 := x ◇ y = (y ◇ (x ◇ (y ◇ z))) ◇ w
equation 49796 := x ◇ y = (y ◇ (x ◇ (z ◇ x))) ◇ x
equation 49797 := x ◇ y = (y ◇ (x ◇ (z ◇ x))) ◇ y
equation 49798 := x ◇ y = (y ◇ (x ◇ (z ◇ x))) ◇ z
equation 49799 := x ◇ y = (y ◇ (x ◇ (z ◇ x))) ◇ w
equation 49800 := x ◇ y = (y ◇ (x ◇ (z ◇ y))) ◇ x
equation 49801 := x ◇ y = (y ◇ (x ◇ (z ◇ y))) ◇ y
equation 49802 := x ◇ y = (y ◇ (x ◇ (z ◇ y))) ◇ z
equation 49803 := x ◇ y = (y ◇ (x ◇ (z ◇ y))) ◇ w
equation 49804 := x ◇ y = (y ◇ (x ◇ (z ◇ z))) ◇ x
equation 49805 := x ◇ y = (y ◇ (x ◇ (z ◇ z))) ◇ y
equation 49806 := x ◇ y = (y ◇ (x ◇ (z ◇ z))) ◇ z
equation 49807 := x ◇ y = (y ◇ (x ◇ (z ◇ z))) ◇ w
equation 49808 := x ◇ y = (y ◇ (x ◇ (z ◇ w))) ◇ x
equation 49809 := x ◇ y = (y ◇ (x ◇ (z ◇ w))) ◇ y
equation 49810 := x ◇ y = (y ◇ (x ◇ (z ◇ w))) ◇ z
equation 49811 := x ◇ y = (y ◇ (x ◇ (z ◇ w))) ◇ w
equation 49812 := x ◇ y = (y ◇ (x ◇ (z ◇ w))) ◇ u
equation 49813 := x ◇ y = (y ◇ (y ◇ (x ◇ x))) ◇ x
equation 49814 := x ◇ y = (y ◇ (y ◇ (x ◇ x))) ◇ y
equation 49815 := x ◇ y = (y ◇ (y ◇ (x ◇ x))) ◇ z
equation 49816 := x ◇ y = (y ◇ (y ◇ (x ◇ y))) ◇ x
equation 49817 := x ◇ y = (y ◇ (y ◇ (x ◇ y))) ◇ y
equation 49818 := x ◇ y = (y ◇ (y ◇ (x ◇ y))) ◇ z
equation 49819 := x ◇ y = (y ◇ (y ◇ (x ◇ z))) ◇ x
equation 49820 := x ◇ y = (y ◇ (y ◇ (x ◇ z))) ◇ y
equation 49821 := x ◇ y = (y ◇ (y ◇ (x ◇ z))) ◇ z
equation 49822 := x ◇ y = (y ◇ (y ◇ (x ◇ z))) ◇ w
equation 49823 := x ◇ y = (y ◇ (y ◇ (y ◇ x))) ◇ x
equation 49824 := x ◇ y = (y ◇ (y ◇ (y ◇ x))) ◇ y
equation 49825 := x ◇ y = (y ◇ (y ◇ (y ◇ x))) ◇ z
equation 49826 := x ◇ y = (y ◇ (y ◇ (y ◇ y))) ◇ x
equation 49827 := x ◇ y = (y ◇ (y ◇ (y ◇ y))) ◇ y
equation 49828 := x ◇ y = (y ◇ (y ◇ (y ◇ y))) ◇ z
equation 49829 := x ◇ y = (y ◇ (y ◇ (y ◇ z))) ◇ x
equation 49830 := x ◇ y = (y ◇ (y ◇ (y ◇ z))) ◇ y
equation 49831 := x ◇ y = (y ◇ (y ◇ (y ◇ z))) ◇ z
equation 49832 := x ◇ y = (y ◇ (y ◇ (y ◇ z))) ◇ w
equation 49833 := x ◇ y = (y ◇ (y ◇ (z ◇ x))) ◇ x
equation 49834 := x ◇ y = (y ◇ (y ◇ (z ◇ x))) ◇ y
equation 49835 := x ◇ y = (y ◇ (y ◇ (z ◇ x))) ◇ z
equation 49836 := x ◇ y = (y ◇ (y ◇ (z ◇ x))) ◇ w
equation 49837 := x ◇ y = (y ◇ (y ◇ (z ◇ y))) ◇ x
equation 49838 := x ◇ y = (y ◇ (y ◇ (z ◇ y))) ◇ y
equation 49839 := x ◇ y = (y ◇ (y ◇ (z ◇ y))) ◇ z
equation 49840 := x ◇ y = (y ◇ (y ◇ (z ◇ y))) ◇ w
equation 49841 := x ◇ y = (y ◇ (y ◇ (z ◇ z))) ◇ x
equation 49842 := x ◇ y = (y ◇ (y ◇ (z ◇ z))) ◇ y
equation 49843 := x ◇ y = (y ◇ (y ◇ (z ◇ z))) ◇ z
equation 49844 := x ◇ y = (y ◇ (y ◇ (z ◇ z))) ◇ w
equation 49845 := x ◇ y = (y ◇ (y ◇ (z ◇ w))) ◇ x
equation 49846 := x ◇ y = (y ◇ (y ◇ (z ◇ w))) ◇ y
equation 49847 := x ◇ y = (y ◇ (y ◇ (z ◇ w))) ◇ z
equation 49848 := x ◇ y = (y ◇ (y ◇ (z ◇ w))) ◇ w
equation 49849 := x ◇ y = (y ◇ (y ◇ (z ◇ w))) ◇ u
equation 49850 := x ◇ y = (y ◇ (z ◇ (x ◇ x))) ◇ x
equation 49851 := x ◇ y = (y ◇ (z ◇ (x ◇ x))) ◇ y
equation 49852 := x ◇ y = (y ◇ (z ◇ (x ◇ x))) ◇ z
equation 49853 := x ◇ y = (y ◇ (z ◇ (x ◇ x))) ◇ w
equation 49854 := x ◇ y = (y ◇ (z ◇ (x ◇ y))) ◇ x
equation 49855 := x ◇ y = (y ◇ (z ◇ (x ◇ y))) ◇ y
equation 49856 := x ◇ y = (y ◇ (z ◇ (x ◇ y))) ◇ z
equation 49857 := x ◇ y = (y ◇ (z ◇ (x ◇ y))) ◇ w
equation 49858 := x ◇ y = (y ◇ (z ◇ (x ◇ z))) ◇ x
equation 49859 := x ◇ y = (y ◇ (z ◇ (x ◇ z))) ◇ y
equation 49860 := x ◇ y = (y ◇ (z ◇ (x ◇ z))) ◇ z
equation 49861 := x ◇ y = (y ◇ (z ◇ (x ◇ z))) ◇ w
equation 49862 := x ◇ y = (y ◇ (z ◇ (x ◇ w))) ◇ x
equation 49863 := x ◇ y = (y ◇ (z ◇ (x ◇ w))) ◇ y
equation 49864 := x ◇ y = (y ◇ (z ◇ (x ◇ w))) ◇ z
equation 49865 := x ◇ y = (y ◇ (z ◇ (x ◇ w))) ◇ w
equation 49866 := x ◇ y = (y ◇ (z ◇ (x ◇ w))) ◇ u
equation 49867 := x ◇ y = (y ◇ (z ◇ (y ◇ x))) ◇ x
equation 49868 := x ◇ y = (y ◇ (z ◇ (y ◇ x))) ◇ y
equation 49869 := x ◇ y = (y ◇ (z ◇ (y ◇ x))) ◇ z
equation 49870 := x ◇ y = (y ◇ (z ◇ (y ◇ x))) ◇ w
equation 49871 := x ◇ y = (y ◇ (z ◇ (y ◇ y))) ◇ x
equation 49872 := x ◇ y = (y ◇ (z ◇ (y ◇ y))) ◇ y
equation 49873 := x ◇ y = (y ◇ (z ◇ (y ◇ y))) ◇ z
equation 49874 := x ◇ y = (y ◇ (z ◇ (y ◇ y))) ◇ w
equation 49875 := x ◇ y = (y ◇ (z ◇ (y ◇ z))) ◇ x
equation 49876 := x ◇ y = (y ◇ (z ◇ (y ◇ z))) ◇ y
equation 49877 := x ◇ y = (y ◇ (z ◇ (y ◇ z))) ◇ z
equation 49878 := x ◇ y = (y ◇ (z ◇ (y ◇ z))) ◇ w
equation 49879 := x ◇ y = (y ◇ (z ◇ (y ◇ w))) ◇ x
equation 49880 := x ◇ y = (y ◇ (z ◇ (y ◇ w))) ◇ y
equation 49881 := x ◇ y = (y ◇ (z ◇ (y ◇ w))) ◇ z
equation 49882 := x ◇ y = (y ◇ (z ◇ (y ◇ w))) ◇ w
equation 49883 := x ◇ y = (y ◇ (z ◇ (y ◇ w))) ◇ u
equation 49884 := x ◇ y = (y ◇ (z ◇ (z ◇ x))) ◇ x
equation 49885 := x ◇ y = (y ◇ (z ◇ (z ◇ x))) ◇ y
equation 49886 := x ◇ y = (y ◇ (z ◇ (z ◇ x))) ◇ z
equation 49887 := x ◇ y = (y ◇ (z ◇ (z ◇ x))) ◇ w
equation 49888 := x ◇ y = (y ◇ (z ◇ (z ◇ y))) ◇ x
equation 49889 := x ◇ y = (y ◇ (z ◇ (z ◇ y))) ◇ y
equation 49890 := x ◇ y = (y ◇ (z ◇ (z ◇ y))) ◇ z
equation 49891 := x ◇ y = (y ◇ (z ◇ (z ◇ y))) ◇ w
equation 49892 := x ◇ y = (y ◇ (z ◇ (z ◇ z))) ◇ x
equation 49893 := x ◇ y = (y ◇ (z ◇ (z ◇ z))) ◇ y
equation 49894 := x ◇ y = (y ◇ (z ◇ (z ◇ z))) ◇ z
equation 49895 := x ◇ y = (y ◇ (z ◇ (z ◇ z))) ◇ w
equation 49896 := x ◇ y = (y ◇ (z ◇ (z ◇ w))) ◇ x
equation 49897 := x ◇ y = (y ◇ (z ◇ (z ◇ w))) ◇ y
equation 49898 := x ◇ y = (y ◇ (z ◇ (z ◇ w))) ◇ z
equation 49899 := x ◇ y = (y ◇ (z ◇ (z ◇ w))) ◇ w
equation 49900 := x ◇ y = (y ◇ (z ◇ (z ◇ w))) ◇ u
equation 49901 := x ◇ y = (y ◇ (z ◇ (w ◇ x))) ◇ x
equation 49902 := x ◇ y = (y ◇ (z ◇ (w ◇ x))) ◇ y
equation 49903 := x ◇ y = (y ◇ (z ◇ (w ◇ x))) ◇ z
equation 49904 := x ◇ y = (y ◇ (z ◇ (w ◇ x))) ◇ w
equation 49905 := x ◇ y = (y ◇ (z ◇ (w ◇ x))) ◇ u
equation 49906 := x ◇ y = (y ◇ (z ◇ (w ◇ y))) ◇ x
equation 49907 := x ◇ y = (y ◇ (z ◇ (w ◇ y))) ◇ y
equation 49908 := x ◇ y = (y ◇ (z ◇ (w ◇ y))) ◇ z
equation 49909 := x ◇ y = (y ◇ (z ◇ (w ◇ y))) ◇ w
equation 49910 := x ◇ y = (y ◇ (z ◇ (w ◇ y))) ◇ u
equation 49911 := x ◇ y = (y ◇ (z ◇ (w ◇ z))) ◇ x
equation 49912 := x ◇ y = (y ◇ (z ◇ (w ◇ z))) ◇ y
equation 49913 := x ◇ y = (y ◇ (z ◇ (w ◇ z))) ◇ z
equation 49914 := x ◇ y = (y ◇ (z ◇ (w ◇ z))) ◇ w
equation 49915 := x ◇ y = (y ◇ (z ◇ (w ◇ z))) ◇ u
equation 49916 := x ◇ y = (y ◇ (z ◇ (w ◇ w))) ◇ x
equation 49917 := x ◇ y = (y ◇ (z ◇ (w ◇ w))) ◇ y
equation 49918 := x ◇ y = (y ◇ (z ◇ (w ◇ w))) ◇ z
equation 49919 := x ◇ y = (y ◇ (z ◇ (w ◇ w))) ◇ w
equation 49920 := x ◇ y = (y ◇ (z ◇ (w ◇ w))) ◇ u
equation 49921 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ x
equation 49922 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ y
equation 49923 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ z
equation 49924 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ w
equation 49925 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ u
equation 49926 := x ◇ y = (y ◇ (z ◇ (w ◇ u))) ◇ v
equation 49927 := x ◇ y = (z ◇ (x ◇ (x ◇ x))) ◇ x
equation 49928 := x ◇ y = (z ◇ (x ◇ (x ◇ x))) ◇ y
equation 49929 := x ◇ y = (z ◇ (x ◇ (x ◇ x))) ◇ z
equation 49930 := x ◇ y = (z ◇ (x ◇ (x ◇ x))) ◇ w
equation 49931 := x ◇ y = (z ◇ (x ◇ (x ◇ y))) ◇ x
equation 49932 := x ◇ y = (z ◇ (x ◇ (x ◇ y))) ◇ y
equation 49933 := x ◇ y = (z ◇ (x ◇ (x ◇ y))) ◇ z
equation 49934 := x ◇ y = (z ◇ (x ◇ (x ◇ y))) ◇ w
equation 49935 := x ◇ y = (z ◇ (x ◇ (x ◇ z))) ◇ x
equation 49936 := x ◇ y = (z ◇ (x ◇ (x ◇ z))) ◇ y
equation 49937 := x ◇ y = (z ◇ (x ◇ (x ◇ z))) ◇ z
equation 49938 := x ◇ y = (z ◇ (x ◇ (x ◇ z))) ◇ w
equation 49939 := x ◇ y = (z ◇ (x ◇ (x ◇ w))) ◇ x
equation 49940 := x ◇ y = (z ◇ (x ◇ (x ◇ w))) ◇ y
equation 49941 := x ◇ y = (z ◇ (x ◇ (x ◇ w))) ◇ z
equation 49942 := x ◇ y = (z ◇ (x ◇ (x ◇ w))) ◇ w
equation 49943 := x ◇ y = (z ◇ (x ◇ (x ◇ w))) ◇ u
equation 49944 := x ◇ y = (z ◇ (x ◇ (y ◇ x))) ◇ x
equation 49945 := x ◇ y = (z ◇ (x ◇ (y ◇ x))) ◇ y
equation 49946 := x ◇ y = (z ◇ (x ◇ (y ◇ x))) ◇ z
equation 49947 := x ◇ y = (z ◇ (x ◇ (y ◇ x))) ◇ w
equation 49948 := x ◇ y = (z ◇ (x ◇ (y ◇ y))) ◇ x
equation 49949 := x ◇ y = (z ◇ (x ◇ (y ◇ y))) ◇ y
equation 49950 := x ◇ y = (z ◇ (x ◇ (y ◇ y))) ◇ z
equation 49951 := x ◇ y = (z ◇ (x ◇ (y ◇ y))) ◇ w
equation 49952 := x ◇ y = (z ◇ (x ◇ (y ◇ z))) ◇ x
equation 49953 := x ◇ y = (z ◇ (x ◇ (y ◇ z))) ◇ y
equation 49954 := x ◇ y = (z ◇ (x ◇ (y ◇ z))) ◇ z
equation 49955 := x ◇ y = (z ◇ (x ◇ (y ◇ z))) ◇ w
equation 49956 := x ◇ y = (z ◇ (x ◇ (y ◇ w))) ◇ x
equation 49957 := x ◇ y = (z ◇ (x ◇ (y ◇ w))) ◇ y
equation 49958 := x ◇ y = (z ◇ (x ◇ (y ◇ w))) ◇ z
equation 49959 := x ◇ y = (z ◇ (x ◇ (y ◇ w))) ◇ w
equation 49960 := x ◇ y = (z ◇ (x ◇ (y ◇ w))) ◇ u
equation 49961 := x ◇ y = (z ◇ (x ◇ (z ◇ x))) ◇ x
equation 49962 := x ◇ y = (z ◇ (x ◇ (z ◇ x))) ◇ y
equation 49963 := x ◇ y = (z ◇ (x ◇ (z ◇ x))) ◇ z
equation 49964 := x ◇ y = (z ◇ (x ◇ (z ◇ x))) ◇ w
equation 49965 := x ◇ y = (z ◇ (x ◇ (z ◇ y))) ◇ x
equation 49966 := x ◇ y = (z ◇ (x ◇ (z ◇ y))) ◇ y
equation 49967 := x ◇ y = (z ◇ (x ◇ (z ◇ y))) ◇ z
equation 49968 := x ◇ y = (z ◇ (x ◇ (z ◇ y))) ◇ w
equation 49969 := x ◇ y = (z ◇ (x ◇ (z ◇ z))) ◇ x
equation 49970 := x ◇ y = (z ◇ (x ◇ (z ◇ z))) ◇ y
equation 49971 := x ◇ y = (z ◇ (x ◇ (z ◇ z))) ◇ z
equation 49972 := x ◇ y = (z ◇ (x ◇ (z ◇ z))) ◇ w
equation 49973 := x ◇ y = (z ◇ (x ◇ (z ◇ w))) ◇ x
equation 49974 := x ◇ y = (z ◇ (x ◇ (z ◇ w))) ◇ y
equation 49975 := x ◇ y = (z ◇ (x ◇ (z ◇ w))) ◇ z
equation 49976 := x ◇ y = (z ◇ (x ◇ (z ◇ w))) ◇ w
equation 49977 := x ◇ y = (z ◇ (x ◇ (z ◇ w))) ◇ u
equation 49978 := x ◇ y = (z ◇ (x ◇ (w ◇ x))) ◇ x
equation 49979 := x ◇ y = (z ◇ (x ◇ (w ◇ x))) ◇ y
equation 49980 := x ◇ y = (z ◇ (x ◇ (w ◇ x))) ◇ z
equation 49981 := x ◇ y = (z ◇ (x ◇ (w ◇ x))) ◇ w
equation 49982 := x ◇ y = (z ◇ (x ◇ (w ◇ x))) ◇ u
equation 49983 := x ◇ y = (z ◇ (x ◇ (w ◇ y))) ◇ x
equation 49984 := x ◇ y = (z ◇ (x ◇ (w ◇ y))) ◇ y
equation 49985 := x ◇ y = (z ◇ (x ◇ (w ◇ y))) ◇ z
equation 49986 := x ◇ y = (z ◇ (x ◇ (w ◇ y))) ◇ w
equation 49987 := x ◇ y = (z ◇ (x ◇ (w ◇ y))) ◇ u
equation 49988 := x ◇ y = (z ◇ (x ◇ (w ◇ z))) ◇ x
equation 49989 := x ◇ y = (z ◇ (x ◇ (w ◇ z))) ◇ y
equation 49990 := x ◇ y = (z ◇ (x ◇ (w ◇ z))) ◇ z
equation 49991 := x ◇ y = (z ◇ (x ◇ (w ◇ z))) ◇ w
equation 49992 := x ◇ y = (z ◇ (x ◇ (w ◇ z))) ◇ u
equation 49993 := x ◇ y = (z ◇ (x ◇ (w ◇ w))) ◇ x
equation 49994 := x ◇ y = (z ◇ (x ◇ (w ◇ w))) ◇ y
equation 49995 := x ◇ y = (z ◇ (x ◇ (w ◇ w))) ◇ z
equation 49996 := x ◇ y = (z ◇ (x ◇ (w ◇ w))) ◇ w
equation 49997 := x ◇ y = (z ◇ (x ◇ (w ◇ w))) ◇ u
equation 49998 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ x
equation 49999 := x ◇ y = (z ◇ (x ◇ (w ◇ u))) ◇ y
