import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 56000-56999 -/

equation 56000 := x ◇ (y ◇ y) = (z ◇ x) ◇ (z ◇ w)
equation 56001 := x ◇ (y ◇ y) = (z ◇ x) ◇ (w ◇ x)
equation 56002 := x ◇ (y ◇ y) = (z ◇ x) ◇ (w ◇ y)
equation 56003 := x ◇ (y ◇ y) = (z ◇ x) ◇ (w ◇ z)
equation 56004 := x ◇ (y ◇ y) = (z ◇ x) ◇ (w ◇ w)
equation 56005 := x ◇ (y ◇ y) = (z ◇ x) ◇ (w ◇ u)
equation 56006 := x ◇ (y ◇ y) = (z ◇ y) ◇ (x ◇ x)
equation 56007 := x ◇ (y ◇ y) = (z ◇ y) ◇ (x ◇ y)
equation 56008 := x ◇ (y ◇ y) = (z ◇ y) ◇ (x ◇ z)
equation 56009 := x ◇ (y ◇ y) = (z ◇ y) ◇ (x ◇ w)
equation 56010 := x ◇ (y ◇ y) = (z ◇ y) ◇ (y ◇ x)
equation 56011 := x ◇ (y ◇ y) = (z ◇ y) ◇ (y ◇ y)
equation 56012 := x ◇ (y ◇ y) = (z ◇ y) ◇ (y ◇ z)
equation 56013 := x ◇ (y ◇ y) = (z ◇ y) ◇ (y ◇ w)
equation 56014 := x ◇ (y ◇ y) = (z ◇ y) ◇ (z ◇ x)
equation 56015 := x ◇ (y ◇ y) = (z ◇ y) ◇ (z ◇ y)
equation 56016 := x ◇ (y ◇ y) = (z ◇ y) ◇ (z ◇ z)
equation 56017 := x ◇ (y ◇ y) = (z ◇ y) ◇ (z ◇ w)
equation 56018 := x ◇ (y ◇ y) = (z ◇ y) ◇ (w ◇ x)
equation 56019 := x ◇ (y ◇ y) = (z ◇ y) ◇ (w ◇ y)
equation 56020 := x ◇ (y ◇ y) = (z ◇ y) ◇ (w ◇ z)
equation 56021 := x ◇ (y ◇ y) = (z ◇ y) ◇ (w ◇ w)
equation 56022 := x ◇ (y ◇ y) = (z ◇ y) ◇ (w ◇ u)
equation 56023 := x ◇ (y ◇ y) = (z ◇ z) ◇ (x ◇ x)
equation 56024 := x ◇ (y ◇ y) = (z ◇ z) ◇ (x ◇ y)
equation 56025 := x ◇ (y ◇ y) = (z ◇ z) ◇ (x ◇ z)
equation 56026 := x ◇ (y ◇ y) = (z ◇ z) ◇ (x ◇ w)
equation 56027 := x ◇ (y ◇ y) = (z ◇ z) ◇ (y ◇ x)
equation 56028 := x ◇ (y ◇ y) = (z ◇ z) ◇ (y ◇ y)
equation 56029 := x ◇ (y ◇ y) = (z ◇ z) ◇ (y ◇ z)
equation 56030 := x ◇ (y ◇ y) = (z ◇ z) ◇ (y ◇ w)
equation 56031 := x ◇ (y ◇ y) = (z ◇ z) ◇ (z ◇ x)
equation 56032 := x ◇ (y ◇ y) = (z ◇ z) ◇ (z ◇ y)
equation 56033 := x ◇ (y ◇ y) = (z ◇ z) ◇ (z ◇ z)
equation 56034 := x ◇ (y ◇ y) = (z ◇ z) ◇ (z ◇ w)
equation 56035 := x ◇ (y ◇ y) = (z ◇ z) ◇ (w ◇ x)
equation 56036 := x ◇ (y ◇ y) = (z ◇ z) ◇ (w ◇ y)
equation 56037 := x ◇ (y ◇ y) = (z ◇ z) ◇ (w ◇ z)
equation 56038 := x ◇ (y ◇ y) = (z ◇ z) ◇ (w ◇ w)
equation 56039 := x ◇ (y ◇ y) = (z ◇ z) ◇ (w ◇ u)
equation 56040 := x ◇ (y ◇ y) = (z ◇ w) ◇ (x ◇ x)
equation 56041 := x ◇ (y ◇ y) = (z ◇ w) ◇ (x ◇ y)
equation 56042 := x ◇ (y ◇ y) = (z ◇ w) ◇ (x ◇ z)
equation 56043 := x ◇ (y ◇ y) = (z ◇ w) ◇ (x ◇ w)
equation 56044 := x ◇ (y ◇ y) = (z ◇ w) ◇ (x ◇ u)
equation 56045 := x ◇ (y ◇ y) = (z ◇ w) ◇ (y ◇ x)
equation 56046 := x ◇ (y ◇ y) = (z ◇ w) ◇ (y ◇ y)
equation 56047 := x ◇ (y ◇ y) = (z ◇ w) ◇ (y ◇ z)
equation 56048 := x ◇ (y ◇ y) = (z ◇ w) ◇ (y ◇ w)
equation 56049 := x ◇ (y ◇ y) = (z ◇ w) ◇ (y ◇ u)
equation 56050 := x ◇ (y ◇ y) = (z ◇ w) ◇ (z ◇ x)
equation 56051 := x ◇ (y ◇ y) = (z ◇ w) ◇ (z ◇ y)
equation 56052 := x ◇ (y ◇ y) = (z ◇ w) ◇ (z ◇ z)
equation 56053 := x ◇ (y ◇ y) = (z ◇ w) ◇ (z ◇ w)
equation 56054 := x ◇ (y ◇ y) = (z ◇ w) ◇ (z ◇ u)
equation 56055 := x ◇ (y ◇ y) = (z ◇ w) ◇ (w ◇ x)
equation 56056 := x ◇ (y ◇ y) = (z ◇ w) ◇ (w ◇ y)
equation 56057 := x ◇ (y ◇ y) = (z ◇ w) ◇ (w ◇ z)
equation 56058 := x ◇ (y ◇ y) = (z ◇ w) ◇ (w ◇ w)
equation 56059 := x ◇ (y ◇ y) = (z ◇ w) ◇ (w ◇ u)
equation 56060 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ x)
equation 56061 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ y)
equation 56062 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ z)
equation 56063 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ w)
equation 56064 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ u)
equation 56065 := x ◇ (y ◇ y) = (z ◇ w) ◇ (u ◇ v)
equation 56066 := x ◇ (y ◇ z) = (x ◇ x) ◇ (x ◇ x)
equation 56067 := x ◇ (y ◇ z) = (x ◇ x) ◇ (x ◇ y)
equation 56068 := x ◇ (y ◇ z) = (x ◇ x) ◇ (x ◇ z)
equation 56069 := x ◇ (y ◇ z) = (x ◇ x) ◇ (x ◇ w)
equation 56070 := x ◇ (y ◇ z) = (x ◇ x) ◇ (y ◇ x)
equation 56071 := x ◇ (y ◇ z) = (x ◇ x) ◇ (y ◇ y)
equation 56072 := x ◇ (y ◇ z) = (x ◇ x) ◇ (y ◇ z)
equation 56073 := x ◇ (y ◇ z) = (x ◇ x) ◇ (y ◇ w)
equation 56074 := x ◇ (y ◇ z) = (x ◇ x) ◇ (z ◇ x)
equation 56075 := x ◇ (y ◇ z) = (x ◇ x) ◇ (z ◇ y)
equation 56076 := x ◇ (y ◇ z) = (x ◇ x) ◇ (z ◇ z)
equation 56077 := x ◇ (y ◇ z) = (x ◇ x) ◇ (z ◇ w)
equation 56078 := x ◇ (y ◇ z) = (x ◇ x) ◇ (w ◇ x)
equation 56079 := x ◇ (y ◇ z) = (x ◇ x) ◇ (w ◇ y)
equation 56080 := x ◇ (y ◇ z) = (x ◇ x) ◇ (w ◇ z)
equation 56081 := x ◇ (y ◇ z) = (x ◇ x) ◇ (w ◇ w)
equation 56082 := x ◇ (y ◇ z) = (x ◇ x) ◇ (w ◇ u)
equation 56083 := x ◇ (y ◇ z) = (x ◇ y) ◇ (x ◇ x)
equation 56084 := x ◇ (y ◇ z) = (x ◇ y) ◇ (x ◇ y)
equation 56085 := x ◇ (y ◇ z) = (x ◇ y) ◇ (x ◇ z)
equation 56086 := x ◇ (y ◇ z) = (x ◇ y) ◇ (x ◇ w)
equation 56087 := x ◇ (y ◇ z) = (x ◇ y) ◇ (y ◇ x)
equation 56088 := x ◇ (y ◇ z) = (x ◇ y) ◇ (y ◇ y)
equation 56089 := x ◇ (y ◇ z) = (x ◇ y) ◇ (y ◇ z)
equation 56090 := x ◇ (y ◇ z) = (x ◇ y) ◇ (y ◇ w)
equation 56091 := x ◇ (y ◇ z) = (x ◇ y) ◇ (z ◇ x)
equation 56092 := x ◇ (y ◇ z) = (x ◇ y) ◇ (z ◇ y)
equation 56093 := x ◇ (y ◇ z) = (x ◇ y) ◇ (z ◇ z)
equation 56094 := x ◇ (y ◇ z) = (x ◇ y) ◇ (z ◇ w)
equation 56095 := x ◇ (y ◇ z) = (x ◇ y) ◇ (w ◇ x)
equation 56096 := x ◇ (y ◇ z) = (x ◇ y) ◇ (w ◇ y)
equation 56097 := x ◇ (y ◇ z) = (x ◇ y) ◇ (w ◇ z)
equation 56098 := x ◇ (y ◇ z) = (x ◇ y) ◇ (w ◇ w)
equation 56099 := x ◇ (y ◇ z) = (x ◇ y) ◇ (w ◇ u)
equation 56100 := x ◇ (y ◇ z) = (x ◇ z) ◇ (x ◇ x)
equation 56101 := x ◇ (y ◇ z) = (x ◇ z) ◇ (x ◇ y)
equation 56102 := x ◇ (y ◇ z) = (x ◇ z) ◇ (x ◇ z)
equation 56103 := x ◇ (y ◇ z) = (x ◇ z) ◇ (x ◇ w)
equation 56104 := x ◇ (y ◇ z) = (x ◇ z) ◇ (y ◇ x)
equation 56105 := x ◇ (y ◇ z) = (x ◇ z) ◇ (y ◇ y)
equation 56106 := x ◇ (y ◇ z) = (x ◇ z) ◇ (y ◇ z)
equation 56107 := x ◇ (y ◇ z) = (x ◇ z) ◇ (y ◇ w)
equation 56108 := x ◇ (y ◇ z) = (x ◇ z) ◇ (z ◇ x)
equation 56109 := x ◇ (y ◇ z) = (x ◇ z) ◇ (z ◇ y)
equation 56110 := x ◇ (y ◇ z) = (x ◇ z) ◇ (z ◇ z)
equation 56111 := x ◇ (y ◇ z) = (x ◇ z) ◇ (z ◇ w)
equation 56112 := x ◇ (y ◇ z) = (x ◇ z) ◇ (w ◇ x)
equation 56113 := x ◇ (y ◇ z) = (x ◇ z) ◇ (w ◇ y)
equation 56114 := x ◇ (y ◇ z) = (x ◇ z) ◇ (w ◇ z)
equation 56115 := x ◇ (y ◇ z) = (x ◇ z) ◇ (w ◇ w)
equation 56116 := x ◇ (y ◇ z) = (x ◇ z) ◇ (w ◇ u)
equation 56117 := x ◇ (y ◇ z) = (x ◇ w) ◇ (x ◇ x)
equation 56118 := x ◇ (y ◇ z) = (x ◇ w) ◇ (x ◇ y)
equation 56119 := x ◇ (y ◇ z) = (x ◇ w) ◇ (x ◇ z)
equation 56120 := x ◇ (y ◇ z) = (x ◇ w) ◇ (x ◇ w)
equation 56121 := x ◇ (y ◇ z) = (x ◇ w) ◇ (x ◇ u)
equation 56122 := x ◇ (y ◇ z) = (x ◇ w) ◇ (y ◇ x)
equation 56123 := x ◇ (y ◇ z) = (x ◇ w) ◇ (y ◇ y)
equation 56124 := x ◇ (y ◇ z) = (x ◇ w) ◇ (y ◇ z)
equation 56125 := x ◇ (y ◇ z) = (x ◇ w) ◇ (y ◇ w)
equation 56126 := x ◇ (y ◇ z) = (x ◇ w) ◇ (y ◇ u)
equation 56127 := x ◇ (y ◇ z) = (x ◇ w) ◇ (z ◇ x)
equation 56128 := x ◇ (y ◇ z) = (x ◇ w) ◇ (z ◇ y)
equation 56129 := x ◇ (y ◇ z) = (x ◇ w) ◇ (z ◇ z)
equation 56130 := x ◇ (y ◇ z) = (x ◇ w) ◇ (z ◇ w)
equation 56131 := x ◇ (y ◇ z) = (x ◇ w) ◇ (z ◇ u)
equation 56132 := x ◇ (y ◇ z) = (x ◇ w) ◇ (w ◇ x)
equation 56133 := x ◇ (y ◇ z) = (x ◇ w) ◇ (w ◇ y)
equation 56134 := x ◇ (y ◇ z) = (x ◇ w) ◇ (w ◇ z)
equation 56135 := x ◇ (y ◇ z) = (x ◇ w) ◇ (w ◇ w)
equation 56136 := x ◇ (y ◇ z) = (x ◇ w) ◇ (w ◇ u)
equation 56137 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ x)
equation 56138 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ y)
equation 56139 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ z)
equation 56140 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ w)
equation 56141 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ u)
equation 56142 := x ◇ (y ◇ z) = (x ◇ w) ◇ (u ◇ v)
equation 56143 := x ◇ (y ◇ z) = (y ◇ x) ◇ (x ◇ x)
equation 56144 := x ◇ (y ◇ z) = (y ◇ x) ◇ (x ◇ y)
equation 56145 := x ◇ (y ◇ z) = (y ◇ x) ◇ (x ◇ z)
equation 56146 := x ◇ (y ◇ z) = (y ◇ x) ◇ (x ◇ w)
equation 56147 := x ◇ (y ◇ z) = (y ◇ x) ◇ (y ◇ x)
equation 56148 := x ◇ (y ◇ z) = (y ◇ x) ◇ (y ◇ y)
equation 56149 := x ◇ (y ◇ z) = (y ◇ x) ◇ (y ◇ z)
equation 56150 := x ◇ (y ◇ z) = (y ◇ x) ◇ (y ◇ w)
equation 56151 := x ◇ (y ◇ z) = (y ◇ x) ◇ (z ◇ x)
equation 56152 := x ◇ (y ◇ z) = (y ◇ x) ◇ (z ◇ y)
equation 56153 := x ◇ (y ◇ z) = (y ◇ x) ◇ (z ◇ z)
equation 56154 := x ◇ (y ◇ z) = (y ◇ x) ◇ (z ◇ w)
equation 56155 := x ◇ (y ◇ z) = (y ◇ x) ◇ (w ◇ x)
equation 56156 := x ◇ (y ◇ z) = (y ◇ x) ◇ (w ◇ y)
equation 56157 := x ◇ (y ◇ z) = (y ◇ x) ◇ (w ◇ z)
equation 56158 := x ◇ (y ◇ z) = (y ◇ x) ◇ (w ◇ w)
equation 56159 := x ◇ (y ◇ z) = (y ◇ x) ◇ (w ◇ u)
equation 56160 := x ◇ (y ◇ z) = (y ◇ y) ◇ (x ◇ x)
equation 56161 := x ◇ (y ◇ z) = (y ◇ y) ◇ (x ◇ y)
equation 56162 := x ◇ (y ◇ z) = (y ◇ y) ◇ (x ◇ z)
equation 56163 := x ◇ (y ◇ z) = (y ◇ y) ◇ (x ◇ w)
equation 56164 := x ◇ (y ◇ z) = (y ◇ y) ◇ (y ◇ x)
equation 56165 := x ◇ (y ◇ z) = (y ◇ y) ◇ (y ◇ y)
equation 56166 := x ◇ (y ◇ z) = (y ◇ y) ◇ (y ◇ z)
equation 56167 := x ◇ (y ◇ z) = (y ◇ y) ◇ (y ◇ w)
equation 56168 := x ◇ (y ◇ z) = (y ◇ y) ◇ (z ◇ x)
equation 56169 := x ◇ (y ◇ z) = (y ◇ y) ◇ (z ◇ y)
equation 56170 := x ◇ (y ◇ z) = (y ◇ y) ◇ (z ◇ z)
equation 56171 := x ◇ (y ◇ z) = (y ◇ y) ◇ (z ◇ w)
equation 56172 := x ◇ (y ◇ z) = (y ◇ y) ◇ (w ◇ x)
equation 56173 := x ◇ (y ◇ z) = (y ◇ y) ◇ (w ◇ y)
equation 56174 := x ◇ (y ◇ z) = (y ◇ y) ◇ (w ◇ z)
equation 56175 := x ◇ (y ◇ z) = (y ◇ y) ◇ (w ◇ w)
equation 56176 := x ◇ (y ◇ z) = (y ◇ y) ◇ (w ◇ u)
equation 56177 := x ◇ (y ◇ z) = (y ◇ z) ◇ (x ◇ x)
equation 56178 := x ◇ (y ◇ z) = (y ◇ z) ◇ (x ◇ y)
equation 56179 := x ◇ (y ◇ z) = (y ◇ z) ◇ (x ◇ z)
equation 56180 := x ◇ (y ◇ z) = (y ◇ z) ◇ (x ◇ w)
equation 56181 := x ◇ (y ◇ z) = (y ◇ z) ◇ (y ◇ x)
equation 56182 := x ◇ (y ◇ z) = (y ◇ z) ◇ (y ◇ y)
equation 56183 := x ◇ (y ◇ z) = (y ◇ z) ◇ (y ◇ z)
equation 56184 := x ◇ (y ◇ z) = (y ◇ z) ◇ (y ◇ w)
equation 56185 := x ◇ (y ◇ z) = (y ◇ z) ◇ (z ◇ x)
equation 56186 := x ◇ (y ◇ z) = (y ◇ z) ◇ (z ◇ y)
equation 56187 := x ◇ (y ◇ z) = (y ◇ z) ◇ (z ◇ z)
equation 56188 := x ◇ (y ◇ z) = (y ◇ z) ◇ (z ◇ w)
equation 56189 := x ◇ (y ◇ z) = (y ◇ z) ◇ (w ◇ x)
equation 56190 := x ◇ (y ◇ z) = (y ◇ z) ◇ (w ◇ y)
equation 56191 := x ◇ (y ◇ z) = (y ◇ z) ◇ (w ◇ z)
equation 56192 := x ◇ (y ◇ z) = (y ◇ z) ◇ (w ◇ w)
equation 56193 := x ◇ (y ◇ z) = (y ◇ z) ◇ (w ◇ u)
equation 56194 := x ◇ (y ◇ z) = (y ◇ w) ◇ (x ◇ x)
equation 56195 := x ◇ (y ◇ z) = (y ◇ w) ◇ (x ◇ y)
equation 56196 := x ◇ (y ◇ z) = (y ◇ w) ◇ (x ◇ z)
equation 56197 := x ◇ (y ◇ z) = (y ◇ w) ◇ (x ◇ w)
equation 56198 := x ◇ (y ◇ z) = (y ◇ w) ◇ (x ◇ u)
equation 56199 := x ◇ (y ◇ z) = (y ◇ w) ◇ (y ◇ x)
equation 56200 := x ◇ (y ◇ z) = (y ◇ w) ◇ (y ◇ y)
equation 56201 := x ◇ (y ◇ z) = (y ◇ w) ◇ (y ◇ z)
equation 56202 := x ◇ (y ◇ z) = (y ◇ w) ◇ (y ◇ w)
equation 56203 := x ◇ (y ◇ z) = (y ◇ w) ◇ (y ◇ u)
equation 56204 := x ◇ (y ◇ z) = (y ◇ w) ◇ (z ◇ x)
equation 56205 := x ◇ (y ◇ z) = (y ◇ w) ◇ (z ◇ y)
equation 56206 := x ◇ (y ◇ z) = (y ◇ w) ◇ (z ◇ z)
equation 56207 := x ◇ (y ◇ z) = (y ◇ w) ◇ (z ◇ w)
equation 56208 := x ◇ (y ◇ z) = (y ◇ w) ◇ (z ◇ u)
equation 56209 := x ◇ (y ◇ z) = (y ◇ w) ◇ (w ◇ x)
equation 56210 := x ◇ (y ◇ z) = (y ◇ w) ◇ (w ◇ y)
equation 56211 := x ◇ (y ◇ z) = (y ◇ w) ◇ (w ◇ z)
equation 56212 := x ◇ (y ◇ z) = (y ◇ w) ◇ (w ◇ w)
equation 56213 := x ◇ (y ◇ z) = (y ◇ w) ◇ (w ◇ u)
equation 56214 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ x)
equation 56215 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ y)
equation 56216 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ z)
equation 56217 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ w)
equation 56218 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ u)
equation 56219 := x ◇ (y ◇ z) = (y ◇ w) ◇ (u ◇ v)
equation 56220 := x ◇ (y ◇ z) = (z ◇ x) ◇ (x ◇ x)
equation 56221 := x ◇ (y ◇ z) = (z ◇ x) ◇ (x ◇ y)
equation 56222 := x ◇ (y ◇ z) = (z ◇ x) ◇ (x ◇ z)
equation 56223 := x ◇ (y ◇ z) = (z ◇ x) ◇ (x ◇ w)
equation 56224 := x ◇ (y ◇ z) = (z ◇ x) ◇ (y ◇ x)
equation 56225 := x ◇ (y ◇ z) = (z ◇ x) ◇ (y ◇ y)
equation 56226 := x ◇ (y ◇ z) = (z ◇ x) ◇ (y ◇ z)
equation 56227 := x ◇ (y ◇ z) = (z ◇ x) ◇ (y ◇ w)
equation 56228 := x ◇ (y ◇ z) = (z ◇ x) ◇ (z ◇ x)
equation 56229 := x ◇ (y ◇ z) = (z ◇ x) ◇ (z ◇ y)
equation 56230 := x ◇ (y ◇ z) = (z ◇ x) ◇ (z ◇ z)
equation 56231 := x ◇ (y ◇ z) = (z ◇ x) ◇ (z ◇ w)
equation 56232 := x ◇ (y ◇ z) = (z ◇ x) ◇ (w ◇ x)
equation 56233 := x ◇ (y ◇ z) = (z ◇ x) ◇ (w ◇ y)
equation 56234 := x ◇ (y ◇ z) = (z ◇ x) ◇ (w ◇ z)
equation 56235 := x ◇ (y ◇ z) = (z ◇ x) ◇ (w ◇ w)
equation 56236 := x ◇ (y ◇ z) = (z ◇ x) ◇ (w ◇ u)
equation 56237 := x ◇ (y ◇ z) = (z ◇ y) ◇ (x ◇ x)
equation 56238 := x ◇ (y ◇ z) = (z ◇ y) ◇ (x ◇ y)
equation 56239 := x ◇ (y ◇ z) = (z ◇ y) ◇ (x ◇ z)
equation 56240 := x ◇ (y ◇ z) = (z ◇ y) ◇ (x ◇ w)
equation 56241 := x ◇ (y ◇ z) = (z ◇ y) ◇ (y ◇ x)
equation 56242 := x ◇ (y ◇ z) = (z ◇ y) ◇ (y ◇ y)
equation 56243 := x ◇ (y ◇ z) = (z ◇ y) ◇ (y ◇ z)
equation 56244 := x ◇ (y ◇ z) = (z ◇ y) ◇ (y ◇ w)
equation 56245 := x ◇ (y ◇ z) = (z ◇ y) ◇ (z ◇ x)
equation 56246 := x ◇ (y ◇ z) = (z ◇ y) ◇ (z ◇ y)
equation 56247 := x ◇ (y ◇ z) = (z ◇ y) ◇ (z ◇ z)
equation 56248 := x ◇ (y ◇ z) = (z ◇ y) ◇ (z ◇ w)
equation 56249 := x ◇ (y ◇ z) = (z ◇ y) ◇ (w ◇ x)
equation 56250 := x ◇ (y ◇ z) = (z ◇ y) ◇ (w ◇ y)
equation 56251 := x ◇ (y ◇ z) = (z ◇ y) ◇ (w ◇ z)
equation 56252 := x ◇ (y ◇ z) = (z ◇ y) ◇ (w ◇ w)
equation 56253 := x ◇ (y ◇ z) = (z ◇ y) ◇ (w ◇ u)
equation 56254 := x ◇ (y ◇ z) = (z ◇ z) ◇ (x ◇ x)
equation 56255 := x ◇ (y ◇ z) = (z ◇ z) ◇ (x ◇ y)
equation 56256 := x ◇ (y ◇ z) = (z ◇ z) ◇ (x ◇ z)
equation 56257 := x ◇ (y ◇ z) = (z ◇ z) ◇ (x ◇ w)
equation 56258 := x ◇ (y ◇ z) = (z ◇ z) ◇ (y ◇ x)
equation 56259 := x ◇ (y ◇ z) = (z ◇ z) ◇ (y ◇ y)
equation 56260 := x ◇ (y ◇ z) = (z ◇ z) ◇ (y ◇ z)
equation 56261 := x ◇ (y ◇ z) = (z ◇ z) ◇ (y ◇ w)
equation 56262 := x ◇ (y ◇ z) = (z ◇ z) ◇ (z ◇ x)
equation 56263 := x ◇ (y ◇ z) = (z ◇ z) ◇ (z ◇ y)
equation 56264 := x ◇ (y ◇ z) = (z ◇ z) ◇ (z ◇ z)
equation 56265 := x ◇ (y ◇ z) = (z ◇ z) ◇ (z ◇ w)
equation 56266 := x ◇ (y ◇ z) = (z ◇ z) ◇ (w ◇ x)
equation 56267 := x ◇ (y ◇ z) = (z ◇ z) ◇ (w ◇ y)
equation 56268 := x ◇ (y ◇ z) = (z ◇ z) ◇ (w ◇ z)
equation 56269 := x ◇ (y ◇ z) = (z ◇ z) ◇ (w ◇ w)
equation 56270 := x ◇ (y ◇ z) = (z ◇ z) ◇ (w ◇ u)
equation 56271 := x ◇ (y ◇ z) = (z ◇ w) ◇ (x ◇ x)
equation 56272 := x ◇ (y ◇ z) = (z ◇ w) ◇ (x ◇ y)
equation 56273 := x ◇ (y ◇ z) = (z ◇ w) ◇ (x ◇ z)
equation 56274 := x ◇ (y ◇ z) = (z ◇ w) ◇ (x ◇ w)
equation 56275 := x ◇ (y ◇ z) = (z ◇ w) ◇ (x ◇ u)
equation 56276 := x ◇ (y ◇ z) = (z ◇ w) ◇ (y ◇ x)
equation 56277 := x ◇ (y ◇ z) = (z ◇ w) ◇ (y ◇ y)
equation 56278 := x ◇ (y ◇ z) = (z ◇ w) ◇ (y ◇ z)
equation 56279 := x ◇ (y ◇ z) = (z ◇ w) ◇ (y ◇ w)
equation 56280 := x ◇ (y ◇ z) = (z ◇ w) ◇ (y ◇ u)
equation 56281 := x ◇ (y ◇ z) = (z ◇ w) ◇ (z ◇ x)
equation 56282 := x ◇ (y ◇ z) = (z ◇ w) ◇ (z ◇ y)
equation 56283 := x ◇ (y ◇ z) = (z ◇ w) ◇ (z ◇ z)
equation 56284 := x ◇ (y ◇ z) = (z ◇ w) ◇ (z ◇ w)
equation 56285 := x ◇ (y ◇ z) = (z ◇ w) ◇ (z ◇ u)
equation 56286 := x ◇ (y ◇ z) = (z ◇ w) ◇ (w ◇ x)
equation 56287 := x ◇ (y ◇ z) = (z ◇ w) ◇ (w ◇ y)
equation 56288 := x ◇ (y ◇ z) = (z ◇ w) ◇ (w ◇ z)
equation 56289 := x ◇ (y ◇ z) = (z ◇ w) ◇ (w ◇ w)
equation 56290 := x ◇ (y ◇ z) = (z ◇ w) ◇ (w ◇ u)
equation 56291 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ x)
equation 56292 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ y)
equation 56293 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ z)
equation 56294 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ w)
equation 56295 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ u)
equation 56296 := x ◇ (y ◇ z) = (z ◇ w) ◇ (u ◇ v)
equation 56297 := x ◇ (y ◇ z) = (w ◇ x) ◇ (x ◇ x)
equation 56298 := x ◇ (y ◇ z) = (w ◇ x) ◇ (x ◇ y)
equation 56299 := x ◇ (y ◇ z) = (w ◇ x) ◇ (x ◇ z)
equation 56300 := x ◇ (y ◇ z) = (w ◇ x) ◇ (x ◇ w)
equation 56301 := x ◇ (y ◇ z) = (w ◇ x) ◇ (x ◇ u)
equation 56302 := x ◇ (y ◇ z) = (w ◇ x) ◇ (y ◇ x)
equation 56303 := x ◇ (y ◇ z) = (w ◇ x) ◇ (y ◇ y)
equation 56304 := x ◇ (y ◇ z) = (w ◇ x) ◇ (y ◇ z)
equation 56305 := x ◇ (y ◇ z) = (w ◇ x) ◇ (y ◇ w)
equation 56306 := x ◇ (y ◇ z) = (w ◇ x) ◇ (y ◇ u)
equation 56307 := x ◇ (y ◇ z) = (w ◇ x) ◇ (z ◇ x)
equation 56308 := x ◇ (y ◇ z) = (w ◇ x) ◇ (z ◇ y)
equation 56309 := x ◇ (y ◇ z) = (w ◇ x) ◇ (z ◇ z)
equation 56310 := x ◇ (y ◇ z) = (w ◇ x) ◇ (z ◇ w)
equation 56311 := x ◇ (y ◇ z) = (w ◇ x) ◇ (z ◇ u)
equation 56312 := x ◇ (y ◇ z) = (w ◇ x) ◇ (w ◇ x)
equation 56313 := x ◇ (y ◇ z) = (w ◇ x) ◇ (w ◇ y)
equation 56314 := x ◇ (y ◇ z) = (w ◇ x) ◇ (w ◇ z)
equation 56315 := x ◇ (y ◇ z) = (w ◇ x) ◇ (w ◇ w)
equation 56316 := x ◇ (y ◇ z) = (w ◇ x) ◇ (w ◇ u)
equation 56317 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ x)
equation 56318 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ y)
equation 56319 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ z)
equation 56320 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ w)
equation 56321 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ u)
equation 56322 := x ◇ (y ◇ z) = (w ◇ x) ◇ (u ◇ v)
equation 56323 := x ◇ (y ◇ z) = (w ◇ y) ◇ (x ◇ x)
equation 56324 := x ◇ (y ◇ z) = (w ◇ y) ◇ (x ◇ y)
equation 56325 := x ◇ (y ◇ z) = (w ◇ y) ◇ (x ◇ z)
equation 56326 := x ◇ (y ◇ z) = (w ◇ y) ◇ (x ◇ w)
equation 56327 := x ◇ (y ◇ z) = (w ◇ y) ◇ (x ◇ u)
equation 56328 := x ◇ (y ◇ z) = (w ◇ y) ◇ (y ◇ x)
equation 56329 := x ◇ (y ◇ z) = (w ◇ y) ◇ (y ◇ y)
equation 56330 := x ◇ (y ◇ z) = (w ◇ y) ◇ (y ◇ z)
equation 56331 := x ◇ (y ◇ z) = (w ◇ y) ◇ (y ◇ w)
equation 56332 := x ◇ (y ◇ z) = (w ◇ y) ◇ (y ◇ u)
equation 56333 := x ◇ (y ◇ z) = (w ◇ y) ◇ (z ◇ x)
equation 56334 := x ◇ (y ◇ z) = (w ◇ y) ◇ (z ◇ y)
equation 56335 := x ◇ (y ◇ z) = (w ◇ y) ◇ (z ◇ z)
equation 56336 := x ◇ (y ◇ z) = (w ◇ y) ◇ (z ◇ w)
equation 56337 := x ◇ (y ◇ z) = (w ◇ y) ◇ (z ◇ u)
equation 56338 := x ◇ (y ◇ z) = (w ◇ y) ◇ (w ◇ x)
equation 56339 := x ◇ (y ◇ z) = (w ◇ y) ◇ (w ◇ y)
equation 56340 := x ◇ (y ◇ z) = (w ◇ y) ◇ (w ◇ z)
equation 56341 := x ◇ (y ◇ z) = (w ◇ y) ◇ (w ◇ w)
equation 56342 := x ◇ (y ◇ z) = (w ◇ y) ◇ (w ◇ u)
equation 56343 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ x)
equation 56344 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ y)
equation 56345 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ z)
equation 56346 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ w)
equation 56347 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ u)
equation 56348 := x ◇ (y ◇ z) = (w ◇ y) ◇ (u ◇ v)
equation 56349 := x ◇ (y ◇ z) = (w ◇ z) ◇ (x ◇ x)
equation 56350 := x ◇ (y ◇ z) = (w ◇ z) ◇ (x ◇ y)
equation 56351 := x ◇ (y ◇ z) = (w ◇ z) ◇ (x ◇ z)
equation 56352 := x ◇ (y ◇ z) = (w ◇ z) ◇ (x ◇ w)
equation 56353 := x ◇ (y ◇ z) = (w ◇ z) ◇ (x ◇ u)
equation 56354 := x ◇ (y ◇ z) = (w ◇ z) ◇ (y ◇ x)
equation 56355 := x ◇ (y ◇ z) = (w ◇ z) ◇ (y ◇ y)
equation 56356 := x ◇ (y ◇ z) = (w ◇ z) ◇ (y ◇ z)
equation 56357 := x ◇ (y ◇ z) = (w ◇ z) ◇ (y ◇ w)
equation 56358 := x ◇ (y ◇ z) = (w ◇ z) ◇ (y ◇ u)
equation 56359 := x ◇ (y ◇ z) = (w ◇ z) ◇ (z ◇ x)
equation 56360 := x ◇ (y ◇ z) = (w ◇ z) ◇ (z ◇ y)
equation 56361 := x ◇ (y ◇ z) = (w ◇ z) ◇ (z ◇ z)
equation 56362 := x ◇ (y ◇ z) = (w ◇ z) ◇ (z ◇ w)
equation 56363 := x ◇ (y ◇ z) = (w ◇ z) ◇ (z ◇ u)
equation 56364 := x ◇ (y ◇ z) = (w ◇ z) ◇ (w ◇ x)
equation 56365 := x ◇ (y ◇ z) = (w ◇ z) ◇ (w ◇ y)
equation 56366 := x ◇ (y ◇ z) = (w ◇ z) ◇ (w ◇ z)
equation 56367 := x ◇ (y ◇ z) = (w ◇ z) ◇ (w ◇ w)
equation 56368 := x ◇ (y ◇ z) = (w ◇ z) ◇ (w ◇ u)
equation 56369 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ x)
equation 56370 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ y)
equation 56371 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ z)
equation 56372 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ w)
equation 56373 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ u)
equation 56374 := x ◇ (y ◇ z) = (w ◇ z) ◇ (u ◇ v)
equation 56375 := x ◇ (y ◇ z) = (w ◇ w) ◇ (x ◇ x)
equation 56376 := x ◇ (y ◇ z) = (w ◇ w) ◇ (x ◇ y)
equation 56377 := x ◇ (y ◇ z) = (w ◇ w) ◇ (x ◇ z)
equation 56378 := x ◇ (y ◇ z) = (w ◇ w) ◇ (x ◇ w)
equation 56379 := x ◇ (y ◇ z) = (w ◇ w) ◇ (x ◇ u)
equation 56380 := x ◇ (y ◇ z) = (w ◇ w) ◇ (y ◇ x)
equation 56381 := x ◇ (y ◇ z) = (w ◇ w) ◇ (y ◇ y)
equation 56382 := x ◇ (y ◇ z) = (w ◇ w) ◇ (y ◇ z)
equation 56383 := x ◇ (y ◇ z) = (w ◇ w) ◇ (y ◇ w)
equation 56384 := x ◇ (y ◇ z) = (w ◇ w) ◇ (y ◇ u)
equation 56385 := x ◇ (y ◇ z) = (w ◇ w) ◇ (z ◇ x)
equation 56386 := x ◇ (y ◇ z) = (w ◇ w) ◇ (z ◇ y)
equation 56387 := x ◇ (y ◇ z) = (w ◇ w) ◇ (z ◇ z)
equation 56388 := x ◇ (y ◇ z) = (w ◇ w) ◇ (z ◇ w)
equation 56389 := x ◇ (y ◇ z) = (w ◇ w) ◇ (z ◇ u)
equation 56390 := x ◇ (y ◇ z) = (w ◇ w) ◇ (w ◇ x)
equation 56391 := x ◇ (y ◇ z) = (w ◇ w) ◇ (w ◇ y)
equation 56392 := x ◇ (y ◇ z) = (w ◇ w) ◇ (w ◇ z)
equation 56393 := x ◇ (y ◇ z) = (w ◇ w) ◇ (w ◇ w)
equation 56394 := x ◇ (y ◇ z) = (w ◇ w) ◇ (w ◇ u)
equation 56395 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ x)
equation 56396 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ y)
equation 56397 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ z)
equation 56398 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ w)
equation 56399 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ u)
equation 56400 := x ◇ (y ◇ z) = (w ◇ w) ◇ (u ◇ v)
equation 56401 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ x)
equation 56402 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ y)
equation 56403 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ z)
equation 56404 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ w)
equation 56405 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ u)
equation 56406 := x ◇ (y ◇ z) = (w ◇ u) ◇ (x ◇ v)
equation 56407 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ x)
equation 56408 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ y)
equation 56409 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ z)
equation 56410 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ w)
equation 56411 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ u)
equation 56412 := x ◇ (y ◇ z) = (w ◇ u) ◇ (y ◇ v)
equation 56413 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ x)
equation 56414 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ y)
equation 56415 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ z)
equation 56416 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ w)
equation 56417 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ u)
equation 56418 := x ◇ (y ◇ z) = (w ◇ u) ◇ (z ◇ v)
equation 56419 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ x)
equation 56420 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ y)
equation 56421 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ z)
equation 56422 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ w)
equation 56423 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ u)
equation 56424 := x ◇ (y ◇ z) = (w ◇ u) ◇ (w ◇ v)
equation 56425 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ x)
equation 56426 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ y)
equation 56427 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ z)
equation 56428 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ w)
equation 56429 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ u)
equation 56430 := x ◇ (y ◇ z) = (w ◇ u) ◇ (u ◇ v)
equation 56431 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ x)
equation 56432 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ y)
equation 56433 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ z)
equation 56434 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ w)
equation 56435 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ u)
equation 56436 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ v)
equation 56437 := x ◇ (y ◇ z) = (w ◇ u) ◇ (v ◇ r)
equation 56438 := x ◇ (x ◇ x) = (x ◇ (x ◇ x)) ◇ x
equation 56439 := x ◇ (x ◇ x) = (x ◇ (x ◇ x)) ◇ y
equation 56440 := x ◇ (x ◇ x) = (x ◇ (x ◇ y)) ◇ x
equation 56441 := x ◇ (x ◇ x) = (x ◇ (x ◇ y)) ◇ y
equation 56442 := x ◇ (x ◇ x) = (x ◇ (x ◇ y)) ◇ z
equation 56443 := x ◇ (x ◇ x) = (x ◇ (y ◇ x)) ◇ x
equation 56444 := x ◇ (x ◇ x) = (x ◇ (y ◇ x)) ◇ y
equation 56445 := x ◇ (x ◇ x) = (x ◇ (y ◇ x)) ◇ z
equation 56446 := x ◇ (x ◇ x) = (x ◇ (y ◇ y)) ◇ x
equation 56447 := x ◇ (x ◇ x) = (x ◇ (y ◇ y)) ◇ y
equation 56448 := x ◇ (x ◇ x) = (x ◇ (y ◇ y)) ◇ z
equation 56449 := x ◇ (x ◇ x) = (x ◇ (y ◇ z)) ◇ x
equation 56450 := x ◇ (x ◇ x) = (x ◇ (y ◇ z)) ◇ y
equation 56451 := x ◇ (x ◇ x) = (x ◇ (y ◇ z)) ◇ z
equation 56452 := x ◇ (x ◇ x) = (x ◇ (y ◇ z)) ◇ w
equation 56453 := x ◇ (x ◇ x) = (y ◇ (x ◇ x)) ◇ x
equation 56454 := x ◇ (x ◇ x) = (y ◇ (x ◇ x)) ◇ y
equation 56455 := x ◇ (x ◇ x) = (y ◇ (x ◇ x)) ◇ z
equation 56456 := x ◇ (x ◇ x) = (y ◇ (x ◇ y)) ◇ x
equation 56457 := x ◇ (x ◇ x) = (y ◇ (x ◇ y)) ◇ y
equation 56458 := x ◇ (x ◇ x) = (y ◇ (x ◇ y)) ◇ z
equation 56459 := x ◇ (x ◇ x) = (y ◇ (x ◇ z)) ◇ x
equation 56460 := x ◇ (x ◇ x) = (y ◇ (x ◇ z)) ◇ y
equation 56461 := x ◇ (x ◇ x) = (y ◇ (x ◇ z)) ◇ z
equation 56462 := x ◇ (x ◇ x) = (y ◇ (x ◇ z)) ◇ w
equation 56463 := x ◇ (x ◇ x) = (y ◇ (y ◇ x)) ◇ x
equation 56464 := x ◇ (x ◇ x) = (y ◇ (y ◇ x)) ◇ y
equation 56465 := x ◇ (x ◇ x) = (y ◇ (y ◇ x)) ◇ z
equation 56466 := x ◇ (x ◇ x) = (y ◇ (y ◇ y)) ◇ x
equation 56467 := x ◇ (x ◇ x) = (y ◇ (y ◇ y)) ◇ y
equation 56468 := x ◇ (x ◇ x) = (y ◇ (y ◇ y)) ◇ z
equation 56469 := x ◇ (x ◇ x) = (y ◇ (y ◇ z)) ◇ x
equation 56470 := x ◇ (x ◇ x) = (y ◇ (y ◇ z)) ◇ y
equation 56471 := x ◇ (x ◇ x) = (y ◇ (y ◇ z)) ◇ z
equation 56472 := x ◇ (x ◇ x) = (y ◇ (y ◇ z)) ◇ w
equation 56473 := x ◇ (x ◇ x) = (y ◇ (z ◇ x)) ◇ x
equation 56474 := x ◇ (x ◇ x) = (y ◇ (z ◇ x)) ◇ y
equation 56475 := x ◇ (x ◇ x) = (y ◇ (z ◇ x)) ◇ z
equation 56476 := x ◇ (x ◇ x) = (y ◇ (z ◇ x)) ◇ w
equation 56477 := x ◇ (x ◇ x) = (y ◇ (z ◇ y)) ◇ x
equation 56478 := x ◇ (x ◇ x) = (y ◇ (z ◇ y)) ◇ y
equation 56479 := x ◇ (x ◇ x) = (y ◇ (z ◇ y)) ◇ z
equation 56480 := x ◇ (x ◇ x) = (y ◇ (z ◇ y)) ◇ w
equation 56481 := x ◇ (x ◇ x) = (y ◇ (z ◇ z)) ◇ x
equation 56482 := x ◇ (x ◇ x) = (y ◇ (z ◇ z)) ◇ y
equation 56483 := x ◇ (x ◇ x) = (y ◇ (z ◇ z)) ◇ z
equation 56484 := x ◇ (x ◇ x) = (y ◇ (z ◇ z)) ◇ w
equation 56485 := x ◇ (x ◇ x) = (y ◇ (z ◇ w)) ◇ x
equation 56486 := x ◇ (x ◇ x) = (y ◇ (z ◇ w)) ◇ y
equation 56487 := x ◇ (x ◇ x) = (y ◇ (z ◇ w)) ◇ z
equation 56488 := x ◇ (x ◇ x) = (y ◇ (z ◇ w)) ◇ w
equation 56489 := x ◇ (x ◇ x) = (y ◇ (z ◇ w)) ◇ u
equation 56490 := x ◇ (x ◇ y) = (x ◇ (x ◇ x)) ◇ x
equation 56491 := x ◇ (x ◇ y) = (x ◇ (x ◇ x)) ◇ y
equation 56492 := x ◇ (x ◇ y) = (x ◇ (x ◇ x)) ◇ z
equation 56493 := x ◇ (x ◇ y) = (x ◇ (x ◇ y)) ◇ x
equation 56494 := x ◇ (x ◇ y) = (x ◇ (x ◇ y)) ◇ y
equation 56495 := x ◇ (x ◇ y) = (x ◇ (x ◇ y)) ◇ z
equation 56496 := x ◇ (x ◇ y) = (x ◇ (x ◇ z)) ◇ x
equation 56497 := x ◇ (x ◇ y) = (x ◇ (x ◇ z)) ◇ y
equation 56498 := x ◇ (x ◇ y) = (x ◇ (x ◇ z)) ◇ z
equation 56499 := x ◇ (x ◇ y) = (x ◇ (x ◇ z)) ◇ w
equation 56500 := x ◇ (x ◇ y) = (x ◇ (y ◇ x)) ◇ x
equation 56501 := x ◇ (x ◇ y) = (x ◇ (y ◇ x)) ◇ y
equation 56502 := x ◇ (x ◇ y) = (x ◇ (y ◇ x)) ◇ z
equation 56503 := x ◇ (x ◇ y) = (x ◇ (y ◇ y)) ◇ x
equation 56504 := x ◇ (x ◇ y) = (x ◇ (y ◇ y)) ◇ y
equation 56505 := x ◇ (x ◇ y) = (x ◇ (y ◇ y)) ◇ z
equation 56506 := x ◇ (x ◇ y) = (x ◇ (y ◇ z)) ◇ x
equation 56507 := x ◇ (x ◇ y) = (x ◇ (y ◇ z)) ◇ y
equation 56508 := x ◇ (x ◇ y) = (x ◇ (y ◇ z)) ◇ z
equation 56509 := x ◇ (x ◇ y) = (x ◇ (y ◇ z)) ◇ w
equation 56510 := x ◇ (x ◇ y) = (x ◇ (z ◇ x)) ◇ x
equation 56511 := x ◇ (x ◇ y) = (x ◇ (z ◇ x)) ◇ y
equation 56512 := x ◇ (x ◇ y) = (x ◇ (z ◇ x)) ◇ z
equation 56513 := x ◇ (x ◇ y) = (x ◇ (z ◇ x)) ◇ w
equation 56514 := x ◇ (x ◇ y) = (x ◇ (z ◇ y)) ◇ x
equation 56515 := x ◇ (x ◇ y) = (x ◇ (z ◇ y)) ◇ y
equation 56516 := x ◇ (x ◇ y) = (x ◇ (z ◇ y)) ◇ z
equation 56517 := x ◇ (x ◇ y) = (x ◇ (z ◇ y)) ◇ w
equation 56518 := x ◇ (x ◇ y) = (x ◇ (z ◇ z)) ◇ x
equation 56519 := x ◇ (x ◇ y) = (x ◇ (z ◇ z)) ◇ y
equation 56520 := x ◇ (x ◇ y) = (x ◇ (z ◇ z)) ◇ z
equation 56521 := x ◇ (x ◇ y) = (x ◇ (z ◇ z)) ◇ w
equation 56522 := x ◇ (x ◇ y) = (x ◇ (z ◇ w)) ◇ x
equation 56523 := x ◇ (x ◇ y) = (x ◇ (z ◇ w)) ◇ y
equation 56524 := x ◇ (x ◇ y) = (x ◇ (z ◇ w)) ◇ z
equation 56525 := x ◇ (x ◇ y) = (x ◇ (z ◇ w)) ◇ w
equation 56526 := x ◇ (x ◇ y) = (x ◇ (z ◇ w)) ◇ u
equation 56527 := x ◇ (x ◇ y) = (y ◇ (x ◇ x)) ◇ x
equation 56528 := x ◇ (x ◇ y) = (y ◇ (x ◇ x)) ◇ y
equation 56529 := x ◇ (x ◇ y) = (y ◇ (x ◇ x)) ◇ z
equation 56530 := x ◇ (x ◇ y) = (y ◇ (x ◇ y)) ◇ x
equation 56531 := x ◇ (x ◇ y) = (y ◇ (x ◇ y)) ◇ y
equation 56532 := x ◇ (x ◇ y) = (y ◇ (x ◇ y)) ◇ z
equation 56533 := x ◇ (x ◇ y) = (y ◇ (x ◇ z)) ◇ x
equation 56534 := x ◇ (x ◇ y) = (y ◇ (x ◇ z)) ◇ y
equation 56535 := x ◇ (x ◇ y) = (y ◇ (x ◇ z)) ◇ z
equation 56536 := x ◇ (x ◇ y) = (y ◇ (x ◇ z)) ◇ w
equation 56537 := x ◇ (x ◇ y) = (y ◇ (y ◇ x)) ◇ x
equation 56538 := x ◇ (x ◇ y) = (y ◇ (y ◇ x)) ◇ y
equation 56539 := x ◇ (x ◇ y) = (y ◇ (y ◇ x)) ◇ z
equation 56540 := x ◇ (x ◇ y) = (y ◇ (y ◇ y)) ◇ x
equation 56541 := x ◇ (x ◇ y) = (y ◇ (y ◇ y)) ◇ y
equation 56542 := x ◇ (x ◇ y) = (y ◇ (y ◇ y)) ◇ z
equation 56543 := x ◇ (x ◇ y) = (y ◇ (y ◇ z)) ◇ x
equation 56544 := x ◇ (x ◇ y) = (y ◇ (y ◇ z)) ◇ y
equation 56545 := x ◇ (x ◇ y) = (y ◇ (y ◇ z)) ◇ z
equation 56546 := x ◇ (x ◇ y) = (y ◇ (y ◇ z)) ◇ w
equation 56547 := x ◇ (x ◇ y) = (y ◇ (z ◇ x)) ◇ x
equation 56548 := x ◇ (x ◇ y) = (y ◇ (z ◇ x)) ◇ y
equation 56549 := x ◇ (x ◇ y) = (y ◇ (z ◇ x)) ◇ z
equation 56550 := x ◇ (x ◇ y) = (y ◇ (z ◇ x)) ◇ w
equation 56551 := x ◇ (x ◇ y) = (y ◇ (z ◇ y)) ◇ x
equation 56552 := x ◇ (x ◇ y) = (y ◇ (z ◇ y)) ◇ y
equation 56553 := x ◇ (x ◇ y) = (y ◇ (z ◇ y)) ◇ z
equation 56554 := x ◇ (x ◇ y) = (y ◇ (z ◇ y)) ◇ w
equation 56555 := x ◇ (x ◇ y) = (y ◇ (z ◇ z)) ◇ x
equation 56556 := x ◇ (x ◇ y) = (y ◇ (z ◇ z)) ◇ y
equation 56557 := x ◇ (x ◇ y) = (y ◇ (z ◇ z)) ◇ z
equation 56558 := x ◇ (x ◇ y) = (y ◇ (z ◇ z)) ◇ w
equation 56559 := x ◇ (x ◇ y) = (y ◇ (z ◇ w)) ◇ x
equation 56560 := x ◇ (x ◇ y) = (y ◇ (z ◇ w)) ◇ y
equation 56561 := x ◇ (x ◇ y) = (y ◇ (z ◇ w)) ◇ z
equation 56562 := x ◇ (x ◇ y) = (y ◇ (z ◇ w)) ◇ w
equation 56563 := x ◇ (x ◇ y) = (y ◇ (z ◇ w)) ◇ u
equation 56564 := x ◇ (x ◇ y) = (z ◇ (x ◇ x)) ◇ x
equation 56565 := x ◇ (x ◇ y) = (z ◇ (x ◇ x)) ◇ y
equation 56566 := x ◇ (x ◇ y) = (z ◇ (x ◇ x)) ◇ z
equation 56567 := x ◇ (x ◇ y) = (z ◇ (x ◇ x)) ◇ w
equation 56568 := x ◇ (x ◇ y) = (z ◇ (x ◇ y)) ◇ x
equation 56569 := x ◇ (x ◇ y) = (z ◇ (x ◇ y)) ◇ y
equation 56570 := x ◇ (x ◇ y) = (z ◇ (x ◇ y)) ◇ z
equation 56571 := x ◇ (x ◇ y) = (z ◇ (x ◇ y)) ◇ w
equation 56572 := x ◇ (x ◇ y) = (z ◇ (x ◇ z)) ◇ x
equation 56573 := x ◇ (x ◇ y) = (z ◇ (x ◇ z)) ◇ y
equation 56574 := x ◇ (x ◇ y) = (z ◇ (x ◇ z)) ◇ z
equation 56575 := x ◇ (x ◇ y) = (z ◇ (x ◇ z)) ◇ w
equation 56576 := x ◇ (x ◇ y) = (z ◇ (x ◇ w)) ◇ x
equation 56577 := x ◇ (x ◇ y) = (z ◇ (x ◇ w)) ◇ y
equation 56578 := x ◇ (x ◇ y) = (z ◇ (x ◇ w)) ◇ z
equation 56579 := x ◇ (x ◇ y) = (z ◇ (x ◇ w)) ◇ w
equation 56580 := x ◇ (x ◇ y) = (z ◇ (x ◇ w)) ◇ u
equation 56581 := x ◇ (x ◇ y) = (z ◇ (y ◇ x)) ◇ x
equation 56582 := x ◇ (x ◇ y) = (z ◇ (y ◇ x)) ◇ y
equation 56583 := x ◇ (x ◇ y) = (z ◇ (y ◇ x)) ◇ z
equation 56584 := x ◇ (x ◇ y) = (z ◇ (y ◇ x)) ◇ w
equation 56585 := x ◇ (x ◇ y) = (z ◇ (y ◇ y)) ◇ x
equation 56586 := x ◇ (x ◇ y) = (z ◇ (y ◇ y)) ◇ y
equation 56587 := x ◇ (x ◇ y) = (z ◇ (y ◇ y)) ◇ z
equation 56588 := x ◇ (x ◇ y) = (z ◇ (y ◇ y)) ◇ w
equation 56589 := x ◇ (x ◇ y) = (z ◇ (y ◇ z)) ◇ x
equation 56590 := x ◇ (x ◇ y) = (z ◇ (y ◇ z)) ◇ y
equation 56591 := x ◇ (x ◇ y) = (z ◇ (y ◇ z)) ◇ z
equation 56592 := x ◇ (x ◇ y) = (z ◇ (y ◇ z)) ◇ w
equation 56593 := x ◇ (x ◇ y) = (z ◇ (y ◇ w)) ◇ x
equation 56594 := x ◇ (x ◇ y) = (z ◇ (y ◇ w)) ◇ y
equation 56595 := x ◇ (x ◇ y) = (z ◇ (y ◇ w)) ◇ z
equation 56596 := x ◇ (x ◇ y) = (z ◇ (y ◇ w)) ◇ w
equation 56597 := x ◇ (x ◇ y) = (z ◇ (y ◇ w)) ◇ u
equation 56598 := x ◇ (x ◇ y) = (z ◇ (z ◇ x)) ◇ x
equation 56599 := x ◇ (x ◇ y) = (z ◇ (z ◇ x)) ◇ y
equation 56600 := x ◇ (x ◇ y) = (z ◇ (z ◇ x)) ◇ z
equation 56601 := x ◇ (x ◇ y) = (z ◇ (z ◇ x)) ◇ w
equation 56602 := x ◇ (x ◇ y) = (z ◇ (z ◇ y)) ◇ x
equation 56603 := x ◇ (x ◇ y) = (z ◇ (z ◇ y)) ◇ y
equation 56604 := x ◇ (x ◇ y) = (z ◇ (z ◇ y)) ◇ z
equation 56605 := x ◇ (x ◇ y) = (z ◇ (z ◇ y)) ◇ w
equation 56606 := x ◇ (x ◇ y) = (z ◇ (z ◇ z)) ◇ x
equation 56607 := x ◇ (x ◇ y) = (z ◇ (z ◇ z)) ◇ y
equation 56608 := x ◇ (x ◇ y) = (z ◇ (z ◇ z)) ◇ z
equation 56609 := x ◇ (x ◇ y) = (z ◇ (z ◇ z)) ◇ w
equation 56610 := x ◇ (x ◇ y) = (z ◇ (z ◇ w)) ◇ x
equation 56611 := x ◇ (x ◇ y) = (z ◇ (z ◇ w)) ◇ y
equation 56612 := x ◇ (x ◇ y) = (z ◇ (z ◇ w)) ◇ z
equation 56613 := x ◇ (x ◇ y) = (z ◇ (z ◇ w)) ◇ w
equation 56614 := x ◇ (x ◇ y) = (z ◇ (z ◇ w)) ◇ u
equation 56615 := x ◇ (x ◇ y) = (z ◇ (w ◇ x)) ◇ x
equation 56616 := x ◇ (x ◇ y) = (z ◇ (w ◇ x)) ◇ y
equation 56617 := x ◇ (x ◇ y) = (z ◇ (w ◇ x)) ◇ z
equation 56618 := x ◇ (x ◇ y) = (z ◇ (w ◇ x)) ◇ w
equation 56619 := x ◇ (x ◇ y) = (z ◇ (w ◇ x)) ◇ u
equation 56620 := x ◇ (x ◇ y) = (z ◇ (w ◇ y)) ◇ x
equation 56621 := x ◇ (x ◇ y) = (z ◇ (w ◇ y)) ◇ y
equation 56622 := x ◇ (x ◇ y) = (z ◇ (w ◇ y)) ◇ z
equation 56623 := x ◇ (x ◇ y) = (z ◇ (w ◇ y)) ◇ w
equation 56624 := x ◇ (x ◇ y) = (z ◇ (w ◇ y)) ◇ u
equation 56625 := x ◇ (x ◇ y) = (z ◇ (w ◇ z)) ◇ x
equation 56626 := x ◇ (x ◇ y) = (z ◇ (w ◇ z)) ◇ y
equation 56627 := x ◇ (x ◇ y) = (z ◇ (w ◇ z)) ◇ z
equation 56628 := x ◇ (x ◇ y) = (z ◇ (w ◇ z)) ◇ w
equation 56629 := x ◇ (x ◇ y) = (z ◇ (w ◇ z)) ◇ u
equation 56630 := x ◇ (x ◇ y) = (z ◇ (w ◇ w)) ◇ x
equation 56631 := x ◇ (x ◇ y) = (z ◇ (w ◇ w)) ◇ y
equation 56632 := x ◇ (x ◇ y) = (z ◇ (w ◇ w)) ◇ z
equation 56633 := x ◇ (x ◇ y) = (z ◇ (w ◇ w)) ◇ w
equation 56634 := x ◇ (x ◇ y) = (z ◇ (w ◇ w)) ◇ u
equation 56635 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ x
equation 56636 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ y
equation 56637 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ z
equation 56638 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ w
equation 56639 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ u
equation 56640 := x ◇ (x ◇ y) = (z ◇ (w ◇ u)) ◇ v
equation 56641 := x ◇ (y ◇ x) = (x ◇ (x ◇ x)) ◇ x
equation 56642 := x ◇ (y ◇ x) = (x ◇ (x ◇ x)) ◇ y
equation 56643 := x ◇ (y ◇ x) = (x ◇ (x ◇ x)) ◇ z
equation 56644 := x ◇ (y ◇ x) = (x ◇ (x ◇ y)) ◇ x
equation 56645 := x ◇ (y ◇ x) = (x ◇ (x ◇ y)) ◇ y
equation 56646 := x ◇ (y ◇ x) = (x ◇ (x ◇ y)) ◇ z
equation 56647 := x ◇ (y ◇ x) = (x ◇ (x ◇ z)) ◇ x
equation 56648 := x ◇ (y ◇ x) = (x ◇ (x ◇ z)) ◇ y
equation 56649 := x ◇ (y ◇ x) = (x ◇ (x ◇ z)) ◇ z
equation 56650 := x ◇ (y ◇ x) = (x ◇ (x ◇ z)) ◇ w
equation 56651 := x ◇ (y ◇ x) = (x ◇ (y ◇ x)) ◇ x
equation 56652 := x ◇ (y ◇ x) = (x ◇ (y ◇ x)) ◇ y
equation 56653 := x ◇ (y ◇ x) = (x ◇ (y ◇ x)) ◇ z
equation 56654 := x ◇ (y ◇ x) = (x ◇ (y ◇ y)) ◇ x
equation 56655 := x ◇ (y ◇ x) = (x ◇ (y ◇ y)) ◇ y
equation 56656 := x ◇ (y ◇ x) = (x ◇ (y ◇ y)) ◇ z
equation 56657 := x ◇ (y ◇ x) = (x ◇ (y ◇ z)) ◇ x
equation 56658 := x ◇ (y ◇ x) = (x ◇ (y ◇ z)) ◇ y
equation 56659 := x ◇ (y ◇ x) = (x ◇ (y ◇ z)) ◇ z
equation 56660 := x ◇ (y ◇ x) = (x ◇ (y ◇ z)) ◇ w
equation 56661 := x ◇ (y ◇ x) = (x ◇ (z ◇ x)) ◇ x
equation 56662 := x ◇ (y ◇ x) = (x ◇ (z ◇ x)) ◇ y
equation 56663 := x ◇ (y ◇ x) = (x ◇ (z ◇ x)) ◇ z
equation 56664 := x ◇ (y ◇ x) = (x ◇ (z ◇ x)) ◇ w
equation 56665 := x ◇ (y ◇ x) = (x ◇ (z ◇ y)) ◇ x
equation 56666 := x ◇ (y ◇ x) = (x ◇ (z ◇ y)) ◇ y
equation 56667 := x ◇ (y ◇ x) = (x ◇ (z ◇ y)) ◇ z
equation 56668 := x ◇ (y ◇ x) = (x ◇ (z ◇ y)) ◇ w
equation 56669 := x ◇ (y ◇ x) = (x ◇ (z ◇ z)) ◇ x
equation 56670 := x ◇ (y ◇ x) = (x ◇ (z ◇ z)) ◇ y
equation 56671 := x ◇ (y ◇ x) = (x ◇ (z ◇ z)) ◇ z
equation 56672 := x ◇ (y ◇ x) = (x ◇ (z ◇ z)) ◇ w
equation 56673 := x ◇ (y ◇ x) = (x ◇ (z ◇ w)) ◇ x
equation 56674 := x ◇ (y ◇ x) = (x ◇ (z ◇ w)) ◇ y
equation 56675 := x ◇ (y ◇ x) = (x ◇ (z ◇ w)) ◇ z
equation 56676 := x ◇ (y ◇ x) = (x ◇ (z ◇ w)) ◇ w
equation 56677 := x ◇ (y ◇ x) = (x ◇ (z ◇ w)) ◇ u
equation 56678 := x ◇ (y ◇ x) = (y ◇ (x ◇ x)) ◇ x
equation 56679 := x ◇ (y ◇ x) = (y ◇ (x ◇ x)) ◇ y
equation 56680 := x ◇ (y ◇ x) = (y ◇ (x ◇ x)) ◇ z
equation 56681 := x ◇ (y ◇ x) = (y ◇ (x ◇ y)) ◇ x
equation 56682 := x ◇ (y ◇ x) = (y ◇ (x ◇ y)) ◇ y
equation 56683 := x ◇ (y ◇ x) = (y ◇ (x ◇ y)) ◇ z
equation 56684 := x ◇ (y ◇ x) = (y ◇ (x ◇ z)) ◇ x
equation 56685 := x ◇ (y ◇ x) = (y ◇ (x ◇ z)) ◇ y
equation 56686 := x ◇ (y ◇ x) = (y ◇ (x ◇ z)) ◇ z
equation 56687 := x ◇ (y ◇ x) = (y ◇ (x ◇ z)) ◇ w
equation 56688 := x ◇ (y ◇ x) = (y ◇ (y ◇ x)) ◇ x
equation 56689 := x ◇ (y ◇ x) = (y ◇ (y ◇ x)) ◇ y
equation 56690 := x ◇ (y ◇ x) = (y ◇ (y ◇ x)) ◇ z
equation 56691 := x ◇ (y ◇ x) = (y ◇ (y ◇ y)) ◇ x
equation 56692 := x ◇ (y ◇ x) = (y ◇ (y ◇ y)) ◇ y
equation 56693 := x ◇ (y ◇ x) = (y ◇ (y ◇ y)) ◇ z
equation 56694 := x ◇ (y ◇ x) = (y ◇ (y ◇ z)) ◇ x
equation 56695 := x ◇ (y ◇ x) = (y ◇ (y ◇ z)) ◇ y
equation 56696 := x ◇ (y ◇ x) = (y ◇ (y ◇ z)) ◇ z
equation 56697 := x ◇ (y ◇ x) = (y ◇ (y ◇ z)) ◇ w
equation 56698 := x ◇ (y ◇ x) = (y ◇ (z ◇ x)) ◇ x
equation 56699 := x ◇ (y ◇ x) = (y ◇ (z ◇ x)) ◇ y
equation 56700 := x ◇ (y ◇ x) = (y ◇ (z ◇ x)) ◇ z
equation 56701 := x ◇ (y ◇ x) = (y ◇ (z ◇ x)) ◇ w
equation 56702 := x ◇ (y ◇ x) = (y ◇ (z ◇ y)) ◇ x
equation 56703 := x ◇ (y ◇ x) = (y ◇ (z ◇ y)) ◇ y
equation 56704 := x ◇ (y ◇ x) = (y ◇ (z ◇ y)) ◇ z
equation 56705 := x ◇ (y ◇ x) = (y ◇ (z ◇ y)) ◇ w
equation 56706 := x ◇ (y ◇ x) = (y ◇ (z ◇ z)) ◇ x
equation 56707 := x ◇ (y ◇ x) = (y ◇ (z ◇ z)) ◇ y
equation 56708 := x ◇ (y ◇ x) = (y ◇ (z ◇ z)) ◇ z
equation 56709 := x ◇ (y ◇ x) = (y ◇ (z ◇ z)) ◇ w
equation 56710 := x ◇ (y ◇ x) = (y ◇ (z ◇ w)) ◇ x
equation 56711 := x ◇ (y ◇ x) = (y ◇ (z ◇ w)) ◇ y
equation 56712 := x ◇ (y ◇ x) = (y ◇ (z ◇ w)) ◇ z
equation 56713 := x ◇ (y ◇ x) = (y ◇ (z ◇ w)) ◇ w
equation 56714 := x ◇ (y ◇ x) = (y ◇ (z ◇ w)) ◇ u
equation 56715 := x ◇ (y ◇ x) = (z ◇ (x ◇ x)) ◇ x
equation 56716 := x ◇ (y ◇ x) = (z ◇ (x ◇ x)) ◇ y
equation 56717 := x ◇ (y ◇ x) = (z ◇ (x ◇ x)) ◇ z
equation 56718 := x ◇ (y ◇ x) = (z ◇ (x ◇ x)) ◇ w
equation 56719 := x ◇ (y ◇ x) = (z ◇ (x ◇ y)) ◇ x
equation 56720 := x ◇ (y ◇ x) = (z ◇ (x ◇ y)) ◇ y
equation 56721 := x ◇ (y ◇ x) = (z ◇ (x ◇ y)) ◇ z
equation 56722 := x ◇ (y ◇ x) = (z ◇ (x ◇ y)) ◇ w
equation 56723 := x ◇ (y ◇ x) = (z ◇ (x ◇ z)) ◇ x
equation 56724 := x ◇ (y ◇ x) = (z ◇ (x ◇ z)) ◇ y
equation 56725 := x ◇ (y ◇ x) = (z ◇ (x ◇ z)) ◇ z
equation 56726 := x ◇ (y ◇ x) = (z ◇ (x ◇ z)) ◇ w
equation 56727 := x ◇ (y ◇ x) = (z ◇ (x ◇ w)) ◇ x
equation 56728 := x ◇ (y ◇ x) = (z ◇ (x ◇ w)) ◇ y
equation 56729 := x ◇ (y ◇ x) = (z ◇ (x ◇ w)) ◇ z
equation 56730 := x ◇ (y ◇ x) = (z ◇ (x ◇ w)) ◇ w
equation 56731 := x ◇ (y ◇ x) = (z ◇ (x ◇ w)) ◇ u
equation 56732 := x ◇ (y ◇ x) = (z ◇ (y ◇ x)) ◇ x
equation 56733 := x ◇ (y ◇ x) = (z ◇ (y ◇ x)) ◇ y
equation 56734 := x ◇ (y ◇ x) = (z ◇ (y ◇ x)) ◇ z
equation 56735 := x ◇ (y ◇ x) = (z ◇ (y ◇ x)) ◇ w
equation 56736 := x ◇ (y ◇ x) = (z ◇ (y ◇ y)) ◇ x
equation 56737 := x ◇ (y ◇ x) = (z ◇ (y ◇ y)) ◇ y
equation 56738 := x ◇ (y ◇ x) = (z ◇ (y ◇ y)) ◇ z
equation 56739 := x ◇ (y ◇ x) = (z ◇ (y ◇ y)) ◇ w
equation 56740 := x ◇ (y ◇ x) = (z ◇ (y ◇ z)) ◇ x
equation 56741 := x ◇ (y ◇ x) = (z ◇ (y ◇ z)) ◇ y
equation 56742 := x ◇ (y ◇ x) = (z ◇ (y ◇ z)) ◇ z
equation 56743 := x ◇ (y ◇ x) = (z ◇ (y ◇ z)) ◇ w
equation 56744 := x ◇ (y ◇ x) = (z ◇ (y ◇ w)) ◇ x
equation 56745 := x ◇ (y ◇ x) = (z ◇ (y ◇ w)) ◇ y
equation 56746 := x ◇ (y ◇ x) = (z ◇ (y ◇ w)) ◇ z
equation 56747 := x ◇ (y ◇ x) = (z ◇ (y ◇ w)) ◇ w
equation 56748 := x ◇ (y ◇ x) = (z ◇ (y ◇ w)) ◇ u
equation 56749 := x ◇ (y ◇ x) = (z ◇ (z ◇ x)) ◇ x
equation 56750 := x ◇ (y ◇ x) = (z ◇ (z ◇ x)) ◇ y
equation 56751 := x ◇ (y ◇ x) = (z ◇ (z ◇ x)) ◇ z
equation 56752 := x ◇ (y ◇ x) = (z ◇ (z ◇ x)) ◇ w
equation 56753 := x ◇ (y ◇ x) = (z ◇ (z ◇ y)) ◇ x
equation 56754 := x ◇ (y ◇ x) = (z ◇ (z ◇ y)) ◇ y
equation 56755 := x ◇ (y ◇ x) = (z ◇ (z ◇ y)) ◇ z
equation 56756 := x ◇ (y ◇ x) = (z ◇ (z ◇ y)) ◇ w
equation 56757 := x ◇ (y ◇ x) = (z ◇ (z ◇ z)) ◇ x
equation 56758 := x ◇ (y ◇ x) = (z ◇ (z ◇ z)) ◇ y
equation 56759 := x ◇ (y ◇ x) = (z ◇ (z ◇ z)) ◇ z
equation 56760 := x ◇ (y ◇ x) = (z ◇ (z ◇ z)) ◇ w
equation 56761 := x ◇ (y ◇ x) = (z ◇ (z ◇ w)) ◇ x
equation 56762 := x ◇ (y ◇ x) = (z ◇ (z ◇ w)) ◇ y
equation 56763 := x ◇ (y ◇ x) = (z ◇ (z ◇ w)) ◇ z
equation 56764 := x ◇ (y ◇ x) = (z ◇ (z ◇ w)) ◇ w
equation 56765 := x ◇ (y ◇ x) = (z ◇ (z ◇ w)) ◇ u
equation 56766 := x ◇ (y ◇ x) = (z ◇ (w ◇ x)) ◇ x
equation 56767 := x ◇ (y ◇ x) = (z ◇ (w ◇ x)) ◇ y
equation 56768 := x ◇ (y ◇ x) = (z ◇ (w ◇ x)) ◇ z
equation 56769 := x ◇ (y ◇ x) = (z ◇ (w ◇ x)) ◇ w
equation 56770 := x ◇ (y ◇ x) = (z ◇ (w ◇ x)) ◇ u
equation 56771 := x ◇ (y ◇ x) = (z ◇ (w ◇ y)) ◇ x
equation 56772 := x ◇ (y ◇ x) = (z ◇ (w ◇ y)) ◇ y
equation 56773 := x ◇ (y ◇ x) = (z ◇ (w ◇ y)) ◇ z
equation 56774 := x ◇ (y ◇ x) = (z ◇ (w ◇ y)) ◇ w
equation 56775 := x ◇ (y ◇ x) = (z ◇ (w ◇ y)) ◇ u
equation 56776 := x ◇ (y ◇ x) = (z ◇ (w ◇ z)) ◇ x
equation 56777 := x ◇ (y ◇ x) = (z ◇ (w ◇ z)) ◇ y
equation 56778 := x ◇ (y ◇ x) = (z ◇ (w ◇ z)) ◇ z
equation 56779 := x ◇ (y ◇ x) = (z ◇ (w ◇ z)) ◇ w
equation 56780 := x ◇ (y ◇ x) = (z ◇ (w ◇ z)) ◇ u
equation 56781 := x ◇ (y ◇ x) = (z ◇ (w ◇ w)) ◇ x
equation 56782 := x ◇ (y ◇ x) = (z ◇ (w ◇ w)) ◇ y
equation 56783 := x ◇ (y ◇ x) = (z ◇ (w ◇ w)) ◇ z
equation 56784 := x ◇ (y ◇ x) = (z ◇ (w ◇ w)) ◇ w
equation 56785 := x ◇ (y ◇ x) = (z ◇ (w ◇ w)) ◇ u
equation 56786 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ x
equation 56787 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ y
equation 56788 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ z
equation 56789 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ w
equation 56790 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ u
equation 56791 := x ◇ (y ◇ x) = (z ◇ (w ◇ u)) ◇ v
equation 56792 := x ◇ (y ◇ y) = (x ◇ (x ◇ x)) ◇ x
equation 56793 := x ◇ (y ◇ y) = (x ◇ (x ◇ x)) ◇ y
equation 56794 := x ◇ (y ◇ y) = (x ◇ (x ◇ x)) ◇ z
equation 56795 := x ◇ (y ◇ y) = (x ◇ (x ◇ y)) ◇ x
equation 56796 := x ◇ (y ◇ y) = (x ◇ (x ◇ y)) ◇ y
equation 56797 := x ◇ (y ◇ y) = (x ◇ (x ◇ y)) ◇ z
equation 56798 := x ◇ (y ◇ y) = (x ◇ (x ◇ z)) ◇ x
equation 56799 := x ◇ (y ◇ y) = (x ◇ (x ◇ z)) ◇ y
equation 56800 := x ◇ (y ◇ y) = (x ◇ (x ◇ z)) ◇ z
equation 56801 := x ◇ (y ◇ y) = (x ◇ (x ◇ z)) ◇ w
equation 56802 := x ◇ (y ◇ y) = (x ◇ (y ◇ x)) ◇ x
equation 56803 := x ◇ (y ◇ y) = (x ◇ (y ◇ x)) ◇ y
equation 56804 := x ◇ (y ◇ y) = (x ◇ (y ◇ x)) ◇ z
equation 56805 := x ◇ (y ◇ y) = (x ◇ (y ◇ y)) ◇ x
equation 56806 := x ◇ (y ◇ y) = (x ◇ (y ◇ y)) ◇ y
equation 56807 := x ◇ (y ◇ y) = (x ◇ (y ◇ y)) ◇ z
equation 56808 := x ◇ (y ◇ y) = (x ◇ (y ◇ z)) ◇ x
equation 56809 := x ◇ (y ◇ y) = (x ◇ (y ◇ z)) ◇ y
equation 56810 := x ◇ (y ◇ y) = (x ◇ (y ◇ z)) ◇ z
equation 56811 := x ◇ (y ◇ y) = (x ◇ (y ◇ z)) ◇ w
equation 56812 := x ◇ (y ◇ y) = (x ◇ (z ◇ x)) ◇ x
equation 56813 := x ◇ (y ◇ y) = (x ◇ (z ◇ x)) ◇ y
equation 56814 := x ◇ (y ◇ y) = (x ◇ (z ◇ x)) ◇ z
equation 56815 := x ◇ (y ◇ y) = (x ◇ (z ◇ x)) ◇ w
equation 56816 := x ◇ (y ◇ y) = (x ◇ (z ◇ y)) ◇ x
equation 56817 := x ◇ (y ◇ y) = (x ◇ (z ◇ y)) ◇ y
equation 56818 := x ◇ (y ◇ y) = (x ◇ (z ◇ y)) ◇ z
equation 56819 := x ◇ (y ◇ y) = (x ◇ (z ◇ y)) ◇ w
equation 56820 := x ◇ (y ◇ y) = (x ◇ (z ◇ z)) ◇ x
equation 56821 := x ◇ (y ◇ y) = (x ◇ (z ◇ z)) ◇ y
equation 56822 := x ◇ (y ◇ y) = (x ◇ (z ◇ z)) ◇ z
equation 56823 := x ◇ (y ◇ y) = (x ◇ (z ◇ z)) ◇ w
equation 56824 := x ◇ (y ◇ y) = (x ◇ (z ◇ w)) ◇ x
equation 56825 := x ◇ (y ◇ y) = (x ◇ (z ◇ w)) ◇ y
equation 56826 := x ◇ (y ◇ y) = (x ◇ (z ◇ w)) ◇ z
equation 56827 := x ◇ (y ◇ y) = (x ◇ (z ◇ w)) ◇ w
equation 56828 := x ◇ (y ◇ y) = (x ◇ (z ◇ w)) ◇ u
equation 56829 := x ◇ (y ◇ y) = (y ◇ (x ◇ x)) ◇ x
equation 56830 := x ◇ (y ◇ y) = (y ◇ (x ◇ x)) ◇ y
equation 56831 := x ◇ (y ◇ y) = (y ◇ (x ◇ x)) ◇ z
equation 56832 := x ◇ (y ◇ y) = (y ◇ (x ◇ y)) ◇ x
equation 56833 := x ◇ (y ◇ y) = (y ◇ (x ◇ y)) ◇ y
equation 56834 := x ◇ (y ◇ y) = (y ◇ (x ◇ y)) ◇ z
equation 56835 := x ◇ (y ◇ y) = (y ◇ (x ◇ z)) ◇ x
equation 56836 := x ◇ (y ◇ y) = (y ◇ (x ◇ z)) ◇ y
equation 56837 := x ◇ (y ◇ y) = (y ◇ (x ◇ z)) ◇ z
equation 56838 := x ◇ (y ◇ y) = (y ◇ (x ◇ z)) ◇ w
equation 56839 := x ◇ (y ◇ y) = (y ◇ (y ◇ x)) ◇ x
equation 56840 := x ◇ (y ◇ y) = (y ◇ (y ◇ x)) ◇ y
equation 56841 := x ◇ (y ◇ y) = (y ◇ (y ◇ x)) ◇ z
equation 56842 := x ◇ (y ◇ y) = (y ◇ (y ◇ y)) ◇ x
equation 56843 := x ◇ (y ◇ y) = (y ◇ (y ◇ y)) ◇ y
equation 56844 := x ◇ (y ◇ y) = (y ◇ (y ◇ y)) ◇ z
equation 56845 := x ◇ (y ◇ y) = (y ◇ (y ◇ z)) ◇ x
equation 56846 := x ◇ (y ◇ y) = (y ◇ (y ◇ z)) ◇ y
equation 56847 := x ◇ (y ◇ y) = (y ◇ (y ◇ z)) ◇ z
equation 56848 := x ◇ (y ◇ y) = (y ◇ (y ◇ z)) ◇ w
equation 56849 := x ◇ (y ◇ y) = (y ◇ (z ◇ x)) ◇ x
equation 56850 := x ◇ (y ◇ y) = (y ◇ (z ◇ x)) ◇ y
equation 56851 := x ◇ (y ◇ y) = (y ◇ (z ◇ x)) ◇ z
equation 56852 := x ◇ (y ◇ y) = (y ◇ (z ◇ x)) ◇ w
equation 56853 := x ◇ (y ◇ y) = (y ◇ (z ◇ y)) ◇ x
equation 56854 := x ◇ (y ◇ y) = (y ◇ (z ◇ y)) ◇ y
equation 56855 := x ◇ (y ◇ y) = (y ◇ (z ◇ y)) ◇ z
equation 56856 := x ◇ (y ◇ y) = (y ◇ (z ◇ y)) ◇ w
equation 56857 := x ◇ (y ◇ y) = (y ◇ (z ◇ z)) ◇ x
equation 56858 := x ◇ (y ◇ y) = (y ◇ (z ◇ z)) ◇ y
equation 56859 := x ◇ (y ◇ y) = (y ◇ (z ◇ z)) ◇ z
equation 56860 := x ◇ (y ◇ y) = (y ◇ (z ◇ z)) ◇ w
equation 56861 := x ◇ (y ◇ y) = (y ◇ (z ◇ w)) ◇ x
equation 56862 := x ◇ (y ◇ y) = (y ◇ (z ◇ w)) ◇ y
equation 56863 := x ◇ (y ◇ y) = (y ◇ (z ◇ w)) ◇ z
equation 56864 := x ◇ (y ◇ y) = (y ◇ (z ◇ w)) ◇ w
equation 56865 := x ◇ (y ◇ y) = (y ◇ (z ◇ w)) ◇ u
equation 56866 := x ◇ (y ◇ y) = (z ◇ (x ◇ x)) ◇ x
equation 56867 := x ◇ (y ◇ y) = (z ◇ (x ◇ x)) ◇ y
equation 56868 := x ◇ (y ◇ y) = (z ◇ (x ◇ x)) ◇ z
equation 56869 := x ◇ (y ◇ y) = (z ◇ (x ◇ x)) ◇ w
equation 56870 := x ◇ (y ◇ y) = (z ◇ (x ◇ y)) ◇ x
equation 56871 := x ◇ (y ◇ y) = (z ◇ (x ◇ y)) ◇ y
equation 56872 := x ◇ (y ◇ y) = (z ◇ (x ◇ y)) ◇ z
equation 56873 := x ◇ (y ◇ y) = (z ◇ (x ◇ y)) ◇ w
equation 56874 := x ◇ (y ◇ y) = (z ◇ (x ◇ z)) ◇ x
equation 56875 := x ◇ (y ◇ y) = (z ◇ (x ◇ z)) ◇ y
equation 56876 := x ◇ (y ◇ y) = (z ◇ (x ◇ z)) ◇ z
equation 56877 := x ◇ (y ◇ y) = (z ◇ (x ◇ z)) ◇ w
equation 56878 := x ◇ (y ◇ y) = (z ◇ (x ◇ w)) ◇ x
equation 56879 := x ◇ (y ◇ y) = (z ◇ (x ◇ w)) ◇ y
equation 56880 := x ◇ (y ◇ y) = (z ◇ (x ◇ w)) ◇ z
equation 56881 := x ◇ (y ◇ y) = (z ◇ (x ◇ w)) ◇ w
equation 56882 := x ◇ (y ◇ y) = (z ◇ (x ◇ w)) ◇ u
equation 56883 := x ◇ (y ◇ y) = (z ◇ (y ◇ x)) ◇ x
equation 56884 := x ◇ (y ◇ y) = (z ◇ (y ◇ x)) ◇ y
equation 56885 := x ◇ (y ◇ y) = (z ◇ (y ◇ x)) ◇ z
equation 56886 := x ◇ (y ◇ y) = (z ◇ (y ◇ x)) ◇ w
equation 56887 := x ◇ (y ◇ y) = (z ◇ (y ◇ y)) ◇ x
equation 56888 := x ◇ (y ◇ y) = (z ◇ (y ◇ y)) ◇ y
equation 56889 := x ◇ (y ◇ y) = (z ◇ (y ◇ y)) ◇ z
equation 56890 := x ◇ (y ◇ y) = (z ◇ (y ◇ y)) ◇ w
equation 56891 := x ◇ (y ◇ y) = (z ◇ (y ◇ z)) ◇ x
equation 56892 := x ◇ (y ◇ y) = (z ◇ (y ◇ z)) ◇ y
equation 56893 := x ◇ (y ◇ y) = (z ◇ (y ◇ z)) ◇ z
equation 56894 := x ◇ (y ◇ y) = (z ◇ (y ◇ z)) ◇ w
equation 56895 := x ◇ (y ◇ y) = (z ◇ (y ◇ w)) ◇ x
equation 56896 := x ◇ (y ◇ y) = (z ◇ (y ◇ w)) ◇ y
equation 56897 := x ◇ (y ◇ y) = (z ◇ (y ◇ w)) ◇ z
equation 56898 := x ◇ (y ◇ y) = (z ◇ (y ◇ w)) ◇ w
equation 56899 := x ◇ (y ◇ y) = (z ◇ (y ◇ w)) ◇ u
equation 56900 := x ◇ (y ◇ y) = (z ◇ (z ◇ x)) ◇ x
equation 56901 := x ◇ (y ◇ y) = (z ◇ (z ◇ x)) ◇ y
equation 56902 := x ◇ (y ◇ y) = (z ◇ (z ◇ x)) ◇ z
equation 56903 := x ◇ (y ◇ y) = (z ◇ (z ◇ x)) ◇ w
equation 56904 := x ◇ (y ◇ y) = (z ◇ (z ◇ y)) ◇ x
equation 56905 := x ◇ (y ◇ y) = (z ◇ (z ◇ y)) ◇ y
equation 56906 := x ◇ (y ◇ y) = (z ◇ (z ◇ y)) ◇ z
equation 56907 := x ◇ (y ◇ y) = (z ◇ (z ◇ y)) ◇ w
equation 56908 := x ◇ (y ◇ y) = (z ◇ (z ◇ z)) ◇ x
equation 56909 := x ◇ (y ◇ y) = (z ◇ (z ◇ z)) ◇ y
equation 56910 := x ◇ (y ◇ y) = (z ◇ (z ◇ z)) ◇ z
equation 56911 := x ◇ (y ◇ y) = (z ◇ (z ◇ z)) ◇ w
equation 56912 := x ◇ (y ◇ y) = (z ◇ (z ◇ w)) ◇ x
equation 56913 := x ◇ (y ◇ y) = (z ◇ (z ◇ w)) ◇ y
equation 56914 := x ◇ (y ◇ y) = (z ◇ (z ◇ w)) ◇ z
equation 56915 := x ◇ (y ◇ y) = (z ◇ (z ◇ w)) ◇ w
equation 56916 := x ◇ (y ◇ y) = (z ◇ (z ◇ w)) ◇ u
equation 56917 := x ◇ (y ◇ y) = (z ◇ (w ◇ x)) ◇ x
equation 56918 := x ◇ (y ◇ y) = (z ◇ (w ◇ x)) ◇ y
equation 56919 := x ◇ (y ◇ y) = (z ◇ (w ◇ x)) ◇ z
equation 56920 := x ◇ (y ◇ y) = (z ◇ (w ◇ x)) ◇ w
equation 56921 := x ◇ (y ◇ y) = (z ◇ (w ◇ x)) ◇ u
equation 56922 := x ◇ (y ◇ y) = (z ◇ (w ◇ y)) ◇ x
equation 56923 := x ◇ (y ◇ y) = (z ◇ (w ◇ y)) ◇ y
equation 56924 := x ◇ (y ◇ y) = (z ◇ (w ◇ y)) ◇ z
equation 56925 := x ◇ (y ◇ y) = (z ◇ (w ◇ y)) ◇ w
equation 56926 := x ◇ (y ◇ y) = (z ◇ (w ◇ y)) ◇ u
equation 56927 := x ◇ (y ◇ y) = (z ◇ (w ◇ z)) ◇ x
equation 56928 := x ◇ (y ◇ y) = (z ◇ (w ◇ z)) ◇ y
equation 56929 := x ◇ (y ◇ y) = (z ◇ (w ◇ z)) ◇ z
equation 56930 := x ◇ (y ◇ y) = (z ◇ (w ◇ z)) ◇ w
equation 56931 := x ◇ (y ◇ y) = (z ◇ (w ◇ z)) ◇ u
equation 56932 := x ◇ (y ◇ y) = (z ◇ (w ◇ w)) ◇ x
equation 56933 := x ◇ (y ◇ y) = (z ◇ (w ◇ w)) ◇ y
equation 56934 := x ◇ (y ◇ y) = (z ◇ (w ◇ w)) ◇ z
equation 56935 := x ◇ (y ◇ y) = (z ◇ (w ◇ w)) ◇ w
equation 56936 := x ◇ (y ◇ y) = (z ◇ (w ◇ w)) ◇ u
equation 56937 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ x
equation 56938 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ y
equation 56939 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ z
equation 56940 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ w
equation 56941 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ u
equation 56942 := x ◇ (y ◇ y) = (z ◇ (w ◇ u)) ◇ v
equation 56943 := x ◇ (y ◇ z) = (x ◇ (x ◇ x)) ◇ x
equation 56944 := x ◇ (y ◇ z) = (x ◇ (x ◇ x)) ◇ y
equation 56945 := x ◇ (y ◇ z) = (x ◇ (x ◇ x)) ◇ z
equation 56946 := x ◇ (y ◇ z) = (x ◇ (x ◇ x)) ◇ w
equation 56947 := x ◇ (y ◇ z) = (x ◇ (x ◇ y)) ◇ x
equation 56948 := x ◇ (y ◇ z) = (x ◇ (x ◇ y)) ◇ y
equation 56949 := x ◇ (y ◇ z) = (x ◇ (x ◇ y)) ◇ z
equation 56950 := x ◇ (y ◇ z) = (x ◇ (x ◇ y)) ◇ w
equation 56951 := x ◇ (y ◇ z) = (x ◇ (x ◇ z)) ◇ x
equation 56952 := x ◇ (y ◇ z) = (x ◇ (x ◇ z)) ◇ y
equation 56953 := x ◇ (y ◇ z) = (x ◇ (x ◇ z)) ◇ z
equation 56954 := x ◇ (y ◇ z) = (x ◇ (x ◇ z)) ◇ w
equation 56955 := x ◇ (y ◇ z) = (x ◇ (x ◇ w)) ◇ x
equation 56956 := x ◇ (y ◇ z) = (x ◇ (x ◇ w)) ◇ y
equation 56957 := x ◇ (y ◇ z) = (x ◇ (x ◇ w)) ◇ z
equation 56958 := x ◇ (y ◇ z) = (x ◇ (x ◇ w)) ◇ w
equation 56959 := x ◇ (y ◇ z) = (x ◇ (x ◇ w)) ◇ u
equation 56960 := x ◇ (y ◇ z) = (x ◇ (y ◇ x)) ◇ x
equation 56961 := x ◇ (y ◇ z) = (x ◇ (y ◇ x)) ◇ y
equation 56962 := x ◇ (y ◇ z) = (x ◇ (y ◇ x)) ◇ z
equation 56963 := x ◇ (y ◇ z) = (x ◇ (y ◇ x)) ◇ w
equation 56964 := x ◇ (y ◇ z) = (x ◇ (y ◇ y)) ◇ x
equation 56965 := x ◇ (y ◇ z) = (x ◇ (y ◇ y)) ◇ y
equation 56966 := x ◇ (y ◇ z) = (x ◇ (y ◇ y)) ◇ z
equation 56967 := x ◇ (y ◇ z) = (x ◇ (y ◇ y)) ◇ w
equation 56968 := x ◇ (y ◇ z) = (x ◇ (y ◇ z)) ◇ x
equation 56969 := x ◇ (y ◇ z) = (x ◇ (y ◇ z)) ◇ y
equation 56970 := x ◇ (y ◇ z) = (x ◇ (y ◇ z)) ◇ z
equation 56971 := x ◇ (y ◇ z) = (x ◇ (y ◇ z)) ◇ w
equation 56972 := x ◇ (y ◇ z) = (x ◇ (y ◇ w)) ◇ x
equation 56973 := x ◇ (y ◇ z) = (x ◇ (y ◇ w)) ◇ y
equation 56974 := x ◇ (y ◇ z) = (x ◇ (y ◇ w)) ◇ z
equation 56975 := x ◇ (y ◇ z) = (x ◇ (y ◇ w)) ◇ w
equation 56976 := x ◇ (y ◇ z) = (x ◇ (y ◇ w)) ◇ u
equation 56977 := x ◇ (y ◇ z) = (x ◇ (z ◇ x)) ◇ x
equation 56978 := x ◇ (y ◇ z) = (x ◇ (z ◇ x)) ◇ y
equation 56979 := x ◇ (y ◇ z) = (x ◇ (z ◇ x)) ◇ z
equation 56980 := x ◇ (y ◇ z) = (x ◇ (z ◇ x)) ◇ w
equation 56981 := x ◇ (y ◇ z) = (x ◇ (z ◇ y)) ◇ x
equation 56982 := x ◇ (y ◇ z) = (x ◇ (z ◇ y)) ◇ y
equation 56983 := x ◇ (y ◇ z) = (x ◇ (z ◇ y)) ◇ z
equation 56984 := x ◇ (y ◇ z) = (x ◇ (z ◇ y)) ◇ w
equation 56985 := x ◇ (y ◇ z) = (x ◇ (z ◇ z)) ◇ x
equation 56986 := x ◇ (y ◇ z) = (x ◇ (z ◇ z)) ◇ y
equation 56987 := x ◇ (y ◇ z) = (x ◇ (z ◇ z)) ◇ z
equation 56988 := x ◇ (y ◇ z) = (x ◇ (z ◇ z)) ◇ w
equation 56989 := x ◇ (y ◇ z) = (x ◇ (z ◇ w)) ◇ x
equation 56990 := x ◇ (y ◇ z) = (x ◇ (z ◇ w)) ◇ y
equation 56991 := x ◇ (y ◇ z) = (x ◇ (z ◇ w)) ◇ z
equation 56992 := x ◇ (y ◇ z) = (x ◇ (z ◇ w)) ◇ w
equation 56993 := x ◇ (y ◇ z) = (x ◇ (z ◇ w)) ◇ u
equation 56994 := x ◇ (y ◇ z) = (x ◇ (w ◇ x)) ◇ x
equation 56995 := x ◇ (y ◇ z) = (x ◇ (w ◇ x)) ◇ y
equation 56996 := x ◇ (y ◇ z) = (x ◇ (w ◇ x)) ◇ z
equation 56997 := x ◇ (y ◇ z) = (x ◇ (w ◇ x)) ◇ w
equation 56998 := x ◇ (y ◇ z) = (x ◇ (w ◇ x)) ◇ u
equation 56999 := x ◇ (y ◇ z) = (x ◇ (w ◇ y)) ◇ x
